In [35]:
pathtosave = './ticker_data/ticker_data_2021-09-25_processed/'

In [19]:
import pandas as pd
import numpy as np
import os
path = './ticker_data/ticker_data_2021-09-25 - Copy/'
df = pd.read_csv('./ticker_data/ticker_data_2021-09-25 - Copy/AAL_ended_2021-09-25.csv')


print(df)

maxall = df['High'].max()
minall = df['Low'].min()
df_csv = pd.read_csv('./ticker_data/ticker_data_2021-09-25 - Copy/AAL_ended_2021-09-25.csv')

threshold = list(np.arange(.1,1.1,.1))
print('threshold:',threshold)
diff = maxall - minall

em = [] #to contain all threshold values; markup from min to max by 10%
em.append('A')
em.append(df['Date'].to_list()[0])

em.append(df_csv['Adj Close'].to_list()[-1])
em.append(minall)
em.append(maxall)
em.append(diff*.1)

for threshold_ in threshold:
    value = threshold_ * diff
    print('value:', value)
    value += minall
    em.append(value)
df_em = pd.DataFrame(em).T

df_basic = pd.DataFrame()
df = pd.concat([df_basic, df_em], axis=0)



df.columns = ['stock','start_date','current_price','minall','maxall','each_markup','markup_10','markup_20','markup_30','markup_40',
                    'markup_50','markup_60','markup_70','markup_80','markup_90','markup_100']
df1 = df.copy()
print('df1:\n', df1)

            Date       Open       High        Low      Close  Adj Close  \
0     2005-09-27  21.049999  21.400000  19.100000  19.299999  18.194910
1     2005-09-28  19.299999  20.530001  19.200001  20.500000  19.326199
2     2005-09-29  20.400000  20.580000  20.100000  20.209999  19.052801
3     2005-09-30  20.260000  21.049999  20.180000  21.010000  19.806999
4     2005-10-03  20.900000  21.750000  20.900000  21.500000  20.268938
...          ...        ...        ...        ...        ...        ...
4008  2021-08-30  20.290001  20.299999  19.469999  19.510000  19.510000
4009  2021-08-31  19.469999  20.020000  19.360001  19.940001  19.940001
4010  2021-09-01  20.010000  20.100000  19.530001  19.639999  19.639999
4011  2021-09-02  19.730000  19.980000  19.480000  19.760000  19.760000
4012  2021-09-03  19.680000  19.930000  19.320000  19.370001  19.370001

          Volume
0         961200
1        5747900
2        1078200
3        3123300
4        1057900
...          ...
4008  2409430000
4009  2496200000
4010  2084320000
4011  2020910000
4012  2031190000

[4013 rows x 7 columns]
threshold: [0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6, 0.7000000000000001, 0.8, 0.9, 1.0]
value: 6.182000041007996
value: 12.364000082015991
value: 18.54600012302399
value: 24.728000164031982
value: 30.910000205039978
value: 37.092000246047974
value: 43.274000287055976
value: 49.456000328063965
value: 55.63800036907196
value: 61.820000410079956
df1:
   stock  start_date current_price minall maxall each_markup markup_10  \
0     A  2005-09-27         19.37   1.45  63.27       6.182     7.632

  markup_20 markup_30 markup_40 markup_50 markup_60 markup_70 markup_80  \
0    13.814    19.996    26.178     32.36    38.542    44.724    50.906

  markup_90 markup_100
0    57.088      63.27

In [20]:
print(df)

  stock  start_date current_price minall maxall each_markup markup_10  \
0     A  2005-09-27         19.37   1.45  63.27       6.182     7.632

  markup_20 markup_30 markup_40 markup_50 markup_60 markup_70 markup_80  \
0    13.814    19.996    26.178     32.36    38.542    44.724    50.906

  markup_90 markup_100
0    57.088      63.27

In [21]:
#get 20%, 40%, 60%, 80%, 100% markup from minimum

def get_entire_df(df, ticker):
    maxall = df['High'].max()
    minall = df['Low'].min()
#     df_csv = pd.read_csv('C:/Users/malco/Desktop/Server Data 2/all stock price/a.csv')

    threshold = list(np.arange(.1,1.1,.1))
#     print('threshold:',threshold)
    diff = maxall - minall

    em = [] #to contain all threshold values; markup from min to max by 10%
    em.append(ticker)
    
    print('tolistdate:',df['Date'])
    em.append(df['Date'].to_list()[0])
    em.append(df['Adj Close'].to_list()[-1])
    em.append(minall)
    em.append(maxall)
    em.append(diff*.1)

    for threshold_ in threshold:
        value = threshold_ * diff
#         print('value:', value)
        value += minall
        em.append(value)
    df_em = pd.DataFrame(em).T

    df_basic = pd.DataFrame()
    df = pd.concat([df_basic, df_em], axis=0)



    df.columns = ['stock','start_date','current_price','minall','maxall','each_markup','markup_10','markup_20','markup_30','markup_40',
                    'markup_50','markup_60','markup_70','markup_80','markup_90','markup_100']
    print(df)
    # df.index = ['a']
    
    return df

In [22]:
#create max column
for i in os.listdir(path)[1:]:#shorten
    
    ticker = i.split('.')[0]
    df_csv = pd.read_csv(path+i)
    print(path+i)
    print(df_csv)
    df_each = get_entire_df(df_csv,ticker)
    print(df_each)
    df1 = pd.concat([df1, df_each],axis=0, sort = False)
    
print(df1)

./ticker_data/ticker_data_2021-09-25 - Copy/AAME_ended_2021-09-25.csv
            Date    Open    High     Low   Close  Adj Close    Volume
0     1999-12-31  2.3125  2.4375  2.2500  2.3125   2.125906     15500
1     2000-01-03  2.3750  2.4375  2.2500  2.3125   2.125906      5100
2     2000-01-04  2.3750  2.3750  2.3750  2.3750   2.183363       100
3     2000-01-05  2.3125  2.4375  2.3125  2.4375   2.240821      7800
4     2000-01-06  2.3125  2.3125  2.3125  2.3125   2.125906       500
...          ...     ...     ...     ...     ...        ...       ...
5118  2021-08-30  3.8600  3.9200  3.7600  3.8700   3.870000   3330000
5119  2021-08-31  3.8700  4.0700  3.8100  3.9700   3.970000   7940000
5120  2021-09-01  4.0200  4.3500  3.9600  4.3500   4.350000  11510000
5121  2021-09-02  4.3400  4.3900  4.1100  4.1200   4.120000   8000000
5122  2021-09-03  4.1200  4.1600  3.9900  3.9900   3.990000   5440000

[5123 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5118    2021-08-30
5119    2021-08-31
5120    2021-09-01
5121    2021-09-02
5122    2021-09-03
Name: Date, Length: 5123, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AAME_ended_2021-09-25  1999-12-31          3.99   0.45  15.97       1.552

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.002     3.554     5.106     6.658      8.21     9.762    11.314

  markup_80 markup_90 markup_100
0    12.866    14.418      15.97
                   stock  start_date current_price minall maxall each_markup  \
0  AAME_ended_2021-09-25  1999-12-31          3.99   0.45  15.97       1.552

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.002     3.554     5.106     6.658      8.21     9.762    11.314

  markup_80 markup_90 markup_100
0    12.866    14.418      15.97
./ticker_data/ticker_data_2021-09-25 - Copy/AAOI_ended_2021-09-25.csv
            Date   Open   High     Low  Close  Adj Close    Volume
0     2013-09-26  10.00  10.09   9.370   9.96       9.96    946000
1     2013-09-27  10.44  10.44  10.000  10.10      10.10    253300
2     2013-09-30  10.00  10.18   9.710  10.00      10.00     84900
3     2013-10-01   9.95  10.02   9.920  10.00      10.00     74500
4     2013-10-02   9.99  10.00   9.890   9.97       9.97     94000
...          ...    ...    ...     ...    ...        ...       ...
1994  2021-08-30   7.30   7.36   7.140   7.28       7.28  31580000
1995  2021-08-31   7.26   7.41   7.150   7.33       7.33  32830000
1996  2021-09-01   7.36   7.70   7.265   7.63       7.63  60510000
1997  2021-09-02   7.62   7.84   7.600   7.77       7.77  41150000
1998  2021-09-03   7.77   7.92   7.650   7.72       7.72  33080000

[1999 rows x 7 columns]
tolistdate: 0       2013-09-26
1       2013-09-27
2       2013-09-30
3       2013-10-01
4       2013-10-02
           ...
1994    2021-08-30
1995    2021-08-31
1996    2021-09-01
1997    2021-09-02
1998    2021-09-03
Name: Date, Length: 1999, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AAOI_ended_2021-09-25  2013-09-26          7.72      5  103.41       9.841

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    14.841    24.682    34.523    44.364    54.205    64.046    73.887

  markup_80 markup_90 markup_100
0    83.728    93.569     103.41
                   stock  start_date current_price minall  maxall each_markup  \
0  AAOI_ended_2021-09-25  2013-09-26          7.72      5  103.41       9.841

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    14.841    24.682    34.523    44.364    54.205    64.046    73.887

  markup_80 markup_90 markup_100
0    83.728    93.569     103.41
./ticker_data/ticker_data_2021-09-25 - Copy/AAON_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   1.251029   1.262003   1.251029   1.262003   1.062155
1     2000-01-03   1.294924   1.294924   1.185185   1.185185   0.997502
2     2000-01-04   1.283951   1.316872   1.196159   1.234568   1.039065
3     2000-01-05   1.262003   1.262003   1.218107   1.245542   1.048301
4     2000-01-06   1.283951   1.294924   1.240055   1.251029   1.052919
...          ...        ...        ...        ...        ...        ...
5449  2021-08-30  69.089996  69.339996  68.470001  69.199997  69.199997
5450  2021-08-31  69.000000  69.000000  68.019997  68.110001  68.110001
5451  2021-09-01  68.250000  68.489998  66.500000  67.489998  67.489998
5452  2021-09-02  67.680000  68.360001  67.519997  68.160004  68.160004
5453  2021-09-03  67.889999  68.440002  67.000000  67.209999  67.209999

        Volume
0        38400
1       683700
2       665100
3      4802500
4      1009800
...        ...
5449  16270000
5450  11620000
5451  11540000
5452   8830000
5453   9760000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price   minall maxall  \
0  AAON_ended_2021-09-25  1999-12-31         67.21  1.18519  81.25

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     8.00648   9.19167   17.1981   25.2046   33.2111   41.2176   49.2241

  markup_70 markup_80 markup_90 markup_100
0   57.2306    65.237   73.2435      81.25
                   stock  start_date current_price   minall maxall  \
0  AAON_ended_2021-09-25  1999-12-31         67.21  1.18519  81.25

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     8.00648   9.19167   17.1981   25.2046   33.2111   41.2176   49.2241

  markup_70 markup_80 markup_90 markup_100
0   57.2306    65.237   73.2435      81.25
./ticker_data/ticker_data_2021-09-25 - Copy/AAPL_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31    0.901228    0.918527    0.888393    0.917969    0.789364
1     2000-01-03    0.936384    1.004464    0.907924    0.999442    0.859423
2     2000-01-04    0.966518    0.987723    0.903460    0.915179    0.786965
3     2000-01-05    0.926339    0.987165    0.919643    0.928571    0.798482
4     2000-01-06    0.947545    0.955357    0.848214    0.848214    0.729382
...          ...         ...         ...         ...         ...         ...
5450  2021-08-30  149.000000  153.490005  148.610001  153.119995  153.119995
5451  2021-08-31  152.660004  152.800003  151.289993  151.830002  151.830002
5452  2021-09-01  152.830002  154.979996  152.339996  152.509995  152.509995
5453  2021-09-02  153.869995  154.720001  152.399994  153.649994  153.649994
5454  2021-09-03  153.759995  154.630005  153.089996  154.300003  154.300003

          Volume
0      163811200
1      535796800
2      512377600
3      778321600
4      767972800
...          ...
5450  9095670000
5451  8632380000
5452  8031370000
5453  7117130000
5454  5780870000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price    minall  maxall  \
0  AAPL_ended_2021-09-25  1999-12-31         154.3  0.227143  154.98

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     15.4753   15.7024   31.1777    46.653   62.1283   77.6036   93.0789

  markup_70 markup_80 markup_90 markup_100
0   108.554   124.029   139.505     154.98
                   stock  start_date current_price    minall  maxall  \
0  AAPL_ended_2021-09-25  1999-12-31         154.3  0.227143  154.98

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     15.4753   15.7024   31.1777    46.653   62.1283   77.6036   93.0789

  markup_70 markup_80 markup_90 markup_100
0   108.554   124.029   139.505     154.98
./ticker_data/ticker_data_2021-09-25 - Copy/AAWW_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2005-11-09  30.000000  31.000000  30.000000  31.000000  31.000000
1     2005-11-10  30.000000  31.000000  30.000000  31.000000  31.000000
2     2005-11-11  30.000000  31.000000  30.000000  31.000000  31.000000
3     2005-11-14  30.200001  31.500000  30.200001  31.000000  31.000000
4     2005-11-15  30.250000  31.000000  30.000000  31.000000  31.000000
...          ...        ...        ...        ...        ...        ...
3975  2021-08-30  73.989998  74.089996  72.820000  73.480003  73.480003
3976  2021-08-31  73.639999  73.889999  72.940002  73.169998  73.169998
3977  2021-09-01  73.379997  73.699997  72.309998  73.550003  73.550003
3978  2021-09-02  73.750000  74.260002  73.410004  73.900002  73.900002
3979  2021-09-03  73.669998  74.290001  73.010002  73.570000  73.570000

        Volume
0       130500
1        17700
2         3700
3         5400
4         6200
...        ...
3975  27160000
3976  36850000
3977  35950000
3978  26290000
3979  23950000

[3980 rows x 7 columns]
tolistdate: 0       2005-11-09
1       2005-11-10
2       2005-11-11
3       2005-11-14
4       2005-11-15
           ...
3975    2021-08-30
3976    2021-08-31
3977    2021-09-01
3978    2021-09-02
3979    2021-09-03
Name: Date, Length: 3980, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AAWW_ended_2021-09-25  2005-11-09         73.57   8.99  78.45       6.946

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.936    22.882    29.828    36.774     43.72    50.666    57.612

  markup_80 markup_90 markup_100
0    64.558    71.504      78.45
                   stock  start_date current_price minall maxall each_markup  \
0  AAWW_ended_2021-09-25  2005-11-09         73.57   8.99  78.45       6.946

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.936    22.882    29.828    36.774     43.72    50.666    57.612

  markup_80 markup_90 markup_100
0    64.558    71.504      78.45
./ticker_data/ticker_data_2021-09-25 - Copy/ABCB_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   8.713251   8.713251   8.611934   8.611934   5.810786
1     2000-01-03   8.865227   8.915885   8.409301   8.713251   5.879149
2     2000-01-04   8.510617   8.611934   8.510617   8.611934   5.810786
3     2000-01-05   8.510617   8.611934   8.510617   8.611934   5.810786
4     2000-01-06   8.662593   8.915885   8.611934   8.611934   5.810786
...          ...        ...        ...        ...        ...        ...
5434  2021-08-30  50.000000  50.209999  48.610001  48.689999  48.689999
5435  2021-08-31  48.380001  50.110001  48.380001  49.240002  49.240002
5436  2021-09-01  49.330002  49.330002  48.169998  48.759998  48.759998
5437  2021-09-02  48.169998  49.180000  47.750000  48.240002  48.240002
5438  2021-09-03  48.549999  49.639999  47.860001  48.029999  48.029999

        Volume
0          700
1        58200
2         7000
3         8400
4         1500
...        ...
5434  21760000
5435  29060000
5436  21320000
5437  31820000
5438  24610000

[5439 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5434    2021-08-30
5435    2021-08-31
5436    2021-09-01
5437    2021-09-02
5438    2021-09-03
Name: Date, Length: 5439, dtype: object
                   stock  start_date current_price   minall maxall  \
0  ABCB_ended_2021-09-25  1999-12-31         48.03  3.35561  59.85

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     5.64944   9.00505   14.6545   20.3039   25.9534   31.6028   37.2522

  markup_70 markup_80 markup_90 markup_100
0   42.9017   48.5511   54.2006      59.85
                   stock  start_date current_price   minall maxall  \
0  ABCB_ended_2021-09-25  1999-12-31         48.03  3.35561  59.85

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     5.64944   9.00505   14.6545   20.3039   25.9534   31.6028   37.2522

  markup_70 markup_80 markup_90 markup_100
0   42.9017   48.5511   54.2006      59.85
./ticker_data/ticker_data_2021-09-25 - Copy/ABCL_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-12-11  61.000000  71.910004  48.980000  58.900002  58.900002
1    2020-12-14  56.925999  60.691002  50.000000  50.009998  50.009998
2    2020-12-15  50.810001  52.209999  45.259998  46.990002  46.990002
3    2020-12-16  47.130001  49.730000  42.150002  47.529999  47.529999
4    2020-12-17  48.540001  50.500000  48.139999  48.599998  48.599998
..          ...        ...        ...        ...        ...        ...
179  2021-08-30  17.860001  17.990000  16.900000  17.350000  17.350000
180  2021-08-31  17.500000  17.605000  16.620001  16.780001  16.780001
181  2021-09-01  16.780001  17.410000  16.545000  16.930000  16.930000
182  2021-09-02  17.139999  17.680000  16.780001  17.549999  17.549999
183  2021-09-03  17.660999  19.120001  17.440001  18.740000  18.740000

        Volume
0      9249200
1      1485900
2      3958000
3      1688700
4       636300
..         ...
179  103180000
180  170530000
181  156760000
182  139610000
183  300340000

[184 rows x 7 columns]
tolistdate: 0      2020-12-11
1      2020-12-14
2      2020-12-15
3      2020-12-16
4      2020-12-17
          ...
179    2021-08-30
180    2021-08-31
181    2021-09-01
182    2021-09-02
183    2021-09-03
Name: Date, Length: 184, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ABCL_ended_2021-09-25  2020-12-11         18.74  14.51  71.91        5.74

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     20.25     25.99     31.73     37.47     43.21     48.95     54.69

  markup_80 markup_90 markup_100
0     60.43     66.17      71.91
                   stock  start_date current_price minall maxall each_markup  \
0  ABCL_ended_2021-09-25  2020-12-11         18.74  14.51  71.91        5.74

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     20.25     25.99     31.73     37.47     43.21     48.95     54.69

  markup_80 markup_90 markup_100
0     60.43     66.17      71.91
./ticker_data/ticker_data_2021-09-25 - Copy/ABCM_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-10-22  18.000000  20.809999  17.709999  19.750000  19.750000
1    2020-10-23  19.000000  19.690001  18.670000  18.900000  18.900000
2    2020-10-26  18.900000  19.450001  18.629999  19.400000  19.400000
3    2020-10-27  19.240000  19.799999  19.000000  19.459999  19.459999
4    2020-10-28  19.400000  19.639999  18.969999  19.110001  19.110001
..          ...        ...        ...        ...        ...        ...
213  2021-08-30  20.600000  21.090000  20.600000  20.940001  20.940001
214  2021-08-31  21.020000  21.298000  21.020000  21.150000  21.150000
215  2021-09-01  21.219999  21.440001  21.139999  21.280001  21.280001
216  2021-09-02  21.400000  21.650000  21.219999  21.540001  21.540001
217  2021-09-03  21.400000  21.510000  21.120001  21.350000  21.350000

      Volume
0    2471300
1    1545100
2     203000
3     296900
4     213600
..       ...
213  6590000
214  4240000
215  2700000
216  3150000
217  4420000

[218 rows x 7 columns]
tolistdate: 0      2020-10-22
1      2020-10-23
2      2020-10-26
3      2020-10-27
4      2020-10-28
          ...
213    2021-08-30
214    2021-08-31
215    2021-09-01
216    2021-09-02
217    2021-09-03
Name: Date, Length: 218, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ABCM_ended_2021-09-25  2020-10-22         21.35  17.14  24.69       0.755

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.895     18.65    19.405     20.16    20.915     21.67    22.425

  markup_80 markup_90 markup_100
0     23.18    23.935      24.69
                   stock  start_date current_price minall maxall each_markup  \
0  ABCM_ended_2021-09-25  2020-10-22         21.35  17.14  24.69       0.755

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.895     18.65    19.405     20.16    20.915     21.67    22.425

  markup_80 markup_90 markup_100
0     23.18    23.935      24.69
./ticker_data/ticker_data_2021-09-25 - Copy/ABEO_ended_2021-09-25.csv
            Date    Open    High     Low   Close   Adj Close    Volume
0     1999-12-31  406.25  500.00  406.25  500.00  458.385986         0
1     2000-01-03  437.50  437.50  437.50  437.50  401.087738         0
2     2000-01-04  406.25  437.50  406.25  406.25  372.438599         0
3     2000-01-05  406.25  406.25  406.25  406.25  372.438599         0
4     2000-01-06  406.25  468.75  375.00  468.75  429.736847         0
...          ...     ...     ...     ...     ...         ...       ...
5362  2021-08-30    1.29    1.32    1.27    1.28    1.280000  36300000
5363  2021-08-31    1.30    1.33    1.29    1.32    1.320000  44400000
5364  2021-09-01    1.29    1.33    1.28    1.29    1.290000  44970000
5365  2021-09-02    1.28    1.36    1.27    1.35    1.350000  63860000
5366  2021-09-03    1.36    1.36    1.30    1.35    1.350000  22470000

[5367 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5362    2021-08-30
5363    2021-08-31
5364    2021-09-01
5365    2021-09-02
5366    2021-09-03
Name: Date, Length: 5367, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ABEO_ended_2021-09-25  1999-12-31          1.35   0.99   3750     374.901

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   375.891   750.792   1125.69   1500.59    1875.5    2250.4    2625.3

  markup_80 markup_90 markup_100
0    3000.2    3375.1       3750
                   stock  start_date current_price minall maxall each_markup  \
0  ABEO_ended_2021-09-25  1999-12-31          1.35   0.99   3750     374.901

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   375.891   750.792   1125.69   1500.59    1875.5    2250.4    2625.3

  markup_80 markup_90 markup_100

0    3000.2    3375.1       3750
./ticker_data/ticker_data_2021-09-25 - Copy/ABGI_ended_2021-09-25.csv
           Date   Open    High    Low  Close  Adj Close   Volume
0    2021-02-17  10.41  10.500  10.23  10.34      10.34  4620500
1    2021-02-18  10.31  10.380  10.27  10.33      10.33   646900
2    2021-02-19  10.39  10.500  10.33  10.40      10.40   130800
3    2021-02-22  10.54  10.690  10.43  10.45      10.45   246800
4    2021-02-23  10.38  10.405  10.25  10.30      10.30   283500
..          ...    ...     ...    ...    ...        ...      ...
130  2021-08-30   9.62   9.620   9.62   9.62       9.62    30000
131  2021-08-31   9.68   9.680   9.62   9.68       9.68    50000
132  2021-09-01   9.62   9.680   9.62   9.68       9.68    50000
133  2021-09-02   9.68   9.680   9.68   9.68       9.68   200000
134  2021-09-03   9.68   9.680   9.68   9.68       9.68        0

[135 rows x 7 columns]
tolistdate: 0      2021-02-17
1      2021-02-18
2      2021-02-19
3      2021-02-22
4      2021-02-23
          ...
130    2021-08-30
131    2021-08-31
132    2021-09-01
133    2021-09-02
134    2021-09-03
Name: Date, Length: 135, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ABGI_ended_2021-09-25  2021-02-17          9.68   9.61  10.69       0.108

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.718     9.826     9.934    10.042     10.15    10.258    10.366

  markup_80 markup_90 markup_100
0    10.474    10.582      10.69
                   stock  start_date current_price minall maxall each_markup  \
0  ABGI_ended_2021-09-25  2021-02-17          9.68   9.61  10.69       0.108

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.718     9.826     9.934    10.042     10.15    10.258    10.366

  markup_80 markup_90 markup_100
0    10.474    10.582      10.69
./ticker_data/ticker_data_2021-09-25 - Copy/ABIO_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  802305.00  816480.00  756945.00  771120.00  771120.00
1     2000-01-03  802305.00  805140.00  564165.00  708750.00  708750.00
2     2000-01-04  657720.00  779625.00  646380.00  725760.00  725760.00
3     2000-01-05  742770.00  768285.00  683235.00  754110.00  754110.00
4     2000-01-06  824985.00  884520.00  788130.00  884520.00  884520.00
...          ...        ...        ...        ...        ...        ...
5435  2021-08-30       3.09       3.09       3.00       3.05       3.05
5436  2021-08-31       3.03       3.10       3.02       3.09       3.09
5437  2021-09-01       3.10       3.10       3.05       3.06       3.06
5438  2021-09-02       3.05       3.13       3.00       3.12       3.12
5439  2021-09-03       3.11       3.17       3.06       3.10       3.10

        Volume
0            0
1            0
2            0
3            0
4            0
...        ...
5435   3850000
5436   9350000
5437   2750000
5438  14600000
5439  11420000

[5440 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5435    2021-08-30
5436    2021-08-31
5437    2021-09-01
5438    2021-09-02
5439    2021-09-03
Name: Date, Length: 5440, dtype: object
                   stock  start_date current_price minall       maxall  \
0  ABIO_ended_2021-09-25  1999-12-31           3.1   2.21  6.32772e+06

  each_markup markup_10    markup_20    markup_30    markup_40    markup_50  \
0      632772    632774  1.26555e+06  1.89832e+06  2.53109e+06  3.16386e+06

     markup_60   markup_70    markup_80    markup_90   markup_100
0  3.79663e+06  4.4294e+06  5.06218e+06  5.69495e+06  6.32772e+06
                   stock  start_date current_price minall       maxall  \
0  ABIO_ended_2021-09-25  1999-12-31           3.1   2.21  6.32772e+06

  each_markup markup_10    markup_20    markup_30    markup_40    markup_50  \
0      632772    632774  1.26555e+06  1.89832e+06  2.53109e+06  3.16386e+06

     markup_60   markup_70    markup_80    markup_90   markup_100
0  3.79663e+06  4.4294e+06  5.06218e+06  5.69495e+06  6.32772e+06
./ticker_data/ticker_data_2021-09-25 - Copy/ABMD_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31   19.125000   19.125000   16.500000   18.375000   18.375000
1     2000-01-03   18.515625   18.656250   18.250000   18.250000   18.250000
2     2000-01-04   18.500000   18.500000   17.000000   17.812500   17.812500
3     2000-01-05   17.062500   18.187500   16.937500   18.000000   18.000000
4     2000-01-06   17.625000   18.062500   17.625000   18.031250   18.031250
...          ...         ...         ...         ...         ...         ...
5449  2021-08-30  360.679993  364.489990  359.809998  360.959991  360.959991
5450  2021-08-31  362.920013  364.239990  359.820007  363.959991  363.959991
5451  2021-09-01  365.390015  367.619995  361.929993  363.269989  363.269989
5452  2021-09-02  366.170013  374.200012  365.600006  369.829987  369.829987
5453  2021-09-03  368.269989  373.109985  363.410004  372.690002  372.690002

        Volume
0       115800
1       185600
2        34400
3       122800
4        84200
...        ...
5449  11200000
5450  22510000
5451  17150000
5452  17830000
5453  13780000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ABMD_ended_2021-09-25  1999-12-31        372.69   2.35  459.75       45.74

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     48.09     93.83    139.57    185.31    231.05    276.79    322.53

  markup_80 markup_90 markup_100
0    368.27    414.01     459.75
                   stock  start_date current_price minall  maxall each_markup  \
0  ABMD_ended_2021-09-25  1999-12-31        372.69   2.35  459.75       45.74

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     48.09     93.83    139.57    185.31    231.05    276.79    322.53

  markup_80 markup_90 markup_100
0    368.27    414.01     459.75
./ticker_data/ticker_data_2021-09-25 - Copy/ABNB_ended_2021-09-25.csv
           Date        Open        High         Low       Close   Adj Close  \
0    2020-12-10  146.000000  165.000000  141.250000  144.710007  144.710007
1    2020-12-11  146.550003  151.500000  135.100006  139.250000  139.250000
2    2020-12-14  135.000000  135.300003  125.160004  130.000000  130.000000
3    2020-12-15  126.690002  127.599998  121.500000  124.800003  124.800003
4    2020-12-16  125.830002  142.000000  124.910004  137.990005  137.990005
..          ...         ...         ...         ...         ...         ...
180  2021-08-30  154.410004  157.490005  151.919998  156.020004  156.020004
181  2021-08-31  155.940002  158.149994  153.580002  154.990005  154.990005
182  2021-09-01  154.839996  158.639999  154.289993  156.589996  156.589996
183  2021-09-02  156.500000  159.460007  156.500000  157.199997  157.199997
184  2021-09-03  158.050003  160.639999  157.199997  158.000000  158.000000

        Volume
0     70447500
1     26980800
2     16930100
3     10914400
4     20409600
..         ...
180  396870000
181  739720000
182  432470000
183  330230000
184  445640000

[185 rows x 7 columns]
tolistdate: 0      2020-12-10
1      2020-12-11
2      2020-12-14
3      2020-12-15
4      2020-12-16
          ...
180    2021-08-30
181    2021-08-31
182    2021-09-01
183    2021-09-02
184    2021-09-03
Name: Date, Length: 185, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ABNB_ended_2021-09-25  2020-12-10           158  121.5  219.94       9.844

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   131.344   141.188   151.032   160.876    170.72   180.564   190.408

  markup_80 markup_90 markup_100
0   200.252   210.096     219.94
                   stock  start_date current_price minall  maxall each_markup  \
0  ABNB_ended_2021-09-25  2020-12-10           158  121.5  219.94       9.844

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   131.344   141.188   151.032   160.876    170.72   180.564   190.408

  markup_80 markup_90 markup_100
0   200.252   210.096     219.94
./ticker_data/ticker_data_2021-09-25 - Copy/ABST_ended_2021-09-25.csv
            Date   Open   High    Low  Close  Adj Close   Volume
0     2009-02-13   2.76   2.76   2.75   2.75   2.114090     5500
1     2009-02-17   2.75   2.75   2.74   2.74   2.106403     4300
2     2009-02-18   2.77   2.78   2.77   2.78   2.137153     1500
3     2009-02-19   2.91   2.91   2.88   2.88   2.214029     1900
4     2009-02-20   2.88   2.88   2.88   2.88   2.214029        0
...          ...    ...    ...    ...    ...        ...      ...
2696  2021-08-30  11.95  12.13  11.91  12.08  12.080000  4130000
2697  2021-08-31  12.06  12.31  12.05  12.24  12.240000  4120000
2698  2021-09-01  12.21  12.51  12.16  12.48  12.480000  5200000
2699  2021-09-02  12.54  12.57  12.40  12.43  12.430000  3830000
2700  2021-09-03  12.42  12.62  12.42  12.50  12.500000  4700000

[2701 rows x 7 columns]
tolistdate: 0       2009-02-13
1       2009-02-17
2       2009-02-18
3       2009-02-19
4       2009-02-20
           ...
2696    2021-08-30
2697    2021-08-31
2698    2021-09-01
2699    2021-09-02
2700    2021-09-03
Name: Date, Length: 2701, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ABST_ended_2021-09-25  2009-02-13          12.5   2.62   21.2       1.858

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.478     6.336     8.194    10.052     11.91    13.768    15.626

  markup_80 markup_90 markup_100
0    17.484    19.342       21.2
                   stock  start_date current_price minall maxall each_markup  \
0  ABST_ended_2021-09-25  2009-02-13          12.5   2.62   21.2       1.858

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.478     6.336     8.194    10.052     11.91    13.768    15.626

  markup_80 markup_90 markup_100
0    17.484    19.342       21.2
./ticker_data/ticker_data_2021-09-25 - Copy/ABTX_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2015-10-08  22.549999  23.469999  22.160000  23.120001  22.603573
1     2015-10-09  23.180000  23.200001  22.520000  22.520000  22.016975
2     2015-10-12  22.400000  22.620001  21.969999  22.200001  21.704123
3     2015-10-13  22.160000  22.570000  22.160000  22.299999  21.801888
4     2015-10-14  22.280001  23.000000  22.280001  22.350000  21.850769
...          ...        ...        ...        ...        ...        ...
1482  2021-08-30  37.959999  37.959999  36.880001  36.980000  36.980000
1483  2021-08-31  36.840000  37.470001  36.840000  37.169998  37.169998
1484  2021-09-01  37.119999  37.119999  36.459999  36.849998  36.849998
1485  2021-09-02  36.759998  37.290001  36.599998  36.599998  36.599998
1486  2021-09-03  36.660000  36.759998  35.910000  36.230000  36.230000

       Volume
0     1239700
1       84300
2       48300
3       32000
4       21600
...       ...
1482  4220000
1483  3860000
1484  3740000
1485  3130000
1486  6370000

[1487 rows x 7 columns]
tolistdate: 0       2015-10-08
1       2015-10-09
2       2015-10-12
3       2015-10-13
4       2015-10-14
           ...
1482    2021-08-30
1483    2021-08-31
1484    2021-09-01
1485    2021-09-02
1486    2021-09-03
Name: Date, Length: 1487, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ABTX_ended_2021-09-25  2015-10-08         36.23  14.38  46.85       3.247

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.627    20.874    24.121    27.368    30.615    33.862    37.109

  markup_80 markup_90 markup_100
0    40.356    43.603      46.85
                   stock  start_date current_price minall maxall each_markup  \
0  ABTX_ended_2021-09-25  2015-10-08         36.23  14.38  46.85       3.247

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.627    20.874    24.121    27.368    30.615    33.862    37.109

  markup_80 markup_90 markup_100
0    40.356    43.603      46.85
./ticker_data/ticker_data_2021-09-25 - Copy/ABUS_ended_2021-09-25.csv
            Date  Open  High   Low  Close  Adj Close     Volume
0     2007-07-26  6.30  6.35  6.30   6.30       6.30        100
1     2007-07-27  6.25  6.25  6.25   6.25       6.25        100
2     2007-07-30  5.55  5.80  5.55   5.55       5.55       1000
3     2007-07-31  5.55  5.55  5.55   5.55       5.55          0
4     2007-08-01  6.40  6.40  6.30   6.40       6.40       1200
...          ...   ...   ...   ...    ...        ...        ...
3436  2021-08-30  3.38  3.53  3.30   3.38       3.38  187470000
3437  2021-08-31  3.40  3.48  3.36   3.43       3.43  104710000
3438  2021-09-01  3.48  3.54  3.40   3.44       3.44  128850000
3439  2021-09-02  3.45  3.52  3.41   3.44       3.44  105210000
3440  2021-09-03  3.43  3.45  3.33   3.41       3.41   65860000

[3441 rows x 7 columns]
tolistdate: 0       2007-07-26
1       2007-07-27
2       2007-07-30
3       2007-07-31
4       2007-08-01
           ...
3436    2021-08-30
3437    2021-08-31
3438    2021-09-01
3439    2021-09-02
3440    2021-09-03
Name: Date, Length: 3441, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ABUS_ended_2021-09-25  2007-07-26          3.41   0.82  31.48       3.066

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.886     6.952    10.018    13.084     16.15    19.216    22.282

  markup_80 markup_90 markup_100
0    25.348    28.414      31.48
                   stock  start_date current_price minall maxall each_markup  \
0  ABUS_ended_2021-09-25  2007-07-26          3.41   0.82  31.48       3.066

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.886     6.952    10.018    13.084     16.15    19.216    22.282

  markup_80 markup_90 markup_100
0    25.348    28.414      31.48
./ticker_data/ticker_data_2021-09-25 - Copy/ACAD_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2004-05-27   7.440000   7.500000   6.500000   6.700000   6.700000
1     2004-05-28   6.880000   6.880000   6.610000   6.610000   6.610000
2     2004-06-01   6.590000   6.710000   6.400000   6.500000   6.500000
3     2004-06-02   6.400000   6.450000   6.250000   6.300000   6.300000
4     2004-06-03   6.250000   6.500000   6.250000   6.250000   6.250000
...          ...        ...        ...        ...        ...        ...
4343  2021-08-30  17.219999  17.360001  16.830000  16.969999  16.969999
4344  2021-08-31  16.969999  17.530001  16.930000  17.510000  17.510000
4345  2021-09-01  17.530001  17.870001  17.360001  17.690001  17.690001
4346  2021-09-02  17.549999  17.770000  17.049999  17.170000  17.170000
4347  2021-09-03  17.170000  17.219999  16.700001  16.780001  16.780001

         Volume
0       1919200
1        105600
2        118600
3         33000
4         30900
...         ...
4343   71450000
4344  128270000
4345   90420000
4346  135150000
4347  115220000

[4348 rows x 7 columns]
tolistdate: 0       2004-05-27
1       2004-05-28
2       2004-06-01
3       2004-06-02
4       2004-06-03
           ...
4343    2021-08-30
4344    2021-08-31
4345    2021-09-01
4346    2021-09-02
4347    2021-09-03
Name: Date, Length: 4348, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACAD_ended_2021-09-25  2004-05-27         16.78   0.65  58.72       5.807

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.457    12.264    18.071    23.878    29.685    35.492    41.299

  markup_80 markup_90 markup_100
0    47.106    52.913      58.72
                   stock  start_date current_price minall maxall each_markup  \
0  ACAD_ended_2021-09-25  2004-05-27         16.78   0.65  58.72       5.807

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.457    12.264    18.071    23.878    29.685    35.492    41.299

  markup_80 markup_90 markup_100
0    47.106    52.913      58.72
./ticker_data/ticker_data_2021-09-25 - Copy/ACAHU_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close   Volume
0    2021-03-04   9.98  10.00   9.95   9.95       9.95  9724200
1    2021-03-05   9.97  10.03   9.95   9.99       9.99  3507900
2    2021-03-08  10.00  10.09   9.99  10.03      10.03  1195800
3    2021-03-09  10.02  10.02   9.99  10.01      10.01  1469500
4    2021-03-10  10.03  10.04  10.00  10.04      10.04    97400
..          ...    ...    ...    ...    ...        ...      ...
119  2021-08-26   9.90   9.90   9.90   9.90       9.90   530000
120  2021-08-30   9.91   9.94   9.91   9.94       9.94  2510000
121  2021-08-31   9.90   9.91   9.90   9.91       9.91  1620000
122  2021-09-01   9.91   9.92   9.91   9.91       9.91  3660000
123  2021-09-03   9.91   9.91   9.91   9.91       9.91    40000

[124 rows x 7 columns]
tolistdate: 0      2021-03-04
1      2021-03-05
2      2021-03-08
3      2021-03-09
4      2021-03-10
          ...
119    2021-08-26
120    2021-08-30
121    2021-08-31
122    2021-09-01
123    2021-09-03
Name: Date, Length: 124, dtype: object

                    stock  start_date current_price minall maxall each_markup  \
0  ACAHU_ended_2021-09-25  2021-03-04          9.91    9.8  10.09       0.029

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.829     9.858     9.887     9.916     9.945     9.974    10.003

  markup_80 markup_90 markup_100
0    10.032    10.061      10.09
                    stock  start_date current_price minall maxall each_markup  \
0  ACAHU_ended_2021-09-25  2021-03-04          9.91    9.8  10.09       0.029

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.829     9.858     9.887     9.916     9.945     9.974    10.003

  markup_80 markup_90 markup_100
0    10.032    10.061      10.09
./ticker_data/ticker_data_2021-09-25 - Copy/ACAHW_ended_2021-09-25.csv
         Date  Open  High  Low  Close  Adj Close  Volume
0  2021-09-22   0.0   0.7  0.7    0.7        0.7   13666
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ACAHW_ended_2021-09-25  2021-09-22           0.7    0.7    0.7           0

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0       0.7       0.7       0.7       0.7       0.7       0.7       0.7

  markup_80 markup_90 markup_100
0       0.7       0.7        0.7
                    stock  start_date current_price minall maxall each_markup  \
0  ACAHW_ended_2021-09-25  2021-09-22           0.7    0.7    0.7           0

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0       0.7       0.7       0.7       0.7       0.7       0.7       0.7

  markup_80 markup_90 markup_100
0       0.7       0.7        0.7
./ticker_data/ticker_data_2021-09-25 - Copy/ACAH_ended_2021-09-25.csv
          Date   Open  High    Low  Close  Adj Close   Volume
0   2021-04-28  9.990  9.99  9.842  9.842      9.842      200
1   2021-04-29  9.990  9.99  9.820  9.820      9.820     3500
2   2021-04-30  9.820  9.82  9.820  9.820      9.820      100
3   2021-05-03  9.722  9.73  9.680  9.680      9.680   152500
4   2021-05-04  9.630  9.72  9.630  9.720      9.720    16400
..         ...    ...   ...    ...    ...        ...      ...
74  2021-08-30  9.610  9.61  9.610  9.610      9.610        0
75  2021-08-31  9.610  9.69  9.610  9.680      9.680  5910000
76  2021-09-01  9.650  9.68  9.630  9.630      9.630  1580000
77  2021-09-02  9.630  9.63  9.620  9.620      9.620   520000
78  2021-09-03  9.670  9.67  9.660  9.660      9.660   250000

[79 rows x 7 columns]
tolistdate: 0     2021-04-28
1     2021-04-29
2     2021-04-30
3     2021-05-03
4     2021-05-04
         ...
74    2021-08-30
75    2021-08-31
76    2021-09-01
77    2021-09-02
78    2021-09-03
Name: Date, Length: 79, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACAH_ended_2021-09-25  2021-04-28          9.66   9.61   9.99       0.038

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.648     9.686     9.724     9.762       9.8     9.838     9.876

  markup_80 markup_90 markup_100
0     9.914     9.952       9.99
                   stock  start_date current_price minall maxall each_markup  \
0  ACAH_ended_2021-09-25  2021-04-28          9.66   9.61   9.99       0.038

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.648     9.686     9.724     9.762       9.8     9.838     9.876

  markup_80 markup_90 markup_100
0     9.914     9.952       9.99
./ticker_data/ticker_data_2021-09-25 - Copy/ACBAU_ended_2021-09-25.csv
          Date   Open   High    Low   Close  Adj Close  Volume
0   2021-04-06  10.02  10.14  10.02  10.070     10.070  363300
1   2021-04-07  10.50  10.50  10.09  10.130     10.130   97900
2   2021-04-08  10.09  10.20  10.09  10.168     10.168   50600
3   2021-04-09  10.15  10.25  10.06  10.070     10.070  193900
4   2021-04-12  10.17  10.18  10.10  10.130     10.130    4200
..         ...    ...    ...    ...     ...        ...     ...
59  2021-08-18  10.31  10.31  10.31  10.310     10.310   10000
60  2021-08-19  10.40  10.40  10.28  10.280     10.280   30000
61  2021-08-20  10.28  10.28  10.28  10.280     10.280       0
62  2021-08-25  10.45  10.45  10.28  10.340     10.340  620000
63  2021-08-26  10.34  10.34  10.34  10.340     10.340       0

[64 rows x 7 columns]
tolistdate: 0     2021-04-06
1     2021-04-07
2     2021-04-08
3     2021-04-09
4     2021-04-12
         ...
59    2021-08-18
60    2021-08-19
61    2021-08-20
62    2021-08-25
63    2021-08-26
Name: Date, Length: 64, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ACBAU_ended_2021-09-25  2021-04-06         10.34  10.02  11.31       0.129

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.149    10.278    10.407    10.536    10.665    10.794    10.923

  markup_80 markup_90 markup_100
0    11.052    11.181      11.31
                    stock  start_date current_price minall maxall each_markup  \
0  ACBAU_ended_2021-09-25  2021-04-06         10.34  10.02  11.31       0.129

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.149    10.278    10.407    10.536    10.665    10.794    10.923

  markup_80 markup_90 markup_100
0    11.052    11.181      11.31
./ticker_data/ticker_data_2021-09-25 - Copy/ACBAW_ended_2021-09-25.csv
         Date     Open    High   Low  Close  Adj Close  Volume
0  2021-09-22  0.57495  0.4998  0.48   0.48       0.48    2644
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall  maxall  \
0  ACBAW_ended_2021-09-25  2021-09-22          0.48   0.48  0.4998

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00198   0.48198   0.48396   0.48594   0.48792    0.4899   0.49188

  markup_70 markup_80 markup_90 markup_100
0   0.49386   0.49584   0.49782     0.4998
                    stock  start_date current_price minall  maxall  \
0  ACBAW_ended_2021-09-25  2021-09-22          0.48   0.48  0.4998

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00198   0.48198   0.48396   0.48594   0.48792    0.4899   0.49188

  markup_70 markup_80 markup_90 markup_100
0   0.49386   0.49584   0.49782     0.4998
./ticker_data/ticker_data_2021-09-25 - Copy/ACBA_ended_2021-09-25.csv
          Date    Open    High     Low   Close  Adj Close   Volume
0   2021-05-26   9.750   9.750   9.700   9.750      9.750    20400
1   2021-05-27   9.900  12.000   9.850   9.850      9.850     8900
2   2021-05-28   9.900   9.940   9.870   9.911      9.911    68500
3   2021-06-01   9.911   9.911   9.911   9.911      9.911        0
4   2021-06-03   9.920   9.970   9.900   9.970      9.970     6200
5   2021-06-04   9.970  10.050   9.970  10.050     10.050    24000
6   2021-06-07   9.975  10.000   9.975  10.000     10.000     2700
7   2021-06-08  10.000  10.000  10.000  10.000     10.000     5600
8   2021-06-09  10.000  10.000  10.000  10.000     10.000        0
9   2021-06-10  10.000  10.030  10.000  10.000     10.000   176700
10  2021-06-11  10.000  10.000  10.000  10.000     10.000     1100
11  2021-06-15  10.010  10.010  10.000  10.000     10.000   138500
12  2021-06-16   9.990  10.030   9.990  10.030     10.030     3800
13  2021-06-17  10.010  10.025  10.010  10.025     10.025     2300
14  2021-06-18  10.025  10.025  10.025  10.025     10.025        0
15  2021-06-21  10.030  10.030   9.935  10.000     10.000     3400
16  2021-06-22  10.000  10.090  10.000  10.050     10.050     4300
17  2021-06-23   9.960  10.000   9.940  10.000     10.000    18700
18  2021-06-24  10.050  10.050  10.050  10.050     10.050     1800
19  2021-06-25  10.050  10.050  10.050  10.050     10.050        0
20  2021-06-29  10.050  10.050  10.050  10.050     10.050      700
21  2021-06-30  10.050  10.050  10.050  10.050     10.050      400
22  2021-07-01   9.975   9.975   9.975   9.975      9.975   160000
23  2021-07-02   9.975   9.975   9.975   9.975      9.975        0
24  2021-07-06  10.050  10.050  10.050  10.050     10.050      100
25  2021-07-16  10.050  10.050  10.050  10.050     10.050      200
26  2021-07-23   9.940   9.950   9.940   9.950      9.950    60000
27  2021-07-26   9.942   9.950   9.900   9.915      9.915    62500
28  2021-07-27   9.930   9.930   9.920   9.930      9.930   243600
29  2021-07-28   9.930   9.930   9.930   9.930      9.930        0
30  2021-07-30   9.950   9.950   9.950   9.950      9.950     1900
31  2021-08-03   9.950   9.950   9.950   9.950      9.950        0
32  2021-08-06   9.950   9.992   9.950   9.992      9.992    20000
33  2021-08-09   9.992   9.992   9.992   9.992      9.992        0
34  2021-08-17  10.040  10.040  10.040  10.040     10.040    10000
35  2021-08-18  10.040  10.040  10.040  10.040     10.040        0
36  2021-08-20   9.990   9.990   9.990   9.990      9.990   400000
37  2021-08-23   9.990   9.990   9.990   9.990      9.990        0
38  2021-08-25  10.045  10.050   9.990   9.998      9.998  7660000
39  2021-08-26  10.040  10.050  10.000  10.000     10.000  1430000
40  2021-08-30  10.000  10.000  10.000  10.000     10.000    90000
41  2021-08-31   9.960   9.960   9.960   9.960      9.960    50000
42  2021-09-01  10.030  10.030   9.960   9.984      9.984   190000
43  2021-09-02   9.980   9.980   9.980   9.980      9.980   520000
44  2021-09-03   9.980   9.980   9.980   9.980      9.980        0
tolistdate: 0     2021-05-26
1     2021-05-27
2     2021-05-28
3     2021-06-01
4     2021-06-03
5     2021-06-04
6     2021-06-07
7     2021-06-08
8     2021-06-09
9     2021-06-10
10    2021-06-11
11    2021-06-15
12    2021-06-16
13    2021-06-17
14    2021-06-18
15    2021-06-21
16    2021-06-22
17    2021-06-23
18    2021-06-24
19    2021-06-25
20    2021-06-29
21    2021-06-30
22    2021-07-01
23    2021-07-02
24    2021-07-06
25    2021-07-16
26    2021-07-23
27    2021-07-26
28    2021-07-27
29    2021-07-28
30    2021-07-30
31    2021-08-03
32    2021-08-06
33    2021-08-09
34    2021-08-17
35    2021-08-18
36    2021-08-20
37    2021-08-23
38    2021-08-25
39    2021-08-26
40    2021-08-30
41    2021-08-31
42    2021-09-01
43    2021-09-02
44    2021-09-03
Name: Date, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACBA_ended_2021-09-25  2021-05-26          9.98    9.7     12        0.23

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.93     10.16     10.39     10.62     10.85     11.08     11.31

  markup_80 markup_90 markup_100
0     11.54     11.77         12
                   stock  start_date current_price minall maxall each_markup  \
0  ACBA_ended_2021-09-25  2021-05-26          9.98    9.7     12        0.23

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.93     10.16     10.39     10.62     10.85     11.08     11.31

  markup_80 markup_90 markup_100
0     11.54     11.77         12
./ticker_data/ticker_data_2021-09-25 - Copy/ACBI_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2015-11-02  13.800000  15.000000  13.800000  15.000000  15.000000
1     2015-11-03  17.500000  17.500000  15.660000  15.660000  15.660000
2     2015-11-04  15.001000  15.050000  14.300000  14.305000  14.305000
3     2015-11-05  14.300000  14.500000  13.990000  14.050000  14.050000
4     2015-11-06  14.160000  14.205000  14.070000  14.150000  14.150000
...          ...        ...        ...        ...        ...        ...
1465  2021-08-30  24.780001  24.780001  24.000000  24.030001  24.030001
1466  2021-08-31  24.080000  24.445000  23.950001  24.230000  24.230000
1467  2021-09-01  24.260000  24.450001  23.264999  24.000000  24.000000
1468  2021-09-02  24.110001  24.430000  23.920000  24.240000  24.240000
1469  2021-09-03  24.209999  24.420000  24.020000  24.219999  24.219999

       Volume
0        1700
1        3800
2       76400
3      147000
4       51200
...       ...
1465  8660000
1466  7740000
1467  5920000
1468  6530000
1469  5880000

[1470 rows x 7 columns]
tolistdate: 0       2015-11-02
1       2015-11-03
2       2015-11-04
3       2015-11-05
4       2015-11-06
           ...
1465    2021-08-30
1466    2021-08-31
1467    2021-09-01
1468    2021-09-02
1469    2021-09-03
Name: Date, Length: 1470, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACBI_ended_2021-09-25  2015-11-02         24.22   8.89  28.93       2.004

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.894    12.898    14.902    16.906     18.91    20.914    22.918

  markup_80 markup_90 markup_100
0    24.922    26.926      28.93
                   stock  start_date current_price minall maxall each_markup  \
0  ACBI_ended_2021-09-25  2015-11-02         24.22   8.89  28.93       2.004

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.894    12.898    14.902    16.906     18.91    20.914    22.918

  markup_80 markup_90 markup_100
0    24.922    26.926      28.93
./ticker_data/ticker_data_2021-09-25 - Copy/ACB_ended_2021-09-25.csv
            Date   Open   High    Low  Close  Adj Close     Volume
0     2014-07-15  7.860  8.424  7.212  7.212      7.212      16000
1     2014-07-16  7.092  7.668  7.092  7.668      7.668        100
2     2014-07-17  7.668  7.668  7.668  7.668      7.668          0
3     2014-07-21  7.104  7.104  7.104  7.104      7.104        200
4     2014-07-22  7.104  7.104  7.104  7.104      7.104          0
...          ...    ...    ...    ...    ...        ...        ...
1579  2021-08-30  7.180  7.229  6.990  7.140      7.140  299250000
1580  2021-08-31  7.140  7.620  7.080  7.420      7.420  581040000
1581  2021-09-01  7.490  7.590  7.145  7.200      7.200  416480000
1582  2021-09-02  7.240  7.570  7.205  7.440      7.440  408590000
1583  2021-09-03  7.460  7.735  7.335  7.390      7.390  584150000

[1584 rows x 7 columns]
tolistdate: 0       2014-07-15
1       2014-07-16
2       2014-07-17
3       2014-07-21
4       2014-07-22
           ...
1579    2021-08-30
1580    2021-08-31
1581    2021-09-01
1582    2021-09-02
1583    2021-09-03
Name: Date, Length: 1584, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  ACB_ended_2021-09-25  2014-07-15          7.39   2.28  150.3      14.802

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.082    31.884    46.686    61.488     76.29    91.092   105.894

  markup_80 markup_90 markup_100
0   120.696   135.498      150.3
                  stock  start_date current_price minall maxall each_markup  \
0  ACB_ended_2021-09-25  2014-07-15          7.39   2.28  150.3      14.802

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.082    31.884    46.686    61.488     76.29    91.092   105.894

  markup_80 markup_90 markup_100
0   120.696   135.498      150.3
./ticker_data/ticker_data_2021-09-25 - Copy/ACCD_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-07-01   0.550000   0.550000   0.550000   0.550000   0.550000
1    2020-07-02  35.000000  36.889999  29.110001  29.700001  29.700001
2    2020-07-06  31.000000  31.179001  28.680000  30.000000  30.000000
3    2020-07-07  30.299999  30.850000  29.440001  30.150000  30.150000
4    2020-07-08  30.250000  34.570000  30.080000  34.310001  34.310001
..          ...        ...        ...        ...        ...        ...
292  2021-08-30  47.029999  47.950001  46.639999  47.220001  47.220001
293  2021-08-31  47.200001  48.340000  46.509998  47.380001  47.380001
294  2021-09-01  47.570000  48.810001  46.955002  48.230000  48.230000
295  2021-09-02  48.400002  49.470001  47.630001  48.470001  48.470001
296  2021-09-03  48.130001  48.919998  47.180000  47.410000  47.410000

       Volume
0         100
1     8507600
2     1781400
3      852100
4     1392800
..        ...
292  37400000
293  48030000
294  34840000
295  24810000
296  18970000

[297 rows x 7 columns]
tolistdate: 0      2020-07-01
1      2020-07-02
2      2020-07-06
3      2020-07-07
4      2020-07-08
          ...
292    2021-08-30
293    2021-08-31
294    2021-09-01
295    2021-09-02
296    2021-09-03
Name: Date, Length: 297, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACCD_ended_2021-09-25  2020-07-01         47.41   0.55  65.25        6.47

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      7.02     13.49     19.96     26.43      32.9     39.37     45.84

  markup_80 markup_90 markup_100
0     52.31     58.78      65.25
                   stock  start_date current_price minall maxall each_markup  \
0  ACCD_ended_2021-09-25  2020-07-01         47.41   0.55  65.25        6.47

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      7.02     13.49     19.96     26.43      32.9     39.37     45.84

  markup_80 markup_90 markup_100
0     52.31     58.78      65.25
./ticker_data/ticker_data_2021-09-25 - Copy/ACER_ended_2021-09-25.csv
            Date          Open          High           Low         Close  \
0     2004-04-14  15000.000000  15000.000000  15000.000000  15000.000000
1     2004-04-15  15000.000000  15000.000000  15000.000000  15000.000000
2     2004-05-11   1666.666626   1666.666626   1666.666626   1666.666626
3     2004-05-12   1700.000000   1700.000000   1700.000000   1700.000000
4     2004-05-14   3333.333252   3333.333252   3333.333252   3333.333252
...          ...           ...           ...           ...           ...
4112  2021-08-30      2.550000      2.620000      2.530000      2.530000
4113  2021-08-31      2.510000      2.630000      2.510000      2.630000
4114  2021-09-01      2.660000      2.730000      2.650000      2.700000
4115  2021-09-02      2.680000      2.790000      2.650000      2.700000
4116  2021-09-03      2.700000      2.730000      2.630000      2.670000

         Adj Close   Volume
0     15000.000000        0
1     15000.000000        0
2      1666.666626        0
3      1700.000000        0
4      3333.333252        0
...            ...      ...
4112      2.530000  3970000
4113      2.630000  5820000
4114      2.700000  5450000
4115      2.700000  7810000
4116      2.670000  4000000

[4117 rows x 7 columns]
tolistdate: 0       2004-04-14
1       2004-04-15
2       2004-05-11
3       2004-05-12
4       2004-05-14
           ...
4112    2021-08-30
4113    2021-08-31
4114    2021-09-01
4115    2021-09-02
4116    2021-09-03
Name: Date, Length: 4117, dtype: object
                   stock  start_date current_price minall   maxall  \
0  ACER_ended_2021-09-25  2004-04-14          2.67   1.08  48333.3

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     4833.23   4834.31   9667.53   14500.8     19334   24167.2   29000.4

  markup_70 markup_80 markup_90 markup_100
0   33833.7   38666.9   43500.1    48333.3
                   stock  start_date current_price minall   maxall  \
0  ACER_ended_2021-09-25  2004-04-14          2.67   1.08  48333.3

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     4833.23   4834.31   9667.53   14500.8     19334   24167.2   29000.4

  markup_70 markup_80 markup_90 markup_100
0   33833.7   38666.9   43500.1    48333.3
./ticker_data/ticker_data_2021-09-25 - Copy/ACET_ended_2021-09-25.csv
           Date        Open        High         Low       Close   Adj Close  \
0    2018-01-26  130.339996  143.500000  113.470001  118.160004  118.160004
1    2018-01-29  120.470001  120.470001  110.809998  113.610001  113.610001
2    2018-01-30  113.959999  115.787003  106.959999  110.180000  110.180000
3    2018-01-31  109.970001  115.919998  109.059998  113.540001  113.540001

0   105.181   119.347   133.513    147.679
./ticker_data/ticker_data_2021-09-25 - Copy/ACEVU_ended_2021-09-25.csv
           Date    Open    High     Low  Close  Adj Close   Volume
0    2020-07-29  10.290  10.290  10.180  10.18      10.18  1154500
1    2020-07-30  10.200  10.250  10.059  10.10      10.10   587800
2    2020-07-31  10.100  10.100  10.010  10.02      10.02   268200
3    2020-08-03  10.020  10.050   9.970  10.00      10.00  1123300
4    2020-08-04  10.100  10.100  10.010  10.03      10.03    61700
..          ...     ...     ...     ...    ...        ...      ...
258  2021-08-24  10.140  10.140  10.140  10.14      10.14        0
259  2021-08-27  10.159  10.159  10.140  10.14      10.14   180000
260  2021-08-31  10.170  10.170  10.170  10.17      10.17    40000
261  2021-09-01  10.130  10.130  10.130  10.13      10.13    20000
262  2021-09-02  10.170  10.170  10.170  10.17      10.17   120000

[263 rows x 7 columns]
tolistdate: 0      2020-07-29
1      2020-07-30
2      2020-07-31
3      2020-08-03
4      2020-08-04
          ...
258    2021-08-24
259    2021-08-27
260    2021-08-31
261    2021-09-01
262    2021-09-02
Name: Date, Length: 263, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ACEVU_ended_2021-09-25  2020-07-29         10.17    9.9     15        0.51

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     10.41     10.92     11.43     11.94     12.45     12.96     13.47

  markup_80 markup_90 markup_100
0     13.98     14.49         15
                    stock  start_date current_price minall maxall each_markup  \
0  ACEVU_ended_2021-09-25  2020-07-29         10.17    9.9     15        0.51

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     10.41     10.92     11.43     11.94     12.45     12.96     13.47

  markup_80 markup_90 markup_100
0     13.98     14.49         15
./ticker_data/ticker_data_2021-09-25 - Copy/ACEVW_ended_2021-09-25.csv
         Date    Open  High   Low  Close  Adj Close  Volume
0  2021-09-22  0.6599  0.66  0.63   0.64       0.64   15587
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ACEVW_ended_2021-09-25  2021-09-22          0.64   0.63   0.66       0.003

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.633     0.636     0.639     0.642     0.645     0.648     0.651

  markup_80 markup_90 markup_100
0     0.654     0.657       0.66
                    stock  start_date current_price minall maxall each_markup  \
0  ACEVW_ended_2021-09-25  2021-09-22          0.64   0.63   0.66       0.003

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.633     0.636     0.639     0.642     0.645     0.648     0.651

  markup_80 markup_90 markup_100
0     0.654     0.657       0.66
./ticker_data/ticker_data_2021-09-25 - Copy/ACEV_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close    Volume
0    2020-09-21  9.790  9.790  9.780   9.78       9.78      3200
1    2020-09-22  9.820  9.820  9.760   9.76       9.76     16700
2    2020-09-23  9.850  9.850  9.750   9.75       9.75     63700
3    2020-09-24  9.750  9.810  9.750   9.77       9.77     52400
4    2020-09-25  9.805  9.805  9.750   9.78       9.78     10200
..          ...    ...    ...    ...    ...        ...       ...
234  2021-08-30  9.860  9.880  9.860   9.87       9.87  10570000
235  2021-08-31  9.870  9.880  9.865   9.87       9.87   3000000
236  2021-09-01  9.870  9.880  9.870   9.87       9.87  10500000
237  2021-09-02  9.870  9.890  9.860   9.88       9.88  12850000
238  2021-09-03  9.870  9.900  9.870   9.89       9.89   5600000

[239 rows x 7 columns]
tolistdate: 0      2020-09-21
1      2020-09-22
2      2020-09-23
3      2020-09-24
4      2020-09-25
          ...
234    2021-08-30
235    2021-08-31
236    2021-09-01
237    2021-09-02
238    2021-09-03
Name: Date, Length: 239, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACEV_ended_2021-09-25  2020-09-21          9.89    9.6   13.5        0.39

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.99     10.38     10.77     11.16     11.55     11.94     12.33

  markup_80 markup_90 markup_100
0     12.72     13.11       13.5
                   stock  start_date current_price minall maxall each_markup  \
0  ACEV_ended_2021-09-25  2020-09-21          9.89    9.6   13.5        0.39

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.99     10.38     10.77     11.16     11.55     11.94     12.33

  markup_80 markup_90 markup_100
0     12.72     13.11       13.5
./ticker_data/ticker_data_2021-09-25 - Copy/ACGLO_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2017-08-21  24.886999  25.049999  24.799999  24.990000  20.224152
1     2017-08-22  25.000000  25.040001  24.950001  24.980000  20.216059
2     2017-08-23  25.010000  25.080999  24.969999  25.070000  20.288895
3     2017-08-24  25.030001  25.100000  25.010000  25.020000  20.248430
4     2017-08-25  25.059999  25.070000  25.010000  25.049999  20.272705
...          ...        ...        ...        ...        ...        ...
1012  2021-08-30  26.219999  26.500000  26.219999  26.400000  26.400000
1013  2021-08-31  26.320000  26.440001  26.320000  26.360001  26.360001
1014  2021-09-01  26.450001  26.450001  26.360001  26.379999  26.379999
1015  2021-09-02  26.290001  26.600000  26.290001  26.590000  26.590000
1016  2021-09-03  26.486000  26.490000  26.410000  26.490000  26.490000

       Volume
0      174800
1      256100
2      119100
3      175600
4       83000
...       ...
1012   640000
1013  2580000
1014  2270000
1015  1410000
1016   680000

[1017 rows x 7 columns]
tolistdate: 0       2017-08-21
1       2017-08-22
2       2017-08-23
3       2017-08-24
4       2017-08-25
           ...
1012    2021-08-30
1013    2021-08-31
1014    2021-09-01
1015    2021-09-02
1016    2021-09-03
Name: Date, Length: 1017, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ACGLO_ended_2021-09-25  2017-08-21         26.49  15.25  27.06       1.181

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    16.431    17.612    18.793    19.974    21.155    22.336    23.517

  markup_80 markup_90 markup_100
0    24.698    25.879      27.06
                    stock  start_date current_price minall maxall each_markup  \
0  ACGLO_ended_2021-09-25  2017-08-21         26.49  15.25  27.06       1.181

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    16.431    17.612    18.793    19.974    21.155    22.336    23.517

  markup_80 markup_90 markup_100
0    24.698    25.879      27.06
./ticker_data/ticker_data_2021-09-25 - Copy/ACGLP_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2016-09-23  24.879999  24.980000  24.850000  24.920000  19.210381
1     2016-09-26  24.900000  25.000000  24.879999  24.930000  19.218088
2     2016-09-27  24.950001  25.020000  24.900000  25.000000  19.272055
3     2016-09-28  24.900000  25.049999  24.900000  25.000000  19.272055
4     2016-09-29  24.959999  25.020000  24.900000  24.920000  19.210381
...          ...        ...        ...        ...        ...        ...
1240  2021-08-30  25.219999  25.289000  25.219999  25.260000  25.260000
1241  2021-08-31  25.260000  25.280001  25.260000  25.270000  25.270000
1242  2021-09-01  25.280001  25.309999  25.280001  25.309999  25.309999
1243  2021-09-02  25.290001  25.309999  25.280001  25.290001  25.290001
1244  2021-09-03  25.280001  25.299999  25.280001  25.290001  25.290001

       Volume
0     3053400
1     2308600
2     1296100
3      303700
4      429900
...       ...
1240  1230000
1241  4180000
1242  3430000
1243  3500000
1244  3270000

[1245 rows x 7 columns]
tolistdate: 0       2016-09-23
1       2016-09-26
2       2016-09-27
3       2016-09-28
4       2016-09-29
           ...
1240    2021-08-30
1241    2021-08-31
1242    2021-09-01
1243    2021-09-02
1244    2021-09-03
Name: Date, Length: 1245, dtype: object
                    stock  start_date current_price minall  maxall  \
0  ACGLP_ended_2021-09-25  2016-09-23         25.29  16.13  26.227

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      1.0097   17.1397   18.1494   19.1591   20.1688   21.1785   22.1882

  markup_70 markup_80 markup_90 markup_100
0   23.1979   24.2076   25.2173     26.227
                    stock  start_date current_price minall  maxall  \
0  ACGLP_ended_2021-09-25  2016-09-23         25.29  16.13  26.227

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      1.0097   17.1397   18.1494   19.1591   20.1688   21.1785   22.1882

  markup_70 markup_80 markup_90 markup_100
0   23.1979   24.2076   25.2173     26.227
./ticker_data/ticker_data_2021-09-25 - Copy/ACGL_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   1.416667   1.416667   1.395833   1.402778   1.402778
1     2000-01-03   1.409722   1.416667   1.263889   1.277778   1.277778
2     2000-01-04   1.263889   1.277778   1.263889   1.270833   1.270833
3     2000-01-05   1.284722   1.388889   1.284722   1.388889   1.388889
4     2000-01-06   1.388889   1.430556   1.326389   1.375000   1.375000
...          ...        ...        ...        ...        ...        ...
5446  2021-08-30  41.759998  41.990002  41.169998  41.250000  41.250000
5447  2021-08-31  41.169998  41.490002  40.939999  41.099998  41.099998
5448  2021-09-01  41.060001  41.189999  40.459999  40.470001  40.470001
5449  2021-09-02  40.410000  40.419998  39.450001  39.610001  39.610001
5450  2021-09-03  39.549999  39.720001  39.110001  39.430000  39.430000

         Volume
0        119700
1        433800
2         84600
3         80100
4        348300
...         ...
5446  154460000
5447  187640000
5448  115610000
5449  174020000
5450  197520000

[5451 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5446    2021-08-30
5447    2021-08-31
5448    2021-09-01
5449    2021-09-02
5450    2021-09-03
Name: Date, Length: 5451, dtype: object
                   stock  start_date current_price   minall maxall  \
0  ACGL_ended_2021-09-25  1999-12-31         39.43  1.26389  48.32

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     4.70561    5.9695   10.6751   15.3807   20.0863   24.7919   29.4976

  markup_70 markup_80 markup_90 markup_100
0   34.2032   38.9088   43.6144      48.32
                   stock  start_date current_price   minall maxall  \
0  ACGL_ended_2021-09-25  1999-12-31         39.43  1.26389  48.32

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     4.70561    5.9695   10.6751   15.3807   20.0863   24.7919   29.4976

  markup_70 markup_80 markup_90 markup_100
0   34.2032   38.9088   43.6144      48.32
./ticker_data/ticker_data_2021-09-25 - Copy/ACHC_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   3.125000   3.250000   2.937500   3.000000   3.000000
1     2000-01-03   3.125000   3.500000   3.000000   3.375000   3.375000
2     2000-01-04   3.375000   3.375000   3.375000   3.375000   3.375000
3     2000-01-05   3.125000   3.250000   2.750000   3.250000   3.250000
4     2000-01-06   3.000000   3.000000   3.000000   3.000000   3.000000
...          ...        ...        ...        ...        ...        ...
5435  2021-08-30  66.239998  66.970001  65.669998  66.300003  66.300003
5436  2021-08-31  66.349998  66.930000  65.800003  66.120003  66.120003
5437  2021-09-01  66.300003  66.989998  65.220001  66.629997  66.629997
5438  2021-09-02  66.870003  68.300003  66.660004  68.260002  68.260002
5439  2021-09-03  67.889999  68.650002  67.889999  68.160004  68.160004

        Volume
0        11900
1          300
2            0
3        18200
4          700
...        ...
5435  30790000
5436  29910000
5437  28010000
5438  31550000
5439  28550000

[5440 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5435    2021-08-30
5436    2021-08-31
5437    2021-09-01
5438    2021-09-02
5439    2021-09-03
Name: Date, Length: 5440, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACHC_ended_2021-09-25  1999-12-31         68.16   0.25  85.62       8.537

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.787    17.324    25.861    34.398    42.935    51.472    60.009

  markup_80 markup_90 markup_100
0    68.546    77.083      85.62
                   stock  start_date current_price minall maxall each_markup  \
0  ACHC_ended_2021-09-25  1999-12-31         68.16   0.25  85.62       8.537

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.787    17.324    25.861    34.398    42.935    51.472    60.009

  markup_80 markup_90 markup_100
0    68.546    77.083      85.62
./ticker_data/ticker_data_2021-09-25 - Copy/ACHL_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2021-03-31  18.000000  18.948000  16.059999  16.549999  16.549999
1    2021-04-01  16.299999  17.344000  15.060000  16.000000  16.000000
2    2021-04-05  15.630000  15.950000  14.730000  14.920000  14.920000
3    2021-04-06  14.870000  17.990000  14.729000  17.860001  17.860001
4    2021-04-07  17.510000  17.790001  15.550000  15.610000  15.610000
..          ...        ...        ...        ...        ...        ...
104  2021-08-30   6.490000   6.600000   6.360000   6.490000   6.490000
105  2021-08-31   6.480000   6.780000   6.410000   6.780000   6.780000
106  2021-09-01   6.800000   7.020000   6.700000   6.810000   6.810000
107  2021-09-02   6.800000   6.860000   6.540000   6.650000   6.650000
108  2021-09-03   6.660000   6.986000   6.410000   6.460000   6.460000

      Volume
0    2110800
1     506500
2     169200
3     447200
4     173300
..       ...
104  4360000
105  6560000
106  6120000
107  6330000
108  6910000

[109 rows x 7 columns]
tolistdate: 0      2021-03-31
1      2021-04-01
2      2021-04-05
3      2021-04-06
4      2021-04-07
          ...
104    2021-08-30
105    2021-08-31
106    2021-09-01
107    2021-09-02
108    2021-09-03
Name: Date, Length: 109, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ACHL_ended_2021-09-25  2021-03-31          6.46   5.51  18.948      1.3438

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    6.8538    8.1976    9.5414   10.8852    12.229   13.5728   14.9166

  markup_80 markup_90 markup_100
0   16.2604   17.6042     18.948
                   stock  start_date current_price minall  maxall each_markup  \
0  ACHL_ended_2021-09-25  2021-03-31          6.46   5.51  18.948      1.3438

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    6.8538    8.1976    9.5414   10.8852    12.229   13.5728   14.9166

  markup_80 markup_90 markup_100
0   16.2604   17.6042     18.948
./ticker_data/ticker_data_2021-09-25 - Copy/ACHV_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   90337.50   99000.00   84150.00   99000.00   99000.00
1     2000-01-03   99000.00  123750.00   95906.25  111375.00  111375.00
2     2000-01-04  111375.00  118800.00  108900.00  118800.00  118800.00
3     2000-01-05  121275.00  153450.00  113850.00  131175.00  131175.00
4     2000-01-06  131175.00  131175.00  118800.00  131175.00  131175.00
...          ...        ...        ...        ...        ...        ...
5408  2021-08-30       7.98       8.04       7.80       7.93       7.93
5409  2021-08-31       7.98       8.35       7.93       8.35       8.35
5410  2021-09-01       8.30       8.41       8.08       8.19       8.19
5411  2021-09-02       8.19       8.57       8.12       8.42       8.42
5412  2021-09-03       8.44       8.54       8.11       8.40       8.40

        Volume
0            0
1            0
2            0
3            0
4            0
...        ...
5408   5500000
5409  12260000
5410   9170000
5411  11980000
5412   4840000

[5413 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5408    2021-08-30
5409    2021-08-31
5410    2021-09-01
5411    2021-09-02
5412    2021-09-03
Name: Date, Length: 5413, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ACHV_ended_2021-09-25  1999-12-31           8.4    4.6  445500     44549.5

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   44554.1   89103.7    133653    178203    222752    267302    311851

  markup_80 markup_90 markup_100
0    356401    400950     445500
                   stock  start_date current_price minall  maxall each_markup  \
0  ACHV_ended_2021-09-25  1999-12-31           8.4    4.6  445500     44549.5

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   44554.1   89103.7    133653    178203    222752    267302    311851

  markup_80 markup_90 markup_100
0    356401    400950     445500

./ticker_data/ticker_data_2021-09-25 - Copy/ACIU_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2016-09-23  14.110000  16.799999  14.110000  15.660000  15.660000
1     2016-09-26  15.600000  17.400000  15.500000  16.500000  16.500000
2     2016-09-27  16.780001  18.364000  16.389999  18.209999  18.209999
3     2016-09-28  19.040001  19.969999  18.600000  19.299999  19.299999
4     2016-09-29  19.600000  19.700001  17.219999  17.540001  17.540001
...          ...        ...        ...        ...        ...        ...
1240  2021-08-30   6.880000   7.210000   6.800000   6.990000   6.990000
1241  2021-08-31  12.010000  12.610000   7.930000   8.130000   8.130000
1242  2021-09-01   7.760000   8.070000   7.230000   7.290000   7.290000
1243  2021-09-02   7.300000   7.360000   6.970000   7.130000   7.130000
1244  2021-09-03   7.150000   7.450000   7.040000   7.120000   7.120000

           Volume
0         3775900
1         1008300
2          531500
3          474400
4          335400
...           ...
1240     14290000
1241  10301170000
1242    407430000
1243    154940000
1244    123540000

[1245 rows x 7 columns]
tolistdate: 0       2016-09-23
1       2016-09-26
2       2016-09-27
3       2016-09-28
4       2016-09-29
           ...
1240    2021-08-30
1241    2021-08-31
1242    2021-09-01
1243    2021-09-02
1244    2021-09-03
Name: Date, Length: 1245, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACIU_ended_2021-09-25  2016-09-23          7.12   3.25  19.97       1.672

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.922     6.594     8.266     9.938     11.61    13.282    14.954

  markup_80 markup_90 markup_100
0    16.626    18.298      19.97
                   stock  start_date current_price minall maxall each_markup  \
0  ACIU_ended_2021-09-25  2016-09-23          7.12   3.25  19.97       1.672

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.922     6.594     8.266     9.938     11.61    13.282    14.954

  markup_80 markup_90 markup_100
0    16.626    18.298      19.97
./ticker_data/ticker_data_2021-09-25 - Copy/ACIW_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   9.208333   9.479167   9.083333   9.333333   9.333333
1     2000-01-03   9.333333   9.375000   8.916667   8.937500   8.937500
2     2000-01-04   8.833333   8.916667   8.104167   8.333333   8.333333
3     2000-01-05   8.250000   8.333333   8.000000   8.062500   8.062500
4     2000-01-06   8.000000   8.166667   7.958333   7.979167   7.979167
...          ...        ...        ...        ...        ...        ...
5449  2021-08-30  31.920000  32.200001  31.590000  32.090000  32.090000
5450  2021-08-31  32.150002  32.389999  31.920000  32.230000  32.230000
5451  2021-09-01  32.189999  32.770000  32.189999  32.470001  32.470001
5452  2021-09-02  32.419998  32.990002  32.259998  32.900002  32.900002
5453  2021-09-03  32.880001  33.450001  32.700001  33.270000  33.270000

         Volume
0       1333800
1       1335300
2       2669400
3       2554200
4       2390400
...         ...
5449   58490000
5450  102510000
5451   51170000
5452   81700000
5453  116880000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACIW_ended_2021-09-25  1999-12-31         33.27   1.42  43.23       4.181

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.601     9.782    13.963    18.144    22.325    26.506    30.687

  markup_80 markup_90 markup_100
0    34.868    39.049      43.23
                   stock  start_date current_price minall maxall each_markup  \
0  ACIW_ended_2021-09-25  1999-12-31         33.27   1.42  43.23       4.181

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.601     9.782    13.963    18.144    22.325    26.506    30.687

  markup_80 markup_90 markup_100
0    34.868    39.049      43.23
./ticker_data/ticker_data_2021-09-25 - Copy/ACKIT_ended_2021-09-25.csv
           Date    Open    High     Low  Close  Adj Close   Volume
0    2021-02-04  10.100  10.280  10.100  10.20      10.20   169000
1    2021-02-05  10.236  10.236  10.200  10.21      10.21    20700
2    2021-02-08  10.440  10.440  10.170  10.17      10.17    12200
3    2021-02-09  10.190  10.240  10.150  10.15      10.15    14000
4    2021-02-10  10.160  10.250  10.150  10.22      10.22    19200
..          ...     ...     ...     ...    ...        ...      ...
138  2021-08-30   9.990   9.995   9.988   9.99       9.99  2730000
139  2021-08-31   9.973  10.030   9.973  10.03      10.03   910000
140  2021-09-01  10.022  10.030  10.010  10.01      10.01   120000
141  2021-09-02  10.000  10.000  10.000  10.00      10.00   300000
142  2021-09-03  10.000  10.000  10.000  10.00      10.00        0

[143 rows x 7 columns]
tolistdate: 0      2021-02-04
1      2021-02-05
2      2021-02-08
3      2021-02-09
4      2021-02-10
          ...
138    2021-08-30
139    2021-08-31
140    2021-09-01
141    2021-09-02
142    2021-09-03
Name: Date, Length: 143, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ACKIT_ended_2021-09-25  2021-02-04            10   9.84  10.44   0.0599999

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0       9.9      9.96     10.02     10.08     10.14      10.2     10.26

  markup_80 markup_90 markup_100
0     10.32     10.38      10.44
                    stock  start_date current_price minall maxall each_markup  \
0  ACKIT_ended_2021-09-25  2021-02-04            10   9.84  10.44   0.0599999

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0       9.9      9.96     10.02     10.08     10.14      10.2     10.26

  markup_80 markup_90 markup_100
0     10.32     10.38      10.44
./ticker_data/ticker_data_2021-09-25 - Copy/ACKIU_ended_2021-09-25.csv
           Date    Open    High     Low   Close  Adj Close   Volume
0    2020-12-21  10.090  10.140  10.080  10.100     10.100  3012800
1    2020-12-22  10.120  10.201  10.116  10.140     10.140   444900
2    2020-12-23  10.200  10.200  10.140  10.140     10.140   121700
3    2020-12-24  10.180  10.230  10.120  10.180     10.180    70000
4    2020-12-28  10.200  10.470  10.145  10.280     10.280   230600
..          ...     ...     ...     ...     ...        ...      ...
166  2021-08-26  10.200  10.200  10.190  10.190     10.190  1930000
167  2021-08-27  10.200  10.200  10.190  10.190     10.190   260000
168  2021-08-30  10.220  10.220  10.220  10.220     10.220  1200000
169  2021-09-02  10.224  10.224  10.224  10.224     10.224   110000
170  2021-09-03  10.260  10.260  10.217  10.217     10.217    40000

[171 rows x 7 columns]
tolistdate: 0      2020-12-21
1      2020-12-22
2      2020-12-23
3      2020-12-24
4      2020-12-28
          ...
166    2021-08-26
167    2021-08-27
168    2021-08-30
169    2021-09-02
170    2021-09-03
Name: Date, Length: 171, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ACKIU_ended_2021-09-25  2020-12-21        10.217  10.08     11       0.092

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.172    10.264    10.356    10.448     10.54    10.632    10.724

  markup_80 markup_90 markup_100
0    10.816    10.908         11
                    stock  start_date current_price minall maxall each_markup  \
0  ACKIU_ended_2021-09-25  2020-12-21        10.217  10.08     11       0.092

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.172    10.264    10.356    10.448     10.54    10.632    10.724

  markup_80 markup_90 markup_100
0    10.816    10.908         11
./ticker_data/ticker_data_2021-09-25 - Copy/ACKIW_ended_2021-09-25.csv
         Date    Open   High   Low  Close  Adj Close  Volume
0  2021-09-22  0.5601  0.495  0.47   0.47       0.47    2100
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ACKIW_ended_2021-09-25  2021-09-22          0.47   0.47  0.495      0.0025

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    0.4725     0.475    0.4775      0.48    0.4825     0.485    0.4875

  markup_80 markup_90 markup_100
0      0.49    0.4925      0.495
                    stock  start_date current_price minall maxall each_markup  \
0  ACKIW_ended_2021-09-25  2021-09-22          0.47   0.47  0.495      0.0025

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    0.4725     0.475    0.4775      0.48    0.4825     0.485    0.4875

  markup_80 markup_90 markup_100
0      0.49    0.4925      0.495
./ticker_data/ticker_data_2021-09-25 - Copy/ACLS_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2000-07-11  110.000000  120.000000   95.000000   95.750000   95.750000
1     2000-07-12   99.000000  106.500000   95.750000  103.500000  103.500000
2     2000-07-13  105.500000  109.750000  100.000000  102.000000  102.000000
3     2000-07-14  103.250000  103.500000   95.750000  100.750000  100.750000
4     2000-07-17  107.500000  107.500000   95.500000   96.500000   96.500000
...          ...         ...         ...         ...         ...         ...
5317  2021-08-30   52.130001   52.799999   50.009998   50.900002   50.900002
5318  2021-08-31   50.880001   50.880001   48.830002   49.709999   49.709999
5319  2021-09-01   49.799999   50.009998   48.169998   48.580002   48.580002
5320  2021-09-02   48.950001   50.099998   48.599998   49.840000   49.840000
5321  2021-09-03   49.549999   50.610001   49.250000   50.060001   50.060001

        Volume
0      4362100
1      1135500
2       521100
3       273700
4       316500
...        ...
5317  29970000
5318  66020000
5319  21010000
5320  15730000
5321  22440000

[5322 rows x 7 columns]
tolistdate: 0       2000-07-11
1       2000-07-12
2       2000-07-13
3       2000-07-14
4       2000-07-17
           ...
5317    2021-08-30
5318    2021-08-31
5319    2021-09-01
5320    2021-09-02
5321    2021-09-03
Name: Date, Length: 5322, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACLS_ended_2021-09-25  2000-07-11         50.06   0.68    120      11.932

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.612    24.544    36.476    48.408     60.34    72.272    84.204

  markup_80 markup_90 markup_100
0    96.136   108.068        120
                   stock  start_date current_price minall maxall each_markup  \
0  ACLS_ended_2021-09-25  2000-07-11         50.06   0.68    120      11.932

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.612    24.544    36.476    48.408     60.34    72.272    84.204

  markup_80 markup_90 markup_100
0    96.136   108.068        120
./ticker_data/ticker_data_2021-09-25 - Copy/ACMR_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2017-11-02   5.600000   5.600000   5.600000   5.600000   5.600000
1    2017-11-03   8.170000   8.484000   5.870000   6.050000   6.050000
2    2017-11-06   6.010000   6.460000   5.600000   5.600000   5.600000
3    2017-11-07   5.600000   5.730000   5.600000   5.600000   5.600000
4    2017-11-08   5.600000   5.650000   5.600000   5.600000   5.600000
..          ...        ...        ...        ...        ...        ...
961  2021-08-30  88.370003  89.099998  85.250000  88.180000  88.180000
962  2021-08-31  87.800003  90.730003  87.529999  89.150002  89.150002
963  2021-09-01  89.389999  92.290001  88.599998  89.029999  89.029999
964  2021-09-02  89.339996  94.165001  88.385002  92.989998  92.989998
965  2021-09-03  92.529999  95.440002  92.180000  94.580002  94.580002

       Volume
0         100
1      523500
2       70600
3       32600
4      118500
..        ...
961  15820000
962  39020000
963  20010000
964  27600000
965  23030000

[966 rows x 7 columns]
tolistdate: 0      2017-11-02
1      2017-11-03
2      2017-11-06
3      2017-11-07
4      2017-11-08
          ...
961    2021-08-30
962    2021-08-31
963    2021-09-01
964    2021-09-02
965    2021-09-03
Name: Date, Length: 966, dtype: object
                   stock  start_date current_price minall   maxall  \
0  ACMR_ended_2021-09-25  2017-11-02         94.58  4.744  144.807

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     14.0063   18.7503   32.7566   46.7629   60.7692   74.7755   88.7818

  markup_70 markup_80 markup_90 markup_100
0   102.788   116.794   130.801    144.807
                   stock  start_date current_price minall   maxall  \
0  ACMR_ended_2021-09-25  2017-11-02         94.58  4.744  144.807

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     14.0063   18.7503   32.7566   46.7629   60.7692   74.7755   88.7818

  markup_70 markup_80 markup_90 markup_100
0   102.788   116.794   130.801    144.807
./ticker_data/ticker_data_2021-09-25 - Copy/ACNB_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  16.666666  16.666666  16.666666  16.666666   6.509614
1     2000-01-03  17.006804  17.006804  16.439909  16.439909   6.421052
2     2000-01-04  16.439909  16.439909  16.439909  16.439909   6.421052
3     2000-01-05  16.439909  16.439909  16.439909  16.439909   6.421052
4     2000-01-07  16.439909  16.780045  16.439909  16.780045   6.553902
...          ...        ...        ...        ...        ...        ...
5103  2021-08-30  28.900000  28.900000  28.660000  28.750000  28.750000
5104  2021-08-31  28.709999  28.969999  28.610001  28.809999  28.809999
5105  2021-09-01  28.719999  29.090000  28.600000  28.889999  28.889999
5106  2021-09-02  28.900000  29.400000  28.350000  28.590000  28.590000
5107  2021-09-03  28.270000  28.379999  28.000000  28.200001  28.200001

       Volume
0           0
1        6300
2         300
3           0
4        6000
...       ...
5103  1600000
5104  1580000
5105  2330000
5106  1540000
5107  1350000

[5108 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-07
           ...
5103    2021-08-30
5104    2021-08-31
5105    2021-09-01
5106    2021-09-02
5107    2021-09-03
Name: Date, Length: 5108, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACNB_ended_2021-09-25  1999-12-31          28.2    7.2  41.45       3.425

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.625     14.05    17.475      20.9    24.325     27.75    31.175

  markup_80 markup_90 markup_100
0      34.6    38.025      41.45
                   stock  start_date current_price minall maxall each_markup  \
0  ACNB_ended_2021-09-25  1999-12-31          28.2    7.2  41.45       3.425

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.625     14.05    17.475      20.9    24.325     27.75    31.175

  markup_80 markup_90 markup_100
0      34.6    38.025      41.45
./ticker_data/ticker_data_2021-09-25 - Copy/ACOR_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2006-02-10  37.020000  44.880001  36.599998  40.320000  40.320000
1     2006-02-13  40.560001  40.799999  36.000000  36.000000  36.000000
2     2006-02-14  36.240002  37.680000  36.000000  36.000000  36.000000
3     2006-02-15  36.599998  37.320000  36.000000  36.240002  36.240002
4     2006-02-16  36.599998  38.340000  36.540001  37.680000  37.680000
...          ...        ...        ...        ...        ...        ...
3913  2021-08-30   4.250000   4.330000   4.080000   4.130000   4.130000
3914  2021-08-31   4.160000   4.390000   4.130000   4.230000   4.230000
3915  2021-09-01   4.250000   4.440000   4.180000   4.370000   4.370000
3916  2021-09-02   4.370000   4.450000   4.300000   4.350000   4.350000
3917  2021-09-03   4.320000   4.410000   4.280000   4.380000   4.380000

        Volume
0       155400
1       107300
2        16100
3         7000
4         5900
...        ...
3913  15510000
3914  27240000
3915  16480000
3916  10070000
3917   4600000

[3918 rows x 7 columns]
tolistdate: 0       2006-02-10
1       2006-02-13
2       2006-02-14
3       2006-02-15
4       2006-02-16
           ...
3913    2021-08-30
3914    2021-08-31
3915    2021-09-01
3916    2021-09-02
3917    2021-09-03
Name: Date, Length: 3918, dtype: object
                   stock  start_date current_price   minall maxall  \
0  ACOR_ended_2021-09-25  2006-02-10          4.38  2.51999  272.7

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      27.018    29.538    56.556    83.574   110.592    137.61   164.628

  markup_70 markup_80 markup_90 markup_100
0   191.646   218.664   245.682      272.7
                   stock  start_date current_price   minall maxall  \
0  ACOR_ended_2021-09-25  2006-02-10          4.38  2.51999  272.7

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      27.018    29.538    56.556    83.574   110.592    137.61   164.628

  markup_70 markup_80 markup_90 markup_100
0   191.646   218.664   245.682      272.7
./ticker_data/ticker_data_2021-09-25 - Copy/ACQRU_ended_2021-09-25.csv
           Date    Open   High     Low  Close  Adj Close   Volume
0    2021-03-09  10.010  10.05   9.995  10.00      10.00  9937900
1    2021-03-10  10.020  10.07  10.000  10.07      10.07  2570600
2    2021-03-11  10.070  10.20  10.050  10.11      10.11   631100
3    2021-03-12  10.110  10.15  10.090  10.12      10.12   379300
4    2021-03-15  10.210  10.49   9.990  10.20      10.20  2575900
..          ...     ...    ...     ...    ...        ...      ...
119  2021-08-30   9.875   9.88   9.870   9.88       9.88    60000
120  2021-08-31   9.850   9.86   9.850   9.86       9.86   220000
121  2021-09-01   9.860  10.01   9.860   9.90       9.90  2060000
122  2021-09-02   9.890   9.99   9.890   9.99       9.99   160000
123  2021-09-03   9.950   9.99   9.900   9.95       9.95  2150000

[124 rows x 7 columns]
tolistdate: 0      2021-03-09
1      2021-03-10
2      2021-03-11
3      2021-03-12
4      2021-03-15
          ...
119    2021-08-30
120    2021-08-31
121    2021-09-01
122    2021-09-02
123    2021-09-03
Name: Date, Length: 124, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ACQRU_ended_2021-09-25  2021-03-09          9.95  9.825  10.73      0.0905

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.9155    10.006   10.0965    10.187   10.2775    10.368   10.4585

  markup_80 markup_90 markup_100
0    10.549   10.6395      10.73
                    stock  start_date current_price minall maxall each_markup  \
0  ACQRU_ended_2021-09-25  2021-03-09          9.95  9.825  10.73      0.0905

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.9155    10.006   10.0965    10.187   10.2775    10.368   10.4585

  markup_80 markup_90 markup_100
0    10.549   10.6395      10.73
./ticker_data/ticker_data_2021-09-25 - Copy/ACQRW_ended_2021-09-25.csv
         Date  Open   High    Low  Close  Adj Close  Volume
0  2021-09-20   0.0  1.045  1.045  1.045      1.045     500
tolistdate: 0    2021-09-20
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ACQRW_ended_2021-09-25  2021-09-20         1.045  1.045  1.045           0

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.045     1.045     1.045     1.045     1.045     1.045     1.045

  markup_80 markup_90 markup_100
0     1.045     1.045      1.045
                    stock  start_date current_price minall maxall each_markup  \
0  ACQRW_ended_2021-09-25  2021-09-20         1.045  1.045  1.045           0

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.045     1.045     1.045     1.045     1.045     1.045     1.045

  markup_80 markup_90 markup_100
0     1.045     1.045      1.045
./ticker_data/ticker_data_2021-09-25 - Copy/ACQR_ended_2021-09-25.csv
          Date    Open    High    Low  Close  Adj Close    Volume
0   2021-05-21   9.770   9.800  9.750  9.800      9.800     40800
1   2021-05-24   9.800   9.800  9.800  9.800      9.800         0
2   2021-05-26   9.915  10.000  9.740  9.865      9.865     11300
3   2021-05-27   9.865   9.865  9.865  9.865      9.865         0
4   2021-06-02   9.870   9.935  9.870  9.935      9.935     22900
5   2021-06-03   9.940   9.940  9.900  9.900      9.900      2800
6   2021-06-04   9.950   9.950  9.660  9.900      9.900      2200
7   2021-06-07   9.900   9.900  9.900  9.900      9.900         0
8   2021-06-11  10.000  10.000  9.950  9.990      9.990     11600
9   2021-06-14   9.740  10.000  9.740  9.950      9.950      1700
10  2021-06-15   9.950   9.950  9.760  9.770      9.770      4300
11  2021-06-16   9.930   9.930  9.820  9.930      9.930      1300
12  2021-06-17   9.780   9.980  9.770  9.940      9.940      7300
13  2021-06-18   9.900   9.940  9.900  9.940      9.940      5000
14  2021-06-21   9.940   9.940  9.940  9.940      9.940         0
15  2021-06-24   9.800   9.800  9.800  9.800      9.800       200
16  2021-06-25   9.800   9.970  9.770  9.800      9.800      6700
17  2021-06-29  10.170  10.170  9.900  9.900      9.900      1300
18  2021-07-01   9.840   9.920  9.740  9.910      9.910       700
19  2021-07-02   9.740   9.870  9.740  9.870      9.870       300
20  2021-07-06   9.800   9.860  9.800  9.860      9.860      2000
21  2021-07-07   9.860   9.860  9.860  9.860      9.860         0
22  2021-07-08   9.750   9.840  9.750  9.840      9.840       700
23  2021-07-09   9.740   9.830  9.740  9.830      9.830      7000
24  2021-07-12   9.790   9.860  9.750  9.810      9.810      3600
25  2021-07-13   9.750  10.000  9.730  9.850      9.850     72600
26  2021-07-14   9.740   9.760  9.720  9.760      9.760     17300
27  2021-07-15   9.750   9.750  9.730  9.730      9.730      1300
28  2021-07-16   9.750   9.760  9.736  9.750      9.750      9400
29  2021-07-19   9.680   9.745  9.680  9.710      9.710     29900
30  2021-07-20   9.710   9.759  9.651  9.680      9.680     12300
31  2021-07-21   9.730   9.730  9.670  9.730      9.730       800
32  2021-07-22   9.730   9.730  9.730  9.730      9.730       800
33  2021-07-23   9.640   9.730  9.630  9.710      9.710      2200
34  2021-07-26   9.675   9.700  9.650  9.700      9.700     10400
35  2021-07-27   9.630   9.700  9.630  9.700      9.700       700
36  2021-07-28   9.640   9.730  9.640  9.730      9.730       300
37  2021-07-29   9.730   9.730  9.730  9.730      9.730         0
38  2021-08-03   9.720   9.720  9.710  9.720      9.720      1700
39  2021-08-04   9.660   9.720  9.660  9.720      9.720    220000
40  2021-08-05   9.700   9.700  9.695  9.695      9.695    170000
41  2021-08-06   9.680   9.720  9.641  9.707      9.707    240000
42  2021-08-09   9.707   9.707  9.707  9.707      9.707         0
43  2021-08-10   9.700   9.720  9.650  9.650      9.650    560000
44  2021-08-11   9.650   9.650  9.650  9.650      9.650     10000
45  2021-08-12   9.720   9.720  9.720  9.720      9.720     20000
46  2021-08-13   9.720   9.720  9.720  9.720      9.720         0
47  2021-08-18   9.650   9.650  9.650  9.650      9.650     30000
48  2021-08-19   9.640   9.640  9.640  9.640      9.640     20000
49  2021-08-20   9.630   9.654  9.630  9.654      9.654   5010000
50  2021-08-23   9.630   9.740  9.630  9.740      9.740   1150000
51  2021-08-24   9.740   9.740  9.740  9.740      9.740         0
52  2021-08-26   9.685   9.700  9.650  9.650      9.650    760000
53  2021-08-27   9.705   9.769  9.705  9.769      9.769     30000
54  2021-08-30   9.769   9.769  9.769  9.769      9.769         0
55  2021-08-31   9.760   9.760  9.669  9.669      9.669     60000
56  2021-09-01   9.670   9.670  9.670  9.670      9.670    220000
57  2021-09-02   9.670   9.670  9.670  9.670      9.670    550000
58  2021-09-03   9.696   9.710  9.630  9.710      9.710  80660000
tolistdate: 0     2021-05-21
1     2021-05-24
2     2021-05-26
3     2021-05-27
4     2021-06-02
5     2021-06-03
6     2021-06-04
7     2021-06-07
8     2021-06-11
9     2021-06-14
10    2021-06-15
11    2021-06-16
12    2021-06-17
13    2021-06-18
14    2021-06-21
15    2021-06-24
16    2021-06-25
17    2021-06-29
18    2021-07-01
19    2021-07-02
20    2021-07-06
21    2021-07-07
22    2021-07-08
23    2021-07-09
24    2021-07-12
25    2021-07-13
26    2021-07-14
27    2021-07-15
28    2021-07-16
29    2021-07-19
30    2021-07-20
31    2021-07-21
32    2021-07-22
33    2021-07-23
34    2021-07-26
35    2021-07-27
36    2021-07-28
37    2021-07-29
38    2021-08-03
39    2021-08-04
40    2021-08-05
41    2021-08-06
42    2021-08-09
43    2021-08-10
44    2021-08-11
45    2021-08-12
46    2021-08-13
47    2021-08-18
48    2021-08-19
49    2021-08-20
50    2021-08-23
51    2021-08-24
52    2021-08-26
53    2021-08-27
54    2021-08-30
55    2021-08-31
56    2021-09-01
57    2021-09-02
58    2021-09-03
Name: Date, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACQR_ended_2021-09-25  2021-05-21          9.71   9.63  10.17       0.054

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.684     9.738     9.792     9.846       9.9     9.954    10.008

  markup_80 markup_90 markup_100
0    10.062    10.116      10.17
                   stock  start_date current_price minall maxall each_markup  \
0  ACQR_ended_2021-09-25  2021-05-21          9.71   9.63  10.17       0.054

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.684     9.738     9.792     9.846       9.9     9.954    10.008

  markup_80 markup_90 markup_100
0    10.062    10.116      10.17
./ticker_data/ticker_data_2021-09-25 - Copy/ACRS_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2015-10-06  11.000000  11.000000  11.000000  11.000000  11.000000
1     2015-10-07  11.940000  11.980000  11.000000  11.050000  11.050000
2     2015-10-08  11.140000  11.300000  10.990000  11.050000  11.050000
3     2015-10-09  11.000000  13.980000  11.000000  12.500000  12.500000
4     2015-10-12  13.340000  14.120000  12.500000  13.600000  13.600000
...          ...        ...        ...        ...        ...        ...
1484  2021-08-30  15.670000  15.780000  15.190000  15.400000  15.400000
1485  2021-08-31  15.490000  16.280001  15.450000  16.209999  16.209999
1486  2021-09-01  16.260000  18.000000  16.049999  17.219999  17.219999
1487  2021-09-02  17.240000  18.459999  16.930000  17.600000  17.600000
1488  2021-09-03  17.549999  17.559999  16.760000  17.340000  17.340000

        Volume
0            0
1      1158700
2       125100
3       161900
4       325200
...        ...
1484  21280000
1485  36850000
1486  99100000
1487  53460000
1488  37510000

[1489 rows x 7 columns]
tolistdate: 0       2015-10-06
1       2015-10-07
2       2015-10-08
3       2015-10-09
4       2015-10-12
           ...
1484    2021-08-30
1485    2021-08-31
1486    2021-09-01
1487    2021-09-02
1488    2021-09-03
Name: Date, Length: 1489, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACRS_ended_2021-09-25  2015-10-06         17.34    0.7  33.88       3.318

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.018     7.336    10.654    13.972     17.29    20.608    23.926

  markup_80 markup_90 markup_100
0    27.244    30.562      33.88
                   stock  start_date current_price minall maxall each_markup  \
0  ACRS_ended_2021-09-25  2015-10-06         17.34    0.7  33.88       3.318

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.018     7.336    10.654    13.972     17.29    20.608    23.926

  markup_80 markup_90 markup_100
0    27.244    30.562      33.88
./ticker_data/ticker_data_2021-09-25 - Copy/ACRX_ended_2021-09-25.csv
            Date  Open  High   Low  Close  Adj Close    Volume
0     2011-02-11  5.00  5.09  4.51   4.55       4.55   1899700
1     2011-02-14  4.53  4.73  4.35   4.38       4.38     66300
2     2011-02-15  4.50  4.50  4.08   4.31       4.31     37400
3     2011-02-16  4.37  4.37  4.15   4.24       4.24      9500
4     2011-02-17  4.14  4.22  3.85   3.85       3.85     60000
...          ...   ...   ...   ...    ...        ...       ...
2648  2021-08-30  1.11  1.15  1.09   1.13       1.13  79240000
2649  2021-08-31  1.15  1.17  1.11   1.12       1.12  74890000
2650  2021-09-01  1.12  1.14  1.08   1.09       1.09  72700000
2651  2021-09-02  1.08  1.11  1.08   1.09       1.09  46650000
2652  2021-09-03  1.10  1.10  1.05   1.05       1.05  66650000

[2653 rows x 7 columns]
tolistdate: 0       2011-02-11
1       2011-02-14
2       2011-02-15
3       2011-02-16
4       2011-02-17
           ...
2648    2021-08-30
2649    2021-08-31
2650    2021-09-01
2651    2021-09-02
2652    2021-09-03
Name: Date, Length: 2653, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACRX_ended_2021-09-25  2011-02-11          1.05    0.7  13.64       1.294

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.994     3.288     4.582     5.876      7.17     8.464     9.758

  markup_80 markup_90 markup_100
0    11.052    12.346      13.64
                   stock  start_date current_price minall maxall each_markup  \
0  ACRX_ended_2021-09-25  2011-02-11          1.05    0.7  13.64       1.294

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.994     3.288     4.582     5.876      7.17     8.464     9.758

  markup_80 markup_90 markup_100
0    11.052    12.346      13.64
./ticker_data/ticker_data_2021-09-25 - Copy/ACST_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2012-02-07  12.100000  12.100000  12.100000  12.100000  12.100000
1     2012-02-14  16.500000  16.500000  16.500000  16.500000  16.500000
2     2012-02-15  16.500000  16.500000  16.500000  16.500000  16.500000
3     2012-03-19  21.799999  21.799999  21.799999  21.799999  21.799999
4     2012-03-22  21.299999  21.299999  20.900000  21.000000  21.000000
...          ...        ...        ...        ...        ...        ...
2258  2021-08-30   3.360000   3.360000   3.120000   3.200000   3.200000
2259  2021-08-31   2.940000   2.940000   2.580000   2.670000   2.670000
2260  2021-09-01   2.710000   2.770000   2.510000   2.550000   2.550000
2261  2021-09-02   2.530000   2.670000   2.520000   2.540000   2.540000
2262  2021-09-03   2.540000   2.560000   2.370000   2.380000   2.380000

         Volume
0             0
1           100
2             0
3             0
4           800
...         ...
2258  146477500
2259  311340000
2260  166040000
2261  198180000
2262  163970000

[2263 rows x 7 columns]
tolistdate: 0       2012-02-07
1       2012-02-14
2       2012-02-15
3       2012-03-19
4       2012-03-22
           ...
2258    2021-08-30
2259    2021-08-31
2260    2021-09-01
2261    2021-09-02
2262    2021-09-03
Name: Date, Length: 2263, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACST_ended_2021-09-25  2012-02-07          2.38   0.17     42       4.183

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.353     8.536    12.719    16.902    21.085    25.268    29.451

  markup_80 markup_90 markup_100
0    33.634    37.817         42
                   stock  start_date current_price minall maxall each_markup  \
0  ACST_ended_2021-09-25  2012-02-07          2.38   0.17     42       4.183

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.353     8.536    12.719    16.902    21.085    25.268    29.451

  markup_80 markup_90 markup_100
0    33.634    37.817         42
./ticker_data/ticker_data_2021-09-25 - Copy/ACTDU_ended_2021-09-25.csv
           Date   Open   High    Low   Close  Adj Close   Volume
0    2021-03-23  10.01  10.03  10.00  10.010     10.010  4455500
1    2021-03-24  10.00  10.00   9.91   9.911      9.911  1724900
2    2021-03-25   9.85  10.02   9.73   9.990      9.990   133200
3    2021-03-26   9.98  10.10   9.98  10.000     10.000   310400
4    2021-03-29  10.17  10.20   9.98  10.060     10.060    44200
..          ...    ...    ...    ...     ...        ...      ...
107  2021-08-30   9.80   9.80   9.80   9.800      9.800   100000
108  2021-08-31   9.85   9.86   9.85   9.860      9.860  1660000
109  2021-09-01   9.82   9.89   9.82   9.890      9.890   210000
110  2021-09-02   9.90   9.90   9.90   9.900      9.900   330000
111  2021-09-03   9.90   9.90   9.90   9.900      9.900  1550000

[112 rows x 7 columns]
tolistdate: 0      2021-03-23
1      2021-03-24
2      2021-03-25
3      2021-03-26
4      2021-03-29
          ...
107    2021-08-30
108    2021-08-31
109    2021-09-01
110    2021-09-02
111    2021-09-03
Name: Date, Length: 112, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ACTDU_ended_2021-09-25  2021-03-23           9.9   9.73  10.88       0.115

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.845      9.96    10.075     10.19    10.305     10.42    10.535

  markup_80 markup_90 markup_100
0     10.65    10.765      10.88
                    stock  start_date current_price minall maxall each_markup  \
0  ACTDU_ended_2021-09-25  2021-03-23           9.9   9.73  10.88       0.115

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.845      9.96    10.075     10.19    10.305     10.42    10.535

  markup_80 markup_90 markup_100
0     10.65    10.765      10.88
./ticker_data/ticker_data_2021-09-25 - Copy/ACTDW_ended_2021-09-25.csv
         Date  Open  High   Low  Close  Adj Close  Volume
0  2021-09-21  1.12  1.63  1.63   1.63       1.63      21
tolistdate: 0    2021-09-21
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ACTDW_ended_2021-09-25  2021-09-21          1.63   1.63   1.63           0

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      1.63      1.63      1.63      1.63      1.63      1.63      1.63

  markup_80 markup_90 markup_100
0      1.63      1.63       1.63
                    stock  start_date current_price minall maxall each_markup  \
0  ACTDW_ended_2021-09-25  2021-09-21          1.63   1.63   1.63           0

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      1.63      1.63      1.63      1.63      1.63      1.63      1.63

  markup_80 markup_90 markup_100
0      1.63      1.63       1.63
./ticker_data/ticker_data_2021-09-25 - Copy/ACTD_ended_2021-09-25.csv
          Date    Open   High   Low  Close  Adj Close   Volume
0   2021-05-24   9.800   9.80  9.80  9.800      9.800    74500
1   2021-05-25   9.830   9.84  9.83  9.830      9.830     2400
2   2021-05-26  10.320  10.32  9.80  9.800      9.800     2900
3   2021-05-27   9.800   9.80  9.80  9.800      9.800        0
4   2021-05-28   9.750   9.75  9.75  9.750      9.750     7700
..         ...     ...    ...   ...    ...        ...      ...
66  2021-08-30   9.610   9.72  9.61  9.650      9.650  8620000
67  2021-08-31   9.650   9.66  9.64  9.650      9.650  1080000
68  2021-09-01   9.650   9.70  9.65  9.654      9.654  1270000
69  2021-09-02   9.679   9.70  9.65  9.680      9.680   790000
70  2021-09-03   9.680   9.74  9.67  9.730      9.730  2890000

[71 rows x 7 columns]
tolistdate: 0     2021-05-24
1     2021-05-25
2     2021-05-26
3     2021-05-27
4     2021-05-28
         ...
66    2021-08-30
67    2021-08-31
68    2021-09-01
69    2021-09-02
70    2021-09-03
Name: Date, Length: 71, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACTD_ended_2021-09-25  2021-05-24          9.73   9.61  10.32       0.071


0    10.178    10.249      10.32
./ticker_data/ticker_data_2021-09-25 - Copy/ACTG_ended_2021-09-25.csv
            Date  Open  High   Low  Close  Adj Close     Volume
0     2002-12-16  3.40  3.40  1.79   1.85   1.671283      14200
1     2002-12-17  2.00  2.20  1.65   2.00   1.806792      47000
2     2002-12-18  2.45  2.65  1.80   1.87   1.689351     138200
3     2002-12-19  1.88  1.95  1.81   1.88   1.698385     139500
4     2002-12-20  1.98  2.33  1.80   1.91   1.725487     327200
...          ...   ...   ...   ...    ...        ...        ...
4708  2021-08-30  5.75  5.96  5.66   5.89   5.890000   49360000
4709  2021-08-31  5.94  6.15  5.90   6.09   6.090000   53460000
4710  2021-09-01  6.09  6.74  6.02   6.32   6.320000  123120000
4711  2021-09-02  6.31  6.63  5.70   6.39   6.390000   87240000
4712  2021-09-03  6.36  6.60  6.27   6.59   6.590000   35450000

[4713 rows x 7 columns]
tolistdate: 0       2002-12-16
1       2002-12-17
2       2002-12-18
3       2002-12-19
4       2002-12-20
           ...
4708    2021-08-30
4709    2021-08-31
4710    2021-09-01
4711    2021-09-02
4712    2021-09-03
Name: Date, Length: 4713, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACTG_ended_2021-09-25  2002-12-16          6.59   0.96  47.24       4.628

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.588    10.216    14.844    19.472      24.1    28.728    33.356

  markup_80 markup_90 markup_100
0    37.984    42.612      47.24
                   stock  start_date current_price minall maxall each_markup  \
0  ACTG_ended_2021-09-25  2002-12-16          6.59   0.96  47.24       4.628

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.588    10.216    14.844    19.472      24.1    28.728    33.356

  markup_80 markup_90 markup_100
0    37.984    42.612      47.24
./ticker_data/ticker_data_2021-09-25 - Copy/ACVA_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2021-03-24  32.000000  34.500000  29.000000  31.250000  31.250000
1    2021-03-25  30.237000  34.991001  26.490000  30.000000  30.000000
2    2021-03-26  30.110001  32.000000  29.000000  30.270000  30.270000
3    2021-03-29  30.000000  33.730999  29.795000  32.360001  32.360001
4    2021-03-30  33.000000  35.779999  32.400002  33.480000  33.480000
..          ...        ...        ...        ...        ...        ...
109  2021-08-30  18.990000  20.309999  18.750000  20.160000  20.160000
110  2021-08-31  20.100000  21.219999  19.879999  20.410000  20.410000
111  2021-09-01  20.389999  20.695000  19.870001  20.100000  20.100000
112  2021-09-02  19.910000  20.480000  19.719999  20.129999  20.129999
113  2021-09-03  20.000000  20.330000  19.650000  20.030001  20.030001

        Volume
0     11332700
1      3092600
2      1067900
3      1517300
4      1988800
..         ...
109   68280000
110   88510000
111  122850000
112  144910000
113  117260000

[114 rows x 7 columns]
tolistdate: 0      2021-03-24
1      2021-03-25
2      2021-03-26
3      2021-03-29
4      2021-03-30
          ...
109    2021-08-30
110    2021-08-31
111    2021-09-01
112    2021-09-02
113    2021-09-03
Name: Date, Length: 114, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ACVA_ended_2021-09-25  2021-03-24         20.03  18.18  37.77       1.959

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    20.139    22.098    24.057    26.016    27.975    29.934    31.893

  markup_80 markup_90 markup_100
0    33.852    35.811      37.77
                   stock  start_date current_price minall maxall each_markup  \
0  ACVA_ended_2021-09-25  2021-03-24         20.03  18.18  37.77       1.959

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    20.139    22.098    24.057    26.016    27.975    29.934    31.893

  markup_80 markup_90 markup_100
0    33.852    35.811      37.77
./ticker_data/ticker_data_2021-09-25 - Copy/ADAG_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2021-02-09  20.400000  31.000000  20.209999  29.990000  29.990000
1    2021-02-10  27.618000  28.500000  26.010000  26.200001  26.200001
2    2021-02-11  26.000000  31.830000  26.000000  29.600000  29.600000
3    2021-02-12  28.010000  28.740000  26.209999  27.660000  27.660000
4    2021-02-16  26.500000  26.950001  25.379999  25.559999  25.559999
..          ...        ...        ...        ...        ...        ...
139  2021-08-30  16.660000  16.980000  16.020000  16.785999  16.785999
140  2021-08-31  16.719999  16.719999  15.690000  16.160000  16.160000
141  2021-09-01  17.350000  18.299999  16.299999  16.490000  16.490000
142  2021-09-02  17.000000  17.629999  16.610001  16.820000  16.820000
143  2021-09-03  16.610001  17.155001  16.610001  16.770000  16.770000

      Volume
0    5135300
1    1014900
2     499800
3     309300
4     187300
..       ...
139  1780000
140  2470000
141  4560000
142  2160000
143   520000

[144 rows x 7 columns]
tolistdate: 0      2021-02-09
1      2021-02-10
2      2021-02-11
3      2021-02-12
4      2021-02-16
          ...
139    2021-08-30
140    2021-08-31
141    2021-09-01
142    2021-09-02
143    2021-09-03
Name: Date, Length: 144, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ADAG_ended_2021-09-25  2021-02-09         16.77  11.11  31.83       2.072

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.182    15.254    17.326    19.398     21.47    23.542    25.614

  markup_80 markup_90 markup_100
0    27.686    29.758      31.83
                   stock  start_date current_price minall maxall each_markup  \
0  ADAG_ended_2021-09-25  2021-02-09         16.77  11.11  31.83       2.072

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.182    15.254    17.326    19.398     21.47    23.542    25.614

  markup_80 markup_90 markup_100
0    27.686    29.758      31.83
./ticker_data/ticker_data_2021-09-25 - Copy/ADAP_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2015-05-06  19.250000  19.500000  15.510000  16.000000  16.000000
1     2015-05-07  15.750000  17.250000  15.750000  17.230000  17.230000
2     2015-05-08  17.250000  17.690001  16.590000  17.180000  17.180000
3     2015-05-11  17.469999  17.469999  16.860001  17.000000  17.000000
4     2015-05-12  17.000000  17.048000  16.750000  16.879999  16.879999
...          ...        ...        ...        ...        ...        ...
1590  2021-08-30   5.260000   5.420000   4.960000   5.240000   5.240000
1591  2021-08-31   5.210000   5.330000   5.140000   5.170000   5.170000
1592  2021-09-01   5.140000   5.250000   4.960000   5.050000   5.050000
1593  2021-09-02   5.050000   5.090000   4.920000   4.940000   4.940000
1594  2021-09-03   4.950000   5.120000   4.900000   4.940000   4.940000

         Volume
0       8301700
1       1766500
2        884100
3        240500
4        338300
...         ...
1590  167750000
1591   96660000
1592  121320000
1593  114320000
1594  134260000

[1595 rows x 7 columns]
tolistdate: 0       2015-05-06
1       2015-05-07
2       2015-05-08
3       2015-05-11
4       2015-05-12
           ...
1590    2021-08-30
1591    2021-08-31
1592    2021-09-01
1593    2021-09-02
1594    2021-09-03
Name: Date, Length: 1595, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ADAP_ended_2021-09-25  2015-05-06          4.94  0.709  21.57      2.0861

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.7951    4.8812    6.9673    9.0534   11.1395   13.2256   15.3117

  markup_80 markup_90 markup_100
0   17.3978   19.4839      21.57
                   stock  start_date current_price minall maxall each_markup  \
0  ADAP_ended_2021-09-25  2015-05-06          4.94  0.709  21.57      2.0861

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.7951    4.8812    6.9673    9.0534   11.1395   13.2256   15.3117

  markup_80 markup_90 markup_100
0   17.3978   19.4839      21.57
./ticker_data/ticker_data_2021-09-25 - Copy/ADBE_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31   16.515625   16.875000   16.500000   16.812500   16.693562
1     2000-01-03   16.812500   16.875000   16.062500   16.390625   16.274673
2     2000-01-04   15.750000   16.453125   14.984375   15.015625   14.909401
3     2000-01-05   14.562500   15.687500   14.562500   15.312500   15.204173
4     2000-01-06   15.359375   15.656250   15.156250   15.437500   15.328290
...          ...         ...         ...         ...         ...         ...
5449  2021-08-30  659.780029  667.669983  659.780029  665.989990  665.989990
5450  2021-08-31  667.900024  667.900024  660.460022  663.700012  663.700012
5451  2021-09-01  664.510010  668.960022  662.000000  665.890015  665.890015
5452  2021-09-02  669.820007  669.849976  661.669983  664.640015  664.640015
5453  2021-09-03  664.429993  673.880005  664.299988  666.590027  666.590027

         Volume
0       2882000
1       7384400
2       7813200
3      14927200
4      10221200
...         ...
5449  134150000
5450  187690000
5451  126120000
5452  140350000
5453  164030000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ADBE_ended_2021-09-25  1999-12-31        666.59  8.245  673.88     66.5635

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   74.8085   141.372   207.936   274.499   341.063   407.626    474.19

  markup_80 markup_90 markup_100
0   540.753   607.317     673.88
                   stock  start_date current_price minall  maxall each_markup  \
0  ADBE_ended_2021-09-25  1999-12-31        666.59  8.245  673.88     66.5635

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   74.8085   141.372   207.936   274.499   341.063   407.626    474.19

  markup_80 markup_90 markup_100
0   540.753   607.317     673.88
./ticker_data/ticker_data_2021-09-25 - Copy/ADERU_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close   Volume
0    2021-01-15  10.41  10.68  10.40  10.55      10.55  5250300
1    2021-01-19  10.55  10.75  10.55  10.65      10.65   334100
2    2021-01-20  10.65  10.85  10.60  10.66      10.66   364000
3    2021-01-21  10.62  10.72  10.56  10.61      10.61   486300
4    2021-01-22  10.74  11.00  10.65  10.70      10.70   453900
..          ...    ...    ...    ...    ...        ...      ...
154  2021-08-30  10.05  10.05  10.05  10.05      10.05   110000
155  2021-08-31  10.08  10.08  10.00  10.00      10.00  1160000
156  2021-09-01  10.00  10.00  10.00  10.00      10.00        0
157  2021-09-02  10.05  10.05  10.01  10.05      10.05    40000
158  2021-09-03  10.05  10.05  10.05  10.05      10.05        0

[159 rows x 7 columns]
tolistdate: 0      2021-01-15
1      2021-01-19
2      2021-01-20
3      2021-01-21
4      2021-01-22
          ...
154    2021-08-30
155    2021-08-31
156    2021-09-01
157    2021-09-02
158    2021-09-03
Name: Date, Length: 159, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ADERU_ended_2021-09-25  2021-01-15         10.05   9.86  11.09       0.123

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.983    10.106    10.229    10.352    10.475    10.598    10.721

  markup_80 markup_90 markup_100
0    10.844    10.967      11.09
                    stock  start_date current_price minall maxall each_markup  \
0  ADERU_ended_2021-09-25  2021-01-15         10.05   9.86  11.09       0.123

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.983    10.106    10.229    10.352    10.475    10.598    10.721

  markup_80 markup_90 markup_100
0    10.844    10.967      11.09
./ticker_data/ticker_data_2021-09-25 - Copy/ADERW_ended_2021-09-25.csv
         Date  Open  High  Low   Close  Adj Close  Volume
0  2021-09-22   0.9  0.85  0.8  0.8498     0.8498   33045
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ADERW_ended_2021-09-25  2021-09-22        0.8498    0.8   0.85       0.005

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.805      0.81     0.815      0.82     0.825      0.83     0.835

  markup_80 markup_90 markup_100
0      0.84     0.845       0.85
                    stock  start_date current_price minall maxall each_markup  \
0  ADERW_ended_2021-09-25  2021-09-22        0.8498    0.8   0.85       0.005

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.805      0.81     0.815      0.82     0.825      0.83     0.835

  markup_80 markup_90 markup_100
0      0.84     0.845       0.85
./ticker_data/ticker_data_2021-09-25 - Copy/ADER_ended_2021-09-25.csv
           Date   Open  High   Low  Close  Adj Close   Volume
0    2021-03-08  9.900  9.90  9.90  9.900      9.900     1000
1    2021-03-09  9.850  9.90  9.70  9.752      9.752    78900
2    2021-03-10  9.795  9.90  9.71  9.800      9.800   191500
3    2021-03-11  9.890  9.89  9.75  9.850      9.850    48600
4    2021-03-12  9.850  9.90  9.60  9.820      9.820    58500
..          ...    ...   ...   ...    ...        ...      ...
121  2021-08-30  9.640  9.66  9.64  9.660      9.660   110000
122  2021-08-31  9.610  9.69  9.61  9.690      9.690  2620000
123  2021-09-01  9.670  9.68  9.67  9.680      9.680    50000
124  2021-09-02  9.660  9.68  9.66  9.680      9.680   330000
125  2021-09-03  9.660  9.70  9.66  9.700      9.700  5900000

[126 rows x 7 columns]
tolistdate: 0      2021-03-08
1      2021-03-09
2      2021-03-10
3      2021-03-11
4      2021-03-12
          ...
121    2021-08-30
122    2021-08-31
123    2021-09-01
124    2021-09-02
125    2021-09-03
Name: Date, Length: 126, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ADER_ended_2021-09-25  2021-03-08           9.7   9.57   9.92       0.035

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.605      9.64     9.675      9.71     9.745      9.78     9.815

  markup_80 markup_90 markup_100
0      9.85     9.885       9.92
                   stock  start_date current_price minall maxall each_markup  \
0  ADER_ended_2021-09-25  2021-03-08           9.7   9.57   9.92       0.035

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.605      9.64     9.675      9.71     9.745      9.78     9.815

  markup_80 markup_90 markup_100
0      9.85     9.885       9.92
./ticker_data/ticker_data_2021-09-25 - Copy/ADES_ended_2021-09-25.csv
            Date   Open  High    Low  Close  Adj Close    Volume
0     2004-01-23  4.275  4.40  4.125  4.175   3.160914     18000
1     2004-01-26  4.175  4.30  4.175  4.250   3.217696     27200
2     2004-01-27  4.250  4.25  4.200  4.225   3.198769     11000
3     2004-01-28  4.225  4.25  4.225  4.225   3.198769     27000
4     2004-01-29  4.300  4.45  4.150  4.215   3.191198     58400
...          ...    ...   ...    ...    ...        ...       ...
4426  2021-08-30  7.040  7.07  6.780  6.820   6.820000  10540000
4427  2021-08-31  6.770  6.99  6.700  6.810   6.810000  11710000
4428  2021-09-01  6.770  6.82  6.710  6.770   6.770000   7580000
4429  2021-09-02  6.740  6.93  6.560  6.700   6.700000  21050000
4430  2021-09-03  6.740  6.86  6.630  6.810   6.810000   7880000

[4431 rows x 7 columns]

tolistdate: 0       2004-01-23
1       2004-01-26
2       2004-01-27
3       2004-01-28
4       2004-01-29
           ...
4426    2021-08-30
4427    2021-08-31
4428    2021-09-01
4429    2021-09-02
4430    2021-09-03
Name: Date, Length: 4431, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ADES_ended_2021-09-25  2004-01-23          6.81  1.025  29.165       2.814

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.839     6.653     9.467    12.281    15.095    17.909    20.723

  markup_80 markup_90 markup_100
0    23.537    26.351     29.165
                   stock  start_date current_price minall  maxall each_markup  \
0  ADES_ended_2021-09-25  2004-01-23          6.81  1.025  29.165       2.814

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.839     6.653     9.467    12.281    15.095    17.909    20.723

  markup_80 markup_90 markup_100
0    23.537    26.351     29.165
./ticker_data/ticker_data_2021-09-25 - Copy/ADILW_ended_2021-09-25.csv
         Date    Open  High   Low  Close  Adj Close  Volume
0  2021-09-21  0.7018  0.85  0.83   0.85       0.85       4
tolistdate: 0    2021-09-21
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ADILW_ended_2021-09-25  2021-09-21          0.85   0.83   0.85       0.002

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.832     0.834     0.836     0.838      0.84     0.842     0.844

  markup_80 markup_90 markup_100
0     0.846     0.848       0.85
                    stock  start_date current_price minall maxall each_markup  \
0  ADILW_ended_2021-09-25  2021-09-21          0.85   0.83   0.85       0.002

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.832     0.834     0.836     0.838      0.84     0.842     0.844

  markup_80 markup_90 markup_100
0     0.846     0.848       0.85
./ticker_data/ticker_data_2021-09-25 - Copy/ADIL_ended_2021-09-25.csv
           Date  Open  High   Low  Close  Adj Close    Volume
0    2018-07-27  4.00  4.40  3.95   4.05       4.05    285400
1    2018-07-30  4.10  4.25  3.96   4.01       4.01     43700
2    2018-07-31  3.75  4.16  3.75   4.00       4.00     16400
3    2018-08-01  3.75  4.35  3.75   4.25       4.25     13900
4    2018-08-02  4.30  4.30  4.00   4.00       4.00      6700
..          ...   ...   ...   ...    ...        ...       ...
777  2021-08-30  4.22  4.39  3.89   4.13       4.13  93490000
778  2021-08-31  4.24  4.37  4.04   4.10       4.10  39710000
779  2021-09-01  4.14  4.18  4.06   4.13       4.13  27030000
780  2021-09-02  4.22  4.35  4.13   4.31       4.31  37180000
781  2021-09-03  4.32  4.38  4.22   4.35       4.35  15840000

[782 rows x 7 columns]
tolistdate: 0      2018-07-27
1      2018-07-30
2      2018-07-31
3      2018-08-01
4      2018-08-02
          ...
777    2021-08-30
778    2021-08-31
779    2021-09-01
780    2021-09-02
781    2021-09-03
Name: Date, Length: 782, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ADIL_ended_2021-09-25  2018-07-27          4.35      1   9.44       0.844

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.844     2.688     3.532     4.376      5.22     6.064     6.908

  markup_80 markup_90 markup_100
0     7.752     8.596       9.44
                   stock  start_date current_price minall maxall each_markup  \
0  ADIL_ended_2021-09-25  2018-07-27          4.35      1   9.44       0.844

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.844     2.688     3.532     4.376      5.22     6.064     6.908

  markup_80 markup_90 markup_100
0     7.752     8.596       9.44
./ticker_data/ticker_data_2021-09-25 - Copy/ADI_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31   45.750000   47.250000   45.656250   46.500000   30.839806
1     2000-01-03   46.750000   46.937500   44.000000   45.093750   29.907148
2     2000-01-04   44.750000   45.750000   42.781250   42.812500   28.394154
3     2000-01-05   42.812500   44.125000   41.593750   43.437500   28.808693
4     2000-01-06   43.437500   43.812500   41.625000   42.250000   28.021109
...          ...         ...         ...         ...         ...         ...
5450  2021-08-30  166.970001  168.270004  166.649994  166.979996  166.979996
5451  2021-08-31  166.149994  166.520004  161.339996  162.949997  162.949997
5452  2021-09-01  163.770004  164.199997  161.039993  161.110001  161.110001
5453  2021-09-02  162.130005  162.940002  161.220001  162.619995  162.619995
5454  2021-09-03  162.520004  163.500000  161.740005  162.440002  162.440002

         Volume
0        591800
1       3655600
2       2533200
3       3228000
4       2601000
...         ...
5450  490160000
5451  913630000
5452  651360000
5453  451470000
5454  238560000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                  stock  start_date current_price minall  maxall each_markup  \
0  ADI_ended_2021-09-25  1999-12-31        162.44  15.29  175.25      15.996

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    31.286    47.282    63.278    79.274     95.27   111.266   127.262

  markup_80 markup_90 markup_100
0   143.258   159.254     175.25
                  stock  start_date current_price minall  maxall each_markup  \
0  ADI_ended_2021-09-25  1999-12-31        162.44  15.29  175.25      15.996

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    31.286    47.282    63.278    79.274     95.27   111.266   127.262

  markup_80 markup_90 markup_100
0   143.258   159.254     175.25
./ticker_data/ticker_data_2021-09-25 - Copy/ADMA_ended_2021-09-25.csv
            Date  Open   High   Low  Close  Adj Close    Volume
0     2013-10-17  7.00  8.910  7.00   8.55       8.55         0
1     2013-10-18  8.54  8.550  8.50   8.53       8.53     28400
2     2013-10-21  8.50  8.500  8.05   8.40       8.40     24500
3     2013-10-22  8.40  8.500  8.40   8.45       8.45      5100
4     2013-10-23  8.45  8.500  8.45   8.49       8.49     16900
...          ...   ...    ...   ...    ...        ...       ...
1968  2021-08-30  1.38  1.385  1.32   1.33       1.33  68860000
1969  2021-08-31  1.32  1.370  1.32   1.34       1.34  71790000
1970  2021-09-01  1.33  1.360  1.32   1.33       1.33  70350000
1971  2021-09-02  1.34  1.360  1.32   1.35       1.35  81450000
1972  2021-09-03  1.33  1.340  1.33   1.33       1.33  48900000

[1973 rows x 7 columns]
tolistdate: 0       2013-10-17
1       2013-10-18
2       2013-10-21
3       2013-10-22
4       2013-10-23
           ...
1968    2021-08-30
1969    2021-08-31
1970    2021-09-01
1971    2021-09-02
1972    2021-09-03
Name: Date, Length: 1973, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ADMA_ended_2021-09-25  2013-10-17          1.33  1.152     14      1.2848

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.4368    3.7216    5.0064    6.2912     7.576    8.8608   10.1456

  markup_80 markup_90 markup_100
0   11.4304   12.7152         14
                   stock  start_date current_price minall maxall each_markup  \
0  ADMA_ended_2021-09-25  2013-10-17          1.33  1.152     14      1.2848

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.4368    3.7216    5.0064    6.2912     7.576    8.8608   10.1456

  markup_80 markup_90 markup_100
0   11.4304   12.7152         14
./ticker_data/ticker_data_2021-09-25 - Copy/ADMP_ended_2021-09-25.csv
            Date      Open     High      Low    Close  Adj Close     Volume
0     1999-12-31  552.5000  595.000  552.500  573.750    573.750        700
1     2000-01-03  584.3750  595.000  552.500  563.125    563.125        100
2     2000-01-04  563.1250  584.375  552.500  552.500    552.500        100
3     2000-01-05  552.5000  584.375  552.500  584.375    584.375          0
4     2000-01-06  579.0625  669.375  563.125  595.000    595.000        400
...          ...       ...      ...      ...      ...        ...        ...
5007  2021-08-30    1.0900    1.100    1.050    1.050      1.050  148550000
5008  2021-08-31    1.0600    1.130    1.050    1.090      1.090  245200000
5009  2021-09-01    1.1000    1.140    1.100    1.110      1.110  153030000
5010  2021-09-02    1.1600    1.170    1.120    1.140      1.140  418170000
5011  2021-09-03    1.1500    1.150    1.080    1.110      1.110  322640000

[5012 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5007    2021-08-30
5008    2021-08-31
5009    2021-09-01
5010    2021-09-02
5011    2021-09-03
Name: Date, Length: 5012, dtype: object
                   stock  start_date current_price minall   maxall  \
0  ADMP_ended_2021-09-25  1999-12-31          1.11   0.27  1795.62

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     179.535   179.806   359.341   538.877   718.412   897.948   1077.48

  markup_70 markup_80 markup_90 markup_100
0   1257.02   1436.55   1616.09    1795.62
                   stock  start_date current_price minall   maxall  \
0  ADMP_ended_2021-09-25  1999-12-31          1.11   0.27  1795.62

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     179.535   179.806   359.341   538.877   718.412   897.948   1077.48

  markup_70 markup_80 markup_90 markup_100
0   1257.02   1436.55   1616.09    1795.62
./ticker_data/ticker_data_2021-09-25 - Copy/ADMS_ended_2021-09-25.csv
            Date   Open    High     Low  Close  Adj Close    Volume
0     2014-04-10  16.85  17.240  14.000  14.01      14.01   2408700
1     2014-04-11  13.74  13.904  12.020  13.00      13.00    197200
2     2014-04-14  12.96  13.890  12.710  13.60      13.60     36500
3     2014-04-15  14.44  14.440  13.100  13.39      13.39     40500
4     2014-04-16  13.40  13.470  13.030  13.20      13.20     32300
...          ...    ...     ...     ...    ...        ...       ...
1859  2021-08-30   4.50   4.690   4.470   4.53       4.53  10000000
1860  2021-08-31   4.57   4.780   4.561   4.71       4.71  16000000
1861  2021-09-01   4.72   4.780   4.580   4.65       4.65   4680000
1862  2021-09-02   4.64   4.740   4.630   4.73       4.73   7740000
1863  2021-09-03   4.73   4.825   4.660   4.75       4.75   9350000

[1864 rows x 7 columns]
tolistdate: 0       2014-04-10
1       2014-04-11
2       2014-04-14
3       2014-04-15
4       2014-04-16
           ...
1859    2021-08-30
1860    2021-08-31
1861    2021-09-01
1862    2021-09-02
1863    2021-09-03
Name: Date, Length: 1864, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ADMS_ended_2021-09-25  2014-04-10          4.75    1.9     44        4.21

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      6.11     10.32     14.53     18.74     22.95     27.16     31.37

  markup_80 markup_90 markup_100
0     35.58     39.79         44
                   stock  start_date current_price minall maxall each_markup  \
0  ADMS_ended_2021-09-25  2014-04-10          4.75    1.9     44        4.21

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      6.11     10.32     14.53     18.74     22.95     27.16     31.37

  markup_80 markup_90 markup_100
0     35.58     39.79         44
./ticker_data/ticker_data_2021-09-25 - Copy/ADNWW_ended_2021-09-25.csv
         Date  Open  High   Low  Close  Adj Close  Volume
0  2021-09-22  0.85  1.43  1.25   1.42       1.42  105288
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ADNWW_ended_2021-09-25  2021-09-22          1.42   1.25   1.43       0.018

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.268     1.286     1.304     1.322      1.34     1.358     1.376

  markup_80 markup_90 markup_100
0     1.394     1.412       1.43
                    stock  start_date current_price minall maxall each_markup  \
0  ADNWW_ended_2021-09-25  2021-09-22          1.42   1.25   1.43       0.018

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.268     1.286     1.304     1.322      1.34     1.358     1.376

  markup_80 markup_90 markup_100
0     1.394     1.412       1.43
./ticker_data/ticker_data_2021-09-25 - Copy/ADN_ended_2021-09-25.csv
           Date   Open    High    Low   Close  Adj Close    Volume
0    2020-08-06  10.29  10.300  10.26  10.260     10.260      2900
1    2020-08-07  10.26  10.300  10.25  10.286     10.286     14600
2    2020-08-10  10.30  10.300  10.30  10.300     10.300      4000
3    2020-08-11  10.29  10.290  10.29  10.290     10.290      8200
4    2020-08-12  10.29  10.339  10.29  10.339     10.339       400
..          ...    ...     ...    ...     ...        ...       ...
268  2021-08-30   7.87   7.870   7.37   7.470      7.470  21890000
269  2021-08-31   7.41   7.630   7.22   7.400      7.400  22260000
270  2021-09-01   7.57   7.840   7.45   7.720      7.720  22360000
271  2021-09-02   7.71   8.040   7.62   7.880      7.880  27540000
272  2021-09-03   7.91   8.070   7.69   8.040      8.040  24120000

[273 rows x 7 columns]
tolistdate: 0      2020-08-06
1      2020-08-07
2      2020-08-10
3      2020-08-11
4      2020-08-12
          ...
268    2021-08-30
269    2021-08-31
270    2021-09-01
271    2021-09-02
272    2021-09-03
Name: Date, Length: 273, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  ADN_ended_2021-09-25  2020-08-06          8.04   6.56  19.21       1.265

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.825      9.09    10.355     11.62    12.885     14.15    15.415

  markup_80 markup_90 markup_100
0     16.68    17.945      19.21
                  stock  start_date current_price minall maxall each_markup  \
0  ADN_ended_2021-09-25  2020-08-06          8.04   6.56  19.21       1.265

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.825      9.09    10.355     11.62    12.885     14.15    15.415

  markup_80 markup_90 markup_100
0     16.68    17.945      19.21
./ticker_data/ticker_data_2021-09-25 - Copy/ADOCR_ended_2021-09-25.csv
         Date      Open      High       Low     Close  Adj Close  Volume
0  2021-09-22  0.369899  0.369899  0.369899  0.369899   0.369899     202
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price    minall    maxall  \
0  ADOCR_ended_2021-09-25  2021-09-22      0.369899  0.369899  0.369899

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0           0  0.369899  0.369899  0.369899  0.369899  0.369899  0.369899

  markup_70 markup_80 markup_90 markup_100

0  0.369899  0.369899  0.369899   0.369899
                    stock  start_date current_price    minall    maxall  \
0  ADOCR_ended_2021-09-25  2021-09-22      0.369899  0.369899  0.369899

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0           0  0.369899  0.369899  0.369899  0.369899  0.369899  0.369899

  markup_70 markup_80 markup_90 markup_100
0  0.369899  0.369899  0.369899   0.369899
./ticker_data/ticker_data_2021-09-25 - Copy/ADOCW_ended_2021-09-25.csv
         Date    Open    High     Low   Close  Adj Close  Volume
0  2021-09-22  0.2701  0.2498  0.2077  0.2187     0.2187    6302
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price  minall  maxall  \
0  ADOCW_ended_2021-09-25  2021-09-22        0.2187  0.2077  0.2498

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00421   0.21191   0.21612   0.22033   0.22454   0.22875   0.23296

  markup_70 markup_80 markup_90 markup_100
0   0.23717   0.24138   0.24559     0.2498
                    stock  start_date current_price  minall  maxall  \
0  ADOCW_ended_2021-09-25  2021-09-22        0.2187  0.2077  0.2498

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00421   0.21191   0.21612   0.22033   0.22454   0.22875   0.23296

  markup_70 markup_80 markup_90 markup_100
0   0.23717   0.24138   0.24559     0.2498
./ticker_data/ticker_data_2021-09-25 - Copy/ADOC_ended_2021-09-25.csv
           Date    Open    High     Low   Close  Adj Close   Volume
0    2020-12-10   9.850   9.980   9.850   9.980      9.980   298900
1    2020-12-11   9.990  10.104   9.950  10.104     10.104   726300
2    2020-12-14  10.100  10.100   9.980  10.000     10.000    70500
3    2020-12-15  10.000  10.028   9.970  10.000     10.000   241700
4    2020-12-16   9.991  10.000   9.965   9.970      9.970   119900
..          ...     ...     ...     ...     ...        ...      ...
165  2021-08-30  10.070  10.070  10.070  10.070     10.070    50000
166  2021-08-31  10.086  10.090  10.070  10.070     10.070  1150000
167  2021-09-01  10.090  10.114  10.090  10.114     10.114  8300000
168  2021-09-02  10.120  10.120  10.120  10.120     10.120    30000
169  2021-09-03  10.120  10.120  10.120  10.120     10.120        0

[170 rows x 7 columns]
tolistdate: 0      2020-12-10
1      2020-12-11
2      2020-12-14
3      2020-12-15
4      2020-12-16
          ...
165    2021-08-30
166    2021-08-31
167    2021-09-01
168    2021-09-02
169    2021-09-03
Name: Date, Length: 170, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ADOC_ended_2021-09-25  2020-12-10         10.12   9.85  10.37       0.052

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.902     9.954    10.006    10.058     10.11    10.162    10.214

  markup_80 markup_90 markup_100
0    10.266    10.318      10.37
                   stock  start_date current_price minall maxall each_markup  \
0  ADOC_ended_2021-09-25  2020-12-10         10.12   9.85  10.37       0.052

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.902     9.954    10.006    10.058     10.11    10.162    10.214

  markup_80 markup_90 markup_100
0    10.266    10.318      10.37
./ticker_data/ticker_data_2021-09-25 - Copy/ADPT_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-06-27  39.490002  40.619999  36.209999  40.299999  40.299999
1    2019-06-28  42.099998  48.825001  41.250000  48.299999  48.299999
2    2019-07-01  51.000000  51.000000  39.580002  40.099998  40.099998
3    2019-07-02  40.000000  40.400002  37.950001  38.889999  38.889999
4    2019-07-03  39.549999  39.549999  38.599998  39.160000  39.160000
..          ...        ...        ...        ...        ...        ...
548  2021-08-30  35.119999  36.480000  35.119999  35.790001  35.790001
549  2021-08-31  35.730000  36.779999  35.259998  36.320000  36.320000
550  2021-09-01  36.360001  38.049999  36.360001  37.849998  37.849998
551  2021-09-02  38.290001  39.759998  38.029999  39.240002  39.240002
552  2021-09-03  39.200001  39.869999  38.750000  39.509998  39.509998

       Volume
0    11245600
1     5403800
2     4314600
3     1877700
4     1010600
..        ...
548  36310000
549  44160000
550  48480000
551  55400000
552  35850000

[553 rows x 7 columns]
tolistdate: 0      2019-06-27
1      2019-06-28
2      2019-07-01
3      2019-07-02
4      2019-07-03
          ...
548    2021-08-30
549    2021-08-31
550    2021-09-01
551    2021-09-02
552    2021-09-03
Name: Date, Length: 553, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ADPT_ended_2021-09-25  2019-06-27         39.51  15.19  71.25       5.606

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    20.796    26.402    32.008    37.614     43.22    48.826    54.432

  markup_80 markup_90 markup_100
0    60.038    65.644      71.25
                   stock  start_date current_price minall maxall each_markup  \
0  ADPT_ended_2021-09-25  2019-06-27         39.51  15.19  71.25       5.606

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    20.796    26.402    32.008    37.614     43.22    48.826    54.432

  markup_80 markup_90 markup_100
0    60.038    65.644      71.25
./ticker_data/ticker_data_2021-09-25 - Copy/ADP_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31   43.370693   43.469826   42.329796   42.726330   27.087296
1     2000-01-03   42.428928   42.775894   41.189766   41.239334   26.144566
2     2000-01-04   40.941933   42.032398   40.842800   41.239334   26.144566
3     2000-01-05   41.189766   41.189766   40.049736   40.842800   25.893185
4     2000-01-06   41.140202   41.982830   40.694099   41.388031   26.238859
...          ...         ...         ...         ...         ...         ...
5450  2021-08-30  209.089996  210.830002  208.990005  209.070007  209.070007
5451  2021-08-31  209.880005  209.880005  207.080002  209.039993  209.039993
5452  2021-09-01  207.500000  207.500000  205.740005  206.860001  206.860001
5453  2021-09-02  205.490005  207.350006  205.490005  206.529999  206.529999
5454  2021-09-03  204.500000  207.779999  204.369995  207.380005  207.380005

           Volume
0        512400.0
1       2698800.0
2       3141100.0
3       3008700.0
4       2121700.0
...           ...
5450   88560000.0
5451  223710000.0
5452  139760000.0
5453  117440000.0
5454  111590000.0

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                  stock  start_date current_price   minall  maxall  \
0  ADP_ended_2021-09-25  1999-12-31        207.38  21.6031  217.15

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     19.5547   41.1578   60.7125   80.2671   99.8218   119.377   138.931

  markup_70 markup_80 markup_90 markup_100
0   158.486   178.041   197.595     217.15
                  stock  start_date current_price   minall  maxall  \
0  ADP_ended_2021-09-25  1999-12-31        207.38  21.6031  217.15

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     19.5547   41.1578   60.7125   80.2671   99.8218   119.377   138.931

  markup_70 markup_80 markup_90 markup_100
0   158.486   178.041   197.595     217.15
./ticker_data/ticker_data_2021-09-25 - Copy/ADSK_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31    8.000000    8.531250    7.937500    8.437500    8.143387
1     2000-01-03    8.500000    8.656250    8.031250    8.343750    8.052903
2     2000-01-04    8.046875    8.125000    7.875000    7.937500    7.660817
3     2000-01-05    7.750000    7.765625    7.343750    7.437500    7.178246
4     2000-01-06    7.375000    7.468750    6.906250    6.984375    6.740915
...          ...         ...         ...         ...         ...         ...
5449  2021-08-30  316.940002  318.720001  310.160004  313.390015  313.390015
5450  2021-08-31  313.130005  314.290009  309.109985  310.089996  310.089996
5451  2021-09-01  311.799988  315.459991  300.790009  303.239990  303.239990
5452  2021-09-02  306.500000  306.839996  285.350006  287.470001  287.470001
5453  2021-09-03  286.700012  293.000000  284.500000  288.750000  288.750000

         Volume
0       1931600
1       2845600
2       3348800
3       4297600
4       3856800
...         ...
5449  141190000
5450  156700000
5451  308540000
5452  547570000
5453  181900000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price   minall  maxall  \
0  ADSK_ended_2021-09-25  1999-12-31        288.75  4.85938  344.39

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     33.9531   38.8124   72.7655   106.719   140.672   174.625   208.578

  markup_70 markup_80 markup_90 markup_100
0   242.531   276.484   310.437     344.39
                   stock  start_date current_price   minall  maxall  \
0  ADSK_ended_2021-09-25  1999-12-31        288.75  4.85938  344.39

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     33.9531   38.8124   72.7655   106.719   140.672   174.625   208.578

  markup_70 markup_80 markup_90 markup_100
0   242.531   276.484   310.437     344.39
./ticker_data/ticker_data_2021-09-25 - Copy/ADTN_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  25.843750  26.375000  25.625000  25.718750  17.888430
1     2000-01-03  26.187500  26.250000  24.562500  25.578125  17.790619
2     2000-01-04  25.125000  25.812500  24.531250  24.781250  17.236357
3     2000-01-05  24.781250  25.500000  24.718750  25.125000  17.475452
4     2000-01-06  24.875000  26.000000  24.750000  25.546875  17.768879
...          ...        ...        ...        ...        ...        ...
5449  2021-08-30  22.980000  22.980000  20.389999  20.510000  20.510000
5450  2021-08-31  20.520000  21.389999  20.299999  20.660000  20.660000
5451  2021-09-01  20.790001  21.180000  20.250000  20.709999  20.709999
5452  2021-09-02  20.879999  20.879999  20.350000  20.719999  20.719999
5453  2021-09-03  20.700001  20.850000  20.379999  20.549999  20.549999

         Volume
0         83400
1        251600
2        284400
3        849000
4        269800
...         ...
5449  267080000
5450  155920000
5451   78640000
5452   61160000
5453   31260000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ADTN_ended_2021-09-25  1999-12-31         20.55    4.8   47.7        4.29

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.09     13.38     17.67     21.96     26.25     30.54     34.83

  markup_80 markup_90 markup_100
0     39.12     43.41       47.7
                   stock  start_date current_price minall maxall each_markup  \
0  ADTN_ended_2021-09-25  1999-12-31         20.55    4.8   47.7        4.29

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.09     13.38     17.67     21.96     26.25     30.54     34.83

  markup_80 markup_90 markup_100
0     39.12     43.41       47.7
./ticker_data/ticker_data_2021-09-25 - Copy/ADTX_ended_2021-09-25.csv
           Date   Open  High   Low  Close  Adj Close     Volume
0    2020-06-30  5.500  7.08  5.00   5.06       5.06    1047800
1    2020-07-01  5.280  5.44  4.52   4.55       4.55     218900
2    2020-07-02  4.600  4.71  4.00   4.02       4.02     152000
3    2020-07-06  4.290  4.29  3.50   3.70       3.70     102600
4    2020-07-07  3.710  4.05  3.61   3.85       3.85      59200
..          ...    ...   ...   ...    ...        ...        ...
293  2021-08-30  1.970  1.97  1.83   1.87       1.87  355210000
294  2021-08-31  1.870  1.91  1.85   1.89       1.89  200800000
295  2021-09-01  1.868  1.87  1.81   1.83       1.83  210630000
296  2021-09-02  1.832  1.88  1.75   1.80       1.80  224600000
297  2021-09-03  1.820  1.82  1.71   1.77       1.77  171100000

[298 rows x 7 columns]
tolistdate: 0      2020-06-30
1      2020-07-01
2      2020-07-02
3      2020-07-06
4      2020-07-07
          ...
293    2021-08-30
294    2021-08-31
295    2021-09-01
296    2021-09-02
297    2021-09-03
Name: Date, Length: 298, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ADTX_ended_2021-09-25  2020-06-30          1.77   1.62   9.58       0.796

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.416     3.212     4.008     4.804       5.6     6.396     7.192

  markup_80 markup_90 markup_100
0     7.988     8.784       9.58
                   stock  start_date current_price minall maxall each_markup  \
0  ADTX_ended_2021-09-25  2020-06-30          1.77   1.62   9.58       0.796

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.416     3.212     4.008     4.804       5.6     6.396     7.192

  markup_80 markup_90 markup_100
0     7.988     8.784       9.58
./ticker_data/ticker_data_2021-09-25 - Copy/ADUS_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2009-10-28   9.400000   9.500000   8.370000   8.490000   8.490000
1     2009-10-29   8.760000   9.000000   8.500000   9.000000   9.000000
2     2009-10-30   9.000000   9.150000   8.400000   9.150000   9.150000
3     2009-11-02   8.780000   9.150000   8.500000   8.640000   8.640000
4     2009-11-03   8.510000   8.600000   8.180000   8.470000   8.470000
...          ...        ...        ...        ...        ...        ...
2978  2021-08-30  90.959999  90.959999  89.500000  89.949997  89.949997
2979  2021-08-31  89.510002  90.540001  89.330002  89.919998  89.919998
2980  2021-09-01  91.589996  91.589996  88.730003  90.239998  90.239998
2981  2021-09-02  90.570000  92.760002  90.570000  92.169998  92.169998
2982  2021-09-03  91.730003  91.730003  89.620003  90.250000  90.250000

       Volume
0     2471500
1      224200
2      125700
3       51700
4       55200
...       ...
2978  4440000
2979  9750000
2980  6100000
2981  5520000
2982  4990000

[2983 rows x 7 columns]
tolistdate: 0       2009-10-28
1       2009-10-29
2       2009-10-30
3       2009-11-02
4       2009-11-03
           ...
2978    2021-08-30
2979    2021-08-31
2980    2021-09-01
2981    2021-09-02
2982    2021-09-03
Name: Date, Length: 2983, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ADUS_ended_2021-09-25  2009-10-28         90.25    2.8  129.01      12.621

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.421    28.042    40.663    53.284    65.905    78.526    91.147

  markup_80 markup_90 markup_100
0   103.768   116.389     129.01
                   stock  start_date current_price minall  maxall each_markup  \
0  ADUS_ended_2021-09-25  2009-10-28         90.25    2.8  129.01      12.621

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.421    28.042    40.663    53.284    65.905    78.526    91.147

  markup_80 markup_90 markup_100
0   103.768   116.389     129.01

./ticker_data/ticker_data_2021-09-25 - Copy/ADVM_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2014-07-31  25.000000  28.950001  24.049999  27.990000  27.990000
1     2014-08-01  26.950001  27.150000  25.000000  25.160000  25.160000
2     2014-08-04  24.980000  26.400000  24.000000  24.250000  24.250000
3     2014-08-05  24.129999  24.139999  22.000000  22.600000  22.600000
4     2014-08-06  22.950001  24.860001  22.059999  23.370001  23.370001
...          ...        ...        ...        ...        ...        ...
1783  2021-08-30   2.430000   2.530000   2.360000   2.390000   2.390000
1784  2021-08-31   2.410000   2.460000   2.400000   2.430000   2.430000
1785  2021-09-01   2.480000   2.500000   2.420000   2.500000   2.500000
1786  2021-09-02   2.500000   2.565000   2.450000   2.530000   2.530000
1787  2021-09-03   2.500000   2.510000   2.330000   2.340000   2.340000

         Volume
0       6316000
1        465900
2        141300
3        144500
4        139200
...         ...
1783  110480000
1784   72820000
1785   86250000
1786   85140000
1787  135630000

[1788 rows x 7 columns]
tolistdate: 0       2014-07-31
1       2014-08-01
2       2014-08-04
3       2014-08-05
4       2014-08-06
           ...
1783    2021-08-30
1784    2021-08-31
1785    2021-09-01
1786    2021-09-02
1787    2021-09-03
Name: Date, Length: 1788, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ADVM_ended_2021-09-25  2014-07-31          2.34  2.065  62.48      6.0415

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    8.1065    14.148   20.1895    26.231   32.2725    38.314   44.3555

  markup_80 markup_90 markup_100
0    50.397   56.4385      62.48
                   stock  start_date current_price minall maxall each_markup  \
0  ADVM_ended_2021-09-25  2014-07-31          2.34  2.065  62.48      6.0415

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    8.1065    14.148   20.1895    26.231   32.2725    38.314   44.3555

  markup_80 markup_90 markup_100
0    50.397   56.4385      62.48
./ticker_data/ticker_data_2021-09-25 - Copy/ADVWW_ended_2021-09-25.csv
         Date  Open  High   Low  Close  Adj Close  Volume
0  2021-09-22  1.81  1.79  1.71   1.75       1.75   23503
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ADVWW_ended_2021-09-25  2021-09-22          1.75   1.71   1.79  0.00799999

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.718     1.726     1.734     1.742      1.75     1.758     1.766

  markup_80 markup_90 markup_100
0     1.774     1.782       1.79
                    stock  start_date current_price minall maxall each_markup  \
0  ADVWW_ended_2021-09-25  2021-09-22          1.75   1.71   1.79  0.00799999

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.718     1.726     1.734     1.742      1.75     1.758     1.766

  markup_80 markup_90 markup_100
0     1.774     1.782       1.79
./ticker_data/ticker_data_2021-09-25 - Copy/ADV_ended_2021-09-25.csv
           Date   Open    High    Low  Close  Adj Close    Volume
0    2020-01-02  10.40  10.400  10.40  10.40      10.40         0
1    2020-01-08  10.90  10.900  10.90  10.90      10.90       100
2    2020-01-09  10.65  10.650  10.58  10.58      10.58    251000
3    2020-01-10  10.90  11.000  10.59  10.59      10.59      5900
4    2020-01-13  10.65  10.750  10.65  10.70      10.70     32600
..          ...    ...     ...    ...    ...        ...       ...
388  2021-08-30   9.16   9.240   8.83   8.88       8.88  44390000
389  2021-08-31   8.88   9.110   8.71   8.71       8.71  76740000
390  2021-09-01   8.76   8.900   8.59   8.69       8.69  41270000
391  2021-09-02   8.74   8.950   8.51   8.82       8.82  38390000
392  2021-09-03   8.81   8.925   8.71   8.86       8.86  26730000

[393 rows x 7 columns]
tolistdate: 0      2020-01-02
1      2020-01-08
2      2020-01-09
3      2020-01-10
4      2020-01-13
          ...
388    2021-08-30
389    2021-08-31
390    2021-09-01
391    2021-09-02
392    2021-09-03
Name: Date, Length: 393, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  ADV_ended_2021-09-25  2020-01-02          8.86   7.89  13.92       0.603

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.493     9.096     9.699    10.302    10.905    11.508    12.111

  markup_80 markup_90 markup_100
0    12.714    13.317      13.92
                  stock  start_date current_price minall maxall each_markup  \
0  ADV_ended_2021-09-25  2020-01-02          8.86   7.89  13.92       0.603

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.493     9.096     9.699    10.302    10.905    11.508    12.111

  markup_80 markup_90 markup_100
0    12.714    13.317      13.92
./ticker_data/ticker_data_2021-09-25 - Copy/ADXN_ended_2021-09-25.csv
           Date   Open    High     Low   Close  Adj Close  Volume
0    2020-02-12  11.32  11.320  11.300  11.300     11.300    1000
1    2020-02-13  11.30  11.300  11.300  11.300     11.300       0
2    2020-03-12   8.85   8.850   8.850   8.850      8.850     100
3    2020-03-13   8.85   8.850   8.850   8.850      8.850       0
4    2020-03-16   8.00   8.000   7.820   7.820      7.820     200
..          ...    ...     ...     ...     ...        ...     ...
306  2021-08-30   9.94   9.940   9.700   9.700      9.700  160000
307  2021-08-31   9.95   9.953   9.725   9.725      9.725   90000
308  2021-09-01   9.76   9.760   9.760   9.760      9.760   30000
309  2021-09-02   9.99   9.990   9.760   9.760      9.760   40000
310  2021-09-03  10.05  10.280   9.490   9.490      9.490  270000

[311 rows x 7 columns]
tolistdate: 0      2020-02-12
1      2020-02-13
2      2020-03-12
3      2020-03-13
4      2020-03-16
          ...
306    2021-08-30
307    2021-08-31
308    2021-09-01
309    2021-09-02
310    2021-09-03
Name: Date, Length: 311, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ADXN_ended_2021-09-25  2020-02-12          9.49   6.19  37.52       3.133

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.323    12.456    15.589    18.722    21.855    24.988    28.121

  markup_80 markup_90 markup_100
0    31.254    34.387      37.52
                   stock  start_date current_price minall maxall each_markup  \
0  ADXN_ended_2021-09-25  2020-02-12          9.49   6.19  37.52       3.133

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.323    12.456    15.589    18.722    21.855    24.988    28.121

  markup_80 markup_90 markup_100
0    31.254    34.387      37.52
./ticker_data/ticker_data_2021-09-25 - Copy/ADXS_ended_2021-09-25.csv
            Date      Open      High      Low    Close  Adj Close      Volume
0     2005-07-28  2343.750  2343.750  731.250  843.750    843.750         100
1     2005-07-29  1031.250  1031.250  656.250  937.500    937.500           0
2     2005-08-01   975.000   975.000  693.750  693.750    693.750           0
3     2005-08-02   693.750   731.250  693.750  731.250    731.250           0
4     2005-08-03   693.750   731.250  618.750  656.250    656.250         100
...          ...       ...       ...      ...      ...        ...         ...
3754  2021-08-30     0.441     0.465    0.438    0.448      0.448   433840000
3755  2021-08-31     0.450     0.478    0.448    0.469      0.469   403100000
3756  2021-09-01     0.466     0.486    0.460    0.470      0.470   461400000
3757  2021-09-02     0.477     0.477    0.453    0.464      0.464   502960000
3758  2021-09-03     0.510     0.524    0.480    0.504      0.504  1760240000

[3759 rows x 7 columns]
tolistdate: 0       2005-07-28
1       2005-07-29
2       2005-08-01
3       2005-08-02
4       2005-08-03
           ...
3754    2021-08-30
3755    2021-08-31
3756    2021-09-01
3757    2021-09-02
3758    2021-09-03
Name: Date, Length: 3759, dtype: object
                   stock  start_date current_price minall   maxall  \
0  ADXS_ended_2021-09-25  2005-07-28         0.504  0.205  2343.75

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     234.355   234.559   468.914   703.268   937.623   1171.98   1406.33

  markup_70 markup_80 markup_90 markup_100
0   1640.69   1875.04    2109.4    2343.75
                   stock  start_date current_price minall   maxall  \
0  ADXS_ended_2021-09-25  2005-07-28         0.504  0.205  2343.75

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     234.355   234.559   468.914   703.268   937.623   1171.98   1406.33

  markup_70 markup_80 markup_90 markup_100
0   1640.69   1875.04    2109.4    2343.75
./ticker_data/ticker_data_2021-09-25 - Copy/AEACU_ended_2021-09-25.csv
           Date    Open   High     Low   Close  Adj Close   Volume
0    2021-01-15  10.350  10.44  10.300  10.380     10.380  5978000
1    2021-01-19  10.500  10.58  10.420  10.420     10.420  1519000
2    2021-01-20  10.470  10.58  10.420  10.470     10.470   493900
3    2021-01-21  10.490  10.58  10.430  10.450     10.450   437100
4    2021-01-22  10.500  10.50  10.400  10.430     10.430   481800
..          ...     ...    ...     ...     ...        ...      ...
152  2021-08-26  10.000  10.00  10.000  10.000     10.000        0
153  2021-08-27   9.990   9.99   9.965   9.968      9.968    90000
154  2021-08-30   9.965   9.98   9.950   9.980      9.980   510000
155  2021-08-31   9.980  10.01   9.980  10.000     10.000   530000
156  2021-09-01   9.990  10.01   9.990  10.010     10.010   370000

[157 rows x 7 columns]
tolistdate: 0      2021-01-15
1      2021-01-19
2      2021-01-20
3      2021-01-21
4      2021-01-22
          ...
152    2021-08-26
153    2021-08-27
154    2021-08-30
155    2021-08-31
156    2021-09-01
Name: Date, Length: 157, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AEACU_ended_2021-09-25  2021-01-15         10.01    9.7  10.98       0.128

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.828     9.956    10.084    10.212     10.34    10.468    10.596

  markup_80 markup_90 markup_100
0    10.724    10.852      10.98
                    stock  start_date current_price minall maxall each_markup  \
0  AEACU_ended_2021-09-25  2021-01-15         10.01    9.7  10.98       0.128

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.828     9.956    10.084    10.212     10.34    10.468    10.596

  markup_80 markup_90 markup_100
0    10.724    10.852      10.98
./ticker_data/ticker_data_2021-09-25 - Copy/AEACW_ended_2021-09-25.csv
         Date  Open  High     Low   Close  Adj Close  Volume
0  2021-09-22  0.66  0.69  0.5902  0.6349     0.6349  168761
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price  minall maxall  \
0  AEACW_ended_2021-09-25  2021-09-22        0.6349  0.5902   0.69

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00998   0.60018   0.61016   0.62014   0.63012    0.6401   0.65008

  markup_70 markup_80 markup_90 markup_100
0   0.66006   0.67004   0.68002       0.69
                    stock  start_date current_price  minall maxall  \
0  AEACW_ended_2021-09-25  2021-09-22        0.6349  0.5902   0.69

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00998   0.60018   0.61016   0.62014   0.63012    0.6401   0.65008

  markup_70 markup_80 markup_90 markup_100
0   0.66006   0.67004   0.68002       0.69
./ticker_data/ticker_data_2021-09-25 - Copy/AEAC_ended_2021-09-25.csv
           Date  Open  High    Low  Close  Adj Close   Volume
0    2021-03-08  9.78  9.78  9.770   9.77       9.77     2000
1    2021-03-09  9.77  9.80  9.715   9.73       9.73    50100
2    2021-03-10  9.80  9.80  9.736   9.76       9.76    22200
3    2021-03-11  9.71  9.79  9.710   9.78       9.78    46900
4    2021-03-12  9.79  9.79  9.750   9.79       9.79    28200
..          ...   ...   ...    ...    ...        ...      ...
117  2021-08-30  9.62  9.68  9.620   9.67       9.67   350000
118  2021-08-31  9.63  9.85  9.630   9.85       9.85  1080000
119  2021-09-01  9.70  9.71  9.630   9.63       9.63   210000
120  2021-09-02  9.63  9.63  9.630   9.63       9.63   280000
121  2021-09-03  9.63  9.63  9.630   9.63       9.63  1500000

[122 rows x 7 columns]
tolistdate: 0      2021-03-08
1      2021-03-09
2      2021-03-10
3      2021-03-11
4      2021-03-12
          ...
117    2021-08-30
118    2021-08-31
119    2021-09-01
120    2021-09-02
121    2021-09-03
Name: Date, Length: 122, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AEAC_ended_2021-09-25  2021-03-08          9.63  9.513   9.87      0.0357

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.5487    9.5844    9.6201    9.6558    9.6915    9.7272    9.7629

  markup_80 markup_90 markup_100
0    9.7986    9.8343       9.87
                   stock  start_date current_price minall maxall each_markup  \
0  AEAC_ended_2021-09-25  2021-03-08          9.63  9.513   9.87      0.0357

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.5487    9.5844    9.6201    9.6558    9.6915    9.7272    9.7629

  markup_80 markup_90 markup_100
0    9.7986    9.8343       9.87
./ticker_data/ticker_data_2021-09-25 - Copy/AEHL_ended_2021-09-25.csv
           Date      Open      High       Low     Close  Adj Close  \
0    2013-12-11       NaN       NaN       NaN       NaN        NaN
1    2014-06-11       NaN       NaN       NaN       NaN        NaN
2    2016-06-28       NaN       NaN       NaN       NaN        NaN
3    2020-04-16  1.410001  1.500002  1.260001  1.500002   1.500002
4    2020-04-17  1.500002  1.650002  1.440001  1.620002   1.620002
..          ...       ...       ...       ...       ...        ...
292  2021-08-30  3.300000  3.480000  3.160000  3.460000   3.460000
293  2021-08-31  3.420000  3.420000  3.110000  3.170000   3.170000
294  2021-09-01  3.260000  3.330000  3.150000  3.210000   3.210000
295  2021-09-02  3.200000  3.250000  2.950000  2.980000   2.980000
296  2021-09-03  3.000000  3.010000  2.900000  2.920000   2.920000

          Volume
0            NaN
1            NaN
2            NaN
3       242200.0
4       145900.0
..           ...
292  133290000.0
293   82120000.0
294   41530000.0
295   54410000.0
296   42310000.0

[297 rows x 7 columns]
tolistdate: 0      2013-12-11
1      2014-06-11
2      2016-06-28
3      2020-04-16
4      2020-04-17
          ...
292    2021-08-30
293    2021-08-31
294    2021-09-01
295    2021-09-02
296    2021-09-03
Name: Date, Length: 297, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AEHL_ended_2021-09-25  2013-12-11          2.92   1.26    7.7       0.644

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.904     2.548     3.192     3.836      4.48     5.124     5.768

  markup_80 markup_90 markup_100
0     6.412     7.056        7.7
                   stock  start_date current_price minall maxall each_markup  \
0  AEHL_ended_2021-09-25  2013-12-11          2.92   1.26    7.7       0.644

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.904     2.548     3.192     3.836      4.48     5.124     5.768

  markup_80 markup_90 markup_100
0     6.412     7.056        7.7
./ticker_data/ticker_data_2021-09-25 - Copy/AEHR_ended_2021-09-25.csv
            Date     Open     High     Low   Close  Adj Close     Volume
0     1999-12-31  5.03125  5.03125  5.0000  5.0000     5.0000       1300
1     2000-01-03  5.00000  5.06250  4.7500  4.8125     4.8125      14200
2     2000-01-04  5.00000  5.12500  4.8125  4.8125     4.8125      19400
3     2000-01-05  5.12500  5.12500  4.3750  4.7500     4.7500      18700
4     2000-01-06  4.68750  4.68750  4.5625  4.6250     4.6250      24700
...          ...      ...      ...     ...     ...        ...        ...
5317  2021-08-30  7.51000  7.52000  6.8500  6.9100     6.9100  101730000
5318  2021-08-31  7.20000  8.36000  7.1000  7.4600     7.4600  481580000
5319  2021-09-01  7.46000  7.49000  6.8300  7.0500     7.0500  126570000
5320  2021-09-02  7.09000  7.68000  7.0100  7.5300     7.5300   65370000
5321  2021-09-03  7.69000  9.11000  7.6200  8.3900     8.3900  824380000

[5322 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5317    2021-08-30
5318    2021-08-31
5319    2021-09-01
5320    2021-09-02
5321    2021-09-03
Name: Date, Length: 5322, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AEHR_ended_2021-09-25  1999-12-31          8.39    0.4   11.2        1.08

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      1.48      2.56      3.64      4.72       5.8      6.88      7.96

  markup_80 markup_90 markup_100

0      9.04     10.12       11.2
                   stock  start_date current_price minall maxall each_markup  \
0  AEHR_ended_2021-09-25  1999-12-31          8.39    0.4   11.2        1.08

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      1.48      2.56      3.64      4.72       5.8      6.88      7.96

  markup_80 markup_90 markup_100
0      9.04     10.12       11.2
./ticker_data/ticker_data_2021-09-25 - Copy/AEIS_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  46.000000  49.875000  45.875000  49.250000  49.153542
1     2000-01-03  49.500000  49.625000  44.312500  45.375000  45.286133
2     2000-01-04  45.375000  47.000000  44.875000  45.000000  44.911869
3     2000-01-05  44.625000  45.125000  44.000000  44.250000  44.163338
4     2000-01-06  44.500000  44.500000  42.937500  43.750000  43.664318
...          ...        ...        ...        ...        ...        ...
5449  2021-08-30  91.760002  92.849998  90.139999  90.459999  90.459999
5450  2021-08-31  90.570000  90.830002  88.669998  90.180000  90.180000
5451  2021-09-01  90.559998  91.050003  89.050003  89.639999  89.639999
5452  2021-09-02  89.620003  90.860001  89.320000  89.910004  89.910004
5453  2021-09-03  89.820000  90.459999  88.669998  89.099998  89.099998

        Volume
0        73800
1        94000
2       202700
3       132700
4        53300
...        ...
5449  14720000
5450  22090000
5451  16190000
5452  14360000
5453  12460000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AEIS_ended_2021-09-25  1999-12-31          89.1   5.36  125.55      12.019

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.379    29.398    41.417    53.436    65.455    77.474    89.493

  markup_80 markup_90 markup_100
0   101.512   113.531     125.55
                   stock  start_date current_price minall  maxall each_markup  \
0  AEIS_ended_2021-09-25  1999-12-31          89.1   5.36  125.55      12.019

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.379    29.398    41.417    53.436    65.455    77.474    89.493

  markup_80 markup_90 markup_100
0   101.512   113.531     125.55
./ticker_data/ticker_data_2021-09-25 - Copy/AEI_ended_2021-09-25.csv
           Date  Open  High   Low  Close  Adj Close      Volume
0    2020-11-25  7.00  7.00  6.10   6.10       6.10      998300
1    2020-11-27  6.00  6.20  5.50   5.55       5.55      282400
2    2020-11-30  5.60  6.38  5.52   6.09       6.09      257000
3    2020-12-01  6.27  6.48  5.81   5.92       5.92      117600
4    2020-12-02  5.81  6.20  5.52   5.65       5.65      162500
..          ...   ...   ...   ...    ...        ...         ...
141  2021-08-30  2.00  2.10  1.97   2.02       2.02   256150000
142  2021-08-31  1.99  2.02  1.91   2.01       2.01    98210000
143  2021-09-01  2.00  2.13  1.93   2.02       2.02   527210000
144  2021-09-02  2.06  2.38  2.00   2.25       2.25  2269840000
145  2021-09-03  2.21  2.25  2.05   2.10       2.10   961350000

[146 rows x 7 columns]
tolistdate: 0      2020-11-25
1      2020-11-27
2      2020-11-30
3      2020-12-01
4      2020-12-02
          ...
141    2021-08-30
142    2021-08-31
143    2021-09-01
144    2021-09-02
145    2021-09-03
Name: Date, Length: 146, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  AEI_ended_2021-09-25  2020-11-25           2.1   1.65  29.49       2.784

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.434     7.218    10.002    12.786     15.57    18.354    21.138

  markup_80 markup_90 markup_100
0    23.922    26.706      29.49
                  stock  start_date current_price minall maxall each_markup  \
0  AEI_ended_2021-09-25  2020-11-25           2.1   1.65  29.49       2.784

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.434     7.218    10.002    12.786     15.57    18.354    21.138

  markup_80 markup_90 markup_100
0    23.922    26.706      29.49
./ticker_data/ticker_data_2021-09-25 - Copy/AEMD_ended_2021-09-25.csv
            Date     Open     High      Low    Close  Adj Close    Volume
0     1999-12-31  6000.00  6000.00  6000.00  6000.00    6000.00         0
1     2000-01-10  6750.00  6750.00  6750.00  6750.00    6750.00         0
2     2000-01-11  6000.00  6750.00  6000.00  6750.00    6750.00         0
3     2000-02-04  5250.00  6750.00  5250.00  6750.00    6750.00         0
4     2000-02-09  6750.00  6750.00  6000.00  6000.00    6000.00         0
...          ...      ...      ...      ...      ...        ...       ...
4023  2021-08-30     3.95     3.97     3.60     3.63       3.63  45280000
4024  2021-08-31     3.71     3.80     3.63     3.72       3.72  21310000
4025  2021-09-01     3.75     3.77     3.64     3.71       3.71  14370000
4026  2021-09-02     3.66     3.83     3.66     3.73       3.73  19060000
4027  2021-09-03     3.69     3.72     3.59     3.69       3.69  14040000

[4028 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-10
2       2000-01-11
3       2000-02-04
4       2000-02-09
           ...
4023    2021-08-30
4024    2021-08-31
4025    2021-09-01
4026    2021-09-02
4027    2021-09-03
Name: Date, Length: 4028, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AEMD_ended_2021-09-25  1999-12-31          3.69   0.76   6750     674.924

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   675.684   1350.61   2025.53   2700.46   3375.38    4050.3   4725.23

  markup_80 markup_90 markup_100
0   5400.15   6075.08       6750
                   stock  start_date current_price minall maxall each_markup  \
0  AEMD_ended_2021-09-25  1999-12-31          3.69   0.76   6750     674.924

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   675.684   1350.61   2025.53   2700.46   3375.38    4050.3   4725.23

  markup_80 markup_90 markup_100
0   5400.15   6075.08       6750
./ticker_data/ticker_data_2021-09-25 - Copy/AEPPL_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-04-02  46.880001  48.166000  46.880001  47.980000  44.394478
1    2020-04-03  47.599998  47.700001  45.389999  45.759998  42.340378
2    2020-04-06  45.849998  49.400002  45.849998  48.599998  44.968147
3    2020-04-07  49.084999  49.709999  47.750999  48.709999  45.069927
4    2020-04-08  49.250000  50.358002  48.480000  50.020000  46.282028
..          ...        ...        ...        ...        ...        ...
354  2021-08-30  50.990002  51.119999  50.979000  51.110001  51.110001
355  2021-08-31  51.070000  51.130001  50.820000  50.919998  50.919998
356  2021-09-01  51.139999  51.299999  50.939999  51.209999  51.209999
357  2021-09-02  51.299999  51.389999  51.209999  51.259998  51.259998
358  2021-09-03  51.486000  51.490002  51.220001  51.400002  51.400002

      Volume
0      28300
1      98000
2     517200
3     799800
4      41200
..       ...
354   610000
355  6400000
356  2820000
357  2050000
358   500000

[359 rows x 7 columns]
tolistdate: 0      2020-04-02
1      2020-04-03
2      2020-04-06
3      2020-04-07
4      2020-04-08
          ...
354    2021-08-30
355    2021-08-31
356    2021-09-01
357    2021-09-02
358    2021-09-03
Name: Date, Length: 359, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AEPPL_ended_2021-09-25  2020-04-02          51.4  45.25   54.8       0.955

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    46.205     47.16    48.115     49.07    50.025     50.98    51.935

  markup_80 markup_90 markup_100
0     52.89    53.845       54.8
                    stock  start_date current_price minall maxall each_markup  \
0  AEPPL_ended_2021-09-25  2020-04-02          51.4  45.25   54.8       0.955

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    46.205     47.16    48.115     49.07    50.025     50.98    51.935

  markup_80 markup_90 markup_100
0     52.89    53.845       54.8
./ticker_data/ticker_data_2021-09-25 - Copy/AEPPZ_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-09-30  49.299999  49.330002  48.900002  49.020000  47.573071
1    2020-10-01  49.490002  50.139999  49.490002  50.000000  48.524139
2    2020-10-02  49.419998  53.270000  49.419998  50.846001  49.345173
3    2020-10-05  50.549999  51.770000  50.310001  51.689999  50.164257
4    2020-10-06  51.880001  53.459999  51.880001  52.389999  50.843594
..          ...        ...        ...        ...        ...        ...
197  2021-08-30  53.029999  53.439999  53.029999  53.070000  53.070000
198  2021-08-31  52.849998  53.160000  52.639999  52.639999  52.639999
199  2021-09-01  52.959999  53.610001  52.959999  53.610001  53.610001
200  2021-09-02  53.560001  53.750000  53.560001  53.750000  53.750000
201  2021-09-03  53.439999  53.820000  53.439999  53.740002  53.740002

      Volume
0     108100
1      56900
2       6100
3      19200
4     162600
..       ...
197   470000
198  8990000
199  2600000
200   470000
201  1420000

[202 rows x 7 columns]
tolistdate: 0      2020-09-30
1      2020-10-01
2      2020-10-02
3      2020-10-05
4      2020-10-06
          ...
197    2021-08-30
198    2021-08-31
199    2021-09-01
200    2021-09-02
201    2021-09-03
Name: Date, Length: 202, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AEPPZ_ended_2021-09-25  2020-09-30         53.74  47.51  55.75       0.824

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    48.334    49.158    49.982    50.806     51.63    52.454    53.278

  markup_80 markup_90 markup_100
0    54.102    54.926      55.75
                    stock  start_date current_price minall maxall each_markup  \
0  AEPPZ_ended_2021-09-25  2020-09-30         53.74  47.51  55.75       0.824

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    48.334    49.158    49.982    50.806     51.63    52.454    53.278

  markup_80 markup_90 markup_100
0    54.102    54.926      55.75
./ticker_data/ticker_data_2021-09-25 - Copy/AEP_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  32.375000  32.687500  32.062500  32.125000  12.217643
1     2000-01-03  32.000000  32.000000  31.125000  31.437500  11.956178
2     2000-01-04  31.375000  31.937500  31.375000  31.812500  12.098797
3     2000-01-05  31.812500  33.125000  31.812500  33.000000  12.550421
4     2000-01-06  32.750000  33.687500  32.750000  33.187500  12.621731
...          ...        ...        ...        ...        ...        ...
5450  2021-08-30  89.209999  89.959999  89.010002  89.620003  89.620003
5451  2021-08-31  89.540001  90.099998  89.230003  89.570000  89.570000
5452  2021-09-01  90.000000  90.820000  89.519997  90.500000  90.500000
5453  2021-09-02  90.459999  91.000000  90.300003  90.930000  90.930000
5454  2021-09-03  90.489998  91.089996  90.269997  90.410004  90.410004

         Volume
0         98700
1        396900
2        325500
3        392200
4        433000
...         ...
5450  222200000
5451  193340000
5452  253240000
5453  151200000
5454  140750000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                  stock  start_date current_price minall  maxall each_markup  \
0  AEP_ended_2021-09-25  1999-12-31         90.41   15.1  104.97       8.987

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    24.087    33.074    42.061    51.048    60.035    69.022    78.009

  markup_80 markup_90 markup_100
0    86.996    95.983     104.97
                  stock  start_date current_price minall  maxall each_markup  \
0  AEP_ended_2021-09-25  1999-12-31         90.41   15.1  104.97       8.987

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    24.087    33.074    42.061    51.048    60.035    69.022    78.009

  markup_80 markup_90 markup_100
0    86.996    95.983     104.97
./ticker_data/ticker_data_2021-09-25 - Copy/AERI_ended_2021-09-25.csv
            Date   Open   High     Low  Close  Adj Close    Volume
0     2013-10-25  10.55  10.86  10.250  10.61      10.61   2678900
1     2013-10-28  10.50  10.70  10.320  10.55      10.55    157700
2     2013-10-29  10.41  10.55  10.310  10.53      10.53     94400
3     2013-10-30  10.53  10.53  10.320  10.40      10.40     78200
4     2013-10-31  10.45  10.54  10.380  10.50      10.50     61200
...          ...    ...    ...     ...    ...        ...       ...
1973  2021-08-30  14.65  14.89  14.480  14.52      14.52  25140000
1974  2021-08-31  14.46  14.92  14.438  14.91      14.91  21630000
1975  2021-09-01  14.90  15.27  14.660  14.83      14.83  19750000
1976  2021-09-02  14.89  15.21  14.740  14.88      14.88  19120000
1977  2021-09-03  14.82  14.83  14.190  14.34      14.34  22050000

[1978 rows x 7 columns]
tolistdate: 0       2013-10-25
1       2013-10-28
2       2013-10-29
3       2013-10-30
4       2013-10-31
           ...
1973    2021-08-30
1974    2021-08-31
1975    2021-09-01
1976    2021-09-02
1977    2021-09-03
Name: Date, Length: 1978, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AERI_ended_2021-09-25  2013-10-25         14.34  8.835  74.75      6.5915

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   15.4265    22.018   28.6095    35.201   41.7925    48.384   54.9755

  markup_80 markup_90 markup_100
0    61.567   68.1585      74.75
                   stock  start_date current_price minall maxall each_markup  \
0  AERI_ended_2021-09-25  2013-10-25         14.34  8.835  74.75      6.5915

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   15.4265    22.018   28.6095    35.201   41.7925    48.384   54.9755

  markup_80 markup_90 markup_100
0    61.567   68.1585      74.75
./ticker_data/ticker_data_2021-09-25 - Copy/AESE_ended_2021-09-25.csv
           Date  Open   High    Low  Close  Adj Close    Volume
0    2017-10-25  9.63  9.630  9.570   9.58       9.58    665300
1    2017-10-26  9.58  9.610  9.550   9.55       9.55   1000800
2    2017-10-27  9.55  9.560  9.537   9.54       9.54     17000
3    2017-10-30  9.58  9.580  9.580   9.58       9.58      1000
4    2017-10-31  9.55  9.560  9.550   9.56       9.56     14600
..          ...   ...    ...    ...    ...        ...       ...
856  2021-08-30  1.98  2.060  1.970   2.00       2.00  61710000
857  2021-08-31  1.97  2.050  1.970   2.01       2.01  44130000
858  2021-09-01  2.01  2.038  1.960   1.99       1.99  25100000
859  2021-09-02  1.97  2.040  1.960   2.00       2.00  20120000
860  2021-09-03  2.02  2.020  1.950   2.00       2.00  31070000

[861 rows x 7 columns]
tolistdate: 0      2017-10-25
1      2017-10-26
2      2017-10-27
3      2017-10-30
4      2017-10-31
          ...
856    2021-08-30
857    2021-08-31
858    2021-09-01
859    2021-09-02
860    2021-09-03
Name: Date, Length: 861, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AESE_ended_2021-09-25  2017-10-25             2    0.4  12.11       1.171

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.571     2.742     3.913     5.084     6.255     7.426     8.597

  markup_80 markup_90 markup_100
0     9.768    10.939      12.11
                   stock  start_date current_price minall maxall each_markup  \
0  AESE_ended_2021-09-25  2017-10-25             2    0.4  12.11       1.171

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.571     2.742     3.913     5.084     6.255     7.426     8.597

  markup_80 markup_90 markup_100
0     9.768    10.939      12.11

./ticker_data/ticker_data_2021-09-25 - Copy/AEYE_ended_2021-09-25.csv
            Date   Open   High    Low  Close  Adj Close   Volume
0     2013-04-26  12.75  75.00  12.75  28.00      28.00      300
1     2013-04-29  30.00  37.50  30.00  35.00      35.00      500
2     2013-04-30  37.50  37.50  25.00  32.25      32.25      500
3     2013-05-01  26.25  30.00  25.25  30.00      30.00      300
4     2013-05-02  25.00  27.50  22.75  27.50      27.50      300
...          ...    ...    ...    ...    ...        ...      ...
1973  2021-08-30  13.00  13.05  12.70  12.95      12.95  5550000
1974  2021-08-31  12.99  13.12  12.80  13.04      13.04  6840000
1975  2021-09-01  13.10  13.48  12.50  12.59      12.59  6030000
1976  2021-09-02  12.61  13.20  12.61  12.94      12.94  7300000
1977  2021-09-03  13.00  13.20  12.61  12.96      12.96  5420000

[1978 rows x 7 columns]
tolistdate: 0       2013-04-26
1       2013-04-29
2       2013-04-30
3       2013-05-01
4       2013-05-02
           ...
1973    2021-08-30
1974    2021-08-31
1975    2021-09-01
1976    2021-09-02
1977    2021-09-03
Name: Date, Length: 1978, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AEYE_ended_2021-09-25  2013-04-26         12.96   0.75     75       7.425

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.175      15.6    23.025     30.45    37.875      45.3    52.725

  markup_80 markup_90 markup_100
0     60.15    67.575         75
                   stock  start_date current_price minall maxall each_markup  \
0  AEYE_ended_2021-09-25  2013-04-26         12.96   0.75     75       7.425

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.175      15.6    23.025     30.45    37.875      45.3    52.725

  markup_80 markup_90 markup_100
0     60.15    67.575         75
./ticker_data/ticker_data_2021-09-25 - Copy/AEY_ended_2021-09-25.csv
            Date    Open    High     Low   Close  Adj Close   Volume
0     1999-12-31  2.8750  3.0000  2.8125  3.0000     3.0000    10100
1     2000-01-03  3.0000  3.0000  3.0000  3.0000     3.0000     1000
2     2000-01-04  2.7500  2.7500  2.7500  2.7500     2.7500      200
3     2000-01-05  3.0625  3.0625  3.0625  3.0625     3.0625      200
4     2000-01-06  3.0625  3.0625  3.0625  3.0625     3.0625      700
...          ...     ...     ...     ...     ...        ...      ...
5025  2021-08-30  2.6200  2.7800  2.6200  2.6400     2.6400  9250000
5026  2021-08-31  2.6100  2.6900  2.6100  2.6500     2.6500  2320000
5027  2021-09-01  2.7000  2.7300  2.6800  2.7100     2.7100  3530000
5028  2021-09-02  2.7100  2.7500  2.7100  2.7300     2.7300  4990000
5029  2021-09-03  2.6800  2.7700  2.6800  2.6900     2.6900  7400000

[5030 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5025    2021-08-30
5026    2021-08-31
5027    2021-09-01
5028    2021-09-02
5029    2021-09-03
Name: Date, Length: 5030, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  AEY_ended_2021-09-25  1999-12-31          2.69   0.52   9.65       0.913

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.433     2.346     3.259     4.172     5.085     5.998     6.911

  markup_80 markup_90 markup_100
0     7.824     8.737       9.65
                  stock  start_date current_price minall maxall each_markup  \
0  AEY_ended_2021-09-25  1999-12-31          2.69   0.52   9.65       0.913

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.433     2.346     3.259     4.172     5.085     5.998     6.911

  markup_80 markup_90 markup_100
0     7.824     8.737       9.65
./ticker_data/ticker_data_2021-09-25 - Copy/AEZS_ended_2021-09-25.csv
            Date     Open     High      Low    Close  Adj Close     Volume
0     2000-05-10  6600.00  6825.00  6000.00  6375.00    6375.00          0
1     2000-05-11  6300.00  6300.00  5850.00  5850.00    5850.00          0
2     2000-05-12  5775.00  6150.00  5775.00  5850.00    5850.00          0
3     2000-05-15  5850.00  5850.00  5850.00  5850.00    5850.00          0
4     2000-05-16  5850.00  6375.00  5850.00  6225.00    6225.00          0
...          ...      ...      ...      ...      ...        ...        ...
5240  2021-08-30     0.72     0.73     0.69     0.70       0.70  105950000
5241  2021-08-31     0.69     0.72     0.69     0.72       0.72   96560000
5242  2021-09-01     0.72     0.74     0.71     0.73       0.73   49100000
5243  2021-09-02     0.74     0.74     0.72     0.74       0.74   60580000
5244  2021-09-03     0.74     0.74     0.73     0.73       0.73   38940000

[5245 rows x 7 columns]
tolistdate: 0       2000-05-10
1       2000-05-11
2       2000-05-12
3       2000-05-15
4       2000-05-16
           ...
5240    2021-08-30
5241    2021-08-31
5242    2021-09-01
5243    2021-09-02
5244    2021-09-03
Name: Date, Length: 5245, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AEZS_ended_2021-09-25  2000-05-10          0.73   0.29   6900     689.971

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   690.261   1380.23    2070.2   2760.17   3450.14   4140.12   4830.09

  markup_80 markup_90 markup_100
0   5520.06   6210.03       6900
                   stock  start_date current_price minall maxall each_markup  \
0  AEZS_ended_2021-09-25  2000-05-10          0.73   0.29   6900     689.971

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   690.261   1380.23    2070.2   2760.17   3450.14   4140.12   4830.09

  markup_80 markup_90 markup_100
0   5520.06   6210.03       6900
./ticker_data/ticker_data_2021-09-25 - Copy/AFAQU_ended_2021-09-25.csv
          Date  Open  High   Low  Close  Adj Close   Volume
0   2021-03-19  9.87  9.90  9.83   9.83       9.83  8737600
1   2021-03-22  9.80  9.86  9.80   9.82       9.82  1138600
2   2021-03-23  9.83  9.83  9.76   9.77       9.77   506300
3   2021-03-24  9.81  9.82  9.78   9.80       9.80  1114800
4   2021-03-25  9.83  9.88  9.75   9.83       9.83   186300
..         ...   ...   ...   ...    ...        ...      ...
92  2021-08-19  9.85  9.85  9.85   9.85       9.85    60000
93  2021-08-20  9.85  9.85  9.85   9.85       9.85        0
94  2021-08-23  9.85  9.85  9.83   9.85       9.85   860000
95  2021-08-25  9.81  9.85  9.80   9.85       9.85   230000
96  2021-09-03  9.80  9.90  9.80   9.90       9.90    70000

[97 rows x 7 columns]
tolistdate: 0     2021-03-19
1     2021-03-22
2     2021-03-23
3     2021-03-24
4     2021-03-25
         ...
92    2021-08-19
93    2021-08-20
94    2021-08-23
95    2021-08-25
96    2021-09-03
Name: Date, Length: 97, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AFAQU_ended_2021-09-25  2021-03-19           9.9   9.75  10.09       0.034

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.784     9.818     9.852     9.886      9.92     9.954     9.988

  markup_80 markup_90 markup_100
0    10.022    10.056      10.09
                    stock  start_date current_price minall maxall each_markup  \
0  AFAQU_ended_2021-09-25  2021-03-19           9.9   9.75  10.09       0.034

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.784     9.818     9.852     9.886      9.92     9.954     9.988

  markup_80 markup_90 markup_100
0    10.022    10.056      10.09
./ticker_data/ticker_data_2021-09-25 - Copy/AFAQW_ended_2021-09-25.csv
         Date      Open  High   Low   Close  Adj Close  Volume
0  2021-09-22  0.700201  0.56  0.55  0.5599     0.5599   31172
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall  \
0  AFAQW_ended_2021-09-25  2021-09-22        0.5599   0.55   0.56

   each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0  0.000999999     0.551     0.552     0.553     0.554     0.555     0.556

  markup_70 markup_80 markup_90 markup_100
0     0.557     0.558     0.559       0.56
                    stock  start_date current_price minall maxall  \
0  AFAQW_ended_2021-09-25  2021-09-22        0.5599   0.55   0.56

   each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0  0.000999999     0.551     0.552     0.553     0.554     0.555     0.556

  markup_70 markup_80 markup_90 markup_100
0     0.557     0.558     0.559       0.56
./ticker_data/ticker_data_2021-09-25 - Copy/AFAQ_ended_2021-09-25.csv
          Date   Open   High    Low  Close  Adj Close    Volume
0   2021-05-27  9.650  9.880  9.650  9.880      9.880    249300
1   2021-05-28  9.650  9.670  9.650  9.650      9.650      1200
2   2021-06-01  9.650  9.670  9.590  9.660      9.660      6100
3   2021-06-02  9.660  9.660  9.660  9.660      9.660         0
4   2021-06-10  9.640  9.680  9.640  9.660      9.660      1200
5   2021-06-15  9.660  9.660  9.660  9.660      9.660      2400
6   2021-06-17  9.675  9.700  9.675  9.695      9.695     71400
7   2021-06-18  9.700  9.700  9.700  9.700      9.700      6100
8   2021-06-21  9.700  9.700  9.700  9.700      9.700         0
9   2021-06-22  9.700  9.700  9.700  9.700      9.700       300
10  2021-06-23  9.880  9.950  9.880  9.950      9.950      1200
11  2021-06-24  9.950  9.950  9.950  9.950      9.950         0
12  2021-06-30  9.755  9.755  9.755  9.755      9.755      1900
13  2021-07-01  9.750  9.790  9.660  9.660      9.660     78200
14  2021-07-02  9.660  9.700  9.660  9.660      9.660      2900
15  2021-07-06  9.680  9.680  9.680  9.680      9.680      3600
16  2021-07-07  9.700  9.700  9.670  9.680      9.680     31500
17  2021-07-08  9.680  9.680  9.680  9.680      9.680         0
18  2021-07-09  9.670  9.670  9.670  9.670      9.670      1700
19  2021-07-12  9.670  9.670  9.670  9.670      9.670         0
20  2021-07-15  9.680  9.680  9.680  9.680      9.680       100
21  2021-07-16  9.655  9.700  9.655  9.690      9.690     15000
22  2021-07-19  9.690  9.690  9.690  9.690      9.690         0
23  2021-07-21  9.650  9.650  9.620  9.630      9.630      3600
24  2021-07-22  9.660  9.670  9.660  9.670      9.670     12300
25  2021-07-23  9.670  9.670  9.670  9.670      9.670       100
26  2021-07-26  9.670  9.700  9.620  9.620      9.620      8900
27  2021-07-27  9.680  9.680  9.680  9.680      9.680      1500
28  2021-07-28  9.610  9.650  9.610  9.650      9.650       400
29  2021-07-29  9.650  9.650  9.650  9.650      9.650       300
30  2021-07-30  9.670  9.680  9.670  9.680      9.680      2200
31  2021-08-03  9.640  9.670  9.610  9.670      9.670     14400
32  2021-08-04  9.620  9.640  9.600  9.640      9.640  11640000
33  2021-08-05  9.630  9.640  9.620  9.620      9.620  48950000
34  2021-08-06  9.630  9.640  9.620  9.620      9.620   2320000
35  2021-08-09  9.620  9.623  9.620  9.620      9.620    520000
36  2021-08-10  9.640  9.640  9.620  9.620      9.620    800000
37  2021-08-11  9.620  9.620  9.620  9.620      9.620     10000
38  2021-08-12  9.620  9.620  9.620  9.620      9.620         0
39  2021-08-16  9.620  9.620  9.620  9.620      9.620  37910000
40  2021-08-17  9.640  9.640  9.640  9.640      9.640    290000
41  2021-08-18  9.640  9.640  9.640  9.640      9.640         0
42  2021-08-20  9.630  9.630  9.630  9.630      9.630     20000
43  2021-08-23  9.630  9.630  9.630  9.630      9.630         0
44  2021-08-24  9.620  9.630  9.619  9.630      9.630    420000
45  2021-08-25  9.610  9.630  9.596  9.600      9.600   1010000
46  2021-08-26  9.600  9.630  9.600  9.600      9.600    180000
47  2021-08-27  9.600  9.630  9.590  9.620      9.620  17880000
48  2021-08-30  9.620  9.620  9.600  9.620      9.620   1300000
49  2021-08-31  9.606  9.630  9.590  9.630      9.630   2910000
50  2021-09-01  9.650  9.650  9.650  9.650      9.650     10000
51  2021-09-02  9.660  9.660  9.660  9.660      9.660    170000
tolistdate: 0     2021-05-27
1     2021-05-28
2     2021-06-01
3     2021-06-02
4     2021-06-10
5     2021-06-15
6     2021-06-17
7     2021-06-18
8     2021-06-21
9     2021-06-22
10    2021-06-23
11    2021-06-24
12    2021-06-30
13    2021-07-01
14    2021-07-02
15    2021-07-06
16    2021-07-07
17    2021-07-08
18    2021-07-09
19    2021-07-12
20    2021-07-15
21    2021-07-16
22    2021-07-19
23    2021-07-21
24    2021-07-22
25    2021-07-23
26    2021-07-26
27    2021-07-27
28    2021-07-28
29    2021-07-29
30    2021-07-30
31    2021-08-03
32    2021-08-04
33    2021-08-05
34    2021-08-06
35    2021-08-09
36    2021-08-10
37    2021-08-11
38    2021-08-12
39    2021-08-16
40    2021-08-17
41    2021-08-18
42    2021-08-20
43    2021-08-23
44    2021-08-24
45    2021-08-25
46    2021-08-26
47    2021-08-27
48    2021-08-30
49    2021-08-31
50    2021-09-01
51    2021-09-02
Name: Date, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AFAQ_ended_2021-09-25  2021-05-27          9.66   9.59   9.95       0.036

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.626     9.662     9.698     9.734      9.77     9.806     9.842

  markup_80 markup_90 markup_100
0     9.878     9.914       9.95
                   stock  start_date current_price minall maxall each_markup  \
0  AFAQ_ended_2021-09-25  2021-05-27          9.66   9.59   9.95       0.036

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.626     9.662     9.698     9.734      9.77     9.806     9.842

  markup_80 markup_90 markup_100
0     9.878     9.914       9.95
./ticker_data/ticker_data_2021-09-25 - Copy/AFBI_ended_2021-09-25.csv
           Date    Open   High     Low   Close  Adj Close  Volume
0    2020-07-23   7.110   7.20   7.050   7.050      7.050     400
1    2020-07-24   7.000   7.00   7.000   7.000      7.000     400
2    2020-07-27   7.100   7.10   7.100   7.100      7.100     100
3    2020-07-28   7.100   7.10   7.100   7.100      7.100       0
4    2020-07-29   7.100   7.11   7.100   7.110      7.110     700
..          ...     ...    ...     ...     ...        ...     ...
276  2021-08-30  13.550  13.93  13.550  13.890     13.890  110000
277  2021-08-31  13.900  14.00  13.760  13.760     13.760  630000
278  2021-09-01  13.820  13.82  13.820  13.820     13.820   40000
279  2021-09-02  13.972  14.09  13.972  14.045     14.045  580000
280  2021-09-03  14.000  14.09  14.000  14.090     14.090  350000

[281 rows x 7 columns]
tolistdate: 0      2020-07-23
1      2020-07-24
2      2020-07-27
3      2020-07-28
4      2020-07-29
          ...
276    2021-08-30
277    2021-08-31
278    2021-09-01
279    2021-09-02
280    2021-09-03
Name: Date, Length: 281, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AFBI_ended_2021-09-25  2020-07-23         14.09   6.53  14.14       0.761

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.291     8.052     8.813     9.574    10.335    11.096    11.857

  markup_80 markup_90 markup_100
0    12.618    13.379      14.14
                   stock  start_date current_price minall maxall each_markup  \
0  AFBI_ended_2021-09-25  2020-07-23         14.09   6.53  14.14       0.761

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.291     8.052     8.813     9.574    10.335    11.096    11.857

  markup_80 markup_90 markup_100
0    12.618    13.379      14.14
./ticker_data/ticker_data_2021-09-25 - Copy/AFCG_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2021-03-19  21.000000  23.750000  19.750000  23.000000  22.637194
1    2021-03-22  23.480000  24.950001  21.615000  21.900000  21.554544
2    2021-03-23  22.000000  22.000000  20.990000  21.200001  20.865587
3    2021-03-24  21.400000  21.840000  20.120001  21.000000  20.668741
4    2021-03-25  20.340000  21.610001  20.080000  20.299999  19.979784
..          ...        ...        ...        ...        ...        ...
112  2021-08-30  21.379999  21.490000  20.910000  21.100000  21.100000
113  2021-08-31  21.180000  21.343000  20.900000  21.309999  21.309999
114  2021-09-01  21.350000  21.590000  21.110001  21.469999  21.469999
115  2021-09-02  21.469999  21.799999  21.160000  21.639999  21.639999
116  2021-09-03  21.730000  21.780001  21.360001  21.370001  21.370001

       Volume
0     1389600
1      397100
2      301800
3      199900
4      165400
..        ...
112  11790000
113  17780000
114  11280000
115   9220000
116   3550000

[117 rows x 7 columns]
tolistdate: 0      2021-03-19
1      2021-03-22
2      2021-03-23
3      2021-03-24
4      2021-03-25
          ...
112    2021-08-30
113    2021-08-31
114    2021-09-01
115    2021-09-02
116    2021-09-03
Name: Date, Length: 117, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AFCG_ended_2021-09-25  2021-03-19         21.37  19.75  25.05        0.53

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     20.28     20.81     21.34     21.87      22.4     22.93     23.46

  markup_80 markup_90 markup_100
0     23.99     24.52      25.05
                   stock  start_date current_price minall maxall each_markup  \
0  AFCG_ended_2021-09-25  2021-03-19         21.37  19.75  25.05        0.53

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     20.28     20.81     21.34     21.87      22.4     22.93     23.46

  markup_80 markup_90 markup_100
0     23.99     24.52      25.05
./ticker_data/ticker_data_2021-09-25 - Copy/AFIB_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-08-06  24.110001  28.299999  24.000000  26.500000  26.500000
1    2020-08-07  25.520000  28.930000  24.777000  26.790001  26.790001
2    2020-08-10  26.980000  28.610001  26.950001  28.000000  28.000000
3    2020-08-11  28.440001  28.440001  24.879999  24.910000  24.910000
4    2020-08-12  25.000000  25.480000  24.780001  24.850000  24.850000
..          ...        ...        ...        ...        ...        ...
267  2021-08-30  13.530000  13.545000  12.820000  12.930000  12.930000
268  2021-08-31  12.940000  13.060000  12.605000  12.790000  12.790000
269  2021-09-01  12.890000  12.950000  12.540000  12.700000  12.700000
270  2021-09-02  12.720000  13.000000  12.630000  12.860000  12.860000
271  2021-09-03  12.740000  13.150000  12.740000  13.000000  13.000000

       Volume
0     3399400
1      648300
2      248400
3      373300
4      132300
..        ...
267  12780000
268  22440000
269  21720000
270  19760000
271  15990000

[272 rows x 7 columns]
tolistdate: 0      2020-08-06
1      2020-08-07
2      2020-08-10
3      2020-08-11
4      2020-08-12
          ...
267    2021-08-30
268    2021-08-31
269    2021-09-01
270    2021-09-02
271    2021-09-03
Name: Date, Length: 272, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AFIB_ended_2021-09-25  2020-08-06            13  11.18  38.99       2.781

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.961    16.742    19.523    22.304    25.085    27.866    30.647

  markup_80 markup_90 markup_100
0    33.428    36.209      38.99
                   stock  start_date current_price minall maxall each_markup  \
0  AFIB_ended_2021-09-25  2020-08-06            13  11.18  38.99       2.781

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.961    16.742    19.523    22.304    25.085    27.866    30.647

  markup_80 markup_90 markup_100
0    33.428    36.209      38.99
./ticker_data/ticker_data_2021-09-25 - Copy/AFINO_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \

[180 rows x 7 columns]
tolistdate: 0      2020-12-16
1      2020-12-17
2      2020-12-18
3      2020-12-21
4      2020-12-22
          ...
175    2021-08-30
176    2021-08-31
177    2021-09-01
178    2021-09-02
179    2021-09-03
Name: Date, Length: 180, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AFINO_ended_2021-09-25  2020-12-16         26.95   24.5  26.96       0.246

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    24.746    24.992    25.238    25.484     25.73    25.976    26.222

  markup_80 markup_90 markup_100
0    26.468    26.714      26.96
                    stock  start_date current_price minall maxall each_markup  \
0  AFINO_ended_2021-09-25  2020-12-16         26.95   24.5  26.96       0.246

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    24.746    24.992    25.238    25.484     25.73    25.976    26.222

  markup_80 markup_90 markup_100
0    26.468    26.714      26.96
./ticker_data/ticker_data_2021-09-25 - Copy/AFINP_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-03-22  24.639999  24.680000  24.180000  24.459999  20.451527
1    2019-03-25  24.500000  24.600000  24.200001  24.320000  20.334471
2    2019-03-26  24.420000  24.520000  24.200001  24.520000  20.501694
3    2019-03-27  24.490000  24.500000  24.309999  24.330000  20.342831
4    2019-03-28  24.400000  24.549999  24.250000  24.500000  20.484974
..          ...        ...        ...        ...        ...        ...
614  2021-08-30  26.980000  27.200001  26.980000  27.200001  27.200001
615  2021-08-31  27.120001  27.180000  27.059999  27.180000  27.180000
616  2021-09-01  27.160000  27.177999  27.020000  27.170000  27.170000
617  2021-09-02  27.190001  27.190001  26.750000  27.190001  27.190001
618  2021-09-03  27.200001  27.290001  27.150000  27.160000  27.160000

      Volume
0     616000
1      16800
2      64300
3      39800
4      12500
..       ...
614   450000
615   360000
616  1060000
617  1160000
618  1780000

[619 rows x 7 columns]
tolistdate: 0      2019-03-22
1      2019-03-25
2      2019-03-26
3      2019-03-27
4      2019-03-28
          ...
614    2021-08-30
615    2021-08-31
616    2021-09-01
617    2021-09-02
618    2021-09-03
Name: Date, Length: 619, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AFINP_ended_2021-09-25  2019-03-22         27.16   6.81   27.5       2.069

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.879    10.948    13.017    15.086    17.155    19.224    21.293

  markup_80 markup_90 markup_100
0    23.362    25.431       27.5
                    stock  start_date current_price minall maxall each_markup  \
0  AFINP_ended_2021-09-25  2019-03-22         27.16   6.81   27.5       2.069

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.879    10.948    13.017    15.086    17.155    19.224    21.293

  markup_80 markup_90 markup_100
0    23.362    25.431       27.5
./ticker_data/ticker_data_2021-09-25 - Copy/AFIN_ended_2021-09-25.csv
           Date   Open       High    Low  Close  Adj Close     Volume
0    2018-07-19  13.15  16.799999  13.15  15.00  10.861096     601700
1    2018-07-20  15.00  15.190000  13.75  13.98  10.122541     795600
2    2018-07-23  13.50  14.500000  13.34  14.22  10.296320     787000
3    2018-07-24  13.90  14.260000  13.90  14.08  10.194946     450000
4    2018-07-25  13.85  14.440000  13.85  14.05  10.173225     397400
..          ...    ...        ...    ...    ...        ...        ...
783  2021-08-30   8.69   8.690000   8.58   8.64   8.640000   88300000
784  2021-08-31   8.62   8.730000   8.59   8.62   8.620000   84010000
785  2021-09-01   8.65   8.670000   8.47   8.50   8.500000  168630000
786  2021-09-02   8.50   8.530000   8.44   8.50   8.500000   85690000
787  2021-09-03   8.46   8.530000   8.42   8.52   8.520000   92580000

[788 rows x 7 columns]
tolistdate: 0      2018-07-19
1      2018-07-20
2      2018-07-23
3      2018-07-24
4      2018-07-25
          ...
783    2021-08-30
784    2021-08-31
785    2021-09-01
786    2021-09-02
787    2021-09-03
Name: Date, Length: 788, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AFIN_ended_2021-09-25  2018-07-19          8.52    4.2   18.5        1.43

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      5.63      7.06      8.49      9.92     11.35     12.78     14.21

  markup_80 markup_90 markup_100
0     15.64     17.07       18.5
                   stock  start_date current_price minall maxall each_markup  \
0  AFIN_ended_2021-09-25  2018-07-19          8.52    4.2   18.5        1.43

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      5.63      7.06      8.49      9.92     11.35     12.78     14.21

  markup_80 markup_90 markup_100
0     15.64     17.07       18.5
./ticker_data/ticker_data_2021-09-25 - Copy/AFMD_ended_2021-09-25.csv
            Date  Open  High    Low  Close  Adj Close     Volume
0     2014-09-12  6.95  7.00  5.630   5.70       5.70    3576200
1     2014-09-15  6.00  6.40  5.850   6.40       6.40     478900
2     2014-09-16  6.40  6.49  5.910   6.22       6.22     163300
3     2014-09-17  6.17  6.32  6.020   6.27       6.27     145300
4     2014-09-18  6.12  6.27  6.000   6.12       6.12     148700
...          ...   ...   ...    ...    ...        ...        ...
1752  2021-08-30  7.23  7.34  7.020   7.07       7.07  120380000
1753  2021-08-31  7.06  7.20  6.870   7.04       7.04   71330000
1754  2021-09-01  7.07  7.16  6.999   7.15       7.15   72680000
1755  2021-09-02  7.16  7.16  6.880   7.08       7.08   72240000
1756  2021-09-03  7.10  7.10  6.660   6.69       6.69   72580000

[1757 rows x 7 columns]
tolistdate: 0       2014-09-12
1       2014-09-15
2       2014-09-16
3       2014-09-17
4       2014-09-18
           ...
1752    2021-08-30
1753    2021-08-31
1754    2021-09-01
1755    2021-09-02
1756    2021-09-03
Name: Date, Length: 1757, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AFMD_ended_2021-09-25  2014-09-12          6.69   1.15   24.2       2.305

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.455      5.76     8.065     10.37    12.675     14.98    17.285

  markup_80 markup_90 markup_100
0     19.59    21.895       24.2
                   stock  start_date current_price minall maxall each_markup  \
0  AFMD_ended_2021-09-25  2014-09-12          6.69   1.15   24.2       2.305

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.455      5.76     8.065     10.37    12.675     14.98    17.285

  markup_80 markup_90 markup_100
0     19.59    21.895       24.2
./ticker_data/ticker_data_2021-09-25 - Copy/AFRM_ended_2021-09-25.csv
           Date        Open        High         Low       Close   Adj Close  \
0    2021-01-13   90.910004  103.000000   90.010002   97.239998   97.239998
1    2021-01-14  103.500000  137.979996  101.000000  114.940002  114.940002
2    2021-01-15  123.054001  127.239998  107.000000  117.000000  117.000000
3    2021-01-19  117.000000  117.675003  108.000000  110.989998  110.989998
4    2021-01-20  110.000000  112.000000  103.250000  106.209999  106.209999
..          ...         ...         ...         ...         ...         ...
158  2021-08-30   96.239998  101.000000   91.279999   99.589996   99.589996
159  2021-08-31   95.239998   96.550003   90.279999   96.339996   96.339996
160  2021-09-01   94.389999   98.669998   93.279999   96.480003   96.480003
161  2021-09-02   97.110001   99.320000   95.239998   98.989998   98.989998
162  2021-09-03   98.940002  100.000000   92.550003   93.050003   93.050003

         Volume
0      25159000
1      20858700
2       8310700
3       3304900
4       5091400
..          ...
158  4440090000
159  1581900000
160   635730000
161   652390000
162   609360000

[163 rows x 7 columns]
tolistdate: 0      2021-01-13
1      2021-01-14
2      2021-01-15
3      2021-01-19
4      2021-01-20
          ...
158    2021-08-30
159    2021-08-31
160    2021-09-01
161    2021-09-02
162    2021-09-03
Name: Date, Length: 163, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AFRM_ended_2021-09-25  2021-01-13         93.05   46.5  146.9       10.04

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     56.54     66.58     76.62     86.66      96.7    106.74    116.78

  markup_80 markup_90 markup_100
0    126.82    136.86      146.9
                   stock  start_date current_price minall maxall each_markup  \
0  AFRM_ended_2021-09-25  2021-01-13         93.05   46.5  146.9       10.04

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     56.54     66.58     76.62     86.66      96.7    106.74    116.78

  markup_80 markup_90 markup_100
0    126.82    136.86      146.9
./ticker_data/ticker_data_2021-09-25 - Copy/AFYA_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-07-19  23.500000  24.299999  22.000000  23.844999  23.844999
1    2019-07-22  23.260000  24.690001  22.799999  23.559999  23.559999
2    2019-07-23  23.520000  24.709999  23.138000  24.520000  24.520000
3    2019-07-24  24.610001  28.129999  24.385000  27.450001  27.450001
4    2019-07-25  27.410000  28.750000  26.719999  27.660000  27.660000
..          ...        ...        ...        ...        ...        ...
532  2021-08-30  21.170000  21.389999  20.735001  20.900000  20.900000
533  2021-08-31  20.969999  21.670000  20.969999  21.580000  21.580000
534  2021-09-01  21.570000  22.420000  21.570000  21.750000  21.750000
535  2021-09-02  21.840000  22.135000  21.570000  22.010000  22.010000
536  2021-09-03  21.959999  22.629999  21.844999  22.059999  22.059999

       Volume
0     7332400
1     1032100
2      599300
3     1260300
4      501400
..        ...
532  13850000
533   7060000
534   5800000
535  15510000
536   9730000

[537 rows x 7 columns]
tolistdate: 0      2019-07-19
1      2019-07-22
2      2019-07-23
3      2019-07-24
4      2019-07-25
          ...
532    2021-08-30
533    2021-08-31
534    2021-09-01
535    2021-09-02
536    2021-09-03
Name: Date, Length: 537, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AFYA_ended_2021-09-25  2019-07-19         22.06  13.98  34.87       2.089

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    16.069    18.158    20.247    22.336    24.425    26.514    28.603

  markup_80 markup_90 markup_100
0    30.692    32.781      34.87
                   stock  start_date current_price minall maxall each_markup  \
0  AFYA_ended_2021-09-25  2019-07-19         22.06  13.98  34.87       2.089

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    16.069    18.158    20.247    22.336    24.425    26.514    28.603

  markup_80 markup_90 markup_100
0    30.692    32.781      34.87
./ticker_data/ticker_data_2021-09-25 - Copy/AGBAR_ended_2021-09-25.csv
         Date    Open    High     Low   Close  Adj Close  Volume
0  2021-09-22  0.2553  0.2553  0.2553  0.2553     0.2553     818
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price  minall  maxall  \
0  AGBAR_ended_2021-09-25  2021-09-22        0.2553  0.2553  0.2553

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0           0    0.2553    0.2553    0.2553    0.2553    0.2553    0.2553

  markup_70 markup_80 markup_90 markup_100
0    0.2553    0.2553    0.2553     0.2553
                    stock  start_date current_price  minall  maxall  \
0  AGBAR_ended_2021-09-25  2021-09-22        0.2553  0.2553  0.2553

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0           0    0.2553    0.2553    0.2553    0.2553    0.2553    0.2553

  markup_70 markup_80 markup_90 markup_100
0    0.2553    0.2553    0.2553     0.2553
./ticker_data/ticker_data_2021-09-25 - Copy/AGBAW_ended_2021-09-25.csv
         Date    Open    High     Low   Close  Adj Close  Volume
0  2021-09-22  0.1508  0.2319  0.1708  0.2201     0.2201    4199
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price  minall  maxall  \
0  AGBAW_ended_2021-09-25  2021-09-22        0.2201  0.1708  0.2319

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00611   0.17691   0.18302   0.18913   0.19524   0.20135   0.20746

  markup_70 markup_80 markup_90 markup_100
0   0.21357   0.21968   0.22579     0.2319
                    stock  start_date current_price  minall  maxall  \
0  AGBAW_ended_2021-09-25  2021-09-22        0.2201  0.1708  0.2319

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00611   0.17691   0.18302   0.18913   0.19524   0.20135   0.20746

  markup_70 markup_80 markup_90 markup_100
0   0.21357   0.21968   0.22579     0.2319
./ticker_data/ticker_data_2021-09-25 - Copy/AGBA_ended_2021-09-25.csv
           Date    Open    High    Low  Close  Adj Close  Volume
0    2019-07-31   9.900   9.900   9.90   9.90       9.90     400
1    2019-08-01   9.900   9.900   9.90   9.90       9.90       0
2    2019-08-02  10.000  10.000  10.00  10.00      10.00     100
3    2019-08-05  10.000  10.000  10.00  10.00      10.00     200
4    2019-08-06  10.000  10.000  10.00  10.00      10.00       0
..          ...     ...     ...    ...    ...        ...     ...
322  2021-08-27  10.820  10.820  10.82  10.82      10.82   10000
323  2021-08-30  10.820  10.830  10.82  10.83      10.83   30000
324  2021-08-31  10.830  10.830  10.83  10.83      10.83       0
325  2021-09-01  10.830  10.830  10.83  10.83      10.83   20000
326  2021-09-03  10.858  10.858  10.84  10.84      10.84   70000

[327 rows x 7 columns]
tolistdate: 0      2019-07-31
1      2019-08-01
2      2019-08-02
3      2019-08-05
4      2019-08-06
          ...
322    2021-08-27
323    2021-08-30
324    2021-08-31
325    2021-09-01
326    2021-09-03
Name: Date, Length: 327, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AGBA_ended_2021-09-25  2019-07-31         10.84   9.86  10.858      0.0998

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.9598   10.0596   10.1594   10.2592    10.359   10.4588   10.5586

  markup_80 markup_90 markup_100
0   10.6584   10.7582     10.858
                   stock  start_date current_price minall  maxall each_markup  \
0  AGBA_ended_2021-09-25  2019-07-31         10.84   9.86  10.858      0.0998

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.9598   10.0596   10.1594   10.2592    10.359   10.4588   10.5586

  markup_80 markup_90 markup_100
0   10.6584   10.7582     10.858
./ticker_data/ticker_data_2021-09-25 - Copy/AGCUU_ended_2021-09-25.csv
           Date    Open    High     Low   Close  Adj Close    Volume
0    2020-10-01  12.000  13.000  11.990  12.150     12.150  10569300
1    2020-10-02  12.150  12.990  11.900  12.000     12.000   1025000
2    2020-10-05  11.900  12.287  11.800  12.030     12.030    242400
3    2020-10-06  12.180  12.180  11.740  11.800     11.800    322500
4    2020-10-07  11.890  11.900  11.740  11.755     11.755     78600
..          ...     ...     ...     ...     ...        ...       ...
228  2021-08-30  10.840  12.150  10.840  10.860     10.860   1630000
229  2021-08-31  11.050  11.250  11.050  11.240     11.240    470000
230  2021-09-01  11.330  11.330  11.110  11.110     11.110    210000
231  2021-09-02  11.125  11.200  11.125  11.130     11.130    280000
232  2021-09-03  11.250  11.250  11.147  11.147     11.147    100000

[233 rows x 7 columns]
tolistdate: 0      2020-10-01
1      2020-10-02
2      2020-10-05
3      2020-10-06
4      2020-10-07
          ...
228    2021-08-30
229    2021-08-31
230    2021-09-01
231    2021-09-02
232    2021-09-03
Name: Date, Length: 233, dtype: object
                    stock  start_date current_price minall  maxall  \
0  AGCUU_ended_2021-09-25  2020-10-01        11.147  10.63  18.918

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      0.8288   11.4588   12.2876   13.1164   13.9452    14.774   15.6028

  markup_70 markup_80 markup_90 markup_100
0   16.4316   17.2604   18.0892     18.918
                    stock  start_date current_price minall  maxall  \
0  AGCUU_ended_2021-09-25  2020-10-01        11.147  10.63  18.918

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      0.8288   11.4588   12.2876   13.1164   13.9452    14.774   15.6028

  markup_70 markup_80 markup_90 markup_100
0   16.4316   17.2604   18.0892     18.918
./ticker_data/ticker_data_2021-09-25 - Copy/AGCWW_ended_2021-09-25.csv
           Date    Open    High   Low  Close  Adj Close   Volume
0    2020-12-09   3.705   3.860  3.50   3.75       3.75     4300
1    2020-12-10   3.850   4.500  3.85   4.50       4.50     1900
2    2020-12-11   5.000   5.000  4.84   5.00       5.00     2800
3    2020-12-14  10.000  10.000  5.03   5.61       5.61     6200
4    2020-12-15   5.000   5.000  4.00   4.25       4.25     5800
..          ...     ...     ...   ...    ...        ...      ...
180  2021-08-30   2.100   2.420  2.01   2.16       2.16  4560000
181  2021-08-31   2.250   2.359  2.24   2.25       2.25  7580000
182  2021-09-01   2.290   2.340  2.25   2.31       2.31  2930000
183  2021-09-02   2.400   2.400  2.25   2.25       2.25  1680000
184  2021-09-03   2.330   2.440  2.33   2.43       2.43  3400000

[185 rows x 7 columns]

tolistdate: 0      2020-12-09
1      2020-12-10
2      2020-12-11
3      2020-12-14
4      2020-12-15
          ...
180    2021-08-30
181    2021-08-31
182    2021-09-01
183    2021-09-02
184    2021-09-03
Name: Date, Length: 185, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AGCWW_ended_2021-09-25  2020-12-09          2.43   1.77     10       0.823

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.593     3.416     4.239     5.062     5.885     6.708     7.531

  markup_80 markup_90 markup_100
0     8.354     9.177         10
                    stock  start_date current_price minall maxall each_markup  \
0  AGCWW_ended_2021-09-25  2020-12-09          2.43   1.77     10       0.823

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.593     3.416     4.239     5.062     5.885     6.708     7.531

  markup_80 markup_90 markup_100
0     8.354     9.177         10
./ticker_data/ticker_data_2021-09-25 - Copy/AGC_ended_2021-09-25.csv
           Date   Open   High     Low  Close  Adj Close     Volume
0    2020-12-01  11.89  11.89  11.890  11.89      11.89        500
1    2020-12-02  12.48  12.48  11.820  11.82      11.82       1000
2    2020-12-03  11.82  11.90  11.800  11.90      11.90      14100
3    2020-12-04  12.99  13.98  11.500  12.40      12.40      15500
4    2020-12-07  13.15  14.00  12.200  12.55      12.55      14500
..          ...    ...    ...     ...    ...        ...        ...
187  2021-08-30  10.60  11.74  10.350  10.49      10.49  127620000
188  2021-08-31  10.85  10.88  10.665  10.75      10.75   42080000
189  2021-09-01  10.80  10.80  10.660  10.69      10.69   28440000
190  2021-09-02  10.70  10.78  10.640  10.69      10.69   38310000
191  2021-09-03  10.73  10.94  10.620  10.64      10.64   28240000

[192 rows x 7 columns]
tolistdate: 0      2020-12-01
1      2020-12-02
2      2020-12-03
3      2020-12-04
4      2020-12-07
          ...
187    2021-08-30
188    2021-08-31
189    2021-09-01
190    2021-09-02
191    2021-09-03
Name: Date, Length: 192, dtype: object
                  stock  start_date current_price  minall  maxall each_markup  \
0  AGC_ended_2021-09-25  2020-12-01         10.64  10.217  18.109      0.7892

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   11.0062   11.7954   12.5846   13.3738    14.163   14.9522   15.7414

  markup_80 markup_90 markup_100
0   16.5306   17.3198     18.109
                  stock  start_date current_price  minall  maxall each_markup  \
0  AGC_ended_2021-09-25  2020-12-01         10.64  10.217  18.109      0.7892

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   11.0062   11.7954   12.5846   13.3738    14.163   14.9522   15.7414

  markup_80 markup_90 markup_100
0   16.5306   17.3198     18.109
./ticker_data/ticker_data_2021-09-25 - Copy/AGEN_ended_2021-09-25.csv
            Date     Open     High      Low      Close  Adj Close     Volume
0     2000-02-08  315.750  316.125  273.000  277.50000  277.50000     115000
1     2000-02-09  276.000  276.750  243.750  264.00000  264.00000      47900
2     2000-02-10  265.500  294.000  265.500  287.15625  287.15625      47200
3     2000-02-11  274.125  281.250  261.375  268.50000  268.50000      32200
4     2000-02-14  271.125  306.000  268.500  274.50000  274.50000      41100
...          ...      ...      ...      ...        ...        ...        ...
5423  2021-08-30    6.300    6.790    6.290    6.63000    6.63000  741590000
5424  2021-08-31    6.740    6.750    6.120    6.17000    6.17000  658250000
5425  2021-09-01    6.190    6.210    5.940    6.19000    6.19000  425980000
5426  2021-09-02    6.170    6.300    6.060    6.17000    6.17000  229450000
5427  2021-09-03    6.110    6.190    5.980    6.09000    6.09000  259560000

[5428 rows x 7 columns]
tolistdate: 0       2000-02-08
1       2000-02-09
2       2000-02-10
3       2000-02-11
4       2000-02-14
           ...
5423    2021-08-30
5424    2021-08-31
5425    2021-09-01
5426    2021-09-02
5427    2021-09-03
Name: Date, Length: 5428, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AGEN_ended_2021-09-25  2000-02-08          6.09   1.14    360      35.886

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    37.026    72.912   108.798   144.684    180.57   216.456   252.342

  markup_80 markup_90 markup_100
0   288.228   324.114        360
                   stock  start_date current_price minall maxall each_markup  \
0  AGEN_ended_2021-09-25  2000-02-08          6.09   1.14    360      35.886

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    37.026    72.912   108.798   144.684    180.57   216.456   252.342

  markup_80 markup_90 markup_100
0   288.228   324.114        360
./ticker_data/ticker_data_2021-09-25 - Copy/AGFS_ended_2021-09-25.csv
            Date   Open   High    Low  Close  Adj Close    Volume
0     2014-11-20  9.640  9.640  9.640  9.640      9.640         0
1     2014-11-25  9.700  9.700  9.600  9.700      9.700      1100
2     2014-11-26  9.700  9.700  9.700  9.700      9.700         0
3     2014-12-01  9.680  9.700  9.650  9.654      9.654      2300
4     2014-12-02  9.654  9.654  9.654  9.654      9.654         0
...          ...    ...    ...    ...    ...        ...       ...
1670  2021-08-30  2.080  2.088  2.000  2.020      2.020   3300000
1671  2021-08-31  2.000  2.076  1.960  2.070      2.070   4160000
1672  2021-09-01  2.070  2.140  2.015  2.120      2.120  11030000
1673  2021-09-02  2.110  2.205  2.110  2.170      2.170   9230000
1674  2021-09-03  2.160  2.220  2.160  2.215      2.215   4790000

[1675 rows x 7 columns]
tolistdate: 0       2014-11-20
1       2014-11-25
2       2014-11-26
3       2014-12-01
4       2014-12-02
           ...
1670    2021-08-30
1671    2021-08-31
1672    2021-09-01
1673    2021-09-02
1674    2021-09-03
Name: Date, Length: 1675, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AGFS_ended_2021-09-25  2014-11-20         2.215      1  13.35       1.235

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.235      3.47     4.705      5.94     7.175      8.41     9.645

  markup_80 markup_90 markup_100
0     10.88    12.115      13.35
                   stock  start_date current_price minall maxall each_markup  \
0  AGFS_ended_2021-09-25  2014-11-20         2.215      1  13.35       1.235

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.235      3.47     4.705      5.94     7.175      8.41     9.645

  markup_80 markup_90 markup_100
0     10.88    12.115      13.35
./ticker_data/ticker_data_2021-09-25 - Copy/AGFY_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2021-01-28  13.000000  14.300000  12.440000  12.740000  12.740000
1    2021-01-29  12.090000  12.444000  10.590000  11.400000  11.400000
2    2021-02-01  11.750000  11.750000  10.800000  10.920000  10.920000
3    2021-02-02  10.930000  15.000000  10.930000  14.200000  14.200000
4    2021-02-03  14.520000  19.190001  13.530000  18.799999  18.799999
..          ...        ...        ...        ...        ...        ...
148  2021-08-30  27.809999  30.250000  27.000000  29.610001  29.610001
149  2021-08-31  28.959999  30.290001  28.320000  28.400000  28.400000
150  2021-09-01  28.950001  28.950001  23.600000  25.450001  25.450001
151  2021-09-02  25.059999  28.469999  25.049999  26.290001  26.290001
152  2021-09-03  25.889999  26.555000  22.650000  23.610001  23.610001

        Volume
0      3512100
1      1223400
2       348300
3      1749200
4      2399100
..         ...
148   82060000
149   48550000
150  202020000
151  101090000
152  121810000

[153 rows x 7 columns]
tolistdate: 0      2021-01-28
1      2021-01-29
2      2021-02-01
3      2021-02-02
4      2021-02-03
          ...
148    2021-08-30
149    2021-08-31
150    2021-09-01
151    2021-09-02
152    2021-09-03
Name: Date, Length: 153, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AGFY_ended_2021-09-25  2021-01-28         23.61   6.81  35.94       2.913

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.723    12.636    15.549    18.462    21.375    24.288    27.201

  markup_80 markup_90 markup_100
0    30.114    33.027      35.94
                   stock  start_date current_price minall maxall each_markup  \
0  AGFY_ended_2021-09-25  2021-01-28         23.61   6.81  35.94       2.913

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.723    12.636    15.549    18.462    21.375    24.288    27.201

  markup_80 markup_90 markup_100
0    30.114    33.027      35.94
./ticker_data/ticker_data_2021-09-25 - Copy/AGGRU_ended_2021-09-25.csv
           Date   Open    High   Low  Close  Adj Close    Volume
0    2021-03-10  10.00  10.000  9.96   9.97       9.97  10566800
1    2021-03-11   9.97  10.000  9.96   9.99       9.99   2061500
2    2021-03-12  10.00  10.000  9.98  10.00      10.00    681400
3    2021-03-15  10.00  10.000  9.92   9.93       9.93    640700
4    2021-03-16   9.95   9.962  9.92   9.95       9.95    217900
..          ...    ...     ...   ...    ...        ...       ...
98   2021-08-30   9.88   9.890  9.88   9.89       9.89     60000
99   2021-08-31   9.89   9.890  9.89   9.89       9.89         0
100  2021-09-01   9.86   9.860  9.86   9.86       9.86     60000
101  2021-09-02   9.85   9.850  9.85   9.85       9.85  81580000
102  2021-09-03   9.85   9.850  9.85   9.85       9.85         0

[103 rows x 7 columns]
tolistdate: 0      2021-03-10
1      2021-03-11
2      2021-03-12
3      2021-03-15
4      2021-03-16
          ...
98     2021-08-30
99     2021-08-31
100    2021-09-01
101    2021-09-02
102    2021-09-03
Name: Date, Length: 103, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AGGRU_ended_2021-09-25  2021-03-10          9.85   9.75  10.05        0.03

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.78      9.81      9.84      9.87       9.9      9.93      9.96

  markup_80 markup_90 markup_100
0      9.99     10.02      10.05
                    stock  start_date current_price minall maxall each_markup  \
0  AGGRU_ended_2021-09-25  2021-03-10          9.85   9.75  10.05        0.03

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.78      9.81      9.84      9.87       9.9      9.93      9.96

  markup_80 markup_90 markup_100
0      9.99     10.02      10.05
./ticker_data/ticker_data_2021-09-25 - Copy/AGGRW_ended_2021-09-25.csv
         Date  Open  High   Low  Close  Adj Close  Volume
0  2021-09-22   0.0   0.7  0.64   0.67       0.67    1684
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AGGRW_ended_2021-09-25  2021-09-22          0.67   0.64    0.7       0.006

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.646     0.652     0.658     0.664      0.67     0.676     0.682

  markup_80 markup_90 markup_100
0     0.688     0.694        0.7
                    stock  start_date current_price minall maxall each_markup  \
0  AGGRW_ended_2021-09-25  2021-09-22          0.67   0.64    0.7       0.006

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.646     0.652     0.658     0.664      0.67     0.676     0.682

  markup_80 markup_90 markup_100
0     0.688     0.694        0.7
./ticker_data/ticker_data_2021-09-25 - Copy/AGGR_ended_2021-09-25.csv
          Date  Open  High   Low  Close  Adj Close  Volume
0   2021-05-21  9.68  9.95  9.65   9.95       9.95   21600
1   2021-05-24  9.95  9.95  9.95   9.95       9.95       0
2   2021-05-25  9.64  9.90  9.63   9.88       9.88   11400
3   2021-05-26  9.86  9.88  9.84   9.88       9.88     800
4   2021-05-27  9.88  9.88  9.88   9.88       9.88       0
..         ...   ...   ...   ...    ...        ...     ...
60  2021-08-27  9.62  9.62  9.62   9.62       9.62  110000
61  2021-08-30  9.62  9.62  9.62   9.62       9.62       0
62  2021-08-31  9.63  9.63  9.63   9.63       9.63   30000
63  2021-09-01  9.63  9.63  9.63   9.63       9.63       0
64  2021-09-02  9.63  9.63  9.63   9.63       9.63  420000

[65 rows x 7 columns]
tolistdate: 0     2021-05-21
1     2021-05-24
2     2021-05-25
3     2021-05-26
4     2021-05-27
         ...
60    2021-08-27
61    2021-08-30
62    2021-08-31
63    2021-09-01
64    2021-09-02
Name: Date, Length: 65, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AGGR_ended_2021-09-25  2021-05-21          9.63   9.58   9.95       0.037

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.617     9.654     9.691     9.728     9.765     9.802     9.839

  markup_80 markup_90 markup_100
0     9.876     9.913       9.95
                   stock  start_date current_price minall maxall each_markup  \
0  AGGR_ended_2021-09-25  2021-05-21          9.63   9.58   9.95       0.037

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.617     9.654     9.691     9.728     9.765     9.802     9.839

  markup_80 markup_90 markup_100
0     9.876     9.913       9.95
./ticker_data/ticker_data_2021-09-25 - Copy/AGIO_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2013-07-24  29.000000  32.000000  27.160000  31.280001  31.280001
1     2013-07-25  31.040001  31.469999  27.760000  27.780001  27.780001
2     2013-07-26  27.750000  29.450001  27.750000  28.530001  28.530001
3     2013-07-29  28.490000  30.790001  28.020000  28.639999  28.639999
4     2013-07-30  28.549999  29.860001  28.120001  29.100000  29.100000
...          ...        ...        ...        ...        ...        ...
2040  2021-08-30  45.009998  45.400002  43.919998  43.990002  43.990002
2041  2021-08-31  44.180000  44.889999  43.990002  44.680000  44.680000
2042  2021-09-01  44.970001  45.880001  44.490002  45.799999  45.799999
2043  2021-09-02  46.000000  46.880001  45.669998  46.419998  46.419998
2044  2021-09-03  46.369999  46.770000  46.119999  46.430000  46.430000

        Volume
0      6203200
1       592600
2       313700
3       149400
4        77300
...        ...
2040  39490000
2041  46840000
2042  48660000
2043  33680000
2044  31060000

[2045 rows x 7 columns]
tolistdate: 0       2013-07-24
1       2013-07-25
2       2013-07-26
3       2013-07-29
4       2013-07-30
           ...
2040    2021-08-30
2041    2021-08-31
2042    2021-09-01
2043    2021-09-02
2044    2021-09-03
Name: Date, Length: 2045, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AGIO_ended_2021-09-25  2013-07-24         46.43  15.77  138.85      12.308

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    28.078    40.386    52.694    65.002     77.31    89.618   101.926

  markup_80 markup_90 markup_100
0   114.234   126.542     138.85
                   stock  start_date current_price minall  maxall each_markup  \
0  AGIO_ended_2021-09-25  2013-07-24         46.43  15.77  138.85      12.308

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    28.078    40.386    52.694    65.002     77.31    89.618   101.926

  markup_80 markup_90 markup_100
0   114.234   126.542     138.85
./ticker_data/ticker_data_2021-09-25 - Copy/AGLE_ended_2021-09-25.csv
            Date   Open   High     Low  Close  Adj Close    Volume
0     2016-04-07  10.00  10.72   9.610   9.77       9.77   1428300
1     2016-04-08  10.00  12.75  10.000  11.99      11.99    560400
2     2016-04-11  11.87  12.04  10.300  10.42      10.42    182600
3     2016-04-12  10.44  10.74   9.420   9.65       9.65    193200
4     2016-04-13   9.94  10.86   9.850  10.07      10.07     70900
...          ...    ...    ...     ...    ...        ...       ...
1358  2021-08-30   7.36   7.46   7.120   7.13       7.13   7800000
1359  2021-08-31   7.12   7.35   6.740   7.25       7.25  11110000
1360  2021-09-01   7.21   7.27   7.000   7.25       7.25   9960000
1361  2021-09-02   7.20   7.46   7.078   7.45       7.45   6360000
1362  2021-09-03   7.38   7.50   7.290   7.40       7.40   5940000

[1363 rows x 7 columns]
tolistdate: 0       2016-04-07
1       2016-04-08
2       2016-04-11
3       2016-04-12
4       2016-04-13
           ...
1358    2021-08-30
1359    2021-08-31
1360    2021-09-01
1361    2021-09-02
1362    2021-09-03
Name: Date, Length: 1363, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AGLE_ended_2021-09-25  2016-04-07           7.4   2.81  12.75       0.994

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.804     4.798     5.792     6.786      7.78     8.774     9.768

  markup_80 markup_90 markup_100
0    10.762    11.756      12.75
                   stock  start_date current_price minall maxall each_markup  \
0  AGLE_ended_2021-09-25  2016-04-07           7.4   2.81  12.75       0.994

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.804     4.798     5.792     6.786      7.78     8.774     9.768

  markup_80 markup_90 markup_100

0    10.762    11.756      12.75
./ticker_data/ticker_data_2021-09-25 - Copy/AGMH_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close    Volume
0    2018-04-18   5.75   7.50  5.010  6.300      6.300    291800
1    2018-04-19   6.80   8.86  6.684  8.480      8.480    299600
2    2018-04-20  13.26  14.99  7.590  7.788      7.788    830400
3    2018-04-23   7.50   8.58  7.010  8.400      8.400    102600
4    2018-04-24   8.12   8.64  7.280  8.450      8.450     87600
..          ...    ...    ...    ...    ...        ...       ...
843  2021-08-30   9.50   9.88  9.239  9.880      9.880  18710000
844  2021-08-31   9.84   9.84  9.330  9.560      9.560   4310000
845  2021-09-01   9.47   9.91  9.340  9.700      9.700   8710000
846  2021-09-02   9.63   9.63  8.890  9.080      9.080   8770000
847  2021-09-03   9.25   9.51  9.100  9.380      9.380   7610000

[848 rows x 7 columns]
tolistdate: 0      2018-04-18
1      2018-04-19
2      2018-04-20
3      2018-04-23
4      2018-04-24
          ...
843    2021-08-30
844    2021-08-31
845    2021-09-01
846    2021-09-02
847    2021-09-03
Name: Date, Length: 848, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AGMH_ended_2021-09-25  2018-04-18          9.38   5.01  52.001      4.6991

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.7091   14.4082   19.1073   23.8064   28.5055   33.2046   37.9037

  markup_80 markup_90 markup_100
0   42.6028   47.3019     52.001
                   stock  start_date current_price minall  maxall each_markup  \
0  AGMH_ended_2021-09-25  2018-04-18          9.38   5.01  52.001      4.6991

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.7091   14.4082   19.1073   23.8064   28.5055   33.2046   37.9037

  markup_80 markup_90 markup_100
0   42.6028   47.3019     52.001
./ticker_data/ticker_data_2021-09-25 - Copy/AGNCM_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  Volume
0    2019-03-06  24.750000  24.889999  24.750000  24.799999  20.948973   69200
1    2019-03-07  24.809999  24.900000  24.770000  24.830999  20.975159  327400
2    2019-03-08  24.830000  24.850000  24.799999  24.849001  20.990364  174200
3    2019-03-11  24.950001  24.950001  24.830000  24.860001  20.999655  170200
4    2019-03-12  24.860001  24.920000  24.830000  24.860001  20.999655  242900
..          ...        ...        ...        ...        ...        ...     ...
641  2021-09-20  26.010000  26.037001  25.870001  25.889999  25.889999    6200
642  2021-09-21  25.860001  25.959999  25.860001  25.885000  25.885000    8300
643  2021-09-22  25.940001  26.070000  25.940001  26.059999  26.059999    6000
644  2021-09-23  26.049999  26.049999  25.910000  26.000000  26.000000   10900
645  2021-09-24  26.000000  25.900000  25.799999  25.889999  25.889999    7770

[646 rows x 7 columns]
tolistdate: 0      2019-03-06
1      2019-03-07
2      2019-03-08
3      2019-03-11
4      2019-03-12
          ...
641    2021-09-20
642    2021-09-21
643    2021-09-22
644    2021-09-23
645    2021-09-24
Name: Date, Length: 646, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AGNCM_ended_2021-09-25  2019-03-06         25.89  10.05   26.5       1.645

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.695     13.34    14.985     16.63    18.275     19.92    21.565

  markup_80 markup_90 markup_100
0     23.21    24.855       26.5
                    stock  start_date current_price minall maxall each_markup  \
0  AGNCM_ended_2021-09-25  2019-03-06         25.89  10.05   26.5       1.645

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.695     13.34    14.985     16.63    18.275     19.92    21.565

  markup_80 markup_90 markup_100
0     23.21    24.855       26.5
./ticker_data/ticker_data_2021-09-25 - Copy/AGNCN_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2017-08-16  24.799999  24.889999  24.700001  24.850000  18.923258
1     2017-08-17  24.940001  25.049999  24.850000  24.950001  18.999409
2     2017-08-18  24.950001  25.049999  24.900000  24.980000  19.022251
3     2017-08-21  24.980000  25.100000  24.900000  24.950001  18.999409
4     2017-08-22  25.000000  25.100000  24.940001  25.010000  19.045097
...          ...        ...        ...        ...        ...        ...
1015  2021-08-30  26.309999  26.490000  26.309999  26.350000  26.350000
1016  2021-08-31  26.270000  26.350000  26.040001  26.110001  26.110001
1017  2021-09-01  26.120001  26.219999  26.070000  26.120001  26.120001
1018  2021-09-02  26.080000  26.240000  26.080000  26.219999  26.219999
1019  2021-09-03  26.160000  26.184000  26.059999  26.125000  26.125000

       Volume
0     4632800
1     1797500
2      507500
3      186800
4      385000
...       ...
1015  1280000
1016  4150000
1017  1540000
1018  1290000
1019  1300000

[1020 rows x 7 columns]
tolistdate: 0       2017-08-16
1       2017-08-17
2       2017-08-18
3       2017-08-21
4       2017-08-22
           ...
1015    2021-08-30
1016    2021-08-31
1017    2021-09-01
1018    2021-09-02
1019    2021-09-03
Name: Date, Length: 1020, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AGNCN_ended_2021-09-25  2017-08-16        26.125     10  27.09       1.709

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.709    13.418    15.127    16.836    18.545    20.254    21.963

  markup_80 markup_90 markup_100
0    23.672    25.381      27.09
                    stock  start_date current_price minall maxall each_markup  \
0  AGNCN_ended_2021-09-25  2017-08-16        26.125     10  27.09       1.709

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.709    13.418    15.127    16.836    18.545    20.254    21.963

  markup_80 markup_90 markup_100
0    23.672    25.381      27.09
./ticker_data/ticker_data_2021-09-25 - Copy/AGNCO_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-09-27  25.000000  25.000000  24.799999  24.910000  22.005598
1    2019-09-30  24.940001  25.129999  24.920000  25.049999  22.129274
2    2019-10-01  25.049999  25.080000  24.980000  25.049999  22.129274
3    2019-10-02  25.100000  25.100000  24.980000  25.040001  22.120445
4    2019-10-03  25.049999  25.150000  25.000000  25.139999  22.208784
..          ...        ...        ...        ...        ...        ...
483  2021-08-30  25.930000  25.930000  25.830000  25.830000  25.830000
484  2021-08-31  25.799999  25.850000  25.760000  25.799999  25.799999
485  2021-09-01  25.850000  25.850000  25.750000  25.790001  25.790001
486  2021-09-02  25.809999  25.900000  25.770000  25.770000  25.770000
487  2021-09-03  25.799999  25.809999  25.760000  25.790001  25.790001

      Volume
0    6105500
1    1281500
2     983100
3     362200
4     369500
..       ...
483  1550000
484  4920000
485  3720000
486  3030000
487  2790000

[488 rows x 7 columns]
tolistdate: 0      2019-09-27
1      2019-09-30
2      2019-10-01
3      2019-10-02
4      2019-10-03
          ...
483    2021-08-30
484    2021-08-31
485    2021-09-01
486    2021-09-02
487    2021-09-03
Name: Date, Length: 488, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AGNCO_ended_2021-09-25  2019-09-27         25.79   8.87  26.59       1.772

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.642    12.414    14.186    15.958     17.73    19.502    21.274

  markup_80 markup_90 markup_100
0    23.046    24.818      26.59
                    stock  start_date current_price minall maxall each_markup  \
0  AGNCO_ended_2021-09-25  2019-09-27         25.79   8.87  26.59       1.772

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.642    12.414    14.186    15.958     17.73    19.502    21.274

  markup_80 markup_90 markup_100
0    23.046    24.818      26.59
./ticker_data/ticker_data_2021-09-25 - Copy/AGNCP_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-02-05  25.000000  25.510000  24.969999  24.980000  22.990997
1    2020-02-06  25.030001  25.040001  24.980000  25.000000  23.009405
2    2020-02-07  25.020000  25.040001  24.900000  24.940001  22.954182
3    2020-02-10  24.959999  25.000000  24.910000  24.920000  22.935776
4    2020-02-11  24.950001  24.980000  24.900000  24.950001  22.963387
..          ...        ...        ...        ...        ...        ...
394  2021-08-30  25.488001  25.500000  25.469999  25.490000  25.490000
395  2021-08-31  25.490000  25.590000  25.370001  25.570000  25.570000
396  2021-09-01  25.549999  25.559999  25.440001  25.559999  25.559999
397  2021-09-02  25.469999  25.559999  25.469999  25.500000  25.500000
398  2021-09-03  25.549999  25.549999  25.379999  25.459999  25.459999

       Volume
0     7403378
1     1749761
2      900114
3      918834
4      899566
..        ...
394   3880000
395  10990000
396   5960000
397   2110000
398   1170000

[399 rows x 7 columns]
tolistdate: 0      2020-02-05
1      2020-02-06
2      2020-02-07
3      2020-02-10
4      2020-02-11
          ...
394    2021-08-30
395    2021-08-31
396    2021-09-01
397    2021-09-02
398    2021-09-03
Name: Date, Length: 399, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AGNCP_ended_2021-09-25  2020-02-05         25.46    8.8  25.59       1.679

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.479    12.158    13.837    15.516    17.195    18.874    20.553

  markup_80 markup_90 markup_100
0    22.232    23.911      25.59
                    stock  start_date current_price minall maxall each_markup  \
0  AGNCP_ended_2021-09-25  2020-02-05         25.46    8.8  25.59       1.679

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.479    12.158    13.837    15.516    17.195    18.874    20.553

  markup_80 markup_90 markup_100
0    22.232    23.911      25.59
./ticker_data/ticker_data_2021-09-25 - Copy/AGNC_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2008-05-15  19.500000  19.650000  19.170000  19.350000   2.791297
1     2008-05-16  19.250000  20.010000  19.250000  19.990000   2.883619
2     2008-05-19  19.889999  19.990000  19.250000  19.510000   2.814379
3     2008-05-20  19.490000  19.809999  19.270000  19.350000   2.791297
4     2008-05-21  19.280001  19.440001  19.240000  19.250000   2.776873
...          ...        ...        ...        ...        ...        ...
3360  2021-09-20  15.840000  15.960000  15.740000  15.910000  15.910000
3361  2021-09-21  15.940000  16.120001  15.940000  16.020000  16.020000
3362  2021-09-22  16.080000  16.260000  16.049999  16.209999  16.209999
3363  2021-09-23  16.250000  16.299999  16.209999  16.219999  16.219999
3364  2021-09-24  16.209999  16.250000  16.160000  16.215000  16.215000

       Volume
0     4197900
1     1109600
2      329700
3      110100
4      300300
...       ...
3360  7826500
3361  7727900
3362  5492700
3363  4671800
3364  2048607

[3365 rows x 7 columns]
tolistdate: 0       2008-05-15
1       2008-05-16
2       2008-05-19
3       2008-05-20
4       2008-05-21
           ...
3360    2021-09-20
3361    2021-09-21
3362    2021-09-22
3363    2021-09-23
3364    2021-09-24
Name: Date, Length: 3365, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AGNC_ended_2021-09-25  2008-05-15        16.215   6.25  36.77       3.052

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.302    12.354    15.406    18.458     21.51    24.562    27.614

  markup_80 markup_90 markup_100
0    30.666    33.718      36.77
                   stock  start_date current_price minall maxall each_markup  \
0  AGNC_ended_2021-09-25  2008-05-15        16.215   6.25  36.77       3.052

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.302    12.354    15.406    18.458     21.51    24.562    27.614

  markup_80 markup_90 markup_100
0    30.666    33.718      36.77
./ticker_data/ticker_data_2021-09-25 - Copy/AGRX_ended_2021-09-25.csv
            Date  Open   High   Low  Close  Adj Close    Volume
0     2014-05-23  5.50  6.060  5.05   5.54       5.54   3359800
1     2014-05-27  5.51  5.610  5.42   5.55       5.55    290000
2     2014-05-28  5.53  5.930  5.52   5.80       5.80    238300
3     2014-05-29  5.90  6.030  5.75   5.94       5.94    211900
4     2014-05-30  5.95  6.000  5.61   5.85       5.85    172500
...          ...   ...    ...   ...    ...        ...       ...
1829  2021-08-30  1.14  1.180  1.13   1.18       1.18  67120000
1830  2021-08-31  1.18  1.185  1.15   1.16       1.16  50810000
1831  2021-09-01  1.18  1.180  1.16   1.17       1.17  35940000
1832  2021-09-02  1.21  1.210  1.17   1.19       1.19  30210000
1833  2021-09-03  1.18  1.190  1.17   1.17       1.17  25240000

[1834 rows x 7 columns]
tolistdate: 0       2014-05-23
1       2014-05-27
2       2014-05-28
3       2014-05-29
4       2014-05-30
           ...
1829    2021-08-30
1830    2021-08-31
1831    2021-09-01
1832    2021-09-02
1833    2021-09-03
Name: Date, Length: 1834, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AGRX_ended_2021-09-25  2014-05-23          1.17  0.231  13.19      1.2959

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    1.5269    2.8228    4.1187    5.4146    6.7105    8.0064    9.3023

  markup_80 markup_90 markup_100
0   10.5982   11.8941      13.19
                   stock  start_date current_price minall maxall each_markup  \
0  AGRX_ended_2021-09-25  2014-05-23          1.17  0.231  13.19      1.2959

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    1.5269    2.8228    4.1187    5.4146    6.7105    8.0064    9.3023

  markup_80 markup_90 markup_100
0   10.5982   11.8941      13.19
./ticker_data/ticker_data_2021-09-25 - Copy/AGTC_ended_2021-09-25.csv
            Date   Open       High     Low  Close  Adj Close    Volume
0     2014-03-27  12.75  16.820000  12.500  14.76      14.76   1566100
1     2014-03-28  14.95  15.900000  13.630  14.55      14.55    183900
2     2014-03-31  14.60  15.450000  14.600  15.00      15.00     35800
3     2014-04-01  15.18  18.389999  15.180  15.61      15.61    120400
4     2014-04-02  16.00  17.180000  15.500  16.35      16.35    134600
...          ...    ...        ...     ...    ...        ...       ...
1870  2021-08-30   3.64   3.680000   3.540   3.54       3.54  27920000
1871  2021-08-31   3.54   3.611000   3.480   3.55       3.55  50530000
1872  2021-09-01   3.56   3.605000   3.460   3.46       3.46  58500000
1873  2021-09-02   3.49   3.625000   3.429   3.57       3.57  64960000
1874  2021-09-03   3.59   3.590000   3.440   3.50       3.50  29700000

[1875 rows x 7 columns]
tolistdate: 0       2014-03-27
1       2014-03-28
2       2014-03-31
3       2014-04-01
4       2014-04-02
           ...
1870    2021-08-30
1871    2021-08-31
1872    2021-09-01
1873    2021-09-02
1874    2021-09-03
Name: Date, Length: 1875, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AGTC_ended_2021-09-25  2014-03-27           3.5   2.26  34.37       3.211

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.471     8.682    11.893    15.104    18.315    21.526    24.737

  markup_80 markup_90 markup_100
0    27.948    31.159      34.37
                   stock  start_date current_price minall maxall each_markup  \
0  AGTC_ended_2021-09-25  2014-03-27           3.5   2.26  34.37       3.211

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.471     8.682    11.893    15.104    18.315    21.526    24.737

  markup_80 markup_90 markup_100
0    27.948    31.159      34.37
./ticker_data/ticker_data_2021-09-25 - Copy/AGYS_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  14.250000  14.500000  14.250000  14.437500  13.025230
1     2000-01-03  14.500000  14.500000  14.125000  14.375000  12.968847
2     2000-01-04  14.000000  14.437500  13.937500  14.343750  12.967715
3     2000-01-05  14.312500  14.500000  14.125000  14.125000  12.769953
4     2000-01-06  14.000000  14.312500  13.750000  14.000000  12.656942
...          ...        ...        ...        ...        ...        ...
5464  2021-09-20  51.650002  52.930000  49.549999  50.730000  50.730000
5465  2021-09-21  51.110001  51.939999  50.430000  51.099998  51.099998
5466  2021-09-22  51.509998  52.939999  51.509998  52.400002  52.400002
5467  2021-09-23  52.820000  54.080002  51.770000  53.840000  53.840000
5468  2021-09-24  53.189999  53.930000  52.794998  53.605000  53.605000

      Volume
0      50500
1     433000
2      98500
3     908800
4     146700
...      ...
5464   79100
5465   65700
5466   41800
5467   44300
5468   13204

[5469 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5464    2021-09-20
5465    2021-09-21
5466    2021-09-22
5467    2021-09-23
5468    2021-09-24
Name: Date, Length: 5469, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AGYS_ended_2021-09-25  1999-12-31        53.605   1.89  64.09        6.22

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      8.11     14.33     20.55     26.77     32.99     39.21     45.43

  markup_80 markup_90 markup_100
0     51.65     57.87      64.09

                   stock  start_date current_price minall maxall each_markup  \
0  AGYS_ended_2021-09-25  1999-12-31        53.605   1.89  64.09        6.22

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      8.11     14.33     20.55     26.77     32.99     39.21     45.43

  markup_80 markup_90 markup_100
0     51.65     57.87      64.09
./ticker_data/ticker_data_2021-09-25 - Copy/AHACU_ended_2021-09-25.csv
           Date    Open    High     Low   Close  Adj Close   Volume
0    2020-09-18   9.850  10.000   9.850  10.000     10.000  3209800
1    2020-09-21   9.920   9.930   9.910   9.921      9.921    67100
2    2020-09-22   9.960   9.980   9.910   9.920      9.920    94900
3    2020-09-23   9.950   9.960   9.930   9.940      9.940    28400
4    2020-09-24   9.945   9.945   9.920   9.940      9.940   106700
..          ...     ...     ...     ...     ...        ...      ...
216  2021-08-20  10.745  10.745  10.745  10.745     10.745    30000
217  2021-08-23  11.175  11.350  11.175  11.175     11.175   150000
218  2021-08-24  10.850  11.350  10.850  11.350     11.350   230000
219  2021-08-25  11.350  11.350  11.200  11.200     11.200    90000
220  2021-08-26  11.070  12.077  11.070  12.077     12.077   330000

[221 rows x 7 columns]
tolistdate: 0      2020-09-18
1      2020-09-21
2      2020-09-22
3      2020-09-23
4      2020-09-24
          ...
216    2021-08-20
217    2021-08-23
218    2021-08-24
219    2021-08-25
220    2021-08-26
Name: Date, Length: 221, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AHACU_ended_2021-09-25  2020-09-18        12.077  9.831  20.23      1.0399

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   10.8709   11.9108   12.9507   13.9906   15.0305   16.0704   17.1103

  markup_80 markup_90 markup_100
0   18.1502   19.1901      20.23
                    stock  start_date current_price minall maxall each_markup  \
0  AHACU_ended_2021-09-25  2020-09-18        12.077  9.831  20.23      1.0399

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   10.8709   11.9108   12.9507   13.9906   15.0305   16.0704   17.1103

  markup_80 markup_90 markup_100
0   18.1502   19.1901      20.23
./ticker_data/ticker_data_2021-09-25 - Copy/AHACW_ended_2021-09-25.csv
         Date  Open   High   Low   Close  Adj Close  Volume
0  2021-08-26  2.26  2.841  2.21  2.7951     2.7951   80740
tolistdate: 0    2021-08-26
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AHACW_ended_2021-09-25  2021-08-26        2.7951   2.21  2.841      0.0631

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.2731    2.3362    2.3993    2.4624    2.5255    2.5886    2.6517

  markup_80 markup_90 markup_100
0    2.7148    2.7779      2.841
                    stock  start_date current_price minall maxall each_markup  \
0  AHACW_ended_2021-09-25  2021-08-26        2.7951   2.21  2.841      0.0631

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.2731    2.3362    2.3993    2.4624    2.5255    2.5886    2.6517

  markup_80 markup_90 markup_100
0    2.7148    2.7779      2.841
./ticker_data/ticker_data_2021-09-25 - Copy/AHAC_ended_2021-09-25.csv
           Date     Open     High      Low    Close  Adj Close  Volume
0    2020-12-01   9.7000  10.1400   9.6500   9.6700     9.6700    3284
1    2020-12-02   9.7400   9.7500   9.7000   9.7200     9.7200    3800
2    2020-12-03   9.7100   9.7300   9.7000   9.7200     9.7200   22350
3    2020-12-04   9.7200   9.8100   9.7200   9.8100     9.8100    6107
4    2020-12-07   9.8500   9.9000   9.7401   9.7401     9.7401   24655
..          ...      ...      ...      ...      ...        ...     ...
181  2021-08-20   9.2600  10.2200   9.2600  10.0200    10.0200  228043
182  2021-08-23  10.0100  10.2138   9.9250  10.1900    10.1900  118347
183  2021-08-24  10.2100  10.2689  10.0200  10.1000    10.1000  122014
184  2021-08-25  10.6946  10.6946  10.0000  10.1500    10.1500  232285
185  2021-08-26  10.2000  11.2700  10.1700  10.9600    10.9600  298128

[186 rows x 7 columns]
tolistdate: 0      2020-12-01
1      2020-12-02
2      2020-12-03
3      2020-12-04
4      2020-12-07
          ...
181    2021-08-20
182    2021-08-23
183    2021-08-24
184    2021-08-25
185    2021-08-26
Name: Date, Length: 186, dtype: object
                   stock  start_date current_price minall   maxall  \
0  AHAC_ended_2021-09-25  2020-12-01         10.96   9.12  16.9599

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.78399   9.90399    10.688    11.472    12.256   13.0399   13.8239

  markup_70 markup_80 markup_90 markup_100
0   14.6079   15.3919   16.1759    16.9599
                   stock  start_date current_price minall   maxall  \
0  AHAC_ended_2021-09-25  2020-12-01         10.96   9.12  16.9599

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.78399   9.90399    10.688    11.472    12.256   13.0399   13.8239

  markup_70 markup_80 markup_90 markup_100
0   14.6079   15.3919   16.1759    16.9599
./ticker_data/ticker_data_2021-09-25 - Copy/AHCO_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-05-31   9.700000   9.700000   9.700000   9.700000   9.700000
1    2018-06-12   9.700000   9.700000   9.700000   9.700000   9.700000
2    2018-06-13   9.700000   9.710000   9.700000   9.700000   9.700000
3    2018-06-14   9.750000   9.750000   9.750000   9.750000   9.750000
4    2018-06-15   9.750000   9.750000   9.750000   9.750000   9.750000
..          ...        ...        ...        ...        ...        ...
685  2021-08-30  23.650000  24.030001  23.250000  23.750000  23.750000
686  2021-08-31  23.809999  24.424999  23.559999  24.040001  24.040001
687  2021-09-01  24.020000  24.480000  23.420000  24.090000  24.090000
688  2021-09-02  24.160000  25.150000  23.870001  24.889999  24.889999
689  2021-09-03  25.250000  25.250000  24.250000  24.379999  24.379999

        Volume
0            0
1       305000
2       279000
3        50000
4            0
..         ...
685   37630000
686  105660000
687   94660000
688   59170000
689   83180000

[690 rows x 7 columns]
tolistdate: 0      2018-05-31
1      2018-06-12
2      2018-06-13
3      2018-06-14
4      2018-06-15
          ...
685    2021-08-30
686    2021-08-31
687    2021-09-01
688    2021-09-02
689    2021-09-03
Name: Date, Length: 690, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AHCO_ended_2021-09-25  2018-05-31         24.38   7.82  41.579      3.3759

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   11.1959   14.5718   17.9477   21.3236   24.6995   28.0754   31.4513

  markup_80 markup_90 markup_100
0   34.8272   38.2031     41.579
                   stock  start_date current_price minall  maxall each_markup  \
0  AHCO_ended_2021-09-25  2018-05-31         24.38   7.82  41.579      3.3759

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   11.1959   14.5718   17.9477   21.3236   24.6995   28.0754   31.4513

  markup_80 markup_90 markup_100
0   34.8272   38.2031     41.579
./ticker_data/ticker_data_2021-09-25 - Copy/AHPI_ended_2021-09-25.csv
            Date   Open    High   Low    Close  Adj Close     Volume
0     1999-12-31   4.75   4.750  4.75  4.75000    4.75000       1100
1     2000-01-03   5.50   5.500  5.00  5.00000    5.00000        900
2     2000-01-04   5.00   5.000  5.00  5.00000    5.00000        100
3     2000-01-05   5.50   5.625  5.50  5.62500    5.62500        100
4     2000-01-06   5.50   5.750  4.75  5.65625    5.65625      30700
...          ...    ...     ...   ...      ...        ...        ...
5050  2021-08-30   9.81  11.160  9.70  9.98000    9.98000  221960000
5051  2021-08-31  10.32  10.320  9.32  9.44000    9.44000   91170000
5052  2021-09-01   9.49   9.760  9.21  9.65000    9.65000   41330000
5053  2021-09-02   9.55   9.920  9.40  9.81000    9.81000   42350000
5054  2021-09-03   9.95   9.950  9.13  9.18000    9.18000   40710000

[5055 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5050    2021-08-30
5051    2021-08-31
5052    2021-09-01
5053    2021-09-02
5054    2021-09-03
Name: Date, Length: 5055, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AHPI_ended_2021-09-25  1999-12-31          9.18   0.92     45       4.408

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.328     9.736    14.144    18.552     22.96    27.368    31.776

  markup_80 markup_90 markup_100
0    36.184    40.592         45
                   stock  start_date current_price minall maxall each_markup  \
0  AHPI_ended_2021-09-25  1999-12-31          9.18   0.92     45       4.408

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.328     9.736    14.144    18.552     22.96    27.368    31.776

  markup_80 markup_90 markup_100
0    36.184    40.592         45
./ticker_data/ticker_data_2021-09-25 - Copy/AIHS_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close    Volume
0    2018-03-19  5.650  6.150  5.550  5.930      5.930    112100
1    2018-03-20  6.250  6.250  5.000  5.160      5.160     86600
2    2018-03-21  5.130  5.780  5.090  5.650      5.650     87300
3    2018-03-22  5.740  5.990  5.650  5.989      5.989     84100
4    2018-03-23  5.950  6.000  5.450  5.980      5.980     90000
..          ...    ...    ...    ...    ...        ...       ...
868  2021-08-30  0.610  0.630  0.603  0.614      0.614  22550000
869  2021-08-31  0.627  0.627  0.596  0.603      0.603  30160000
870  2021-09-01  0.603  0.620  0.600  0.616      0.616  33280000
871  2021-09-02  0.628  0.650  0.611  0.618      0.618  26240000
872  2021-09-03  0.615  0.635  0.603  0.617      0.617  17270000

[873 rows x 7 columns]
tolistdate: 0      2018-03-19
1      2018-03-20
2      2018-03-21
3      2018-03-22
4      2018-03-23
          ...
868    2021-08-30
869    2021-08-31
870    2021-09-01
871    2021-09-02
872    2021-09-03
Name: Date, Length: 873, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AIHS_ended_2021-09-25  2018-03-19         0.617   0.26   8.91       0.865

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.125      1.99     2.855      3.72     4.585      5.45     6.315

  markup_80 markup_90 markup_100
0      7.18     8.045       8.91
                   stock  start_date current_price minall maxall each_markup  \
0  AIHS_ended_2021-09-25  2018-03-19         0.617   0.26   8.91       0.865

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.125      1.99     2.855      3.72     4.585      5.45     6.315

  markup_80 markup_90 markup_100
0      7.18     8.045       8.91
./ticker_data/ticker_data_2021-09-25 - Copy/AIH_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close  Volume
0    2019-10-25  12.35  12.56  7.190  10.03      10.03  775900
1    2019-10-28   9.31   9.80  8.180   9.35       9.35   98600
2    2019-10-29   9.74   9.80  8.921   9.21       9.21   43400
3    2019-10-30   8.30   9.27  8.270   8.80       8.80   44200
4    2019-10-31   8.80   8.80  8.800   8.80       8.80       0
..          ...    ...    ...    ...    ...        ...     ...
478  2021-09-20   3.61   3.61  3.380   3.47       3.47   22900
479  2021-09-21   3.46   3.74  3.460   3.70       3.70   35000
480  2021-09-22   3.70   3.99  3.700   3.91       3.91   28900
481  2021-09-23   3.91   3.91  3.760   3.79       3.79   17100
482  2021-09-24   3.81   3.81  3.710   3.72       3.72    4495

[483 rows x 7 columns]
tolistdate: 0      2019-10-25
1      2019-10-28
2      2019-10-29
3      2019-10-30
4      2019-10-31
          ...
478    2021-09-20
479    2021-09-21
480    2021-09-22
481    2021-09-23
482    2021-09-24
Name: Date, Length: 483, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  AIH_ended_2021-09-25  2019-10-25          3.72   3.38  12.56       0.918

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.298     5.216     6.134     7.052      7.97     8.888     9.806

  markup_80 markup_90 markup_100
0    10.724    11.642      12.56
                  stock  start_date current_price minall maxall each_markup  \
0  AIH_ended_2021-09-25  2019-10-25          3.72   3.38  12.56       0.918

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.298     5.216     6.134     7.052      7.97     8.888     9.806

  markup_80 markup_90 markup_100
0    10.724    11.642      12.56
./ticker_data/ticker_data_2021-09-25 - Copy/AIKI_ended_2021-09-25.csv
            Date          Open          High           Low         Close  \
0     1999-12-31  82630.804688  82630.804688  76274.585938  79906.710938
1     2000-01-03  82630.804688  82630.804688  76274.585938  80814.742188
2     2000-01-04  80814.742188  80814.742188  76274.585938  77182.617188
3     2000-01-05  79906.710938  79906.710938  77182.617188  79906.710938
4     2000-01-06  80814.742188  82630.804688  76274.585938  78090.648438
...          ...           ...           ...           ...           ...
5402  2021-08-30      0.810000      0.810000      0.780000      0.790000
5403  2021-08-31      0.800000      0.830000      0.800000      0.830000
5404  2021-09-01      0.830000      0.840000      0.810000      0.830000
5405  2021-09-02      0.830000      0.840000      0.820000      0.820000
5406  2021-09-03      0.820000      0.830000      0.800000      0.800000

         Adj Close    Volume
0     79906.710938         0
1     80814.742188         0
2     77182.617188         0
3     79906.710938         0
4     78090.648438         0
...            ...       ...
5402      0.790000  60060000
5403      0.830000  65450000
5404      0.830000  83880000
5405      0.820000  55830000
5406      0.800000  50810000

[5407 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5402    2021-08-30
5403    2021-08-31
5404    2021-09-01
5405    2021-09-02
5406    2021-09-03
Name: Date, Length: 5407, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AIKI_ended_2021-09-25  1999-12-31           0.8   0.47  217927     21792.7

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   21793.2   43585.9   65378.5   87171.2    108964    130757    152549

  markup_80 markup_90 markup_100
0    174342    196135     217927
                   stock  start_date current_price minall  maxall each_markup  \
0  AIKI_ended_2021-09-25  1999-12-31           0.8   0.47  217927     21792.7

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   21793.2   43585.9   65378.5   87171.2    108964    130757    152549

  markup_80 markup_90 markup_100
0    174342    196135     217927
./ticker_data/ticker_data_2021-09-25 - Copy/AIMC_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2006-12-15  13.500000  14.290000  13.360000  14.290000  12.302939
1     2006-12-18  13.900000  14.220000  13.530000  13.990000  12.044651
2     2006-12-19  13.700000  13.800000  13.500000  13.790000  11.872465
3     2006-12-20  13.500000  13.800000  13.500000  13.750000  11.838027
4     2006-12-21  13.700000  14.550000  13.600000  14.550000  12.526785
...          ...        ...        ...        ...        ...        ...
3700  2021-08-30  61.540001  61.599998  59.669998  59.919998  59.919998
3701  2021-08-31  60.209999  60.779999  58.360001  58.560001  58.560001
3702  2021-09-01  58.810001  59.110001  57.730000  58.720001  58.720001
3703  2021-09-02  59.049999  59.910000  58.400002  59.310001  59.310001
3704  2021-09-03  59.349998  59.490002  58.020000  58.340000  58.340000

        Volume
0      5134900
1       426100
2       289000
3       155400
4       184700
...        ...
3700  17360000
3701  34100000
3702  30480000
3703  22410000
3704  30980000

[3705 rows x 7 columns]
tolistdate: 0       2006-12-15
1       2006-12-18
2       2006-12-19
3       2006-12-20
4       2006-12-21
           ...
3700    2021-08-30
3701    2021-08-31
3702    2021-09-01
3703    2021-09-02
3704    2021-09-03
Name: Date, Length: 3705, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AIMC_ended_2021-09-25  2006-12-15         58.34   3.07  68.07         6.5

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.57     16.07     22.57     29.07     35.57     42.07     48.57

  markup_80 markup_90 markup_100
0     55.07     61.57      68.07
                   stock  start_date current_price minall maxall each_markup  \
0  AIMC_ended_2021-09-25  2006-12-15         58.34   3.07  68.07         6.5

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.57     16.07     22.57     29.07     35.57     42.07     48.57

  markup_80 markup_90 markup_100
0     55.07     61.57      68.07

./ticker_data/ticker_data_2021-09-25 - Copy/AINV_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2004-04-06  46.230000  46.320000  45.000000  45.000000   6.199956
1     2004-04-07  45.090000  45.689999  45.000000  45.000000   6.199956
2     2004-04-08  45.240002  45.869999  45.150002  45.750000   6.303289
3     2004-04-12  45.750000  45.750000  45.090000  45.570000   6.278490
4     2004-04-13  45.720001  45.720001  45.000000  45.119999   6.216489
...          ...        ...        ...        ...        ...        ...
4394  2021-09-20  12.930000  12.960000  12.350000  12.730000  12.730000
4395  2021-09-21  12.800000  13.060000  12.800000  12.900000  12.900000
4396  2021-09-22  12.930000  13.110000  12.920000  12.990000  12.990000
4397  2021-09-23  12.940000  13.130000  12.940000  12.980000  12.980000
4398  2021-09-24  12.940000  13.070000  12.926500  13.060000  13.060000

       Volume
0     5615467
1      929000
2      428600
3      322100
4     1261900
...       ...
4394  1131100
4395   434800
4396   306300
4397   434900
4398    87687

[4399 rows x 7 columns]
tolistdate: 0       2004-04-06
1       2004-04-07
2       2004-04-08
3       2004-04-12
4       2004-04-13
           ...
4394    2021-09-20
4395    2021-09-21
4396    2021-09-22
4397    2021-09-23
4398    2021-09-24
Name: Date, Length: 4399, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AINV_ended_2021-09-25  2004-04-06         13.06    5.2   72.6        6.74

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     11.94     18.68     25.42     32.16      38.9     45.64     52.38

  markup_80 markup_90 markup_100
0     59.12     65.86       72.6
                   stock  start_date current_price minall maxall each_markup  \
0  AINV_ended_2021-09-25  2004-04-06         13.06    5.2   72.6        6.74

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     11.94     18.68     25.42     32.16      38.9     45.64     52.38

  markup_80 markup_90 markup_100
0     59.12     65.86       72.6
./ticker_data/ticker_data_2021-09-25 - Copy/AIRG_ended_2021-09-25.csv
            Date   Open   High     Low   Close  Adj Close   Volume
0     2016-08-12   8.00   8.37   7.361   8.000      8.000   848700
1     2016-08-15   8.00   8.74   7.950   8.300      8.300   836100
2     2016-08-16   8.40   8.40   8.100   8.110      8.110   196900
3     2016-08-17   8.10   8.22   7.520   8.198      8.198   226300
4     2016-08-18   8.12   9.65   8.120   9.200      9.200   456300
...          ...    ...    ...     ...     ...        ...      ...
1269  2021-08-30  14.30  14.60  13.890  14.430     14.430  5820000
1270  2021-08-31  14.33  14.60  14.230  14.230     14.230  2110000
1271  2021-09-01  14.23  14.52  14.150  14.300     14.300  4150000
1272  2021-09-02  14.30  14.43  14.200  14.420     14.420  3870000
1273  2021-09-03  14.34  14.64  14.050  14.210     14.210  4430000

[1274 rows x 7 columns]
tolistdate: 0       2016-08-12
1       2016-08-15
2       2016-08-16
3       2016-08-17
4       2016-08-18
           ...
1269    2021-08-30
1270    2021-08-31
1271    2021-09-01
1272    2021-09-02
1273    2021-09-03
Name: Date, Length: 1274, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AIRG_ended_2021-09-25  2016-08-12         14.21   5.63   29.5       2.387

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.017    10.404    12.791    15.178    17.565    19.952    22.339

  markup_80 markup_90 markup_100
0    24.726    27.113       29.5
                   stock  start_date current_price minall maxall each_markup  \
0  AIRG_ended_2021-09-25  2016-08-12         14.21   5.63   29.5       2.387

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.017    10.404    12.791    15.178    17.565    19.952    22.339

  markup_80 markup_90 markup_100
0    24.726    27.113       29.5
./ticker_data/ticker_data_2021-09-25 - Copy/AIRTP_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  Volume
0    2019-06-13  28.969999  29.090000  23.420000  27.440001  22.901218    1100
1    2019-06-14  23.700001  23.900000  23.600000  23.799999  19.863300     300
2    2019-06-17  24.600000  26.900000  24.500000  26.900000  22.450537     100
3    2019-06-18  26.770000  26.770000  23.330000  23.430000  19.554501    5200
4    2019-06-19  23.500000  24.500000  23.500000  24.200001  20.197136    2600
..          ...        ...        ...        ...        ...        ...     ...
483  2021-08-30  24.920000  25.000000  24.889999  24.889999  24.889999  420000
484  2021-08-31  25.104000  25.129999  24.910000  24.910000  24.910000  840000
485  2021-09-01  24.910000  25.080000  24.910000  25.000000  25.000000  350000
486  2021-09-02  25.132000  25.132000  25.090000  25.120001  25.120001   60000
487  2021-09-03  25.240000  25.240000  25.090000  25.090000  25.090000   90000

[488 rows x 7 columns]
tolistdate: 0      2019-06-13
1      2019-06-14
2      2019-06-17
3      2019-06-18
4      2019-06-19
          ...
483    2021-08-30
484    2021-08-31
485    2021-09-01
486    2021-09-02
487    2021-09-03
Name: Date, Length: 488, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AIRTP_ended_2021-09-25  2019-06-13         25.09  18.01  29.09       1.108

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    19.118    20.226    21.334    22.442     23.55    24.658    25.766

  markup_80 markup_90 markup_100
0    26.874    27.982      29.09
                    stock  start_date current_price minall maxall each_markup  \
0  AIRTP_ended_2021-09-25  2019-06-13         25.09  18.01  29.09       1.108

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    19.118    20.226    21.334    22.442     23.55    24.658    25.766

  markup_80 markup_90 markup_100
0    26.874    27.982      29.09
./ticker_data/ticker_data_2021-09-25 - Copy/AIRTW_ended_2021-09-25.csv
         Date    Open  High     Low  Close  Adj Close  Volume
0  2021-08-30  0.0516  0.04  0.0083   0.01       0.01  459631
tolistdate: 0    2021-08-30
Name: Date, dtype: object
                    stock  start_date current_price  minall maxall  \
0  AIRTW_ended_2021-09-25  2021-08-30          0.01  0.0083   0.04

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00317   0.01147   0.01464   0.01781   0.02098   0.02415   0.02732

  markup_70 markup_80 markup_90 markup_100
0   0.03049   0.03366   0.03683       0.04
                    stock  start_date current_price  minall maxall  \
0  AIRTW_ended_2021-09-25  2021-08-30          0.01  0.0083   0.04

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00317   0.01147   0.01464   0.01781   0.02098   0.02415   0.02732

  markup_70 markup_80 markup_90 markup_100
0   0.03049   0.03366   0.03683       0.04
./ticker_data/ticker_data_2021-09-25 - Copy/AIRT_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   2.125000   2.125000   2.125000   2.125000   1.401639
1     2000-01-03   2.333333   2.333333   2.125000   2.125000   1.401639
2     2000-01-04   2.166667   2.166667   2.166667   2.166667   1.429123
3     2000-01-05   2.166667   2.166667   2.166667   2.166667   1.429123
4     2000-01-07   2.250000   2.375000   2.250000   2.375000   1.566538
...          ...        ...        ...        ...        ...        ...
5165  2021-09-20  38.660000  40.500000  37.770000  38.799999  38.799999
5166  2021-09-21  39.000000  39.750000  38.529999  39.750000  39.750000
5167  2021-09-22  40.180000  40.299999  39.310001  39.310001  39.310001
5168  2021-09-23  39.400002  39.849998  38.750000  39.250000  39.250000
5169  2021-09-24  39.400002  39.040001  39.040001  39.040001  39.040001

      Volume
0      11550
1       7950
2       1800
3          0
4       1050
...      ...
5165   11600
5166    7700
5167    2300
5168    2300
5169     195

[5170 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-07
           ...
5165    2021-09-20
5166    2021-09-21
5167    2021-09-22
5168    2021-09-23
5169    2021-09-24
Name: Date, Length: 5170, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AIRT_ended_2021-09-25  1999-12-31         39.04   0.94  43.05       4.211

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.151     9.362    13.573    17.784    21.995    26.206    30.417

  markup_80 markup_90 markup_100
0    34.628    38.839      43.05
                   stock  start_date current_price minall maxall each_markup  \
0  AIRT_ended_2021-09-25  1999-12-31         39.04   0.94  43.05       4.211

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.151     9.362    13.573    17.784    21.995    26.206    30.417

  markup_80 markup_90 markup_100
0    34.628    38.839      43.05
./ticker_data/ticker_data_2021-09-25 - Copy/AKAM_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31  334.000000  344.875000  320.000000  327.625000  327.625000
1     2000-01-03  344.187500  345.500000  311.000000  321.250000  321.250000
2     2000-01-04  320.000000  321.500000  300.000000  300.000000  300.000000
3     2000-01-05  282.500000  299.625000  262.000000  283.500000  283.500000
4     2000-01-06  272.000000  278.125000  235.250000  236.125000  236.125000
...          ...         ...         ...         ...         ...         ...
5449  2021-08-30  112.750000  113.599998  112.190002  113.019997  113.019997
5450  2021-08-31  113.199997  113.550003  112.290001  113.250000  113.250000
5451  2021-09-01  113.839996  114.269997  112.769997  113.389999  113.389999
5452  2021-09-02  113.690002  114.300003  112.790001  112.940002  112.940002
5453  2021-09-03  112.669998  114.779999  112.639999  113.800003  113.800003

         Volume
0        237400
1        285600
2        215900
3       1183500
4        797500
...         ...
5449  116080000
5450  182630000
5451  114540000
5452   66610000
5453   91070000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AKAM_ended_2021-09-25  1999-12-31         113.8   0.56  345.5      34.494

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    35.054    69.548   104.042   138.536    173.03   207.524   242.018

  markup_80 markup_90 markup_100
0   276.512   311.006      345.5
                   stock  start_date current_price minall maxall each_markup  \
0  AKAM_ended_2021-09-25  1999-12-31         113.8   0.56  345.5      34.494

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    35.054    69.548   104.042   138.536    173.03   207.524   242.018

  markup_80 markup_90 markup_100
0   276.512   311.006      345.5
./ticker_data/ticker_data_2021-09-25 - Copy/AKBA_ended_2021-09-25.csv
            Date       Open    High        Low      Close  Adj Close  \
0     2014-03-20  22.900000  28.500  20.620001  26.695000  26.695000
1     2014-03-21  25.520000  28.195  22.500000  23.700001  23.700001
2     2014-03-24  25.000000  25.000  20.010000  20.200001  20.200001
3     2014-03-25  20.219999  20.500  18.959999  20.000000  20.000000
4     2014-03-26  19.940001  20.000  18.750000  18.959999  18.959999
...          ...        ...     ...        ...        ...        ...
1875  2021-08-30   2.790000   2.900   2.781000   2.820000   2.820000
1876  2021-08-31   2.830000   2.990   2.820000   2.940000   2.940000
1877  2021-09-01   2.920000   3.070   2.920000   3.050000   3.050000
1878  2021-09-02   3.060000   3.150   3.010000   3.140000   3.140000
1879  2021-09-03   3.090000   3.100   2.950000   3.030000   3.030000

         Volume
0       4677300
1        440400
2        448100
3        219900
4        128900
...         ...
1875  199150000
1876  245600000
1877  275700000
1878  314100000
1879  275640000

[1880 rows x 7 columns]
tolistdate: 0       2014-03-20
1       2014-03-21
2       2014-03-24
3       2014-03-25
4       2014-03-26
           ...
1875    2021-08-30
1876    2021-08-31
1877    2021-09-01
1878    2021-09-02
1879    2021-09-03
Name: Date, Length: 1880, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AKBA_ended_2021-09-25  2014-03-20          3.03   2.09     31       2.891

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.981     7.872    10.763    13.654    16.545    19.436    22.327

  markup_80 markup_90 markup_100
0    25.218    28.109         31
                   stock  start_date current_price minall maxall each_markup  \
0  AKBA_ended_2021-09-25  2014-03-20          3.03   2.09     31       2.891

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.981     7.872    10.763    13.654    16.545    19.436    22.327

  markup_80 markup_90 markup_100
0    25.218    28.109         31
./ticker_data/ticker_data_2021-09-25 - Copy/AKICU_ended_2021-09-25.csv
           Date   Open    High    Low   Close  Adj Close   Volume
0    2021-01-06  10.40  10.500  10.35  10.400     10.400  3972400
1    2021-01-07  10.45  10.730  10.41  10.530     10.530  1520000
2    2021-01-08  10.74  10.746  10.59  10.592     10.592   159600
3    2021-01-11  10.60  10.779  10.53  10.770     10.770   142200
4    2021-01-12  10.89  10.890  10.70  10.728     10.728   107500
..          ...    ...     ...    ...     ...        ...      ...
151  2021-08-30   9.84   9.840   9.82   9.840      9.840  2070000
152  2021-08-31   9.84   9.840   9.84   9.840      9.840  3400000
153  2021-09-01   9.88   9.900   9.88   9.900      9.900   620000
154  2021-09-02   9.90   9.920   9.90   9.920      9.920  1150000
155  2021-09-03   9.86   9.930   9.86   9.930      9.930   180000

[156 rows x 7 columns]
tolistdate: 0      2021-01-06
1      2021-01-07
2      2021-01-08
3      2021-01-11
4      2021-01-12
          ...
151    2021-08-30
152    2021-08-31
153    2021-09-01
154    2021-09-02
155    2021-09-03
Name: Date, Length: 156, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AKICU_ended_2021-09-25  2021-01-06          9.93   9.75  10.99       0.124

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.874     9.998    10.122    10.246     10.37    10.494    10.618

  markup_80 markup_90 markup_100
0    10.742    10.866      10.99
                    stock  start_date current_price minall maxall each_markup  \
0  AKICU_ended_2021-09-25  2021-01-06          9.93   9.75  10.99       0.124

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.874     9.998    10.122    10.246     10.37    10.494    10.618

  markup_80 markup_90 markup_100
0    10.742    10.866      10.99
./ticker_data/ticker_data_2021-09-25 - Copy/AKIC_ended_2021-09-25.csv
           Date    Open   High    Low  Close  Adj Close  Volume
0    2021-02-26  10.060  10.06   9.95   9.97       9.97   57000
1    2021-03-01  10.000  10.10   9.94   9.98       9.98  119400
2    2021-03-02   9.940  10.88   9.93  10.88      10.88  100300
3    2021-03-03  10.200  10.20  10.00  10.09      10.09   20700
4    2021-03-04  10.020  10.02   9.80   9.88       9.88   16700
..          ...     ...    ...    ...    ...        ...     ...
128  2021-09-13   9.730   9.73   9.73   9.73       9.73     600
129  2021-09-14   9.690   9.69   9.69   9.69       9.69    1600
130  2021-09-15   9.720   9.72   9.70   9.71       9.71    1800
131  2021-09-16   9.725   9.73   9.72   9.73       9.73    2400
132  2021-09-23   9.730   9.73   9.73   9.73       9.73    2900

[133 rows x 7 columns]
tolistdate: 0      2021-02-26
1      2021-03-01
2      2021-03-02
3      2021-03-03
4      2021-03-04
          ...
128    2021-09-13
129    2021-09-14
130    2021-09-15
131    2021-09-16
132    2021-09-23
Name: Date, Length: 133, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AKIC_ended_2021-09-25  2021-02-26          9.73   9.55  10.88       0.133

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.683     9.816     9.949    10.082    10.215    10.348    10.481

  markup_80 markup_90 markup_100
0    10.614    10.747      10.88
                   stock  start_date current_price minall maxall each_markup  \
0  AKIC_ended_2021-09-25  2021-02-26          9.73   9.55  10.88       0.133

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.683     9.816     9.949    10.082    10.215    10.348    10.481

  markup_80 markup_90 markup_100
0    10.614    10.747      10.88

./ticker_data/ticker_data_2021-09-25 - Copy/AKRO_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-06-20  16.160000  21.940001  16.059999  18.320000  18.320000
1    2019-06-21  17.580000  19.700001  16.860001  19.700001  19.700001
2    2019-06-24  19.740000  20.830000  18.702999  19.040001  19.040001
3    2019-06-25  19.110001  19.110001  17.417000  18.080000  18.080000
4    2019-06-26  18.340000  20.129999  17.407000  19.830000  19.830000
..          ...        ...        ...        ...        ...        ...
553  2021-08-30  23.129999  23.760000  23.000000  23.090000  23.090000
554  2021-08-31  23.260000  23.750000  23.260000  23.740000  23.740000
555  2021-09-01  23.365000  24.250000  23.365000  24.180000  24.180000
556  2021-09-02  24.480000  24.480000  23.510000  23.990000  23.990000
557  2021-09-03  23.770000  24.155001  23.180000  23.709999  23.709999

       Volume
0     2983300
1      304400
2      296400
3      201900
4      138600
..        ...
553  16610000
554   9500000
555  14550000
556  13600000
557  12780000

[558 rows x 7 columns]
tolistdate: 0      2019-06-20
1      2019-06-21
2      2019-06-24
3      2019-06-25
4      2019-06-26
          ...
553    2021-08-30
554    2021-08-31
555    2021-09-01
556    2021-09-02
557    2021-09-03
Name: Date, Length: 558, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AKRO_ended_2021-09-25  2019-06-20         23.71  10.78  41.16       3.038

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.818    16.856    19.894    22.932     25.97    29.008    32.046

  markup_80 markup_90 markup_100
0    35.084    38.122      41.16
                   stock  start_date current_price minall maxall each_markup  \
0  AKRO_ended_2021-09-25  2019-06-20         23.71  10.78  41.16       3.038

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.818    16.856    19.894    22.932     25.97    29.008    32.046

  markup_80 markup_90 markup_100
0    35.084    38.122      41.16
./ticker_data/ticker_data_2021-09-25 - Copy/AKTS_ended_2021-09-25.csv
            Date   Open   High     Low  Close  Adj Close     Volume
0     2015-06-04   4.00   5.00   4.000   4.99       4.99       9000
1     2015-06-05   9.99  10.02   6.500   6.50       6.50       6600
2     2015-06-08   6.00   6.00   6.000   6.00       6.00       1100
3     2015-06-09   6.00   6.00   6.000   6.00       6.00          0
4     2015-06-11   5.99   5.99   5.990   5.99       5.99        300
...          ...    ...    ...     ...    ...        ...        ...
1500  2021-08-30  10.00  10.04   8.730   9.12       9.12  160030000
1501  2021-08-31   9.01   9.94   8.945   9.92       9.92   79100000
1502  2021-09-01   9.91  10.10   9.825  10.04      10.04   54700000
1503  2021-09-02  10.09  10.20   9.850  10.13      10.13   62850000
1504  2021-09-03  10.18  10.53  10.150  10.36      10.36   60920000

[1505 rows x 7 columns]
tolistdate: 0       2015-06-04
1       2015-06-05
2       2015-06-08
3       2015-06-09
4       2015-06-11
           ...
1500    2021-08-30
1501    2021-08-31
1502    2021-09-01
1503    2021-09-02
1504    2021-09-03
Name: Date, Length: 1505, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AKTS_ended_2021-09-25  2015-06-04         10.36   1.51  19.15       1.764

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.274     5.038     6.802     8.566     10.33    12.094    13.858

  markup_80 markup_90 markup_100
0    15.622    17.386      19.15
                   stock  start_date current_price minall maxall each_markup  \
0  AKTS_ended_2021-09-25  2015-06-04         10.36   1.51  19.15       1.764

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.274     5.038     6.802     8.566     10.33    12.094    13.858

  markup_80 markup_90 markup_100
0    15.622    17.386      19.15
./ticker_data/ticker_data_2021-09-25 - Copy/AKTX_ended_2021-09-25.csv
            Date       Open        High    Low  Close  Adj Close    Volume
0     2014-01-06  80.000000   80.000000  80.00  80.00      80.00         0
1     2014-01-07  95.000000   95.000000  95.00  95.00      95.00         0
2     2014-01-08  92.500000   95.000000  92.50  95.00      95.00         0
3     2014-01-10  95.000000  100.000000  95.00  98.50      98.50      1100
4     2014-01-13  98.599998   98.599998  98.00  98.00      98.00       200
...          ...        ...         ...    ...    ...        ...       ...
1892  2021-08-30   1.870000    1.870000   1.72   1.73       1.73  18390000
1893  2021-08-31   1.770000    1.870000   1.73   1.84       1.84  23390000
1894  2021-09-01   1.880000    1.880000   1.81   1.87       1.87  19920000
1895  2021-09-02   1.850000    1.870000   1.78   1.82       1.82  10440000
1896  2021-09-03   1.850000    1.860000   1.79   1.85       1.85   8370000

[1897 rows x 7 columns]
tolistdate: 0       2014-01-06
1       2014-01-07
2       2014-01-08
3       2014-01-10
4       2014-01-13
           ...
1892    2021-08-30
1893    2021-08-31
1894    2021-09-01
1895    2021-09-02
1896    2021-09-03
Name: Date, Length: 1897, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AKTX_ended_2021-09-25  2014-01-06          1.85   0.87    119      11.813

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.683    24.496    36.309    48.122    59.935    71.748    83.561

  markup_80 markup_90 markup_100
0    95.374   107.187        119
                   stock  start_date current_price minall maxall each_markup  \
0  AKTX_ended_2021-09-25  2014-01-06          1.85   0.87    119      11.813

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.683    24.496    36.309    48.122    59.935    71.748    83.561

  markup_80 markup_90 markup_100
0    95.374   107.187        119
./ticker_data/ticker_data_2021-09-25 - Copy/AKUS_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-06-26  22.260000  24.080000  19.719999  22.000000  22.000000
1    2020-06-29  23.478001  23.990000  21.520000  22.370001  22.370001
2    2020-06-30  22.100000  23.650000  22.100000  22.500000  22.500000
3    2020-07-01  23.200001  23.209999  21.299999  21.830000  21.830000
4    2020-07-02  22.280001  22.280001  21.150000  21.150000  21.150000
..          ...        ...        ...        ...        ...        ...
295  2021-08-30  11.070000  11.070000  10.620000  10.800000  10.800000
296  2021-08-31  10.780000  11.890000  10.780000  11.890000  11.890000
297  2021-09-01  11.980000  12.680000  11.910000  12.480000  12.480000
298  2021-09-02  12.490000  12.890000  12.420000  12.700000  12.700000
299  2021-09-03  12.770000  12.990000  12.270000  12.270000  12.270000

       Volume
0     2695300
1      973800
2      279000
3     1107600
4      390000
..        ...
295   9420000
296  18800000
297  13760000
298   7580000
299   6500000

[300 rows x 7 columns]
tolistdate: 0      2020-06-26
1      2020-06-29
2      2020-06-30
3      2020-07-01
4      2020-07-02
          ...
295    2021-08-30
296    2021-08-31
297    2021-09-01
298    2021-09-02
299    2021-09-03
Name: Date, Length: 300, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AKUS_ended_2021-09-25  2020-06-26         12.27   9.86  30.67       2.081

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.941    14.022    16.103    18.184    20.265    22.346    24.427

  markup_80 markup_90 markup_100
0    26.508    28.589      30.67
                   stock  start_date current_price minall maxall each_markup  \
0  AKUS_ended_2021-09-25  2020-06-26         12.27   9.86  30.67       2.081

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.941    14.022    16.103    18.184    20.265    22.346    24.427

  markup_80 markup_90 markup_100
0    26.508    28.589      30.67
./ticker_data/ticker_data_2021-09-25 - Copy/AKU_ended_2021-09-25.csv
           Date  Open   High   Low  Close  Adj Close    Volume
0    2020-09-03  3.47  3.470  2.90   3.00       3.00     13300
1    2020-09-04  3.00  3.060  2.75   3.02       3.02     12800
2    2020-09-08  2.70  3.000  2.70   2.90       2.90      9200
3    2020-09-09  2.86  3.000  2.86   2.99       2.99      8500
4    2020-09-10  2.96  3.026  2.90   2.90       2.90     16200
..          ...   ...    ...   ...    ...        ...       ...
247  2021-08-30  2.42  2.420  2.23   2.26       2.26   9640000
248  2021-08-31  2.27  2.270  2.15   2.17       2.17   6040000
249  2021-09-01  2.20  2.640  2.15   2.52       2.52  19240000
250  2021-09-02  2.68  2.780  2.41   2.51       2.51  37650000
251  2021-09-03  2.44  2.500  2.34   2.44       2.44   7540000

[252 rows x 7 columns]
tolistdate: 0      2020-09-03
1      2020-09-04
2      2020-09-08
3      2020-09-09
4      2020-09-10
          ...
247    2021-08-30
248    2021-08-31
249    2021-09-01
250    2021-09-02
251    2021-09-03
Name: Date, Length: 252, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  AKU_ended_2021-09-25  2020-09-03          2.44    2.1    4.1         0.2

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0       2.3       2.5       2.7       2.9       3.1       3.3       3.5

  markup_80 markup_90 markup_100
0       3.7       3.9        4.1
                  stock  start_date current_price minall maxall each_markup  \
0  AKU_ended_2021-09-25  2020-09-03          2.44    2.1    4.1         0.2

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0       2.3       2.5       2.7       2.9       3.1       3.3       3.5

  markup_80 markup_90 markup_100
0       3.7       3.9        4.1
./ticker_data/ticker_data_2021-09-25 - Copy/AKYA_ended_2021-09-25.csv
          Date       Open       High        Low      Close  Adj Close   Volume
0   2021-04-16  26.000000  28.955999  24.000000  26.049999  26.049999  3804000
1   2021-04-19  24.600000  25.225000  22.600000  22.969999  22.969999   578300
2   2021-04-20  22.309999  24.440001  22.160000  23.120001  23.120001   234200
3   2021-04-21  23.570000  24.670000  22.650000  23.969999  23.969999   229800
4   2021-04-22  23.299999  23.780001  22.650000  22.950001  22.950001    86300
..         ...        ...        ...        ...        ...        ...      ...
93  2021-08-30  16.709999  16.879999  16.200001  16.590000  16.590000  1960000
94  2021-08-31  16.520000  17.040001  15.840000  15.970000  15.970000  2560000
95  2021-09-01  15.920000  15.920000  15.220000  15.460000  15.460000  3650000
96  2021-09-02  15.460000  16.459999  15.240000  16.160000  16.160000  4210000
97  2021-09-03  16.139999  16.139999  15.590000  15.680000  15.680000  3200000

[98 rows x 7 columns]
tolistdate: 0     2021-04-16
1     2021-04-19
2     2021-04-20
3     2021-04-21
4     2021-04-22
         ...
93    2021-08-30
94    2021-08-31
95    2021-09-01
96    2021-09-02
97    2021-09-03
Name: Date, Length: 98, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AKYA_ended_2021-09-25  2021-04-16         15.68  14.13  28.956      1.4826

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   15.6126   17.0952   18.5778   20.0604    21.543   23.0256   24.5082

  markup_80 markup_90 markup_100
0   25.9908   27.4734     28.956
                   stock  start_date current_price minall  maxall each_markup  \
0  AKYA_ended_2021-09-25  2021-04-16         15.68  14.13  28.956      1.4826

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   15.6126   17.0952   18.5778   20.0604    21.543   23.0256   24.5082

  markup_80 markup_90 markup_100
0   25.9908   27.4734     28.956
./ticker_data/ticker_data_2021-09-25 - Copy/ALACR_ended_2021-09-25.csv
          Date   Open   High    Low  Close  Adj Close  Volume
0   2012-03-08  2.950  2.950  2.950  2.950      2.950      25
1   2012-03-09  2.950  2.950  2.950  2.950      2.950       0
2   2012-03-30  2.950  2.950  2.950  2.950      2.950     100
3   2012-12-21  2.900  2.900  2.900  2.900      2.900     462
4   2012-12-24  2.900  2.900  2.900  2.900      2.900       0
..         ...    ...    ...    ...    ...        ...     ...
94  2015-09-18  0.510  0.510  0.510  0.510      0.510       0
95  2015-12-09  0.230  0.230  0.230  0.230      0.230    9001
96  2016-01-11  0.250  0.250  0.250  0.250      0.250       0
97  2016-04-18  1.030  1.030  1.030  1.030      1.030    2862
98  2021-09-24  0.455  0.485  0.455  0.485      0.485    1401

[99 rows x 7 columns]
tolistdate: 0     2012-03-08
1     2012-03-09
2     2012-03-30
3     2012-12-21
4     2012-12-24
         ...
94    2015-09-18
95    2015-12-09
96    2016-01-11
97    2016-04-18
98    2021-09-24
Name: Date, Length: 99, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ALACR_ended_2021-09-25  2012-03-08         0.485   0.23      3       0.277

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.507     0.784     1.061     1.338     1.615     1.892     2.169

  markup_80 markup_90 markup_100
0     2.446     2.723          3
                    stock  start_date current_price minall maxall each_markup  \
0  ALACR_ended_2021-09-25  2012-03-08         0.485   0.23      3       0.277

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.507     0.784     1.061     1.338     1.615     1.892     2.169

  markup_80 markup_90 markup_100
0     2.446     2.723          3
./ticker_data/ticker_data_2021-09-25 - Copy/ALACW_ended_2021-09-25.csv
         Date    Open   High   Low  Close  Adj Close  Volume
0  2021-09-22  0.2747  0.329  0.32  0.329      0.329   17384
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ALACW_ended_2021-09-25  2021-09-22         0.329   0.32  0.329      0.0009

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    0.3209    0.3218    0.3227    0.3236    0.3245    0.3254    0.3263

  markup_80 markup_90 markup_100
0    0.3272    0.3281      0.329
                    stock  start_date current_price minall maxall each_markup  \
0  ALACW_ended_2021-09-25  2021-09-22         0.329   0.32  0.329      0.0009

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    0.3209    0.3218    0.3227    0.3236    0.3245    0.3254    0.3263

  markup_80 markup_90 markup_100
0    0.3272    0.3281      0.329
./ticker_data/ticker_data_2021-09-25 - Copy/ALAC_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close   Volume
0    2018-11-21   9.68   9.72   9.65   9.67       9.67  1261800
1    2018-11-23   9.68   9.68   9.68   9.68       9.68    15000
2    2018-11-26   9.75   9.78   9.68   9.78       9.78     5800
3    2018-11-27   9.70   9.73   9.70   9.73       9.73    26100
4    2018-11-28   9.73   9.73   9.73   9.73       9.73      100
..          ...    ...    ...    ...    ...        ...      ...
552  2021-08-30  11.28  11.28  11.27  11.28      11.28   750000
553  2021-08-31  11.28  11.28  11.24  11.24      11.24   840000
554  2021-09-01  11.23  11.25  11.23  11.25      11.25   280000
555  2021-09-02  11.23  11.29  11.23  11.23      11.23   490000
556  2021-09-03  11.24  11.30  11.23  11.30      11.30  1100000

[557 rows x 7 columns]
tolistdate: 0      2018-11-21
1      2018-11-23
2      2018-11-26
3      2018-11-27
4      2018-11-28
          ...
552    2021-08-30
553    2021-08-31
554    2021-09-01
555    2021-09-02
556    2021-09-03
Name: Date, Length: 557, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALAC_ended_2021-09-25  2018-11-21          11.3   9.65  16.25        0.66

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     10.31     10.97     11.63     12.29     12.95     13.61     14.27

  markup_80 markup_90 markup_100
0     14.93     15.59      16.25
                   stock  start_date current_price minall maxall each_markup  \
0  ALAC_ended_2021-09-25  2018-11-21          11.3   9.65  16.25        0.66

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     10.31     10.97     11.63     12.29     12.95     13.61     14.27

  markup_80 markup_90 markup_100
0     14.93     15.59      16.25
./ticker_data/ticker_data_2021-09-25 - Copy/ALBO_ended_2021-09-25.csv
            Date         Open         High          Low        Close  \
0     2007-05-11  1980.000000  2208.000000  1951.199951  2160.000000
1     2007-05-14  2160.000000  2216.399902  2145.600098  2187.600098
2     2007-05-15  2138.399902  2176.800049  2113.199951  2146.800049
3     2007-05-16  2130.000000  2180.399902  2061.600098  2164.800049
4     2007-05-17  2164.800049  2209.199951  2139.600098  2142.000000
...          ...          ...          ...          ...          ...
3615  2021-09-20    30.680000    31.209999    30.090000    30.379999
3616  2021-09-21    30.660000    31.809999    30.480000    31.590000
3617  2021-09-22    31.770000    32.099998    31.370001    31.760000
3618  2021-09-23    31.900000    33.000000    31.850000    32.720001
3619  2021-09-24    32.450001    32.634998    31.150000    31.280001

        Adj Close  Volume
0     2160.000000   19459
1     2187.600098    1373
2     2146.800049    1046
3     2164.800049    1833
4     2142.000000     268
...           ...     ...
3615    30.379999  247100
3616    31.590000  233900
3617    31.760000  104600
3618    32.720001  237200
3619    31.280001   84617

[3620 rows x 7 columns]
tolistdate: 0       2007-05-11
1       2007-05-14
2       2007-05-15
3       2007-05-16
4       2007-05-17
           ...
3615    2021-09-20
3616    2021-09-21
3617    2021-09-22
3618    2021-09-23
3619    2021-09-24
Name: Date, Length: 3620, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ALBO_ended_2021-09-25  2007-05-11         31.28    6.6  3082.8      307.62

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    314.22    621.84    929.46   1237.08    1544.7   1852.32   2159.94

  markup_80 markup_90 markup_100

0   2467.56   2775.18     3082.8
                   stock  start_date current_price minall  maxall each_markup  \
0  ALBO_ended_2021-09-25  2007-05-11         31.28    6.6  3082.8      307.62

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    314.22    621.84    929.46   1237.08    1544.7   1852.32   2159.94

  markup_80 markup_90 markup_100
0   2467.56   2775.18     3082.8
./ticker_data/ticker_data_2021-09-25 - Copy/ALCO_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  16.750000  16.750000  16.750000  16.750000  11.692787
1     2000-01-03  16.875000  16.875000  16.375000  16.375000  11.431012
2     2000-01-04  15.875000  15.875000  15.875000  15.875000  11.081966
3     2000-01-05  15.875000  15.875000  15.437500  15.437500  10.776564
4     2000-01-06  16.250000  16.250000  16.250000  16.250000  11.343748
...          ...        ...        ...        ...        ...        ...
5421  2021-08-30  37.880001  37.980000  37.369999  37.650002  37.650002
5422  2021-08-31  37.759998  38.220001  37.090000  37.330002  37.330002
5423  2021-09-01  37.450001  37.450001  36.520000  36.709999  36.709999
5424  2021-09-02  36.869999  37.250000  36.290001  36.950001  36.950001
5425  2021-09-03  37.000000  37.009998  36.270000  36.410000  36.410000

       Volume
0         100
1         600
2         100
3         400
4        1400
...       ...
5421  2180000
5422  2320000
5423  1920000
5424   940000
5425  1700000

[5426 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5421    2021-08-30
5422    2021-08-31
5423    2021-09-01
5424    2021-09-02
5425    2021-09-03
Name: Date, Length: 5426, dtype: object
                   stock  start_date current_price   minall maxall  \
0  ALCO_ended_2021-09-25  1999-12-31         36.41  14.8281     65

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     5.01719   19.8453   24.8625   29.8797   34.8969   39.9141   44.9312

  markup_70 markup_80 markup_90 markup_100
0   49.9484   54.9656   59.9828         65
                   stock  start_date current_price   minall maxall  \
0  ALCO_ended_2021-09-25  1999-12-31         36.41  14.8281     65

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     5.01719   19.8453   24.8625   29.8797   34.8969   39.9141   44.9312

  markup_70 markup_80 markup_90 markup_100
0   49.9484   54.9656   59.9828         65
./ticker_data/ticker_data_2021-09-25 - Copy/ALDX_ended_2021-09-25.csv
            Date  Open  High   Low  Close  Adj Close    Volume
0     2014-05-02  7.50  7.69  6.01   7.20       7.20    579900
1     2014-05-05  6.80  7.00  6.30   6.70       6.70     41100
2     2014-05-06  6.65  6.85  6.10   6.10       6.10     24900
3     2014-05-07  6.12  6.24  6.05   6.05       6.05     12700
4     2014-05-08  6.50  6.99  6.49   6.99       6.99     24200
...          ...   ...   ...   ...    ...        ...       ...
1844  2021-08-30  9.11  9.16  8.81   9.13       9.13  39050000
1845  2021-08-31  9.15  9.58  9.14   9.49       9.49  38200000
1846  2021-09-01  9.42  9.63  9.35   9.51       9.51  28780000
1847  2021-09-02  9.56  9.81  9.43   9.50       9.50  49830000
1848  2021-09-03  9.39  9.49  9.02   9.22       9.22  41220000

[1849 rows x 7 columns]
tolistdate: 0       2014-05-02
1       2014-05-05
2       2014-05-06
3       2014-05-07
4       2014-05-08
           ...
1844    2021-08-30
1845    2021-08-31
1846    2021-09-01
1847    2021-09-02
1848    2021-09-03
Name: Date, Length: 1849, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALDX_ended_2021-09-25  2014-05-02          9.22   1.48   16.7       1.522

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.002     4.524     6.046     7.568      9.09    10.612    12.134

  markup_80 markup_90 markup_100
0    13.656    15.178       16.7
                   stock  start_date current_price minall maxall each_markup  \
0  ALDX_ended_2021-09-25  2014-05-02          9.22   1.48   16.7       1.522

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.002     4.524     6.046     7.568      9.09    10.612    12.134

  markup_80 markup_90 markup_100
0    13.656    15.178       16.7
./ticker_data/ticker_data_2021-09-25 - Copy/ALEC_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-02-07  18.700001  19.500000  18.000000  18.080000  18.080000
1    2019-02-08  17.719999  17.799999  15.554000  16.299999  16.299999
2    2019-02-11  16.230000  17.500000  16.160000  17.180000  17.180000
3    2019-02-12  17.200001  17.900000  17.200001  17.500000  17.500000
4    2019-02-13  17.500000  19.000000  17.500000  18.250000  18.250000
..          ...        ...        ...        ...        ...        ...
644  2021-08-30  27.129999  27.700001  26.180000  26.270000  26.270000
645  2021-08-31  26.150000  27.170000  26.059999  27.030001  27.030001
646  2021-09-01  27.290001  27.490000  26.430000  27.170000  27.170000
647  2021-09-02  26.730000  29.299999  26.670000  27.889999  27.889999
648  2021-09-03  28.000000  28.700001  26.410000  26.639999  26.639999

        Volume
0      3626100
1      1094100
2       538600
3       299500
4       957300
..         ...
644   44010000
645   83380000
646   63210000
647  104740000
648   57820000

[649 rows x 7 columns]
tolistdate: 0      2019-02-07
1      2019-02-08
2      2019-02-11
3      2019-02-12
4      2019-02-13
          ...
644    2021-08-30
645    2021-08-31
646    2021-09-01
647    2021-09-02
648    2021-09-03
Name: Date, Length: 649, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALEC_ended_2021-09-25  2019-02-07         26.64   9.12  43.32        3.42

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     12.54     15.96     19.38      22.8     26.22     29.64     33.06

  markup_80 markup_90 markup_100
0     36.48      39.9      43.32
                   stock  start_date current_price minall maxall each_markup  \
0  ALEC_ended_2021-09-25  2019-02-07         26.64   9.12  43.32        3.42

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     12.54     15.96     19.38      22.8     26.22     29.64     33.06

  markup_80 markup_90 markup_100
0     36.48      39.9      43.32
./ticker_data/ticker_data_2021-09-25 - Copy/ALFIW_ended_2021-09-25.csv
         Date  Open  High  Low  Close  Adj Close  Volume
0  2021-09-24   0.0  3.63  3.4   3.58       3.58    4391
tolistdate: 0    2021-09-24
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ALFIW_ended_2021-09-25  2021-09-24          3.58    3.4   3.63       0.023

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.423     3.446     3.469     3.492     3.515     3.538     3.561

  markup_80 markup_90 markup_100
0     3.584     3.607       3.63
                    stock  start_date current_price minall maxall each_markup  \
0  ALFIW_ended_2021-09-25  2021-09-24          3.58    3.4   3.63       0.023

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.423     3.446     3.469     3.492     3.515     3.538     3.561

  markup_80 markup_90 markup_100
0     3.584     3.607       3.63
./ticker_data/ticker_data_2021-09-25 - Copy/ALF_ended_2021-09-25.csv
          Date  Open  High    Low  Close  Adj Close     Volume
0   2021-05-04  3.75  3.91  2.410   2.90       2.90    4573100
1   2021-05-05  3.10  3.73  2.960   3.58       3.58    3752000
2   2021-05-06  5.22  5.60  3.400   3.61       3.61   41259200
3   2021-05-07  3.22  3.79  2.875   3.70       3.70    8957500
4   2021-05-10  4.88  4.91  3.860   4.57       4.57   23111300
..         ...   ...   ...    ...    ...        ...        ...
82  2021-08-30  8.43  8.97  8.010   8.83       8.83  136450000
83  2021-08-31  8.80  9.25  8.410   8.90       8.90  186430000
84  2021-09-01  8.91  9.44  8.680   8.71       8.71  128220000
85  2021-09-02  8.82  9.24  8.190   8.60       8.60  257010000
86  2021-09-03  8.60  8.74  8.050   8.21       8.21   71560000

[87 rows x 7 columns]
tolistdate: 0     2021-05-04
1     2021-05-05
2     2021-05-06
3     2021-05-07
4     2021-05-10
         ...
82    2021-08-30
83    2021-08-31
84    2021-09-01
85    2021-09-02
86    2021-09-03
Name: Date, Length: 87, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  ALF_ended_2021-09-25  2021-05-04          8.21   2.41   22.5       2.009

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.419     6.428     8.437    10.446    12.455    14.464    16.473

  markup_80 markup_90 markup_100
0    18.482    20.491       22.5
                  stock  start_date current_price minall maxall each_markup  \
0  ALF_ended_2021-09-25  2021-05-04          8.21   2.41   22.5       2.009

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.419     6.428     8.437    10.446    12.455    14.464    16.473

  markup_80 markup_90 markup_100
0    18.482    20.491       22.5
./ticker_data/ticker_data_2021-09-25 - Copy/ALGM_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-10-29  19.400000  19.740000  17.020000  17.700001  17.700001
1    2020-10-30  17.490000  18.725000  16.780001  18.299999  18.299999
2    2020-11-02  18.299999  19.799999  17.915001  19.750000  19.750000
3    2020-11-03  19.750000  21.430000  19.500000  21.000000  21.000000
4    2020-11-04  21.110001  22.510000  20.600000  21.000000  21.000000
..          ...        ...        ...        ...        ...        ...
208  2021-08-30  30.400000  30.870001  29.930000  30.530001  30.530001
209  2021-08-31  30.270000  30.400000  29.671000  30.049999  30.049999
210  2021-09-01  30.000000  30.650000  29.719999  30.160000  30.160000
211  2021-09-02  30.180000  30.770000  29.990000  30.690001  30.690001
212  2021-09-03  30.690001  31.480000  30.580000  31.049999  31.049999

        Volume
0     11098400
1      2008600
2      1640600
3      2075400
4      6056400
..         ...
208   85290000
209  117100000
210   62300000
211   49190000
212   66590000

[213 rows x 7 columns]
tolistdate: 0      2020-10-29
1      2020-10-30
2      2020-11-02
3      2020-11-03
4      2020-11-04
          ...
208    2021-08-30
209    2021-08-31
210    2021-09-01
211    2021-09-02
212    2021-09-03
Name: Date, Length: 213, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALGM_ended_2021-09-25  2020-10-29         31.05  16.78  34.66       1.788

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    18.568    20.356    22.144    23.932     25.72    27.508    29.296

  markup_80 markup_90 markup_100
0    31.084    32.872      34.66
                   stock  start_date current_price minall maxall each_markup  \
0  ALGM_ended_2021-09-25  2020-10-29         31.05  16.78  34.66       1.788

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    18.568    20.356    22.144    23.932     25.72    27.508    29.296

  markup_80 markup_90 markup_100
0    31.084    32.872      34.66
./ticker_data/ticker_data_2021-09-25 - Copy/ALGN_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2001-01-30   18.125000   18.187500   16.250000   16.875000   16.875000
1     2001-01-31   17.125000   17.187500   13.437500   13.500000   13.500000
2     2001-02-01   13.125000   14.375000   13.000000   14.187500   14.187500
3     2001-02-02   14.000000   14.562500   13.750000   14.125000   14.125000
4     2001-02-05   14.437500   14.500000   13.875000   14.125000   14.125000
...          ...         ...         ...         ...         ...         ...
5192  2021-09-20  708.020020  713.690002  698.030029  709.640015  709.640015
5193  2021-09-21  717.140015  721.000000  704.609985  709.150024  709.150024
5194  2021-09-22  713.309998  725.270020  701.210022  716.609985  716.609985
5195  2021-09-23  723.000000  737.450012  720.179993  727.109985  727.109985
5196  2021-09-24  718.469971  724.140015  715.289795  723.039978  723.039978

       Volume
0      812300
1     1212700
2      669100
3      775000
4      489400
...       ...
5192   684100
5193   646900
5194   447900
5195   349700
5196    77228

[5197 rows x 7 columns]
tolistdate: 0       2001-01-30
1       2001-01-31
2       2001-02-01
3       2001-02-02
4       2001-02-05
           ...
5192    2021-09-20
5193    2021-09-21
5194    2021-09-22
5195    2021-09-23
5196    2021-09-24
Name: Date, Length: 5197, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ALGN_ended_2021-09-25  2001-01-30        723.04   1.26  737.45      73.619

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    74.879   148.498   222.117   295.736   369.355   442.974   516.593

  markup_80 markup_90 markup_100
0   590.212   663.831     737.45
                   stock  start_date current_price minall  maxall each_markup  \
0  ALGN_ended_2021-09-25  2001-01-30        723.04   1.26  737.45      73.619

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    74.879   148.498   222.117   295.736   369.355   442.974   516.593

  markup_80 markup_90 markup_100
0   590.212   663.831     737.45
./ticker_data/ticker_data_2021-09-25 - Copy/ALGS_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-10-16  17.400000  17.500000  13.630000  14.850000  14.850000
1    2020-10-19  14.740000  15.000000  14.000000  14.760000  14.760000
2    2020-10-20  14.530000  14.930000  12.820000  13.200000  13.200000
3    2020-10-21  13.420000  15.000000  13.040000  14.940000  14.940000
4    2020-10-22  14.650000  15.460000  14.510000  15.070000  15.070000
..          ...        ...        ...        ...        ...        ...
218  2021-08-30  16.650000  16.900000  16.209999  16.620001  16.620001
219  2021-08-31  16.590000  17.145000  16.139999  17.049999  17.049999
220  2021-09-01  17.180000  17.450001  16.330000  16.590000  16.590000
221  2021-09-02  16.760000  17.549999  16.462999  17.080000  17.080000
222  2021-09-03  17.120001  17.500000  16.850000  17.059999  17.059999

       Volume
0     2761400
1      342400
2      645700
3      323000
4      328500
..        ...
218   6090000
219  17370000
220  49990000
221  23430000
222   6600000

[223 rows x 7 columns]
tolistdate: 0      2020-10-16
1      2020-10-19
2      2020-10-20
3      2020-10-21
4      2020-10-22
          ...
218    2021-08-30
219    2021-08-31
220    2021-09-01
221    2021-09-02
222    2021-09-03
Name: Date, Length: 223, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALGS_ended_2021-09-25  2020-10-16         17.06  12.82  37.51       2.469

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.289    17.758    20.227    22.696    25.165    27.634    30.103

  markup_80 markup_90 markup_100
0    32.572    35.041      37.51
                   stock  start_date current_price minall maxall each_markup  \
0  ALGS_ended_2021-09-25  2020-10-16         17.06  12.82  37.51       2.469

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.289    17.758    20.227    22.696    25.165    27.634    30.103

  markup_80 markup_90 markup_100
0    32.572    35.041      37.51
./ticker_data/ticker_data_2021-09-25 - Copy/ALGT_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2006-12-08   24.000000   26.250000   24.000000   25.100000   21.034210
1     2006-12-11   25.100000   27.830000   24.799999   26.299999   22.039825
2     2006-12-12   25.879999   26.950001   25.559999   26.070000   21.847084
3     2006-12-13   26.049999   27.400000   26.049999   26.850000   22.500736
4     2006-12-14   26.260000   28.700001   26.260000   27.840000   23.330378
...          ...         ...         ...         ...         ...         ...
3704  2021-08-30  192.860001  192.860001  184.179993  188.520004  188.520004
3705  2021-08-31  189.169998  193.199997  188.429993  192.440002  192.440002
3706  2021-09-01  194.130005  195.410004  191.100006  193.380005  193.380005
3707  2021-09-02  193.679993  195.679993  190.589996  193.330002  193.330002
3708  2021-09-03  192.589996  193.199997  189.470001  192.009995  192.009995

        Volume
0      5542000
1       707200
2       227000
3       330800
4       295000
...        ...
3704  14760000
3705  13220000
3706  10490000
3707   8700000
3708  11250000

[3709 rows x 7 columns]
tolistdate: 0       2006-12-08
1       2006-12-11
2       2006-12-12
3       2006-12-13
4       2006-12-14
           ...
3704    2021-08-30
3705    2021-08-31
3706    2021-09-01
3707    2021-09-02
3708    2021-09-03
Name: Date, Length: 3709, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ALGT_ended_2021-09-25  2006-12-08        192.01  15.89  271.29       25.54

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     41.43     66.97     92.51    118.05    143.59    169.13    194.67

  markup_80 markup_90 markup_100

0    220.21    245.75     271.29
                   stock  start_date current_price minall  maxall each_markup  \
0  ALGT_ended_2021-09-25  2006-12-08        192.01  15.89  271.29       25.54

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     41.43     66.97     92.51    118.05    143.59    169.13    194.67

  markup_80 markup_90 markup_100
0    220.21    245.75     271.29
./ticker_data/ticker_data_2021-09-25 - Copy/ALHC_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2021-03-26  19.049999  19.700001  16.320000  17.309999  17.309999
1    2021-03-29  17.000000  19.240000  17.000000  19.000000  19.000000
2    2021-03-30  18.750000  20.860001  18.250000  19.940001  19.940001
3    2021-03-31  20.320000  22.150000  20.000000  21.930000  21.930000
4    2021-04-01  21.500000  24.000000  20.580000  23.200001  23.200001
..          ...        ...        ...        ...        ...        ...
108  2021-08-30  18.219999  18.379999  17.889999  18.200001  18.200001
109  2021-08-31  18.160000  18.184999  17.420000  17.670000  17.670000
110  2021-09-01  17.740000  18.250000  17.139999  18.180000  18.180000
111  2021-09-02  18.375000  19.629999  18.230000  19.580000  19.580000
112  2021-09-03  19.379999  20.549999  19.379999  20.400000  20.400000

       Volume
0     5327000
1     1483200
2     1447100
3     1197400
4     3178800
..        ...
108  24360000
109  15170000
110  25310000
111  35260000
112  29200000

[113 rows x 7 columns]
tolistdate: 0      2021-03-26
1      2021-03-29
2      2021-03-30
3      2021-03-31
4      2021-04-01
          ...
108    2021-08-30
109    2021-08-31
110    2021-09-01
111    2021-09-02
112    2021-09-03
Name: Date, Length: 113, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ALHC_ended_2021-09-25  2021-03-26          20.4  16.32  28.592      1.2272

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   17.5472   18.7744   20.0016   21.2288    22.456   23.6832   24.9104

  markup_80 markup_90 markup_100
0   26.1376   27.3648     28.592
                   stock  start_date current_price minall  maxall each_markup  \
0  ALHC_ended_2021-09-25  2021-03-26          20.4  16.32  28.592      1.2272

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   17.5472   18.7744   20.0016   21.2288    22.456   23.6832   24.9104

  markup_80 markup_90 markup_100
0   26.1376   27.3648     28.592
./ticker_data/ticker_data_2021-09-25 - Copy/ALIM_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close   Volume
0    2019-11-04  4.500  4.575  4.125  4.155      4.155    34600
1    2019-11-05  4.200  4.500  4.200  4.380      4.380    19400
2    2019-11-06  4.395  4.500  4.230  4.350      4.350    21500
3    2019-11-07  4.500  4.515  4.065  4.125      4.125    12300
4    2019-11-08  3.900  4.050  3.420  3.600      3.600    62900
..          ...    ...    ...    ...    ...        ...      ...
457  2021-08-30  6.360  6.480  6.010  6.460      6.460  7970000
458  2021-08-31  6.360  6.360  5.960  5.990      5.990  5220000
459  2021-09-01  6.040  6.070  5.710  5.720      5.720  3120000
460  2021-09-02  5.740  5.920  5.640  5.820      5.820  2360000
461  2021-09-03  5.830  6.040  5.702  6.020      6.020  1660000

[462 rows x 7 columns]
tolistdate: 0      2019-11-04
1      2019-11-05
2      2019-11-06
3      2019-11-07
4      2019-11-08
          ...
457    2021-08-30
458    2021-08-31
459    2021-09-01
460    2021-09-02
461    2021-09-03
Name: Date, Length: 462, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALIM_ended_2021-09-25  2019-11-04          6.02   2.86  12.25       0.939

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.799     4.738     5.677     6.616     7.555     8.494     9.433

  markup_80 markup_90 markup_100
0    10.372    11.311      12.25
                   stock  start_date current_price minall maxall each_markup  \
0  ALIM_ended_2021-09-25  2019-11-04          6.02   2.86  12.25       0.939

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.799     4.738     5.677     6.616     7.555     8.494     9.433

  markup_80 markup_90 markup_100
0    10.372    11.311      12.25
./ticker_data/ticker_data_2021-09-25 - Copy/ALJJ_ended_2021-09-25.csv
            Date     Open      High      Low   Close  Adj Close   Volume
0     1999-12-31  27.5000  29.75000  26.9375  29.750     29.750   181600
1     2000-01-03  29.5000  30.50000  28.5000  29.000     29.000   234000
2     2000-01-04  28.9375  28.96875  27.0000  27.625     27.625   180200
3     2000-01-05  27.7500  28.00000  26.3750  27.250     27.250   182300
4     2000-01-06  27.0000  27.93750  26.2500  26.750     26.750   119100
...          ...      ...       ...      ...     ...        ...      ...
5129  2021-08-30   1.2300   1.29000   1.2200   1.260      1.260  4340000
5130  2021-08-31   1.2800   1.28000   1.2500   1.260      1.260  1090000
5131  2021-09-01   1.2800   1.28000   1.2300   1.270      1.270  3390000
5132  2021-09-02   1.2600   1.26000   1.2100   1.230      1.230  2160000
5133  2021-09-03   1.2400   1.29000   1.2300   1.250      1.250  5870000

[5134 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5129    2021-08-30
5130    2021-08-31
5131    2021-09-01
5132    2021-09-02
5133    2021-09-03
Name: Date, Length: 5134, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALJJ_ended_2021-09-25  1999-12-31          1.25   0.02   30.5       3.048

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.068     6.116     9.164    12.212     15.26    18.308    21.356

  markup_80 markup_90 markup_100
0    24.404    27.452       30.5
                   stock  start_date current_price minall maxall each_markup  \
0  ALJJ_ended_2021-09-25  1999-12-31          1.25   0.02   30.5       3.048

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.068     6.116     9.164    12.212     15.26    18.308    21.356

  markup_80 markup_90 markup_100
0    24.404    27.452       30.5
./ticker_data/ticker_data_2021-09-25 - Copy/ALKS_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  24.000000  24.562500  24.000000  24.562500  24.562500
1     2000-01-03  24.843750  25.750000  24.500000  25.500000  25.500000
2     2000-01-04  24.875000  25.250000  23.875000  24.000000  24.000000
3     2000-01-05  23.875000  24.687500  23.750000  24.687500  24.687500
4     2000-01-06  24.687500  26.875000  24.375000  25.968750  25.968750
...          ...        ...        ...        ...        ...        ...
5450  2021-08-30  31.230000  31.490000  30.959999  31.410000  31.410000
5451  2021-08-31  31.370001  31.520000  30.830000  31.260000  31.260000
5452  2021-09-01  31.350000  31.450001  30.959999  31.250000  31.250000
5453  2021-09-02  30.290001  30.799999  29.780001  30.330000  30.330000
5454  2021-09-03  30.309999  30.309999  29.700001  29.860001  29.860001

         Volume
0        132400
1       1252800
2       1325000
3        856000
4        978200
...         ...
5450   89040000
5451  113900000
5452   87630000
5453  193410000
5454  159600000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALKS_ended_2021-09-25  1999-12-31         29.86   3.55   98.5       9.495

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.045     22.54    32.035     41.53    51.025     60.52    70.015

  markup_80 markup_90 markup_100
0     79.51    89.005       98.5
                   stock  start_date current_price minall maxall each_markup  \
0  ALKS_ended_2021-09-25  1999-12-31         29.86   3.55   98.5       9.495

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.045     22.54    32.035     41.53    51.025     60.52    70.015

  markup_80 markup_90 markup_100
0     79.51    89.005       98.5
./ticker_data/ticker_data_2021-09-25 - Copy/ALKT_ended_2021-09-25.csv
          Date       Open       High        Low      Close  Adj Close  \
0   2021-04-14  41.259998  49.320000  41.049999  43.000000  43.000000
1   2021-04-15  42.650002  48.500000  41.599998  41.630001  41.630001
2   2021-04-16  42.000000  45.419998  41.270000  42.130001  42.130001
3   2021-04-19  42.740002  42.740002  40.029999  41.570000  41.570000
4   2021-04-20  41.349998  42.009998  40.099998  41.439999  41.439999
..         ...        ...        ...        ...        ...        ...
95  2021-08-30  27.860001  28.559999  27.270000  28.480000  28.480000
96  2021-08-31  28.270000  28.920000  27.709999  28.559999  28.559999
97  2021-09-01  28.610001  30.000000  28.110001  29.709999  29.709999
98  2021-09-02  30.000000  30.350000  29.400000  30.219999  30.219999
99  2021-09-03  29.950001  30.540001  29.510000  29.950001  29.950001

      Volume
0    5737400
1    1267600
2     334700
3     407200
4     337300
..       ...
95  13790000
96  10770000
97  15560000
98  13040000
99  11880000

[100 rows x 7 columns]
tolistdate: 0     2021-04-14
1     2021-04-15
2     2021-04-16
3     2021-04-19
4     2021-04-20
         ...
95    2021-08-30
96    2021-08-31
97    2021-09-01
98    2021-09-02
99    2021-09-03
Name: Date, Length: 100, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALKT_ended_2021-09-25  2021-04-14         29.95  26.12  49.32        2.32

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     28.44     30.76     33.08      35.4     37.72     40.04     42.36

  markup_80 markup_90 markup_100
0     44.68        47      49.32
                   stock  start_date current_price minall maxall each_markup  \
0  ALKT_ended_2021-09-25  2021-04-14         29.95  26.12  49.32        2.32

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     28.44     30.76     33.08      35.4     37.72     40.04     42.36

  markup_80 markup_90 markup_100
0     44.68        47      49.32
./ticker_data/ticker_data_2021-09-25 - Copy/ALLK_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-07-19  27.200001  33.240002  26.000000  31.250000  31.250000
1    2018-07-20  30.290001  37.000000  30.250000  35.049999  35.049999
2    2018-07-23  35.049999  38.529999  34.000000  36.290001  36.290001
3    2018-07-24  36.240002  38.830002  35.090000  38.119999  38.119999
4    2018-07-25  38.299999  40.139999  37.820000  39.299999  39.299999
..          ...        ...        ...        ...        ...        ...
783  2021-08-30  86.059998  89.300003  85.339996  87.089996  87.089996
784  2021-08-31  87.050003  89.330002  86.930000  89.160004  89.160004
785  2021-09-01  89.629997  91.389999  88.320000  91.250000  91.250000
786  2021-09-02  91.400002  95.480003  90.339996  94.839996  94.839996
787  2021-09-03  94.769997  97.260002  94.220001  97.089996  97.089996

       Volume
0     4438200
1      697700
2     1008700
3      293800
4      543600
..        ...
783  17970000
784  22070000
785  27280000
786  26080000
787  30410000

[788 rows x 7 columns]
tolistdate: 0      2018-07-19
1      2018-07-20
2      2018-07-23
3      2018-07-24
4      2018-07-25
          ...
783    2021-08-30
784    2021-08-31
785    2021-09-01
786    2021-09-02
787    2021-09-03
Name: Date, Length: 788, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ALLK_ended_2021-09-25  2018-07-19         97.09     26  157.98      13.198

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    39.198    52.396    65.594    78.792     91.99   105.188   118.386

  markup_80 markup_90 markup_100
0   131.584   144.782     157.98
                   stock  start_date current_price minall  maxall each_markup  \
0  ALLK_ended_2021-09-25  2018-07-19         97.09     26  157.98      13.198

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    39.198    52.396    65.594    78.792     91.99   105.188   118.386

  markup_80 markup_90 markup_100
0   131.584   144.782     157.98
./ticker_data/ticker_data_2021-09-25 - Copy/ALLO_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-10-11  22.000000  25.990000  21.670000  25.000000  25.000000
1    2018-10-12  26.900000  27.400000  25.530001  26.809999  26.809999
2    2018-10-15  27.459999  27.719999  25.549999  26.959999  26.959999
3    2018-10-16  27.040001  27.620001  25.600000  25.870001  25.870001
4    2018-10-17  26.000000  26.110001  24.160000  24.980000  24.980000
..          ...        ...        ...        ...        ...        ...
724  2021-08-30  24.410000  24.910000  24.080000  24.150000  24.150000
725  2021-08-31  24.129999  24.540001  23.670000  23.850000  23.850000
726  2021-09-01  23.760000  24.959999  23.760000  24.780001  24.780001
727  2021-09-02  25.000000  26.160000  24.780001  26.000000  26.000000
728  2021-09-03  25.760000  25.910000  25.100000  25.469999  25.469999

        Volume
0      8110200
1      2197400
2      1345600
3       939100
4      2139500
..         ...
724   86110000
725   56730000
726   58420000
727  115510000
728   62120000

[729 rows x 7 columns]
tolistdate: 0      2018-10-11
1      2018-10-12
2      2018-10-15
3      2018-10-16
4      2018-10-17
          ...
724    2021-08-30
725    2021-08-31
726    2021-09-01
727    2021-09-02
728    2021-09-03
Name: Date, Length: 729, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALLO_ended_2021-09-25  2018-10-11         25.47  17.43     55       3.757

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    21.187    24.944    28.701    32.458    36.215    39.972    43.729

  markup_80 markup_90 markup_100
0    47.486    51.243         55
                   stock  start_date current_price minall maxall each_markup  \
0  ALLO_ended_2021-09-25  2018-10-11         25.47  17.43     55       3.757

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    21.187    24.944    28.701    32.458    36.215    39.972    43.729

  markup_80 markup_90 markup_100
0    47.486    51.243         55
./ticker_data/ticker_data_2021-09-25 - Copy/ALLT_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2006-11-16  14.500000  15.530000  13.810000  13.810000  13.810000
1     2006-11-17  13.980000  13.990000  12.850000  13.000000  13.000000
2     2006-11-20  13.000000  13.010000  11.980000  12.160000  12.160000
3     2006-11-21  12.030000  12.200000  11.490000  11.610000  11.610000
4     2006-11-22  12.020000  12.480000  11.680000  12.430000  12.430000
...          ...        ...        ...        ...        ...        ...
3719  2021-08-30  16.500000  16.740000  16.299999  16.690001  16.690001
3720  2021-08-31  16.500000  16.740000  16.400000  16.620001  16.620001
3721  2021-09-01  16.730000  16.830000  16.320000  16.379999  16.379999
3722  2021-09-02  16.299999  16.330000  15.720000  15.780000  15.780000
3723  2021-09-03  15.740000  16.360001  15.640000  16.160000  16.160000

        Volume
0      5704800
1       960000
2       973800
3       950500
4       283100
...        ...
3719  16560000
3720  16560000
3721   8140000
3722  10330000
3723  12660000

[3724 rows x 7 columns]
tolistdate: 0       2006-11-16
1       2006-11-17
2       2006-11-20
3       2006-11-21
4       2006-11-22
           ...
3719    2021-08-30
3720    2021-08-31
3721    2021-09-01
3722    2021-09-02
3723    2021-09-03
Name: Date, Length: 3724, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALLT_ended_2021-09-25  2006-11-16         16.16   1.25  29.05        2.78

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      4.03      6.81      9.59     12.37     15.15     17.93     20.71

  markup_80 markup_90 markup_100
0     23.49     26.27      29.05
                   stock  start_date current_price minall maxall each_markup  \
0  ALLT_ended_2021-09-25  2006-11-16         16.16   1.25  29.05        2.78

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      4.03      6.81      9.59     12.37     15.15     17.93     20.71

  markup_80 markup_90 markup_100
0     23.49     26.27      29.05

./ticker_data/ticker_data_2021-09-25 - Copy/ALNA_ended_2021-09-25.csv
           Date    Open   High    Low  Close  Adj Close     Volume
0    2017-11-02  12.400  12.40   9.77   9.98       9.98    2388800
1    2017-11-03  10.100  10.50   8.66   9.79       9.79     356200
2    2017-11-06   9.740  10.64   9.01  10.48      10.48     125800
3    2017-11-07  10.650  11.23  10.60  11.00      11.00     267100
4    2017-11-08  11.020  11.70  11.00  11.58      11.58      60500
..          ...     ...    ...    ...    ...        ...        ...
961  2021-08-30   0.979   1.02   0.97   1.02       1.02  133190000
962  2021-08-31   1.010   1.03   1.00   1.02       1.02   82610000
963  2021-09-01   1.030   1.05   1.00   1.05       1.05  127410000
964  2021-09-02   1.070   1.08   1.03   1.05       1.05   91940000
965  2021-09-03   1.040   1.06   1.03   1.06       1.06   79860000

[966 rows x 7 columns]
tolistdate: 0      2017-11-02
1      2017-11-03
2      2017-11-06
3      2017-11-07
4      2017-11-08
          ...
961    2021-08-30
962    2021-08-31
963    2021-09-01
964    2021-09-02
965    2021-09-03
Name: Date, Length: 966, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALNA_ended_2021-09-25  2017-11-02          1.06  0.525  17.56      1.7035

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.2285     3.932    5.6355     7.339    9.0425    10.746   12.4495

  markup_80 markup_90 markup_100
0    14.153   15.8565      17.56
                   stock  start_date current_price minall maxall each_markup  \
0  ALNA_ended_2021-09-25  2017-11-02          1.06  0.525  17.56      1.7035

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.2285     3.932    5.6355     7.339    9.0425    10.746   12.4495

  markup_80 markup_90 markup_100
0    14.153   15.8565      17.56
./ticker_data/ticker_data_2021-09-25 - Copy/ALNY_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2004-06-01    6.100000    7.050000    6.080000    7.000000    7.000000
1     2004-06-02    6.500000    9.500000    6.400000    7.210000    7.210000
2     2004-06-03    7.390000    8.000000    7.300000    7.460000    7.460000
3     2004-06-04    7.300000    7.900000    7.200000    7.680000    7.680000
4     2004-06-07    8.170000    8.550000    7.500000    7.770000    7.770000
...          ...         ...         ...         ...         ...         ...
4342  2021-08-30  204.800003  208.320007  203.110001  203.509995  203.509995
4343  2021-08-31  204.449997  205.690002  200.330002  201.429993  201.429993
4344  2021-09-01  200.720001  201.679993  196.559998  197.039993  197.039993
4345  2021-09-02  198.990005  202.770004  197.029999  200.179993  200.179993
4346  2021-09-03  199.669998  200.419998  197.360001  197.460007  197.460007

        Volume
0       198200
1       572200
2       248500
3       186600
4       131800
...        ...
4342  46730000
4343  80690000
4344  58790000
4345  54080000
4346  32100000

[4347 rows x 7 columns]
tolistdate: 0       2004-06-01
1       2004-06-02
2       2004-06-03
3       2004-06-04
4       2004-06-07
           ...
4342    2021-08-30
4343    2021-08-31
4344    2021-09-01
4345    2021-09-02
4346    2021-09-03
Name: Date, Length: 4347, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ALNY_ended_2021-09-25  2004-06-01        197.46   3.65  209.73      20.608

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    24.258    44.866    65.474    86.082    106.69   127.298   147.906

  markup_80 markup_90 markup_100
0   168.514   189.122     209.73
                   stock  start_date current_price minall  maxall each_markup  \
0  ALNY_ended_2021-09-25  2004-06-01        197.46   3.65  209.73      20.608

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    24.258    44.866    65.474    86.082    106.69   127.298   147.906

  markup_80 markup_90 markup_100
0   168.514   189.122     209.73
./ticker_data/ticker_data_2021-09-25 - Copy/ALOT_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   4.000000   4.454545   4.000000   4.454545   2.597492
1     2000-01-03   4.363636   4.409091   4.363636   4.409091   2.570987
2     2000-01-04   4.727273   4.727273   4.727273   4.727273   2.756522
3     2000-01-05   4.727273   4.727273   4.363636   4.363636   2.544483
4     2000-01-06   4.181818   4.363636   4.181818   4.318182   2.517978
...          ...        ...        ...        ...        ...        ...
5287  2021-09-20  15.690000  16.080000  14.900000  15.980000  15.980000
5288  2021-09-21  15.950000  16.160000  15.890000  15.920000  15.920000
5289  2021-09-22  15.800000  15.990000  15.800000  15.800000  15.800000
5290  2021-09-23  15.700000  15.700000  15.250000  15.660000  15.660000
5291  2021-09-24  15.310700  15.460000  15.293900  15.293900  15.293900

      Volume
0       7975
1       2063
2        275
3       2475
4       9625
...      ...
5287   16600
5288    3300
5289    6100
5290    3700
5291     845

[5292 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5287    2021-09-20
5288    2021-09-21
5289    2021-09-22
5290    2021-09-23
5291    2021-09-24
Name: Date, Length: 5292, dtype: object
                   stock  start_date current_price   minall maxall  \
0  ALOT_ended_2021-09-25  1999-12-31       15.2939  2.02182  27.96

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     2.59382   4.61564   7.20945   9.80327   12.3971   14.9909   17.5847

  markup_70 markup_80 markup_90 markup_100
0   20.1785   22.7724   25.3662      27.96
                   stock  start_date current_price   minall maxall  \
0  ALOT_ended_2021-09-25  1999-12-31       15.2939  2.02182  27.96

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     2.59382   4.61564   7.20945   9.80327   12.3971   14.9909   17.5847

  markup_70 markup_80 markup_90 markup_100
0   20.1785   22.7724   25.3662      27.96
./ticker_data/ticker_data_2021-09-25 - Copy/ALPN_ended_2021-09-25.csv
            Date       Open       High        Low  Close  Adj Close    Volume
0     2015-06-17  66.000000  71.360001  59.000000  59.68      59.68   1267800
1     2015-06-18  61.520000  61.520000  58.959999  59.00      59.00    127000
2     2015-06-19  57.919998  60.360001  56.279999  59.00      59.00     58000
3     2015-06-22  60.000000  60.000000  58.799999  59.52      59.52     33700
4     2015-06-23  59.279999  60.000000  58.680000  59.48      59.48     15100
...          ...        ...        ...        ...    ...        ...       ...
1561  2021-08-30   9.560000   9.560000   9.170000   9.27       9.27  10610000
1562  2021-08-31   9.460000   9.510000   9.309000   9.51       9.51  20090000
1563  2021-09-01   9.570000   9.790000   9.510000   9.63       9.63   3930000
1564  2021-09-02   9.620000   9.639000   9.440000   9.50       9.50   7240000
1565  2021-09-03   9.530000   9.700000   9.310000   9.49       9.49   2320000

[1566 rows x 7 columns]
tolistdate: 0       2015-06-17
1       2015-06-18
2       2015-06-19
3       2015-06-22
4       2015-06-23
           ...
1561    2021-08-30
1562    2021-08-31
1563    2021-09-01
1564    2021-09-02
1565    2021-09-03
Name: Date, Length: 1566, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALPN_ended_2021-09-25  2015-06-17          9.49   2.05  81.72       7.967

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.017    17.984    25.951    33.918    41.885    49.852    57.819

  markup_80 markup_90 markup_100
0    65.786    73.753      81.72
                   stock  start_date current_price minall maxall each_markup  \
0  ALPN_ended_2021-09-25  2015-06-17          9.49   2.05  81.72       7.967

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.017    17.984    25.951    33.918    41.885    49.852    57.819

  markup_80 markup_90 markup_100
0    65.786    73.753      81.72
./ticker_data/ticker_data_2021-09-25 - Copy/ALRM_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2015-06-26  16.049999  17.879999  15.900000  16.879999  16.879999
1     2015-06-29  16.790001  16.889999  15.750000  15.770000  15.770000
2     2015-06-30  16.000000  16.250000  14.710000  15.380000  15.380000
3     2015-07-01  16.660000  16.680000  15.620000  15.720000  15.720000
4     2015-07-02  15.850000  17.650000  15.600000  17.040001  17.040001
...          ...        ...        ...        ...        ...        ...
1554  2021-08-30  84.150002  84.230003  82.339996  83.330002  83.330002
1555  2021-08-31  83.489998  84.449997  82.629997  84.330002  84.330002
1556  2021-09-01  84.489998  85.379997  84.489998  85.279999  85.279999
1557  2021-09-02  85.820000  86.285004  85.000000  85.290001  85.290001
1558  2021-09-03  84.930000  85.330002  83.624001  85.139999  85.139999

        Volume
0      9088400
1       891000
2       805000
3       924500
4       695300
...        ...
1554  18470000
1555  17940000
1556  10770000
1557  11380000
1558  16610000

[1559 rows x 7 columns]
tolistdate: 0       2015-06-26
1       2015-06-29
2       2015-06-30
3       2015-07-01
4       2015-07-02
           ...
1554    2021-08-30
1555    2021-08-31
1556    2021-09-01
1557    2021-09-02
1558    2021-09-03
Name: Date, Length: 1559, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ALRM_ended_2021-09-25  2015-06-26         85.14  10.26  108.67       9.841

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    20.101    29.942    39.783    49.624    59.465    69.306    79.147

  markup_80 markup_90 markup_100
0    88.988    98.829     108.67
                   stock  start_date current_price minall  maxall each_markup  \
0  ALRM_ended_2021-09-25  2015-06-26         85.14  10.26  108.67       9.841

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    20.101    29.942    39.783    49.624    59.465    69.306    79.147

  markup_80 markup_90 markup_100
0    88.988    98.829     108.67
./ticker_data/ticker_data_2021-09-25 - Copy/ALRN_ended_2021-09-25.csv
            Date   Open   High     Low  Close  Adj Close    Volume
0     2017-06-29  13.75  14.00  10.370  10.80      10.80   2168800
1     2017-06-30  10.75  11.48  10.730  11.15      11.15    243600
2     2017-07-03  11.95  12.65  11.510  12.60      12.60    251300
3     2017-07-05  12.53  12.80  12.000  12.31      12.31    200500
4     2017-07-06  12.33  13.30  12.088  13.30      13.30    125400
...          ...    ...    ...     ...    ...        ...       ...
1049  2021-08-30   1.10   1.13   1.090   1.10       1.10  60030000
1050  2021-08-31   1.09   1.15   1.090   1.15       1.15  49570000
1051  2021-09-01   1.13   1.18   1.130   1.16       1.16  23490000
1052  2021-09-02   1.17   1.20   1.150   1.18       1.18  58150000
1053  2021-09-03   1.19   1.19   1.160   1.17       1.17  28380000

[1054 rows x 7 columns]
tolistdate: 0       2017-06-29
1       2017-06-30
2       2017-07-03
3       2017-07-05
4       2017-07-06
           ...
1049    2021-08-30
1050    2021-08-31
1051    2021-09-01
1052    2021-09-02
1053    2021-09-03
Name: Date, Length: 1054, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALRN_ended_2021-09-25  2017-06-29          1.17   0.25  15.48       1.523

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.773     3.296     4.819     6.342     7.865     9.388    10.911

  markup_80 markup_90 markup_100
0    12.434    13.957      15.48
                   stock  start_date current_price minall maxall each_markup  \
0  ALRN_ended_2021-09-25  2017-06-29          1.17   0.25  15.48       1.523

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.773     3.296     4.819     6.342     7.865     9.388    10.911

  markup_80 markup_90 markup_100
0    12.434    13.957      15.48
./ticker_data/ticker_data_2021-09-25 - Copy/ALRS_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2003-03-20   4.983333   4.983333   4.983333   4.983333   3.058184
1     2003-04-01   4.766667   4.766667   4.766667   4.766667   2.925220
2     2003-04-02   4.975000   4.975000   4.975000   4.975000   3.053070
3     2003-04-03   4.708333   4.708333   4.548333   4.548333   2.791232
4     2003-04-04   4.548333   4.548333   4.548333   4.548333   2.791232
...          ...        ...        ...        ...        ...        ...
2784  2021-09-20  28.290001  28.969999  27.549999  27.830000  27.830000
2785  2021-09-21  28.200001  28.740000  27.670000  27.730000  27.730000
2786  2021-09-22  27.750000  28.559999  27.510000  27.850000  27.850000
2787  2021-09-23  28.230000  29.990000  27.540001  28.900000  28.900000
2788  2021-09-24  29.100000  29.389999  28.530001  29.389999  29.389999

      Volume
0          0
1      12000
2      12000
3       8400
4          0
...      ...
2784   25300
2785    5900
2786   15300
2787   24800
2788    6620

[2789 rows x 7 columns]
tolistdate: 0       2003-03-20
1       2003-04-01
2       2003-04-02
3       2003-04-03
4       2003-04-04
           ...
2784    2021-09-20
2785    2021-09-21
2786    2021-09-22
2787    2021-09-23
2788    2021-09-24
Name: Date, Length: 2789, dtype: object
                   stock  start_date current_price   minall maxall  \
0  ALRS_ended_2021-09-25  2003-03-20         29.39  4.54833   34.7

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     3.01517    7.5635   10.5787   13.5938    16.609   19.6242   22.6393

  markup_70 markup_80 markup_90 markup_100
0   25.6545   28.6697   31.6848       34.7
                   stock  start_date current_price   minall maxall  \
0  ALRS_ended_2021-09-25  2003-03-20         29.39  4.54833   34.7

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     3.01517    7.5635   10.5787   13.5938    16.609   19.6242   22.6393

  markup_70 markup_80 markup_90 markup_100
0   25.6545   28.6697   31.6848       34.7
./ticker_data/ticker_data_2021-09-25 - Copy/ALSK_ended_2021-09-25.csv
            Date     Open    High      Low    Close  Adj Close  Volume
0     1999-12-31  12.3750  12.750  12.3750  12.3750   6.193254   63500
1     2000-01-03  12.6250  13.250  12.1875  13.2500   6.631161  117500
2     2000-01-04  13.3125  14.500  13.2500  14.2500   7.131626  618400
3     2000-01-05  14.0000  15.000  13.7500  14.5625   7.288022  382000
4     2000-01-06  14.6250  15.125  14.3125  14.5000   7.256742  304800
...          ...      ...     ...      ...      ...        ...     ...
5419  2021-07-16   3.3500   3.380   3.3400   3.3800   3.380000  372100
5420  2021-07-19   3.3800   3.380   3.3700   3.3800   3.380000  356800
5421  2021-07-20   3.3700   3.390   3.3700   3.3800   3.380000  365000
5422  2021-07-21   3.3900   3.390   3.3800   3.3900   3.390000  377900
5423  2021-07-22   3.3800   3.400   3.3800   3.4000   3.400000  879557

[5424 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5419    2021-07-16
5420    2021-07-19
5421    2021-07-20
5422    2021-07-21
5423    2021-07-22
Name: Date, Length: 5424, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALSK_ended_2021-09-25  1999-12-31           3.4   1.18  17.15       1.597

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.777     4.374     5.971     7.568     9.165    10.762    12.359

  markup_80 markup_90 markup_100
0    13.956    15.553      17.15
                   stock  start_date current_price minall maxall each_markup  \
0  ALSK_ended_2021-09-25  1999-12-31           3.4   1.18  17.15       1.597

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.777     4.374     5.971     7.568     9.165    10.762    12.359

  markup_80 markup_90 markup_100
0    13.956    15.553      17.15
./ticker_data/ticker_data_2021-09-25 - Copy/ALTA_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2015-06-11  15.760000  17.440001  15.610000  16.700001  16.159697
1     2015-06-12  16.490000  16.780001  16.000000  16.410000  15.879080
2     2015-06-15  16.110001  16.600000  16.000000  16.059999  15.540401
3     2015-06-16  16.070000  16.250000  16.049999  16.200001  15.675875
4     2015-06-17  16.200001  16.690001  16.110001  16.490000  15.956491
...          ...        ...        ...        ...        ...        ...
1565  2021-08-30  42.209999  42.305000  41.220001  41.220001  41.220001
1566  2021-08-31  41.430000  41.910000  41.099998  41.520000  41.520000
1567  2021-09-01  41.549999  41.970001  40.820000  41.799999  41.799999
1568  2021-09-02  41.770000  42.139999  41.419998  41.570000  41.570000
1569  2021-09-03  41.529999  41.660000  41.110001  41.290001  41.290001

       Volume
0     1408700
1      186200
2       70500
3       41700
4       43900
...       ...
1565  6290000
1566  6440000
1567  9010000
1568  4300000
1569  2490000

[1570 rows x 7 columns]
tolistdate: 0       2015-06-11
1       2015-06-12
2       2015-06-15
3       2015-06-16
4       2015-06-17
           ...
1565    2021-08-30
1566    2021-08-31
1567    2021-09-01
1568    2021-09-02
1569    2021-09-03
Name: Date, Length: 1570, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALTA_ended_2021-09-25  2015-06-11         41.29  13.55   47.8       3.425

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    16.975      20.4    23.825     27.25    30.675      34.1    37.525

  markup_80 markup_90 markup_100
0     40.95    44.375       47.8
                   stock  start_date current_price minall maxall each_markup  \
0  ALTA_ended_2021-09-25  2015-06-11         41.29  13.55   47.8       3.425

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    16.975      20.4    23.825     27.25    30.675      34.1    37.525

  markup_80 markup_90 markup_100
0     40.95    44.375       47.8
./ticker_data/ticker_data_2021-09-25 - Copy/ALTM_ended_2021-09-25.csv
           Date        Open        High         Low       Close   Adj Close  \
0    2018-11-13  191.000000  191.000000  181.199997  182.000000  169.424744
1    2018-11-14  191.000000  192.000000  166.199997  166.199997  154.716446
2    2018-11-15  171.000000  184.000000  170.399994  176.399994  164.211685
3    2018-11-16  179.600006  182.199997  171.399994  173.600006  161.605164
4    2018-11-19  175.199997  176.199997  164.800003  165.000000  153.599350
..          ...         ...         ...         ...         ...         ...
701  2021-08-30   65.410004   65.410004   63.900002   63.900002   63.900002
702  2021-08-31   63.900002   65.500000   62.509998   65.180000   65.180000
703  2021-09-01   65.180000   65.180000   63.680000   64.360001   64.360001
704  2021-09-02   64.430000   65.529999   64.339996   64.870003   64.870003
705  2021-09-03   65.000000   65.500000   64.029999   64.779999   64.779999

      Volume
0        600
1       2800
2      27600
3       5600
4       1100
..       ...
701  2170000
702  3930000
703  2560000
704  2780000
705  4070000

[706 rows x 7 columns]
tolistdate: 0      2018-11-13
1      2018-11-14
2      2018-11-15
3      2018-11-16
4      2018-11-19
          ...
701    2021-08-30
702    2021-08-31
703    2021-09-01
704    2021-09-02
705    2021-09-03
Name: Date, Length: 706, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALTM_ended_2021-09-25  2018-11-13         64.78    9.4  209.6       20.02

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     29.42     49.44     69.46     89.48     109.5    129.52    149.54

  markup_80 markup_90 markup_100
0    169.56    189.58      209.6
                   stock  start_date current_price minall maxall each_markup  \
0  ALTM_ended_2021-09-25  2018-11-13         64.78    9.4  209.6       20.02

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     29.42     49.44     69.46     89.48     109.5    129.52    149.54

  markup_80 markup_90 markup_100
0    169.56    189.58      209.6
./ticker_data/ticker_data_2021-09-25 - Copy/ALTO_ended_2021-09-25.csv
           Date     Open     High      Low    Close  Adj Close     Volume
0    2009-05-11  0.14250  0.14250  0.14250  0.14250    0.14250    1024000
1    2009-05-18  0.14250  0.14250  0.14188  0.14188    0.14188     424000
2    2009-05-20  0.14250  0.14250  0.14188  0.14250    0.14250     400000
3    2009-05-21  0.13125  0.14188  0.13125  0.14188    0.14188     212000
4    2009-06-25  0.13500  0.13500  0.12625  0.12875    0.12875      52000
..          ...      ...      ...      ...      ...        ...        ...
848  2021-08-30  5.00000  5.02000  4.74000  4.89000    4.89000  309950000
849  2021-08-31  4.92000  5.14000  4.87000  5.09000    5.09000  216120000
850  2021-09-01  5.08000  5.10000  4.86000  4.91000    4.91000  160860000
851  2021-09-02  5.01000  5.19000  5.00000  5.04000    5.04000  200370000
852  2021-09-03  5.04000  5.09000  4.91000  4.91000    4.91000  113940000

[853 rows x 7 columns]
tolistdate: 0      2009-05-11
1      2009-05-18
2      2009-05-20
3      2009-05-21
4      2009-06-25
          ...
848    2021-08-30
849    2021-08-31
850    2021-09-01
851    2021-09-02
852    2021-09-03
Name: Date, Length: 853, dtype: object
                   stock  start_date current_price  minall maxall each_markup  \
0  ALTO_ended_2021-09-25  2009-05-11          4.91  0.0002    320          32

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   32.0002   64.0002   96.0001       128       160       192       224

  markup_80 markup_90 markup_100
0       256       288        320
                   stock  start_date current_price  minall maxall each_markup  \
0  ALTO_ended_2021-09-25  2009-05-11          4.91  0.0002    320          32

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   32.0002   64.0002   96.0001       128       160       192       224

  markup_80 markup_90 markup_100
0       256       288        320
./ticker_data/ticker_data_2021-09-25 - Copy/ALTR_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2017-11-01  17.100000  18.980000  16.549999  18.309999  18.309999
1    2017-11-02  18.049999  18.200001  17.330000  17.410000  17.410000
2    2017-11-03  17.500000  19.400000  17.500000  19.370001  19.370001
3    2017-11-06  19.059999  19.600000  18.101000  18.969999  18.969999
4    2017-11-07  18.990000  19.945000  18.850000  19.510000  19.510000
..          ...        ...        ...        ...        ...        ...
961  2021-08-30  75.230003  75.230003  73.900002  74.070000  74.070000
962  2021-08-31  74.260002  74.459999  73.519997  73.989998  73.989998
963  2021-09-01  74.500000  76.089996  74.440002  75.300003  75.300003
964  2021-09-02  75.709999  75.764999  74.470001  75.339996  75.339996
965  2021-09-03  75.110001  76.199997  74.849998  75.070000  75.070000

       Volume
0     7533500
1      952100
2      842700
3      427400
4     1008700
..        ...
961  13090000
962  19190000
963  16610000
964  16880000
965   9640000

[966 rows x 7 columns]
tolistdate: 0      2017-11-01
1      2017-11-02
2      2017-11-03
3      2017-11-06
4      2017-11-07
          ...
961    2021-08-30
962    2021-08-31
963    2021-09-01
964    2021-09-02
965    2021-09-03
Name: Date, Length: 966, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALTR_ended_2021-09-25  2017-11-01         75.07  16.55  76.91       6.036

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    22.586    28.622    34.658    40.694     46.73    52.766    58.802

  markup_80 markup_90 markup_100
0    64.838    70.874      76.91
                   stock  start_date current_price minall maxall each_markup  \
0  ALTR_ended_2021-09-25  2017-11-01         75.07  16.55  76.91       6.036

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    22.586    28.622    34.658    40.694     46.73    52.766    58.802

  markup_80 markup_90 markup_100
0    64.838    70.874      76.91
./ticker_data/ticker_data_2021-09-25 - Copy/ALTUU_ended_2021-09-25.csv
           Date   Open   High     Low  Close  Adj Close   Volume
0    2020-12-09  10.22  10.29  10.200  10.21      10.21  3914800
1    2020-12-10  10.25  10.25  10.190  10.19      10.19   145900
2    2020-12-11  10.34  10.34  10.205  10.29      10.29   618900
3    2020-12-14  10.40  10.40  10.260  10.29      10.29    73000
4    2020-12-15  10.30  10.30  10.280  10.30      10.30    23900
..          ...    ...    ...     ...    ...        ...      ...
166  2021-08-30  10.27  10.27  10.270  10.27      10.27    10000
167  2021-08-31  10.02  10.02  10.020  10.02      10.02    20000
168  2021-09-01  10.21  10.21  10.140  10.18      10.18  1520000
169  2021-09-02  10.09  10.09  10.090  10.09      10.09    10000
170  2021-09-03  10.09  10.09  10.090  10.09      10.09        0

[171 rows x 7 columns]
tolistdate: 0      2020-12-09
1      2020-12-10
2      2020-12-11
3      2020-12-14
4      2020-12-15
          ...
166    2021-08-30
167    2021-08-31
168    2021-09-01
169    2021-09-02
170    2021-09-03
Name: Date, Length: 171, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ALTUU_ended_2021-09-25  2020-12-09         10.09   9.92     17       0.708

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.628    11.336    12.044    12.752     13.46    14.168    14.876

  markup_80 markup_90 markup_100
0    15.584    16.292         17
                    stock  start_date current_price minall maxall each_markup  \
0  ALTUU_ended_2021-09-25  2020-12-09         10.09   9.92     17       0.708

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.628    11.336    12.044    12.752     13.46    14.168    14.876

  markup_80 markup_90 markup_100
0    15.584    16.292         17
./ticker_data/ticker_data_2021-09-25 - Copy/ALTUW_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close   Volume
0    2021-01-29  1.910  2.010  1.690  1.700      1.700    45600
1    2021-02-01  4.302  5.200  1.800  2.050      2.050    39700
2    2021-02-02  2.090  2.717  1.850  2.390      2.390   508100
3    2021-02-03  2.120  2.360  1.950  2.050      2.050   738500
4    2021-02-04  2.240  2.240  1.950  2.050      2.050    48500
..          ...    ...    ...    ...    ...        ...      ...
146  2021-08-30  0.660  0.680  0.560  0.605      0.605  6990000
147  2021-08-31  0.610  0.650  0.600  0.610      0.610  3260000
148  2021-09-01  0.600  0.649  0.589  0.610      0.610  8780000
149  2021-09-02  0.589  0.649  0.589  0.600      0.600  2580000
150  2021-09-03  0.591  0.659  0.591  0.630      0.630  3610000

[151 rows x 7 columns]
tolistdate: 0      2021-01-29
1      2021-02-01
2      2021-02-02
3      2021-02-03
4      2021-02-04
          ...
146    2021-08-30
147    2021-08-31
148    2021-09-01
149    2021-09-02
150    2021-09-03
Name: Date, Length: 151, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ALTUW_ended_2021-09-25  2021-01-29          0.63   0.56   5.72       0.516

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.076     1.592     2.108     2.624      3.14     3.656     4.172

  markup_80 markup_90 markup_100
0     4.688     5.204       5.72
                    stock  start_date current_price minall maxall each_markup  \
0  ALTUW_ended_2021-09-25  2021-01-29          0.63   0.56   5.72       0.516

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.076     1.592     2.108     2.624      3.14     3.656     4.172

  markup_80 markup_90 markup_100
0     4.688     5.204       5.72
./ticker_data/ticker_data_2021-09-25 - Copy/ALTU_ended_2021-09-25.csv
           Date   Open    High    Low  Close  Adj Close   Volume
0    2021-01-29  10.04  10.200  10.01  10.10      10.10    21700
1    2021-02-01  10.20  10.700  10.15  10.18      10.18    41300
2    2021-02-02  10.18  10.210  10.10  10.14      10.14    78800
3    2021-02-03  10.12  10.330  10.11  10.25      10.25   115600
4    2021-02-04  10.30  10.310  10.14  10.26      10.26    73200
..          ...    ...     ...    ...    ...        ...      ...
147  2021-08-30   9.80   9.830   9.78   9.78       9.78  2100000
148  2021-08-31   9.77   9.810   9.77   9.79       9.79  3170000
149  2021-09-01   9.78   9.825   9.78   9.80       9.80  2710000
150  2021-09-02   9.79   9.830   9.79   9.80       9.80  2250000
151  2021-09-03   9.80   9.830   9.79   9.83       9.83  6080000

[152 rows x 7 columns]
tolistdate: 0      2021-01-29
1      2021-02-01
2      2021-02-02
3      2021-02-03
4      2021-02-04
          ...
147    2021-08-30
148    2021-08-31
149    2021-09-01
150    2021-09-02
151    2021-09-03
Name: Date, Length: 152, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALTU_ended_2021-09-25  2021-01-29          9.83   9.62  14.54       0.492

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.112    10.604    11.096    11.588     12.08    12.572    13.064

  markup_80 markup_90 markup_100
0    13.556    14.048      14.54
                   stock  start_date current_price minall maxall each_markup  \
0  ALTU_ended_2021-09-25  2021-01-29          9.83   9.62  14.54       0.492

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.112    10.604    11.096    11.588     12.08    12.572    13.064

  markup_80 markup_90 markup_100
0    13.556    14.048      14.54
./ticker_data/ticker_data_2021-09-25 - Copy/ALT_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2017-05-26  135.000000  137.699997  131.699997  133.199997  133.199997
1     2017-05-30  132.000000  132.000000  124.230003  125.099998  125.099998
2     2017-05-31  123.300003  129.360001  123.300003  127.500000  127.500000
3     2017-06-01  126.900002  133.770004  126.900002  129.899994  129.899994
4     2017-06-02  129.899994  133.320007  127.500000  128.100006  128.100006
...          ...         ...         ...         ...         ...         ...
1072  2021-08-30   14.790000   14.960000   13.880000   14.090000   14.090000
1073  2021-08-31   14.050000   15.000000   13.950000   14.990000   14.990000
1074  2021-09-01   14.865000   15.400000   14.750000   15.370000   15.370000
1075  2021-09-02   15.497000   16.610001   15.390000   16.070000   16.070000
1076  2021-09-03   16.000000   16.480000   15.570000   16.430000   16.430000

         Volume
0          1500
1          2600
2          1600
3          1400
4          2100
...         ...
1072   82530000
1073  113050000
1074   81910000
1075  165940000
1076  100380000

[1077 rows x 7 columns]
tolistdate: 0       2017-05-26
1       2017-05-30
2       2017-05-31
3       2017-06-01
4       2017-06-02
           ...
1072    2021-08-30
1073    2021-08-31
1074    2021-09-01
1075    2021-09-02
1076    2021-09-03
Name: Date, Length: 1077, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  ALT_ended_2021-09-25  2017-05-26         16.43   1.51  137.7      13.619

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.129    28.748    42.367    55.986    69.605    83.224    96.843

  markup_80 markup_90 markup_100
0   110.462   124.081      137.7
                  stock  start_date current_price minall maxall each_markup  \
0  ALT_ended_2021-09-25  2017-05-26         16.43   1.51  137.7      13.619

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.129    28.748    42.367    55.986    69.605    83.224    96.843

  markup_80 markup_90 markup_100
0   110.462   124.081      137.7
./ticker_data/ticker_data_2021-09-25 - Copy/ALVR_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-07-30  21.000000  29.840000  18.150000  25.389999  25.389999
1    2020-07-31  22.820000  26.000000  22.100000  24.900000  24.900000
2    2020-08-03  24.049999  26.850000  23.010000  25.850000  25.850000
3    2020-08-04  26.110001  31.590000  25.969999  29.400000  29.400000
4    2020-08-05  29.389999  36.689999  29.250000  30.549999  30.549999
..          ...        ...        ...        ...        ...        ...
272  2021-08-30  19.500000  20.150000  19.150000  19.280001  19.280001
273  2021-08-31  20.365000  20.365000  18.540001  19.250000  19.250000
274  2021-09-01  19.370001  19.959999  19.264999  19.889999  19.889999
275  2021-09-02  19.860001  20.299999  19.629999  20.070000  20.070000
276  2021-09-03  19.900000  20.490000  19.629999  20.209999  20.209999

       Volume
0     5316100
1      407900
2      474600
3      378300
4     1774100
..        ...
272  18980000
273  14100000
274  16530000
275  31760000
276  23010000

[277 rows x 7 columns]
tolistdate: 0      2020-07-30
1      2020-07-31
2      2020-08-03
3      2020-08-04
4      2020-08-05
          ...
272    2021-08-30
273    2021-08-31
274    2021-09-01
275    2021-09-02
276    2021-09-03
Name: Date, Length: 277, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ALVR_ended_2021-09-25  2020-07-30         20.21  16.66  48.96        3.23

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     19.89     23.12     26.35     29.58     32.81     36.04     39.27

  markup_80 markup_90 markup_100
0      42.5     45.73      48.96
                   stock  start_date current_price minall maxall each_markup  \
0  ALVR_ended_2021-09-25  2020-07-30         20.21  16.66  48.96        3.23

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     19.89     23.12     26.35     29.58     32.81     36.04     39.27

  markup_80 markup_90 markup_100
0      42.5     45.73      48.96
./ticker_data/ticker_data_2021-09-25 - Copy/ALXO_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-07-17  37.500000  37.577000  29.020000  30.000000  30.000000
1    2020-07-20  30.440001  32.990002  29.250000  30.330000  30.330000
2    2020-07-21  32.250000  32.490002  28.250000  30.770000  30.770000
3    2020-07-22  30.910000  31.340000  29.139999  29.360001  29.360001
4    2020-07-23  29.340000  30.250000  28.010000  29.700001  29.700001
..          ...        ...        ...        ...        ...        ...
281  2021-08-30  75.500000  75.514999  72.000000  72.180000  72.180000
282  2021-08-31  72.680000  73.800003  69.629997  70.000000  70.000000
283  2021-09-01  70.839996  72.620003  70.209999  71.000000  71.000000
284  2021-09-02  71.389999  72.838997  70.500000  72.639999  72.639999
285  2021-09-03  73.040001  74.459999  70.500000  71.970001  71.970001

       Volume
0     1594900
1      455500
2      483100
3      170000
4       72000
..        ...
281  13710000
282  19810000
283  18620000
284   8940000
285  17190000

[286 rows x 7 columns]
tolistdate: 0      2020-07-17
1      2020-07-20
2      2020-07-21
3      2020-07-22
4      2020-07-23
          ...
281    2021-08-30
282    2021-08-31
283    2021-09-01
284    2021-09-02
285    2021-09-03
Name: Date, Length: 286, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ALXO_ended_2021-09-25  2020-07-17         71.97  28.01  117.45       8.944

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    36.954    45.898    54.842    63.786     72.73    81.674    90.618

  markup_80 markup_90 markup_100

0    99.562   108.506     117.45
                   stock  start_date current_price minall  maxall each_markup  \
0  ALXO_ended_2021-09-25  2020-07-17         71.97  28.01  117.45       8.944

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    36.954    45.898    54.842    63.786     72.73    81.674    90.618

  markup_80 markup_90 markup_100
0    99.562   108.506     117.45
./ticker_data/ticker_data_2021-09-25 - Copy/ALYA_ended_2021-09-25.csv
            Date    Open    High     Low   Close  Adj Close   Volume
0     1999-12-31  6.9375  7.5625  6.8750  7.5625   5.603745   252500
1     2000-01-03  7.3750  8.0000  7.1250  8.0000   5.927928    91400
2     2000-01-04  7.5000  8.0000  7.4375  7.5625   5.603745   126500
3     2000-01-05  7.5625  7.7500  7.2500  7.7500   5.742680   114000
4     2000-01-06  7.6250  8.1250  7.5000  8.0625   5.974240   175500
...          ...     ...     ...     ...     ...        ...      ...
5439  2021-08-30  2.8100  2.8700  2.7900  2.8400   2.840000  2250000
5440  2021-08-31  2.8600  2.9400  2.8400  2.8600   2.860000  2030000
5441  2021-09-01  2.8600  2.9100  2.8300  2.8400   2.840000  1300000
5442  2021-09-02  2.8000  2.9000  2.8000  2.8700   2.870000  6010000
5443  2021-09-03  2.8500  2.9300  2.8400  2.8900   2.890000  1590000

[5444 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5439    2021-08-30
5440    2021-08-31
5441    2021-09-01
5442    2021-09-02
5443    2021-09-03
Name: Date, Length: 5444, dtype: object
                   stock  start_date current_price minall   maxall  \
0  ALYA_ended_2021-09-25  1999-12-31          2.89   0.96  12.0625

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     1.11025   2.07025    3.1805   4.29075     5.401   6.51125    7.6215

  markup_70 markup_80 markup_90 markup_100
0   8.73175     9.842   10.9522    12.0625
                   stock  start_date current_price minall   maxall  \
0  ALYA_ended_2021-09-25  1999-12-31          2.89   0.96  12.0625

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     1.11025   2.07025    3.1805   4.29075     5.401   6.51125    7.6215

  markup_70 markup_80 markup_90 markup_100
0   8.73175     9.842   10.9522    12.0625
./ticker_data/ticker_data_2021-09-25 - Copy/AMAL_ended_2021-09-25.csv
           Date       Open       High        Low  Close  Adj Close   Volume
0    2018-08-09  16.000000  16.639999  16.000000  16.50  15.574078  3584100
1    2018-08-10  16.389999  16.480000  16.010000  16.40  15.479690   337800
2    2018-08-13  16.450001  16.520000  16.200001  16.50  15.574078   212100
3    2018-08-14  16.490000  16.520000  16.350000  16.50  15.574078   199800
4    2018-08-15  16.510000  16.530001  16.200001  16.43  15.508004    82100
..          ...        ...        ...        ...    ...        ...      ...
768  2021-08-30  15.700000  15.700000  15.240000  15.31  15.310000  1320000
769  2021-08-31  15.310000  15.610000  15.260000  15.55  15.550000  4620000
770  2021-09-01  15.610000  16.040001  15.510000  15.85  15.850000  7130000
771  2021-09-02  16.000000  16.150000  15.800000  16.01  16.010000  4130000
772  2021-09-03  15.940000  15.940000  15.550000  15.82  15.820000  2130000

[773 rows x 7 columns]
tolistdate: 0      2018-08-09
1      2018-08-10
2      2018-08-13
3      2018-08-14
4      2018-08-15
          ...
768    2021-08-30
769    2021-08-31
770    2021-09-01
771    2021-09-02
772    2021-09-03
Name: Date, Length: 773, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMAL_ended_2021-09-25  2018-08-09         15.82    7.9  22.97       1.507

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.407    10.914    12.421    13.928    15.435    16.942    18.449

  markup_80 markup_90 markup_100
0    19.956    21.463      22.97
                   stock  start_date current_price minall maxall each_markup  \
0  AMAL_ended_2021-09-25  2018-08-09         15.82    7.9  22.97       1.507

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.407    10.914    12.421    13.928    15.435    16.942    18.449

  markup_80 markup_90 markup_100
0    19.956    21.463      22.97
./ticker_data/ticker_data_2021-09-25 - Copy/AMAOU_ended_2021-09-25.csv
          Date    Open    High     Low   Close  Adj Close   Volume
0   2021-03-18   9.940   9.980   9.930   9.980      9.980  1720500
1   2021-03-19   9.990  10.000   9.950   9.970      9.970   133400
2   2021-03-22   9.975  10.000   9.950   9.960      9.960    68600
3   2021-03-23   9.950   9.957   9.930   9.930      9.930   177700
4   2021-03-24   9.910   9.950   9.890   9.900      9.900   665900
..         ...     ...     ...     ...     ...        ...      ...
71  2021-08-17  10.120  10.120  10.120  10.120     10.120        0
72  2021-08-20  10.102  10.102  10.102  10.102     10.102    10000
73  2021-08-23  10.102  10.102  10.102  10.102     10.102        0
74  2021-09-01  10.120  10.130  10.110  10.110     10.110   100000
75  2021-09-02  10.110  10.110  10.110  10.110     10.110        0

[76 rows x 7 columns]
tolistdate: 0     2021-03-18
1     2021-03-19
2     2021-03-22
3     2021-03-23
4     2021-03-24
         ...
71    2021-08-17
72    2021-08-20
73    2021-08-23
74    2021-09-01
75    2021-09-02
Name: Date, Length: 76, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AMAOU_ended_2021-09-25  2021-03-18         10.11   9.88  10.25       0.037

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.917     9.954     9.991    10.028    10.065    10.102    10.139

  markup_80 markup_90 markup_100
0    10.176    10.213      10.25
                    stock  start_date current_price minall maxall each_markup  \
0  AMAOU_ended_2021-09-25  2021-03-18         10.11   9.88  10.25       0.037

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.917     9.954     9.991    10.028    10.065    10.102    10.139

  markup_80 markup_90 markup_100
0    10.176    10.213      10.25
./ticker_data/ticker_data_2021-09-25 - Copy/AMAOW_ended_2021-09-25.csv
         Date  Open    High   Low   Close  Adj Close  Volume
0  2021-09-22  0.66  0.6699  0.51  0.6685     0.6685   12728
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall  maxall  \
0  AMAOW_ended_2021-09-25  2021-09-22        0.6685   0.51  0.6699

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.01599   0.52599   0.54198   0.55797   0.57396   0.58995   0.60594

  markup_70 markup_80 markup_90 markup_100
0   0.62193   0.63792   0.65391     0.6699
                    stock  start_date current_price minall  maxall  \
0  AMAOW_ended_2021-09-25  2021-09-22        0.6685   0.51  0.6699

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.01599   0.52599   0.54198   0.55797   0.57396   0.58995   0.60594

  markup_70 markup_80 markup_90 markup_100
0   0.62193   0.63792   0.65391     0.6699
./ticker_data/ticker_data_2021-09-25 - Copy/AMAO_ended_2021-09-25.csv
          Date  Open   High   Low  Close  Adj Close   Volume
0   2021-05-05  9.85   9.87  9.85   9.87       9.87   153100
1   2021-05-06  9.86  10.00  9.85   9.85       9.85    46600
2   2021-05-07  9.86   9.86  9.84   9.84       9.84    49800
3   2021-05-10  9.84   9.86  9.84   9.84       9.84   128100
4   2021-05-11  9.84  10.00  9.84  10.00      10.00     1800
..         ...   ...    ...   ...    ...        ...      ...
57  2021-08-05  9.91   9.91  9.90   9.90       9.90   280000
58  2021-08-12  9.90   9.90  9.90   9.90       9.90    20000
59  2021-08-16  9.87   9.92  9.85   9.92       9.92  1430000
60  2021-09-01  9.92  10.00  9.92   9.99       9.99   290000
61  2021-09-02  9.99   9.99  9.99   9.99       9.99        0

[62 rows x 7 columns]
tolistdate: 0     2021-05-05
1     2021-05-06
2     2021-05-07
3     2021-05-10
4     2021-05-11
         ...
57    2021-08-05
58    2021-08-12
59    2021-08-16
60    2021-09-01
61    2021-09-02
Name: Date, Length: 62, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMAO_ended_2021-09-25  2021-05-05          9.99   9.84     10       0.016

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.856     9.872     9.888     9.904      9.92     9.936     9.952

  markup_80 markup_90 markup_100
0     9.968     9.984         10
                   stock  start_date current_price minall maxall each_markup  \
0  AMAO_ended_2021-09-25  2021-05-05          9.99   9.84     10       0.016

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.856     9.872     9.888     9.904      9.92     9.936     9.952

  markup_80 markup_90 markup_100
0     9.968     9.984         10
./ticker_data/ticker_data_2021-09-25 - Copy/AMAT_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31   31.140625   32.250000   31.031250   31.671875   23.803324
1     2000-01-03   32.093750   32.093750   30.343750   31.625000   23.768091
2     2000-01-04   30.437500   31.312500   30.000000   30.062500   22.593775
3     2000-01-05   29.515625   30.046875   28.406250   28.937500   21.748281
4     2000-01-06   28.562500   29.718750   28.062500   28.984375   21.783504
...          ...         ...         ...         ...         ...         ...
5451  2021-08-30  137.570007  137.889999  135.380005  136.050003  136.050003
5452  2021-08-31  136.449997  136.600006  133.550003  135.130005  135.130005
5453  2021-09-01  135.679993  136.039993  133.240005  133.460007  133.460007
5454  2021-09-02  134.729996  135.949997  133.880005  134.449997  134.449997
5455  2021-09-03  133.839996  136.429993  133.350006  135.830002  135.830002

           Volume
0       6462800.0
1      14356400.0
2      22822400.0
3      27791200.0
4      22438000.0
...           ...
5451  461770000.0
5452  558390000.0
5453  626030000.0
5454  514660000.0
5455  483600000.0

[5456 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5451    2021-08-30
5452    2021-08-31
5453    2021-09-01
5454    2021-09-02
5455    2021-09-03
Name: Date, Length: 5456, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMAT_ended_2021-09-25  1999-12-31        135.83    7.8    146       13.82

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     21.62     35.44     49.26     63.08      76.9     90.72    104.54

  markup_80 markup_90 markup_100
0    118.36    132.18        146
                   stock  start_date current_price minall maxall each_markup  \
0  AMAT_ended_2021-09-25  1999-12-31        135.83    7.8    146       13.82

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     21.62     35.44     49.26     63.08      76.9     90.72    104.54

  markup_80 markup_90 markup_100
0    118.36    132.18        146
./ticker_data/ticker_data_2021-09-25 - Copy/AMBA_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2012-10-10    6.710000    6.850000    6.000000    6.060000    6.060000
1     2012-10-11    6.060000    6.440000    6.000000    6.080000    6.080000
2     2012-10-12    6.050000    6.300000    6.010000    6.230000    6.230000
3     2012-10-15    6.350000    6.400000    6.050000    6.150000    6.150000
4     2012-10-16    6.150000    6.300000    5.940000    6.010000    6.010000
...          ...         ...         ...         ...         ...         ...
2234  2021-08-30  103.089996  106.430000  103.000000  105.489998  105.489998
2235  2021-08-31  105.290001  105.370003  101.400002  103.570000  103.570000
2236  2021-09-01  116.750000  132.729996  115.400002  131.960007  131.960007
2237  2021-09-02  132.770004  138.960007  130.770004  132.669998  132.669998
2238  2021-09-03  132.440002  139.850006  130.179993  137.199997  137.199997

         Volume
0       3566700
1        416700
2        155200
3        156700
4        173000
...         ...
2234   43970000
2235   70430000
2236  520380000
2237  262800000
2238  133230000

[2239 rows x 7 columns]
tolistdate: 0       2012-10-10
1       2012-10-11
2       2012-10-12
3       2012-10-15
4       2012-10-16
           ...
2234    2021-08-30
2235    2021-08-31
2236    2021-09-01
2237    2021-09-02
2238    2021-09-03
Name: Date, Length: 2239, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AMBA_ended_2021-09-25  2012-10-10         137.2   5.55  139.85       13.43

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     18.98     32.41     45.84     59.27      72.7     86.13     99.56

  markup_80 markup_90 markup_100
0    112.99    126.42     139.85
                   stock  start_date current_price minall  maxall each_markup  \
0  AMBA_ended_2021-09-25  2012-10-10         137.2   5.55  139.85       13.43

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     18.98     32.41     45.84     59.27      72.7     86.13     99.56

  markup_80 markup_90 markup_100
0    112.99    126.42     139.85
./ticker_data/ticker_data_2021-09-25 - Copy/AMCX_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2011-06-16  31.150000  35.490002  31.000000  35.490002  35.490002
1     2011-06-17  35.029999  35.500000  34.750000  35.049999  35.049999
2     2011-06-20  35.799999  35.799999  34.750000  34.950001  34.950001
3     2011-06-21  34.919998  38.450001  34.900002  35.000000  35.000000
4     2011-06-22  35.169998  35.540001  35.150002  35.540001  35.540001
...          ...        ...        ...        ...        ...        ...
2582  2021-09-20  46.639999  47.389999  45.830002  46.380001  46.380001
2583  2021-09-21  46.880001  47.189999  45.130001  45.209999  45.209999
2584  2021-09-22  45.720001  46.799999  45.720001  45.830002  45.830002
2585  2021-09-23  46.130001  46.820000  45.860001  46.639999  46.639999
2586  2021-09-24  46.209999  47.259998  46.119999  47.160000  47.160000

       Volume
0     1827600
1      435900
2      299400
3      335700
4       26700
...       ...
2582   329400
2583   252200
2584   163500
2585   177900
2586    70106

[2587 rows x 7 columns]
tolistdate: 0       2011-06-16
1       2011-06-17
2       2011-06-20
3       2011-06-21
4       2011-06-22
           ...
2582    2021-09-20
2583    2021-09-21
2584    2021-09-22
2585    2021-09-23
2586    2021-09-24
Name: Date, Length: 2587, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMCX_ended_2021-09-25  2011-06-16         47.16  19.62  87.18       6.756

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    26.376    33.132    39.888    46.644      53.4    60.156    66.912

  markup_80 markup_90 markup_100
0    73.668    80.424      87.18
                   stock  start_date current_price minall maxall each_markup  \
0  AMCX_ended_2021-09-25  2011-06-16         47.16  19.62  87.18       6.756

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    26.376    33.132    39.888    46.644      53.4    60.156    66.912

  markup_80 markup_90 markup_100
0    73.668    80.424      87.18

./ticker_data/ticker_data_2021-09-25 - Copy/AMD_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31   14.218750   14.468750   14.000000   14.468750   14.468750
1     2000-01-03   14.968750   15.593750   14.687500   15.500000   15.500000
2     2000-01-04   15.125000   15.500000   14.593750   14.625000   14.625000
3     2000-01-05   14.531250   15.062500   14.000000   15.000000   15.000000
4     2000-01-06   15.500000   16.000000   15.250000   16.000000   16.000000
...          ...         ...         ...         ...         ...         ...
5450  2021-08-30  112.610001  114.489998  111.260002  111.320000  111.320000
5451  2021-08-31  111.260002  111.260002  109.029999  110.720001  110.720001
5452  2021-09-01  111.300003  111.849998  109.849998  109.989998  109.989998
5453  2021-09-02  110.320000  110.879997  108.769997  109.199997  109.199997
5454  2021-09-03  108.849998  111.169998  108.500000  109.919998  109.919998

          Volume
0        1765600
1        7843200
2        6290200
3        8204600
4       11489400
...          ...
5450  5613050000
5451  4931590000
5452  3857960000
5453  4010880000
5454  4260580000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                  stock  start_date current_price minall  maxall each_markup  \
0  AMD_ended_2021-09-25  1999-12-31        109.92   1.61  122.49      12.088

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.698    25.786    37.874    49.962     62.05    74.138    86.226

  markup_80 markup_90 markup_100
0    98.314   110.402     122.49
                  stock  start_date current_price minall  maxall each_markup  \
0  AMD_ended_2021-09-25  1999-12-31        109.92   1.61  122.49      12.088

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.698    25.786    37.874    49.962     62.05    74.138    86.226

  markup_80 markup_90 markup_100
0    98.314   110.402     122.49
./ticker_data/ticker_data_2021-09-25 - Copy/AMED_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31    1.078125    1.078125    1.031250    1.031250    1.031250
1     2000-01-03    1.031250    1.031250    1.031250    1.031250    1.031250
2     2000-01-04    1.031250    1.078125    1.031250    1.078125    1.078125
3     2000-01-05    1.078125    1.078125    1.078125    1.078125    1.078125
4     2000-01-06    1.078125    1.125000    1.078125    1.125000    1.125000
...          ...         ...         ...         ...         ...         ...
5447  2021-08-30  178.320007  179.410004  175.850006  176.210007  176.210007
5448  2021-08-31  177.279999  183.720001  174.050003  183.449997  183.449997
5449  2021-09-01  183.000000  186.070007  179.770004  183.949997  183.949997
5450  2021-09-02  184.029999  187.529999  183.440002  187.210007  187.210007
5451  2021-09-03  186.699997  186.910004  183.000000  183.169998  183.169998

        Volume
0         5300
1            0
2         4100
3         4200
4         7300
...        ...
5447  20660000
5448  47010000
5449  46550000
5450  28870000
5451  23400000

[5452 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5447    2021-08-30
5448    2021-08-31
5449    2021-09-01
5450    2021-09-02
5451    2021-09-03
Name: Date, Length: 5452, dtype: object
                   stock  start_date current_price    minall  maxall  \
0  AMED_ended_2021-09-25  1999-12-31        183.17  0.796875  325.12

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     32.4323   33.2292   65.6615   98.0938   130.526   162.958   195.391

  markup_70 markup_80 markup_90 markup_100
0   227.823   260.255   292.688     325.12
                   stock  start_date current_price    minall  maxall  \
0  AMED_ended_2021-09-25  1999-12-31        183.17  0.796875  325.12

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     32.4323   33.2292   65.6615   98.0938   130.526   162.958   195.391

  markup_70 markup_80 markup_90 markup_100
0   227.823   260.255   292.688     325.12
./ticker_data/ticker_data_2021-09-25 - Copy/AMEH_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2009-03-11   9.400000   9.400000   9.400000   9.400000   9.400000
1     2009-04-06   2.000000   2.000000   2.000000   2.000000   2.000000
2     2009-04-07   2.000000   2.000000   2.000000   2.000000   2.000000
3     2009-04-09   2.000000   2.000000   2.000000   2.000000   2.000000
4     2009-04-13  17.000000  17.000000  17.000000  17.000000  17.000000
...          ...        ...        ...        ...        ...        ...
1991  2021-09-20  90.889999  93.059998  81.050003  82.809998  82.809998
1992  2021-09-21  84.570000  86.470001  78.610001  85.070000  85.070000
1993  2021-09-22  85.879997  90.389999  83.730003  90.290001  90.290001
1994  2021-09-23  91.239998  97.230003  91.010002  96.370003  96.370003
1995  2021-09-24  94.870003  99.589996  93.502899  95.230003  95.230003

       Volume
0           0
1          50
2           0
3         120
4          10
...       ...
1991  1273200
1992   823400
1993   569600
1994   653400
1995   257378

[1996 rows x 7 columns]
tolistdate: 0       2009-03-11
1       2009-04-06
2       2009-04-07
3       2009-04-09
4       2009-04-13
           ...
1991    2021-09-20
1992    2021-09-21
1993    2021-09-22
1994    2021-09-23
1995    2021-09-24
Name: Date, Length: 1996, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AMEH_ended_2021-09-25  2009-03-11         95.23    0.1  114.55      11.445

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.545     22.99    34.435     45.88    57.325     68.77    80.215

  markup_80 markup_90 markup_100
0     91.66   103.105     114.55
                   stock  start_date current_price minall  maxall each_markup  \
0  AMEH_ended_2021-09-25  2009-03-11         95.23    0.1  114.55      11.445

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.545     22.99    34.435     45.88    57.325     68.77    80.215

  markup_80 markup_90 markup_100
0     91.66   103.105     114.55
./ticker_data/ticker_data_2021-09-25 - Copy/AMGN_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31   65.375000   65.500000   59.875000   60.062500   47.196812
1     2000-01-03   70.000000   70.000000   62.875000   62.937500   49.455975
2     2000-01-04   62.000000   64.125000   57.687500   58.125000   45.674335
3     2000-01-05   59.187500   60.687500   58.250000   60.125000   47.245934
4     2000-01-06   60.750000   61.937500   60.250000   61.125000   48.031715
...          ...         ...         ...         ...         ...         ...
5449  2021-08-30  222.279999  225.309998  222.100006  224.130005  224.130005
5450  2021-08-31  224.940002  225.649994  223.339996  225.529999  225.529999
5451  2021-09-01  225.550003  226.119995  221.880005  223.350006  223.350006
5452  2021-09-02  223.639999  226.029999  223.429993  225.960007  225.960007
5453  2021-09-03  225.759995  227.190002  224.199997  226.369995  226.369995

         Volume
0       2610400
1      22914900
2      15052600
3      15071400
4      11118400
...         ...
5449  188180000
5450  290430000
5451  269900000
5452  181840000
5453  166410000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AMGN_ended_2021-09-25  1999-12-31        226.37  30.57  276.69      24.612

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    55.182    79.794   104.406   129.018    153.63   178.242   202.854

  markup_80 markup_90 markup_100
0   227.466   252.078     276.69
                   stock  start_date current_price minall  maxall each_markup  \
0  AMGN_ended_2021-09-25  1999-12-31        226.37  30.57  276.69      24.612

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    55.182    79.794   104.406   129.018    153.63   178.242   202.854

  markup_80 markup_90 markup_100
0   227.466   252.078     276.69
./ticker_data/ticker_data_2021-09-25 - Copy/AMHCW_ended_2021-09-25.csv
         Date  Open  High   Low  Close  Adj Close  Volume
0  2021-09-22  0.75  1.29  1.12   1.12       1.12   27009
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AMHCW_ended_2021-09-25  2021-09-22          1.12   1.12   1.29       0.017

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.137     1.154     1.171     1.188     1.205     1.222     1.239

  markup_80 markup_90 markup_100
0     1.256     1.273       1.29
                    stock  start_date current_price minall maxall each_markup  \
0  AMHCW_ended_2021-09-25  2021-09-22          1.12   1.12   1.29       0.017

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.137     1.154     1.171     1.188     1.205     1.222     1.239

  markup_80 markup_90 markup_100
0     1.256     1.273       1.29
./ticker_data/ticker_data_2021-09-25 - Copy/AMHC_ended_2021-09-25.csv
           Date  Open   High   Low  Close  Adj Close    Volume
0    2020-01-10  9.82   9.82  9.82   9.82       9.82    150000
1    2020-01-13  9.82   9.82  9.82   9.82       9.82    400000
2    2020-01-14  9.82   9.82  9.82   9.82       9.82         0
3    2020-01-17  9.82   9.82  9.82   9.82       9.82    100000
4    2020-01-22  9.86   9.86  9.85   9.85       9.85     90900
..          ...   ...    ...   ...    ...        ...       ...
329  2021-08-30  9.96   9.98  9.96   9.98       9.98   2450000
330  2021-08-31  9.97   9.97  9.97   9.97       9.97     90000
331  2021-09-01  9.97  10.01  9.97   9.99       9.99  30450000
332  2021-09-02  9.98   9.98  9.97   9.98       9.98   4250000
333  2021-09-03  9.98   9.99  9.97   9.99       9.99   5860000

[334 rows x 7 columns]
tolistdate: 0      2020-01-10
1      2020-01-13
2      2020-01-14
3      2020-01-17
4      2020-01-22
          ...
329    2021-08-30
330    2021-08-31
331    2021-09-01
332    2021-09-02
333    2021-09-03
Name: Date, Length: 334, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMHC_ended_2021-09-25  2020-01-10          9.99   9.45   10.5       0.105

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.555      9.66     9.765      9.87     9.975     10.08    10.185

  markup_80 markup_90 markup_100
0     10.29    10.395       10.5
                   stock  start_date current_price minall maxall each_markup  \
0  AMHC_ended_2021-09-25  2020-01-10          9.99   9.45   10.5       0.105

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.555      9.66     9.765      9.87     9.975     10.08    10.185

  markup_80 markup_90 markup_100
0     10.29    10.395       10.5
./ticker_data/ticker_data_2021-09-25 - Copy/AMKR_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  26.125000  28.250000  25.875000  28.250000  28.076715
1     2000-01-03  28.062500  28.750000  27.375000  28.500000  28.325182
2     2000-01-04  27.750000  27.937500  26.000000  26.187500  26.026867
3     2000-01-05  25.937500  27.000000  24.125000  26.875000  26.710150
4     2000-01-06  26.000000  26.250000  24.500000  24.687500  24.536068
...          ...        ...        ...        ...        ...        ...
5450  2021-08-30  27.719999  28.059999  27.389999  27.930000  27.930000
5451  2021-08-31  27.889999  27.980000  27.209999  27.469999  27.469999
5452  2021-09-01  27.639999  28.150000  27.270000  27.799999  27.799999
5453  2021-09-02  27.879999  28.420000  27.680000  28.230000  28.230000
5454  2021-09-03  28.299999  28.790001  28.150000  28.420000  28.420000

         Volume
0        366400
1        864800
2        323000
3        597400
4        433400
...         ...
5450   80690000
5451  134260000
5452   84820000
5453   73700000
5454   74260000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price minall   maxall  \
0  AMKR_ended_2021-09-25  1999-12-31         28.42   1.13  65.3125

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     6.41825   7.54825   13.9665   20.3847    26.803   33.2212   39.6395

  markup_70 markup_80 markup_90 markup_100
0   46.0577    52.476   58.8942    65.3125
                   stock  start_date current_price minall   maxall  \
0  AMKR_ended_2021-09-25  1999-12-31         28.42   1.13  65.3125

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     6.41825   7.54825   13.9665   20.3847    26.803   33.2212   39.6395

  markup_70 markup_80 markup_90 markup_100
0   46.0577    52.476   58.8942    65.3125
./ticker_data/ticker_data_2021-09-25 - Copy/AMNB_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  18.500000  18.500000  18.500000  18.500000   8.188849
1     2000-01-04  16.750000  17.500000  16.750000  16.750000   7.414225
2     2000-01-05  16.625000  16.625000  16.375000  16.375000   7.248236
3     2000-01-06  16.000000  16.125000  14.500000  15.500000   6.860926
4     2000-01-07  16.000000  16.625000  16.000000  16.625000   7.358899
...          ...        ...        ...        ...        ...        ...
5361  2021-08-30  34.980000  34.980000  33.730000  33.730000  33.730000
5362  2021-08-31  34.090000  34.180000  33.810001  34.180000  34.180000
5363  2021-09-01  34.209999  34.540001  33.700001  34.310001  34.310001
5364  2021-09-02  34.220001  34.340000  33.369999  33.820000  33.820000
5365  2021-09-03  33.880001  33.880001  33.400002  33.610001  33.610001

       Volume
0           0
1        2100
2        2800
3        5600
4        1800
...       ...
5361  1580000
5362  1490000
5363  1820000
5364  1470000
5365   760000

[5366 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-04
2       2000-01-05
3       2000-01-06
4       2000-01-07
           ...
5361    2021-08-30
5362    2021-08-31
5363    2021-09-01
5364    2021-09-02
5365    2021-09-03
Name: Date, Length: 5366, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMNB_ended_2021-09-25  1999-12-31         33.61      9     43         3.4

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      12.4      15.8      19.2      22.6        26      29.4      32.8

  markup_80 markup_90 markup_100
0      36.2      39.6         43
                   stock  start_date current_price minall maxall each_markup  \
0  AMNB_ended_2021-09-25  1999-12-31         33.61      9     43         3.4

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      12.4      15.8      19.2      22.6        26      29.4      32.8

  markup_80 markup_90 markup_100
0      36.2      39.6         43

./ticker_data/ticker_data_2021-09-25 - Copy/AMOT_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   1.000000   1.166667   1.000000   1.083333   1.012609
1     2000-01-03   1.166667   1.229167   1.083333   1.166667   1.090501
2     2000-01-04   1.166667   1.229167   1.125000   1.166667   1.090501
3     2000-01-05   1.166667   1.166667   1.083333   1.083333   1.012609
4     2000-01-06   1.166667   1.250000   1.166667   1.250000   1.168395
...          ...        ...        ...        ...        ...        ...
5402  2021-08-30  34.580002  34.830002  34.220001  34.389999  34.389999
5403  2021-08-31  34.209999  34.700001  34.009998  34.560001  34.560001
5404  2021-09-01  34.599998  34.869999  34.470001  34.779999  34.779999
5405  2021-09-02  34.900002  35.439999  34.700001  35.439999  35.439999
5406  2021-09-03  35.529999  35.820000  35.060001  35.480000  35.480000

       Volume
0        7500
1       29400
2       18200
3        9000
4       13200
...       ...
5402  2510000
5403  2620000
5404  2650000
5405  2530000
5406  1760000

[5407 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5402    2021-08-30
5403    2021-08-31
5404    2021-09-01
5405    2021-09-02
5406    2021-09-03
Name: Date, Length: 5407, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMOT_ended_2021-09-25  1999-12-31         35.48   0.78   38.1       3.732

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.512     8.244    11.976    15.708     19.44    23.172    26.904

  markup_80 markup_90 markup_100
0    30.636    34.368       38.1
                   stock  start_date current_price minall maxall each_markup  \
0  AMOT_ended_2021-09-25  1999-12-31         35.48   0.78   38.1       3.732

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.512     8.244    11.976    15.708     19.44    23.172    26.904

  markup_80 markup_90 markup_100
0    30.636    34.368       38.1
./ticker_data/ticker_data_2021-09-25 - Copy/AMPGW_ended_2021-09-25.csv
           Date  Open   High    Low  Close  Adj Close  Volume
0    2021-02-18  1.50  2.827  1.500  1.610      1.610  107700
1    2021-02-19  2.00  2.490  1.900  2.230      2.230   37700
2    2021-02-22  2.50  2.600  2.000  2.350      2.350   23600
3    2021-02-23  2.15  3.360  1.750  2.770      2.770   61200
4    2021-02-24  2.40  3.400  2.400  3.000      3.000   18900
..          ...   ...    ...    ...    ...        ...     ...
125  2021-08-30  1.46  1.460  1.460  1.460      1.460       0
126  2021-08-31  1.31  1.310  1.310  1.310      1.310   20000
127  2021-09-01  1.39  1.390  1.390  1.390      1.390   10000
128  2021-09-02  1.39  1.390  1.390  1.390      1.390       0
129  2021-09-03  1.79  1.790  1.315  1.315      1.315  320000

[130 rows x 7 columns]
tolistdate: 0      2021-02-18
1      2021-02-19
2      2021-02-22
3      2021-02-23
4      2021-02-24
          ...
125    2021-08-30
126    2021-08-31
127    2021-09-01
128    2021-09-02
129    2021-09-03
Name: Date, Length: 130, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AMPGW_ended_2021-09-25  2021-02-18         1.315   1.09  6.488      0.5398

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    1.6298    2.1696    2.7094    3.2492     3.789    4.3288    4.8686

  markup_80 markup_90 markup_100
0    5.4084    5.9482      6.488
                    stock  start_date current_price minall maxall each_markup  \
0  AMPGW_ended_2021-09-25  2021-02-18         1.315   1.09  6.488      0.5398

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    1.6298    2.1696    2.7094    3.2492     3.789    4.3288    4.8686

  markup_80 markup_90 markup_100
0    5.4084    5.9482      6.488
./ticker_data/ticker_data_2021-09-25 - Copy/AMPG_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close   Volume
0    2021-01-08  0.450  0.494  0.415  0.440      0.440   507100
1    2021-01-11  0.424  0.490  0.424  0.460      0.460   247600
2    2021-01-12  0.460  0.479  0.431  0.475      0.475   494800
3    2021-01-13  0.470  0.480  0.440  0.470      0.470   241800
4    2021-01-14  0.475  0.480  0.441  0.460      0.460   279200
..          ...    ...    ...    ...    ...        ...      ...
160  2021-08-30  3.850  3.910  3.750  3.760      3.760  5400000
161  2021-08-31  3.740  3.750  3.660  3.720      3.720  4660000
162  2021-09-01  3.740  3.880  3.610  3.660      3.660  8860000
163  2021-09-02  3.710  3.850  3.680  3.780      3.780  8490000
164  2021-09-03  3.770  3.850  3.700  3.820      3.820  3740000

[165 rows x 7 columns]
tolistdate: 0      2021-01-08
1      2021-01-11
2      2021-01-12
3      2021-01-13
4      2021-01-14
          ...
160    2021-08-30
161    2021-08-31
162    2021-09-01
163    2021-09-02
164    2021-09-03
Name: Date, Length: 165, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMPG_ended_2021-09-25  2021-01-08          3.82  0.353   19.8      1.9447

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.2977    4.2424    6.1871    8.1318   10.0765   12.0212   13.9659

  markup_80 markup_90 markup_100
0   15.9106   17.8553       19.8
                   stock  start_date current_price minall maxall each_markup  \
0  AMPG_ended_2021-09-25  2021-01-08          3.82  0.353   19.8      1.9447

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.2977    4.2424    6.1871    8.1318   10.0765   12.0212   13.9659

  markup_80 markup_90 markup_100
0   15.9106   17.8553       19.8
./ticker_data/ticker_data_2021-09-25 - Copy/AMPH_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2014-06-25   7.000000   8.950000   6.670000   8.750000   8.750000
1     2014-06-26   9.000000  11.070000   8.800000  10.010000  10.010000
2     2014-06-27  10.250000  10.680000   9.960000  10.500000  10.500000
3     2014-06-30  10.000000  10.960000   9.750000  10.010000  10.010000
4     2014-07-01   9.900000  10.390000   9.490000   9.750000   9.750000
...          ...        ...        ...        ...        ...        ...
1807  2021-08-30  19.270000  19.490000  19.270000  19.379999  19.379999
1808  2021-08-31  19.309999  19.670000  19.309999  19.660000  19.660000
1809  2021-09-01  19.580000  19.830000  19.570000  19.740000  19.740000
1810  2021-09-02  19.700001  19.940001  19.420000  19.530001  19.530001
1811  2021-09-03  19.520000  19.520000  19.230000  19.270000  19.270000

        Volume
0      4159700
1      1412900
2       395600
3       183800
4       204800
...        ...
1807  15630000
1808  17620000
1809  15630000
1810  25300000
1811  12570000

[1812 rows x 7 columns]
tolistdate: 0       2014-06-25
1       2014-06-26
2       2014-06-27
3       2014-06-30
4       2014-07-01
           ...
1807    2021-08-30
1808    2021-08-31
1809    2021-09-01
1810    2021-09-02
1811    2021-09-03
Name: Date, Length: 1812, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMPH_ended_2021-09-25  2014-06-25         19.27   6.67  25.43       1.876

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.546    10.422    12.298    14.174     16.05    17.926    19.802

  markup_80 markup_90 markup_100
0    21.678    23.554      25.43
                   stock  start_date current_price minall maxall each_markup  \
0  AMPH_ended_2021-09-25  2014-06-25         19.27   6.67  25.43       1.876

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.546    10.422    12.298    14.174     16.05    17.926    19.802

  markup_80 markup_90 markup_100
0    21.678    23.554      25.43
./ticker_data/ticker_data_2021-09-25 - Copy/AMRB_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   6.599184   6.599184   6.599184   6.599184   4.575317
1     2000-01-03   6.711990   6.711990   6.711990   6.711990   4.653526
2     2000-01-04   6.768394   6.768394   6.768394   6.768394   4.692631
3     2000-01-05   6.768394   7.219620   6.768394   6.768394   4.777352
4     2000-01-06   6.768394   6.768394   6.768394   6.768394   4.777352
...          ...        ...        ...        ...        ...        ...
5204  2021-07-30  19.500000  19.920000  19.500000  19.850000  19.850000
5205  2021-08-03  19.809999  20.010000  19.799999  20.000000  20.000000
5206  2021-08-04  19.980000  20.459999  19.980000  20.070000  20.070000
5207  2021-08-05  20.340000  20.500000  20.330000  20.500000  20.500000
5208  2021-08-06  20.500000  21.400000  20.500000  20.910000  20.910000

        Volume
0            0
1          300
2         1600
3         1000
4            0
...        ...
5204      3600
5205      2100
5206    170000
5207    690000
5208  11510000

[5209 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5204    2021-07-30
5205    2021-08-03
5206    2021-08-04
5207    2021-08-05
5208    2021-08-06
Name: Date, Length: 5209, dtype: object
                   stock  start_date current_price minall   maxall  \
0  AMRB_ended_2021-09-25  1999-12-31         20.91    4.5  25.0513

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     2.05513   6.55513   8.61026   10.6654   12.7205   14.7756   16.8308

  markup_70 markup_80 markup_90 markup_100
0   18.8859    20.941   22.9962    25.0513
                   stock  start_date current_price minall   maxall  \
0  AMRB_ended_2021-09-25  1999-12-31         20.91    4.5  25.0513

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     2.05513   6.55513   8.61026   10.6654   12.7205   14.7756   16.8308

  markup_70 markup_80 markup_90 markup_100
0   18.8859    20.941   22.9962    25.0513
./ticker_data/ticker_data_2021-09-25 - Copy/AMRK_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2014-03-17  12.490000  13.690000  12.490000  13.300000  11.382409
1     2014-03-18  13.300000  14.900000  13.250000  14.250000  12.195439
2     2014-03-19  14.150000  14.400000  13.850000  14.000000  11.981483
3     2014-03-20  14.000000  14.000000  13.801000  14.000000  11.981483
4     2014-03-21  13.900000  13.900000  13.000000  13.240000  11.331060
...          ...        ...        ...        ...        ...        ...
1876  2021-08-30  48.400002  49.590000  48.070000  48.580002  48.580002
1877  2021-08-31  48.509998  49.490002  48.310001  48.509998  48.509998
1878  2021-09-01  48.790001  49.150002  48.044998  48.959999  48.959999
1879  2021-09-02  49.099998  49.599998  48.560001  49.410000  49.410000
1880  2021-09-03  49.189999  49.896000  48.605000  49.560001  49.560001

        Volume
0        34100
1        67800
2        12800
3         4100
4         5300
...        ...
1876  10460000
1877   2860000
1878   3890000
1879   4740000
1880   7590000

[1881 rows x 7 columns]
tolistdate: 0       2014-03-17
1       2014-03-18
2       2014-03-19
3       2014-03-20
4       2014-03-21
           ...
1876    2021-08-30
1877    2021-08-31
1878    2021-09-01
1879    2021-09-02
1880    2021-09-03
Name: Date, Length: 1881, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AMRK_ended_2021-09-25  2014-03-17         49.56   7.47  57.628      5.0158

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   12.4858   17.5016   22.5174   27.5332    32.549   37.5648   42.5806

  markup_80 markup_90 markup_100
0   47.5964   52.6122     57.628
                   stock  start_date current_price minall  maxall each_markup  \
0  AMRK_ended_2021-09-25  2014-03-17         49.56   7.47  57.628      5.0158

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   12.4858   17.5016   22.5174   27.5332    32.549   37.5648   42.5806

  markup_80 markup_90 markup_100
0   47.5964   52.6122     57.628
./ticker_data/ticker_data_2021-09-25 - Copy/AMRN_ended_2021-09-25.csv
            Date     Open     High    Low  Close  Adj Close     Volume
0     1999-12-31  47.5000  47.5000  47.50  47.50      47.50          0
1     2000-01-03  47.1875  47.1875  45.00  45.00      45.00        500
2     2000-01-04  43.7500  46.2500  43.75  43.75      43.75        500
3     2000-01-05  43.7500  43.7500  43.75  43.75      43.75          0
4     2000-01-06  43.7500  43.7500  43.75  43.75      43.75        200
...          ...      ...      ...    ...    ...        ...        ...
5372  2021-08-30   5.6000   5.6800   5.48   5.54       5.54  325220000
5373  2021-08-31   5.5400   5.6800   5.41   5.44       5.44  357030000
5374  2021-09-01   5.4800   5.4800   5.33   5.43       5.43  260300000
5375  2021-09-02   5.4200   5.4900   5.35   5.40       5.40  182040000
5376  2021-09-03   5.3600   5.3900   5.20   5.29       5.29  281250000

[5377 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5372    2021-08-30
5373    2021-08-31
5374    2021-09-01
5375    2021-09-02
5376    2021-09-03
Name: Date, Length: 5377, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMRN_ended_2021-09-25  1999-12-31          5.29   0.46  288.4      28.794

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    29.254    58.048    86.842   115.636    144.43   173.224   202.018

  markup_80 markup_90 markup_100
0   230.812   259.606      288.4
                   stock  start_date current_price minall maxall each_markup  \
0  AMRN_ended_2021-09-25  1999-12-31          5.29   0.46  288.4      28.794

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    29.254    58.048    86.842   115.636    144.43   173.224   202.018

  markup_80 markup_90 markup_100
0   230.812   259.606      288.4
./ticker_data/ticker_data_2021-09-25 - Copy/AMRS_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2010-09-28  247.500000  261.600006  247.199997  247.500000  247.500000
1     2010-09-29  247.500000  253.949997  247.500000  252.750000  252.750000
2     2010-09-30  254.550003  260.250000  252.300003  258.750000  258.750000
3     2010-10-01  258.750000  270.000000  253.649994  258.450012  258.450012
4     2010-10-04  256.500000  259.950012  255.000000  255.899994  255.899994
...          ...         ...         ...         ...         ...         ...
2763  2021-09-20   13.200000   13.730000   12.670000   12.880000   12.880000
2764  2021-09-21   12.990000   13.490000   12.970000   13.480000   13.480000
2765  2021-09-22   13.460000   13.580000   13.060000   13.230000   13.230000
2766  2021-09-23   13.370000   13.600000   12.990000   13.510000   13.510000
2767  2021-09-24   13.650000   14.550000   13.660000   14.260000   14.260000

       Volume
0      158973
1       19200
2       21133
3       13193
4        8220
...       ...
2763  3102400
2764  1900800
2765  1936900
2766  3075800
2767  3039526

[2768 rows x 7 columns]
tolistdate: 0       2010-09-28
1       2010-09-29
2       2010-09-30
3       2010-10-01
4       2010-10-04
           ...
2763    2021-09-20
2764    2021-09-21
2765    2021-09-22
2766    2021-09-23
2767    2021-09-24
Name: Date, Length: 2768, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AMRS_ended_2021-09-25  2010-09-28         14.26    1.4  509.85      50.845

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    52.245    103.09   153.935    204.78   255.625    306.47   357.315

  markup_80 markup_90 markup_100
0    408.16   459.005     509.85
                   stock  start_date current_price minall  maxall each_markup  \
0  AMRS_ended_2021-09-25  2010-09-28         14.26    1.4  509.85      50.845

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    52.245    103.09   153.935    204.78   255.625    306.47   357.315

  markup_80 markup_90 markup_100
0    408.16   459.005     509.85

./ticker_data/ticker_data_2021-09-25 - Copy/AMSC_ended_2021-09-25.csv
            Date     Open     High      Low    Close  Adj Close     Volume
0     1999-12-31  276.250  288.750  275.625  280.000    280.000       7400
1     2000-01-03  286.250  328.750  283.750  295.625    295.625      49000
2     2000-01-04  286.250  297.500  275.000  280.000    280.000      15600
3     2000-01-05  280.625  284.375  262.500  278.125    278.125      24000
4     2000-01-06  273.750  283.750  273.750  278.125    278.125       6500
...          ...      ...      ...      ...      ...        ...        ...
5450  2021-08-30   12.520   12.540   12.270   12.340     12.340   14140000
5451  2021-08-31   13.100   15.370   13.100   14.900     14.900  188210000
5452  2021-09-01   14.770   14.870   13.900   13.990     13.990   66470000
5453  2021-09-02   14.050   14.290   13.870   14.010     14.010   27650000
5454  2021-09-03   13.980   14.420   13.950   14.170     14.170   20060000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AMSC_ended_2021-09-25  1999-12-31         14.17   2.89  751.25      74.836

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    77.726   152.562   227.398   302.234    377.07   451.906   526.742

  markup_80 markup_90 markup_100
0   601.578   676.414     751.25
                   stock  start_date current_price minall  maxall each_markup  \
0  AMSC_ended_2021-09-25  1999-12-31         14.17   2.89  751.25      74.836

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    77.726   152.562   227.398   302.234    377.07   451.906   526.742

  markup_80 markup_90 markup_100
0   601.578   676.414     751.25
./ticker_data/ticker_data_2021-09-25 - Copy/AMSF_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2005-11-18   9.020000   9.170000   8.120000   9.000000   5.565519
1     2005-11-21   9.080000   9.400000   8.830000   9.300000   5.751037
2     2005-11-22   8.920000   9.200000   8.920000   9.190000   5.683013
3     2005-11-23   9.210000   9.280000   9.010000   9.220000   5.701565
4     2005-11-25   9.220000   9.500000   9.020000   9.500000   5.874714
...          ...        ...        ...        ...        ...        ...
3969  2021-08-30  57.740002  57.810001  56.730000  57.490002  57.490002
3970  2021-08-31  57.340000  57.900002  57.340000  57.549999  57.549999
3971  2021-09-01  57.779999  58.070000  56.700001  57.369999  57.369999
3972  2021-09-02  57.480000  57.779999  56.980000  57.220001  57.220001
3973  2021-09-03  57.520000  57.529999  56.099998  57.139999  57.139999

        Volume
0      3272500
1       695900
2       329400
3       111800
4        39000
...        ...
3969  10510000
3970   5520000
3971   4920000
3972   5580000
3973   5710000

[3974 rows x 7 columns]
tolistdate: 0       2005-11-18
1       2005-11-21
2       2005-11-22
3       2005-11-23
4       2005-11-25
           ...
3969    2021-08-30
3970    2021-08-31
3971    2021-09-01
3972    2021-09-02
3973    2021-09-03
Name: Date, Length: 3974, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMSF_ended_2021-09-25  2005-11-18         57.14   8.12  80.65       7.253

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.373    22.626    29.879    37.132    44.385    51.638    58.891

  markup_80 markup_90 markup_100
0    66.144    73.397      80.65
                   stock  start_date current_price minall maxall each_markup  \
0  AMSF_ended_2021-09-25  2005-11-18         57.14   8.12  80.65       7.253

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.373    22.626    29.879    37.132    44.385    51.638    58.891

  markup_80 markup_90 markup_100
0    66.144    73.397      80.65
./ticker_data/ticker_data_2021-09-25 - Copy/AMST_ended_2021-09-25.csv
           Date  Open   High    Low  Close  Adj Close    Volume
0    2020-09-25  4.95  6.580  4.550   5.22       5.22   2115600
1    2020-09-28  5.01  5.179  4.205   4.79       4.79    381500
2    2020-09-29  4.75  4.770  4.300   4.50       4.50    149800
3    2020-09-30  4.59  4.590  4.250   4.40       4.40     84500
4    2020-10-01  4.69  4.690  4.260   4.35       4.35     79400
..          ...   ...    ...    ...    ...        ...       ...
233  2021-08-30  1.99  2.080  1.940   2.04       2.04  14110000
234  2021-08-31  2.05  2.060  1.920   2.01       2.01  22980000
235  2021-09-01  2.00  2.050  1.970   1.97       1.97   4990000
236  2021-09-02  2.00  2.044  1.980   1.99       1.99  16050000
237  2021-09-03  2.00  2.040  1.973   2.01       2.01   5790000

[238 rows x 7 columns]
tolistdate: 0      2020-09-25
1      2020-09-28
2      2020-09-29
3      2020-09-30
4      2020-10-01
          ...
233    2021-08-30
234    2021-08-31
235    2021-09-01
236    2021-09-02
237    2021-09-03
Name: Date, Length: 238, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMST_ended_2021-09-25  2020-09-25          2.01   1.67   9.06       0.739

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.409     3.148     3.887     4.626     5.365     6.104     6.843

  markup_80 markup_90 markup_100
0     7.582     8.321       9.06
                   stock  start_date current_price minall maxall each_markup  \
0  AMST_ended_2021-09-25  2020-09-25          2.01   1.67   9.06       0.739

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.409     3.148     3.887     4.626     5.365     6.104     6.843

  markup_80 markup_90 markup_100
0     7.582     8.321       9.06
./ticker_data/ticker_data_2021-09-25 - Copy/AMSWA_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  10.375000  10.875000   9.750000  10.250000   4.419317
1     2000-01-03  10.375000  10.625000   8.000000   8.812500   3.799535
2     2000-01-04   8.000000   9.000000   7.562500   8.500000   3.664800
3     2000-01-05   8.250000   8.437500   7.312500   8.250000   3.557011
4     2000-01-06   8.250000   9.250000   7.750000   8.500000   3.664800
...          ...        ...        ...        ...        ...        ...
5449  2021-08-30  24.660000  24.719999  24.129999  24.480000  24.480000
5450  2021-08-31  24.480000  25.570000  24.360001  25.370001  25.370001
5451  2021-09-01  25.490000  25.530001  25.000000  25.500000  25.500000
5452  2021-09-02  25.540001  25.980000  25.190001  25.280001  25.280001
5453  2021-09-03  25.370001  25.820000  25.340000  25.690001  25.690001

        Volume
0       478200
1       551100
2       321500
3       214000
4       202700
...        ...
5449  11520000
5450  20850000
5451   8190000
5452   9380000
5453   7320000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AMSWA_ended_2021-09-25  1999-12-31         25.69   1.05  28.45        2.74

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      3.79      6.53      9.27     12.01     14.75     17.49     20.23

  markup_80 markup_90 markup_100
0     22.97     25.71      28.45
                    stock  start_date current_price minall maxall each_markup  \
0  AMSWA_ended_2021-09-25  1999-12-31         25.69   1.05  28.45        2.74

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      3.79      6.53      9.27     12.01     14.75     17.49     20.23

  markup_80 markup_90 markup_100
0     22.97     25.71      28.45
./ticker_data/ticker_data_2021-09-25 - Copy/AMTBB_ended_2021-09-25.csv
           Date       Open       High    Low      Close  Adj Close   Volume
0    2018-10-18  21.000000  25.650000  18.90  25.500000  25.500000     2700
1    2018-10-19  18.600000  26.430000  18.60  26.430000  26.430000      500
2    2018-10-22  26.100000  26.100000  25.50  25.500000  25.500000      100
3    2018-10-23  24.750000  24.750000  24.60  24.600000  24.600000      200
4    2018-10-24  26.000000  26.000000  26.00  26.000000  26.000000      400
..          ...        ...        ...    ...        ...        ...      ...
691  2021-08-30  21.760000  22.770000  21.50  22.230000  22.230000   550000
692  2021-08-31  22.250000  22.500000  22.15  22.200001  22.200001   930000
693  2021-09-01  21.500000  22.200001  21.50  22.049999  22.049999  1730000
694  2021-09-02  22.000000  22.000000  21.50  21.799999  21.799999  1540000
695  2021-09-03  21.190001  21.190001  21.15  21.150000  21.150000    50000

[696 rows x 7 columns]
tolistdate: 0      2018-10-18
1      2018-10-19
2      2018-10-22
3      2018-10-23
4      2018-10-24
          ...
691    2021-08-30
692    2021-08-31
693    2021-09-01
694    2021-09-02
695    2021-09-03
Name: Date, Length: 696, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AMTBB_ended_2021-09-25  2018-10-18         21.15   6.84  26.43       1.959

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.799    10.758    12.717    14.676    16.635    18.594    20.553

  markup_80 markup_90 markup_100
0    22.512    24.471      26.43
                    stock  start_date current_price minall maxall each_markup  \
0  AMTBB_ended_2021-09-25  2018-10-18         21.15   6.84  26.43       1.959

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.799    10.758    12.717    14.676    16.635    18.594    20.553

  markup_80 markup_90 markup_100
0    22.512    24.471      26.43
./ticker_data/ticker_data_2021-09-25 - Copy/AMTB_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-10-18  30.000000  30.000000  30.000000  30.000000  30.000000
1    2018-10-19  26.250000  26.250000  26.250000  26.250000  26.250000
2    2018-10-22  26.250000  26.250000  26.250000  26.250000  26.250000
3    2018-10-24  29.700001  29.700001  29.700001  29.700001  29.700001
4    2018-10-25  27.100000  27.100000  27.100000  27.100000  27.100000
..          ...        ...        ...        ...        ...        ...
718  2021-08-30  25.000000  26.910000  25.000000  26.540001  26.540001
719  2021-08-31  26.459999  27.110001  26.379999  26.570000  26.570000
720  2021-09-01  26.760000  26.870001  26.200001  26.469999  26.469999
721  2021-09-02  26.660000  26.660000  26.200001  26.240000  26.240000
722  2021-09-03  26.260000  27.459999  26.049999  26.309999  26.309999

       Volume
0         200
1         200
2           0
3         100
4         300
..        ...
718  19920000
719   5560000
720   4600000
721   3570000
722   4250000

[723 rows x 7 columns]
tolistdate: 0      2018-10-18
1      2018-10-19
2      2018-10-22
3      2018-10-24
4      2018-10-25
          ...
718    2021-08-30
719    2021-08-31
720    2021-09-01
721    2021-09-02
722    2021-09-03
Name: Date, Length: 723, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMTB_ended_2021-09-25  2018-10-18         26.31   9.01     30       2.099

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.109    13.208    15.307    17.406    19.505    21.604    23.703

  markup_80 markup_90 markup_100
0    25.802    27.901         30
                   stock  start_date current_price minall maxall each_markup  \
0  AMTB_ended_2021-09-25  2018-10-18         26.31   9.01     30       2.099

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.109    13.208    15.307    17.406    19.505    21.604    23.703

  markup_80 markup_90 markup_100
0    25.802    27.901         30
./ticker_data/ticker_data_2021-09-25 - Copy/AMTI_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-06-05  25.510000  26.000000  17.150000  17.980000  17.980000
1    2020-06-08  18.059999  21.719999  18.059999  18.990000  18.990000
2    2020-06-09  18.209999  21.490000  17.045000  20.490000  20.490000
3    2020-06-10  20.580000  25.980000  19.600000  25.480000  25.480000
4    2020-06-11  26.000000  27.809999  23.330000  24.040001  24.040001
..          ...        ...        ...        ...        ...        ...
310  2021-08-30  31.170000  31.490000  29.780001  29.980000  29.980000
311  2021-08-31  30.190001  31.249001  29.260000  30.070000  30.070000
312  2021-09-01  30.490000  32.029999  29.975000  31.110001  31.110001
313  2021-09-02  31.459999  33.279999  31.129999  32.250000  32.250000
314  2021-09-03  32.110001  33.000000  29.010000  30.059999  30.059999

       Volume
0     3479300
1      917600
2     1124600
3      697600
4      531900
..        ...
310  14270000
311  16950000
312  14410000
313   9810000
314  17660000

[315 rows x 7 columns]
tolistdate: 0      2020-06-05
1      2020-06-08
2      2020-06-09
3      2020-06-10
4      2020-06-11
          ...
310    2021-08-30
311    2021-08-31
312    2021-09-01
313    2021-09-02
314    2021-09-03
Name: Date, Length: 315, dtype: object
                   stock  start_date current_price  minall maxall each_markup  \
0  AMTI_ended_2021-09-25  2020-06-05         30.06  17.045  78.22      6.1175

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   23.1625     29.28   35.3975    41.515   47.6325     53.75   59.8675

  markup_80 markup_90 markup_100
0    65.985   72.1025      78.22
                   stock  start_date current_price  minall maxall each_markup  \
0  AMTI_ended_2021-09-25  2020-06-05         30.06  17.045  78.22      6.1175

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   23.1625     29.28   35.3975    41.515   47.6325     53.75   59.8675

  markup_80 markup_90 markup_100
0    65.985   72.1025      78.22
./ticker_data/ticker_data_2021-09-25 - Copy/AMTX_ended_2021-09-25.csv
            Date   Open    High     Low   Close  Adj Close     Volume
0     2014-05-15   5.72   6.000   5.720   5.720      5.720       8600
1     2014-05-16   5.72   6.400   5.000   5.825      5.825      16400
2     2014-05-19   5.82   5.990   5.010   5.500      5.500      10100
3     2014-05-20   5.02   5.240   5.000   5.240      5.240       3800
4     2014-05-21   5.00   5.000   5.000   5.000      5.000       3100
...          ...    ...     ...     ...     ...        ...        ...
1836  2021-08-30  10.75  10.870  10.025  10.230     10.230   38110000
1837  2021-08-31  10.30  11.290  10.250  11.120     11.120   73890000
1838  2021-09-01  11.10  12.040  11.060  11.750     11.750  103550000
1839  2021-09-02  11.78  12.531  11.780  12.110     12.110  100960000
1840  2021-09-03  12.11  12.290  11.500  12.090     12.090   58010000

[1841 rows x 7 columns]
tolistdate: 0       2014-05-15
1       2014-05-16
2       2014-05-19
3       2014-05-20
4       2014-05-21
           ...
1836    2021-08-30
1837    2021-08-31
1838    2021-09-01
1839    2021-09-02
1840    2021-09-03
Name: Date, Length: 1841, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMTX_ended_2021-09-25  2014-05-15         12.09  0.371  27.44      2.7069

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    3.0779    5.7848    8.4917   11.1986   13.9055   16.6124   19.3193

  markup_80 markup_90 markup_100
0   22.0262   24.7331      27.44
                   stock  start_date current_price minall maxall each_markup  \
0  AMTX_ended_2021-09-25  2014-05-15         12.09  0.371  27.44      2.7069

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    3.0779    5.7848    8.4917   11.1986   13.9055   16.6124   19.3193

  markup_80 markup_90 markup_100
0   22.0262   24.7331      27.44
./ticker_data/ticker_data_2021-09-25 - Copy/AMWD_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  12.500000  12.500000  11.750000  12.125000  10.793589
1     2000-01-03  12.000000  12.218750  11.750000  11.750000  10.459764
2     2000-01-04  11.750000  12.125000  11.625000  11.625000  10.348492
3     2000-01-05  11.531250  12.000000  11.531250  11.812500  10.515404
4     2000-01-06  12.125000  12.125000  11.812500  12.000000  10.682312
...          ...        ...        ...        ...        ...        ...
5450  2021-08-30  82.500000  82.500000  80.150002  80.400002  80.400002
5451  2021-08-31  69.800003  73.730003  67.419998  70.459999  70.459999
5452  2021-09-01  70.769997  71.389999  68.559998  69.910004  69.910004
5453  2021-09-02  69.919998  70.500000  69.629997  69.900002  69.900002
5454  2021-09-03  69.540001  70.019997  68.269997  69.290001  69.290001

          Volume
0        41000.0
1        39200.0
2        31200.0
3        11600.0
4        16000.0
...          ...
5450  10960000.0
5451  78410000.0
5452  28780000.0
5453  17680000.0
5454  11360000.0

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price  minall  maxall  \
0  AMWD_ended_2021-09-25  1999-12-31         69.29  7.0625  148.44

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     14.1378   21.2003    35.338   49.4758   63.6135   77.7513    91.889

  markup_70 markup_80 markup_90 markup_100
0   106.027   120.165   134.302     148.44
                   stock  start_date current_price  minall  maxall  \
0  AMWD_ended_2021-09-25  1999-12-31         69.29  7.0625  148.44

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     14.1378   21.2003    35.338   49.4758   63.6135   77.7513    91.889

  markup_70 markup_80 markup_90 markup_100

0   106.027   120.165   134.302     148.44
./ticker_data/ticker_data_2021-09-25 - Copy/AMYT_ended_2021-09-25.csv
           Date   Open    High     Low   Close  Adj Close    Volume
0    2020-07-08  14.26  15.500  10.245  11.250     11.250     38000
1    2020-07-09  12.49  12.490  11.000  11.000     11.000     63200
2    2020-07-10  10.35  11.500  10.350  11.075     11.075      4700
3    2020-07-13  11.15  11.490  10.668  11.490     11.490      5100
4    2020-07-14  11.38  12.250  11.000  11.500     11.500      2800
..          ...    ...     ...     ...     ...        ...       ...
288  2021-08-30  11.20  11.400  11.120  11.200     11.200   6840000
289  2021-08-31  11.10  11.350  11.080  11.100     11.100   6440000
290  2021-09-01  11.09  11.315  11.030  11.180     11.180   5650000
291  2021-09-02  11.12  11.190  10.910  10.990     10.990   5490000
292  2021-09-03  11.10  11.100  10.710  10.900     10.900  11380000

[293 rows x 7 columns]
tolistdate: 0      2020-07-08
1      2020-07-09
2      2020-07-10
3      2020-07-13
4      2020-07-14
          ...
288    2021-08-30
289    2021-08-31
290    2021-09-01
291    2021-09-02
292    2021-09-03
Name: Date, Length: 293, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AMYT_ended_2021-09-25  2020-07-08          10.9   9.55   15.5       0.595

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.145     10.74    11.335     11.93    12.525     13.12    13.715

  markup_80 markup_90 markup_100
0     14.31    14.905       15.5
                   stock  start_date current_price minall maxall each_markup  \
0  AMYT_ended_2021-09-25  2020-07-08          10.9   9.55   15.5       0.595

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.145     10.74    11.335     11.93    12.525     13.12    13.715

  markup_80 markup_90 markup_100
0     14.31    14.905       15.5
./ticker_data/ticker_data_2021-09-25 - Copy/AMZN_ended_2021-09-25.csv
            Date         Open         High          Low        Close  \
0     1999-12-31    79.312500    79.375000    76.000000    76.125000
1     2000-01-03    81.500000    89.562500    79.046875    89.375000
2     2000-01-04    85.375000    91.500000    81.750000    81.937500
3     2000-01-05    70.500000    75.125000    68.000000    69.750000
4     2000-01-06    71.312500    72.687500    64.000000    65.562500
...          ...          ...          ...          ...          ...
5450  2021-08-30  3357.429932  3445.000000  3355.219971  3421.570068
5451  2021-08-31  3424.800049  3472.580078  3395.590088  3470.790039
5452  2021-09-01  3496.399902  3527.000000  3475.239990  3479.000000
5453  2021-09-02  3494.760010  3511.959961  3455.000000  3463.120117
5454  2021-09-03  3452.000000  3482.669922  3436.439941  3478.050049

        Adj Close     Volume
0       76.125000    7270700
1       89.375000   16117600
2       81.937500   17487400
3       69.750000   38457400
4       65.562500   18752000
...           ...        ...
5450  3421.570068  319220000
5451  3470.790039  435110000
5452  3479.000000  362990000
5453  3463.120117  292560000
5454  3478.050049  257570000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price minall   maxall  \
0  AMZN_ended_2021-09-25  1999-12-31       3478.05   5.51  3773.08

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     376.757   382.267   759.024   1135.78   1512.54    1889.3   2266.05

  markup_70 markup_80 markup_90 markup_100
0   2642.81   3019.57   3396.32    3773.08
                   stock  start_date current_price minall   maxall  \
0  AMZN_ended_2021-09-25  1999-12-31       3478.05   5.51  3773.08

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     376.757   382.267   759.024   1135.78   1512.54    1889.3   2266.05

  markup_70 markup_80 markup_90 markup_100
0   2642.81   3019.57   3396.32    3773.08
./ticker_data/ticker_data_2021-09-25 - Copy/ANAB_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2017-01-26  16.000000  17.719999  15.170000  17.000000  17.000000
1     2017-01-27  16.809999  18.350000  16.379999  17.530001  17.530001
2     2017-01-30  17.160000  17.709999  17.049999  17.160000  17.160000
3     2017-01-31  17.049999  17.110001  16.799999  16.950001  16.950001
4     2017-02-01  17.260000  17.260000  16.590000  16.620001  16.620001
...          ...        ...        ...        ...        ...        ...
1155  2021-08-30  25.510000  26.030001  24.959999  24.990000  24.990000
1156  2021-08-31  25.160000  25.660000  25.010000  25.610001  25.610001
1157  2021-09-01  25.559999  26.260000  25.350000  25.930000  25.930000
1158  2021-09-02  26.160000  26.430000  25.740000  26.290001  26.290001
1159  2021-09-03  26.430000  26.950001  25.150000  26.799999  26.799999

        Volume
0      3318300
1       264100
2        86900
3        51600
4       102500
...        ...
1155  10240000
1156   9090000
1157  12670000
1158  12310000
1159  15610000

[1160 rows x 7 columns]
tolistdate: 0       2017-01-26
1       2017-01-27
2       2017-01-30
3       2017-01-31
4       2017-02-01
           ...
1155    2021-08-30
1156    2021-08-31
1157    2021-09-01
1158    2021-09-02
1159    2021-09-03
Name: Date, Length: 1160, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ANAB_ended_2021-09-25  2017-01-26          26.8     10    134        12.4

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      22.4      34.8      47.2      59.6        72      84.4      96.8

  markup_80 markup_90 markup_100
0     109.2     121.6        134
                   stock  start_date current_price minall maxall each_markup  \
0  ANAB_ended_2021-09-25  2017-01-26          26.8     10    134        12.4

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      22.4      34.8      47.2      59.6        72      84.4      96.8

  markup_80 markup_90 markup_100
0     109.2     121.6        134
./ticker_data/ticker_data_2021-09-25 - Copy/ANAT_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31   62.000000   64.000000   62.000000   63.750000   30.864439
1     2000-01-03   64.000000   65.000000   63.000000   64.000000   30.985483
2     2000-01-04   63.000000   63.000000   62.250000   62.250000   30.138214
3     2000-01-05   62.500000   63.250000   62.125000   62.125000   30.077688
4     2000-01-06   62.750000   63.500000   62.250000   63.500000   30.743404
...          ...         ...         ...         ...         ...         ...
5449  2021-08-30  192.639999  193.119995  191.520004  191.860001  191.860001
5450  2021-08-31  192.449997  192.750000  191.750000  192.500000  192.500000
5451  2021-09-01  192.789993  195.889999  192.000000  193.520004  193.520004
5452  2021-09-02  193.919998  194.559998  193.369995  194.460007  194.460007
5453  2021-09-03  193.940002  195.050003  191.050003  191.600006  191.600006

        Volume
0         5800
1         7400
2         3400
3         5000
4        10100
...        ...
5449   5390000
5450  14060000
5451  14490000
5452  12000000
5453  10930000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ANAT_ended_2021-09-25  1999-12-31         191.6  33.74  195.89      16.215

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    49.955     66.17    82.385      98.6   114.815    131.03   147.245

  markup_80 markup_90 markup_100
0    163.46   179.675     195.89
                   stock  start_date current_price minall  maxall each_markup  \
0  ANAT_ended_2021-09-25  1999-12-31         191.6  33.74  195.89      16.215

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    49.955     66.17    82.385      98.6   114.815    131.03   147.245

  markup_80 markup_90 markup_100
0    163.46   179.675     195.89
./ticker_data/ticker_data_2021-09-25 - Copy/ANDE_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   2.645833   2.750000   2.625000   2.750000   1.903497
1     2000-01-03   2.666667   2.729167   2.666667   2.729167   1.889077
2     2000-01-04   2.729167   2.729167   2.500000   2.500000   1.730452
3     2000-01-05   2.500000   2.562500   2.500000   2.562500   1.773713
4     2000-01-06   2.541667   2.562500   2.541667   2.562500   1.773713
...          ...        ...        ...        ...        ...        ...
5455  2021-09-20  28.750000  28.889999  28.160000  28.600000  28.600000
5456  2021-09-21  28.750000  28.969999  28.469999  28.770000  28.770000
5457  2021-09-22  29.100000  29.299999  28.760000  28.790001  28.790001
5458  2021-09-23  29.010000  29.850000  29.010000  29.820000  29.820000
5459  2021-09-24  29.620001  30.420000  29.620001  30.100000  30.100000

      Volume
0      74100
1       2400
2      36600
3      11400
4        900
...      ...
5455  132100
5456  100100
5457   73900
5458  104600
5459   30536

[5460 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5455    2021-09-20
5456    2021-09-21
5457    2021-09-22
5458    2021-09-23
5459    2021-09-24
Name: Date, Length: 5460, dtype: object
                   stock  start_date current_price   minall maxall  \
0  ANDE_ended_2021-09-25  1999-12-31          30.1  2.29167  69.93

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     6.76383    9.0555   15.8193   22.5832    29.347   36.1108   42.8747

  markup_70 markup_80 markup_90 markup_100
0   49.6385   56.4023   63.1662      69.93
                   stock  start_date current_price   minall maxall  \
0  ANDE_ended_2021-09-25  1999-12-31          30.1  2.29167  69.93

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     6.76383    9.0555   15.8193   22.5832    29.347   36.1108   42.8747

  markup_70 markup_80 markup_90 markup_100
0   49.6385   56.4023   63.1662      69.93
./ticker_data/ticker_data_2021-09-25 - Copy/ANEB_ended_2021-09-25.csv
          Date   Open   High   Low  Close  Adj Close   Volume
0   2021-05-07  7.480  7.480  6.72   7.10       7.10  1314800
1   2021-05-10  7.000  7.200  7.00   7.05       7.05   242400
2   2021-05-11  7.000  7.100  7.00   7.08       7.08   146500
3   2021-05-12  7.000  7.090  6.97   7.00       7.00    47800
4   2021-05-13  7.007  7.030  7.00   7.00       7.00    12800
..         ...    ...    ...   ...    ...        ...      ...
78  2021-08-30  6.950  6.990  6.95   6.99       6.99   100000
79  2021-08-31  6.750  6.750  6.75   6.75       6.75    60000
80  2021-09-01  6.900  6.900  6.90   6.90       6.90    40000
81  2021-09-02  6.900  6.900  6.90   6.90       6.90        0
82  2021-09-03  6.823  6.823  6.50   6.75       6.75   890000

[83 rows x 7 columns]
tolistdate: 0     2021-05-07
1     2021-05-10
2     2021-05-11
3     2021-05-12
4     2021-05-13
         ...
78    2021-08-30
79    2021-08-31
80    2021-09-01
81    2021-09-02
82    2021-09-03
Name: Date, Length: 83, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ANEB_ended_2021-09-25  2021-05-07          6.75   6.31   9.33       0.302

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.612     6.914     7.216     7.518      7.82     8.122     8.424

  markup_80 markup_90 markup_100
0     8.726     9.028       9.33
                   stock  start_date current_price minall maxall each_markup  \
0  ANEB_ended_2021-09-25  2021-05-07          6.75   6.31   9.33       0.302

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.612     6.914     7.216     7.518      7.82     8.122     8.424

  markup_80 markup_90 markup_100
0     8.726     9.028       9.33
./ticker_data/ticker_data_2021-09-25 - Copy/ANGI_ended_2021-09-25.csv
            Date   Open       High    Low      Close  Adj Close     Volume
0     2011-11-17  18.00  18.750000  15.02  16.260000  16.260000    6507700
1     2011-11-18  16.25  16.299999  15.60  15.800000  15.800000     584100
2     2011-11-21  15.40  15.750000  14.31  15.400000  15.400000     469600
3     2011-11-22  15.01  16.790001  15.01  16.120001  16.120001     211300
4     2011-11-23  15.75  15.990000  14.50  14.770000  14.770000     430500
...          ...    ...        ...    ...        ...        ...        ...
2460  2021-08-30  10.59  10.940000  10.42  10.730000  10.730000   92690000
2461  2021-08-31  10.74  10.840000  10.56  10.640000  10.640000   70430000
2462  2021-09-01  10.61  10.750000  10.36  10.410000  10.410000   89540000
2463  2021-09-02  10.50  10.790000  10.37  10.550000  10.550000  148810000
2464  2021-09-03  10.54  10.580000  10.27  10.510000  10.510000   61440000

[2465 rows x 7 columns]
tolistdate: 0       2011-11-17
1       2011-11-18
2       2011-11-21
3       2011-11-22
4       2011-11-23
           ...
2460    2021-08-30
2461    2021-08-31
2462    2021-09-01
2463    2021-09-02
2464    2021-09-03
Name: Date, Length: 2465, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ANGI_ended_2021-09-25  2011-11-17         10.51   3.73  28.32       2.459

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.189     8.648    11.107    13.566    16.025    18.484    20.943

  markup_80 markup_90 markup_100
0    23.402    25.861      28.32
                   stock  start_date current_price minall maxall each_markup  \
0  ANGI_ended_2021-09-25  2011-11-17         10.51   3.73  28.32       2.459

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.189     8.648    11.107    13.566    16.025    18.484    20.943

  markup_80 markup_90 markup_100
0    23.402    25.861      28.32
./ticker_data/ticker_data_2021-09-25 - Copy/ANGN_ended_2021-09-25.csv
           Date       Open       High    Low      Close  Adj Close    Volume
0    2021-02-05  17.620001  18.985001  16.50  17.020000  17.020000   1667100
1    2021-02-08  16.150000  18.700001  16.00  18.250000  18.250000    562700
2    2021-02-09  18.000000  18.580000  16.98  17.980000  17.980000    187000
3    2021-02-10  18.180000  18.450001  17.50  18.200001  18.200001    130200
4    2021-02-11  18.070000  18.750000  17.91  18.340000  18.340000    113400
..          ...        ...        ...    ...        ...        ...       ...
141  2021-08-30  10.030000  10.710000   9.73  10.540000  10.540000  18380000
142  2021-08-31  10.580000  11.145000  10.50  11.010000  11.010000  11610000
143  2021-09-01  10.960000  11.130000  10.77  11.010000  11.010000  14870000
144  2021-09-02  11.100000  12.160000  11.08  11.980000  11.980000  14510000
145  2021-09-03  12.060000  13.110000  11.80  12.460000  12.460000  18440000

[146 rows x 7 columns]
tolistdate: 0      2021-02-05
1      2021-02-08
2      2021-02-09
3      2021-02-10
4      2021-02-11
          ...
141    2021-08-30
142    2021-08-31
143    2021-09-01
144    2021-09-02
145    2021-09-03
Name: Date, Length: 146, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ANGN_ended_2021-09-25  2021-02-05         12.46   9.03   26.3       1.727

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.757    12.484    14.211    15.938    17.665    19.392    21.119

  markup_80 markup_90 markup_100
0    22.846    24.573       26.3
                   stock  start_date current_price minall maxall each_markup  \
0  ANGN_ended_2021-09-25  2021-02-05         12.46   9.03   26.3       1.727

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.757    12.484    14.211    15.938    17.665    19.392    21.119

  markup_80 markup_90 markup_100

0    22.846    24.573       26.3
./ticker_data/ticker_data_2021-09-25 - Copy/ANGO_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2004-06-01  14.170000  14.320000  13.000000  13.600000  13.600000
1     2004-06-02  13.650000  14.000000  13.000000  13.550000  13.550000
2     2004-06-03  13.550000  13.550000  13.000000  13.000000  13.000000
3     2004-06-04  12.900000  13.240000  12.800000  12.910000  12.910000
4     2004-06-07  12.850000  14.160000  12.850000  13.530000  13.530000
...          ...        ...        ...        ...        ...        ...
4341  2021-08-30  28.299999  28.549999  28.180000  28.490000  28.490000
4342  2021-08-31  28.540001  28.580000  28.049999  28.299999  28.299999
4343  2021-09-01  28.379999  29.230000  28.170000  29.200001  29.200001
4344  2021-09-02  29.379999  29.379999  28.379999  28.500000  28.500000
4345  2021-09-03  28.500000  28.840000  28.160000  28.410000  28.410000

        Volume
0       120100
1        58300
2        68100
3        50300
4       102800
...        ...
4341  11130000
4342  14590000
4343  26780000
4344  20470000
4345  26030000

[4346 rows x 7 columns]
tolistdate: 0       2004-06-01
1       2004-06-02
2       2004-06-03
3       2004-06-04
4       2004-06-07
           ...
4341    2021-08-30
4342    2021-08-31
4343    2021-09-01
4344    2021-09-02
4345    2021-09-03
Name: Date, Length: 4346, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ANGO_ended_2021-09-25  2004-06-01         28.41   7.48  31.29       2.381

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.861    12.242    14.623    17.004    19.385    21.766    24.147

  markup_80 markup_90 markup_100
0    26.528    28.909      31.29
                   stock  start_date current_price minall maxall each_markup  \
0  ANGO_ended_2021-09-25  2004-06-01         28.41   7.48  31.29       2.381

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.861    12.242    14.623    17.004    19.385    21.766    24.147

  markup_80 markup_90 markup_100
0    26.528    28.909      31.29
./ticker_data/ticker_data_2021-09-25 - Copy/ANIK_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   6.625000   7.062500   6.500000   7.062500   7.062500
1     2000-01-03   7.000000   7.125000   7.000000   7.000000   7.000000
2     2000-01-04   7.000000   7.062500   6.875000   7.000000   7.000000
3     2000-01-05   6.937500   6.937500   6.625000   6.750000   6.750000
4     2000-01-06   6.937500   7.000000   6.500000   6.703125   6.703125
...          ...        ...        ...        ...        ...        ...
5445  2021-08-30  42.480000  43.200001  42.279999  42.970001  42.970001
5446  2021-08-31  43.099998  43.759998  42.240002  43.130001  43.130001
5447  2021-09-01  43.240002  43.320000  42.200001  43.299999  43.299999
5448  2021-09-02  43.389999  43.389999  42.270000  42.490002  42.490002
5449  2021-09-03  42.500000  42.500000  40.480000  40.570000  40.570000

        Volume
0        36900
1        32500
2        35800
3        59600
4        44300
...        ...
5445   5260000
5446   3710000
5447   3330000
5448   3380000
5449  15570000

[5450 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5445    2021-08-30
5446    2021-08-31
5447    2021-09-01
5448    2021-09-02
5449    2021-09-03
Name: Date, Length: 5450, dtype: object
                   stock  start_date current_price  minall maxall each_markup  \
0  ANIK_ended_2021-09-25  1999-12-31         40.57  0.6875  75.72     7.50325

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   8.19075    15.694   23.1973   30.7005   38.2038    45.707   53.2103

  markup_80 markup_90 markup_100
0   60.7135   68.2168      75.72
                   stock  start_date current_price  minall maxall each_markup  \
0  ANIK_ended_2021-09-25  1999-12-31         40.57  0.6875  75.72     7.50325

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   8.19075    15.694   23.1973   30.7005   38.2038    45.707   53.2103

  markup_80 markup_90 markup_100
0   60.7135   68.2168      75.72
./ticker_data/ticker_data_2021-09-25 - Copy/ANIP_ended_2021-09-25.csv
            Date        Open        High         Low    Close  Adj Close  \
0     2000-05-05  213.750000  213.750000  213.750000  213.750    213.750
1     2000-05-12  185.625000  213.750000  185.625000  213.750    213.750
2     2000-05-18  185.625000  213.750000  185.625000  196.875    196.875
3     2000-05-19  196.875000  196.875000  196.875000  196.875    196.875
4     2000-05-24  180.000000  196.875000  180.000000  180.000    180.000
...          ...         ...         ...         ...      ...        ...
5093  2021-08-30   28.000000   28.250000   27.209999   27.400     27.400
5094  2021-08-31   28.750000   30.990000   28.750000   30.330     30.330
5095  2021-09-01   30.110001   30.980000   29.200001   30.680     30.680
5096  2021-09-02   30.780001   31.139999   28.809999   30.650     30.650
5097  2021-09-03   30.719999   30.719999   29.420000   29.500     29.500

        Volume
0            0
1            0
2            0
3            0
4            0
...        ...
5093   3010000
5094  12790000
5095  11580000
5096   4630000
5097   3590000

[5098 rows x 7 columns]
tolistdate: 0       2000-05-05
1       2000-05-12
2       2000-05-18
3       2000-05-19
4       2000-05-24
           ...
5093    2021-08-30
5094    2021-08-31
5095    2021-09-01
5096    2021-09-02
5097    2021-09-03
Name: Date, Length: 5098, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ANIP_ended_2021-09-25  2000-05-05          29.5    4.8    450       44.52

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     49.32     93.84    138.36    182.88     227.4    271.92    316.44

  markup_80 markup_90 markup_100
0    360.96    405.48        450
                   stock  start_date current_price minall maxall each_markup  \
0  ANIP_ended_2021-09-25  2000-05-05          29.5    4.8    450       44.52

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     49.32     93.84    138.36    182.88     227.4    271.92    316.44

  markup_80 markup_90 markup_100
0    360.96    405.48        450
./ticker_data/ticker_data_2021-09-25 - Copy/ANIX_ended_2021-09-25.csv
            Date       Open      High       Low     Close  Adj Close  \
0     1999-12-31  20.312500  21.09375  18.75000  20.31250   20.31250
1     2000-01-03  19.531250  21.09375  18.75000  19.53125   19.53125
2     2000-01-04  20.312500  21.87500  18.75000  20.31250   20.31250
3     2000-01-05  21.093750  21.87500  19.53125  21.09375   21.09375
4     2000-01-06  21.484375  23.43750  20.31250  21.87500   21.87500
...          ...        ...       ...       ...       ...        ...
5406  2021-08-30   5.360000   5.87000   5.25000   5.48000    5.48000
5407  2021-08-31   5.430000   5.74000   5.07000   5.60000    5.60000
5408  2021-09-01   5.640000   5.65000   5.28000   5.31000    5.31000
5409  2021-09-02   5.320000   5.54000   5.25000   5.48000    5.48000
5410  2021-09-03   5.480000   5.52000   5.35000   5.43000    5.43000

         Volume
0         21500
1          5200
2          9200
3          3300
4          7800
...         ...
5406  127820000
5407   41180000
5408   22220000
5409   15190000
5410    8080000

[5411 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5406    2021-08-30
5407    2021-08-31
5408    2021-09-01
5409    2021-09-02
5410    2021-09-03
Name: Date, Length: 5411, dtype: object
                   stock  start_date current_price minall   maxall  \
0  ANIX_ended_2021-09-25  1999-12-31          5.43    0.6  103.906

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     10.3306   10.9306   21.2613   31.5919   41.9225   52.2531   62.5838

  markup_70 markup_80 markup_90 markup_100
0   72.9144    83.245   93.5756    103.906
                   stock  start_date current_price minall   maxall  \
0  ANIX_ended_2021-09-25  1999-12-31          5.43    0.6  103.906

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     10.3306   10.9306   21.2613   31.5919   41.9225   52.2531   62.5838

  markup_70 markup_80 markup_90 markup_100
0   72.9144    83.245   93.5756    103.906
./ticker_data/ticker_data_2021-09-25 - Copy/ANNX_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-07-24  17.400000  19.000000  16.590000  17.760000  17.760000
1    2020-07-27  16.864000  17.995001  15.330000  17.500000  17.500000
2    2020-07-28  17.299999  18.230000  16.480000  17.990000  17.990000
3    2020-07-29  18.040001  19.625000  17.805000  18.760000  18.760000
4    2020-07-30  19.139999  19.650000  18.230000  18.410000  18.410000
..          ...        ...        ...        ...        ...        ...
276  2021-08-30  16.600000  17.370001  16.480000  16.870001  16.870001
277  2021-08-31  16.549999  17.299999  15.860000  16.350000  16.350000
278  2021-09-01  16.459999  16.805000  15.830000  16.530001  16.530001
279  2021-09-02  16.590000  17.275000  16.070000  17.160000  17.160000
280  2021-09-03  16.990000  17.250000  16.709999  17.150000  17.150000

       Volume
0     4914000
1      581900
2      151100
3      174700
4      119100
..        ...
276  11190000
277  15210000
278  10640000
279   8640000
280  13400000

[281 rows x 7 columns]
tolistdate: 0      2020-07-24
1      2020-07-27
2      2020-07-28
3      2020-07-29
4      2020-07-30
          ...
276    2021-08-30
277    2021-08-31
278    2021-09-01
279    2021-09-02
280    2021-09-03
Name: Date, Length: 281, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ANNX_ended_2021-09-25  2020-07-24         17.15  15.33  38.01       2.268

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.598    19.866    22.134    24.402     26.67    28.938    31.206

  markup_80 markup_90 markup_100
0    33.474    35.742      38.01
                   stock  start_date current_price minall maxall each_markup  \
0  ANNX_ended_2021-09-25  2020-07-24         17.15  15.33  38.01       2.268

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.598    19.866    22.134    24.402     26.67    28.938    31.206

  markup_80 markup_90 markup_100
0    33.474    35.742      38.01
./ticker_data/ticker_data_2021-09-25 - Copy/ANPC_ended_2021-09-25.csv
           Date    Open    High     Low  Close  Adj Close    Volume
0    2020-01-31  10.990  11.200   9.660  10.12      10.12    107400
1    2020-02-03  10.090  10.910  10.090  10.62      10.62     39200
2    2020-02-04  10.624  10.893   9.842  10.64      10.64     31300
3    2020-02-05  10.600  10.600   9.800  10.00      10.00     44600
4    2020-02-06  10.150  10.250   9.800  10.01      10.01     23700
..          ...     ...     ...     ...    ...        ...       ...
397  2021-08-30   3.420   3.500   3.330   3.43       3.43   5280000
398  2021-08-31   3.450   3.680   3.420   3.61       3.61  17540000
399  2021-09-01   3.610   3.637   3.450   3.50       3.50   2030000
400  2021-09-02   3.510   3.600   3.510   3.58       3.58   1130000
401  2021-09-03   3.600   3.600   3.500   3.52       3.52  22730000

[402 rows x 7 columns]
tolistdate: 0      2020-01-31
1      2020-02-03
2      2020-02-04
3      2020-02-05
4      2020-02-06
          ...
397    2021-08-30
398    2021-08-31
399    2021-09-01
400    2021-09-02
401    2021-09-03
Name: Date, Length: 402, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ANPC_ended_2021-09-25  2020-01-31          3.52   3.15  12.09       0.894

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.044     4.938     5.832     6.726      7.62     8.514     9.408

  markup_80 markup_90 markup_100
0    10.302    11.196      12.09
                   stock  start_date current_price minall maxall each_markup  \
0  ANPC_ended_2021-09-25  2020-01-31          3.52   3.15  12.09       0.894

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.044     4.938     5.832     6.726      7.62     8.514     9.408

  markup_80 markup_90 markup_100
0    10.302    11.196      12.09
./ticker_data/ticker_data_2021-09-25 - Copy/ANSS_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31    2.781250    2.812500    2.718750    2.750000    2.750000
1     2000-01-03    2.718750    2.781250    2.718750    2.765625    2.765625
2     2000-01-04    2.812500    2.812500    2.656250    2.687500    2.687500
3     2000-01-05    2.679688    2.703125    2.656250    2.703125    2.703125
4     2000-01-06    2.687500    2.703125    2.531250    2.703125    2.703125
...          ...         ...         ...         ...         ...         ...
5449  2021-08-30  366.609985  369.000000  362.869995  365.799988  365.799988
5450  2021-08-31  366.549988  368.109985  362.760010  365.359985  365.359985
5451  2021-09-01  367.459991  371.890015  365.779999  370.059998  370.059998
5452  2021-09-02  371.399994  372.950012  366.200012  368.399994  368.399994
5453  2021-09-03  366.079987  371.570007  366.079987  368.380005  368.380005

        Volume
0        38400
1        52400
2      1358800
3       336400
4       238800
...        ...
5449  34550000
5450  43920000
5451  37660000
5452  21460000
5453  29300000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price   minall  maxall  \
0  ANSS_ended_2021-09-25  1999-12-31        368.38  2.01562  413.19

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     41.1174   43.1331   84.2505   125.368   166.485   207.603    248.72

  markup_70 markup_80 markup_90 markup_100
0   289.838   330.955   372.073     413.19
                   stock  start_date current_price   minall  maxall  \
0  ANSS_ended_2021-09-25  1999-12-31        368.38  2.01562  413.19

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     41.1174   43.1331   84.2505   125.368   166.485   207.603    248.72

  markup_70 markup_80 markup_90 markup_100
0   289.838   330.955   372.073     413.19
./ticker_data/ticker_data_2021-09-25 - Copy/ANTE_ended_2021-09-25.csv
            Date       Open        High    Low       Close   Adj Close  \
0     2007-11-07  97.500000  113.550003  96.00  104.500000  104.500000
1     2007-11-08  97.500000  101.750000  92.50   95.000000   95.000000
2     2007-11-09  92.500000   98.650002  91.00   97.000000   97.000000
3     2007-11-12  90.000000   96.500000  90.00   92.800003   92.800003
4     2007-11-13  91.550003   94.400002  90.00   90.000000   90.000000
...          ...        ...         ...    ...         ...         ...
3475  2021-08-30   2.800000    2.830000   2.66    2.740000    2.740000
3476  2021-08-31   2.770000    2.770000   2.60    2.660000    2.660000
3477  2021-09-01   2.750000    2.760000   2.67    2.720000    2.720000
3478  2021-09-02   2.720000    2.780000   2.67    2.750000    2.750000
3479  2021-09-03   2.730000    2.840000   2.73    2.810000    2.810000

       Volume
0     2381500
1      648400
2      339200
3      250700
4      361900
...       ...
3475  4070000
3476  3350000
3477  1500000
3478  1250000
3479  1460000

[3480 rows x 7 columns]
tolistdate: 0       2007-11-07
1       2007-11-08
2       2007-11-09
3       2007-11-12
4       2007-11-13
           ...
3475    2021-08-30
3476    2021-08-31
3477    2021-09-01
3478    2021-09-02
3479    2021-09-03

Name: Date, Length: 3480, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ANTE_ended_2021-09-25  2007-11-07          2.81   0.63  132.55      13.192

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.822    27.014    40.206    53.398     66.59    79.782    92.974

  markup_80 markup_90 markup_100
0   106.166   119.358     132.55
                   stock  start_date current_price minall  maxall each_markup  \
0  ANTE_ended_2021-09-25  2007-11-07          2.81   0.63  132.55      13.192

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.822    27.014    40.206    53.398     66.59    79.782    92.974

  markup_80 markup_90 markup_100
0   106.166   119.358     132.55
./ticker_data/ticker_data_2021-09-25 - Copy/ANY_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2013-08-12  187.000000  224.000000  187.000000  210.000000  210.000000
1     2013-08-13  210.000000  210.000000  210.000000  210.000000  210.000000
2     2013-08-14  233.399994  233.399994  215.000000  232.600006  232.600006
3     2013-08-15  232.600006  232.600006  232.600006  232.600006  232.600006
4     2013-08-16  206.000000  216.000000  206.000000  214.000000  214.000000
...          ...         ...         ...         ...         ...         ...
2025  2021-08-30    5.205000    7.680000    5.200000    6.400000    6.400000
2026  2021-08-31    6.046000    6.750000    5.531000    6.490000    6.490000
2027  2021-09-01    6.400000    7.430000    6.210000    6.630000    6.630000
2028  2021-09-02    6.893000   11.980000    6.570000    9.400000    9.400000
2029  2021-09-03    7.200000    7.640000    6.260000    6.360000    6.360000

           Volume
0             400
1               0
2             200
3               0
4               0
...           ...
2025   9361510000
2026   1776750000
2027   3142380000
2028  24789880000
2029   8749280000

[2030 rows x 7 columns]
tolistdate: 0       2013-08-12
1       2013-08-13
2       2013-08-14
3       2013-08-15
4       2013-08-16
           ...
2025    2021-08-30
2026    2021-08-31
2027    2021-09-01
2028    2021-09-02
2029    2021-09-03
Name: Date, Length: 2030, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  ANY_ended_2021-09-25  2013-08-12          6.36   0.33   2292     229.167

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   229.497   458.664   687.831   916.998   1146.17   1375.33    1604.5

  markup_80 markup_90 markup_100
0   1833.67   2062.83       2292
                  stock  start_date current_price minall maxall each_markup  \
0  ANY_ended_2021-09-25  2013-08-12          6.36   0.33   2292     229.167

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   229.497   458.664   687.831   916.998   1146.17   1375.33    1604.5

  markup_80 markup_90 markup_100
0   1833.67   2062.83       2292
./ticker_data/ticker_data_2021-09-25 - Copy/ANZUU_ended_2021-09-25.csv
           Date   Open    High    Low  Close  Adj Close    Volume
0    2021-03-02  10.00  10.010  9.940  10.00      10.00  20111200
1    2021-03-03  10.10  10.101  9.950  10.00      10.00   1778000
2    2021-03-04   9.99  10.040  9.960  10.00      10.00   3823000
3    2021-03-05  10.00  10.055  9.970  10.03      10.03   1578600
4    2021-03-08  10.00  10.050  9.985  10.05      10.05   1377300
..          ...    ...     ...    ...    ...        ...       ...
118  2021-08-30   9.84   9.840  9.840   9.84       9.84     70000
119  2021-08-31   9.84   9.840  9.840   9.84       9.84         0
120  2021-09-01   9.81   9.840  9.810   9.82       9.82    320000
121  2021-09-02   9.83   9.830  9.830   9.83       9.83    810000
122  2021-09-03   9.83   9.830  9.830   9.83       9.83         0

[123 rows x 7 columns]
tolistdate: 0      2021-03-02
1      2021-03-03
2      2021-03-04
3      2021-03-05
4      2021-03-08
          ...
118    2021-08-30
119    2021-08-31
120    2021-09-01
121    2021-09-02
122    2021-09-03
Name: Date, Length: 123, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ANZUU_ended_2021-09-25  2021-03-02          9.83   9.66  10.14       0.048

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.708     9.756     9.804     9.852       9.9     9.948     9.996

  markup_80 markup_90 markup_100
0    10.044    10.092      10.14
                    stock  start_date current_price minall maxall each_markup  \
0  ANZUU_ended_2021-09-25  2021-03-02          9.83   9.66  10.14       0.048

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.708     9.756     9.804     9.852       9.9     9.948     9.996

  markup_80 markup_90 markup_100
0    10.044    10.092      10.14
./ticker_data/ticker_data_2021-09-25 - Copy/ANZUW_ended_2021-09-25.csv
         Date      Open  High   Low  Close  Adj Close  Volume
0  2021-09-21  0.869899  0.68  0.66   0.68       0.68    2000
tolistdate: 0    2021-09-21
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ANZUW_ended_2021-09-25  2021-09-21          0.68   0.66   0.68       0.002

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.662     0.664     0.666     0.668      0.67     0.672     0.674

  markup_80 markup_90 markup_100
0     0.676     0.678       0.68
                    stock  start_date current_price minall maxall each_markup  \
0  ANZUW_ended_2021-09-25  2021-09-21          0.68   0.66   0.68       0.002

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.662     0.664     0.666     0.668      0.67     0.672     0.674

  markup_80 markup_90 markup_100
0     0.676     0.678       0.68
./ticker_data/ticker_data_2021-09-25 - Copy/ANZU_ended_2021-09-25.csv
          Date  Open  High    Low  Close  Adj Close  Volume
0   2021-04-29  9.76  9.76  9.760  9.760      9.760     300
1   2021-04-30  9.76  9.80  9.750  9.750      9.750    2800
2   2021-05-03  9.76  9.76  9.710  9.728      9.728  112100
3   2021-05-04  9.70  9.77  9.700  9.770      9.770   13400
4   2021-05-05  9.77  9.77  9.764  9.770      9.770    1100
..         ...   ...   ...    ...    ...        ...     ...
67  2021-08-24  9.64  9.69  9.640  9.690      9.690   60000
68  2021-08-27  9.69  9.69  9.690  9.690      9.690   10000
69  2021-08-30  9.65  9.65  9.650  9.650      9.650   30000
70  2021-08-31  9.67  9.67  9.670  9.670      9.670  490000
71  2021-09-02  9.65  9.70  9.650  9.700      9.700  550000

[72 rows x 7 columns]
tolistdate: 0     2021-04-29
1     2021-04-30
2     2021-05-03
3     2021-05-04
4     2021-05-05
         ...
67    2021-08-24
68    2021-08-27
69    2021-08-30
70    2021-08-31
71    2021-09-02
Name: Date, Length: 72, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ANZU_ended_2021-09-25  2021-04-29           9.7   9.61     10       0.039

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.649     9.688     9.727     9.766     9.805     9.844     9.883

  markup_80 markup_90 markup_100
0     9.922     9.961         10
                   stock  start_date current_price minall maxall each_markup  \
0  ANZU_ended_2021-09-25  2021-04-29           9.7   9.61     10       0.039

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.649     9.688     9.727     9.766     9.805     9.844     9.883

  markup_80 markup_90 markup_100
0     9.922     9.961         10
./ticker_data/ticker_data_2021-09-25 - Copy/AOSL_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2010-04-29  18.110001  18.440001  17.059999  17.700001  17.700001
1     2010-04-30  17.750000  17.940001  17.250000  17.910000  17.910000
2     2010-05-03  18.000000  18.200001  17.760000  17.900000  17.900000
3     2010-05-04  17.990000  17.990000  17.070000  17.330000  17.330000
4     2010-05-05  17.250000  17.500000  16.520000  16.700001  16.700001
...          ...        ...        ...        ...        ...        ...
2868  2021-09-20  27.860001  28.190001  27.139999  27.760000  27.760000
2869  2021-09-21  28.129999  28.129999  27.100000  27.770000  27.770000
2870  2021-09-22  28.010000  28.959999  27.920000  28.620001  28.620001
2871  2021-09-23  29.500000  30.830000  28.799999  30.660000  30.660000
2872  2021-09-24  30.450001  31.700001  30.230000  31.530001  31.530001

       Volume
0     3800200
1      490900
2       92100
3      126200
4       89800
...       ...
2868   258200
2869   130600
2870   143500
2871   316400
2872   167468

[2873 rows x 7 columns]
tolistdate: 0       2010-04-29
1       2010-04-30
2       2010-05-03
3       2010-05-04
4       2010-05-05
           ...
2868    2021-09-20
2869    2021-09-21
2870    2021-09-22
2871    2021-09-23
2872    2021-09-24
Name: Date, Length: 2873, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AOSL_ended_2021-09-25  2010-04-29         31.53   5.82     43       3.718

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.538    13.256    16.974    20.692     24.41    28.128    31.846

  markup_80 markup_90 markup_100
0    35.564    39.282         43
                   stock  start_date current_price minall maxall each_markup  \
0  AOSL_ended_2021-09-25  2010-04-29         31.53   5.82     43       3.718

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.538    13.256    16.974    20.692     24.41    28.128    31.846

  markup_80 markup_90 markup_100
0    35.564    39.282         43
./ticker_data/ticker_data_2021-09-25 - Copy/AOUT_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-08-21  18.180000  18.180000  15.500000  15.500000  15.500000
1    2020-08-24  19.959999  30.010000  17.350000  19.400000  19.400000
2    2020-08-25  16.150000  19.275000  14.570000  17.780001  17.780001
3    2020-08-26  18.219000  19.298000  17.103001  18.930000  18.930000
4    2020-08-27  19.430000  19.475000  17.400000  17.940001  17.940001
..          ...        ...        ...        ...        ...        ...
271  2021-09-20  25.440001  26.080000  25.400000  25.680000  25.680000
272  2021-09-21  25.799999  25.850000  24.100000  25.120001  25.120001
273  2021-09-22  25.100000  25.440001  24.530001  25.020000  25.020000
274  2021-09-23  25.100000  25.889999  25.080000  25.670000  25.670000
275  2021-09-24  25.559999  25.719999  25.100000  25.709999  25.709999

      Volume
0       2100
1     106900
2    1444400
3     661600
4     425700
..       ...
271   156800
272   252100
273   125900
274    99900
275    37502

[276 rows x 7 columns]
tolistdate: 0      2020-08-21
1      2020-08-24
2      2020-08-25
3      2020-08-26
4      2020-08-27
          ...
271    2021-09-20
272    2021-09-21
273    2021-09-22
274    2021-09-23
275    2021-09-24
Name: Date, Length: 276, dtype: object
                   stock  start_date current_price  minall maxall each_markup  \
0  AOUT_ended_2021-09-25  2020-08-21         25.71  12.238  36.62      2.4382

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   14.6762   17.1144   19.5526   21.9908    24.429   26.8672   29.3054

  markup_80 markup_90 markup_100
0   31.7436   34.1818      36.62
                   stock  start_date current_price  minall maxall each_markup  \
0  AOUT_ended_2021-09-25  2020-08-21         25.71  12.238  36.62      2.4382

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   14.6762   17.1144   19.5526   21.9908    24.429   26.8672   29.3054

  markup_80 markup_90 markup_100
0   31.7436   34.1818      36.62
./ticker_data/ticker_data_2021-09-25 - Copy/APA_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  15.773809  15.990260  15.638528  15.990260  12.563864
1     2000-01-03  15.882034  15.882034  14.745671  14.772727  11.607217
2     2000-01-04  14.285714  14.556277  13.961039  14.123377  11.097013
3     2000-01-05  14.231602  14.583333  14.123377  14.529221  11.415894
4     2000-01-06  14.935065  16.017317  14.745671  15.909091  12.500087
...          ...        ...        ...        ...        ...        ...
5449  2021-08-30  19.059999  19.059999  18.459999  18.660000  18.660000
5450  2021-08-31  18.490000  19.620001  18.450001  19.480000  19.480000
5451  2021-09-01  19.340000  19.520000  18.719999  19.049999  19.049999
5452  2021-09-02  19.260000  20.059999  19.219999  19.850000  19.850000
5453  2021-09-03  19.820000  20.040001  19.490000  19.670000  19.670000

         Volume
0        192600
1       1082400
2       2959400
3       2169800
4       2415800
...         ...
5449  618220000
5450  931660000
5451  736510000
5452  749480000
5453  676440000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                  stock  start_date current_price minall  maxall each_markup  \
0  APA_ended_2021-09-25  1999-12-31         19.67    3.8  149.23      14.543

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    18.343    32.886    47.429    61.972    76.515    91.058   105.601

  markup_80 markup_90 markup_100
0   120.144   134.687     149.23
                  stock  start_date current_price minall  maxall each_markup  \
0  APA_ended_2021-09-25  1999-12-31         19.67    3.8  149.23      14.543

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    18.343    32.886    47.429    61.972    76.515    91.058   105.601

  markup_80 markup_90 markup_100
0   120.144   134.687     149.23
./ticker_data/ticker_data_2021-09-25 - Copy/APDN_ended_2021-09-25.csv
            Date     Open     High      Low    Close  Adj Close    Volume
0     2003-07-15  6600.00  6600.00  6600.00  6600.00    6600.00         0
1     2003-07-16  6480.00  6720.00  6480.00  6480.00    6480.00         0
2     2003-07-17  6600.00  6600.00  6480.00  6480.00    6480.00         0
3     2003-07-21  6720.00  6720.00  6240.00  6600.00    6600.00         0
4     2003-07-25  6480.00  6600.00  5880.00  6240.00    6240.00         0
...          ...      ...      ...      ...      ...        ...       ...
3275  2021-08-30     5.89     6.18     5.67     6.02       6.02  29250000
3276  2021-08-31     6.01     6.13     5.73     5.86       5.86  21840000
3277  2021-09-01     5.87     5.99     5.78     5.87       5.87   9360000
3278  2021-09-02     5.93     6.26     5.89     6.19       6.19  75060000
3279  2021-09-03     6.04     6.13     5.75     5.98       5.98  26830000

[3280 rows x 7 columns]
tolistdate: 0       2003-07-15
1       2003-07-16
2       2003-07-17
3       2003-07-21
4       2003-07-25
           ...
3275    2021-08-30
3276    2021-08-31
3277    2021-09-01
3278    2021-09-02
3279    2021-09-03
Name: Date, Length: 3280, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  APDN_ended_2021-09-25  2003-07-15          5.98   2.52   8520     851.748

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   854.268   1706.02   2557.76   3409.51   4261.26   5113.01   5964.76

  markup_80 markup_90 markup_100
0    6816.5   7668.25       8520
                   stock  start_date current_price minall maxall each_markup  \
0  APDN_ended_2021-09-25  2003-07-15          5.98   2.52   8520     851.748

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   854.268   1706.02   2557.76   3409.51   4261.26   5113.01   5964.76

  markup_80 markup_90 markup_100
0    6816.5   7668.25       8520
./ticker_data/ticker_data_2021-09-25 - Copy/APEI_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2007-11-09  30.000000  38.360001  29.230000  35.919998  35.919998
1     2007-11-12  34.279999  34.500000  32.610001  33.200001  33.200001
2     2007-11-13  33.750000  35.689999  33.000000  35.110001  35.110001
3     2007-11-14  35.500000  36.700001  34.000000  35.049999  35.049999
4     2007-11-15  34.000000  34.910000  33.599998  34.000000  34.000000
...          ...        ...        ...        ...        ...        ...
3473  2021-08-30  26.750000  26.750000  26.020000  26.200001  26.200001
3474  2021-08-31  26.360001  26.570000  26.219999  26.299999  26.299999
3475  2021-09-01  26.430000  26.450001  26.139999  26.200001  26.200001
3476  2021-09-02  26.370001  26.629999  26.090000  26.290001  26.290001
3477  2021-09-03  26.370001  27.129999  26.160000  27.020000  27.020000

        Volume
0      2997200
1       509600
2       177100
3        99500
4       103000
...        ...
3473  12760000
3474   8790000
3475   3760000
3476   9980000
3477   8800000

[3478 rows x 7 columns]
tolistdate: 0       2007-11-09
1       2007-11-12
2       2007-11-13
3       2007-11-14
4       2007-11-15
           ...
3473    2021-08-30
3474    2021-08-31
3475    2021-09-01
3476    2021-09-02
3477    2021-09-03
Name: Date, Length: 3478, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  APEI_ended_2021-09-25  2007-11-09         27.02   13.8  53.24       3.944

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.744    21.688    25.632    29.576     33.52    37.464    41.408

  markup_80 markup_90 markup_100
0    45.352    49.296      53.24
                   stock  start_date current_price minall maxall each_markup  \
0  APEI_ended_2021-09-25  2007-11-09         27.02   13.8  53.24       3.944

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.744    21.688    25.632    29.576     33.52    37.464    41.408

  markup_80 markup_90 markup_100
0    45.352    49.296      53.24
./ticker_data/ticker_data_2021-09-25 - Copy/APEN_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2007-05-01  916.299988  916.299988  889.349976  889.349976  889.349976
1     2007-05-02  878.570007  889.349976  857.010010  857.010010  857.010010
2     2007-05-03  808.500000  862.400024  808.500000  835.450012  835.450012
3     2007-05-04  889.349976  916.299988  889.349976  916.299988  916.299988
4     2007-05-07  916.299988  970.200012  905.520020  970.200012  970.200012
...          ...         ...         ...         ...         ...         ...
3542  2021-09-20    8.740000    9.200000    8.640000    9.160000    9.160000
3543  2021-09-21    9.120000    9.220000    9.050000    9.080000    9.080000
3544  2021-09-22    9.080000    9.180000    8.760000    9.070000    9.070000
3545  2021-09-23    9.040000    9.570000    8.950000    9.200000    9.200000
3546  2021-09-24    9.240000    9.599900    9.240000    9.570000    9.570000

      Volume
0         81
1         37
2         23
3         22
4         97
...      ...
3542  128300
3543   68300
3544   67900
3545  107000
3546   99466

[3547 rows x 7 columns]
tolistdate: 0       2007-05-01
1       2007-05-02
2       2007-05-03
3       2007-05-04
4       2007-05-07
           ...
3542    2021-09-20
3543    2021-09-21
3544    2021-09-22
3545    2021-09-23
3546    2021-09-24
Name: Date, Length: 3547, dtype: object
                   stock  start_date current_price minall   maxall  \
0  APEN_ended_2021-09-25  2007-05-01          9.57   1.24  1369.06

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     136.782   138.022   274.804   411.586   548.368    685.15   821.932

  markup_70 markup_80 markup_90 markup_100
0   958.714    1095.5   1232.28    1369.06
                   stock  start_date current_price minall   maxall  \
0  APEN_ended_2021-09-25  2007-05-01          9.57   1.24  1369.06

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     136.782   138.022   274.804   411.586   548.368    685.15   821.932

  markup_70 markup_80 markup_90 markup_100
0   958.714    1095.5   1232.28    1369.06
./ticker_data/ticker_data_2021-09-25 - Copy/API_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-06-26  45.000000  55.700001  43.099998  50.500000  50.500000
1    2020-06-29  52.099998  52.459999  45.259998  47.000000  47.000000
2    2020-06-30  45.529999  49.622002  42.250000  44.169998  44.169998
3    2020-07-01  43.660000  48.919998  43.000000  48.790001  48.790001
4    2020-07-02  50.130001  56.779999  48.549999  56.490002  56.490002
..          ...        ...        ...        ...        ...        ...
295  2021-08-30  29.780001  30.860001  29.370001  30.480000  30.480000
296  2021-08-31  30.950001  34.310001  30.660000  33.919998  33.919998
297  2021-09-01  34.400002  34.419998  32.220001  33.200001  33.200001
298  2021-09-02  33.200001  33.720001  32.090000  32.680000  32.680000
299  2021-09-03  32.310001  33.166000  32.279999  32.810001  32.810001

        Volume
0      7705300
1      3305400
2      1857500
3      1037000
4      1974700
..         ...
295   38410000
296  210480000
297  129390000
298   47170000
299   40010000

[300 rows x 7 columns]
tolistdate: 0      2020-06-26
1      2020-06-29
2      2020-06-30
3      2020-07-01
4      2020-07-02
          ...
295    2021-08-30
296    2021-08-31
297    2021-09-01
298    2021-09-02
299    2021-09-03
Name: Date, Length: 300, dtype: object
                  stock  start_date current_price  minall   maxall  \
0  API_ended_2021-09-25  2020-06-26         32.81  24.285  114.965

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0       9.068    33.353    42.421    51.489    60.557    69.625    78.693

  markup_70 markup_80 markup_90 markup_100
0    87.761    96.829   105.897    114.965
                  stock  start_date current_price  minall   maxall  \
0  API_ended_2021-09-25  2020-06-26         32.81  24.285  114.965

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0       9.068    33.353    42.421    51.489    60.557    69.625    78.693

  markup_70 markup_80 markup_90 markup_100
0    87.761    96.829   105.897    114.965
./ticker_data/ticker_data_2021-09-25 - Copy/APLS_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2017-11-09  14.500000  14.900000  13.150000  14.030000  14.030000
1    2017-11-10  13.900000  14.190000  13.560000  14.000000  14.000000
2    2017-11-13  14.020000  14.140000  13.600000  14.100000  14.100000
3    2017-11-14  14.200000  14.200000  13.700000  13.930000  13.930000
4    2017-11-15  13.910000  13.950000  13.700000  13.830000  13.830000
..          ...        ...        ...        ...        ...        ...
956  2021-08-30  66.949997  67.739998  64.500000  65.410004  65.410004
957  2021-08-31  66.720001  67.330002  65.449997  65.849998  65.849998
958  2021-09-01  65.849998  66.610001  63.125000  64.730003  64.730003
959  2021-09-02  65.199997  65.400002  62.549999  62.619999  62.619999
960  2021-09-03  62.340000  64.320000  61.810001  64.029999  64.029999

        Volume
0      2297000
1       183100
2        64400
3        49300
4        85600
..         ...
956  100860000
957   86200000
958   86630000
959   66900000
960  114560000

[961 rows x 7 columns]
tolistdate: 0      2017-11-09
1      2017-11-10
2      2017-11-13
3      2017-11-14
4      2017-11-15
          ...
956    2021-08-30
957    2021-08-31
958    2021-09-01
959    2021-09-02
960    2021-09-03
Name: Date, Length: 961, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  APLS_ended_2021-09-25  2017-11-09         64.03  11.45     73       6.155

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.605     23.76    29.915     36.07    42.225     48.38    54.535

  markup_80 markup_90 markup_100
0     60.69    66.845         73
                   stock  start_date current_price minall maxall each_markup  \
0  APLS_ended_2021-09-25  2017-11-09         64.03  11.45     73       6.155

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.605     23.76    29.915     36.07    42.225     48.38    54.535

  markup_80 markup_90 markup_100
0     60.69    66.845         73
./ticker_data/ticker_data_2021-09-25 - Copy/APLT_ended_2021-09-25.csv
           Date       Open       High        Low   Close  Adj Close   Volume
0    2019-05-14   8.400000   9.500000   7.950000   9.400      9.400  1342600
1    2019-05-15   9.450000  10.250000   9.450000   9.750      9.750   213900
2    2019-05-16   9.730000  10.190000   9.021000   9.910      9.910    97800
3    2019-05-17   9.140000  10.194000   9.140000  10.020     10.020   116900
4    2019-05-20  10.020000  10.200000  10.000000  10.012     10.012    73000
..          ...        ...        ...        ...     ...        ...      ...
593  2021-09-20  13.740000  13.970000  13.040000  13.540     13.540   132800
594  2021-09-21  13.790000  15.510000  13.780000  15.310     15.310   112300
595  2021-09-22  15.390000  15.815000  14.660000  15.360     15.360   167300
596  2021-09-23  15.450000  16.950001  15.450000  16.730     16.730   162200
597  2021-09-24  16.530001  16.940001  16.110001  16.180     16.180    30063

[598 rows x 7 columns]
tolistdate: 0      2019-05-14
1      2019-05-15
2      2019-05-16
3      2019-05-17
4      2019-05-20
          ...
593    2021-09-20
594    2021-09-21
595    2021-09-22
596    2021-09-23
597    2021-09-24
Name: Date, Length: 598, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  APLT_ended_2021-09-25  2019-05-14         16.18   7.95  57.39       4.944

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.894    17.838    22.782    27.726     32.67    37.614    42.558

  markup_80 markup_90 markup_100
0    47.502    52.446      57.39
                   stock  start_date current_price minall maxall each_markup  \
0  APLT_ended_2021-09-25  2019-05-14         16.18   7.95  57.39       4.944

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.894    17.838    22.782    27.726     32.67    37.614    42.558

  markup_80 markup_90 markup_100
0    47.502    52.446      57.39
./ticker_data/ticker_data_2021-09-25 - Copy/APM_ended_2021-09-25.csv
           Date   Open    High    Low   Close  Adj Close    Volume
0    2018-12-18  15.80  15.850  13.25  14.350     14.350     23200
1    2018-12-19  14.05  14.683  13.51  13.510     13.510      8300
2    2018-12-20  13.47  15.800  13.40  15.300     15.300     24600
3    2018-12-21  15.23  15.750  13.76  15.150     15.150      5100
4    2018-12-24  15.62  15.700  15.62  15.698     15.698      4700
..          ...    ...     ...    ...     ...        ...       ...
678  2021-08-30   2.59   2.606   2.47   2.580      2.580  12460000
679  2021-08-31   2.55   2.660   2.52   2.660      2.660  14080000
680  2021-09-01   2.64   2.750   2.51   2.630      2.630  23480000
681  2021-09-02   2.58   2.650   2.55   2.610      2.610  12390000
682  2021-09-03   2.60   2.640   2.55   2.640      2.640   6150000

[683 rows x 7 columns]
tolistdate: 0      2018-12-18
1      2018-12-19
2      2018-12-20
3      2018-12-21
4      2018-12-24
          ...
678    2021-08-30
679    2021-08-31
680    2021-09-01
681    2021-09-02
682    2021-09-03
Name: Date, Length: 683, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  APM_ended_2021-09-25  2018-12-18          2.64   1.16  33.28       3.212

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.372     7.584    10.796    14.008     17.22    20.432    23.644

  markup_80 markup_90 markup_100
0    26.856    30.068      33.28
                  stock  start_date current_price minall maxall each_markup  \
0  APM_ended_2021-09-25  2018-12-18          2.64   1.16  33.28       3.212

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.372     7.584    10.796    14.008     17.22    20.432    23.644

  markup_80 markup_90 markup_100
0    26.856    30.068      33.28
./ticker_data/ticker_data_2021-09-25 - Copy/APOG_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   5.031250   5.125000   4.906250   5.062500   3.268817
1     2000-01-03   5.125000   6.250000   5.000000   5.625000   3.632020
2     2000-01-04   5.750000   5.750000   5.000000   5.000000   3.228462
3     2000-01-05   5.125000   5.250000   4.875000   5.125000   3.309174
4     2000-01-06   5.125000   5.125000   4.937500   5.000000   3.228462
...          ...        ...        ...        ...        ...        ...
5449  2021-08-30  43.779999  43.889999  43.060001  43.119999  43.119999
5450  2021-08-31  43.250000  43.250000  42.500000  42.980000  42.980000
5451  2021-09-01  43.029999  43.380001  42.209999  43.230000  43.230000
5452  2021-09-02  43.480000  43.709999  42.279999  43.580002  43.580002
5453  2021-09-03  43.660000  43.799999  43.410000  43.540001  43.540001

       Volume
0      121900
1      222200
2      233800
3       98400
4      129800
...       ...
5449  9050000
5450  8670000
5451  9410000
5452  6910000
5453  8420000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  APOG_ended_2021-09-25  1999-12-31         43.54   3.25  61.05        5.78

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.03     14.81     20.59     26.37     32.15     37.93     43.71

  markup_80 markup_90 markup_100
0     49.49     55.27      61.05
                   stock  start_date current_price minall maxall each_markup  \
0  APOG_ended_2021-09-25  1999-12-31         43.54   3.25  61.05        5.78

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.03     14.81     20.59     26.37     32.15     37.93     43.71

  markup_80 markup_90 markup_100
0     49.49     55.27      61.05
./ticker_data/ticker_data_2021-09-25 - Copy/APOPW_ended_2021-09-25.csv
         Date  Open    High       Low   Close  Adj Close  Volume
0  2021-08-03  0.07  0.0876  0.049064  0.0876     0.0876   51821
tolistdate: 0    2021-08-03
Name: Date, dtype: object
                    stock  start_date current_price    minall  maxall  \
0  APOPW_ended_2021-09-25  2021-08-03        0.0876  0.049064  0.0876

  each_markup  markup_10  markup_20  markup_30  markup_40 markup_50  \
0   0.0038536  0.0529176  0.0567712  0.0606248  0.0644784  0.068332

   markup_60  markup_70  markup_80  markup_90 markup_100
0  0.0721856  0.0760392  0.0798928  0.0837464     0.0876
                    stock  start_date current_price    minall  maxall  \
0  APOPW_ended_2021-09-25  2021-08-03        0.0876  0.049064  0.0876

  each_markup  markup_10  markup_20  markup_30  markup_40 markup_50  \
0   0.0038536  0.0529176  0.0567712  0.0606248  0.0644784  0.068332

   markup_60  markup_70  markup_80  markup_90 markup_100
0  0.0721856  0.0760392  0.0798928  0.0837464     0.0876
./ticker_data/ticker_data_2021-09-25 - Copy/APOP_ended_2021-09-25.csv
            Date       Open       High        Low  Close  Adj Close  \
0     2016-08-01  26.250000  26.799999  25.750000  26.50      26.50
1     2016-08-02  26.250000  26.250000  25.049999  25.50      25.50
2     2016-08-03  25.500000  25.500000  23.549999  24.50      24.50
3     2016-08-04  24.450001  24.549999  23.150000  23.15      23.15
4     2016-08-05  24.950001  24.950001  22.750000  23.50      23.50
...          ...        ...        ...        ...    ...        ...
1273  2021-08-30   4.250000   4.970000   4.200000   4.97       4.97
1274  2021-08-31   4.890000   5.620000   4.880000   5.30       5.30
1275  2021-09-01   5.200000   5.840000   4.930000   5.15       5.15
1276  2021-09-02   5.130000   5.780000   5.060000   5.50       5.50
1277  2021-09-03   8.870000   8.880000   6.250000   6.69       6.69

          Volume
0          34400
1          10900
2          15600
3           5200
4           4900
...          ...
1273   417470000
1274   275390000
1275   337110000
1276  1177940000
1277  6447500000

[1278 rows x 7 columns]
tolistdate: 0       2016-08-01
1       2016-08-02
2       2016-08-03
3       2016-08-04
4       2016-08-05
           ...
1273    2021-08-30
1274    2021-08-31
1275    2021-09-01
1276    2021-09-02
1277    2021-09-03
Name: Date, Length: 1278, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  APOP_ended_2021-09-25  2016-08-01          6.69    0.4   67.5        6.71

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      7.11     13.82     20.53     27.24     33.95     40.66     47.37

  markup_80 markup_90 markup_100
0     54.08     60.79       67.5
                   stock  start_date current_price minall maxall each_markup  \
0  APOP_ended_2021-09-25  2016-08-01          6.69    0.4   67.5        6.71

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      7.11     13.82     20.53     27.24     33.95     40.66     47.37

  markup_80 markup_90 markup_100
0     54.08     60.79       67.5
./ticker_data/ticker_data_2021-09-25 - Copy/APPF_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2015-06-26   12.150000   14.870000   12.110000   14.080000   14.080000
1     2015-06-29   13.260000   14.240000   13.260000   13.700000   13.700000
2     2015-06-30   14.860000   14.860000   13.820000   14.100000   14.100000
3     2015-07-01   14.800000   14.800000   13.750000   14.000000   14.000000
4     2015-07-02   14.400000   14.400000   13.750000   13.750000   13.750000
...          ...         ...         ...         ...         ...         ...
1569  2021-09-20  119.959999  123.570000  117.684998  119.860001  119.860001
1570  2021-09-21  121.620003  122.570000  118.879997  120.059998  120.059998
1571  2021-09-22  120.199997  122.860001  119.029999  119.040001  119.040001
1572  2021-09-23  120.300003  122.849998  117.389999  122.589996  122.589996
1573  2021-09-24  121.860001  125.059998  121.099998  123.849998  123.849998

       Volume
0     3529100
1      332600
2       98600
3      215800
4      107900
...       ...
1569    85200
1570    75500
1571   143700
1572    88800
1573    34287

[1574 rows x 7 columns]
tolistdate: 0       2015-06-26
1       2015-06-29
2       2015-06-30
3       2015-07-01
4       2015-07-02
           ...
1569    2021-09-20
1570    2021-09-21
1571    2021-09-22
1572    2021-09-23
1573    2021-09-24
Name: Date, Length: 1574, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  APPF_ended_2021-09-25  2015-06-26        123.85  11.07  186.59      17.552

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    28.622    46.174    63.726    81.278     98.83   116.382   133.934

  markup_80 markup_90 markup_100

0   151.486   169.038     186.59
                   stock  start_date current_price minall  maxall each_markup  \
0  APPF_ended_2021-09-25  2015-06-26        123.85  11.07  186.59      17.552

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    28.622    46.174    63.726    81.278     98.83   116.382   133.934

  markup_80 markup_90 markup_100
0   151.486   169.038     186.59
./ticker_data/ticker_data_2021-09-25 - Copy/APPHW_ended_2021-09-25.csv
         Date  Open  High    Low  Close  Adj Close  Volume
0  2021-09-22   1.6   1.7  1.545   1.64       1.64   12735
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  APPHW_ended_2021-09-25  2021-09-22          1.64  1.545    1.7      0.0155

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    1.5605     1.576    1.5915     1.607    1.6225     1.638    1.6535

  markup_80 markup_90 markup_100
0     1.669    1.6845        1.7
                    stock  start_date current_price minall maxall each_markup  \
0  APPHW_ended_2021-09-25  2021-09-22          1.64  1.545    1.7      0.0155

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    1.5605     1.576    1.5915     1.607    1.6225     1.638    1.6535

  markup_80 markup_90 markup_100
0     1.669    1.6845        1.7
./ticker_data/ticker_data_2021-09-25 - Copy/APPH_ended_2021-09-25.csv
           Date    Open    High    Low  Close  Adj Close     Volume
0    2020-08-03   9.900   9.930  9.830  9.930      9.930       4800
1    2020-08-04   9.900   9.970  9.900  9.970      9.970       4700
2    2020-08-05  10.000  10.000  9.915  9.915      9.915       1000
3    2020-08-06   9.925   9.970  9.921  9.970      9.970       2600
4    2020-08-07   9.860   9.970  9.860  9.970      9.970       1300
..          ...     ...     ...    ...    ...        ...        ...
271  2021-08-30   8.160   8.770  8.030  8.590      8.590  175090000
272  2021-08-31   8.660   8.660  8.080  8.400      8.400  166690000
273  2021-09-01   8.410   8.650  8.335  8.490      8.490  118230000
274  2021-09-02   8.580   8.850  8.160  8.200      8.200  110100000
275  2021-09-03   8.216   8.216  7.655  7.880      7.880  161420000

[276 rows x 7 columns]
tolistdate: 0      2020-08-03
1      2020-08-04
2      2020-08-05
3      2020-08-06
4      2020-08-07
          ...
271    2021-08-30
272    2021-08-31
273    2021-09-01
274    2021-09-02
275    2021-09-03
Name: Date, Length: 276, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  APPH_ended_2021-09-25  2020-08-03          7.88   6.66   42.9       3.624

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.284    13.908    17.532    21.156     24.78    28.404    32.028

  markup_80 markup_90 markup_100
0    35.652    39.276       42.9
                   stock  start_date current_price minall maxall each_markup  \
0  APPH_ended_2021-09-25  2020-08-03          7.88   6.66   42.9       3.624

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.284    13.908    17.532    21.156     24.78    28.404    32.028

  markup_80 markup_90 markup_100
0    35.652    39.276       42.9
./ticker_data/ticker_data_2021-09-25 - Copy/APPN_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2017-05-25   15.000000   16.750000   14.600000   15.010000   15.010000
1     2017-05-26   15.250000   17.389999   15.229000   17.110001   17.110001
2     2017-05-30   18.190001   18.940001   17.299999   17.900000   17.900000
3     2017-05-31   18.480000   18.480000   17.309999   17.650000   17.650000
4     2017-06-01   17.440001   18.299999   16.782000   17.945000   17.945000
...          ...         ...         ...         ...         ...         ...
1072  2021-08-30  108.769997  110.279999  107.455002  107.889999  107.889999
1073  2021-08-31  107.889999  108.379997  106.290001  107.199997  107.199997
1074  2021-09-01  107.489998  110.910004  107.489998  108.820000  108.820000
1075  2021-09-02  109.360001  112.599998  108.059998  108.070000  108.070000
1076  2021-09-03  109.919998  115.680000  109.220001  113.690002  113.690002

        Volume
0      4949200
1      1725800
2      1244500
3       671800
4       414200
...        ...
1072  36900000
1073  26990000
1074  27070000
1075  41420000
1076  49460000

[1077 rows x 7 columns]
tolistdate: 0       2017-05-25
1       2017-05-26
2       2017-05-30
3       2017-05-31
4       2017-06-01
           ...
1072    2021-08-30
1073    2021-08-31
1074    2021-09-01
1075    2021-09-02
1076    2021-09-03
Name: Date, Length: 1077, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  APPN_ended_2021-09-25  2017-05-25        113.69   14.6    260       24.54

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     39.14     63.68     88.22    112.76     137.3    161.84    186.38

  markup_80 markup_90 markup_100
0    210.92    235.46        260
                   stock  start_date current_price minall maxall each_markup  \
0  APPN_ended_2021-09-25  2017-05-25        113.69   14.6    260       24.54

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     39.14     63.68     88.22    112.76     137.3    161.84    186.38

  markup_80 markup_90 markup_100
0    210.92    235.46        260
./ticker_data/ticker_data_2021-09-25 - Copy/APPS_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2006-07-06   2.100000   2.100000   2.100000   2.100000   2.100000
1     2006-07-07   2.200000   2.200000   2.100000   2.200000   2.200000
2     2006-07-10   2.200000   2.200000   2.200000   2.200000   2.200000
3     2006-07-11   2.200000   2.200000   2.200000   2.200000   2.200000
4     2006-07-12   2.200000   2.200000   2.200000   2.200000   2.200000
...          ...        ...        ...        ...        ...        ...
3118  2021-08-30  52.970001  53.029999  50.430000  51.240002  51.240002
3119  2021-08-31  57.549999  61.070000  56.029999  58.450001  58.450001
3120  2021-09-01  58.779999  60.680000  58.150002  59.790001  59.790001
3121  2021-09-02  60.439999  64.540001  60.049999  63.349998  63.349998
3122  2021-09-03  63.349998  65.290001  62.750000  63.889999  63.889999

          Volume
0           2100
1           2000
2              0
3            400
4           3900
...          ...
3118   275200000
3119  1699070000
3120   511160000
3121   698180000
3122  1693650000

[3123 rows x 7 columns]
tolistdate: 0       2006-07-06
1       2006-07-07
2       2006-07-10
3       2006-07-11
4       2006-07-12
           ...
3118    2021-08-30
3119    2021-08-31
3120    2021-09-01
3121    2021-09-02
3122    2021-09-03
Name: Date, Length: 3123, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  APPS_ended_2021-09-25  2006-07-06         63.89   0.56  102.56        10.2

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     10.76     20.96     31.16     41.36     51.56     61.76     71.96

  markup_80 markup_90 markup_100
0     82.16     92.36     102.56
                   stock  start_date current_price minall  maxall each_markup  \
0  APPS_ended_2021-09-25  2006-07-06         63.89   0.56  102.56        10.2

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     10.76     20.96     31.16     41.36     51.56     61.76     71.96

  markup_80 markup_90 markup_100
0     82.16     92.36     102.56
./ticker_data/ticker_data_2021-09-25 - Copy/APP_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2021-04-15  70.000000  71.510002  63.000000  65.199997  65.199997
1    2021-04-16  65.000000  65.199997  58.650002  61.000000  61.000000
2    2021-04-19  60.000000  61.000000  55.705002  58.860001  58.860001
3    2021-04-20  60.040001  61.900002  58.990002  60.150002  60.150002
4    2021-04-21  60.490002  62.209999  56.526001  61.810001  61.810001
..          ...        ...        ...        ...        ...        ...
109  2021-09-20  70.589996  73.959999  69.339996  70.339996  70.339996
110  2021-09-21  70.470001  74.389999  70.139999  74.089996  74.089996
111  2021-09-22  74.089996  75.739998  72.889999  73.080002  73.080002
112  2021-09-23  76.000000  79.889999  75.639999  77.849998  77.849998
113  2021-09-24  77.720001  80.730003  77.480003  79.514999  79.514999

       Volume
0    11444400
1     4199300
2     4642500
3     3055500
4     3607100
..        ...
109    843600
110    632000
111   1003600
112   1300100
113   1050612

[114 rows x 7 columns]
tolistdate: 0      2021-04-15
1      2021-04-16
2      2021-04-19
3      2021-04-20
4      2021-04-21
          ...
109    2021-09-20
110    2021-09-21
111    2021-09-22
112    2021-09-23
113    2021-09-24
Name: Date, Length: 114, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  APP_ended_2021-09-25  2021-04-15        79.515  49.41  90.03       4.062

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    53.472    57.534    61.596    65.658     69.72    73.782    77.844

  markup_80 markup_90 markup_100
0    81.906    85.968      90.03
                  stock  start_date current_price minall maxall each_markup  \
0  APP_ended_2021-09-25  2021-04-15        79.515  49.41  90.03       4.062

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    53.472    57.534    61.596    65.658     69.72    73.782    77.844

  markup_80 markup_90 markup_100
0    81.906    85.968      90.03
./ticker_data/ticker_data_2021-09-25 - Copy/APRE_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-10-03  15.455000  21.000000  15.100000  20.500000  20.500000
1    2019-10-04  19.520000  20.115999  18.670000  19.070000  19.070000
2    2019-10-07  19.170000  20.900000  19.010000  20.250000  20.250000
3    2019-10-08  20.200001  20.677000  18.549999  18.940001  18.940001
4    2019-10-09  18.940001  21.610001  18.663000  19.040001  19.040001
..          ...        ...        ...        ...        ...        ...
494  2021-09-20   5.470000   5.590000   4.730000   4.850000   4.850000
495  2021-09-21   4.940000   5.050000   4.440000   4.670000   4.670000
496  2021-09-22   4.570000   4.630000   4.320000   4.500000   4.500000
497  2021-09-23   4.480000   4.640000   4.320000   4.530000   4.530000
498  2021-09-24   4.500000   4.760000   4.410000   4.680000   4.680000

       Volume
0     1820600
1      256500
2      132300
3      103400
4      183200
..        ...
494  19275800
495   8904200
496   2548500
497   1844900
498    720610

[499 rows x 7 columns]
tolistdate: 0      2019-10-03
1      2019-10-04
2      2019-10-07
3      2019-10-08
4      2019-10-09
          ...
494    2021-09-20
495    2021-09-21
496    2021-09-22
497    2021-09-23
498    2021-09-24
Name: Date, Length: 499, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  APRE_ended_2021-09-25  2019-10-03          4.68   3.17  53.11       4.994

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.164    13.158    18.152    23.146     28.14    33.134    38.128

  markup_80 markup_90 markup_100
0    43.122    48.116      53.11
                   stock  start_date current_price minall maxall each_markup  \
0  APRE_ended_2021-09-25  2019-10-03          4.68   3.17  53.11       4.994

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.164    13.158    18.152    23.146     28.14    33.134    38.128

  markup_80 markup_90 markup_100
0    43.122    48.116      53.11
./ticker_data/ticker_data_2021-09-25 - Copy/APR_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2021-02-11  28.000000  28.010000  22.000000  23.360001  23.360001
1    2021-02-12  23.870001  23.870001  20.780001  20.990000  20.990000
2    2021-02-16  21.150000  22.100000  21.000000  21.600000  21.600000
3    2021-02-17  21.320000  21.572001  20.250000  21.150000  21.150000
4    2021-02-18  20.760000  21.420000  20.350000  20.750000  20.750000
..          ...        ...        ...        ...        ...        ...
152  2021-09-20  37.310001  38.000000  36.709999  37.290001  37.290001
153  2021-09-21  37.709999  38.270000  37.110001  37.160000  37.160000
154  2021-09-22  37.209999  38.299999  36.740002  37.110001  37.110001
155  2021-09-23  37.410000  37.500000  36.029999  36.490002  36.490002
156  2021-09-24  36.610001  36.619999  35.730000  35.849998  35.849998

      Volume
0    2404000
1     875900
2     577400
3     374600
4     340500
..       ...
152   315300
153   274400
154   269700
155   305900
156   113248

[157 rows x 7 columns]
tolistdate: 0      2021-02-11
1      2021-02-12
2      2021-02-16
3      2021-02-17
4      2021-02-18
          ...
152    2021-09-20
153    2021-09-21
154    2021-09-22
155    2021-09-23
156    2021-09-24
Name: Date, Length: 157, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  APR_ended_2021-09-25  2021-02-11         35.85  20.07     40       1.993

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    22.063    24.056    26.049    28.042    30.035    32.028    34.021

  markup_80 markup_90 markup_100
0    36.014    38.007         40
                  stock  start_date current_price minall maxall each_markup  \
0  APR_ended_2021-09-25  2021-02-11         35.85  20.07     40       1.993

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    22.063    24.056    26.049    28.042    30.035    32.028    34.021

  markup_80 markup_90 markup_100
0    36.014    38.007         40
./ticker_data/ticker_data_2021-09-25 - Copy/APTO_ended_2021-09-25.csv
            Date     Open      High      Low    Close  Adj Close  Volume
0     1999-12-31  258.750  326.2500  253.125  320.625    320.625     624
1     2000-01-03  303.750  472.5000  286.875  472.500    472.500    2348
2     2000-01-04  388.125  393.7500  315.000  376.875    376.875    1237
3     2000-01-05  427.500  540.0000  393.750  540.000    540.000    1020
4     2000-01-06  618.750  765.0000  540.000  607.500    607.500    1782
...          ...      ...       ...      ...      ...        ...     ...
4752  2021-09-20    2.690    2.6900    2.550    2.560      2.560  571500
4753  2021-09-21    2.590    2.6700    2.580    2.650      2.650  905900
4754  2021-09-22    2.660    2.6700    2.580    2.610      2.610  590400
4755  2021-09-23    2.610    2.6300    2.530    2.600      2.600  992500
4756  2021-09-24    2.600    2.6299    2.510    2.553      2.553  417837

[4757 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
4752    2021-09-20
4753    2021-09-21
4754    2021-09-22
4755    2021-09-23
4756    2021-09-24
Name: Date, Length: 4757, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  APTO_ended_2021-09-25  1999-12-31         2.553   0.78   2205     220.422

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   221.202   441.624   662.046   882.468   1102.89   1323.31   1543.73

  markup_80 markup_90 markup_100
0   1764.16   1984.58       2205
                   stock  start_date current_price minall maxall each_markup  \
0  APTO_ended_2021-09-25  1999-12-31         2.553   0.78   2205     220.422

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   221.202   441.624   662.046   882.468   1102.89   1323.31   1543.73

  markup_80 markup_90 markup_100
0   1764.16   1984.58       2205
./ticker_data/ticker_data_2021-09-25 - Copy/APTX_ended_2021-09-25.csv
           Date       Open       High    Low      Close  Adj Close   Volume
0    2018-06-21  17.400000  20.879999  17.35  20.200001  20.200001  3507600
1    2018-06-22  19.790001  20.450001  18.74  20.000000  20.000000   333200
2    2018-06-25  20.000000  20.490000  19.02  19.830000  19.830000   576500
3    2018-06-26  20.040001  20.700001  19.01  20.000000  20.000000   535800
4    2018-06-27  20.000000  22.620001  19.73  22.240000  22.240000   498900
..          ...        ...        ...    ...        ...        ...      ...
817  2021-09-20   2.380000   2.480000   2.37   2.370000   2.370000   140700
818  2021-09-21   2.410000   2.480000   2.38   2.450000   2.450000   120600
819  2021-09-22   2.460000   2.500000   2.38   2.410000   2.410000   163900
820  2021-09-23   2.410000   2.460000   2.38   2.390000   2.390000   269400
821  2021-09-24   2.350000   2.430000   2.35   2.385000   2.385000   146407

[822 rows x 7 columns]
tolistdate: 0      2018-06-21
1      2018-06-22
2      2018-06-25
3      2018-06-26
4      2018-06-27
          ...
817    2021-09-20
818    2021-09-21
819    2021-09-22
820    2021-09-23
821    2021-09-24
Name: Date, Length: 822, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  APTX_ended_2021-09-25  2018-06-21         2.385    1.6  32.25       3.065

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.665      7.73    10.795     13.86    16.925     19.99    23.055

  markup_80 markup_90 markup_100
0     26.12    29.185      32.25
                   stock  start_date current_price minall maxall each_markup  \
0  APTX_ended_2021-09-25  2018-06-21         2.385    1.6  32.25       3.065

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.665      7.73    10.795     13.86    16.925     19.99    23.055

  markup_80 markup_90 markup_100
0     26.12    29.185      32.25
./ticker_data/ticker_data_2021-09-25 - Copy/APVO_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2016-07-20  112.000000  112.000000  112.000000  112.000000  112.000000
1     2016-07-21  112.000000  112.000000  112.000000  112.000000  112.000000
2     2016-07-22  112.000000  112.000000  110.180000  110.180000  110.180000
3     2016-07-25   84.699997   94.500000   84.699997   94.500000   94.500000
4     2016-07-26   98.000000   98.000000   95.339996   96.599998   96.599998
...          ...         ...         ...         ...         ...         ...
1301  2021-09-20   17.010000   17.559999   16.670000   16.670000   16.670000
1302  2021-09-21   16.910000   17.540001   16.910000   17.049999   17.049999
1303  2021-09-22   17.299999   17.620001   16.950001   16.995001   16.995001
1304  2021-09-23   17.299999   17.299999   16.658001   16.900000   16.900000
1305  2021-09-24   16.680000   17.049999   16.635000   16.785000   16.785000

      Volume
0         43
1          0
2         43
3       2243
4       1736
...      ...
1301   74100
1302   47300
1303   31300
1304   70700
1305   13275

[1306 rows x 7 columns]
tolistdate: 0       2016-07-20
1       2016-07-21
2       2016-07-22
3       2016-07-25
4       2016-07-26
           ...
1301    2021-09-20
1302    2021-09-21
1303    2021-09-22
1304    2021-09-23
1305    2021-09-24
Name: Date, Length: 1306, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  APVO_ended_2021-09-25  2016-07-20        16.785   2.94  116.06      11.312

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    14.252    25.564    36.876    48.188      59.5    70.812    82.124

  markup_80 markup_90 markup_100
0    93.436   104.748     116.06
                   stock  start_date current_price minall  maxall each_markup  \
0  APVO_ended_2021-09-25  2016-07-20        16.785   2.94  116.06      11.312

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    14.252    25.564    36.876    48.188      59.5    70.812    82.124

  markup_80 markup_90 markup_100
0    93.436   104.748     116.06
./ticker_data/ticker_data_2021-09-25 - Copy/APWC_ended_2021-09-25.csv
            Date  Open  High   Low  Close  Adj Close   Volume
0     2003-07-15  2.55  2.55  2.35   2.40   2.252263     5500
1     2003-07-16  2.40  2.40  2.20   2.40   2.252263    13900
2     2003-07-17  2.40  2.60  2.20   2.60   2.439951    23300
3     2003-07-18  2.31  2.37  2.25   2.35   2.205340    21200
4     2003-07-21  1.90  2.10  1.90   2.00   1.876886    66100
...          ...   ...   ...   ...    ...        ...      ...
3764  2021-08-30  3.37  3.52  3.20   3.44   3.440000  2630000
3765  2021-08-31  3.36  3.58  3.27   3.44   3.440000  3580000
3766  2021-09-01  3.43  3.50  3.28   3.36   3.360000  1250000
3767  2021-09-02  3.42  3.42  3.20   3.31   3.310000  1820000
3768  2021-09-03  3.26  3.26  3.17   3.17   3.170000  1230000

[3769 rows x 7 columns]
tolistdate: 0       2003-07-15
1       2003-07-16
2       2003-07-17
3       2003-07-18
4       2003-07-21
           ...
3764    2021-08-30
3765    2021-08-31
3766    2021-09-01
3767    2021-09-02
3768    2021-09-03
Name: Date, Length: 3769, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  APWC_ended_2021-09-25  2003-07-15          3.17    0.5    8.8        0.83

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      1.33      2.16      2.99      3.82      4.65      5.48      6.31

  markup_80 markup_90 markup_100
0      7.14      7.97        8.8
                   stock  start_date current_price minall maxall each_markup  \
0  APWC_ended_2021-09-25  2003-07-15          3.17    0.5    8.8        0.83

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      1.33      2.16      2.99      3.82      4.65      5.48      6.31

  markup_80 markup_90 markup_100
0      7.14      7.97        8.8
./ticker_data/ticker_data_2021-09-25 - Copy/APYX_ended_2021-09-25.csv
           Date   Open    High     Low  Close  Adj Close   Volume
0    2019-01-02   7.96   7.960   6.211   6.47       6.47   104900
1    2019-01-03   6.75   6.750   6.100   6.50       6.50   130400
2    2019-01-04   6.50   6.975   6.450   6.62       6.62   108700
3    2019-01-07   6.84   8.530   6.750   7.49       7.49   401900
4    2019-01-08   7.50   8.100   7.493   7.74       7.74   299400
..          ...    ...     ...     ...    ...        ...      ...
669  2021-08-30  11.43  11.550  11.420  11.43      11.43  3290000
670  2021-08-31  11.43  11.850  11.160  11.81      11.81  9160000
671  2021-09-01  11.85  11.850  11.160  11.23      11.23  5830000
672  2021-09-02  11.30  11.580  11.200  11.36      11.36  3620000
673  2021-09-03  11.42  11.420  11.010  11.28      11.28  5510000

[674 rows x 7 columns]
tolistdate: 0      2019-01-02
1      2019-01-03
2      2019-01-04
3      2019-01-07
4      2019-01-08
          ...
669    2021-08-30
670    2021-08-31
671    2021-09-01
672    2021-09-02
673    2021-09-03
Name: Date, Length: 674, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  APYX_ended_2021-09-25  2019-01-02         11.28  2.805  12.01      0.9205

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    3.7255     4.646    5.5665     6.487    7.4075     8.328    9.2485

  markup_80 markup_90 markup_100
0    10.169   11.0895      12.01
                   stock  start_date current_price minall maxall each_markup  \
0  APYX_ended_2021-09-25  2019-01-02         11.28  2.805  12.01      0.9205

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    3.7255     4.646    5.5665     6.487    7.4075     8.328    9.2485

  markup_80 markup_90 markup_100
0    10.169   11.0895      12.01
./ticker_data/ticker_data_2021-09-25 - Copy/AQB_ended_2021-09-25.csv
            Date    Open       High        Low      Close  Adj Close    Volume
0     2017-01-11   5.200  26.490000   5.200000  26.490000  26.490000      2900
1     2017-01-12  30.500  30.500000  14.010000  17.209999  17.209999      2600
2     2017-01-13  17.150  17.150000  14.100000  15.600000  15.600000      1900
3     2017-01-17  17.670  19.719999  17.030001  17.030001  17.030001      1700
4     2017-01-18  16.430  16.930000  16.059999  16.059999  16.059999      1000
...          ...     ...        ...        ...        ...        ...       ...
1165  2021-08-30   4.640   4.710000   4.525000   4.540000   4.540000  52700000
1166  2021-08-31   4.530   4.710000   4.530000   4.630000   4.630000  56860000
1167  2021-09-01   4.551   4.655000   4.510000   4.630000   4.630000  70350000
1168  2021-09-02   4.630   4.750000   4.615000   4.700000   4.700000  53800000
1169  2021-09-03   4.710   4.719000   4.510000   4.580000   4.580000  66060000

[1170 rows x 7 columns]
tolistdate: 0       2017-01-11
1       2017-01-12
2       2017-01-13
3       2017-01-17
4       2017-01-18
           ...
1165    2021-08-30
1166    2021-08-31
1167    2021-09-01
1168    2021-09-02
1169    2021-09-03
Name: Date, Length: 1170, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  AQB_ended_2021-09-25  2017-01-11          4.58   1.51   30.5       2.899

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.409     7.308    10.207    13.106    16.005    18.904    21.803

  markup_80 markup_90 markup_100
0    24.702    27.601       30.5
                  stock  start_date current_price minall maxall each_markup  \
0  AQB_ended_2021-09-25  2017-01-11          4.58   1.51   30.5       2.899

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.409     7.308    10.207    13.106    16.005    18.904    21.803

  markup_80 markup_90 markup_100
0    24.702    27.601       30.5
./ticker_data/ticker_data_2021-09-25 - Copy/AQMS_ended_2021-09-25.csv
            Date   Open   High    Low  Close  Adj Close    Volume
0     2015-07-31  6.500  6.550  5.250  5.350      5.350    537500
1     2015-08-03  5.930  5.970  4.850  5.025      5.025    290700
2     2015-08-04  4.900  5.050  4.660  4.990      4.990    278600
3     2015-08-05  4.990  5.100  4.780  5.000      5.000    103900
4     2015-08-06  5.040  5.240  5.040  5.150      5.150     35500
...          ...    ...    ...    ...    ...        ...       ...
1531  2021-08-30  2.258  2.415  2.225  2.360      2.360  66670000
1532  2021-08-31  2.380  2.420  2.320  2.380      2.380  77810000
1533  2021-09-01  2.360  2.395  2.263  2.270      2.270  52420000
1534  2021-09-02  2.270  2.470  2.270  2.380      2.380  95530000
1535  2021-09-03  2.400  2.410  2.300  2.340      2.340  44120000

[1536 rows x 7 columns]
tolistdate: 0       2015-07-31
1       2015-08-03
2       2015-08-04
3       2015-08-05
4       2015-08-06
           ...
1531    2021-08-30
1532    2021-08-31
1533    2021-09-01
1534    2021-09-02
1535    2021-09-03
Name: Date, Length: 1536, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AQMS_ended_2021-09-25  2015-07-31          2.34   0.33  22.75       2.242

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.572     4.814     7.056     9.298     11.54    13.782    16.024

  markup_80 markup_90 markup_100
0    18.266    20.508      22.75
                   stock  start_date current_price minall maxall each_markup  \
0  AQMS_ended_2021-09-25  2015-07-31          2.34   0.33  22.75       2.242

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.572     4.814     7.056     9.298     11.54    13.782    16.024

  markup_80 markup_90 markup_100
0    18.266    20.508      22.75
./ticker_data/ticker_data_2021-09-25 - Copy/AQST_ended_2021-09-25.csv
           Date       Open       High     Low      Close  Adj Close     Volume
0    2018-07-25  15.100000  19.299999  15.020  16.049999  16.049999    3144000
1    2018-07-26  16.200001  16.665001  15.000  15.850000  15.850000     469700
2    2018-07-27  16.170000  16.195000  15.050  15.180000  15.180000     294400
3    2018-07-30  15.100000  15.320000  15.060  15.060000  15.060000      34100
4    2018-07-31  15.060000  15.417000  15.000  15.040000  15.040000     169300
..          ...        ...        ...     ...        ...        ...        ...
779  2021-08-30   4.130000   4.680000   4.130   4.660000   4.660000  205930000
780  2021-08-31   4.600000   4.600000   4.301   4.580000   4.580000  125340000
781  2021-09-01   4.568000   4.800000   4.420   4.630000   4.630000   81220000
782  2021-09-02   4.670000   4.780000   4.560   4.620000   4.620000   50560000
783  2021-09-03   4.660000   4.750000   4.390   4.530000   4.530000   53950000

[784 rows x 7 columns]
tolistdate: 0      2018-07-25
1      2018-07-26
2      2018-07-27
3      2018-07-30
4      2018-07-31
          ...
779    2021-08-30
780    2021-08-31
781    2021-09-01
782    2021-09-02
783    2021-09-03
Name: Date, Length: 784, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AQST_ended_2021-09-25  2018-07-25          4.53   1.41  20.696      1.9286

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    3.3386    5.2672    7.1958    9.1244    11.053   12.9816   14.9102

  markup_80 markup_90 markup_100
0   16.8388   18.7674     20.696
                   stock  start_date current_price minall  maxall each_markup  \
0  AQST_ended_2021-09-25  2018-07-25          4.53   1.41  20.696      1.9286

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    3.3386    5.2672    7.1958    9.1244    11.053   12.9816   14.9102

  markup_80 markup_90 markup_100
0   16.8388   18.7674     20.696
./ticker_data/ticker_data_2021-09-25 - Copy/ARAV_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2014-03-21  168.000000  217.800003  168.000000  188.220001  188.220001
1     2014-03-24  186.000000  195.899994  165.000000  177.839996  177.839996
2     2014-03-25  177.960007  200.880005  175.919998  186.720001  186.720001
3     2014-03-26  187.199997  197.873993  183.179993  185.220001  185.220001
4     2014-03-27  183.720001  185.639999  162.000000  180.059998  180.059998
...          ...         ...         ...         ...         ...         ...
1873  2021-08-30    4.050000    4.230000    4.050000    4.100000    4.100000
1874  2021-08-31    4.140000    4.400000    4.140000    4.320000    4.320000
1875  2021-09-01    4.340000    4.340000    4.121000    4.210000    4.210000
1876  2021-09-02    4.230000    4.310000    4.160000    4.270000    4.270000
1877  2021-09-03    4.270000    4.300000    4.030000    4.150000    4.150000

        Volume
0      1012700
1       129200
2        18900
3        18900
4        42400
...        ...
1873   7990000
1874  10460000
1875   6200000
1876   6870000
1877   7300000

[1878 rows x 7 columns]
tolistdate: 0       2014-03-21
1       2014-03-24
2       2014-03-25
3       2014-03-26
4       2014-03-27
           ...
1873    2021-08-30
1874    2021-08-31
1875    2021-09-01
1876    2021-09-02
1877    2021-09-03
Name: Date, Length: 1878, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ARAV_ended_2021-09-25  2014-03-21          4.15   3.07  221.16      21.809

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    24.879    46.688    68.497    90.306   112.115   133.924   155.733

  markup_80 markup_90 markup_100
0   177.542   199.351     221.16
                   stock  start_date current_price minall  maxall each_markup  \
0  ARAV_ended_2021-09-25  2014-03-21          4.15   3.07  221.16      21.809

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    24.879    46.688    68.497    90.306   112.115   133.924   155.733

  markup_80 markup_90 markup_100
0   177.542   199.351     221.16
./ticker_data/ticker_data_2021-09-25 - Copy/ARAY_ended_2021-09-25.csv
            Date   Open       High        Low      Close  Adj Close    Volume
0     2007-02-08  21.00  28.600000  20.549999  28.469999  28.469999  19190700
1     2007-02-09  28.50  31.090000  27.600000  29.250000  29.250000   3288700
2     2007-02-12  29.60  30.000000  27.850000  28.549999  28.549999    981100
3     2007-02-13  29.00  29.400000  26.770000  27.610001  27.610001   1350100
4     2007-02-14  27.60  28.200001  26.590000  26.620001  26.620001    840300
...          ...    ...        ...        ...        ...        ...       ...
3664  2021-08-30   4.06   4.080000   3.970000   3.970000   3.970000  24160000
3665  2021-08-31   3.93   4.100000   3.930000   4.070000   4.070000  24400000
3666  2021-09-01   4.11   4.130000   4.010000   4.040000   4.040000  29930000
3667  2021-09-02   4.02   4.100000   4.020000   4.060000   4.060000  16470000
3668  2021-09-03   4.07   4.090000   3.900000   3.950000   3.950000  38640000

[3669 rows x 7 columns]
tolistdate: 0       2007-02-08
1       2007-02-09
2       2007-02-12
3       2007-02-13
4       2007-02-14
           ...
3664    2021-08-30
3665    2021-08-31
3666    2021-09-01
3667    2021-09-02
3668    2021-09-03
Name: Date, Length: 3669, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARAY_ended_2021-09-25  2007-02-08          3.95   1.33  31.09       2.976

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.306     7.282    10.258    13.234     16.21    19.186    22.162

  markup_80 markup_90 markup_100
0    25.138    28.114      31.09
                   stock  start_date current_price minall maxall each_markup  \
0  ARAY_ended_2021-09-25  2007-02-08          3.95   1.33  31.09       2.976

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.306     7.282    10.258    13.234     16.21    19.186    22.162

  markup_80 markup_90 markup_100
0    25.138    28.114      31.09
./ticker_data/ticker_data_2021-09-25 - Copy/ARBGU_ended_2021-09-25.csv
           Date  Open   High    Low  Close  Adj Close   Volume
0    2020-11-20  9.86  9.930  9.850   9.85       9.85  5076400
1    2020-11-23  9.85  9.870  9.832   9.84       9.84   398700
2    2020-11-24  9.88  9.880  9.840   9.86       9.86  1171600
3    2020-11-25  9.85  9.870  9.840   9.87       9.87    97300
4    2020-11-27  9.84  9.905  9.820   9.88       9.88   173100
..          ...   ...    ...    ...    ...        ...      ...
159  2021-08-18  9.91  9.910  9.910   9.91       9.91        0
160  2021-08-19  9.90  9.900  9.890   9.90       9.90   550000
161  2021-08-20  9.90  9.900  9.900   9.90       9.90        0
162  2021-08-26  9.90  9.900  9.900   9.90       9.90   150000
163  2021-08-27  9.91  9.910  9.900   9.90       9.90   280000

[164 rows x 7 columns]
tolistdate: 0      2020-11-20
1      2020-11-23
2      2020-11-24
3      2020-11-25
4      2020-11-27
          ...
159    2021-08-18
160    2021-08-19
161    2021-08-20
162    2021-08-26
163    2021-08-27
Name: Date, Length: 164, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ARBGU_ended_2021-09-25  2020-11-20           9.9   9.74  11.14        0.14

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.88     10.02     10.16      10.3     10.44     10.58     10.72

  markup_80 markup_90 markup_100
0     10.86        11      11.14
                    stock  start_date current_price minall maxall each_markup  \
0  ARBGU_ended_2021-09-25  2020-11-20           9.9   9.74  11.14        0.14

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.88     10.02     10.16      10.3     10.44     10.58     10.72

  markup_80 markup_90 markup_100
0     10.86        11      11.14
./ticker_data/ticker_data_2021-09-25 - Copy/ARBGW_ended_2021-09-25.csv
         Date    Open  High   Low  Close  Adj Close  Volume
0  2021-09-22  0.7701   0.6  0.55   0.57       0.57   93768
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ARBGW_ended_2021-09-25  2021-09-22          0.57   0.55    0.6       0.005

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.555      0.56     0.565      0.57     0.575      0.58     0.585

  markup_80 markup_90 markup_100

0      0.59     0.595        0.6
                    stock  start_date current_price minall maxall each_markup  \
0  ARBGW_ended_2021-09-25  2021-09-22          0.57   0.55    0.6       0.005

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.555      0.56     0.565      0.57     0.575      0.58     0.585

  markup_80 markup_90 markup_100
0      0.59     0.595        0.6
./ticker_data/ticker_data_2021-09-25 - Copy/ARBG_ended_2021-09-25.csv
           Date   Open   High     Low  Close  Adj Close  Volume
0    2021-01-11  10.25  10.50  10.200  10.27      10.27    7400
1    2021-01-12  10.27  10.45  10.270  10.45      10.45    2200
2    2021-01-13  10.71  10.75  10.380  10.50      10.50   39500
3    2021-01-14  10.75  10.75  10.399  10.45      10.45   49400
4    2021-01-15  10.45  10.48  10.390  10.45      10.45    4400
..          ...    ...    ...     ...    ...        ...     ...
164  2021-09-14   9.74   9.75   9.740   9.74       9.74   19900
165  2021-09-20   9.70   9.72   9.670   9.72       9.72   25400
166  2021-09-21   9.72   9.72   9.720   9.72       9.72       0
167  2021-09-22   9.72   9.72   9.720   9.72       9.72     800
168  2021-09-23   9.72   9.72   9.720   9.72       9.72     700

[169 rows x 7 columns]
tolistdate: 0      2021-01-11
1      2021-01-12
2      2021-01-13
3      2021-01-14
4      2021-01-15
          ...
164    2021-09-14
165    2021-09-20
166    2021-09-21
167    2021-09-22
168    2021-09-23
Name: Date, Length: 169, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARBG_ended_2021-09-25  2021-01-11          9.72   9.43  10.75       0.132

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.562     9.694     9.826     9.958     10.09    10.222    10.354

  markup_80 markup_90 markup_100
0    10.486    10.618      10.75
                   stock  start_date current_price minall maxall each_markup  \
0  ARBG_ended_2021-09-25  2021-01-11          9.72   9.43  10.75       0.132

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.562     9.694     9.826     9.958     10.09    10.222    10.354

  markup_80 markup_90 markup_100
0    10.486    10.618      10.75
./ticker_data/ticker_data_2021-09-25 - Copy/ARCB_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  12.250000  12.312500  12.000000  12.000000   9.664385
1     2000-01-03  12.250000  12.687500  12.125000  12.562500  10.117401
2     2000-01-04  12.625000  12.750000  12.437500  12.718750  10.243240
3     2000-01-05  12.750000  12.875000  12.437500  12.750000  10.268408
4     2000-01-06  12.750000  13.375000  12.750000  13.187500  10.620753
...          ...        ...        ...        ...        ...        ...
5450  2021-08-30  68.400002  69.290001  67.029999  68.800003  68.800003
5451  2021-08-31  68.400002  68.739998  66.160004  66.730003  66.730003
5452  2021-09-01  67.239998  70.050003  65.540001  68.910004  68.910004
5453  2021-09-02  69.220001  70.910004  68.620003  69.889999  69.889999
5454  2021-09-03  69.839996  70.040001  68.709999  69.610001  69.610001

        Volume
0        23500
1        91700
2        37000
3        78100
4        56600
...        ...
5450  12750000
5451  19550000
5452  44690000
5453  18580000
5454  15270000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARCB_ended_2021-09-25  1999-12-31         69.61   6.43  93.96       8.753

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.183    23.936    32.689    41.442    50.195    58.948    67.701

  markup_80 markup_90 markup_100
0    76.454    85.207      93.96
                   stock  start_date current_price minall maxall each_markup  \
0  ARCB_ended_2021-09-25  1999-12-31         69.61   6.43  93.96       8.753

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.183    23.936    32.689    41.442    50.195    58.948    67.701

  markup_80 markup_90 markup_100
0    76.454    85.207      93.96
./ticker_data/ticker_data_2021-09-25 - Copy/ARCC_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2004-10-05  15.000000  15.190000  14.980000  15.020000   2.495760
1     2004-10-06  15.100000  15.100000  15.000000  15.000000   2.492437
2     2004-10-07  15.000000  15.200000  15.000000  15.150000   2.517361
3     2004-10-08  15.200000  15.400000  15.200000  15.300000   2.542286
4     2004-10-11  15.300000  15.400000  15.250000  15.350000   2.550594
...          ...        ...        ...        ...        ...        ...
4255  2021-08-30  20.200001  20.200001  19.959999  19.969999  19.969999
4256  2021-08-31  20.010000  20.090000  19.889999  19.900000  19.900000
4257  2021-09-01  19.930000  20.090000  19.910000  19.990000  19.990000
4258  2021-09-02  20.090000  20.230000  20.010000  20.219999  20.219999
4259  2021-09-03  20.209999  20.389999  20.200001  20.360001  20.360001

         Volume
0       4235200
1        539600
2        798200
3        465800
4        201800
...         ...
4255  180810000
4256  192930000
4257  153690000
4258  251670000
4259  234290000

[4260 rows x 7 columns]
tolistdate: 0       2004-10-05
1       2004-10-06
2       2004-10-07
3       2004-10-08
4       2004-10-11
           ...
4255    2021-08-30
4256    2021-08-31
4257    2021-09-01
4258    2021-09-02
4259    2021-09-03
Name: Date, Length: 4260, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARCC_ended_2021-09-25  2004-10-05         20.36   3.12  20.55       1.743

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.863     6.606     8.349    10.092    11.835    13.578    15.321

  markup_80 markup_90 markup_100
0    17.064    18.807      20.55
                   stock  start_date current_price minall maxall each_markup  \
0  ARCC_ended_2021-09-25  2004-10-05         20.36   3.12  20.55       1.743

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.863     6.606     8.349    10.092    11.835    13.578    15.321

  markup_80 markup_90 markup_100
0    17.064    18.807      20.55
./ticker_data/ticker_data_2021-09-25 - Copy/ARCE_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-09-26  24.500000  25.590000  23.160000  23.500000  23.500000
1    2018-09-27  23.969999  25.200001  23.000000  23.690001  23.690001
2    2018-09-28  23.570000  23.879999  22.230000  22.799999  22.799999
3    2018-10-01  22.750000  22.750000  20.600000  21.980000  21.980000
4    2018-10-02  22.000000  22.320000  21.129999  21.920000  21.920000
..          ...        ...        ...        ...        ...        ...
735  2021-08-30  23.200001  23.559999  22.180000  23.510000  23.510000
736  2021-08-31  23.620001  24.719999  23.620001  24.180000  24.180000
737  2021-09-01  24.200001  24.440001  23.940001  24.000000  24.000000
738  2021-09-02  24.080000  24.219999  23.120001  23.900000  23.900000
739  2021-09-03  23.990000  24.620001  23.700001  24.379999  24.379999

       Volume
0     7353800
1     1119100
2      722600
3      702000
4      653500
..        ...
735  49910000
736  10310000
737  13000000
738  28360000
739  22380000

[740 rows x 7 columns]
tolistdate: 0      2018-09-26
1      2018-09-27
2      2018-09-28
3      2018-10-01
4      2018-10-02
          ...
735    2021-08-30
736    2021-08-31
737    2021-09-01
738    2021-09-02
739    2021-09-03
Name: Date, Length: 740, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARCE_ended_2021-09-25  2018-09-26         24.38  17.68  59.49       4.181

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    21.861    26.042    30.223    34.404    38.585    42.766    46.947

  markup_80 markup_90 markup_100
0    51.128    55.309      59.49
                   stock  start_date current_price minall maxall each_markup  \
0  ARCE_ended_2021-09-25  2018-09-26         24.38  17.68  59.49       4.181

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    21.861    26.042    30.223    34.404    38.585    42.766    46.947

  markup_80 markup_90 markup_100
0    51.128    55.309      59.49
./ticker_data/ticker_data_2021-09-25 - Copy/ARCT_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2013-05-22  57.750000  58.099998  50.119999  52.849998  52.849998
1     2013-05-23  50.750000  52.500000  50.119999  50.470001  50.470001
2     2013-05-24  50.400002  51.799999  47.950001  50.750000  50.750000
3     2013-05-28  55.299999  55.299999  47.669998  48.790001  48.790001
4     2013-05-29  49.630001  49.630001  47.810001  47.950001  47.950001
...          ...        ...        ...        ...        ...        ...
2083  2021-08-30  57.230000  57.400002  53.189999  53.669998  53.669998
2084  2021-08-31  53.130001  56.650002  52.009998  54.810001  54.810001
2085  2021-09-01  54.610001  58.320000  53.610001  56.400002  56.400002
2086  2021-09-02  57.180000  58.450001  56.500000  57.220001  57.220001
2087  2021-09-03  56.500000  56.619999  53.299999  54.279999  54.279999

        Volume
0       225400
1        23500
2        12200
3         9100
4         9200
...        ...
2083  67720000
2084  54070000
2085  54090000
2086  45250000
2087  47240000

[2088 rows x 7 columns]
tolistdate: 0       2013-05-22
1       2013-05-23
2       2013-05-24
3       2013-05-28
4       2013-05-29
           ...
2083    2021-08-30
2084    2021-08-31
2085    2021-09-01
2086    2021-09-02
2087    2021-09-03
Name: Date, Length: 2088, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ARCT_ended_2021-09-25  2013-05-22         54.28   4.11  188.72      18.461

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    22.571    41.032    59.493    77.954    96.415   114.876   133.337

  markup_80 markup_90 markup_100
0   151.798   170.259     188.72
                   stock  start_date current_price minall  maxall each_markup  \
0  ARCT_ended_2021-09-25  2013-05-22         54.28   4.11  188.72      18.461

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    22.571    41.032    59.493    77.954    96.415   114.876   133.337

  markup_80 markup_90 markup_100
0   151.798   170.259     188.72
./ticker_data/ticker_data_2021-09-25 - Copy/ARDS_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close   Volume
0    2018-08-14  13.02  13.85  12.61  13.00      13.00   519800
1    2018-08-15  13.00  13.03  12.85  12.96      12.96    81700
2    2018-08-16  12.86  13.00  12.85  12.92      12.92    21200
3    2018-08-17  12.85  12.98  12.85  12.93      12.93    14900
4    2018-08-20  13.04  13.04  12.85  12.85      12.85    27400
..          ...    ...    ...    ...    ...        ...      ...
765  2021-08-30   3.77   3.88   3.63   3.73       3.73  6630000
766  2021-08-31   3.75   4.06   3.75   4.02       4.02  3420000
767  2021-09-01   3.98   4.33   3.94   4.19       4.19  6340000
768  2021-09-02   4.20   4.29   4.12   4.20       4.20  2000000
769  2021-09-03   4.23   4.34   4.15   4.15       4.15  2210000

[770 rows x 7 columns]
tolistdate: 0      2018-08-14
1      2018-08-15
2      2018-08-16
3      2018-08-17
4      2018-08-20
          ...
765    2021-08-30
766    2021-08-31
767    2021-09-01
768    2021-09-02
769    2021-09-03
Name: Date, Length: 770, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARDS_ended_2021-09-25  2018-08-14          4.15   3.54  13.85       1.031

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.571     5.602     6.633     7.664     8.695     9.726    10.757

  markup_80 markup_90 markup_100
0    11.788    12.819      13.85
                   stock  start_date current_price minall maxall each_markup  \
0  ARDS_ended_2021-09-25  2018-08-14          4.15   3.54  13.85       1.031

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.571     5.602     6.633     7.664     8.695     9.726    10.757

  markup_80 markup_90 markup_100
0    11.788    12.819      13.85
./ticker_data/ticker_data_2021-09-25 - Copy/ARDX_ended_2021-09-25.csv
            Date    Open   High    Low  Close  Adj Close      Volume
0     2014-06-19  14.500  14.88  14.09  14.11      14.11     1583100
1     2014-06-20  14.060  14.54  14.05  14.31      14.31       74500
2     2014-06-23  14.360  15.88  14.36  15.15      15.15       99600
3     2014-06-24  15.200  16.00  15.20  15.81      15.81       50200
4     2014-06-25  15.670  15.93  15.35  15.45      15.45       30900
...          ...     ...    ...    ...    ...        ...         ...
1812  2021-08-30   1.455   1.47   1.42   1.44       1.44   206950000
1813  2021-08-31   1.430   1.46   1.41   1.41       1.41   291740000
1814  2021-09-01   1.414   1.47   1.40   1.45       1.45   237020000
1815  2021-09-02   1.460   1.47   1.44   1.45       1.45   154290000
1816  2021-09-03   1.560   1.58   1.42   1.44       1.44  1432530000

[1817 rows x 7 columns]
tolistdate: 0       2014-06-19
1       2014-06-20
2       2014-06-23
3       2014-06-24
4       2014-06-25
           ...
1812    2021-08-30
1813    2021-08-31
1814    2021-09-01
1815    2021-09-02
1816    2021-09-03
Name: Date, Length: 1817, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARDX_ended_2021-09-25  2014-06-19          1.44   1.28  35.48        3.42

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0       4.7      8.12     11.54     14.96     18.38      21.8     25.22

  markup_80 markup_90 markup_100
0     28.64     32.06      35.48
                   stock  start_date current_price minall maxall each_markup  \
0  ARDX_ended_2021-09-25  2014-06-19          1.44   1.28  35.48        3.42

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0       4.7      8.12     11.54     14.96     18.38      21.8     25.22

  markup_80 markup_90 markup_100
0     28.64     32.06      35.48
./ticker_data/ticker_data_2021-09-25 - Copy/AREC_ended_2021-09-25.csv
           Date   Open   High   Low  Close  Adj Close    Volume
0    2017-06-30  1.000  1.000  1.00   1.00       1.00         0
1    2017-07-05  0.750  0.750  0.75   0.75       0.75      7400
2    2017-07-06  0.750  0.750  0.75   0.75       0.75         0
3    2017-07-10  0.510  0.510  0.51   0.51       0.51      2000
4    2017-07-11  0.510  0.510  0.51   0.51       0.51         0
..          ...    ...    ...   ...    ...        ...       ...
808  2021-08-30  2.200  2.200  2.09   2.17       2.17  75530000
809  2021-08-31  2.170  2.250  2.15   2.24       2.24  68600000
810  2021-09-01  2.186  2.250  2.16   2.23       2.23  49880000
811  2021-09-02  2.229  2.350  2.22   2.27       2.27  81880000
812  2021-09-03  2.290  2.405  2.22   2.39       2.39  75360000

[813 rows x 7 columns]
tolistdate: 0      2017-06-30
1      2017-07-05
2      2017-07-06
3      2017-07-10
4      2017-07-11
          ...
808    2021-08-30
809    2021-08-31
810    2021-09-01
811    2021-09-02
812    2021-09-03
Name: Date, Length: 813, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AREC_ended_2021-09-25  2017-06-30          2.39   0.05     14       1.395

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.445      2.84     4.235      5.63     7.025      8.42     9.815

  markup_80 markup_90 markup_100
0     11.21    12.605         14
                   stock  start_date current_price minall maxall each_markup  \
0  AREC_ended_2021-09-25  2017-06-30          2.39   0.05     14       1.395

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.445      2.84     4.235      5.63     7.025      8.42     9.815

  markup_80 markup_90 markup_100
0     11.21    12.605         14
./ticker_data/ticker_data_2021-09-25 - Copy/ARGX_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2017-05-18   17.900000   25.000000   17.330000   23.000000   23.000000
1     2017-05-19   22.100000   22.680000   21.059999   21.850000   21.850000
2     2017-05-22   21.959999   21.959999   20.610001   21.410000   21.410000
3     2017-05-23   21.160000   21.170000   20.632000   20.969999   20.969999
4     2017-05-24   20.570000   21.430000   20.389999   20.620001   20.620001
...          ...         ...         ...         ...         ...         ...
1076  2021-08-30  336.679993  339.700012  336.230011  336.899994  336.899994
1077  2021-08-31  342.640015  344.149994  327.000000  331.019989  331.019989
1078  2021-09-01  333.850006  338.339996  330.899994  337.910004  337.910004
1079  2021-09-02  347.809998  351.725006  345.670013  349.070007  349.070007
1080  2021-09-03  345.929993  352.890015  345.309998  350.579987  350.579987

        Volume
0       798800
1       219200
2        49000
3        33500
4        31700
...        ...
1076   6200000
1077  49690000
1078  19790000
1079  14220000
1080   8550000

[1081 rows x 7 columns]
tolistdate: 0       2017-05-18
1       2017-05-19
2       2017-05-22
3       2017-05-23
4       2017-05-24
           ...
1076    2021-08-30
1077    2021-08-31
1078    2021-09-01
1079    2021-09-02
1080    2021-09-03
Name: Date, Length: 1081, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ARGX_ended_2021-09-25  2017-05-18        350.58  17.33  382.15      36.482

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    53.812    90.294   126.776   163.258    199.74   236.222   272.704

  markup_80 markup_90 markup_100
0   309.186   345.668     382.15
                   stock  start_date current_price minall  maxall each_markup  \
0  ARGX_ended_2021-09-25  2017-05-18        350.58  17.33  382.15      36.482

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    53.812    90.294   126.776   163.258    199.74   236.222   272.704

  markup_80 markup_90 markup_100
0   309.186   345.668     382.15
./ticker_data/ticker_data_2021-09-25 - Copy/ARKOW_ended_2021-09-25.csv
         Date  Open  High   Low  Close  Adj Close  Volume
0  2021-09-24  2.15  2.24  2.05   2.16       2.16   35068
tolistdate: 0    2021-09-24
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ARKOW_ended_2021-09-25  2021-09-24          2.16   2.05   2.24       0.019

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.069     2.088     2.107     2.126     2.145     2.164     2.183

  markup_80 markup_90 markup_100
0     2.202     2.221       2.24
                    stock  start_date current_price minall maxall each_markup  \
0  ARKOW_ended_2021-09-25  2021-09-24          2.16   2.05   2.24       0.019

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.069     2.088     2.107     2.126     2.145     2.164     2.183

  markup_80 markup_90 markup_100
0     2.202     2.221       2.24
./ticker_data/ticker_data_2021-09-25 - Copy/ARKO_ended_2021-09-25.csv
           Date    Open    High     Low  Close  Adj Close     Volume
0    2020-06-25  10.100  10.180  10.070  10.18      10.18      30900
1    2020-06-26  10.280  10.280  10.170  10.17      10.17       3000
2    2020-06-29  10.268  10.400  10.250  10.38      10.38      63200
3    2020-06-30  10.490  10.520  10.260  10.35      10.35     118500
4    2020-07-01  10.350  10.395  10.350  10.35      10.35      46400
..          ...     ...     ...     ...    ...        ...        ...
296  2021-08-30   9.790  10.240   9.682  10.17      10.17   97620000
297  2021-08-31  10.100  10.355   9.940  10.34      10.34  121770000
298  2021-09-01  10.250  10.485  10.170  10.41      10.41   88710000
299  2021-09-02  10.380  10.830  10.360  10.70      10.70   83360000
300  2021-09-03  10.750  10.980  10.620  10.75      10.75  103430000

[301 rows x 7 columns]
tolistdate: 0      2020-06-25
1      2020-06-26
2      2020-06-29
3      2020-06-30
4      2020-07-01
          ...
296    2021-08-30
297    2021-08-31
298    2021-09-01
299    2021-09-02
300    2021-09-03
Name: Date, Length: 301, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARKO_ended_2021-09-25  2020-06-25         10.75   7.32   11.4       0.408

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.728     8.136     8.544     8.952      9.36     9.768    10.176

  markup_80 markup_90 markup_100
0    10.584    10.992       11.4
                   stock  start_date current_price minall maxall each_markup  \
0  ARKO_ended_2021-09-25  2020-06-25         10.75   7.32   11.4       0.408

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.728     8.136     8.544     8.952      9.36     9.768    10.176

  markup_80 markup_90 markup_100
0    10.584    10.992       11.4
./ticker_data/ticker_data_2021-09-25 - Copy/ARKR_ended_2021-09-25.csv
            Date       Open       High      Low      Close  Adj Close   Volume
0     1999-12-31   8.250000   8.625000   8.2500   8.625000   3.426163     5000
1     2000-01-03   8.250000   8.250000   8.2500   8.250000   3.277200      400
2     2000-01-04   8.250000   8.250000   8.2500   8.250000   3.277200        0
3     2000-01-05   8.625000   9.000000   8.6250   8.687500   3.450990     8000
4     2000-01-06   8.687500   8.687500   8.6875   8.687500   3.450990        0
...          ...        ...        ...      ...        ...        ...      ...
5195  2021-08-30  16.420000  16.420000  16.0200  16.049999  16.049999   390000
5196  2021-08-31  16.219999  16.379999  16.0200  16.049999  16.049999   430000
5197  2021-09-01  16.200001  16.250000  16.0200  16.250000  16.250000   170000
5198  2021-09-02  16.139999  16.250000  15.7500  15.900000  15.900000   840000
5199  2021-09-03  16.020000  16.309999  15.7500  15.760000  15.760000  1450000

[5200 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5195    2021-08-30
5196    2021-08-31
5197    2021-09-01
5198    2021-09-02
5199    2021-09-03
Name: Date, Length: 5200, dtype: object
                   stock  start_date current_price  minall maxall each_markup  \
0  ARKR_ended_2021-09-25  1999-12-31         15.76  5.0625  43.48     3.84175

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   8.90425    12.746   16.5877   20.4295   24.2712    28.113   31.9547

  markup_80 markup_90 markup_100
0   35.7965   39.6382      43.48
                   stock  start_date current_price  minall maxall each_markup  \
0  ARKR_ended_2021-09-25  1999-12-31         15.76  5.0625  43.48     3.84175

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   8.90425    12.746   16.5877   20.4295   24.2712    28.113   31.9547

  markup_80 markup_90 markup_100
0   35.7965   39.6382      43.48
./ticker_data/ticker_data_2021-09-25 - Copy/ARLP_ended_2021-09-25.csv
            Date      Open      High      Low     Close  Adj Close    Volume
0     1999-12-31  3.031250  3.093750  3.03125  3.062500   0.592943    434800
1     2000-01-03  3.179688  3.390625  3.09375  3.390625   0.656473    255200
2     2000-01-04  3.375000  3.406250  3.31250  3.390625   0.656473    374400
3     2000-01-05  3.390625  3.390625  3.18750  3.375000   0.653448    208400
4     2000-01-06  3.351562  3.390625  3.28125  3.281250   0.635296    145600
...          ...       ...       ...      ...       ...        ...       ...
5450  2021-08-30  8.500000  8.540000  8.38000  8.390000   8.390000  20050000
5451  2021-08-31  8.350000  8.660000  8.33000  8.660000   8.660000  45130000
5452  2021-09-01  8.660000  8.750000  8.45000  8.660000   8.660000  25190000
5453  2021-09-02  8.750000  9.020000  8.75000  8.990000   8.990000  40590000
5454  2021-09-03  9.010000  9.200000  8.95000  9.150000   9.150000  36010000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARLP_ended_2021-09-25  1999-12-31          9.15   2.63  53.84       5.121

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.751    12.872    17.993    23.114    28.235    33.356    38.477

  markup_80 markup_90 markup_100
0    43.598    48.719      53.84
                   stock  start_date current_price minall maxall each_markup  \
0  ARLP_ended_2021-09-25  1999-12-31          9.15   2.63  53.84       5.121

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.751    12.872    17.993    23.114    28.235    33.356    38.477

  markup_80 markup_90 markup_100
0    43.598    48.719      53.84
./ticker_data/ticker_data_2021-09-25 - Copy/ARNA_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2000-07-28  240.000000  260.000000  210.000000  250.000000  250.000000
1     2000-07-31  232.500000  247.500000  230.000000  237.500000  237.500000
2     2000-08-01  240.000000  240.000000  235.000000  238.750000  238.750000
3     2000-08-02  240.000000  240.000000  236.250000  240.000000  240.000000
4     2000-08-03  236.250000  240.625000  235.000000  236.250000  236.250000
...          ...         ...         ...         ...         ...         ...
5304  2021-08-30   52.459999   53.119999   51.490002   51.750000   51.750000
5305  2021-08-31   51.889999   53.130001   51.610001   52.919998   52.919998
5306  2021-09-01   52.980000   58.000000   52.290001   56.779999   56.779999
5307  2021-09-02   57.200001   60.000000   56.340000   59.340000   59.340000
5308  2021-09-03   59.310001   61.180000   58.759998   60.250000   60.250000

         Volume
0        665400
1         61900
2         42300
3         20200
4         32200
...         ...
5304   40960000
5305   57470000
5306  101390000
5307   81890000
5308   82580000

[5309 rows x 7 columns]
tolistdate: 0       2000-07-28
1       2000-07-31
2       2000-08-01
3       2000-08-02
4       2000-08-03
           ...
5304    2021-08-30
5305    2021-08-31
5306    2021-09-01
5307    2021-09-02
5308    2021-09-03
Name: Date, Length: 5309, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARNA_ended_2021-09-25  2000-07-28         60.25   11.3    470       45.87

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     57.17    103.04    148.91    194.78    240.65    286.52    332.39

  markup_80 markup_90 markup_100
0    378.26    424.13        470
                   stock  start_date current_price minall maxall each_markup  \
0  ARNA_ended_2021-09-25  2000-07-28         60.25   11.3    470       45.87

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     57.17    103.04    148.91    194.78    240.65    286.52    332.39

  markup_80 markup_90 markup_100
0    378.26    424.13        470
./ticker_data/ticker_data_2021-09-25 - Copy/AROW_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   9.290407   9.758045   9.290407   9.695693   4.439808
1     2000-01-03   9.477462   9.851572   9.477462   9.602165   4.396979
2     2000-01-04   9.602165   9.726869   9.477462   9.664517   4.425531
3     2000-01-05   9.602165   9.851572   9.602165   9.664517   4.425531
4     2000-01-06   9.695693   9.695693   9.165704   9.602165   4.396979
...          ...        ...        ...        ...        ...        ...
5448  2021-08-30  36.680000  36.840000  36.380001  36.450001  36.450001
5449  2021-08-31  36.459999  36.959999  36.389999  36.849998  36.849998
5450  2021-09-01  37.000000  37.580002  36.119999  37.580002  37.580002
5451  2021-09-02  37.240002  37.470001  36.889999  37.020000  37.020000
5452  2021-09-03  36.980000  36.980000  36.299999  36.509998  36.509998

       Volume
0       18700
1       22000
2       13500
3       30000
4       79500
...       ...
5448  2170000
5449  3040000
5450  2810000
5451  1380000
5452  1380000

[5453 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5448    2021-08-30
5449    2021-08-31
5450    2021-09-01
5451    2021-09-02
5452    2021-09-03
Name: Date, Length: 5453, dtype: object
                   stock  start_date current_price  minall maxall each_markup  \
0  AROW_ended_2021-09-25  1999-12-31         36.51  7.1081  38.31     3.12019

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   10.2283   13.3485   16.4687   19.5889    22.709   25.8292   28.9494

  markup_80 markup_90 markup_100
0   32.0696   35.1898      38.31
                   stock  start_date current_price  minall maxall each_markup  \
0  AROW_ended_2021-09-25  1999-12-31         36.51  7.1081  38.31     3.12019

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   10.2283   13.3485   16.4687   19.5889    22.709   25.8292   28.9494

  markup_80 markup_90 markup_100
0   32.0696   35.1898      38.31
./ticker_data/ticker_data_2021-09-25 - Copy/ARPO_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2017-08-08  89.999550  89.999550  89.999550  89.999550  89.999550
1    2017-08-09  89.999550  89.999550  89.999550  89.999550  89.999550
2    2017-08-10  89.999550  89.999550  89.249550  89.249550  89.249550
3    2017-08-11  89.999550  89.999550  89.249550  89.249550  89.249550
4    2017-08-14  89.249550  89.249550  89.249550  89.249550  89.249550
..          ...        ...        ...        ...        ...        ...
980  2021-08-23  31.799841  33.299831  31.649841  33.299831  33.299831
981  2021-08-24  33.299831  33.749832  31.949841  33.449833  33.449833
982  2021-08-25  33.299831  34.124828  32.549835  33.299831  33.299831
983  2021-08-26  33.299831  34.499828  32.399837  32.999836  32.999836
984  2021-08-27        NaN        NaN        NaN        NaN        NaN

      Volume
0        6.0
1        0.0
2      666.0
3       13.0
4        0.0
..       ...
980  74059.0
981  51409.0
982  47448.0
983  55067.0
984      NaN

[985 rows x 7 columns]
tolistdate: 0      2017-08-08
1      2017-08-09
2      2017-08-10
3      2017-08-11
4      2017-08-14
          ...
980    2021-08-23
981    2021-08-24
982    2021-08-25
983    2021-08-26
984    2021-08-27
Name: Date, Length: 985, dtype: object
                   stock  start_date current_price   minall   maxall  \
0  ARPO_ended_2021-09-25  2017-08-08           NaN  6.29997  101.249

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     9.49495   15.7949   25.2899   34.7848   44.2798   53.7747   63.2697

  markup_70 markup_80 markup_90 markup_100
0   72.7646   82.2596   91.7545    101.249
                   stock  start_date current_price   minall   maxall  \
0  ARPO_ended_2021-09-25  2017-08-08           NaN  6.29997  101.249

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     9.49495   15.7949   25.2899   34.7848   44.2798   53.7747   63.2697

  markup_70 markup_80 markup_90 markup_100
0   72.7646   82.2596   91.7545    101.249
./ticker_data/ticker_data_2021-09-25 - Copy/ARQT_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-01-31  23.059999  24.400000  19.320000  21.799999  21.799999
1    2020-02-03  21.160000  25.820000  21.110001  25.129999  25.129999
2    2020-02-04  25.129999  27.450001  24.299999  25.639999  25.639999
3    2020-02-05  26.090000  26.090000  24.500000  25.230000  25.230000
4    2020-02-06  25.270000  25.549999  23.139999  24.740000  24.740000
..          ...        ...        ...        ...        ...        ...
397  2021-08-30  21.700001  22.280001  20.850000  21.070000  21.070000
398  2021-08-31  21.100000  21.389999  20.790001  21.170000  21.170000
399  2021-09-01  21.270000  21.700001  20.290001  21.270000  21.270000
400  2021-09-02  21.250000  22.760000  20.820000  22.160000  22.160000
401  2021-09-03  22.110001  22.110001  21.004999  21.650000  21.650000

       Volume
0     2931700
1      712500
2      247200
3      161300
4      223100
..        ...
397  10520000
398   6340000
399  23730000
400  25070000
401  25130000

[402 rows x 7 columns]
tolistdate: 0      2020-01-31
1      2020-02-03
2      2020-02-04
3      2020-02-05
4      2020-02-06
          ...
397    2021-08-30
398    2021-08-31
399    2021-09-01
400    2021-09-02
401    2021-09-03

Name: Date, Length: 402, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARQT_ended_2021-09-25  2020-01-31         21.65   17.1  40.88       2.378

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    19.478    21.856    24.234    26.612     28.99    31.368    33.746

  markup_80 markup_90 markup_100
0    36.124    38.502      40.88
                   stock  start_date current_price minall maxall each_markup  \
0  ARQT_ended_2021-09-25  2020-01-31         21.65   17.1  40.88       2.378

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    19.478    21.856    24.234    26.612     28.99    31.368    33.746

  markup_80 markup_90 markup_100
0    36.124    38.502      40.88
./ticker_data/ticker_data_2021-09-25 - Copy/ARRWU_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close   Volume
0    2021-03-02  10.01  10.05   9.98  10.00      10.00  8613900
1    2021-03-03  10.01  10.01   9.96  10.00      10.00  1380600
2    2021-03-04   9.99  10.02   9.96   9.98       9.98  1810100
3    2021-03-05  10.12  10.12   9.99  10.10      10.10   532300
4    2021-03-08  10.19  10.19  10.00  10.00      10.00   110400
..          ...    ...    ...    ...    ...        ...      ...
117  2021-09-16   9.87   9.87   9.87   9.87       9.87        0
118  2021-09-21   9.92   9.92   9.92   9.92       9.92      800
119  2021-09-22   9.92   9.95   9.92   9.94       9.94     5200
120  2021-09-23   9.94   9.94   9.94   9.94       9.94        0
121  2021-09-24   9.93   9.93   9.93   9.93       9.93      400

[122 rows x 7 columns]
tolistdate: 0      2021-03-02
1      2021-03-03
2      2021-03-04
3      2021-03-05
4      2021-03-08
          ...
117    2021-09-16
118    2021-09-21
119    2021-09-22
120    2021-09-23
121    2021-09-24
Name: Date, Length: 122, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ARRWU_ended_2021-09-25  2021-03-02          9.93    9.8  10.19   0.0389999

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.839     9.878     9.917     9.956     9.995    10.034    10.073

  markup_80 markup_90 markup_100
0    10.112    10.151      10.19
                    stock  start_date current_price minall maxall each_markup  \
0  ARRWU_ended_2021-09-25  2021-03-02          9.93    9.8  10.19   0.0389999

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.839     9.878     9.917     9.956     9.995    10.034    10.073

  markup_80 markup_90 markup_100
0    10.112    10.151      10.19
./ticker_data/ticker_data_2021-09-25 - Copy/ARRWW_ended_2021-09-25.csv
         Date    Open  High   Low  Close  Adj Close  Volume
0  2021-09-22  0.6201   0.6  0.58   0.58       0.58   14815
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ARRWW_ended_2021-09-25  2021-09-22          0.58   0.58    0.6       0.002

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.582     0.584     0.586     0.588      0.59     0.592     0.594

  markup_80 markup_90 markup_100
0     0.596     0.598        0.6
                    stock  start_date current_price minall maxall each_markup  \
0  ARRWW_ended_2021-09-25  2021-09-22          0.58   0.58    0.6       0.002

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.582     0.584     0.586     0.588      0.59     0.592     0.594

  markup_80 markup_90 markup_100
0     0.596     0.598        0.6
./ticker_data/ticker_data_2021-09-25 - Copy/ARRW_ended_2021-09-25.csv
          Date   Open   High   Low  Close  Adj Close  Volume
0   2021-04-26  9.660  9.660  9.65   9.66       9.66    2800
1   2021-04-27  9.680  9.720  9.67   9.68       9.68   22000
2   2021-04-28  9.700  9.870  9.68   9.68       9.68   34600
3   2021-04-29  9.663  9.764  9.66   9.72       9.72   63100
4   2021-04-30  9.710  9.720  9.66   9.72       9.72   25400
..         ...    ...    ...   ...    ...        ...     ...
70  2021-08-24  9.650  9.650  9.65   9.65       9.65   90000
71  2021-08-31  9.660  9.660  9.65   9.65       9.65   60000
72  2021-09-01  9.660  9.660  9.66   9.66       9.66  110000
73  2021-09-02  9.650  9.650  9.65   9.65       9.65  890000
74  2021-09-03  9.650  9.650  9.65   9.65       9.65  120000

[75 rows x 7 columns]
tolistdate: 0     2021-04-26
1     2021-04-27
2     2021-04-28
3     2021-04-29
4     2021-04-30
         ...
70    2021-08-24
71    2021-08-31
72    2021-09-01
73    2021-09-02
74    2021-09-03
Name: Date, Length: 75, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARRW_ended_2021-09-25  2021-04-26          9.65   9.61   9.87       0.026

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.636     9.662     9.688     9.714      9.74     9.766     9.792

  markup_80 markup_90 markup_100
0     9.818     9.844       9.87
                   stock  start_date current_price minall maxall each_markup  \
0  ARRW_ended_2021-09-25  2021-04-26          9.65   9.61   9.87       0.026

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.636     9.662     9.688     9.714      9.74     9.766     9.792

  markup_80 markup_90 markup_100
0     9.818     9.844       9.87
./ticker_data/ticker_data_2021-09-25 - Copy/ARRY_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-10-15  29.500000  37.349998  29.049999  36.450001  36.450001
1    2020-10-16  37.450001  41.939999  36.639999  38.950001  38.950001
2    2020-10-19  38.849998  40.500000  38.480000  38.950001  38.950001
3    2020-10-20  39.279999  40.730000  37.250000  38.500000  38.500000
4    2020-10-21  38.119999  42.099998  37.360001  39.340000  39.340000
..          ...        ...        ...        ...        ...        ...
219  2021-08-30  19.190001  19.420000  18.809999  18.920000  18.920000
220  2021-08-31  19.049999  19.480000  18.900000  19.070000  19.070000
221  2021-09-01  19.250000  19.250000  18.830000  18.980000  18.980000
222  2021-09-02  19.110001  19.990000  19.066000  19.360001  19.360001
223  2021-09-03  19.280001  19.600000  19.129999  19.500000  19.500000

        Volume
0     33963400
1     12251300
2      3539600
3      2853200
4      8694200
..         ...
219  175930000
220  215200000
221  142260000
222  230540000
223  125710000

[224 rows x 7 columns]
tolistdate: 0      2020-10-15
1      2020-10-16
2      2020-10-19
3      2020-10-20
4      2020-10-21
          ...
219    2021-08-30
220    2021-08-31
221    2021-09-01
222    2021-09-02
223    2021-09-03
Name: Date, Length: 224, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARRY_ended_2021-09-25  2020-10-15          19.5  12.72  54.78       4.206

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    16.926    21.132    25.338    29.544     33.75    37.956    42.162

  markup_80 markup_90 markup_100
0    46.368    50.574      54.78
                   stock  start_date current_price minall maxall each_markup  \
0  ARRY_ended_2021-09-25  2020-10-15          19.5  12.72  54.78       4.206

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    16.926    21.132    25.338    29.544     33.75    37.956    42.162

  markup_80 markup_90 markup_100
0    46.368    50.574      54.78
./ticker_data/ticker_data_2021-09-25 - Copy/ARTAU_ended_2021-09-25.csv
          Date   Open   High    Low  Close  Adj Close   Volume
0   2021-05-14  9.880  10.00  9.870  9.960      9.960  2971600
1   2021-05-17  9.950   9.95  9.870  9.915      9.915   148300
2   2021-05-18  9.990  10.00  9.880  9.901      9.901   394000
3   2021-05-19  9.960   9.98  9.930  9.965      9.965   179500
4   2021-05-20  9.950  10.00  9.950  9.950      9.950   220100
..         ...    ...    ...    ...    ...        ...      ...
71  2021-08-27  9.936   9.95  9.910  9.950      9.950   230000
72  2021-08-30  9.950   9.95  9.950  9.950      9.950        0
73  2021-09-01  9.860   9.93  9.860  9.910      9.910   210000
74  2021-09-02  9.910   9.91  9.910  9.910      9.910        0
75  2021-09-03  9.900   9.93  9.884  9.930      9.930   240000

[76 rows x 7 columns]
tolistdate: 0     2021-05-14
1     2021-05-17
2     2021-05-18
3     2021-05-19
4     2021-05-20
         ...
71    2021-08-27
72    2021-08-30
73    2021-09-01
74    2021-09-02
75    2021-09-03
Name: Date, Length: 76, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ARTAU_ended_2021-09-25  2021-05-14          9.93  9.822  10.15      0.0328

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.8548    9.8876    9.9204    9.9532     9.986   10.0188   10.0516

  markup_80 markup_90 markup_100
0   10.0844   10.1172      10.15
                    stock  start_date current_price minall maxall each_markup  \
0  ARTAU_ended_2021-09-25  2021-05-14          9.93  9.822  10.15      0.0328

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.8548    9.8876    9.9204    9.9532     9.986   10.0188   10.0516

  markup_80 markup_90 markup_100
0   10.0844   10.1172      10.15
./ticker_data/ticker_data_2021-09-25 - Copy/ARTLW_ended_2021-09-25.csv
         Date      Open    High     Low  Close  Adj Close  Volume
0  2021-09-22  0.301399  0.2501  0.1817   0.25       0.25    3650
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price  minall  maxall  \
0  ARTLW_ended_2021-09-25  2021-09-22          0.25  0.1817  0.2501

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00684   0.18854   0.19538   0.20222   0.20906    0.2159   0.22274

  markup_70 markup_80 markup_90 markup_100
0   0.22958   0.23642   0.24326     0.2501
                    stock  start_date current_price  minall  maxall  \
0  ARTLW_ended_2021-09-25  2021-09-22          0.25  0.1817  0.2501

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00684   0.18854   0.19538   0.20222   0.20906    0.2159   0.22274

  markup_70 markup_80 markup_90 markup_100
0   0.22958   0.23642   0.24326     0.2501
./ticker_data/ticker_data_2021-09-25 - Copy/ARTL_ended_2021-09-25.csv
           Date   Open  High    Low  Close  Adj Close    Volume
0    2019-06-21  4.900  4.95  4.210  4.650      4.650    274600
1    2019-06-24  4.940  5.00  4.310  4.930      4.930    130600
2    2019-06-25  4.930  4.93  4.490  4.600      4.600     55600
3    2019-06-26  4.610  4.90  4.510  4.900      4.900     24100
4    2019-06-27  4.880  4.93  4.650  4.930      4.930     32600
..          ...    ...   ...    ...    ...        ...       ...
552  2021-08-30  0.970  0.98  0.914  0.930      0.930  21830000
553  2021-08-31  0.915  0.95  0.911  0.911      0.911  18240000
554  2021-09-01  0.948  0.97  0.930  0.955      0.955  13780000
555  2021-09-02  0.950  0.96  0.931  0.943      0.943  13510000
556  2021-09-03  0.950  0.96  0.901  0.915      0.915  16790000

[557 rows x 7 columns]
tolistdate: 0      2019-06-21
1      2019-06-24
2      2019-06-25
3      2019-06-26
4      2019-06-27
          ...
552    2021-08-30
553    2021-08-31
554    2021-09-01
555    2021-09-02
556    2021-09-03
Name: Date, Length: 557, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARTL_ended_2021-09-25  2019-06-21         0.915  0.451      5      0.4549

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    0.9059    1.3608    1.8157    2.2706    2.7255    3.1804    3.6353

  markup_80 markup_90 markup_100
0    4.0902    4.5451          5
                   stock  start_date current_price minall maxall each_markup  \
0  ARTL_ended_2021-09-25  2019-06-21         0.915  0.451      5      0.4549

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    0.9059    1.3608    1.8157    2.2706    2.7255    3.1804    3.6353

  markup_80 markup_90 markup_100
0    4.0902    4.5451          5
./ticker_data/ticker_data_2021-09-25 - Copy/ARTNA_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  13.555555  14.000000  13.555555  14.000000   6.550218
1     2000-01-03  13.611111  13.722222  13.222222  13.222222   6.186317
2     2000-01-04  13.555555  13.666667  13.555555  13.555555   6.342276
3     2000-01-05  13.555555  13.611111  13.555555  13.555555   6.342276
4     2000-01-06  13.555555  13.666667  13.555555  13.555555   6.342276
...          ...        ...        ...        ...        ...        ...
5438  2021-08-30  38.450001  39.639999  38.450001  39.250000  39.250000
5439  2021-08-31  39.430000  40.189999  39.279999  39.410000  39.410000
5440  2021-09-01  39.380001  39.830002  38.950001  39.470001  39.470001
5441  2021-09-02  39.639999  39.740002  38.759998  39.020000  39.020000
5442  2021-09-03  38.970001  39.490002  38.830002  39.270000  39.270000

       Volume
0        2400
1       12100
2       24700
3       78700
4       35100
...       ...
5438  2160000
5439  1900000
5440  2090000
5441   930000
5442  1210000

[5443 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5438    2021-08-30
5439    2021-08-31
5440    2021-09-01
5441    2021-09-02
5442    2021-09-03
Name: Date, Length: 5443, dtype: object
                    stock  start_date current_price   minall maxall  \
0  ARTNA_ended_2021-09-25  1999-12-31         39.27  9.33333  43.22

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     3.38867    12.722   16.1107   19.4993    22.888   26.2767   29.6653

  markup_70 markup_80 markup_90 markup_100
0    33.054   36.4427   39.8313      43.22
                    stock  start_date current_price   minall maxall  \
0  ARTNA_ended_2021-09-25  1999-12-31         39.27  9.33333  43.22

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     3.38867    12.722   16.1107   19.4993    22.888   26.2767   29.6653

  markup_70 markup_80 markup_90 markup_100
0    33.054   36.4427   39.8313      43.22
./ticker_data/ticker_data_2021-09-25 - Copy/ARTW_ended_2021-09-25.csv
            Date     Open     High     Low   Close  Adj Close   Volume
0     1999-12-31  1.84375  1.84375  1.8125  1.8125   1.618885     2600
1     2000-01-03  1.81250  1.81250  1.8125  1.8125   1.618885        0
2     2000-01-05  1.87500  1.87500  1.8750  1.8750   1.674709      600
3     2000-01-06  1.81250  1.81250  1.8125  1.8125   1.618885      800
4     2000-01-10  1.87500  1.87500  1.8750  1.8750   1.674709     1000
...          ...      ...      ...     ...     ...        ...      ...
4788  2021-08-30  3.35000  3.53000  3.3300  3.4900   3.490000  1530000
4789  2021-08-31  3.42000  3.42000  3.3700  3.3700   3.370000   730000
4790  2021-09-01  3.36000  3.45000  3.3600  3.4500   3.450000    80000
4791  2021-09-02  3.45000  3.46000  3.3300  3.4600   3.460000  2780000
4792  2021-09-03  3.39000  3.41000  3.3200  3.3800   3.380000  1880000

[4793 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-05
3       2000-01-06
4       2000-01-10
           ...
4788    2021-08-30
4789    2021-08-31
4790    2021-09-01
4791    2021-09-02
4792    2021-09-03
Name: Date, Length: 4793, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ARTW_ended_2021-09-25  1999-12-31          3.38   0.81  19.875      1.9065

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.7165     4.623    6.5295     8.436   10.3425    12.249   14.1555

  markup_80 markup_90 markup_100

0    16.062   17.9685     19.875
                   stock  start_date current_price minall  maxall each_markup  \
0  ARTW_ended_2021-09-25  1999-12-31          3.38   0.81  19.875      1.9065

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.7165     4.623    6.5295     8.436   10.3425    12.249   14.1555

  markup_80 markup_90 markup_100
0    16.062   17.9685     19.875
./ticker_data/ticker_data_2021-09-25 - Copy/ARVL_ended_2021-09-25.csv
           Date    Open    High    Low  Close  Adj Close     Volume
0    2020-09-28  10.050  10.157  10.04  10.04      10.04       2000
1    2020-09-29  10.130  10.160  10.00  10.00      10.00      66600
2    2020-09-30  10.095  10.095  10.01  10.02      10.02      64900
3    2020-10-01  10.090  10.090  10.00  10.00      10.00      34900
4    2020-10-02   9.980  10.020   9.97  10.02      10.02      10400
..          ...     ...     ...    ...    ...        ...        ...
201  2021-08-30  11.270  12.070  10.77  11.90      11.90  284360000
202  2021-08-31  11.820  12.030  11.40  11.77      11.77  147020000
203  2021-09-01  11.660  12.210  11.51  12.14      12.14  132490000
204  2021-09-02  12.140  12.600  12.11  12.40      12.40  138660000
205  2021-09-03  12.490  12.850  12.29  12.64      12.64  122100000

[206 rows x 7 columns]
tolistdate: 0      2020-09-28
1      2020-09-29
2      2020-09-30
3      2020-10-01
4      2020-10-02
          ...
201    2021-08-30
202    2021-08-31
203    2021-09-01
204    2021-09-02
205    2021-09-03
Name: Date, Length: 206, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARVL_ended_2021-09-25  2020-09-28         12.64   9.92  37.18       2.726

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.646    15.372    18.098    20.824     23.55    26.276    29.002

  markup_80 markup_90 markup_100
0    31.728    34.454      37.18
                   stock  start_date current_price minall maxall each_markup  \
0  ARVL_ended_2021-09-25  2020-09-28         12.64   9.92  37.18       2.726

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.646    15.372    18.098    20.824     23.55    26.276    29.002

  markup_80 markup_90 markup_100
0    31.728    34.454      37.18
./ticker_data/ticker_data_2021-09-25 - Copy/ARVN_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-09-27  21.000000  21.250000  16.000000  16.049999  16.049999
1    2018-09-28  15.980000  16.990000  15.940000  16.870001  16.870001
2    2018-10-01  16.879999  17.240000  16.000000  16.010000  16.010000
3    2018-10-02  16.000000  16.110001  14.000000  14.810000  14.810000
4    2018-10-03  15.250000  15.650000  14.810000  15.650000  15.650000
..          ...        ...        ...        ...        ...        ...
734  2021-08-30  85.129997  88.330002  84.099998  85.190002  85.190002
735  2021-08-31  85.000000  86.870003  84.769997  86.209999  86.209999
736  2021-09-01  86.389999  89.089996  85.269997  85.339996  85.339996
737  2021-09-02  85.169998  86.830002  83.980003  86.589996  86.589996
738  2021-09-03  86.720001  86.720001  84.029999  85.889999  85.889999

       Volume
0     3424000
1      315800
2       78700
3      524100
4       87200
..        ...
734  36490000
735  41690000
736  34150000
737  29630000
738  21140000

[739 rows x 7 columns]
tolistdate: 0      2018-09-27
1      2018-09-28
2      2018-10-01
3      2018-10-02
4      2018-10-03
          ...
734    2021-08-30
735    2021-08-31
736    2021-09-01
737    2021-09-02
738    2021-09-03
Name: Date, Length: 739, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ARVN_ended_2021-09-25  2018-09-27         85.89  10.19  108.47       9.828

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    20.018    29.846    39.674    49.502     59.33    69.158    78.986

  markup_80 markup_90 markup_100
0    88.814    98.642     108.47
                   stock  start_date current_price minall  maxall each_markup  \
0  ARVN_ended_2021-09-25  2018-09-27         85.89  10.19  108.47       9.828

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    20.018    29.846    39.674    49.502     59.33    69.158    78.986

  markup_80 markup_90 markup_100
0    88.814    98.642     108.47
./ticker_data/ticker_data_2021-09-25 - Copy/ARWR_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  35.750000  35.750000  35.750000  35.750000  35.750000
1     2000-01-19  71.500000  97.500000  52.000000  97.500000  97.500000
2     2000-01-20  81.250000  81.250000  81.250000  81.250000  81.250000
3     2000-01-21  81.250000  97.500000  81.250000  97.500000  97.500000
4     2000-01-24  97.500000  97.500000  97.500000  97.500000  97.500000
...          ...        ...        ...        ...        ...        ...
4451  2021-08-30  66.070000  68.400002  66.000000  66.839996  66.839996
4452  2021-08-31  67.070000  68.160004  66.430000  67.120003  67.120003
4453  2021-09-01  67.339996  68.989998  67.120003  68.489998  68.489998
4454  2021-09-02  69.000000  69.650002  68.230003  69.099998  69.099998
4455  2021-09-03  68.760002  69.050003  67.059998  67.550003  67.550003

        Volume
0            0
1          100
2            0
3            0
4            0
...        ...
4451  56700000
4452  41730000
4453  45040000
4454  37140000
4455  34030000

[4456 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-19
2       2000-01-20
3       2000-01-21
4       2000-01-24
           ...
4451    2021-08-30
4452    2021-08-31
4453    2021-09-01
4454    2021-09-02
4455    2021-09-03
Name: Date, Length: 4456, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARWR_ended_2021-09-25  1999-12-31         67.55    1.2  162.5       16.13

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     17.33     33.46     49.59     65.72     81.85     97.98    114.11

  markup_80 markup_90 markup_100
0    130.24    146.37      162.5
                   stock  start_date current_price minall maxall each_markup  \
0  ARWR_ended_2021-09-25  1999-12-31         67.55    1.2  162.5       16.13

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     17.33     33.46     49.59     65.72     81.85     97.98    114.11

  markup_80 markup_90 markup_100
0    130.24    146.37      162.5
./ticker_data/ticker_data_2021-09-25 - Copy/ARYD_ended_2021-09-25.csv
           Date    Open   High    Low  Close  Adj Close   Volume
0    2021-02-26  10.950  11.84  10.60  11.13      11.13  2168900
1    2021-03-01  11.790  12.00  11.50  11.55      11.55   226600
2    2021-03-02  11.580  11.80  10.80  11.11      11.11   314500
3    2021-03-03  11.240  11.69  10.76  11.49      11.49   135600
4    2021-03-04  11.400  12.38  10.80  10.99      10.99    44600
..          ...     ...    ...    ...    ...        ...      ...
127  2021-08-30   9.860   9.98   9.85   9.87       9.87   500000
128  2021-08-31   9.870   9.87   9.87   9.87       9.87        0
129  2021-09-01   9.950   9.95   9.90   9.90       9.90   390000
130  2021-09-02   9.905   9.95   9.87   9.87       9.87   210000
131  2021-09-03   9.802  10.00   9.80  10.00      10.00   210000

[132 rows x 7 columns]
tolistdate: 0      2021-02-26
1      2021-03-01
2      2021-03-02
3      2021-03-03
4      2021-03-04
          ...
127    2021-08-30
128    2021-08-31
129    2021-09-01
130    2021-09-02
131    2021-09-03
Name: Date, Length: 132, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ARYD_ended_2021-09-25  2021-02-26            10   9.73  12.38       0.265

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.995     10.26    10.525     10.79    11.055     11.32    11.585

  markup_80 markup_90 markup_100
0     11.85    12.115      12.38
                   stock  start_date current_price minall maxall each_markup  \
0  ARYD_ended_2021-09-25  2021-02-26            10   9.73  12.38       0.265

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.995     10.26    10.525     10.79    11.055     11.32    11.585

  markup_80 markup_90 markup_100
0     11.85    12.115      12.38
./ticker_data/ticker_data_2021-09-25 - Copy/ASAXU_ended_2021-09-25.csv
           Date    Open   High      Low   Close  Adj Close   Volume
0    2021-02-04  10.170  10.32  10.0800  10.230     10.230  4385000
1    2021-02-05  10.300  10.38  10.1600  10.190     10.190  1381100
2    2021-02-08  10.200  10.36  10.1900  10.330     10.330   289600
3    2021-02-09  10.300  10.35  10.2100  10.300     10.300   128400
4    2021-02-10  10.300  10.35  10.2300  10.320     10.320   206500
..          ...     ...    ...      ...     ...        ...      ...
141  2021-09-20  10.100  10.10  10.0600  10.060     10.060     3900
142  2021-09-21  10.068  10.11  10.0680  10.110     10.110     1800
143  2021-09-22  10.120  10.12  10.0780  10.096     10.096     2700
144  2021-09-23  10.060  10.15  10.0400  10.040     10.040     9500
145  2021-09-24  10.100  10.15  10.0927  10.115     10.115     2960

[146 rows x 7 columns]
tolistdate: 0      2021-02-04
1      2021-02-05
2      2021-02-08
3      2021-02-09
4      2021-02-10
          ...
141    2021-09-20
142    2021-09-21
143    2021-09-22
144    2021-09-23
145    2021-09-24
Name: Date, Length: 146, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ASAXU_ended_2021-09-25  2021-02-04        10.115    8.9  10.39       0.149

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.049     9.198     9.347     9.496     9.645     9.794     9.943

  markup_80 markup_90 markup_100
0    10.092    10.241      10.39
                    stock  start_date current_price minall maxall each_markup  \
0  ASAXU_ended_2021-09-25  2021-02-04        10.115    8.9  10.39       0.149

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.049     9.198     9.347     9.496     9.645     9.794     9.943

  markup_80 markup_90 markup_100
0    10.092    10.241      10.39
./ticker_data/ticker_data_2021-09-25 - Copy/ASAXW_ended_2021-09-25.csv
         Date    Open    High   Low   Close  Adj Close  Volume
0  2021-09-22  0.5151  0.5801  0.55  0.5801     0.5801   15348
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall  maxall  \
0  ASAXW_ended_2021-09-25  2021-09-22        0.5801   0.55  0.5801

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00301   0.55301   0.55602   0.55903   0.56204   0.56505   0.56806

  markup_70 markup_80 markup_90 markup_100
0   0.57107   0.57408   0.57709     0.5801
                    stock  start_date current_price minall  maxall  \
0  ASAXW_ended_2021-09-25  2021-09-22        0.5801   0.55  0.5801

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00301   0.55301   0.55602   0.55903   0.56204   0.56505   0.56806

  markup_70 markup_80 markup_90 markup_100
0   0.57107   0.57408   0.57709     0.5801
./ticker_data/ticker_data_2021-09-25 - Copy/ASAX_ended_2021-09-25.csv
           Date  Open  High   Low  Close  Adj Close   Volume
0    2021-03-15  9.69  9.69  9.68   9.68       9.68     7100
1    2021-03-16  9.73  9.73  9.70   9.70       9.70     4600
2    2021-03-17  9.71  9.80  9.68   9.68       9.68    23700
3    2021-03-18  9.68  9.68  9.68   9.68       9.68        0
4    2021-03-19  9.74  9.75  9.74   9.75       9.75     2700
..          ...   ...   ...   ...    ...        ...      ...
110  2021-08-27  9.77  9.77  9.77   9.77       9.77        0
111  2021-08-31  9.77  9.78  9.77   9.78       9.78   780000
112  2021-09-01  9.80  9.82  9.80   9.81       9.81   320000
113  2021-09-02  9.80  9.83  9.80   9.83       9.83   560000
114  2021-09-03  9.78  9.83  9.78   9.82       9.82  2260000

[115 rows x 7 columns]
tolistdate: 0      2021-03-15
1      2021-03-16
2      2021-03-17
3      2021-03-18
4      2021-03-19
          ...
110    2021-08-27
111    2021-08-31
112    2021-09-01
113    2021-09-02
114    2021-09-03
Name: Date, Length: 115, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ASAX_ended_2021-09-25  2021-03-15          9.82   9.55  9.895      0.0345

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.5845     9.619    9.6535     9.688    9.7225     9.757    9.7915

  markup_80 markup_90 markup_100
0     9.826    9.8605      9.895
                   stock  start_date current_price minall maxall each_markup  \
0  ASAX_ended_2021-09-25  2021-03-15          9.82   9.55  9.895      0.0345

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.5845     9.619    9.6535     9.688    9.7225     9.757    9.7915

  markup_80 markup_90 markup_100
0     9.826    9.8605      9.895
./ticker_data/ticker_data_2021-09-25 - Copy/ASLEW_ended_2021-09-25.csv
         Date  Open  High   Low   Close  Adj Close  Volume
0  2021-09-22  3.61  4.17  4.04  4.1001     4.1001   80272
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ASLEW_ended_2021-09-25  2021-09-22        4.1001   4.04   4.17       0.013

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.053     4.066     4.079     4.092     4.105     4.118     4.131

  markup_80 markup_90 markup_100
0     4.144     4.157       4.17
                    stock  start_date current_price minall maxall each_markup  \
0  ASLEW_ended_2021-09-25  2021-09-22        4.1001   4.04   4.17       0.013

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.053     4.066     4.079     4.092     4.105     4.118     4.131

  markup_80 markup_90 markup_100
0     4.144     4.157       4.17
./ticker_data/ticker_data_2021-09-25 - Copy/ASLE_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close   Volume
0    2020-06-25  10.28  10.37  10.14  10.27      10.27    35500
1    2020-06-26  10.23  10.45  10.23  10.29      10.29   250400
2    2020-06-29  10.30  10.30  10.20  10.25      10.25   340600
3    2020-06-30  10.29  10.30  10.25  10.27      10.27   140900
4    2020-07-01  10.23  10.30  10.20  10.26      10.26   140900
..          ...    ...    ...    ...    ...        ...      ...
295  2021-08-30  13.25  13.50  13.14  13.35      13.35  2920000
296  2021-08-31  13.28  13.74  13.28  13.53      13.53  2340000
297  2021-09-01  13.59  13.78  13.00  13.66      13.66  2560000
298  2021-09-02  13.65  13.95  13.54  13.73      13.73  2870000
299  2021-09-03  13.70  13.83  13.33  13.67      13.67  1970000

[300 rows x 7 columns]
tolistdate: 0      2020-06-25
1      2020-06-26
2      2020-06-29
3      2020-06-30
4      2020-07-01
          ...
295    2021-08-30
296    2021-08-31
297    2021-09-01
298    2021-09-02
299    2021-09-03
Name: Date, Length: 300, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ASLE_ended_2021-09-25  2020-06-25         13.67   8.68  18.35       0.967

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.647    10.614    11.581    12.548    13.515    14.482    15.449

  markup_80 markup_90 markup_100
0    16.416    17.383      18.35
                   stock  start_date current_price minall maxall each_markup  \
0  ASLE_ended_2021-09-25  2020-06-25         13.67   8.68  18.35       0.967

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.647    10.614    11.581    12.548    13.515    14.482    15.449

  markup_80 markup_90 markup_100
0    16.416    17.383      18.35
./ticker_data/ticker_data_2021-09-25 - Copy/ASLN_ended_2021-09-25.csv
           Date  Open   High    Low  Close  Adj Close   Volume
0    2018-05-04  6.15  6.450  5.080  5.610      5.610   817200
1    2018-05-07  5.72  5.839  5.200  5.480      5.480   293800
2    2018-05-08  5.58  6.290  5.580  6.270      6.270   186000
3    2018-05-09  6.33  6.330  6.125  6.250      6.250    92400
4    2018-05-10  6.26  6.830  6.200  6.250      6.250   197200
..          ...   ...    ...    ...    ...        ...      ...
850  2021-09-20  3.15  3.200  2.970  3.020      3.020   700400
851  2021-09-21  3.03  3.140  3.000  3.080      3.080   711800
852  2021-09-22  3.10  3.180  3.075  3.130      3.130   365300
853  2021-09-23  3.15  3.288  3.070  3.240      3.240  1283800
854  2021-09-24  3.26  3.300  3.120  3.205      3.205   351126

[855 rows x 7 columns]
tolistdate: 0      2018-05-04
1      2018-05-07
2      2018-05-08
3      2018-05-09
4      2018-05-10
          ...
850    2021-09-20
851    2021-09-21
852    2021-09-22
853    2021-09-23
854    2021-09-24
Name: Date, Length: 855, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ASLN_ended_2021-09-25  2018-05-04         3.205   0.35  10.439      1.0089

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    1.3589    2.3678    3.3767    4.3856    5.3945    6.4034    7.4123

  markup_80 markup_90 markup_100
0    8.4212    9.4301     10.439
                   stock  start_date current_price minall  maxall each_markup  \
0  ASLN_ended_2021-09-25  2018-05-04         3.205   0.35  10.439      1.0089

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    1.3589    2.3678    3.3767    4.3856    5.3945    6.4034    7.4123

  markup_80 markup_90 markup_100

0    8.4212    9.4301     10.439
./ticker_data/ticker_data_2021-09-25 - Copy/ASMB_ended_2021-09-25.csv
            Date       Open       High        Low  Close  Adj Close     Volume
0     2010-12-17  38.549999  38.549999  31.250000  31.50      31.50      39000
1     2010-12-20  33.750000  33.750000  31.049999  31.50      31.50      13700
2     2010-12-21  31.250000  32.250000  31.250000  31.25      31.25      10300
3     2010-12-22  31.500000  31.500000  30.000000  30.25      30.25      23100
4     2010-12-23  30.500000  31.500000  30.000000  31.50      31.50      12200
...          ...        ...        ...        ...    ...        ...        ...
2692  2021-08-30   3.710000   3.720000   3.650000   3.68       3.68   44910000
2693  2021-08-31   3.690000   3.870000   3.670000   3.80       3.80   83490000
2694  2021-09-01   3.810000   3.940000   3.790000   3.90       3.90  124340000
2695  2021-09-02   3.150000   3.300000   3.090000   3.27       3.27  419810000
2696  2021-09-03   3.250000   3.280000   3.170000   3.26       3.26  121130000

[2697 rows x 7 columns]
tolistdate: 0       2010-12-17
1       2010-12-20
2       2010-12-21
3       2010-12-22
4       2010-12-23
           ...
2692    2021-08-30
2693    2021-08-31
2694    2021-09-01
2695    2021-09-02
2696    2021-09-03
Name: Date, Length: 2697, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ASMB_ended_2021-09-25  2010-12-17          3.26   3.09    105      10.191

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.281    23.472    33.663    43.854    54.045    64.236    74.427

  markup_80 markup_90 markup_100
0    84.618    94.809        105
                   stock  start_date current_price minall maxall each_markup  \
0  ASMB_ended_2021-09-25  2010-12-17          3.26   3.09    105      10.191

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.281    23.472    33.663    43.854    54.045    64.236    74.427

  markup_80 markup_90 markup_100
0    84.618    94.809        105
./ticker_data/ticker_data_2021-09-25 - Copy/ASML_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31   40.312500   42.656250   40.125000   42.656250   27.153721
1     2000-01-03   43.875000   43.875000   41.906250   43.640625   27.780346
2     2000-01-04   41.953125   42.562500   40.593750   40.734375   25.930315
3     2000-01-05   39.281250   39.703125   37.757812   39.609375   25.214170
4     2000-01-06   36.750000   37.593750   35.226562   37.171875   23.662525
...          ...         ...         ...         ...         ...         ...
5450  2021-08-30  839.940002  843.010010  836.760010  839.590027  839.590027
5451  2021-08-31  843.780029  844.159973  827.210022  833.039978  833.039978
5452  2021-09-01  838.719971  850.719971  836.690002  842.169983  842.169983
5453  2021-09-02  852.159973  862.049988  848.869995  861.280029  861.280029
5454  2021-09-03  848.520020  862.979980  848.520020  858.109985  858.109985

        Volume
0       247700
1      1121600
2       968800
3      1458100
4      3517800
...        ...
5450  49100000
5451  57930000
5452  58190000
5453  74720000
5454  69800000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price   minall  maxall  \
0  ASML_ended_2021-09-25  1999-12-31        858.11  5.56875  862.98

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     85.7411   91.3099   177.051   262.792   348.533   434.274   520.015

  markup_70 markup_80 markup_90 markup_100
0   605.757   691.498   777.239     862.98
                   stock  start_date current_price   minall  maxall  \
0  ASML_ended_2021-09-25  1999-12-31        858.11  5.56875  862.98

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     85.7411   91.3099   177.051   262.792   348.533   434.274   520.015

  markup_70 markup_80 markup_90 markup_100
0   605.757   691.498   777.239     862.98
./ticker_data/ticker_data_2021-09-25 - Copy/ASND_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2015-01-28   21.500000   21.969999   18.540001   18.830000   18.830000
1     2015-01-29   18.709999   20.184999   18.709999   20.000000   20.000000
2     2015-01-30   19.760000   20.000000   19.059999   19.830000   19.830000
3     2015-02-02   19.850000   19.850000   18.950001   19.080000   19.080000
4     2015-02-03   19.040001   19.379999   18.639999   18.990000   18.990000
...          ...         ...         ...         ...         ...         ...
1658  2021-08-30  159.649994  159.649994  150.559998  154.279999  154.279999
1659  2021-08-31  154.279999  158.300003  154.279999  156.729996  156.729996
1660  2021-09-01  155.660004  166.449997  154.000000  165.720001  165.720001
1661  2021-09-02  169.587006  177.839996  167.500000  176.919998  176.919998
1662  2021-09-03  178.710007  178.710007  165.610001  167.000000  167.000000

        Volume
0      3507000
1       581200
2       146300
3       148700
4        69800
...        ...
1658  26770000
1659  22960000
1660  50670000
1661  62050000
1662  42830000

[1663 rows x 7 columns]
tolistdate: 0       2015-01-28
1       2015-01-29
2       2015-01-30
3       2015-02-02
4       2015-02-03
           ...
1658    2021-08-30
1659    2021-08-31
1660    2021-09-01
1661    2021-09-02
1662    2021-09-03
Name: Date, Length: 1663, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ASND_ended_2021-09-25  2015-01-28           167  11.92  183.98      17.206

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    29.126    46.332    63.538    80.744     97.95   115.156   132.362

  markup_80 markup_90 markup_100
0   149.568   166.774     183.98
                   stock  start_date current_price minall  maxall each_markup  \
0  ASND_ended_2021-09-25  2015-01-28           167  11.92  183.98      17.206

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    29.126    46.332    63.538    80.744     97.95   115.156   132.362

  markup_80 markup_90 markup_100
0   149.568   166.774     183.98
./ticker_data/ticker_data_2021-09-25 - Copy/ASO_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-10-02  12.100000  13.010000  12.050000  12.990000  12.990000
1    2020-10-05  13.330000  13.880000  13.050000  13.150000  13.150000
2    2020-10-06  13.150000  13.360000  12.750000  13.040000  13.040000
3    2020-10-07  13.020000  13.320000  12.850000  13.180000  13.180000
4    2020-10-08  13.250000  13.480000  13.100000  13.280000  13.280000
..          ...        ...        ...        ...        ...        ...
227  2021-08-30  42.570000  43.500000  41.807999  43.400002  43.400002
228  2021-08-31  43.639999  44.439999  42.200001  44.270000  44.270000
229  2021-09-01  44.160000  45.000000  43.669998  44.459999  44.459999
230  2021-09-02  44.770000  45.450001  44.209999  44.560001  44.560001
231  2021-09-03  44.500000  44.880001  44.200001  44.520000  44.520000

        Volume
0      8785600
1      2040800
2       901400
3      1333600
4       998900
..         ...
227  165090000
228  275020000
229  253970000
230  219780000
231  186300000

[232 rows x 7 columns]
tolistdate: 0      2020-10-02
1      2020-10-05
2      2020-10-06
3      2020-10-07
4      2020-10-08
          ...
227    2021-08-30
228    2021-08-31
229    2021-09-01
230    2021-09-02
231    2021-09-03
Name: Date, Length: 232, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  ASO_ended_2021-09-25  2020-10-02         44.52  12.05  45.45        3.34

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     15.39     18.73     22.07     25.41     28.75     32.09     35.43

  markup_80 markup_90 markup_100
0     38.77     42.11      45.45
                  stock  start_date current_price minall maxall each_markup  \
0  ASO_ended_2021-09-25  2020-10-02         44.52  12.05  45.45        3.34

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     15.39     18.73     22.07     25.41     28.75     32.09     35.43

  markup_80 markup_90 markup_100
0     38.77     42.11      45.45
./ticker_data/ticker_data_2021-09-25 - Copy/ASPCU_ended_2021-09-25.csv
           Date    Open    High     Low   Close  Adj Close   Volume
0    2021-02-19  10.350  10.500  10.350  10.470     10.470  9980000
1    2021-02-22  10.430  10.590  10.390  10.500     10.500   952200
2    2021-02-23  10.400  10.440  10.400  10.410     10.410   328900
3    2021-02-24  10.400  10.500  10.400  10.450     10.450   148700
4    2021-02-25  10.450  10.480  10.400  10.460     10.460   340400
..          ...     ...     ...     ...     ...        ...      ...
125  2021-08-30  10.204  10.204  10.204  10.204     10.204        0
126  2021-08-31   9.896   9.896   9.896   9.896      9.896   110000
127  2021-09-01   9.920   9.920   9.895   9.910      9.910  3700000
128  2021-09-02   9.920   9.920   9.900   9.900      9.900    60000
129  2021-09-03   9.900   9.910   9.895   9.900      9.900   540000

[130 rows x 7 columns]
tolistdate: 0      2021-02-19
1      2021-02-22
2      2021-02-23
3      2021-02-24
4      2021-02-25
          ...
125    2021-08-30
126    2021-08-31
127    2021-09-01
128    2021-09-02
129    2021-09-03
Name: Date, Length: 130, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ASPCU_ended_2021-09-25  2021-02-19           9.9   9.49  10.59        0.11

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0       9.6      9.71      9.82      9.93     10.04     10.15     10.26

  markup_80 markup_90 markup_100
0     10.37     10.48      10.59
                    stock  start_date current_price minall maxall each_markup  \
0  ASPCU_ended_2021-09-25  2021-02-19           9.9   9.49  10.59        0.11

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0       9.6      9.71      9.82      9.93     10.04     10.15     10.26

  markup_80 markup_90 markup_100
0     10.37     10.48      10.59
./ticker_data/ticker_data_2021-09-25 - Copy/ASPCW_ended_2021-09-25.csv
         Date    Open    High   Low   Close  Adj Close  Volume
0  2021-09-22  0.6139  0.5996  0.52  0.5275     0.5275   61907
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall  maxall  \
0  ASPCW_ended_2021-09-25  2021-09-22        0.5275   0.52  0.5996

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00796   0.52796   0.53592   0.54388   0.55184    0.5598   0.56776

  markup_70 markup_80 markup_90 markup_100
0   0.57572   0.58368   0.59164     0.5996
                    stock  start_date current_price minall  maxall  \
0  ASPCW_ended_2021-09-25  2021-09-22        0.5275   0.52  0.5996

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00796   0.52796   0.53592   0.54388   0.55184    0.5598   0.56776

  markup_70 markup_80 markup_90 markup_100
0   0.57572   0.58368   0.59164     0.5996
./ticker_data/ticker_data_2021-09-25 - Copy/ASPC_ended_2021-09-25.csv
          Date  Open  High   Low  Close  Adj Close  Volume
0   2021-04-14  9.85  9.85  9.81   9.81       9.81     400
1   2021-04-15  9.81  9.81  9.81   9.81       9.81       0
2   2021-04-16  9.81  9.83  9.77   9.80       9.80   99800
3   2021-04-19  9.86  9.89  9.77   9.89       9.89   22500
4   2021-04-20  9.89  9.89  9.89   9.89       9.89       0
..         ...   ...   ...   ...    ...        ...     ...
89  2021-08-30  9.66  9.66  9.66   9.66       9.66   10000
90  2021-08-31  9.69  9.70  9.69   9.70       9.70  210000
91  2021-09-01  9.70  9.75  9.67   9.70       9.70  630000
92  2021-09-02  9.70  9.70  9.70   9.70       9.70  140000
93  2021-09-03  9.68  9.71  9.67   9.71       9.71  130000

[94 rows x 7 columns]
tolistdate: 0     2021-04-14
1     2021-04-15
2     2021-04-16
3     2021-04-19
4     2021-04-20
         ...
89    2021-08-30
90    2021-08-31
91    2021-09-01
92    2021-09-02
93    2021-09-03
Name: Date, Length: 94, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ASPC_ended_2021-09-25  2021-04-14          9.71    9.6   9.89       0.029

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.629     9.658     9.687     9.716     9.745     9.774     9.803

  markup_80 markup_90 markup_100
0     9.832     9.861       9.89
                   stock  start_date current_price minall maxall each_markup  \
0  ASPC_ended_2021-09-25  2021-04-14          9.71    9.6   9.89       0.029

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.629     9.658     9.687     9.716     9.745     9.774     9.803

  markup_80 markup_90 markup_100
0     9.832     9.861       9.89
./ticker_data/ticker_data_2021-09-25 - Copy/ASPS_ended_2021-09-25.csv
            Date   Open   High    Low  Close  Adj Close    Volume
0     2009-08-06   5.60   7.00   5.60   7.00       7.00      1800
1     2009-08-07  10.00  18.00   9.50  16.00      16.00     78300
2     2009-08-10  11.05  13.00  11.05  12.20      12.20    282800
3     2009-08-11  11.16  16.00  11.16  11.91      11.91    112100
4     2009-08-12  11.26  11.99  10.59  10.90      10.90    398800
...          ...    ...    ...    ...    ...        ...       ...
3036  2021-08-30  10.44  10.73   9.67  10.25      10.25  22360000
3037  2021-08-31  10.27  11.13  10.21  10.85      10.85  18130000
3038  2021-09-01  10.97  11.16  10.51  10.92      10.92   9370000
3039  2021-09-02  10.97  11.29  10.77  11.11      11.11   8440000
3040  2021-09-03  11.20  11.58  10.80  11.34      11.34  10800000

[3041 rows x 7 columns]
tolistdate: 0       2009-08-06
1       2009-08-07
2       2009-08-10
3       2009-08-11
4       2009-08-12
           ...
3036    2021-08-30
3037    2021-08-31
3038    2021-09-01
3039    2021-09-02
3040    2021-09-03
Name: Date, Length: 3041, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ASPS_ended_2021-09-25  2009-08-06         11.34    5.6    171       16.54

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     22.14     38.68     55.22     71.76      88.3    104.84    121.38

  markup_80 markup_90 markup_100
0    137.92    154.46        171
                   stock  start_date current_price minall maxall each_markup  \
0  ASPS_ended_2021-09-25  2009-08-06         11.34    5.6    171       16.54

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     22.14     38.68     55.22     71.76      88.3    104.84    121.38

  markup_80 markup_90 markup_100
0    137.92    154.46        171
./ticker_data/ticker_data_2021-09-25 - Copy/ASPU_ended_2021-09-25.csv
            Date  Open  High   Low  Close  Adj Close  Volume
0     2013-03-22  6.00  6.00  6.00   6.00       6.00     258
1     2013-03-25  6.00  6.00  6.00   6.00       6.00       0
2     2013-03-28  6.00  6.00  6.00   6.00       6.00     167
3     2013-04-05  5.88  5.88  5.88   5.88       5.88      83
4     2013-04-08  5.88  5.88  5.88   5.88       5.88       0
...          ...   ...   ...   ...    ...        ...     ...
2074  2021-09-20  5.69  5.71  5.52   5.55       5.55   86300
2075  2021-09-21  5.53  5.74  5.21   5.67       5.67  256800
2076  2021-09-22  5.70  5.77  5.30   5.40       5.40  275400
2077  2021-09-23  5.41  5.42  5.11   5.15       5.15  160000
2078  2021-09-24  5.15  5.25  5.06   5.25       5.25   41670

[2079 rows x 7 columns]
tolistdate: 0       2013-03-22
1       2013-03-25
2       2013-03-28
3       2013-04-05
4       2013-04-08
           ...
2074    2021-09-20
2075    2021-09-21
2076    2021-09-22
2077    2021-09-23
2078    2021-09-24
Name: Date, Length: 2079, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ASPU_ended_2021-09-25  2013-03-22          5.25  1.116  13.165      1.2049

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.3209    3.5258    4.7307    5.9356    7.1405    8.3454    9.5503

  markup_80 markup_90 markup_100
0   10.7552   11.9601     13.165
                   stock  start_date current_price minall  maxall each_markup  \
0  ASPU_ended_2021-09-25  2013-03-22          5.25  1.116  13.165      1.2049

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.3209    3.5258    4.7307    5.9356    7.1405    8.3454    9.5503

  markup_80 markup_90 markup_100
0   10.7552   11.9601     13.165

./ticker_data/ticker_data_2021-09-25 - Copy/ASRT_ended_2021-09-25.csv
            Date   Open   High    Low  Close  Adj Close    Volume
0     1999-12-31  20.25  25.00  20.25  24.00      24.00     11800
1     2000-01-03  24.50  24.75  21.50  22.00      22.00     13000
2     2000-01-04  22.50  23.00  21.50  22.50      22.50      6300
3     2000-01-05  22.25  22.25  22.00  22.00      22.00      3600
4     2000-01-06  21.50  22.00  20.50  21.50      21.50      2700
...          ...    ...    ...    ...    ...        ...       ...
5444  2021-08-30   1.10   1.12   1.08   1.08       1.08  33570000
5445  2021-08-31   1.08   1.08   1.06   1.07       1.07  15430000
5446  2021-09-01   1.08   1.10   1.07   1.08       1.08  32090000
5447  2021-09-02   1.08   1.10   1.07   1.09       1.09  21480000
5448  2021-09-03   1.09   1.09   1.07   1.08       1.08  10630000

[5449 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5444    2021-08-30
5445    2021-08-31
5446    2021-09-01
5447    2021-09-02
5448    2021-09-03
Name: Date, Length: 5449, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ASRT_ended_2021-09-25  1999-12-31          1.08   0.88  134.96      13.408

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    14.288    27.696    41.104    54.512     67.92    81.328    94.736

  markup_80 markup_90 markup_100
0   108.144   121.552     134.96
                   stock  start_date current_price minall  maxall each_markup  \
0  ASRT_ended_2021-09-25  1999-12-31          1.08   0.88  134.96      13.408

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    14.288    27.696    41.104    54.512     67.92    81.328    94.736

  markup_80 markup_90 markup_100
0   108.144   121.552     134.96
./ticker_data/ticker_data_2021-09-25 - Copy/ASRVP_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  20.000000  20.000000  20.000000  20.000000   3.059160
1     2000-01-03  19.875000  19.875000  19.125000  19.125000   2.925320
2     2000-01-04  19.125000  19.125000  19.125000  19.125000   2.925320
3     2000-01-05  19.000000  21.125000  19.000000  21.125000   3.231237
4     2000-01-06  21.500000  22.500000  21.500000  22.500000   3.441556
...          ...        ...        ...        ...        ...        ...
4119  2021-08-30  25.500000  25.500000  25.400000  25.400000  25.400000
4120  2021-08-31  25.400000  25.420000  25.400000  25.410000  25.410000
4121  2021-09-01  25.469999  25.469999  25.459999  25.469999  25.469999
4122  2021-09-02  25.459999  25.459999  25.379999  25.430000  25.430000
4123  2021-09-03  25.469999  25.549999  25.469999  25.549999  25.549999

      Volume
0        600
1       1200
2          0
3       3300
4       1600
...      ...
4119  470000
4120  120000
4121   50000
4122  370000
4123  370000

[4124 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
4119    2021-08-30
4120    2021-08-31
4121    2021-09-01
4122    2021-09-02
4123    2021-09-03
Name: Date, Length: 4124, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ASRVP_ended_2021-09-25  1999-12-31         25.55  13.84   33.9       2.006

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.846    17.852    19.858    21.864     23.87    25.876    27.882

  markup_80 markup_90 markup_100
0    29.888    31.894       33.9
                    stock  start_date current_price minall maxall each_markup  \
0  ASRVP_ended_2021-09-25  1999-12-31         25.55  13.84   33.9       2.006

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.846    17.852    19.858    21.864     23.87    25.876    27.882

  markup_80 markup_90 markup_100
0    29.888    31.894       33.9
./ticker_data/ticker_data_2021-09-25 - Copy/ASRV_ended_2021-09-25.csv
            Date      Open     High     Low   Close  Adj Close  Volume
0     1999-12-31  11.75000  12.2500  11.750  11.750   7.870097   14700
1     2000-01-03  11.75000  12.5000  11.625  12.000   8.037547   11800
2     2000-01-04  12.43750  12.4375  12.000  12.125   8.121268   29100
3     2000-01-05  12.21875  12.3750  12.125  12.375   8.288718    9800
4     2000-01-06  12.18750  12.2500  12.125  12.250   8.204995   15600
...          ...       ...      ...     ...     ...        ...     ...
5455  2021-09-20   4.00000   4.0000   3.880   3.920   3.920000    4900
5456  2021-09-21   3.93000   4.0000   3.840   3.900   3.900000    5300
5457  2021-09-22   3.97000   3.9700   3.880   3.900   3.900000    5000
5458  2021-09-23   3.88000   3.9300   3.880   3.930   3.930000   12100
5459  2021-09-24   3.92990   3.9300   3.890   3.890   3.890000    1611

[5460 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5455    2021-09-20
5456    2021-09-21
5457    2021-09-22
5458    2021-09-23
5459    2021-09-24
Name: Date, Length: 5460, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ASRV_ended_2021-09-25  1999-12-31          3.89    0.9  12.875      1.1975

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.0975     3.295    4.4925      5.69    6.8875     8.085    9.2825

  markup_80 markup_90 markup_100
0     10.48   11.6775     12.875
                   stock  start_date current_price minall  maxall each_markup  \
0  ASRV_ended_2021-09-25  1999-12-31          3.89    0.9  12.875      1.1975

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.0975     3.295    4.4925      5.69    6.8875     8.085    9.2825

  markup_80 markup_90 markup_100
0     10.48   11.6775     12.875
./ticker_data/ticker_data_2021-09-25 - Copy/ASTC_ended_2021-09-25.csv
            Date      Open     High     Low    Close  Adj Close    Volume
0     1999-12-31  256.2500  275.000  256.25  268.750    268.750       300
1     2000-01-03  268.7500  271.875  262.50  268.750    268.750       100
2     2000-01-04  267.1875  268.750  262.50  262.500    262.500       200
3     2000-01-05  262.5000  265.625  262.50  265.625    265.625       300
4     2000-01-06  264.0625  287.500  262.50  271.875    271.875       500
...          ...       ...      ...     ...      ...        ...       ...
5410  2021-08-30    1.0900    1.110    1.06    1.100      1.100  98530000
5411  2021-08-31    1.0900    1.120    1.07    1.110      1.110  49280000
5412  2021-09-01    1.1100    1.120    1.09    1.100      1.100  49380000
5413  2021-09-02    1.1100    1.130    1.10    1.110      1.110  41800000
5414  2021-09-03    1.1200    1.120    1.07    1.090      1.090  38140000

[5415 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5410    2021-08-30
5411    2021-08-31
5412    2021-09-01
5413    2021-09-02
5414    2021-09-03
Name: Date, Length: 5415, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ASTC_ended_2021-09-25  1999-12-31          1.09   0.94    325      32.406

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    33.346    65.752    98.158   130.564    162.97   195.376   227.782

  markup_80 markup_90 markup_100
0   260.188   292.594        325
                   stock  start_date current_price minall maxall each_markup  \
0  ASTC_ended_2021-09-25  1999-12-31          1.09   0.94    325      32.406

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    33.346    65.752    98.158   130.564    162.97   195.376   227.782

  markup_80 markup_90 markup_100
0   260.188   292.594        325
./ticker_data/ticker_data_2021-09-25 - Copy/ASTE_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  17.500000  19.000000  17.500000  18.812500  16.699821
1     2000-01-03  19.125000  19.125000  17.500000  17.562500  15.590202
2     2000-01-04  17.562500  17.562500  16.750000  16.750000  14.868941
3     2000-01-05  16.812500  18.250000  16.750000  17.937500  15.923087
4     2000-01-06  18.250000  21.000000  17.812500  20.625000  18.308769
...          ...        ...        ...        ...        ...        ...
5464  2021-09-20  54.119999  54.759998  53.500000  54.590000  54.590000
5465  2021-09-21  54.790001  55.040001  53.310001  53.610001  53.610001
5466  2021-09-22  53.939999  54.849998  53.680000  54.180000  54.180000
5467  2021-09-23  54.490002  55.779999  54.490002  54.930000  54.930000
5468  2021-09-24  54.650002  55.195000  54.340000  54.759998  54.759998

      Volume
0      97300
1     219200
2     330700
3     292000
4     332700
...      ...
5464   70200
5465  107900
5466   90800
5467   67200
5468   13128

[5469 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5464    2021-09-20
5465    2021-09-21
5466    2021-09-22
5467    2021-09-23
5468    2021-09-24
Name: Date, Length: 5469, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ASTE_ended_2021-09-25  1999-12-31         54.76   5.21     80       7.479

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.689    20.168    27.647    35.126    42.605    50.084    57.563

  markup_80 markup_90 markup_100
0    65.042    72.521         80
                   stock  start_date current_price minall maxall each_markup  \
0  ASTE_ended_2021-09-25  1999-12-31         54.76   5.21     80       7.479

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.689    20.168    27.647    35.126    42.605    50.084    57.563

  markup_80 markup_90 markup_100
0    65.042    72.521         80
./ticker_data/ticker_data_2021-09-25 - Copy/ASTSW_ended_2021-09-25.csv
         Date  Open    High   Low  Close  Adj Close  Volume
0  2021-09-22  2.78  4.1999  3.95   3.95       3.95   58794
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall  maxall  \
0  ASTSW_ended_2021-09-25  2021-09-22          3.95   3.95  4.1999

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.02499   3.97499   3.99998   4.02497   4.04996   4.07495   4.09994

  markup_70 markup_80 markup_90 markup_100
0   4.12493   4.14992   4.17491     4.1999
                    stock  start_date current_price minall  maxall  \
0  ASTSW_ended_2021-09-25  2021-09-22          3.95   3.95  4.1999

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.02499   3.97499   3.99998   4.02497   4.04996   4.07495   4.09994

  markup_70 markup_80 markup_90 markup_100
0   4.12493   4.14992   4.17491     4.1999
./ticker_data/ticker_data_2021-09-25 - Copy/ASTS_ended_2021-09-25.csv
           Date    Open    High    Low  Close  Adj Close     Volume
0    2020-10-09  10.119  10.119  10.10  10.10      10.10      50800
1    2020-10-12  10.100  10.110  10.10  10.10      10.10       1300
2    2020-10-13  10.150  10.150  10.12  10.12      10.12       1700
3    2020-10-14  10.110  10.110  10.11  10.11      10.11        400
4    2020-10-15  10.070  10.100  10.06  10.10      10.10       6500
..          ...     ...     ...    ...    ...        ...        ...
181  2021-08-30  11.180  12.360  11.10  12.36      12.36  401860000
182  2021-08-31  12.275  12.660  11.58  12.35      12.35  208650000
183  2021-09-01  12.220  12.740  11.70  12.26      12.26  154870000
184  2021-09-02  12.270  12.990  12.25  12.38      12.38  156660000
185  2021-09-03  12.520  12.911  12.06  12.36      12.36  107520000

[186 rows x 7 columns]
tolistdate: 0      2020-10-09
1      2020-10-12
2      2020-10-13
3      2020-10-14
4      2020-10-15
          ...
181    2021-08-30
182    2021-08-31
183    2021-09-01
184    2021-09-02
185    2021-09-03
Name: Date, Length: 186, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ASTS_ended_2021-09-25  2020-10-09         12.36   6.96  17.69       1.073

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.033     9.106    10.179    11.252    12.325    13.398    14.471

  markup_80 markup_90 markup_100
0    15.544    16.617      17.69
                   stock  start_date current_price minall maxall each_markup  \
0  ASTS_ended_2021-09-25  2020-10-09         12.36   6.96  17.69       1.073

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.033     9.106    10.179    11.252    12.325    13.398    14.471

  markup_80 markup_90 markup_100
0    15.544    16.617      17.69
./ticker_data/ticker_data_2021-09-25 - Copy/ASUR_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  22.083334  23.125000  20.833334  21.875000  21.875000
1     2000-01-03  22.500000  22.916666  21.875000  22.916666  22.916666
2     2000-01-04  22.604166  23.333334  20.000000  21.250000  21.250000
3     2000-01-05  21.979166  22.500000  20.208334  20.833334  20.833334
4     2000-01-06  21.250000  22.500000  20.833334  21.666666  21.666666
...          ...        ...        ...        ...        ...        ...
5427  2021-08-30   8.980000   9.050000   8.920000   8.930000   8.930000
5428  2021-08-31   9.030000   9.250000   9.000000   9.050000   9.050000
5429  2021-09-01   9.110000   9.440000   8.910000   9.010000   9.010000
5430  2021-09-02   9.010000   9.010000   8.770000   8.830000   8.830000
5431  2021-09-03   8.780000   9.010000   8.720000   8.960000   8.960000

       Volume
0       33100
1       24300
2       47100
3       26500
4       14700
...       ...
5427  1050000
5428  4410000
5429  2280000
5430  1780000
5431  2680000

[5432 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5427    2021-08-30
5428    2021-08-31
5429    2021-09-01
5430    2021-09-02
5431    2021-09-03
Name: Date, Length: 5432, dtype: object
                   stock  start_date current_price    minall maxall  \
0  ASUR_ended_2021-09-25  1999-12-31          8.96  0.666667     80

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     7.93333       8.6   16.5333   24.4667      32.4   40.3333   48.2667

  markup_70 markup_80 markup_90 markup_100
0      56.2   64.1333   72.0667         80
                   stock  start_date current_price    minall maxall  \
0  ASUR_ended_2021-09-25  1999-12-31          8.96  0.666667     80

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     7.93333       8.6   16.5333   24.4667      32.4   40.3333   48.2667

  markup_70 markup_80 markup_90 markup_100
0      56.2   64.1333   72.0667         80
./ticker_data/ticker_data_2021-09-25 - Copy/ASYS_ended_2021-09-25.csv

            Date       Open      High       Low   Close  Adj Close   Volume
0     1999-12-31   5.140625   5.15625   5.00000   5.000      5.000    14100
1     2000-01-03   5.062500   5.21875   4.62500   4.875      4.875    73100
2     2000-01-04   4.656250   4.93750   4.50000   4.750      4.750    15400
3     2000-01-05   4.531250   4.56250   4.37500   4.375      4.375    11800
4     2000-01-06   4.125000   4.37500   3.96875   4.375      4.375    26400
...          ...        ...       ...       ...     ...        ...      ...
5444  2021-08-30  10.050000  10.34000  10.04000  10.280     10.280  7940000
5445  2021-08-31  10.320000  10.35000   9.88000  10.340     10.340  2840000
5446  2021-09-01  10.330000  10.39000  10.20000  10.200     10.200  4160000
5447  2021-09-02  10.210000  10.49000  10.21000  10.380     10.380  9510000
5448  2021-09-03  10.430000  10.49000  10.26000  10.480     10.480  3140000

[5449 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5444    2021-08-30
5445    2021-08-31
5446    2021-09-01
5447    2021-09-02
5448    2021-09-03
Name: Date, Length: 5449, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ASYS_ended_2021-09-25  1999-12-31         10.48      2   30.8        2.88

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      4.88      7.76     10.64     13.52      16.4     19.28     22.16

  markup_80 markup_90 markup_100
0     25.04     27.92       30.8
                   stock  start_date current_price minall maxall each_markup  \
0  ASYS_ended_2021-09-25  1999-12-31         10.48      2   30.8        2.88

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      4.88      7.76     10.64     13.52      16.4     19.28     22.16

  markup_80 markup_90 markup_100
0     25.04     27.92       30.8
./ticker_data/ticker_data_2021-09-25 - Copy/ATAX_ended_2021-09-25.csv
            Date      Open    High    Low   Close  Adj Close    Volume
0     1999-12-31  4.828125  5.0000  4.750  5.0000   0.867143     66300
1     2000-01-03  5.000000  5.3750  4.875  5.1250   0.888821     22100
2     2000-01-04  5.000000  5.3750  5.000  5.3125   0.921339     43300
3     2000-01-05  5.125000  5.1250  5.125  5.1250   0.888821      8600
4     2000-01-06  5.375000  5.4375  5.250  5.2500   0.910500     25700
...          ...       ...     ...    ...     ...        ...       ...
5441  2021-08-30  6.560000  6.6500  6.490  6.6000   6.600000  13020000
5442  2021-08-31  6.610000  6.7800  6.610  6.6500   6.650000   5390000
5443  2021-09-01  6.660000  6.7400  6.640  6.7300   6.730000   5180000
5444  2021-09-02  6.700000  6.7100  6.520  6.5500   6.550000   7680000
5445  2021-09-03  6.540000  6.6800  6.540  6.6800   6.680000   4990000

[5446 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5441    2021-08-30
5442    2021-08-31
5443    2021-09-01
5444    2021-09-02
5445    2021-09-03
Name: Date, Length: 5446, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATAX_ended_2021-09-25  1999-12-31          6.68   3.52   9.44       0.592

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.112     4.704     5.296     5.888      6.48     7.072     7.664

  markup_80 markup_90 markup_100
0     8.256     8.848       9.44
                   stock  start_date current_price minall maxall each_markup  \
0  ATAX_ended_2021-09-25  1999-12-31          6.68   3.52   9.44       0.592

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.112     4.704     5.296     5.888      6.48     7.072     7.664

  markup_80 markup_90 markup_100
0     8.256     8.848       9.44
./ticker_data/ticker_data_2021-09-25 - Copy/ATCOL_ended_2021-09-25.csv
          Date       Open       High        Low      Close  Adj Close  Volume
0   2021-05-19  25.600000  26.000000  25.600000  26.000000  25.565853    4400
1   2021-05-20  25.750000  26.120001  25.750000  26.110001  25.674017   14600
2   2021-05-21  25.995001  25.995001  25.995001  25.995001  25.560938     200
3   2021-05-24  26.190001  26.240000  26.190001  26.240000  25.801846    1600
4   2021-05-25  26.120001  26.230000  26.100000  26.230000  25.792013    4500
..         ...        ...        ...        ...        ...        ...     ...
70  2021-08-30  26.400000  26.549999  26.400000  26.483999  26.483999  360000
71  2021-08-31  26.400000  26.559999  26.400000  26.496000  26.496000  270000
72  2021-09-01  26.417000  26.549999  26.417000  26.549999  26.549999  420000
73  2021-09-02  26.549999  26.549999  26.549999  26.549999  26.549999       0
74  2021-09-03  26.410000  26.535000  26.400000  26.440001  26.440001  730000

[75 rows x 7 columns]
tolistdate: 0     2021-05-19
1     2021-05-20
2     2021-05-21
3     2021-05-24
4     2021-05-25
         ...
70    2021-08-30
71    2021-08-31
72    2021-09-01
73    2021-09-02
74    2021-09-03
Name: Date, Length: 75, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ATCOL_ended_2021-09-25  2021-05-19         26.44   25.6  26.72       0.112

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    25.712    25.824    25.936    26.048     26.16    26.272    26.384

  markup_80 markup_90 markup_100
0    26.496    26.608      26.72
                    stock  start_date current_price minall maxall each_markup  \
0  ATCOL_ended_2021-09-25  2021-05-19         26.44   25.6  26.72       0.112

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    25.712    25.824    25.936    26.048     26.16    26.272    26.384

  markup_80 markup_90 markup_100
0    26.496    26.608      26.72
./ticker_data/ticker_data_2021-09-25 - Copy/ATCX_ended_2021-09-25.csv
           Date   Open    High   Low    Close  Adj Close  Volume
0    2019-02-06   9.55   9.550  9.55   9.5500     9.5500       0
1    2019-02-08   9.59   9.590  9.59   9.5900     9.5900     900
2    2019-02-11   9.62   9.630  9.62   9.6300     9.6300    2200
3    2019-02-12   9.65   9.660  9.65   9.6600     9.6600    3400
4    2019-02-13   9.66   9.660  9.66   9.6600     9.6600       0
..          ...    ...     ...   ...      ...        ...     ...
622  2021-09-20   9.65   9.810  9.17   9.2200     9.2200  209400
623  2021-09-21   9.40   9.760  9.08   9.2500     9.2500  207200
624  2021-09-22   9.31   9.745  9.20   9.5500     9.5500  124600
625  2021-09-23   9.50  10.105  9.44  10.1000    10.1000  227700
626  2021-09-24  10.00  10.140  9.98  10.1047    10.1047   50203

[627 rows x 7 columns]
tolistdate: 0      2019-02-06
1      2019-02-08
2      2019-02-11
3      2019-02-12
4      2019-02-13
          ...
622    2021-09-20
623    2021-09-21
624    2021-09-22
625    2021-09-23
626    2021-09-24
Name: Date, Length: 627, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATCX_ended_2021-09-25  2019-02-06       10.1047   4.95   15.4       1.045

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.995      7.04     8.085      9.13    10.175     11.22    12.265

  markup_80 markup_90 markup_100
0     13.31    14.355       15.4
                   stock  start_date current_price minall maxall each_markup  \
0  ATCX_ended_2021-09-25  2019-02-06       10.1047   4.95   15.4       1.045

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.995      7.04     8.085      9.13    10.175     11.22    12.265

  markup_80 markup_90 markup_100
0     13.31    14.355       15.4
./ticker_data/ticker_data_2021-09-25 - Copy/ATEC_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2006-06-12  105.599998  105.599998  101.040001  102.000000  102.000000
1     2006-06-13  100.919998  101.519997   98.400002  100.800003  100.800003
2     2006-06-14  100.800003  101.279999   99.720001   99.720001   99.720001
3     2006-06-15   99.480003  100.199997   97.680000   97.800003   97.800003
4     2006-06-16   99.000000   99.000000   95.040001   95.040001   95.040001
...          ...         ...         ...         ...         ...         ...
3845  2021-09-20   13.830000   14.120000   13.620000   13.870000   13.870000
3846  2021-09-21   13.970000   14.260000   13.880000   14.040000   14.040000
3847  2021-09-22   14.070000   14.520000   13.970000   14.360000   14.360000
3848  2021-09-23   14.430000   14.540000   13.900000   14.140000   14.140000
3849  2021-09-24   13.970000   14.085000   13.720000   13.855000   13.855000

       Volume
0       13050
1        5933
2        6042
3        2967
4        4842
...       ...
3845   921500
3846   589300
3847  1129800
3848   950700
3849   348014

[3850 rows x 7 columns]
tolistdate: 0       2006-06-12
1       2006-06-13
2       2006-06-14
3       2006-06-15
4       2006-06-16
           ...
3845    2021-09-20
3846    2021-09-21
3847    2021-09-22
3848    2021-09-23
3849    2021-09-24
Name: Date, Length: 3850, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATEC_ended_2021-09-25  2006-06-12        13.855   1.18  105.6      10.442

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.622    22.064    32.506    42.948     53.39    63.832    74.274

  markup_80 markup_90 markup_100
0    84.716    95.158      105.6
                   stock  start_date current_price minall maxall each_markup  \
0  ATEC_ended_2021-09-25  2006-06-12        13.855   1.18  105.6      10.442

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.622    22.064    32.506    42.948     53.39    63.832    74.274

  markup_80 markup_90 markup_100
0    84.716    95.158      105.6
./ticker_data/ticker_data_2021-09-25 - Copy/ATER_ended_2021-09-25.csv
           Date   Open  High   Low  Close  Adj Close      Volume
0    2020-11-02  8.040  8.55  7.98   8.38       8.38       57900
1    2020-11-03  8.500  8.65  8.39   8.44       8.44       76600
2    2020-11-04  8.540  8.88  8.37   8.69       8.69       85800
3    2020-11-05  8.700  9.17  8.70   9.10       9.10       93500
4    2020-11-06  9.090  9.39  8.94   9.15       9.15      105000
..          ...    ...   ...   ...    ...        ...         ...
148  2021-08-30  8.880  9.00  6.48   6.62       6.62  5216100000
149  2021-08-31  6.410  6.44  5.32   5.96       5.96  1517080000
150  2021-09-01  5.832  8.00  5.64   7.40       7.40  4651250000
151  2021-09-02  7.260  7.69  6.33   6.49       6.49  1629840000
152  2021-09-03  6.370  6.76  6.09   6.70       6.70   752600000

[153 rows x 7 columns]
tolistdate: 0      2020-11-02
1      2020-11-03
2      2020-11-04
3      2020-11-05
4      2020-11-06
          ...
148    2021-08-30
149    2021-08-31
150    2021-09-01
151    2021-09-02
152    2021-09-03
Name: Date, Length: 153, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATER_ended_2021-09-25  2020-11-02           6.7   3.04  33.89       3.085

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.125      9.21    12.295     15.38    18.465     21.55    24.635

  markup_80 markup_90 markup_100
0     27.72    30.805      33.89
                   stock  start_date current_price minall maxall each_markup  \
0  ATER_ended_2021-09-25  2020-11-02           6.7   3.04  33.89       3.085

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.125      9.21    12.295     15.38    18.465     21.55    24.635

  markup_80 markup_90 markup_100
0     27.72    30.805      33.89
./ticker_data/ticker_data_2021-09-25 - Copy/ATEX_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2015-02-03  39.000000  40.000000  39.000000  40.000000  40.000000
1     2015-02-04  50.000000  50.000000  41.000000  41.000000  41.000000
2     2015-02-05  42.000000  42.000000  42.000000  42.000000  42.000000
3     2015-02-06  48.000000  48.000000  43.000000  43.000000  43.000000
4     2015-02-09  45.000000  45.000000  41.500000  43.970001  43.970001
...          ...        ...        ...        ...        ...        ...
1654  2021-08-30  57.650002  57.650002  55.750000  56.980000  56.980000
1655  2021-08-31  56.900002  59.169998  56.900002  59.020000  59.020000
1656  2021-09-01  59.970001  59.970001  58.310001  58.990002  58.990002
1657  2021-09-02  59.369999  60.689999  58.700001  60.599998  60.599998
1658  2021-09-03  60.669998  61.900002  59.599998  59.889999  59.889999

       Volume
0       24700
1         800
2         400
3         900
4      151400
...       ...
1654  5970000
1655  7180000
1656  6010000
1657  3970000
1658  5660000

[1659 rows x 7 columns]
tolistdate: 0       2015-02-03
1       2015-02-04
2       2015-02-05
3       2015-02-06
4       2015-02-09
           ...
1654    2021-08-30
1655    2021-08-31
1656    2021-09-01
1657    2021-09-02
1658    2021-09-03
Name: Date, Length: 1659, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ATEX_ended_2021-09-25  2015-02-03         59.89   18.6  64.955      4.6355

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   23.2355    27.871   32.5065    37.142   41.7775    46.413   51.0485

  markup_80 markup_90 markup_100
0    55.684   60.3195     64.955
                   stock  start_date current_price minall  maxall each_markup  \
0  ATEX_ended_2021-09-25  2015-02-03         59.89   18.6  64.955      4.6355

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   23.2355    27.871   32.5065    37.142   41.7775    46.413   51.0485

  markup_80 markup_90 markup_100
0    55.684   60.3195     64.955
./ticker_data/ticker_data_2021-09-25 - Copy/ATHA_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-09-18  19.950001  20.419001  16.700001  17.110001  17.110001
1    2020-09-21  16.360001  18.379999  16.160000  16.809999  16.809999
2    2020-09-22  17.160000  17.160000  16.250000  16.650000  16.650000
3    2020-09-23  17.000000  17.000000  16.000000  16.299999  16.299999
4    2020-09-24  16.490000  16.490000  15.790000  16.020000  16.020000
..          ...        ...        ...        ...        ...        ...
237  2021-08-30  10.800000  10.870000  10.320000  10.660000  10.660000
238  2021-08-31  10.650000  10.959000  10.440000  10.590000  10.590000
239  2021-09-01  10.590000  10.750000  10.490000  10.730000  10.730000
240  2021-09-02  10.760000  10.980000  10.620000  10.920000  10.920000
241  2021-09-03  10.890000  10.890000  10.540000  10.660000  10.660000

       Volume
0     3213000
1      348400
2      126100
3      256500
4      207900
..        ...
237  34700000
238  19550000
239  13910000
240  21680000
241  14100000

[242 rows x 7 columns]
tolistdate: 0      2020-09-18
1      2020-09-21
2      2020-09-22
3      2020-09-23
4      2020-09-24
          ...
237    2021-08-30
238    2021-08-31
239    2021-09-01
240    2021-09-02
241    2021-09-03
Name: Date, Length: 242, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATHA_ended_2021-09-25  2020-09-18         10.66   8.88  34.79       2.591

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.471    14.062    16.653    19.244    21.835    24.426    27.017

  markup_80 markup_90 markup_100
0    29.608    32.199      34.79
                   stock  start_date current_price minall maxall each_markup  \
0  ATHA_ended_2021-09-25  2020-09-18         10.66   8.88  34.79       2.591

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.471    14.062    16.653    19.244    21.835    24.426    27.017

  markup_80 markup_90 markup_100
0    29.608    32.199      34.79
./ticker_data/ticker_data_2021-09-25 - Copy/ATHE_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2003-09-29  30.420000  30.540001  29.940001  29.940001  29.940001
1     2003-09-30  28.440001  29.639999  28.080000  29.580000  29.580000
2     2003-10-01  29.400000  30.840000  28.440001  29.340000  29.340000
3     2003-10-02  28.080000  29.700001  28.080000  29.700001  29.700001
4     2003-10-03  29.700001  29.700001  29.700001  29.700001  29.700001
...          ...        ...        ...        ...        ...        ...
4480  2021-08-30   1.370000   1.390000   1.330000   1.340000   1.340000
4481  2021-08-31   1.360000   1.380000   1.330000   1.360000   1.360000
4482  2021-09-01   1.320000   1.380000   1.320000   1.360000   1.360000
4483  2021-09-02   1.350000   1.390000   1.350000   1.370000   1.370000
4484  2021-09-03   1.360000   1.400000   1.360000   1.380000   1.380000

        Volume
0          400
1          900
2          400
3          100
4            0
...        ...
4480  37570000
4481  21620000
4482  17380000
4483  22290000
4484  35400000

[4485 rows x 7 columns]
tolistdate: 0       2003-09-29
1       2003-09-30
2       2003-10-01
3       2003-10-02
4       2003-10-03
           ...
4480    2021-08-30
4481    2021-08-31
4482    2021-09-01
4483    2021-09-02
4484    2021-09-03
Name: Date, Length: 4485, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATHE_ended_2021-09-25  2003-09-29          1.38   0.28  79.74       7.946

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.226    16.172    24.118    32.064     40.01    47.956    55.902

  markup_80 markup_90 markup_100
0    63.848    71.794      79.74
                   stock  start_date current_price minall maxall each_markup  \
0  ATHE_ended_2021-09-25  2003-09-29          1.38   0.28  79.74       7.946

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.226    16.172    24.118    32.064     40.01    47.956    55.902

  markup_80 markup_90 markup_100
0    63.848    71.794      79.74
./ticker_data/ticker_data_2021-09-25 - Copy/ATHX_ended_2021-09-25.csv
            Date  Open   High   Low  Close  Adj Close     Volume
0     2007-06-12  5.25   5.25  5.25   5.25       5.25        500
1     2007-06-13  5.25   5.25  5.25   5.25       5.25          0
2     2007-06-19  7.40  10.00  7.40   7.75       7.75      62400
3     2007-06-20  8.00   8.60  8.00   8.00       8.00       6800
4     2007-06-21  8.10   8.25  8.00   8.00       8.00       8100
...          ...   ...    ...   ...    ...        ...        ...
3523  2021-08-30  1.60   1.64  1.59   1.63       1.63  106920000
3524  2021-08-31  1.65   1.74  1.64   1.68       1.68  243080000
3525  2021-09-01  1.68   1.71  1.65   1.67       1.67  102420000
3526  2021-09-02  1.68   1.81  1.67   1.77       1.77  302200000
3527  2021-09-03  1.75   1.78  1.68   1.68       1.68  151020000

[3528 rows x 7 columns]
tolistdate: 0       2007-06-12
1       2007-06-13
2       2007-06-19
3       2007-06-20
4       2007-06-21
           ...
3523    2021-08-30
3524    2021-08-31
3525    2021-09-01
3526    2021-09-02
3527    2021-09-03
Name: Date, Length: 3528, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATHX_ended_2021-09-25  2007-06-12          1.68   0.15     10       0.985

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.135      2.12     3.105      4.09     5.075      6.06     7.045

  markup_80 markup_90 markup_100
0      8.03     9.015         10
                   stock  start_date current_price minall maxall each_markup  \
0  ATHX_ended_2021-09-25  2007-06-12          1.68   0.15     10       0.985

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.135      2.12     3.105      4.09     5.075      6.06     7.045

  markup_80 markup_90 markup_100
0      8.03     9.015         10
./ticker_data/ticker_data_2021-09-25 - Copy/ATIF_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close      Volume
0    2019-05-03  5.000  5.100  4.275   4.95       4.95       86300
1    2019-05-06  5.000  5.000  3.890   4.70       4.70       19500
2    2019-05-07  4.545  4.545  4.400   4.40       4.40        9100
3    2019-05-08  4.370  4.530  4.150   4.53       4.53        2600
4    2019-05-09  4.548  4.550  4.095   4.50       4.50        8000
..          ...    ...    ...    ...    ...        ...         ...
585  2021-08-30  3.000  5.650  2.900   3.38       3.38  2906590000
586  2021-08-31  3.162  3.746  2.860   3.43       3.43   243630000
587  2021-09-01  3.440  3.770  3.350   3.73       3.73    91850000
588  2021-09-02  3.670  4.040  3.450   3.76       3.76   101680000
589  2021-09-03  3.830  3.980  3.760   3.93       3.93    59350000

[590 rows x 7 columns]
tolistdate: 0      2019-05-03
1      2019-05-06
2      2019-05-07
3      2019-05-08
4      2019-05-09
          ...
585    2021-08-30
586    2021-08-31
587    2021-09-01
588    2021-09-02
589    2021-09-03
Name: Date, Length: 590, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATIF_ended_2021-09-25  2019-05-03          3.93  0.421   5.65      0.5229

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    0.9439    1.4668    1.9897    2.5126    3.0355    3.5584    4.0813

  markup_80 markup_90 markup_100
0    4.6042    5.1271       5.65
                   stock  start_date current_price minall maxall each_markup  \
0  ATIF_ended_2021-09-25  2019-05-03          3.93  0.421   5.65      0.5229

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    0.9439    1.4668    1.9897    2.5126    3.0355    3.5584    4.0813

  markup_80 markup_90 markup_100
0    4.6042    5.1271       5.65
./ticker_data/ticker_data_2021-09-25 - Copy/ATLC_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  38.250000  38.625000  38.000000  38.500000  32.887756
1     2000-01-03  38.500000  38.875000  37.250000  38.000000  32.460644
2     2000-01-04  37.500000  37.500000  33.250000  34.687500  29.631014
3     2000-01-05  34.312500  34.312500  30.000000  30.000000  25.626823
4     2000-01-06  30.468750  31.000000  29.937500  30.500000  26.053936
...          ...        ...        ...        ...        ...        ...
5377  2021-08-30  57.480000  59.490002  56.000000  58.820000  58.820000
5378  2021-08-31  58.750000  65.610001  58.360001  64.199997  64.199997
5379  2021-09-01  64.190002  64.519997  59.040001  60.490002  60.490002
5380  2021-09-02  60.349998  62.000000  58.250000  60.529999  60.529999
5381  2021-09-03  60.730000  61.150002  58.509998  59.950001  59.950001

        Volume
0         9100
1        44100
2        40400
3        59200
4        49600
...        ...
5377  12100000
5378  22410000
5379  17580000
5380   6500000
5381   5320000

[5382 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5377    2021-08-30
5378    2021-08-31
5379    2021-09-01
5380    2021-09-02
5381    2021-09-03
Name: Date, Length: 5382, dtype: object
                   stock  start_date current_price minall   maxall  \
0  ATLC_ended_2021-09-25  1999-12-31         59.95   1.15  66.0625

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     6.49125   7.64125   14.1325   20.6237    27.115   33.6062   40.0975

  markup_70 markup_80 markup_90 markup_100
0   46.5887     53.08   59.5712    66.0625
                   stock  start_date current_price minall   maxall  \
0  ATLC_ended_2021-09-25  1999-12-31         59.95   1.15  66.0625

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     6.49125   7.64125   14.1325   20.6237    27.115   33.6062   40.0975

  markup_70 markup_80 markup_90 markup_100
0   46.5887     53.08   59.5712    66.0625
./ticker_data/ticker_data_2021-09-25 - Copy/ATLO_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2000-02-15  17.333334  17.333334  17.333334  17.333334   7.201772
1     2000-03-31  16.333334  16.333334  16.333334  16.333334   6.786284
2     2000-04-03  18.166666  18.166666  18.166666  18.166666   7.548009
3     2000-04-04  18.166666  18.166666  18.166666  18.166666   7.709269
4     2000-04-05  18.166666  18.166666  18.166666  18.166666   7.709269
...          ...        ...        ...        ...        ...        ...
4518  2021-08-30  23.500000  23.889999  23.379999  23.480000  23.480000
4519  2021-08-31  23.500000  23.570000  23.389999  23.410000  23.410000
4520  2021-09-01  23.700001  23.820000  23.330000  23.690001  23.690001
4521  2021-09-02  23.750000  23.950001  23.290001  23.459999  23.459999
4522  2021-09-03  23.450001  23.809999  23.230000  23.410000  23.410000

       Volume
0           0
1         900
2         900
3           0
4           0
...       ...
4518  1100000
4519   920000
4520  2120000
4521   700000
4522  1490000

[4523 rows x 7 columns]
tolistdate: 0       2000-02-15
1       2000-03-31
2       2000-04-03
3       2000-04-04
4       2000-04-05
           ...
4518    2021-08-30
4519    2021-08-31
4520    2021-09-01
4521    2021-09-02
4522    2021-09-03
Name: Date, Length: 4523, dtype: object
                   stock  start_date current_price   minall maxall  \
0  ATLO_ended_2021-09-25  2000-02-15         23.41  11.9167  42.82

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     3.09033    15.007   18.0973   21.1877    24.278   27.3683   30.4587

  markup_70 markup_80 markup_90 markup_100
0    33.549   36.6393   39.7297      42.82
                   stock  start_date current_price   minall maxall  \
0  ATLO_ended_2021-09-25  2000-02-15         23.41  11.9167  42.82

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     3.09033    15.007   18.0973   21.1877    24.278   27.3683   30.4587

  markup_70 markup_80 markup_90 markup_100
0    33.549   36.6393   39.7297      42.82
./ticker_data/ticker_data_2021-09-25 - Copy/ATNFW_ended_2021-09-25.csv
         Date  Open    High    Low   Close  Adj Close  Volume
0  2021-09-24  1.03  0.9899  0.955  0.9775     0.9775   15815
tolistdate: 0    2021-09-24
Name: Date, dtype: object
                    stock  start_date current_price minall  maxall  \
0  ATNFW_ended_2021-09-25  2021-09-24        0.9775  0.955  0.9899

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00349   0.95849   0.96198   0.96547   0.96896   0.97245   0.97594

  markup_70 markup_80 markup_90 markup_100
0   0.97943   0.98292   0.98641     0.9899
                    stock  start_date current_price minall  maxall  \
0  ATNFW_ended_2021-09-25  2021-09-24        0.9775  0.955  0.9899

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00349   0.95849   0.96198   0.96547   0.96896   0.97245   0.97594

  markup_70 markup_80 markup_90 markup_100
0   0.97943   0.98292   0.98641     0.9899
./ticker_data/ticker_data_2021-09-25 - Copy/ATNF_ended_2021-09-25.csv
           Date    Open    High     Low   Close  Adj Close     Volume
0    2020-05-11  10.760  10.760  10.760  10.760     10.760          0
1    2020-06-08  10.835  10.835  10.835  10.835     10.835        200
2    2020-06-09  10.874  10.900  10.874  10.890     10.890       1600
3    2020-06-10  10.900  10.900  10.880  10.900     10.900       1800
4    2020-06-11  10.880  10.880  10.800  10.800     10.800       1200
..          ...     ...     ...     ...     ...        ...        ...
299  2021-08-30   5.290   5.510   5.133   5.430      5.430   53010000
300  2021-08-31   5.480   6.450   5.410   5.890      5.890  150700000
301  2021-09-01   5.875   6.820   5.875   6.610      6.610  118580000
302  2021-09-02   6.670   6.700   6.050   6.230      6.230   88240000
303  2021-09-03   6.310   6.565   6.010   6.350      6.350   51030000

[304 rows x 7 columns]
tolistdate: 0      2020-05-11
1      2020-06-08
2      2020-06-09
3      2020-06-10
4      2020-06-11
          ...
299    2021-08-30
300    2021-08-31
301    2021-09-01
302    2021-09-02
303    2021-09-03
Name: Date, Length: 304, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ATNF_ended_2021-09-25  2020-05-11          6.35    1.9  13.045      1.1145

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    3.0145     4.129    5.2435     6.358    7.4725     8.587    9.7015

  markup_80 markup_90 markup_100
0    10.816   11.9305     13.045
                   stock  start_date current_price minall  maxall each_markup  \
0  ATNF_ended_2021-09-25  2020-05-11          6.35    1.9  13.045      1.1145

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    3.0145     4.129    5.2435     6.358    7.4725     8.587    9.7015

  markup_80 markup_90 markup_100
0    10.816   11.9305     13.045
./ticker_data/ticker_data_2021-09-25 - Copy/ATNI_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   3.700000   3.750000   3.650000   3.650000   2.015067
1     2000-01-03   3.700000   3.700000   3.650000   3.650000   2.015067
2     2000-01-04   3.650000   3.650000   3.600000   3.600000   1.987463
3     2000-01-05   3.600000   3.600000   3.600000   3.600000   1.987463
4     2000-01-06   3.550000   3.550000   3.550000   3.550000   1.959859
...          ...        ...        ...        ...        ...        ...
5379  2021-08-30  45.330002  45.590000  44.980000  45.189999  45.189999
5380  2021-08-31  45.060001  45.759998  45.000000  45.590000  45.590000
5381  2021-09-01  45.490002  45.810001  45.060001  45.200001  45.200001
5382  2021-09-02  45.130001  47.400002  45.029999  47.090000  47.090000
5383  2021-09-03  47.169998  47.259998  45.330002  45.959999  45.959999

       Volume
0       21500
1        8000
2        1500
3        2000
4        2700
...       ...
5379  1970000
5380  3440000
5381  2150000
5382  5280000
5383  3880000

[5384 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5379    2021-08-30
5380    2021-08-31
5381    2021-09-01
5382    2021-09-02
5383    2021-09-03
Name: Date, Length: 5384, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATNI_ended_2021-09-25  1999-12-31         45.96  3.475  88.78      8.5305

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   12.0055    20.536   29.0665    37.597   46.1275    54.658   63.1885

  markup_80 markup_90 markup_100
0    71.719   80.2495      88.78
                   stock  start_date current_price minall maxall each_markup  \
0  ATNI_ended_2021-09-25  1999-12-31         45.96  3.475  88.78      8.5305

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   12.0055    20.536   29.0665    37.597   46.1275    54.658   63.1885

  markup_80 markup_90 markup_100
0    71.719   80.2495      88.78
./ticker_data/ticker_data_2021-09-25 - Copy/ATNX_ended_2021-09-25.csv
            Date    Open    High     Low  Close  Adj Close     Volume
0     2017-06-14  12.000  13.000  11.210  12.56      12.56    1951700
1     2017-06-15  12.700  13.840  12.300  13.68      13.68     808500
2     2017-06-16  13.660  13.890  13.400  13.89      13.89     120700
3     2017-06-19  13.900  15.780  13.765  14.52      14.52     392300
4     2017-06-20  15.350  15.421  14.120  14.49      14.49     390600
...          ...     ...     ...     ...    ...        ...        ...
1060  2021-08-30   3.670   3.760   3.590   3.62       3.62   79980000
1061  2021-08-31   3.640   3.690   3.590   3.65       3.65   61320000
1062  2021-09-01   3.680   3.900   3.660   3.89       3.89  145440000
1063  2021-09-02   3.895   3.910   3.690   3.70       3.70   90240000
1064  2021-09-03   3.740   3.740   3.560   3.60       3.60  105690000

[1065 rows x 7 columns]
tolistdate: 0       2017-06-14
1       2017-06-15
2       2017-06-16
3       2017-06-19
4       2017-06-20
           ...
1060    2021-08-30
1061    2021-08-31
1062    2021-09-01
1063    2021-09-02
1064    2021-09-03
Name: Date, Length: 1065, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATNX_ended_2021-09-25  2017-06-14           3.6   3.12  21.11       1.799

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.919     6.718     8.517    10.316    12.115    13.914    15.713

  markup_80 markup_90 markup_100
0    17.512    19.311      21.11
                   stock  start_date current_price minall maxall each_markup  \
0  ATNX_ended_2021-09-25  2017-06-14           3.6   3.12  21.11       1.799

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.919     6.718     8.517    10.316    12.115    13.914    15.713

  markup_80 markup_90 markup_100
0    17.512    19.311      21.11
./ticker_data/ticker_data_2021-09-25 - Copy/ATOM_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2016-08-08   8.000000   8.400000   7.900000   8.000000   8.000000
1     2016-08-09   7.780000   8.000000   7.780000   7.890000   7.890000
2     2016-08-10   7.973000   8.065000   7.900000   7.990000   7.990000
3     2016-08-11   8.050000   8.050000   7.860000   7.860000   7.860000
4     2016-08-12   7.950000   8.000000   7.800000   7.810000   7.810000
...          ...        ...        ...        ...        ...        ...
1274  2021-08-30  24.490000  24.980000  23.105000  24.030001  24.030001
1275  2021-08-31  23.840000  25.240000  23.090000  24.670000  24.670000
1276  2021-09-01  24.400000  24.639999  23.799999  24.020000  24.020000
1277  2021-09-02  24.330000  26.459999  24.120001  24.850000  24.850000
1278  2021-09-03  25.030001  26.000000  24.750000  25.260000  25.260000

        Volume
0        17800
1        17000
2        12100
3        12500
4        20100
...        ...
1274  38010000
1275  27790000
1276  23160000
1277  42420000
1278  29990000

[1279 rows x 7 columns]
tolistdate: 0       2016-08-08
1       2016-08-09
2       2016-08-10
3       2016-08-11
4       2016-08-12
           ...
1274    2021-08-30
1275    2021-08-31
1276    2021-09-01
1277    2021-09-02
1278    2021-09-03
Name: Date, Length: 1279, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATOM_ended_2021-09-25  2016-08-08         25.26   2.33  47.13        4.48

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      6.81     11.29     15.77     20.25     24.73     29.21     33.69

  markup_80 markup_90 markup_100
0     38.17     42.65      47.13
                   stock  start_date current_price minall maxall each_markup  \
0  ATOM_ended_2021-09-25  2016-08-08         25.26   2.33  47.13        4.48

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      6.81     11.29     15.77     20.25     24.73     29.21     33.69

  markup_80 markup_90 markup_100
0     38.17     42.65      47.13

./ticker_data/ticker_data_2021-09-25 - Copy/ATOS_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2012-11-08  819.000000  900.000000  765.000000  864.000000  864.000000
1     2012-11-09  844.200012  844.200012  729.000000  729.000000  729.000000
2     2012-11-12  718.200012  833.400024  718.200012  828.000000  828.000000
3     2012-11-13  835.200012  837.000000  795.599976  795.599976  795.599976
4     2012-11-14  820.799988  820.799988  768.599976  774.000000  774.000000
...          ...         ...         ...         ...         ...         ...
2210  2021-08-30    3.680000    3.760000    3.490000    3.530000    3.530000
2211  2021-08-31    3.530000    3.840000    3.510000    3.800000    3.800000
2212  2021-09-01    3.870000    3.960000    3.700000    3.760000    3.760000
2213  2021-09-02    3.770000    4.310000    3.760000    3.800000    3.800000
2214  2021-09-03    3.810000    3.890000    3.640000    3.750000    3.750000

          Volume
0           1100
1            200
2            100
3            100
4              0
...          ...
2210   651740000
2211   794910000
2212   966390000
2213  1573670000
2214   702460000

[2215 rows x 7 columns]
tolistdate: 0       2012-11-08
1       2012-11-09
2       2012-11-12
3       2012-11-13
4       2012-11-14
           ...
2210    2021-08-30
2211    2021-08-31
2212    2021-09-01
2213    2021-09-02
2214    2021-09-03
Name: Date, Length: 2215, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATOS_ended_2021-09-25  2012-11-08          3.75   0.76   2232     223.124

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   223.884   447.008   670.132   893.256   1116.38    1339.5   1562.63

  markup_80 markup_90 markup_100
0   1785.75   2008.88       2232
                   stock  start_date current_price minall maxall each_markup  \
0  ATOS_ended_2021-09-25  2012-11-08          3.75   0.76   2232     223.124

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   223.884   447.008   670.132   893.256   1116.38    1339.5   1562.63

  markup_80 markup_90 markup_100
0   1785.75   2008.88       2232
./ticker_data/ticker_data_2021-09-25 - Copy/ATRA_ended_2021-09-25.csv
            Date   Open       High     Low      Close  Adj Close     Volume
0     2014-10-16   9.89  11.250000   9.660  10.650000  10.650000    1416100
1     2014-10-17  10.26  12.500000  10.104  12.000000  12.000000     133100
2     2014-10-20  12.04  15.170000  12.040  14.350000  14.350000      93600
3     2014-10-21  14.37  15.235000  13.000  13.850000  13.850000      52000
4     2014-10-22  13.32  14.530000  13.300  13.670000  13.670000      51700
...          ...    ...        ...     ...        ...        ...        ...
1728  2021-08-30  14.76  15.180000  14.640  14.730000  14.730000   83490000
1729  2021-08-31  14.74  15.140000  14.650  14.980000  14.980000  239520000
1730  2021-09-01  14.94  15.840000  14.730  15.690000  15.690000   73520000
1731  2021-09-02  15.80  16.260000  15.710  16.120001  16.120001   60580000
1732  2021-09-03  16.00  16.129999  15.540  15.560000  15.560000   60120000

[1733 rows x 7 columns]
tolistdate: 0       2014-10-16
1       2014-10-17
2       2014-10-20
3       2014-10-21
4       2014-10-22
           ...
1728    2021-08-30
1729    2021-08-31
1730    2021-09-01
1731    2021-09-02
1732    2021-09-03
Name: Date, Length: 1733, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATRA_ended_2021-09-25  2014-10-16         15.56   4.52  65.56       6.104

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.624    16.728    22.832    28.936     35.04    41.144    47.248

  markup_80 markup_90 markup_100
0    53.352    59.456      65.56
                   stock  start_date current_price minall maxall each_markup  \
0  ATRA_ended_2021-09-25  2014-10-16         15.56   4.52  65.56       6.104

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.624    16.728    22.832    28.936     35.04    41.144    47.248

  markup_80 markup_90 markup_100
0    53.352    59.456      65.56
./ticker_data/ticker_data_2021-09-25 - Copy/ATRC_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2005-08-05  12.100000  15.450000  12.030000  14.080000  14.080000
1     2005-08-08  14.300000  15.050000  14.000000  14.200000  14.200000
2     2005-08-09  14.000000  15.000000  14.000000  14.700000  14.700000
3     2005-08-10  15.020000  15.120000  14.250000  14.500000  14.500000
4     2005-08-11  14.980000  14.980000  14.340000  14.950000  14.950000
...          ...        ...        ...        ...        ...        ...
4044  2021-08-30  74.589996  75.120003  73.239998  73.830002  73.830002
4045  2021-08-31  74.029999  74.430000  72.519997  73.620003  73.620003
4046  2021-09-01  74.019997  75.029999  73.010002  74.900002  74.900002
4047  2021-09-02  75.160004  76.320000  74.389999  75.809998  75.809998
4048  2021-09-03  75.580002  76.660004  75.379997  76.360001  76.360001

        Volume
0      3087900
1       246900
2       108100
3       139400
4        35800
...        ...
4044  18730000
4045  21200000
4046  13260000
4047  28090000
4048  18820000

[4049 rows x 7 columns]
tolistdate: 0       2005-08-05
1       2005-08-08
2       2005-08-09
3       2005-08-10
4       2005-08-11
           ...
4044    2021-08-30
4045    2021-08-31
4046    2021-09-01
4047    2021-09-02
4048    2021-09-03
Name: Date, Length: 4049, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATRC_ended_2021-09-25  2005-08-05         76.36      1   85.5        8.45

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.45      17.9     26.35      34.8     43.25      51.7     60.15

  markup_80 markup_90 markup_100
0      68.6     77.05       85.5
                   stock  start_date current_price minall maxall each_markup  \
0  ATRC_ended_2021-09-25  2005-08-05         76.36      1   85.5        8.45

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.45      17.9     26.35      34.8     43.25      51.7     60.15

  markup_80 markup_90 markup_100
0      68.6     77.05       85.5
./ticker_data/ticker_data_2021-09-25 - Copy/ATRI_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31   10.625000   10.625000   10.625000   10.625000    8.046102
1     2000-01-03   10.875000   10.875000   10.625000   10.625000    8.046102
2     2000-01-04   10.625000   10.625000   10.625000   10.625000    8.046102
3     2000-01-06   10.875000   10.875000   10.875000   10.875000    8.235423
4     2000-01-07   10.875000   10.875000   10.875000   10.875000    8.235423
...          ...         ...         ...         ...         ...         ...
5308  2021-08-30  703.630005  703.630005  703.630005  703.630005  703.630005
5309  2021-08-31  712.659973  712.659973  694.059998  694.059998  694.059998
5310  2021-09-01  689.309998  704.770020  689.309998  699.549988  699.549988
5311  2021-09-02  705.000000  709.719971  704.700012  704.700012  704.700012
5312  2021-09-03  705.000000  718.479980  705.000000  714.989990  714.989990

      Volume
0       3000
1       1100
2        800
3        500
4          0
...      ...
5308  160000
5309  680000
5310  720000
5311  360000
5312  830000

[5313 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-06
4       2000-01-07
           ...
5308    2021-08-30
5309    2021-08-31
5310    2021-09-01
5311    2021-09-02
5312    2021-09-03
Name: Date, Length: 5313, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  ATRI_ended_2021-09-25  1999-12-31        714.99  9.625  948.03     93.8405

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   103.466   197.306   291.147   384.987   478.828   572.668   666.509

  markup_80 markup_90 markup_100
0   760.349    854.19     948.03
                   stock  start_date current_price minall  maxall each_markup  \
0  ATRI_ended_2021-09-25  1999-12-31        714.99  9.625  948.03     93.8405

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   103.466   197.306   291.147   384.987   478.828   572.668   666.509

  markup_80 markup_90 markup_100
0   760.349    854.19     948.03
./ticker_data/ticker_data_2021-09-25 - Copy/ATRO_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   3.751605   3.751605   3.751605   3.751605   0.850822
1     2000-01-03   3.867395   3.867395   3.751605   3.751605   0.850822
2     2000-01-04   3.751605   3.774763   3.751605   3.751605   0.850822
3     2000-01-05   3.751605   3.797921   3.658973   3.751605   0.850822
4     2000-01-06   3.728447   3.797921   3.728447   3.797921   0.861326
...          ...        ...        ...        ...        ...        ...
5443  2021-08-30  14.060000  14.060000  13.430000  13.500000  13.500000
5444  2021-08-31  13.520000  13.640000  13.260000  13.360000  13.360000
5445  2021-09-01  13.480000  13.540000  13.320000  13.410000  13.410000
5446  2021-09-02  13.440000  13.760000  13.440000  13.630000  13.630000
5447  2021-09-03  13.970000  13.970000  13.420000  13.690000  13.690000

        Volume
0            0
1        23600
2        18200
3        13100
4        19100
...        ...
5443  10310000
5444   8100000
5445   7600000
5446   5780000
5447   8880000

[5448 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5443    2021-08-30
5444    2021-08-31
5445    2021-09-01
5446    2021-09-02
5447    2021-09-03
Name: Date, Length: 5448, dtype: object
                   stock  start_date current_price   minall  maxall  \
0  ATRO_ended_2021-09-25  1999-12-31         13.69  1.11529  49.482

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     4.83667   5.95196   10.7886   15.6253    20.462   25.2986   30.1353

  markup_70 markup_80 markup_90 markup_100
0    34.972   39.8087   44.6453     49.482
                   stock  start_date current_price   minall  maxall  \
0  ATRO_ended_2021-09-25  1999-12-31         13.69  1.11529  49.482

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     4.83667   5.95196   10.7886   15.6253    20.462   25.2986   30.1353

  markup_70 markup_80 markup_90 markup_100
0    34.972   39.8087   44.6453     49.482
./ticker_data/ticker_data_2021-09-25 - Copy/ATRS_ended_2021-09-25.csv
            Date     Open    High     Low   Close  Adj Close    Volume
0     1999-12-31  1.56250  1.6250  1.5000  1.5000     1.5000     46200
1     2000-01-03  1.53125  1.5625  1.5000  1.5625     1.5625      7900
2     2000-01-04  1.53125  1.6250  1.4375  1.5000     1.5000      6100
3     2000-01-05  1.50000  1.5625  1.5000  1.5625     1.5625      4700
4     2000-01-06  1.50000  1.5000  1.5000  1.5000     1.5000      1000
...          ...      ...     ...     ...     ...        ...       ...
5400  2021-08-30  4.00000  4.0600  3.9600  3.9700     3.9700  43670000
5401  2021-08-31  3.96000  4.0000  3.9000  3.9400     3.9400  41800000
5402  2021-09-01  3.96000  3.9700  3.8900  3.9100     3.9100  36410000
5403  2021-09-02  3.91000  3.9400  3.8700  3.9300     3.9300  34820000
5404  2021-09-03  3.92000  3.9700  3.8800  3.9200     3.9200  43600000

[5405 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5400    2021-08-30
5401    2021-08-31
5402    2021-09-01
5403    2021-09-02
5404    2021-09-03
Name: Date, Length: 5405, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATRS_ended_2021-09-25  1999-12-31          3.92   0.29  7.875      0.7585

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    1.0485     1.807    2.5655     3.324    4.0825     4.841    5.5995

  markup_80 markup_90 markup_100
0     6.358    7.1165      7.875
                   stock  start_date current_price minall maxall each_markup  \
0  ATRS_ended_2021-09-25  1999-12-31          3.92   0.29  7.875      0.7585

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    1.0485     1.807    2.5655     3.324    4.0825     4.841    5.5995

  markup_80 markup_90 markup_100
0     6.358    7.1165      7.875
./ticker_data/ticker_data_2021-09-25 - Copy/ATSG_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2003-07-23   0.300000   0.650000   0.300000   0.600000   0.600000
1     2003-07-24   0.650000   0.950000   0.600000   0.900000   0.900000
2     2003-07-25   0.900000   1.400000   0.900000   1.350000   1.350000
3     2003-07-28   1.300000   1.500000   1.200000   1.200000   1.200000
4     2003-07-29   1.200000   1.250000   1.100000   1.200000   1.200000
...          ...        ...        ...        ...        ...        ...
4558  2021-08-30  26.930000  27.600000  26.820000  27.120001  27.120001
4559  2021-08-31  27.129999  27.920000  27.129999  27.389999  27.389999
4560  2021-09-01  27.270000  27.660000  27.070000  27.190001  27.190001
4561  2021-09-02  27.219999  27.559999  26.969999  27.180000  27.180000
4562  2021-09-03  27.190001  27.330000  26.410000  26.570000  26.570000

        Volume
0     13905300
1      8900400
2     11532200
3      3787000
4      1385900
...        ...
4558  78890000
4559  53980000
4560  42330000
4561  48390000
4562  50080000

[4563 rows x 7 columns]
tolistdate: 0       2003-07-23
1       2003-07-24
2       2003-07-25
3       2003-07-28
4       2003-07-29
           ...
4558    2021-08-30
4559    2021-08-31
4560    2021-09-01
4561    2021-09-02
4562    2021-09-03
Name: Date, Length: 4563, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATSG_ended_2021-09-25  2003-07-23         26.57   0.12  32.43       3.231

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.351     6.582     9.813    13.044    16.275    19.506    22.737

  markup_80 markup_90 markup_100
0    25.968    29.199      32.43
                   stock  start_date current_price minall maxall each_markup  \
0  ATSG_ended_2021-09-25  2003-07-23         26.57   0.12  32.43       3.231

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.351     6.582     9.813    13.044    16.275    19.506    22.737

  markup_80 markup_90 markup_100
0    25.968    29.199      32.43
./ticker_data/ticker_data_2021-09-25 - Copy/ATSPT_ended_2021-09-25.csv
          Date  Open   High    Low  Close  Adj Close  Volume
0   2021-04-23  9.75  9.781  9.750  9.781      9.781  124700
1   2021-04-26  4.50  9.970  4.500  9.900      9.900    4200
2   2021-04-27  9.90  9.900  9.900  9.900      9.900       0
3   2021-04-28  9.95  9.950  9.720  9.720      9.720     800
4   2021-04-29  9.72  9.720  9.720  9.720      9.720       0
..         ...   ...    ...    ...    ...        ...     ...
60  2021-09-16  9.79  9.800  9.775  9.790      9.790    5000
61  2021-09-17  9.75  9.750  9.750  9.750      9.750    1700
62  2021-09-21  9.75  9.750  9.750  9.750      9.750    5800
63  2021-09-22  9.75  9.750  9.750  9.750      9.750     300
64  2021-09-23  9.75  9.750  9.750  9.750      9.750    4100

[65 rows x 7 columns]
tolistdate: 0     2021-04-23
1     2021-04-26
2     2021-04-27
3     2021-04-28
4     2021-04-29
         ...
60    2021-09-16
61    2021-09-17
62    2021-09-21
63    2021-09-22
64    2021-09-23
Name: Date, Length: 65, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ATSPT_ended_2021-09-25  2021-04-23          9.75    4.5   9.99       0.549

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.049     5.598     6.147     6.696     7.245     7.794     8.343

  markup_80 markup_90 markup_100
0     8.892     9.441       9.99
                    stock  start_date current_price minall maxall each_markup  \
0  ATSPT_ended_2021-09-25  2021-04-23          9.75    4.5   9.99       0.549

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.049     5.598     6.147     6.696     7.245     7.794     8.343

  markup_80 markup_90 markup_100
0     8.892     9.441       9.99
./ticker_data/ticker_data_2021-09-25 - Copy/ATSPU_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close   Volume
0    2021-03-11  9.950  9.960  9.900  9.930      9.930  1716100
1    2021-03-12  9.900  9.940  9.900  9.930      9.930   147300
2    2021-03-15  9.950  9.970  9.900  9.920      9.920   807900
3    2021-03-16  9.950  9.950  9.900  9.900      9.900   272100
4    2021-03-17  9.940  9.940  9.900  9.910      9.910   176000
..          ...    ...    ...    ...    ...        ...      ...
106  2021-08-27  9.870  9.870  9.860  9.860      9.860   700000
107  2021-08-30  9.860  9.860  9.860  9.860      9.860        0
108  2021-08-31  9.860  9.920  9.850  9.900      9.900  1550000
109  2021-09-02  9.863  9.863  9.863  9.863      9.863    60000
110  2021-09-03  9.863  9.863  9.863  9.863      9.863        0

[111 rows x 7 columns]
tolistdate: 0      2021-03-11
1      2021-03-12
2      2021-03-15
3      2021-03-16
4      2021-03-17
          ...
106    2021-08-27
107    2021-08-30
108    2021-08-31
109    2021-09-02
110    2021-09-03
Name: Date, Length: 111, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ATSPU_ended_2021-09-25  2021-03-11         9.863   9.75  10.03       0.028

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.778     9.806     9.834     9.862      9.89     9.918     9.946

  markup_80 markup_90 markup_100

0     9.974    10.002      10.03
                    stock  start_date current_price minall maxall each_markup  \
0  ATSPU_ended_2021-09-25  2021-03-11         9.863   9.75  10.03       0.028

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.778     9.806     9.834     9.862      9.89     9.918     9.946

  markup_80 markup_90 markup_100
0     9.974    10.002      10.03
./ticker_data/ticker_data_2021-09-25 - Copy/ATSPW_ended_2021-09-25.csv
         Date  Open   High    Low  Close  Adj Close  Volume
0  2021-09-24   0.0  0.675  0.675  0.675      0.675       3
tolistdate: 0    2021-09-24
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ATSPW_ended_2021-09-25  2021-09-24         0.675  0.675  0.675           0

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.675     0.675     0.675     0.675     0.675     0.675     0.675

  markup_80 markup_90 markup_100
0     0.675     0.675      0.675
                    stock  start_date current_price minall maxall each_markup  \
0  ATSPW_ended_2021-09-25  2021-09-24         0.675  0.675  0.675           0

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.675     0.675     0.675     0.675     0.675     0.675     0.675

  markup_80 markup_90 markup_100
0     0.675     0.675      0.675
./ticker_data/ticker_data_2021-09-25 - Copy/ATVCU_ended_2021-09-25.csv
           Date    Open    High     Low  Close  Adj Close   Volume
0    2021-03-05  10.100  10.400  10.040  10.20      10.20  4176200
1    2021-03-08  10.320  10.400  10.110  10.20      10.20   730700
2    2021-03-09  10.200  10.200  10.120  10.15      10.15    67200
3    2021-03-10  10.150  10.340  10.100  10.20      10.20   121600
4    2021-03-11  10.340  10.340  10.200  10.23      10.23     6300
..          ...     ...     ...     ...    ...        ...      ...
117  2021-09-17   9.910   9.910   9.889   9.90       9.90     2300
118  2021-09-20   9.910   9.910   9.910   9.91       9.91      800
119  2021-09-21   9.880   9.880   9.880   9.88       9.88      300
120  2021-09-22   9.910   9.910   9.910   9.91       9.91     6100
121  2021-09-24   9.905   9.905   9.900   9.90       9.90      800

[122 rows x 7 columns]
tolistdate: 0      2021-03-05
1      2021-03-08
2      2021-03-09
3      2021-03-10
4      2021-03-11
          ...
117    2021-09-17
118    2021-09-20
119    2021-09-21
120    2021-09-22
121    2021-09-24
Name: Date, Length: 122, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  ATVCU_ended_2021-09-25  2021-03-05           9.9    9.8  10.63       0.083

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.883     9.966    10.049    10.132    10.215    10.298    10.381

  markup_80 markup_90 markup_100
0    10.464    10.547      10.63
                    stock  start_date current_price minall maxall each_markup  \
0  ATVCU_ended_2021-09-25  2021-03-05           9.9    9.8  10.63       0.083

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.883     9.966    10.049    10.132    10.215    10.298    10.381

  markup_80 markup_90 markup_100
0    10.464    10.547      10.63
./ticker_data/ticker_data_2021-09-25 - Copy/ATVCW_ended_2021-09-25.csv
         Date    Open    High     Low  Close  Adj Close  Volume
0  2021-09-21  1.0433  0.8702  0.8602  0.935      0.935     675
tolistdate: 0    2021-09-21
Name: Date, dtype: object
                    stock  start_date current_price  minall  maxall  \
0  ATVCW_ended_2021-09-25  2021-09-21         0.935  0.8602  0.8702

   each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0  0.000999999    0.8612    0.8622    0.8632    0.8642    0.8652    0.8662

  markup_70 markup_80 markup_90 markup_100
0    0.8672    0.8682    0.8692     0.8702
                    stock  start_date current_price  minall  maxall  \
0  ATVCW_ended_2021-09-25  2021-09-21         0.935  0.8602  0.8702

   each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0  0.000999999    0.8612    0.8622    0.8632    0.8642    0.8652    0.8662

  markup_70 markup_80 markup_90 markup_100
0    0.8672    0.8682    0.8692     0.8702
./ticker_data/ticker_data_2021-09-25 - Copy/ATVC_ended_2021-09-25.csv
          Date   Open   High    Low  Close  Adj Close  Volume
0   2021-05-26  10.50  10.50  10.03  10.03      10.03     200
1   2021-05-27   9.90   9.90   9.90   9.90       9.90     500
2   2021-05-28   9.90   9.90   9.90   9.90       9.90     100
3   2021-06-01   9.95   9.95   9.95   9.95       9.95     600
4   2021-06-02   9.95   9.95   9.95   9.95       9.95     100
..         ...    ...    ...    ...    ...        ...     ...
60  2021-08-30   9.64   9.64   9.64   9.64       9.64   20000
61  2021-08-31   9.64   9.64   9.64   9.64       9.64       0
62  2021-09-01   9.63   9.70   9.63   9.69       9.69  170000
63  2021-09-02   9.69   9.69   9.69   9.69       9.69  280000
64  2021-09-03   9.69   9.69   9.69   9.69       9.69       0

[65 rows x 7 columns]
tolistdate: 0     2021-05-26
1     2021-05-27
2     2021-05-28
3     2021-06-01
4     2021-06-02
         ...
60    2021-08-30
61    2021-08-31
62    2021-09-01
63    2021-09-02
64    2021-09-03
Name: Date, Length: 65, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATVC_ended_2021-09-25  2021-05-26          9.69  9.618   10.5      0.0882

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.7062    9.7944    9.8826    9.9708    10.059   10.1472   10.2354

  markup_80 markup_90 markup_100
0   10.3236   10.4118       10.5
                   stock  start_date current_price minall maxall each_markup  \
0  ATVC_ended_2021-09-25  2021-05-26          9.69  9.618   10.5      0.0882

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.7062    9.7944    9.8826    9.9708    10.059   10.1472   10.2354

  markup_80 markup_90 markup_100
0   10.3236   10.4118       10.5
./ticker_data/ticker_data_2021-09-25 - Copy/ATVI_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   1.250000   1.364583   1.187500   1.276042   1.138029
1     2000-01-03   1.312500   1.375000   1.166667   1.369792   1.221639
2     2000-01-04   1.343750   1.354167   1.187500   1.328125   1.184479
3     2000-01-05   1.317708   1.364583   1.312500   1.333333   1.189124
4     2000-01-06   1.322917   1.333333   1.296875   1.307292   1.165899
...          ...        ...        ...        ...        ...        ...
5450  2021-08-30  81.500000  81.559998  79.919998  81.120003  81.120003
5451  2021-08-31  81.480003  83.379997  81.199997  82.370003  82.370003
5452  2021-09-01  82.730003  83.379997  82.000000  82.300003  82.300003
5453  2021-09-02  82.750000  82.849998  81.139999  81.309998  81.309998
5454  2021-09-03  81.209999  81.650002  80.779999  81.180000  81.180000

         Volume
0       2582600
1       7225800
2       4262400
3       3389000
4       2429000
...         ...
5450  840520000
5451  947690000
5452  622600000
5453  843470000
5454  560540000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price    minall  maxall  \
0  ATVI_ended_2021-09-25  1999-12-31         81.18  0.447917  104.53

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     10.4082   10.8561   21.2643   31.6725   42.0807    52.489   62.8972

  markup_70 markup_80 markup_90 markup_100
0   73.3054   83.7136   94.1218     104.53
                   stock  start_date current_price    minall  maxall  \
0  ATVI_ended_2021-09-25  1999-12-31         81.18  0.447917  104.53

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     10.4082   10.8561   21.2643   31.6725   42.0807    52.489   62.8972

  markup_70 markup_80 markup_90 markup_100
0   73.3054   83.7136   94.1218     104.53
./ticker_data/ticker_data_2021-09-25 - Copy/ATXI_ended_2021-09-25.csv
            Date  Open   High    Low  Close  Adj Close   Volume
0     2017-06-27  7.60  8.580  7.570   8.25       8.25   580200
1     2017-06-28  8.10  8.370  7.810   7.92       7.92   135300
2     2017-06-29  7.90  7.978  7.710   7.88       7.88    44000
3     2017-06-30  7.90  8.150  7.720   7.95       7.95    20800
4     2017-07-03  8.27  8.270  7.810   8.00       8.00    16600
...          ...   ...    ...    ...    ...        ...      ...
1051  2021-08-30  1.67  1.770  1.650   1.72       1.72  5350000
1052  2021-08-31  1.73  1.840  1.730   1.81       1.81  8250000
1053  2021-09-01  1.83  1.830  1.741   1.80       1.80  6870000
1054  2021-09-02  1.80  1.800  1.730   1.78       1.78  4360000
1055  2021-09-03  1.80  1.800  1.740   1.74       1.74  2650000

[1056 rows x 7 columns]
tolistdate: 0       2017-06-27
1       2017-06-28
2       2017-06-29
3       2017-06-30
4       2017-07-03
           ...
1051    2021-08-30
1052    2021-08-31
1053    2021-09-01
1054    2021-09-02
1055    2021-09-03
Name: Date, Length: 1056, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  ATXI_ended_2021-09-25  2017-06-27          1.74   1.53  12.34       1.081

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.611     3.692     4.773     5.854     6.935     8.016     9.097

  markup_80 markup_90 markup_100
0    10.178    11.259      12.34
                   stock  start_date current_price minall maxall each_markup  \
0  ATXI_ended_2021-09-25  2017-06-27          1.74   1.53  12.34       1.081

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.611     3.692     4.773     5.854     6.935     8.016     9.097

  markup_80 markup_90 markup_100
0    10.178    11.259      12.34
./ticker_data/ticker_data_2021-09-25 - Copy/AUBAP_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-06-03  24.920000  25.200001  24.920000  25.150000  23.632940
1    2020-06-04  25.150000  25.200001  25.049999  25.139999  23.623545
2    2020-06-05  25.100000  25.190001  25.000000  25.000000  23.491989
3    2020-06-08  25.049999  25.049999  24.920000  24.980000  23.473196
4    2020-06-09  24.950001  25.920000  24.850000  25.000000  23.491989
..          ...        ...        ...        ...        ...        ...
312  2021-08-30  28.000000  28.340000  27.740000  28.340000  28.340000
313  2021-08-31  28.124001  28.205000  27.889999  28.205000  28.205000
314  2021-09-01  28.389999  28.500000  27.893000  28.250000  28.250000
315  2021-09-02  28.200001  28.400000  28.200001  28.400000  28.400000
316  2021-09-03  28.370001  28.370001  28.100000  28.100000  28.100000

      Volume
0    1741100
1     740300
2     525000
3     114900
4     223000
..       ...
312   690000
313  1670000
314  1900000
315   560000
316   450000

[317 rows x 7 columns]
tolistdate: 0      2020-06-03
1      2020-06-04
2      2020-06-05
3      2020-06-08
4      2020-06-09
          ...
312    2021-08-30
313    2021-08-31
314    2021-09-01
315    2021-09-02
316    2021-09-03
Name: Date, Length: 317, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AUBAP_ended_2021-09-25  2020-06-03          28.1  22.05  28.69       0.664

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    22.714    23.378    24.042    24.706     25.37    26.034    26.698

  markup_80 markup_90 markup_100
0    27.362    28.026      28.69
                    stock  start_date current_price minall maxall each_markup  \
0  AUBAP_ended_2021-09-25  2020-06-03          28.1  22.05  28.69       0.664

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    22.714    23.378    24.042    24.706     25.37    26.034    26.698

  markup_80 markup_90 markup_100
0    27.362    28.026      28.69
./ticker_data/ticker_data_2021-09-25 - Copy/AUBN_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  14.500000  14.500000  14.500000  14.500000   7.445821
1     2000-01-05  13.500000  14.500000  13.500000  14.500000   7.445821
2     2000-01-07  14.500000  14.750000  14.500000  14.500000   7.445821
3     2000-01-10  16.250000  16.250000  15.250000  15.312500   7.863045
4     2000-01-11  15.312500  15.312500  15.312500  15.312500   7.863045
...          ...        ...        ...        ...        ...        ...
4710  2021-08-31  34.509998  34.509998  34.349998  34.349998  34.349998
4711  2021-09-01  34.349998  34.349998  34.349998  34.349998  34.349998
4712  2021-09-02  34.200001  34.320000  33.410000  34.320000  34.320000
4713  2021-09-03  34.320000  35.000000  34.320000  35.000000  35.000000
4714  2021-09-09        NaN        NaN        NaN        NaN        NaN

        Volume
0          0.0
1       2500.0
2       3600.0
3       3400.0
4          0.0
...        ...
4710  160000.0
4711       0.0
4712  300000.0
4713  150000.0
4714       NaN

[4715 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-05
2       2000-01-07
3       2000-01-10
4       2000-01-11
           ...
4710    2021-08-31
4711    2021-09-01
4712    2021-09-02
4713    2021-09-03
4714    2021-09-09
Name: Date, Length: 4715, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AUBN_ended_2021-09-25  1999-12-31           NaN   8.75  65.55        5.68

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     14.43     20.11     25.79     31.47     37.15     42.83     48.51

  markup_80 markup_90 markup_100
0     54.19     59.87      65.55
                   stock  start_date current_price minall maxall each_markup  \
0  AUBN_ended_2021-09-25  1999-12-31           NaN   8.75  65.55        5.68

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     14.43     20.11     25.79     31.47     37.15     42.83     48.51

  markup_80 markup_90 markup_100
0     54.19     59.87      65.55
./ticker_data/ticker_data_2021-09-25 - Copy/AUB_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   9.833333   9.833333   9.750000   9.750000   5.629371
1     2000-01-03   9.500000   9.500000   9.166667   9.166667   5.292570
2     2000-01-04   9.166667   9.833333   9.000000   9.833333   5.677486
3     2000-01-05   9.666667   9.666667   9.666667   9.666667   5.581256
4     2000-01-06   9.666667   9.666667   9.000000   9.000000   5.196342
...          ...        ...        ...        ...        ...        ...
5401  2021-08-30  37.910000  37.910000  36.709999  36.799999  36.799999
5402  2021-08-31  36.930000  37.400002  36.840000  37.000000  37.000000
5403  2021-09-01  37.119999  37.119999  36.330002  36.540001  36.540001
5404  2021-09-02  36.529999  36.849998  36.259998  36.360001  36.360001
5405  2021-09-03  36.480000  36.830002  35.950001  36.189999  36.189999

        Volume
0         3000
1         3400
2         7600
3          100
4          600
...        ...
5401  20110000
5402  22010000
5403  11760000
5404  14550000
5405  14320000

[5406 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5401    2021-08-30
5402    2021-08-31
5403    2021-09-01
5404    2021-09-02
5405    2021-09-03
Name: Date, Length: 5406, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  AUB_ended_2021-09-25  1999-12-31         36.19   5.75  42.74       3.699

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.449    13.148    16.847    20.546    24.245    27.944    31.643

  markup_80 markup_90 markup_100
0    35.342    39.041      42.74
                  stock  start_date current_price minall maxall each_markup  \
0  AUB_ended_2021-09-25  1999-12-31         36.19   5.75  42.74       3.699

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.449    13.148    16.847    20.546    24.245    27.944    31.643

  markup_80 markup_90 markup_100
0    35.342    39.041      42.74
./ticker_data/ticker_data_2021-09-25 - Copy/AUDC_ended_2021-09-25.csv

            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  47.031250  47.031250  45.437500  46.000000  42.886959
1     2000-01-03  46.312500  46.625000  42.625000  43.750000  40.789234
2     2000-01-04  41.500000  41.500000  35.000000  35.750000  33.330627
3     2000-01-05  35.687500  36.687500  34.687500  36.062500  33.621983
4     2000-01-06  36.687500  36.687500  35.687500  36.312500  33.855061
...          ...        ...        ...        ...        ...        ...
5449  2021-08-30  32.549999  32.790001  32.130001  32.250000  32.250000
5450  2021-08-31  32.150002  32.380001  31.219999  31.299999  31.299999
5451  2021-09-01  31.590000  32.680000  31.590000  32.459999  32.459999
5452  2021-09-02  32.340000  33.180000  32.240002  33.020000  33.020000
5453  2021-09-03  32.959999  33.380001  32.910000  33.119999  33.119999

        Volume
0        42200
1        91200
2       492200
3        83600
4       195200
...        ...
5449  10740000
5450  16480000
5451  14980000
5452  21210000
5453   7750000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AUDC_ended_2021-09-25  1999-12-31         33.12   0.92     76       7.508

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.428    15.936    23.444    30.952     38.46    45.968    53.476

  markup_80 markup_90 markup_100
0    60.984    68.492         76
                   stock  start_date current_price minall maxall each_markup  \
0  AUDC_ended_2021-09-25  1999-12-31         33.12   0.92     76       7.508

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.428    15.936    23.444    30.952     38.46    45.968    53.476

  markup_80 markup_90 markup_100
0    60.984    68.492         76
./ticker_data/ticker_data_2021-09-25 - Copy/AUPH_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2014-09-03   4.000000   4.000000   4.000000   4.000000   4.000000
1     2014-09-04   4.000000   4.000000   3.730000   3.730000   3.730000
2     2014-09-05   3.730000   3.730000   3.730000   3.730000   3.730000
3     2014-09-10   3.680000   3.840000   3.680000   3.840000   3.840000
4     2014-09-11   4.240000   4.240000   3.520000   3.550000   3.550000
...          ...        ...        ...        ...        ...        ...
1754  2021-08-30  17.799999  18.120001  16.530001  17.020000  17.020000
1755  2021-08-31  16.959999  17.070000  16.139999  16.280001  16.280001
1756  2021-09-01  16.389999  17.580000  16.360001  16.980000  16.980000
1757  2021-09-02  16.898001  17.570000  16.730000  17.549999  17.549999
1758  2021-09-03  17.500000  17.775000  17.200001  17.540001  17.540001

         Volume
0          5500
1          1200
2             0
3          1500
4           400
...         ...
1754  392810000
1755  293200000
1756  228450000
1757  228530000
1758  164960000

[1759 rows x 7 columns]
tolistdate: 0       2014-09-03
1       2014-09-04
2       2014-09-05
3       2014-09-10
4       2014-09-11
           ...
1754    2021-08-30
1755    2021-08-31
1756    2021-09-01
1757    2021-09-02
1758    2021-09-03
Name: Date, Length: 1759, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AUPH_ended_2021-09-25  2014-09-03         17.54   1.41  21.93       2.052

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.462     5.514     7.566     9.618     11.67    13.722    15.774

  markup_80 markup_90 markup_100
0    17.826    19.878      21.93
                   stock  start_date current_price minall maxall each_markup  \
0  AUPH_ended_2021-09-25  2014-09-03         17.54   1.41  21.93       2.052

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.462     5.514     7.566     9.618     11.67    13.722    15.774

  markup_80 markup_90 markup_100
0    17.826    19.878      21.93
./ticker_data/ticker_data_2021-09-25 - Copy/AURCU_ended_2021-09-25.csv
           Date   Open   High     Low   Close  Adj Close   Volume
0    2021-03-04   9.95  10.01   9.950   9.970      9.970  6626900
1    2021-03-05   9.92  10.01   9.920  10.000     10.000  2124100
2    2021-03-08  10.00  10.04   9.937  10.015     10.015   209200
3    2021-03-09  10.06  10.06  10.000  10.060     10.060   360200
4    2021-03-10  10.06  10.06  10.020  10.030     10.030    43100
..          ...    ...    ...     ...     ...        ...      ...
108  2021-08-27  10.38  10.38  10.370  10.380     10.380   390000
109  2021-08-30  10.38  10.38  10.380  10.380     10.380        0
110  2021-09-01  10.15  10.24  10.130  10.240     10.240  2730000
111  2021-09-02  10.24  10.24  10.240  10.240     10.240    60000
112  2021-09-03  10.31  10.31  10.300  10.300     10.300    40000

[113 rows x 7 columns]
tolistdate: 0      2021-03-04
1      2021-03-05
2      2021-03-08
3      2021-03-09
4      2021-03-10
          ...
108    2021-08-27
109    2021-08-30
110    2021-09-01
111    2021-09-02
112    2021-09-03
Name: Date, Length: 113, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AURCU_ended_2021-09-25  2021-03-04          10.3   9.78  11.56       0.178

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.958    10.136    10.314    10.492     10.67    10.848    11.026

  markup_80 markup_90 markup_100
0    11.204    11.382      11.56
                    stock  start_date current_price minall maxall each_markup  \
0  AURCU_ended_2021-09-25  2021-03-04          10.3   9.78  11.56       0.178

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.958    10.136    10.314    10.492     10.67    10.848    11.026

  markup_80 markup_90 markup_100
0    11.204    11.382      11.56
./ticker_data/ticker_data_2021-09-25 - Copy/AURCW_ended_2021-09-25.csv
         Date  Open  High   Low  Close  Adj Close  Volume
0  2021-09-22   0.0  1.57  1.53   1.57       1.57   25852
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  AURCW_ended_2021-09-25  2021-09-22          1.57   1.53   1.57  0.00400001

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.534     1.538     1.542     1.546      1.55     1.554     1.558

  markup_80 markup_90 markup_100
0     1.562     1.566       1.57
                    stock  start_date current_price minall maxall each_markup  \
0  AURCW_ended_2021-09-25  2021-09-22          1.57   1.53   1.57  0.00400001

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.534     1.538     1.542     1.546      1.55     1.554     1.558

  markup_80 markup_90 markup_100
0     1.562     1.566       1.57
./ticker_data/ticker_data_2021-09-25 - Copy/AURC_ended_2021-09-25.csv
          Date   Open    High     Low   Close  Adj Close   Volume
0   2021-04-30   9.76  10.450   9.760  10.350     10.350     1900
1   2021-05-03  10.35  10.350   9.620  10.000     10.000      900
2   2021-05-04  10.00  10.000  10.000  10.000     10.000      100
3   2021-05-05  10.70  10.700  10.500  10.500     10.500      700
4   2021-05-06  10.50  10.500  10.500  10.500     10.500        0
..         ...    ...     ...     ...     ...        ...      ...
82  2021-08-30   9.91   9.950   9.890   9.928      9.928   150000
83  2021-08-31   9.95   9.970   9.926   9.960      9.960  1790000
84  2021-09-01   9.92   9.950   9.900   9.930      9.930  3520000
85  2021-09-02   9.94   9.948   9.925   9.930      9.930   220000
86  2021-09-03   9.95   9.950   9.914   9.940      9.940   100000

[87 rows x 7 columns]
tolistdate: 0     2021-04-30
1     2021-05-03
2     2021-05-04
3     2021-05-05
4     2021-05-06
         ...
82    2021-08-30
83    2021-08-31
84    2021-09-01
85    2021-09-02
86    2021-09-03
Name: Date, Length: 87, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AURC_ended_2021-09-25  2021-04-30          9.94   9.62  11.11       0.149

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.769     9.918    10.067    10.216    10.365    10.514    10.663

  markup_80 markup_90 markup_100
0    10.812    10.961      11.11
                   stock  start_date current_price minall maxall each_markup  \
0  AURC_ended_2021-09-25  2021-04-30          9.94   9.62  11.11       0.149

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.769     9.918    10.067    10.216    10.365    10.514    10.663

  markup_80 markup_90 markup_100
0    10.812    10.961      11.11
./ticker_data/ticker_data_2021-09-25 - Copy/AUTL_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-06-22  28.000000  30.000000  25.000000  25.000000  25.000000
1    2018-06-25  24.700001  26.950001  24.070000  26.190001  26.190001
2    2018-06-26  26.510000  27.959999  25.500000  27.750000  27.750000
3    2018-06-27  27.790001  27.790001  25.344999  26.639999  26.639999
4    2018-06-28  25.076000  26.809999  25.076000  26.180000  26.180000
..          ...        ...        ...        ...        ...        ...
802  2021-08-30   6.810000   7.190000   6.710000   6.840000   6.840000
803  2021-08-31   6.940000   7.100000   6.620000   6.870000   6.870000
804  2021-09-01   6.900000   7.340000   6.840000   7.150000   7.150000
805  2021-09-02   7.280000   7.550000   7.223000   7.370000   7.370000
806  2021-09-03   7.310000   7.310000   6.930000   7.270000   7.270000

       Volume
0     3153600
1      478600
2      380000
3      180100
4      186700
..        ...
802  70340000
803  60180000
804  85470000
805  66220000
806  88120000

[807 rows x 7 columns]
tolistdate: 0      2018-06-22
1      2018-06-25
2      2018-06-26
3      2018-06-27
4      2018-06-28
          ...
802    2021-08-30
803    2021-08-31
804    2021-09-01
805    2021-09-02
806    2021-09-03
Name: Date, Length: 807, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AUTL_ended_2021-09-25  2018-06-22          7.27      3  53.24       5.024

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.024    13.048    18.072    23.096     28.12    33.144    38.168

  markup_80 markup_90 markup_100
0    43.192    48.216      53.24
                   stock  start_date current_price minall maxall each_markup  \
0  AUTL_ended_2021-09-25  2018-06-22          7.27      3  53.24       5.024

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.024    13.048    18.072    23.096     28.12    33.144    38.168

  markup_80 markup_90 markup_100
0    43.192    48.216      53.24
./ticker_data/ticker_data_2021-09-25 - Copy/AUTO_ended_2021-09-25.csv
            Date     Open     High      Low    Close  Adj Close    Volume
0     1999-12-31  73.7500  76.2500  72.8125  75.9375    75.9375     50300
1     2000-01-03  78.7500  80.0000  76.2500  76.8750    76.8750     56200
2     2000-01-04  76.5625  85.6250  75.0000  81.2500    81.2500     57200
3     2000-01-05  80.9375  82.8125  75.0000  81.2500    81.2500     65500
4     2000-01-06  85.3125  90.0000  82.5000  84.3750    84.3750    182000
...          ...      ...      ...      ...      ...        ...       ...
5450  2021-08-30   2.6400   2.7200   2.5500   2.6300     2.6300   8460000
5451  2021-08-31   2.6200   2.7200   2.6200   2.6800     2.6800  14140000
5452  2021-09-01   2.6900   2.7300   2.6800   2.6900     2.6900   4060000
5453  2021-09-02   2.7100   2.7200   2.6200   2.6500     2.6500   2080000
5454  2021-09-03   2.7000   2.7000   2.6400   2.6800     2.6800   4440000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AUTO_ended_2021-09-25  1999-12-31          2.68    0.5     90        8.95

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.45      18.4     27.35      36.3     45.25      54.2     63.15

  markup_80 markup_90 markup_100
0      72.1     81.05         90
                   stock  start_date current_price minall maxall each_markup  \
0  AUTO_ended_2021-09-25  1999-12-31          2.68    0.5     90        8.95

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.45      18.4     27.35      36.3     45.25      54.2     63.15

  markup_80 markup_90 markup_100
0      72.1     81.05         90
./ticker_data/ticker_data_2021-09-25 - Copy/AUUDW_ended_2021-09-25.csv
         Date      Open    High     Low  Close  Adj Close  Volume
0  2021-09-22  0.839699  0.7888  0.6505   0.73       0.73    5627
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price  minall  maxall  \
0  AUUDW_ended_2021-09-25  2021-09-22          0.73  0.6505  0.7888

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.01383   0.66433   0.67816   0.69199   0.70582   0.71965   0.73348

  markup_70 markup_80 markup_90 markup_100
0   0.74731   0.76114   0.77497     0.7888
                    stock  start_date current_price  minall  maxall  \
0  AUUDW_ended_2021-09-25  2021-09-22          0.73  0.6505  0.7888

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.01383   0.66433   0.67816   0.69199   0.70582   0.71965   0.73348

  markup_70 markup_80 markup_90 markup_100
0   0.74731   0.76114   0.77497     0.7888
./ticker_data/ticker_data_2021-09-25 - Copy/AUUD_ended_2021-09-25.csv
           Date  Open  High   Low  Close  Adj Close    Volume
0    2021-02-17  4.00  4.09  2.90   3.34       3.34   1140900
1    2021-02-18  3.40  3.40  2.91   2.99       2.99    410800
2    2021-02-19  3.11  3.12  2.76   3.07       3.07    259200
3    2021-02-22  3.05  3.50  2.90   3.05       3.05    618000
4    2021-02-23  3.05  3.21  2.70   3.11       3.11    299600
..          ...   ...   ...   ...    ...        ...       ...
134  2021-08-30  3.05  3.12  2.90   2.91       2.91  39990000
135  2021-08-31  2.93  3.01  2.80   2.99       2.99  21070000
136  2021-09-01  3.01  3.01  2.89   2.97       2.97  13300000
137  2021-09-02  3.03  3.08  2.91   3.06       3.06  14080000
138  2021-09-03  3.04  3.05  2.88   2.88       2.88  16330000

[139 rows x 7 columns]
tolistdate: 0      2021-02-17
1      2021-02-18
2      2021-02-19
3      2021-02-22
4      2021-02-23
          ...
134    2021-08-30
135    2021-08-31
136    2021-09-01
137    2021-09-02
138    2021-09-03
Name: Date, Length: 139, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AUUD_ended_2021-09-25  2021-02-17          2.88   2.21    9.3       0.709

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.919     3.628     4.337     5.046     5.755     6.464     7.173

  markup_80 markup_90 markup_100
0     7.882     8.591        9.3
                   stock  start_date current_price minall maxall each_markup  \
0  AUUD_ended_2021-09-25  2021-02-17          2.88   2.21    9.3       0.709

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.919     3.628     4.337     5.046     5.755     6.464     7.173

  markup_80 markup_90 markup_100
0     7.882     8.591        9.3
./ticker_data/ticker_data_2021-09-25 - Copy/AUVI_ended_2021-09-25.csv
           Date    Open    High    Low    Close  Adj Close   Volume
0    2020-08-31   5.750  12.990  5.150  11.6000    11.6000  7561600
1    2020-09-01  10.880  11.000  8.010   8.6000     8.6000  1756100
2    2020-09-02   7.721   8.400  7.010   7.2500     7.2500   560900
3    2020-09-03   7.350   7.670  6.310   6.3500     6.3500   386600
4    2020-09-04   6.380   6.670  5.137   5.7000     5.7000   404900
..          ...     ...     ...    ...      ...        ...      ...
265  2021-09-20   6.780   6.796  6.480   6.7800     6.7800    10300
266  2021-09-21   6.770   6.780  6.600   6.7400     6.7400    17500
267  2021-09-22   6.820   6.860  6.520   6.7400     6.7400    11100
268  2021-09-23   6.820   6.860  6.580   6.7400     6.7400    11900
269  2021-09-24   6.700   6.700  6.350   6.4776     6.4776    20633

[270 rows x 7 columns]
tolistdate: 0      2020-08-31
1      2020-09-01
2      2020-09-02
3      2020-09-03
4      2020-09-04
          ...
265    2021-09-20
266    2021-09-21
267    2021-09-22
268    2021-09-23
269    2021-09-24
Name: Date, Length: 270, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AUVI_ended_2021-09-25  2020-08-31        6.4776   4.52  35.78       3.126

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.646    10.772    13.898    17.024     20.15    23.276    26.402

  markup_80 markup_90 markup_100
0    29.528    32.654      35.78

                   stock  start_date current_price minall maxall each_markup  \
0  AUVI_ended_2021-09-25  2020-08-31        6.4776   4.52  35.78       3.126

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.646    10.772    13.898    17.024     20.15    23.276    26.402

  markup_80 markup_90 markup_100
0    29.528    32.654      35.78
./ticker_data/ticker_data_2021-09-25 - Copy/AVAH_ended_2021-09-25.csv
          Date    Open    High     Low  Close  Adj Close    Volume
0   2021-04-28  12.000  12.000  12.000  12.00      12.00       100
1   2021-04-29  12.000  12.180  11.120  11.53      11.53  12116200
2   2021-04-30  11.580  11.790  11.320  11.68      11.68   2062400
3   2021-05-03  11.780  12.000  11.580  11.80      11.80   1255400
4   2021-05-04  11.800  12.000  11.455  11.75      11.75   1379700
..         ...     ...     ...     ...    ...        ...       ...
85  2021-08-30   9.908   9.908   9.290   9.41       9.41  19870000
86  2021-08-31   9.390   9.500   9.380   9.44       9.44  19080000
87  2021-09-01   9.430   9.630   9.260   9.47       9.47  19080000
88  2021-09-02   9.470   9.550   9.370   9.44       9.44  40180000
89  2021-09-03   9.420   9.505   9.100   9.38       9.38  38250000

[90 rows x 7 columns]
tolistdate: 0     2021-04-28
1     2021-04-29
2     2021-04-30
3     2021-05-03
4     2021-05-04
         ...
85    2021-08-30
86    2021-08-31
87    2021-09-01
88    2021-09-02
89    2021-09-03
Name: Date, Length: 90, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AVAH_ended_2021-09-25  2021-04-28          9.38   8.49     13       0.451

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.941     9.392     9.843    10.294    10.745    11.196    11.647

  markup_80 markup_90 markup_100
0    12.098    12.549         13
                   stock  start_date current_price minall maxall each_markup  \
0  AVAH_ended_2021-09-25  2021-04-28          9.38   8.49     13       0.451

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.941     9.392     9.843    10.294    10.745    11.196    11.647

  markup_80 markup_90 markup_100
0    12.098    12.549         13
./ticker_data/ticker_data_2021-09-25 - Copy/AVAV_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2007-01-23   25.000000   26.219999   22.600000   23.930000   23.930000
1     2007-01-24   24.250000   24.379999   23.700001   23.900000   23.900000
2     2007-01-25   23.990000   24.090000   23.070000   23.600000   23.600000
3     2007-01-26   23.820000   23.900000   23.160000   23.160000   23.160000
4     2007-01-29   23.200001   23.830000   22.770000   22.879999   22.879999
...          ...         ...         ...         ...         ...         ...
3676  2021-08-30  104.540001  104.540001  102.160004  102.760002  102.760002
3677  2021-08-31  103.110001  103.599998  102.110001  102.360001  102.360001
3678  2021-09-01  103.150002  105.580002  101.529999  103.639999  103.639999
3679  2021-09-02  103.730003  104.290001  102.489998  103.529999  103.529999
3680  2021-09-03  104.010002  104.290001  103.059998  103.860001  103.860001

        Volume
0      6804600
1       770200
2       348700
3       244900
4       339200
...        ...
3676   8690000
3677   7940000
3678  11160000
3679  11950000
3680   8340000

[3681 rows x 7 columns]
tolistdate: 0       2007-01-23
1       2007-01-24
2       2007-01-25
3       2007-01-26
4       2007-01-29
           ...
3676    2021-08-30
3677    2021-08-31
3678    2021-09-01
3679    2021-09-02
3680    2021-09-03
Name: Date, Length: 3681, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AVAV_ended_2021-09-25  2007-01-23        103.86  16.98  143.72      12.674

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    29.654    42.328    55.002    67.676     80.35    93.024   105.698

  markup_80 markup_90 markup_100
0   118.372   131.046     143.72
                   stock  start_date current_price minall  maxall each_markup  \
0  AVAV_ended_2021-09-25  2007-01-23        103.86  16.98  143.72      12.674

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    29.654    42.328    55.002    67.676     80.35    93.024   105.698

  markup_80 markup_90 markup_100
0   118.372   131.046     143.72
./ticker_data/ticker_data_2021-09-25 - Copy/AVCO_ended_2021-09-25.csv
           Date  Open  High   Low  Close  Adj Close    Volume
0    2018-03-27  2.04  2.48  2.04   2.25       2.25      9100
1    2018-03-28  2.30  2.36  2.30   2.36       2.36      1400
2    2018-03-29  2.40  2.50  2.40   2.41       2.41      2700
3    2018-04-02  2.41  2.46  2.41   2.46       2.46       200
4    2018-04-03  2.50  2.73  2.50   2.73       2.73      1400
..          ...   ...   ...   ...    ...        ...       ...
836  2021-08-30  1.10  1.11  1.05   1.05       1.05  13850000
837  2021-08-31  1.01  1.06  1.01   1.05       1.05  18340000
838  2021-09-01  1.04  1.07  1.01   1.03       1.03  16320000
839  2021-09-02  1.03  1.05  1.02   1.02       1.02  13230000
840  2021-09-03  1.02  1.03  1.01   1.01       1.01  11960000

[841 rows x 7 columns]
tolistdate: 0      2018-03-27
1      2018-03-28
2      2018-03-29
3      2018-04-02
4      2018-04-03
          ...
836    2021-08-30
837    2021-08-31
838    2021-09-01
839    2021-09-02
840    2021-09-03
Name: Date, Length: 841, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AVCO_ended_2021-09-25  2018-03-27          1.01    0.5   13.5         1.3

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0       1.8       3.1       4.4       5.7         7       8.3       9.6

  markup_80 markup_90 markup_100
0      10.9      12.2       13.5
                   stock  start_date current_price minall maxall each_markup  \
0  AVCO_ended_2021-09-25  2018-03-27          1.01    0.5   13.5         1.3

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0       1.8       3.1       4.4       5.7         7       8.3       9.6

  markup_80 markup_90 markup_100
0      10.9      12.2       13.5
./ticker_data/ticker_data_2021-09-25 - Copy/AVCTW_ended_2021-09-25.csv
         Date  Open    High    Low  Close  Adj Close  Volume
0  2021-09-22  0.29  0.2569  0.225  0.225      0.225   15087
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall  maxall  \
0  AVCTW_ended_2021-09-25  2021-09-22         0.225  0.225  0.2569

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00319   0.22819   0.23138   0.23457   0.23776   0.24095   0.24414

  markup_70 markup_80 markup_90 markup_100
0   0.24733   0.25052   0.25371     0.2569
                    stock  start_date current_price minall  maxall  \
0  AVCTW_ended_2021-09-25  2021-09-22         0.225  0.225  0.2569

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00319   0.22819   0.23138   0.23457   0.23776   0.24095   0.24414

  markup_70 markup_80 markup_90 markup_100
0   0.24733   0.25052   0.25371     0.2569
./ticker_data/ticker_data_2021-09-25 - Copy/AVCT_ended_2021-09-25.csv
           Date   Open  High   Low  Close  Adj Close   Volume
0    2017-08-08  9.700  9.70  9.67  9.690      9.690  3269100
1    2017-08-09  9.720  9.72  9.67  9.690      9.690   201500
2    2017-08-10  9.700  9.70  9.68  9.680      9.680   288100
3    2017-08-11  9.670  9.70  9.65  9.700      9.700   332300
4    2017-08-14  9.670  9.67  9.67  9.670      9.670   819500
..          ...    ...   ...   ...    ...        ...      ...
868  2021-09-20  3.150  3.25  2.78  2.830      2.830   315000
869  2021-09-21  2.980  3.07  2.63  2.810      2.810   453900
870  2021-09-22  2.710  2.76  2.56  2.660      2.660   168200
871  2021-09-23  2.677  2.87  2.61  2.830      2.830   107200
872  2021-09-24  2.870  2.95  2.76  2.877      2.877    89450

[873 rows x 7 columns]
tolistdate: 0      2017-08-08
1      2017-08-09
2      2017-08-10
3      2017-08-11
4      2017-08-14
          ...
868    2021-09-20
869    2021-09-21
870    2021-09-22
871    2021-09-23
872    2021-09-24
Name: Date, Length: 873, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AVCT_ended_2021-09-25  2017-08-08         2.877   1.45  12.96       1.151

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.601     3.752     4.903     6.054     7.205     8.356     9.507

  markup_80 markup_90 markup_100
0    10.658    11.809      12.96
                   stock  start_date current_price minall maxall each_markup  \
0  AVCT_ended_2021-09-25  2017-08-08         2.877   1.45  12.96       1.151

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.601     3.752     4.903     6.054     7.205     8.356     9.507

  markup_80 markup_90 markup_100
0    10.658    11.809      12.96
./ticker_data/ticker_data_2021-09-25 - Copy/AVDL_ended_2021-09-25.csv
            Date     Open     High     Low   Close  Adj Close    Volume
0     1999-12-31  1.87500  2.12500  1.8125  2.1250     2.1250     39200
1     2000-01-03  2.12500  2.25000  1.8750  2.1875     2.1875     68800
2     2000-01-04  2.25000  2.50000  2.2500  2.2500     2.2500     73400
3     2000-01-05  2.09375  2.25000  2.0000  2.0000     2.0000     42700
4     2000-01-06  2.09375  2.21875  2.0000  2.0000     2.0000     22700
...          ...      ...      ...     ...     ...        ...       ...
5449  2021-08-30  8.26000  8.39000  8.0200  8.2500     8.2500  14600000
5450  2021-08-31  8.24000  8.35000  8.1800  8.2900     8.2900   5430000
5451  2021-09-01  8.31000  8.44000  8.1400  8.3000     8.3000  20930000
5452  2021-09-02  8.31000  8.39000  8.1700  8.3000     8.3000  17940000
5453  2021-09-03  8.30000  8.37000  8.0900  8.1200     8.1200  20250000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AVDL_ended_2021-09-25  1999-12-31          8.12   0.71   43.6       4.289

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.999     9.288    13.577    17.866    22.155    26.444    30.733

  markup_80 markup_90 markup_100
0    35.022    39.311       43.6
                   stock  start_date current_price minall maxall each_markup  \
0  AVDL_ended_2021-09-25  1999-12-31          8.12   0.71   43.6       4.289

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.999     9.288    13.577    17.866    22.155    26.444    30.733

  markup_80 markup_90 markup_100
0    35.022    39.311       43.6
./ticker_data/ticker_data_2021-09-25 - Copy/AVEO_ended_2021-09-25.csv
            Date   Open   High        Low      Close  Adj Close    Volume
0     2010-03-12  82.50  90.00  81.599998  89.900002  89.900002    299500
1     2010-03-15  86.50  90.00  86.500000  90.000000  90.000000     51900
2     2010-03-16  90.00  90.00  87.500000  88.599998  88.599998      8700
3     2010-03-17  88.50  88.50  86.900002  88.300003  88.300003      9400
4     2010-03-18  89.00  89.00  87.500000  88.400002  88.400002      6500
...          ...    ...    ...        ...        ...        ...       ...
2886  2021-08-30   6.59   6.60   6.250000   6.270000   6.270000  22880000
2887  2021-08-31   6.29   6.47   6.250000   6.410000   6.410000  27380000
2888  2021-09-01   6.35   6.66   6.290000   6.560000   6.560000  44450000
2889  2021-09-02   6.56   6.60   6.300000   6.350000   6.350000  29070000
2890  2021-09-03   6.35   6.39   6.140000   6.170000   6.170000  29010000

[2891 rows x 7 columns]
tolistdate: 0       2010-03-12
1       2010-03-15
2       2010-03-16
3       2010-03-17
4       2010-03-18
           ...
2886    2021-08-30
2887    2021-08-31
2888    2021-09-01
2889    2021-09-02
2890    2021-09-03
Name: Date, Length: 2891, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AVEO_ended_2021-09-25  2010-03-12          6.17   2.23  215.5      21.327

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    23.557    44.884    66.211    87.538   108.865   130.192   151.519

  markup_80 markup_90 markup_100
0   172.846   194.173      215.5
                   stock  start_date current_price minall maxall each_markup  \
0  AVEO_ended_2021-09-25  2010-03-12          6.17   2.23  215.5      21.327

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    23.557    44.884    66.211    87.538   108.865   130.192   151.519

  markup_80 markup_90 markup_100
0   172.846   194.173      215.5
./ticker_data/ticker_data_2021-09-25 - Copy/AVGOP_ended_2021-09-25.csv
           Date         Open         High          Low        Close  \
0    2019-09-25  1003.000000  1015.000000   997.500000  1014.000000
1    2019-09-26  1009.109985  1045.319946  1006.737976  1043.699951
2    2019-09-27  1020.383972  1040.000000  1016.940979  1022.000000
3    2019-09-30  1023.107971  1045.709961  1017.088013  1025.385986
4    2019-10-01  1030.000000  1061.010010  1022.500000  1030.000000
..          ...          ...          ...          ...          ...
484  2021-08-30  1599.410034  1599.410034  1599.410034  1599.410034
485  2021-08-31  1566.050049  1580.920044  1564.069946  1578.250000
486  2021-09-01  1570.390015  1570.390015  1570.390015  1570.390015
487  2021-09-02  1559.369995  1562.520020  1559.369995  1559.979980
488  2021-09-03  1597.530029  1597.530029  1580.420044  1580.420044

       Adj Close   Volume
0     904.230347   771600
1     930.715210   296400
2     911.364319   423800
3     914.383789   126000
4     918.498291    43800
..           ...      ...
484  1599.410034   750000
485  1578.250000  1380000
486  1570.390015   140000
487  1559.979980   780000
488  1580.420044  2740000

[489 rows x 7 columns]
tolistdate: 0      2019-09-25
1      2019-09-26
2      2019-09-27
3      2019-09-30
4      2019-10-01
          ...
484    2021-08-30
485    2021-08-31
486    2021-09-01
487    2021-09-02
488    2021-09-03
Name: Date, Length: 489, dtype: object
                    stock  start_date current_price minall   maxall  \
0  AVGOP_ended_2021-09-25  2019-09-25       1580.42    635  1599.41

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      96.441   731.441   827.882   924.323   1020.76   1117.21   1213.65

  markup_70 markup_80 markup_90 markup_100
0   1310.09   1406.53   1502.97    1599.41
                    stock  start_date current_price minall   maxall  \
0  AVGOP_ended_2021-09-25  2019-09-25       1580.42    635  1599.41

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      96.441   731.441   827.882   924.323   1020.76   1117.21   1213.65

  markup_70 markup_80 markup_90 markup_100
0   1310.09   1406.53   1502.97    1599.41
./ticker_data/ticker_data_2021-09-25 - Copy/AVGO_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2009-08-06   16.500000   16.910000   15.560000   16.180000   12.473777
1     2009-08-07   16.150000   16.760000   16.030001   16.430000   12.666513
2     2009-08-10   16.629999   16.629999   15.610000   15.970000   12.311883
3     2009-08-11   15.980000   16.000000   15.500000   15.670000   12.080601
4     2009-08-12   16.150000   16.200001   15.660000   16.000000   12.335008
...          ...         ...         ...         ...         ...         ...
3036  2021-08-30  500.000000  507.850006  498.250000  498.890015  498.890015
3037  2021-08-31  501.290009  501.290009  492.700012  497.209991  497.209991
3038  2021-09-01  496.269989  499.239990  492.890015  493.160004  493.160004
3039  2021-09-02  495.790009  495.980011  490.160004  491.899994  491.899994
3040  2021-09-03  495.910004  506.000000  495.040009  497.679993  497.679993

         Volume
0      24197800
1       2454300
2       2421000
3       2305400
4       1451300
...         ...
3036  196140000
3037  173780000
3038  125860000
3039  171220000
3040  251910000

[3041 rows x 7 columns]
tolistdate: 0       2009-08-06
1       2009-08-07
2       2009-08-10
3       2009-08-11
4       2009-08-12
           ...
3036    2021-08-30
3037    2021-08-31
3038    2021-09-01
3039    2021-09-02
3040    2021-09-03
Name: Date, Length: 3041, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AVGO_ended_2021-09-25  2009-08-06        497.68  14.33  507.85      49.352

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    63.682   113.034   162.386   211.738    261.09   310.442   359.794

  markup_80 markup_90 markup_100
0   409.146   458.498     507.85
                   stock  start_date current_price minall  maxall each_markup  \
0  AVGO_ended_2021-09-25  2009-08-06        497.68  14.33  507.85      49.352

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    63.682   113.034   162.386   211.738    261.09   310.442   359.794

  markup_80 markup_90 markup_100
0   409.146   458.498     507.85
./ticker_data/ticker_data_2021-09-25 - Copy/AVGR_ended_2021-09-25.csv
            Date      Open      High       Low     Close  Adj Close   Volume
0     2015-01-30  5260.000  5500.000  5200.000  5400.000   5400.000     6747
1     2015-02-02  5400.000  5768.000  5244.000  5328.000   5328.000      225
2     2015-02-03  5352.000  5420.000  5200.000  5220.000   5220.000      366
3     2015-02-04  5224.000  5268.000  5200.000  5200.000   5200.000      730
4     2015-02-05  5200.000  5276.000  5168.000  5256.000   5256.000     1069
...          ...       ...       ...       ...       ...        ...      ...
1671  2021-09-20     0.822     0.830     0.771     0.800      0.800  1452600
1672  2021-09-21     0.807     0.821     0.800     0.801      0.801   576900
1673  2021-09-22     0.800     0.820     0.798     0.812      0.812   463100
1674  2021-09-23     0.820     0.840     0.812     0.835      0.835   533500
1675  2021-09-24     0.830     0.838     0.813     0.838      0.838   401257

[1676 rows x 7 columns]
tolistdate: 0       2015-01-30
1       2015-02-02
2       2015-02-03
3       2015-02-04
4       2015-02-05
           ...
1671    2021-09-20
1672    2021-09-21
1673    2021-09-22
1674    2021-09-23
1675    2021-09-24
Name: Date, Length: 1676, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AVGR_ended_2021-09-25  2015-01-30         0.838  0.214  10044     1004.38

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   1004.59   2008.97   3013.35   4017.73   5022.11   6026.49   7030.86

  markup_80 markup_90 markup_100
0   8035.24   9039.62      10044
                   stock  start_date current_price minall maxall each_markup  \
0  AVGR_ended_2021-09-25  2015-01-30         0.838  0.214  10044     1004.38

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   1004.59   2008.97   3013.35   4017.73   5022.11   6026.49   7030.86

  markup_80 markup_90 markup_100
0   8035.24   9039.62      10044
./ticker_data/ticker_data_2021-09-25 - Copy/AVID_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  12.562500  13.625000  12.375000  13.062500  13.062500
1     2000-01-03  13.750000  13.875000  12.500000  13.125000  13.125000
2     2000-01-04  12.812500  13.125000  12.250000  12.281250  12.281250
3     2000-01-05  12.250000  12.250000  11.500000  12.125000  12.125000
4     2000-01-06  12.625000  12.750000  11.375000  11.875000  11.875000
...          ...        ...        ...        ...        ...        ...
5464  2021-09-20  26.209999  27.590000  26.080000  27.000000  27.000000
5465  2021-09-21  27.070000  27.370001  26.030001  27.240000  27.240000
5466  2021-09-22  27.930000  28.680000  27.469999  28.590000  28.590000
5467  2021-09-23  28.639999  29.330000  28.549999  29.150000  29.150000
5468  2021-09-24  29.000000  29.240000  28.190001  29.219999  29.219999

      Volume
0     120800
1     144700
2      99500
3     101300
4     118200
...      ...
5464  727100
5465  427600
5466  593500
5467  385500
5468  288794

[5469 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5464    2021-09-20
5465    2021-09-21
5466    2021-09-22
5467    2021-09-23
5468    2021-09-24
Name: Date, Length: 5469, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AVID_ended_2021-09-25  1999-12-31         29.22   3.99  68.35       6.436

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.426    16.862    23.298    29.734     36.17    42.606    49.042

  markup_80 markup_90 markup_100
0    55.478    61.914      68.35
                   stock  start_date current_price minall maxall each_markup  \
0  AVID_ended_2021-09-25  1999-12-31         29.22   3.99  68.35       6.436

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.426    16.862    23.298    29.734     36.17    42.606    49.042

  markup_80 markup_90 markup_100
0    55.478    61.914      68.35
./ticker_data/ticker_data_2021-09-25 - Copy/AVIR_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-10-30  27.030001  32.419998  27.020000  30.340000  30.340000
1    2020-11-02  29.940001  31.450001  28.000000  29.740000  29.740000
2    2020-11-03  30.590000  31.209999  28.020000  28.150000  28.150000
3    2020-11-04  28.000000  31.799999  27.500000  31.030001  31.030001
4    2020-11-05  31.059999  34.450001  31.059999  34.000000  34.000000
..          ...        ...        ...        ...        ...        ...
207  2021-08-30  31.350000  31.660000  30.049999  30.500000  30.500000
208  2021-08-31  30.309999  30.750000  29.469999  29.719999  29.719999
209  2021-09-01  30.250000  30.280001  27.799999  28.629999  28.629999
210  2021-09-02  28.629999  29.270000  28.000000  29.000000  29.000000
211  2021-09-03  28.889999  29.250000  28.379999  28.910000  28.910000

        Volume
0      3575800
1       835400
2       698800
3       861300
4      1473000
..         ...
207  123100000
208  139240000
209  142830000
210   82600000
211  107930000

[212 rows x 7 columns]
tolistdate: 0      2020-10-30
1      2020-11-02
2      2020-11-03
3      2020-11-04
4      2020-11-05
          ...
207    2021-08-30
208    2021-08-31
209    2021-09-01
210    2021-09-02
211    2021-09-03
Name: Date, Length: 212, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AVIR_ended_2021-09-25  2020-10-30         28.91  18.72  94.174      7.5454

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   26.2654   33.8108   41.3562   48.9016    56.447   63.9924   71.5378

  markup_80 markup_90 markup_100
0   79.0832   86.6286     94.174
                   stock  start_date current_price minall  maxall each_markup  \
0  AVIR_ended_2021-09-25  2020-10-30         28.91  18.72  94.174      7.5454

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   26.2654   33.8108   41.3562   48.9016    56.447   63.9924   71.5378

  markup_80 markup_90 markup_100
0   79.0832   86.6286     94.174
./ticker_data/ticker_data_2021-09-25 - Copy/AVNW_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31  142.500000  144.000000  138.000000  140.625000  140.625000
1     2000-01-03  153.000000  154.875000  129.750000  138.750000  138.750000
2     2000-01-04  135.375000  136.500000  120.000000  126.562500  126.562500
3     2000-01-05  126.375000  136.500000  123.750000  135.750000  135.750000
4     2000-01-06  135.000000  142.875000  133.500000  142.125000  142.125000
...          ...         ...         ...         ...         ...         ...
5449  2021-08-30   35.660000   35.900002   34.619999   35.560001   35.560001
5450  2021-08-31   35.619999   35.939999   34.759998   35.439999   35.439999
5451  2021-09-01   35.220001   36.930000   34.900002   35.970001   35.970001
5452  2021-09-02   36.139999   36.849998   35.639999   36.400002   36.400002
5453  2021-09-03   36.299999   36.320000   35.419998   36.189999   36.189999

        Volume
0        32200
1       280800
2       190200
3       166000
4       270800
...        ...
5449  16740000
5450  16250000
5451  13030000
5452  12940000
5453   9020000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AVNW_ended_2021-09-25  1999-12-31         36.19  2.855    291     28.8145

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   31.6695    60.484   89.2985   118.113   146.928   175.742   204.557

  markup_80 markup_90 markup_100
0   233.371   262.186        291
                   stock  start_date current_price minall maxall each_markup  \
0  AVNW_ended_2021-09-25  1999-12-31         36.19  2.855    291     28.8145

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   31.6695    60.484   89.2985   118.113   146.928   175.742   204.557

  markup_80 markup_90 markup_100
0   233.371   262.186        291
./ticker_data/ticker_data_2021-09-25 - Copy/AVO_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-10-02  13.640000  13.900000  12.300000  12.450000  12.450000
1    2020-10-05  12.960000  13.150000  12.050000  12.360000  12.360000
2    2020-10-06  12.190000  12.450000  11.750000  12.100000  12.100000
3    2020-10-07  12.040000  12.190000  11.800000  11.860000  11.860000
4    2020-10-08  11.860000  12.450000  11.810000  12.230000  12.230000
..          ...        ...        ...        ...        ...        ...
227  2021-08-30  21.030001  21.290001  20.400000  20.500000  20.500000
228  2021-08-31  20.490000  20.870001  20.200001  20.740000  20.740000
229  2021-09-01  20.840000  20.870001  20.520000  20.799999  20.799999
230  2021-09-02  20.879999  21.500000  20.200001  20.250000  20.250000
231  2021-09-03  20.250000  20.370001  20.080000  20.180000  20.180000

       Volume
0     1106100
1      396300
2      424800
3      470900
4      205900
..        ...
227  12720000
228  25160000
229   8090000
230  20730000
231   8880000

[232 rows x 7 columns]
tolistdate: 0      2020-10-02
1      2020-10-05
2      2020-10-06
3      2020-10-07
4      2020-10-08
          ...
227    2021-08-30
228    2021-08-31
229    2021-09-01
230    2021-09-02
231    2021-09-03
Name: Date, Length: 232, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  AVO_ended_2021-09-25  2020-10-02         20.18  11.75  22.93       1.118

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.868    13.986    15.104    16.222     17.34    18.458    19.576

  markup_80 markup_90 markup_100
0    20.694    21.812      22.93
                  stock  start_date current_price minall maxall each_markup  \
0  AVO_ended_2021-09-25  2020-10-02         20.18  11.75  22.93       1.118

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.868    13.986    15.104    16.222     17.34    18.458    19.576

  markup_80 markup_90 markup_100
0    20.694    21.812      22.93
./ticker_data/ticker_data_2021-09-25 - Copy/AVRO_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-06-21  29.500000  35.000000  28.020000  31.200001  31.200001
1    2018-06-22  31.250000  32.490002  27.049999  30.740000  30.740000
2    2018-06-25  29.639999  32.000000  29.500000  30.480000  30.480000
3    2018-06-26  30.559999  31.799999  29.600000  30.830000  30.830000
4    2018-06-27  30.440001  31.000000  30.020000  30.540001  30.540001
..          ...        ...        ...        ...        ...        ...
817  2021-09-20   6.050000   6.410000   5.980000   6.220000   6.220000
818  2021-09-21   6.230000   6.440000   6.110000   6.210000   6.210000
819  2021-09-22   6.280000   6.310000   6.090000   6.110000   6.110000
820  2021-09-23   6.100000   6.310000   5.990000   6.250000   6.250000
821  2021-09-24   6.180000   6.225000   6.050000   6.110000   6.110000

      Volume
0    2783600
1     475400
2     229900
3     277300
4     171600
..       ...
817   358800
818   208500
819   173700
820   248000
821    74713

[822 rows x 7 columns]
tolistdate: 0      2018-06-21
1      2018-06-22
2      2018-06-25
3      2018-06-26
4      2018-06-27
          ...
817    2021-09-20
818    2021-09-21
819    2021-09-22
820    2021-09-23
821    2021-09-24
Name: Date, Length: 822, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AVRO_ended_2021-09-25  2018-06-21          6.11   5.44   53.7       4.826

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.266    15.092    19.918    24.744     29.57    34.396    39.222

  markup_80 markup_90 markup_100
0    44.048    48.874       53.7
                   stock  start_date current_price minall maxall each_markup  \
0  AVRO_ended_2021-09-25  2018-06-21          6.11   5.44   53.7       4.826

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.266    15.092    19.918    24.744     29.57    34.396    39.222

  markup_80 markup_90 markup_100
0    44.048    48.874       53.7
./ticker_data/ticker_data_2021-09-25 - Copy/AVT_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  29.125000  30.250000  28.937500  30.250000  25.436039
1     2000-01-03  30.062500  30.093750  29.531250  29.625000  24.910500
2     2000-01-04  29.375000  29.375000  27.750000  28.250000  23.754316
3     2000-01-05  28.312500  28.312500  26.125000  26.968750  22.676964
4     2000-01-06  26.968750  27.156250  26.531250  26.656250  22.414200
...          ...        ...        ...        ...        ...        ...
5451  2021-08-30  41.169998  41.360001  40.840000  40.910000  40.910000
5452  2021-08-31  41.009998  41.189999  40.380001  40.459999  40.459999
5453  2021-09-01  40.580002  40.580002  39.740002  39.810001  39.810001
5454  2021-09-02  39.849998  40.049999  39.500000  39.639999  39.639999
5455  2021-09-03  39.349998  39.520000  39.020000  39.220001  39.220001

          Volume
0       213000.0
1       378000.0
2       491000.0
3      1694400.0
4       457600.0
...          ...
5451  30500000.0
5452  56230000.0
5453  33360000.0
5454  38200000.0
5455  51700000.0

[5456 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5451    2021-08-30
5452    2021-08-31
5453    2021-09-01
5454    2021-09-02
5455    2021-09-03
Name: Date, Length: 5456, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  AVT_ended_2021-09-25  1999-12-31         39.22   5.55   51.5       4.595

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.145     14.74    19.335     23.93    28.525     33.12    37.715

  markup_80 markup_90 markup_100
0     42.31    46.905       51.5
                  stock  start_date current_price minall maxall each_markup  \
0  AVT_ended_2021-09-25  1999-12-31         39.22   5.55   51.5       4.595

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.145     14.74    19.335     23.93    28.525     33.12    37.715

  markup_80 markup_90 markup_100
0     42.31    46.905       51.5
./ticker_data/ticker_data_2021-09-25 - Copy/AVXL_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2006-08-02   8.000000   8.000000   8.000000   8.000000   8.000000
1     2006-08-03   8.000000   8.400000   8.000000   8.240000   8.240000
2     2006-08-04   8.240000   8.280000   8.200000   8.240000   8.240000
3     2006-08-07   8.360000   8.360000   8.280000   8.280000   8.280000
4     2006-08-08   8.360000   8.360000   8.360000   8.360000   8.360000
...          ...        ...        ...        ...        ...        ...
3629  2021-08-30  18.830000  19.190001  18.309999  18.540001  18.540001
3630  2021-08-31  18.650000  20.190001  18.562000  19.490000  19.490000
3631  2021-09-01  19.309999  20.340000  18.959999  20.219999  20.219999
3632  2021-09-02  20.250000  20.650000  19.660000  19.969999  19.969999
3633  2021-09-03  19.870001  20.070000  19.110001  19.480000  19.480000

         Volume
0           500
1          2700
2          1500
3          1000
4           700
...         ...
3629   72830000
3630  183650000
3631  101180000
3632   68420000
3633   74980000

[3634 rows x 7 columns]
tolistdate: 0       2006-08-02
1       2006-08-03
2       2006-08-04
3       2006-08-07
4       2006-08-08
           ...
3629    2021-08-30
3630    2021-08-31
3631    2021-09-01
3632    2021-09-02
3633    2021-09-03
Name: Date, Length: 3634, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AVXL_ended_2021-09-25  2006-08-02         19.48    0.6   31.5        3.09

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      3.69      6.78      9.87     12.96     16.05     19.14     22.23

  markup_80 markup_90 markup_100
0     25.32     28.41       31.5
                   stock  start_date current_price minall maxall each_markup  \
0  AVXL_ended_2021-09-25  2006-08-02         19.48    0.6   31.5        3.09

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      3.69      6.78      9.87     12.96     16.05     19.14     22.23

  markup_80 markup_90 markup_100
0     25.32     28.41       31.5
./ticker_data/ticker_data_2021-09-25 - Copy/AWH_ended_2021-09-25.csv
            Date      Open     High     Low    Close  Adj Close  Volume
0     2000-10-02  305.3125  394.375  302.50  356.875    356.875   81110
1     2000-10-03  370.0000  370.000  316.25  318.750    318.750   26390
2     2000-10-04  322.5000  328.750  308.75  325.000    325.000   30000
3     2000-10-05  318.7500  330.000  310.00  317.500    317.500   26480
4     2000-10-06  318.7500  323.750  286.25  286.875    286.875   26660
...          ...       ...      ...     ...      ...        ...     ...
5257  2021-09-20    3.5500    3.650    3.45    3.480      3.480  355200
5258  2021-09-21    3.4800    3.520    3.44    3.490      3.490  247500
5259  2021-09-22    3.4900    3.600    3.45    3.550      3.550  410900
5260  2021-09-23    3.5700    3.830    3.53    3.680      3.680  666900
5261  2021-09-24    3.6300    3.630    3.37    3.370      3.370  235425

[5262 rows x 7 columns]
tolistdate: 0       2000-10-02
1       2000-10-03
2       2000-10-04
3       2000-10-05
4       2000-10-06
           ...
5257    2021-09-20
5258    2021-09-21
5259    2021-09-22
5260    2021-09-23
5261    2021-09-24
Name: Date, Length: 5262, dtype: object
                  stock  start_date current_price minall   maxall each_markup  \
0  AWH_ended_2021-09-25  2000-10-02          3.37   0.01  394.375     39.4365

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   39.4465    78.883   118.319   157.756   197.192   236.629   276.065

  markup_80 markup_90 markup_100

0   315.502   354.938    394.375
                  stock  start_date current_price minall   maxall each_markup  \
0  AWH_ended_2021-09-25  2000-10-02          3.37   0.01  394.375     39.4365

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   39.4465    78.883   118.319   157.756   197.192   236.629   276.065

  markup_80 markup_90 markup_100
0   315.502   354.938    394.375
./ticker_data/ticker_data_2021-09-25 - Copy/AWRE_ended_2021-09-25.csv
            Date     Open     High      Low    Close  Adj Close   Volume
0     1999-12-31  36.0000  37.0000  35.4375  36.3750  16.435513   225100
1     2000-01-03  37.8750  38.5625  35.6250  35.7500  16.153116   464300
2     2000-01-04  34.5000  35.5000  33.2500  33.2500  15.023529   331400
3     2000-01-05  33.5625  37.6250  33.0000  37.0625  16.746149   308000
4     2000-01-06  37.3750  38.0000  34.6875  35.7500  16.153116   313000
...          ...      ...      ...      ...      ...        ...      ...
5447  2021-08-30   4.0000   4.1400   4.0000   4.0500   4.050000  1440000
5448  2021-08-31   4.0200   4.0900   4.0000   4.0900   4.090000  1480000
5449  2021-09-01   4.1200   4.1500   4.0800   4.1200   4.120000  1340000
5450  2021-09-02   4.1100   4.1200   4.0600   4.0800   4.080000  1690000
5451  2021-09-03   4.0600   4.1300   3.9900   4.0700   4.070000   880000

[5452 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5447    2021-08-30
5448    2021-08-31
5449    2021-09-01
5450    2021-09-02
5451    2021-09-03
Name: Date, Length: 5452, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AWRE_ended_2021-09-25  1999-12-31          4.07   1.58     67       6.542

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.122    14.664    21.206    27.748     34.29    40.832    47.374

  markup_80 markup_90 markup_100
0    53.916    60.458         67
                   stock  start_date current_price minall maxall each_markup  \
0  AWRE_ended_2021-09-25  1999-12-31          4.07   1.58     67       6.542

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.122    14.664    21.206    27.748     34.29    40.832    47.374

  markup_80 markup_90 markup_100
0    53.916    60.458         67
./ticker_data/ticker_data_2021-09-25 - Copy/AXAS_ended_2021-09-25.csv
            Date   Open   High    Low  Close  Adj Close   Volume
0     1999-12-31  17.50  22.50  17.50  18.75      18.75     7600
1     2000-01-03  21.25  22.50  21.25  21.25      21.25      500
2     2000-01-04  22.50  22.50  22.50  22.50      22.50      800
3     2000-01-05  25.00  32.50  25.00  30.00      30.00     4700
4     2000-01-06  27.50  30.00  27.50  30.00      30.00      500
...          ...    ...    ...    ...    ...        ...      ...
5445  2021-08-30   2.05   2.10   2.05   2.05       2.05  2370000
5446  2021-08-31   2.06   2.08   2.00   2.04       2.04  3010000
5447  2021-09-01   2.00   2.04   1.93   2.02       2.02  1720000
5448  2021-09-02   1.95   2.02   1.90   1.99       1.99  4090000
5449  2021-09-03   1.95   2.02   1.88   2.02       2.02  5710000

[5450 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5445    2021-08-30
5446    2021-08-31
5447    2021-09-01
5448    2021-09-02
5449    2021-09-03
Name: Date, Length: 5450, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AXAS_ended_2021-09-25  1999-12-31          2.02   1.23    185      18.377

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    19.607    37.984    56.361    74.738    93.115   111.492   129.869

  markup_80 markup_90 markup_100
0   148.246   166.623        185
                   stock  start_date current_price minall maxall each_markup  \
0  AXAS_ended_2021-09-25  1999-12-31          2.02   1.23    185      18.377

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    19.607    37.984    56.361    74.738    93.115   111.492   129.869

  markup_80 markup_90 markup_100
0   148.246   166.623        185
./ticker_data/ticker_data_2021-09-25 - Copy/AXDX_ended_2021-09-25.csv
            Date      Open     High     Low     Close  Adj Close    Volume
0     1999-12-31  1.312500  1.31250  1.3125  1.312500   1.312500         0
1     2000-06-26  0.312500  1.12500  0.3125  1.000000   1.000000    201200
2     2000-06-27  1.000000  1.12500  0.6250  0.859375   0.859375    178500
3     2000-06-28  0.812500  0.84375  0.7500  0.750000   0.750000      8500
4     2000-06-29  0.765625  0.81250  0.6250  0.687500   0.687500     65000
...          ...       ...      ...     ...       ...        ...       ...
5221  2021-08-30  6.290000  6.53000  6.1000  6.210000   6.210000  12910000
5222  2021-08-31  6.190000  6.31000  6.0700  6.250000   6.250000  10470000
5223  2021-09-01  6.330000  6.36000  6.0700  6.240000   6.240000  13410000
5224  2021-09-02  6.300000  6.30000  6.0200  6.120000   6.120000  18300000
5225  2021-09-03  6.100000  6.12000  5.9700  6.070000   6.070000  13410000

[5226 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-06-26
2       2000-06-27
3       2000-06-28
4       2000-06-29
           ...
5221    2021-08-30
5222    2021-08-31
5223    2021-09-01
5224    2021-09-02
5225    2021-09-03
Name: Date, Length: 5226, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AXDX_ended_2021-09-25  1999-12-31          6.07   0.25  31.86       3.161

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.411     6.572     9.733    12.894    16.055    19.216    22.377

  markup_80 markup_90 markup_100
0    25.538    28.699      31.86
                   stock  start_date current_price minall maxall each_markup  \
0  AXDX_ended_2021-09-25  1999-12-31          6.07   0.25  31.86       3.161

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.411     6.572     9.733    12.894    16.055    19.216    22.377

  markup_80 markup_90 markup_100
0    25.538    28.699      31.86
./ticker_data/ticker_data_2021-09-25 - Copy/AXGN_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   1.500000   1.625000   1.375000   1.625000   1.331006
1     2000-01-03   1.500000   1.562500   1.375000   1.500000   1.228621
2     2000-01-04   1.531250   1.531250   1.531250   1.531250   1.254218
3     2000-01-05   1.562500   1.562500   1.562500   1.562500   1.279814
4     2000-01-06   1.500000   1.562500   1.500000   1.562500   1.279814
...          ...        ...        ...        ...        ...        ...
4754  2021-08-30  16.850000  16.980000  16.410000  16.480000  16.480000
4755  2021-08-31  16.510000  17.090000  16.170000  17.059999  17.059999
4756  2021-09-01  17.190001  17.850000  16.790001  17.360001  17.360001
4757  2021-09-02  17.400000  17.700001  17.309999  17.660000  17.660000
4758  2021-09-03  17.469999  17.690001  17.070000  17.370001  17.370001

        Volume
0        10800
1        15500
2          800
3         2000
4         1200
...        ...
4754   7440000
4755   9050000
4756   9040000
4757  11510000
4758   5390000

[4759 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
4754    2021-08-30
4755    2021-08-31
4756    2021-09-01
4757    2021-09-02
4758    2021-09-03
Name: Date, Length: 4759, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AXGN_ended_2021-09-25  1999-12-31         17.37    0.2  56.85       5.665

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.865     11.53    17.195     22.86    28.525     34.19    39.855

  markup_80 markup_90 markup_100
0     45.52    51.185      56.85
                   stock  start_date current_price minall maxall each_markup  \
0  AXGN_ended_2021-09-25  1999-12-31         17.37    0.2  56.85       5.665

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.865     11.53    17.195     22.86    28.525     34.19    39.855

  markup_80 markup_90 markup_100
0     45.52    51.185      56.85
./ticker_data/ticker_data_2021-09-25 - Copy/AXLA_ended_2021-09-25.csv
           Date   Open    High    Low  Close  Adj Close   Volume
0    2019-05-09  15.12  15.990  13.51  13.80      13.80  1636300
1    2019-05-10  13.77  14.000  12.75  13.92      13.92   214200
2    2019-05-13  13.84  14.100  12.60  13.95      13.95   158300
3    2019-05-14  13.98  14.198  13.11  14.09      14.09   164700
4    2019-05-15  14.08  14.300  13.34  13.75      13.75    84800
..          ...    ...     ...    ...    ...        ...      ...
581  2021-08-30   3.43   3.500   3.36   3.36       3.36  3640000
582  2021-08-31   3.47   3.650   3.41   3.65       3.65  6630000
583  2021-09-01   3.65   3.700   3.51   3.53       3.53  3570000
584  2021-09-02   3.61   3.690   3.55   3.67       3.67  3410000
585  2021-09-03   3.65   3.680   3.55   3.59       3.59  2860000

[586 rows x 7 columns]
tolistdate: 0      2019-05-09
1      2019-05-10
2      2019-05-13
3      2019-05-14
4      2019-05-15
          ...
581    2021-08-30
582    2021-08-31
583    2021-09-01
584    2021-09-02
585    2021-09-03
Name: Date, Length: 586, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AXLA_ended_2021-09-25  2019-05-09          3.59   2.25  15.99       1.374

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.624     4.998     6.372     7.746      9.12    10.494    11.868

  markup_80 markup_90 markup_100
0    13.242    14.616      15.99
                   stock  start_date current_price minall maxall each_markup  \
0  AXLA_ended_2021-09-25  2019-05-09          3.59   2.25  15.99       1.374

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.624     4.998     6.372     7.746      9.12    10.494    11.868

  markup_80 markup_90 markup_100
0    13.242    14.616      15.99
./ticker_data/ticker_data_2021-09-25 - Copy/AXNX_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-10-31  16.049999  17.000000  14.750000  14.980000  14.980000
1    2018-11-01  14.900000  14.900000  13.070000  14.500000  14.500000
2    2018-11-02  14.950000  15.880000  14.670000  15.070000  15.070000
3    2018-11-05  15.150000  15.750000  14.750000  14.750000  14.750000
4    2018-11-06  14.850000  15.350000  14.750000  14.900000  14.900000
..          ...        ...        ...        ...        ...        ...
725  2021-09-20  70.750000  71.800003  68.680000  68.870003  68.870003
726  2021-09-21  69.050003  70.769997  69.050003  69.250000  69.250000
727  2021-09-22  69.449997  70.599998  68.199997  69.779999  69.779999
728  2021-09-23  69.760002  70.070000  67.690002  69.699997  69.699997
729  2021-09-24  69.449997  70.709999  67.510002  70.639999  70.639999

      Volume
0    3031000
1     445700
2     641100
3     266000
4     272300
..       ...
725   896400
726   869700
727   444500
728   508700
729   106869

[730 rows x 7 columns]
tolistdate: 0      2018-10-31
1      2018-11-01
2      2018-11-02
3      2018-11-05
4      2018-11-06
          ...
725    2021-09-20
726    2021-09-21
727    2021-09-22
728    2021-09-23
729    2021-09-24
Name: Date, Length: 730, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AXNX_ended_2021-09-25  2018-10-31         70.64  11.95  79.81       6.786

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    18.736    25.522    32.308    39.094     45.88    52.666    59.452

  markup_80 markup_90 markup_100
0    66.238    73.024      79.81
                   stock  start_date current_price minall maxall each_markup  \
0  AXNX_ended_2021-09-25  2018-10-31         70.64  11.95  79.81       6.786

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    18.736    25.522    32.308    39.094     45.88    52.666    59.452

  markup_80 markup_90 markup_100
0    66.238    73.024      79.81
./ticker_data/ticker_data_2021-09-25 - Copy/AXON_ended_2021-09-25.csv
           Date        Open        High         Low       Close   Adj Close  \
0    2019-04-18    0.058000    0.058000    0.058000    0.058000    0.058000
1    2020-07-28   86.040001   86.809998   84.959999   85.849998   85.849998
2    2020-07-29   86.070000   86.790001   84.730003   84.889999   84.889999
3    2020-07-30   84.059998   85.709999   83.480003   84.879997   84.879997
4    2020-07-31   85.660004   86.050003   82.449997   83.129997   83.129997
..          ...         ...         ...         ...         ...         ...
275  2021-08-30  187.860001  193.220001  185.860001  192.839996  192.839996
276  2021-08-31  193.410004  194.000000  181.610001  181.869995  181.869995
277  2021-09-01  181.779999  184.669998  181.220001  181.649994  181.649994
278  2021-09-02  181.619995  184.910004  181.059998  182.869995  182.869995
279  2021-09-03  182.000000  185.520004  180.649994  184.889999  184.889999

       Volume
0           0
1      374500
2      413200
3      493400
4      680300
..        ...
275  42840000
276  54790000
277  52930000
278  24040000
279  20450000

[280 rows x 7 columns]
tolistdate: 0      2019-04-18
1      2020-07-28
2      2020-07-29
3      2020-07-30
4      2020-07-31
          ...
275    2021-08-30
276    2021-08-31
277    2021-09-01
278    2021-09-02
279    2021-09-03
Name: Date, Length: 280, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AXON_ended_2021-09-25  2019-04-18        184.89  0.058  212.37     21.2312

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   21.2892   42.5204   63.7516   84.9828   106.214   127.445   148.676

  markup_80 markup_90 markup_100
0   169.908   191.139     212.37
                   stock  start_date current_price minall  maxall each_markup  \
0  AXON_ended_2021-09-25  2019-04-18        184.89  0.058  212.37     21.2312

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   21.2892   42.5204   63.7516   84.9828   106.214   127.445   148.676

  markup_80 markup_90 markup_100
0   169.908   191.139     212.37
./ticker_data/ticker_data_2021-09-25 - Copy/AXSM_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2015-11-19   9.000000   9.440000   8.320000   8.740000   8.740000
1     2015-11-20   8.540000   9.090000   8.430000   9.070000   9.070000
2     2015-11-23   9.070000   9.200000   9.050000   9.060000   9.060000
3     2015-11-24   9.200000   9.200000   9.020000   9.200000   9.200000
4     2015-11-25   9.200000   9.700000   8.090000   8.820000   8.820000
...          ...        ...        ...        ...        ...        ...
1467  2021-09-20  28.980000  29.549999  28.520000  29.230000  29.230000
1468  2021-09-21  29.549999  31.889999  29.198000  31.209999  31.209999
1469  2021-09-22  31.559999  31.600000  29.709999  30.889999  30.889999
1470  2021-09-23  31.200001  32.990002  31.000000  32.959999  32.959999
1471  2021-09-24  32.540001  34.404999  32.540001  33.820000  33.820000

       Volume
0      532300
1       30800
2       13900
3        7600
4      135600
...       ...
1467   893500
1468  1177000
1469  1104100
1470   828000
1471   524988

[1472 rows x 7 columns]
tolistdate: 0       2015-11-19
1       2015-11-20
2       2015-11-23
3       2015-11-24
4       2015-11-25
           ...
1467    2021-09-20
1468    2021-09-21
1469    2021-09-22
1470    2021-09-23
1471    2021-09-24
Name: Date, Length: 1472, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AXSM_ended_2021-09-25  2015-11-19         33.82   1.94  109.94        10.8

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     12.74     23.54     34.34     45.14     55.94     66.74     77.54

  markup_80 markup_90 markup_100
0     88.34     99.14     109.94
                   stock  start_date current_price minall  maxall each_markup  \
0  AXSM_ended_2021-09-25  2015-11-19         33.82   1.94  109.94        10.8

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     12.74     23.54     34.34     45.14     55.94     66.74     77.54

  markup_80 markup_90 markup_100
0     88.34     99.14     109.94
./ticker_data/ticker_data_2021-09-25 - Copy/AXTI_ended_2021-09-25.csv
            Date     Open     High      Low    Close  Adj Close    Volume
0     1999-12-31  17.6875  17.6875  17.0000  17.4375    17.4375    268200
1     2000-01-03  17.8750  18.8750  17.8125  18.7500    18.7500    231500
2     2000-01-04  18.5000  19.2500  18.0000  18.3125    18.3125    299300
3     2000-01-05  18.2500  18.5000  17.8750  18.0625    18.0625    398800
4     2000-01-06  18.1250  18.8750  17.8750  18.5625    18.5625    214700
...          ...      ...      ...      ...      ...        ...       ...
5449  2021-08-30   9.3800   9.4200   9.2000   9.3600     9.3600  14750000
5450  2021-08-31   9.3600   9.3900   9.1200   9.3100     9.3100  14760000
5451  2021-09-01   9.3600   9.4100   9.1900   9.3000     9.3000  15900000
5452  2021-09-02   9.3900   9.9100   9.3000   9.7200     9.7200  24090000
5453  2021-09-03   9.7200   9.9900   9.6300   9.8100     9.8100  18880000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall   maxall  \
0  AXTI_ended_2021-09-25  1999-12-31          9.81   0.66  49.5625

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     4.89025   5.55025   10.4405   15.3308    20.221   25.1113   30.0015

  markup_70 markup_80 markup_90 markup_100
0   34.8918    39.782   44.6723    49.5625
                   stock  start_date current_price minall   maxall  \
0  AXTI_ended_2021-09-25  1999-12-31          9.81   0.66  49.5625

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     4.89025   5.55025   10.4405   15.3308    20.221   25.1113   30.0015

  markup_70 markup_80 markup_90 markup_100
0   34.8918    39.782   44.6723    49.5625
./ticker_data/ticker_data_2021-09-25 - Copy/AYLA_ended_2021-09-25.csv
           Date    Open    High     Low   Close  Adj Close   Volume
0    2020-05-08  15.660  16.500  14.630  15.030     15.030  1728700
1    2020-05-11  15.390  15.400  15.010  15.150     15.150   125500
2    2020-05-12  15.180  15.360  14.830  15.000     15.000   194700
3    2020-05-13  15.000  15.150  14.830  15.000     15.000   184400
4    2020-05-14  15.000  15.200  14.901  15.000     15.000   125500
..          ...     ...     ...     ...     ...        ...      ...
329  2021-08-30  12.436  12.509  12.150  12.250     12.250   520000
330  2021-08-31  12.320  12.670  12.320  12.670     12.670   210000
331  2021-09-01  12.340  13.200  12.120  13.180     13.180  2680000
332  2021-09-02  12.490  13.200  12.240  13.100     13.100  1550000
333  2021-09-03  13.200  13.311  12.600  13.311     13.311   500000

[334 rows x 7 columns]
tolistdate: 0      2020-05-08
1      2020-05-11
2      2020-05-12
3      2020-05-13
4      2020-05-14
          ...
329    2021-08-30
330    2021-08-31
331    2021-09-01
332    2021-09-02
333    2021-09-03
Name: Date, Length: 334, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AYLA_ended_2021-09-25  2020-05-08        13.311  7.738  28.68      2.0942

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.8322   11.9264   14.0206   16.1148    18.209   20.3032   22.3974

  markup_80 markup_90 markup_100
0   24.4916   26.5858      28.68
                   stock  start_date current_price minall maxall each_markup  \
0  AYLA_ended_2021-09-25  2020-05-08        13.311  7.738  28.68      2.0942

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.8322   11.9264   14.0206   16.1148    18.209   20.3032   22.3974

  markup_80 markup_90 markup_100
0   24.4916   26.5858      28.68
./ticker_data/ticker_data_2021-09-25 - Copy/AYRO_ended_2021-09-25.csv
            Date         Open         High           Low         Close  \
0     2003-10-07  337075.1875  354816.0000  337075.18750  352598.40625
1     2003-10-08  361468.8125  361468.8125  345945.59375  350380.81250
2     2003-10-09  354816.0000  370339.1875  354816.00000  365904.00000
3     2003-10-10  365904.0000  376992.0000  365904.00000  374774.40625
4     2003-10-13  370339.1875  383644.8125  365904.00000  372556.81250
...          ...          ...          ...           ...           ...
4447  2021-08-30       3.9900       4.1000       3.89000       4.07000
4448  2021-08-31       4.0400       4.2000       3.99000       4.13000
4449  2021-09-01       4.0700       4.1700       4.02000       4.05000
4450  2021-09-02       4.0900       4.1700       4.06000       4.12000
4451  2021-09-03       4.0800       4.1500       3.91000       4.00000

         Adj Close    Volume
0     352598.40625         0
1     350380.81250         0
2     365904.00000         0
3     374774.40625         0
4     372556.81250         0
...            ...       ...
4447       4.07000  40880000
4448       4.13000  43020000
4449       4.05000  42980000
4450       4.12000  48500000
4451       4.00000  49900000

[4452 rows x 7 columns]
tolistdate: 0       2003-10-07
1       2003-10-08
2       2003-10-09
3       2003-10-10
4       2003-10-13
           ...
4447    2021-08-30
4448    2021-08-31
4449    2021-09-01
4450    2021-09-02
4451    2021-09-03
Name: Date, Length: 4452, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AYRO_ended_2021-09-25  2003-10-07             4    1.8  383645     38364.3

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   38366.1   76730.4    115095    153459    191823    230188    268552

  markup_80 markup_90 markup_100
0    306916    345281     383645
                   stock  start_date current_price minall  maxall each_markup  \
0  AYRO_ended_2021-09-25  2003-10-07             4    1.8  383645     38364.3

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   38366.1   76730.4    115095    153459    191823    230188    268552

  markup_80 markup_90 markup_100
0    306916    345281     383645
./ticker_data/ticker_data_2021-09-25 - Copy/AYTU_ended_2021-09-25.csv
            Date           Open           High            Low          Close  \
0     2008-09-25  187317.078125  187317.078125  187317.078125  187317.078125
1     2008-10-02  117073.171875  117073.171875  117073.171875  117073.171875
2     2008-10-03  175609.750000  175609.750000  175609.750000  175609.750000
3     2008-10-09  134634.140625  134634.140625  134634.140625  134634.140625
4     2008-10-15  146341.468750  146341.468750  146341.468750  146341.468750
...          ...            ...            ...            ...            ...
1520  2021-09-20       3.060000       3.120000       2.980000       3.000000
1521  2021-09-21       3.000000       3.020000       2.830000       2.840000
1522  2021-09-22       2.850000       2.920000       2.790000       2.800000
1523  2021-09-23       2.820000       3.070000       2.800000       3.010000
1524  2021-09-24       3.040000       3.040000       2.950000       2.990800

          Adj Close  Volume
0     187317.078125       0
1     117073.171875       0
2     175609.750000       0
3     134634.140625       0
4     146341.468750       0
...             ...     ...
1520       3.000000  390500
1521       2.840000  617000
1522       2.800000  674100
1523       3.010000  594900
1524       2.990800   89449

[1525 rows x 7 columns]
tolistdate: 0       2008-09-25
1       2008-10-02
2       2008-10-03
3       2008-10-09
4       2008-10-15
           ...
1520    2021-09-20
1521    2021-09-21
1522    2021-09-22
1523    2021-09-23
1524    2021-09-24
Name: Date, Length: 1525, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AYTU_ended_2021-09-25  2008-09-25        2.9908   2.79  591220     59121.7

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   59124.5    118246    177368    236489    295611    354733    413854

  markup_80 markup_90 markup_100
0    472976    532098     591220
                   stock  start_date current_price minall  maxall each_markup  \
0  AYTU_ended_2021-09-25  2008-09-25        2.9908   2.79  591220     59121.7

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   59124.5    118246    177368    236489    295611    354733    413854

  markup_80 markup_90 markup_100
0    472976    532098     591220
./ticker_data/ticker_data_2021-09-25 - Copy/AY_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2014-06-13  35.160000  38.279999  35.000000  37.000000  25.470146
1     2014-06-16  37.000000  37.480000  36.110001  36.520000  25.139713
2     2014-06-17  36.470001  36.799999  35.540001  36.500000  25.125948
3     2014-06-18  35.799999  37.000000  35.650002  36.900002  25.401299
4     2014-06-19  36.750000  37.560001  36.580002  37.360001  25.717955
...          ...        ...        ...        ...        ...        ...
1815  2021-08-30  38.009998  38.130001  37.259998  37.410000  37.410000
1816  2021-08-31  37.549999  37.799999  37.049999  37.610001  37.610001
1817  2021-09-01  37.869999  38.449001  37.770000  37.959999  37.959999
1818  2021-09-02  38.020000  38.634998  37.910000  38.459999  38.459999
1819  2021-09-03  38.529999  38.529999  38.049999  38.160000  38.160000

        Volume
0     15448800
1      1702200
2      1099100
3       479900
4       496400
...        ...
1815  49980000
1816  60700000
1817  41200000
1818  29230000
1819  23760000

[1820 rows x 7 columns]
tolistdate: 0       2014-06-13
1       2014-06-16
2       2014-06-17
3       2014-06-18
4       2014-06-19
           ...
1815    2021-08-30
1816    2021-08-31
1817    2021-09-01
1818    2021-09-02
1819    2021-09-03
Name: Date, Length: 1820, dtype: object
                 stock  start_date current_price minall maxall each_markup  \
0  AY_ended_2021-09-25  2014-06-13         38.16  13.11  48.49       3.538

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    16.648    20.186    23.724    27.262      30.8    34.338    37.876

  markup_80 markup_90 markup_100
0    41.414    44.952      48.49
                 stock  start_date current_price minall maxall each_markup  \
0  AY_ended_2021-09-25  2014-06-13         38.16  13.11  48.49       3.538

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    16.648    20.186    23.724    27.262      30.8    34.338    37.876

  markup_80 markup_90 markup_100
0    41.414    44.952      48.49
./ticker_data/ticker_data_2021-09-25 - Copy/AZN_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  20.656250  20.937500  20.406250  20.875000   8.617407
1     2000-01-03  20.687500  20.687500  20.437500  20.562500   8.488406
2     2000-01-04  20.031250  20.187500  19.812500  19.875000   8.204600
3     2000-01-05  19.750000  20.000000  19.531250  19.968750   8.243298
4     2000-01-06  19.781250  19.968750  19.718750  19.906250   8.217499
...          ...        ...        ...        ...        ...        ...
5450  2021-08-30  58.669998  58.810001  58.509998  58.610001  58.610001
5451  2021-08-31  58.450001  58.810001  58.169998  58.279999  58.279999
5452  2021-09-01  58.740002  58.919998  58.380001  58.720001  58.720001
5453  2021-09-02  59.169998  59.619999  59.090000  59.590000  59.590000
5454  2021-09-03  59.150002  59.240002  58.630001  58.830002  58.830002

         Volume
0        146600
1        345000
2        447200
3        466400
4        753400
...         ...
5450  229650000
5451  441690000
5452  434430000
5453  325430000
5454  533060000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  AZN_ended_2021-09-25  1999-12-31         58.83     14  64.94       5.094

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    19.094    24.188    29.282    34.376     39.47    44.564    49.658

  markup_80 markup_90 markup_100
0    54.752    59.846      64.94
                  stock  start_date current_price minall maxall each_markup  \
0  AZN_ended_2021-09-25  1999-12-31         58.83     14  64.94       5.094

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    19.094    24.188    29.282    34.376     39.47    44.564    49.658

  markup_80 markup_90 markup_100
0    54.752    59.846      64.94
./ticker_data/ticker_data_2021-09-25 - Copy/AZPN_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31   26.250000   26.625000   25.875000   26.437500   26.437500
1     2000-01-03   30.000000   30.375000   27.375000   29.937500   29.937500
2     2000-01-04   28.125000   29.875000   28.000000   29.718750   29.718750
3     2000-01-05   29.687500   30.500000   29.250000   30.250000   30.250000
4     2000-01-06   30.062500   30.937500   29.625000   30.312500   30.312500
...          ...         ...         ...         ...         ...         ...
5449  2021-08-30  131.100006  132.000000  129.820007  129.899994  129.899994
5450  2021-08-31  130.389999  130.389999  129.080002  129.500000  129.500000
5451  2021-09-01  129.669998  131.350006  129.500000  130.050003  130.050003
5452  2021-09-02  130.570007  131.699997  130.070007  130.919998  130.919998
5453  2021-09-03  131.169998  132.589996  130.610001  130.919998  130.919998

        Volume
0        27000
1       375700
2       432100
3       420800
4       697700
...        ...
5449  29030000
5450  34730000
5451  35260000
5452  31400000
5453  18590000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  AZPN_ended_2021-09-25  1999-12-31        130.92   0.59  162.56      16.197

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    16.787    32.984    49.181    65.378    81.575    97.772   113.969

  markup_80 markup_90 markup_100
0   130.166   146.363     162.56
                   stock  start_date current_price minall  maxall each_markup  \
0  AZPN_ended_2021-09-25  1999-12-31        130.92   0.59  162.56      16.197

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    16.787    32.984    49.181    65.378    81.575    97.772   113.969

  markup_80 markup_90 markup_100
0   130.166   146.363     162.56
./ticker_data/ticker_data_2021-09-25 - Copy/AZRX_ended_2021-09-25.csv
            Date   Open   High    Low  Close  Adj Close     Volume
0     2016-10-11  5.060  5.590  4.870  4.980      4.980     115800
1     2016-10-12  5.010  5.480  5.000  5.480      5.480     124200
2     2016-10-13  5.550  5.600  5.120  5.150      5.150      45900
3     2016-10-14  5.340  5.350  5.011  5.260      5.260      78300
4     2016-10-17  5.270  5.340  5.000  5.010      5.010     121300
...          ...    ...    ...    ...    ...        ...        ...
1229  2021-08-30  0.625  0.625  0.600  0.600      0.600  166930000
1230  2021-08-31  0.610  0.629  0.601  0.629      0.629  154400000
1231  2021-09-01  0.640  0.668  0.616  0.640      0.640  268770000
1232  2021-09-02  0.626  0.668  0.626  0.638      0.638  166660000
1233  2021-09-03  0.636  0.636  0.625  0.627      0.627   82050000

[1234 rows x 7 columns]
tolistdate: 0       2016-10-11
1       2016-10-12
2       2016-10-13
3       2016-10-14
4       2016-10-17
           ...
1229    2021-08-30
1230    2021-08-31
1231    2021-09-01
1232    2021-09-02
1233    2021-09-03
Name: Date, Length: 1234, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AZRX_ended_2021-09-25  2016-10-11         0.627  0.371    5.6      0.5229

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    0.8939    1.4168    1.9397    2.4626    2.9855    3.5084    4.0313

  markup_80 markup_90 markup_100
0    4.5542    5.0771        5.6
                   stock  start_date current_price minall maxall each_markup  \
0  AZRX_ended_2021-09-25  2016-10-11         0.627  0.371    5.6      0.5229

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    0.8939    1.4168    1.9397    2.4626    2.9855    3.5084    4.0313

  markup_80 markup_90 markup_100
0    4.5542    5.0771        5.6
./ticker_data/ticker_data_2021-09-25 - Copy/AZYO_ended_2021-09-25.csv
           Date    Open    High     Low  Close  Adj Close   Volume
0    2020-10-08  17.320  18.000  13.750  14.50      14.50  2043800
1    2020-10-09  14.030  14.392  13.540  13.54      13.54    91200
2    2020-10-12  13.970  13.970  12.600  12.60      12.60   136200
3    2020-10-13  12.480  12.880  12.100  12.25      12.25    92800
4    2020-10-14  12.150  12.800  12.080  12.31      12.31    73400
..          ...     ...     ...     ...    ...        ...      ...
238  2021-09-20   8.250   8.500   7.410   7.45       7.45    35100
239  2021-09-21   7.390   7.825   7.255   7.57       7.57     8600
240  2021-09-22   7.720   8.000   7.500   7.52       7.52     4400
241  2021-09-23   7.561   7.800   7.550   7.55       7.55     4400
242  2021-09-24   7.550   7.680   7.550   7.68       7.68     2200

[243 rows x 7 columns]
tolistdate: 0      2020-10-08
1      2020-10-09
2      2020-10-12
3      2020-10-13
4      2020-10-14
          ...
238    2021-09-20
239    2021-09-21
240    2021-09-22
241    2021-09-23
242    2021-09-24
Name: Date, Length: 243, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  AZYO_ended_2021-09-25  2020-10-08          7.68  7.255   18.2      1.0945

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    8.3495     9.444   10.5385    11.633   12.7275    13.822   14.9165

  markup_80 markup_90 markup_100
0    16.011   17.1055       18.2
                   stock  start_date current_price minall maxall each_markup  \
0  AZYO_ended_2021-09-25  2020-10-08          7.68  7.255   18.2      1.0945

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    8.3495     9.444   10.5385    11.633   12.7275    13.822   14.9165

  markup_80 markup_90 markup_100
0    16.011   17.1055       18.2
./ticker_data/ticker_data_2021-09-25 - Copy/BAND_ended_2021-09-25.csv
           Date        Open        High         Low       Close   Adj Close  \
0    2017-11-09   20.000000   20.000000   20.000000   20.000000   20.000000
1    2017-11-10   21.049999   22.000000   20.549999   21.190001   21.190001
2    2017-11-13   21.250000   21.379999   20.010000   20.299999   20.299999
3    2017-11-14   20.070000   20.480000   20.000000   20.090000   20.090000
4    2017-11-15   20.040001   20.350000   20.000000   20.040001   20.040001
..          ...         ...         ...         ...         ...         ...
955  2021-08-30  105.120003  107.599998  104.589996  104.699997  104.699997
956  2021-08-31  104.040001  104.550003  102.419998  102.900002  102.900002
957  2021-09-01  103.989998  108.669998  102.599998  106.900002  106.900002
958  2021-09-02  107.059998  110.599998  106.440002  108.050003  108.050003
959  2021-09-03  107.500000  108.530998  105.500000  106.669998  106.669998

       Volume
0         100
1     2409300
2      420000
3      151300
4      146200
..        ...
955  22740000
956  35860000
957  33370000
958  25370000
959  17340000

[960 rows x 7 columns]
tolistdate: 0      2017-11-09
1      2017-11-10
2      2017-11-13
3      2017-11-14
4      2017-11-15
          ...
955    2021-08-30
956    2021-08-31
957    2021-09-01
958    2021-09-02
959    2021-09-03
Name: Date, Length: 960, dtype: object
                   stock  start_date current_price minall   maxall  \
0  BAND_ended_2021-09-25  2017-11-09        106.67  18.05  198.605

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     18.0555   36.1055    54.161   72.2165    90.272   108.327   126.383

  markup_70 markup_80 markup_90 markup_100
0   144.438   162.494   180.549    198.605
                   stock  start_date current_price minall   maxall  \
0  BAND_ended_2021-09-25  2017-11-09        106.67  18.05  198.605

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     18.0555   36.1055    54.161   72.2165    90.272   108.327   126.383

  markup_70 markup_80 markup_90 markup_100
0   144.438   162.494   180.549    198.605
./ticker_data/ticker_data_2021-09-25 - Copy/BANFP_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2004-03-16  25.850000  25.950001  25.750000  25.950001   7.883038
1     2004-03-17  25.850000  25.950001  25.850000  25.950001   7.883038
2     2004-03-18  25.900000  25.950001  25.900000  25.950001   7.883038
3     2004-03-19  25.950001  26.309999  25.950001  26.000000   7.898227
4     2004-03-22  26.000000  26.000000  26.000000  26.000000   7.898227
...          ...        ...        ...        ...        ...        ...
3137  2021-08-26  27.020000  27.020000  27.020000  27.020000  27.020000
3138  2021-08-31  27.500000  27.500000  27.500000  27.500000  27.500000
3139  2021-09-01  27.500000  27.500000  27.500000  27.500000  27.500000
3140  2021-09-02  27.500000  27.580000  27.500000  27.500000  27.500000
3141  2021-09-03  27.639999  27.650000  27.639999  27.650000  27.650000

      Volume
0      24700
1       2900
2        200
3       2400
4        600
...      ...
3137       0
3138  100000
3139   30000
3140  110000
3141   70000

[3142 rows x 7 columns]
tolistdate: 0       2004-03-16
1       2004-03-17
2       2004-03-18
3       2004-03-19
4       2004-03-22
           ...
3137    2021-08-26
3138    2021-08-31
3139    2021-09-01
3140    2021-09-02
3141    2021-09-03
Name: Date, Length: 3142, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BANFP_ended_2021-09-25  2004-03-16         27.65  17.11   36.2       1.909

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    19.019    20.928    22.837    24.746    26.655    28.564    30.473

  markup_80 markup_90 markup_100
0    32.382    34.291       36.2
                    stock  start_date current_price minall maxall each_markup  \
0  BANFP_ended_2021-09-25  2004-03-16         27.65  17.11   36.2       1.909

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    19.019    20.928    22.837    24.746    26.655    28.564    30.473

  markup_80 markup_90 markup_100
0    32.382    34.291       36.2
./ticker_data/ticker_data_2021-09-25 - Copy/BANF_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   8.484375   8.484375   8.484375   8.484375   5.347830
1     2000-01-03   8.562500   8.562500   8.343750   8.343750   5.259192
2     2000-01-04   8.343750   8.453125   8.015625   8.070312   5.086838
3     2000-01-05   8.023438   8.023438   7.953125   8.000000   5.042522
4     2000-01-06   8.078125   8.562500   8.000000   8.031250   5.062218
...          ...        ...        ...        ...        ...        ...
5443  2021-08-30  57.270000  57.270000  55.770000  55.919998  55.919998
5444  2021-08-31  56.130001  57.070000  55.410000  56.560001  56.560001
5445  2021-09-01  56.840000  56.840000  55.750000  56.380001  56.380001
5446  2021-09-02  56.270000  56.560001  55.790001  55.970001  55.970001
5447  2021-09-03  56.110001  56.119999  55.099998  55.570000  55.570000

        Volume
0         3200
1         3600
2        10400
3        10400
4        35600
...        ...
5443   8750000
5444  11020000
5445   7700000
5446   6960000
5447   8390000

[5448 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5443    2021-08-30
5444    2021-08-31
5445    2021-09-01
5446    2021-09-02
5447    2021-09-03
Name: Date, Length: 5448, dtype: object
                   stock  start_date current_price  minall maxall each_markup  \
0  BANF_ended_2021-09-25  1999-12-31         55.57  6.1875  77.38     7.11925

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   13.3067    20.426   27.5452   34.6645   41.7837    48.903   56.0222

  markup_80 markup_90 markup_100
0   63.1415   70.2607      77.38
                   stock  start_date current_price  minall maxall each_markup  \
0  BANF_ended_2021-09-25  1999-12-31         55.57  6.1875  77.38     7.11925

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   13.3067    20.426   27.5452   34.6645   41.7837    48.903   56.0222

  markup_80 markup_90 markup_100
0   63.1415   70.2607      77.38
./ticker_data/ticker_data_2021-09-25 - Copy/BANR_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  95.454544  96.250000  93.863632  93.863632  54.953884
1     2000-01-03  96.846588  96.846588  93.465912  94.261368  55.186752
2     2000-01-04  94.261368  94.659088  93.068184  93.863632  54.953884
3     2000-01-05  92.670456  97.840912  91.477272  94.261368  55.186752
4     2000-01-06  94.659088  94.659088  92.272728  93.068184  54.488167
...          ...        ...        ...        ...        ...        ...
5464  2021-09-20  51.180000  51.709999  50.020000  51.119999  51.119999
5465  2021-09-21  51.360001  51.700001  50.759998  51.080002  51.080002
5466  2021-09-22  51.610001  52.790001  51.310001  51.400002  51.400002
5467  2021-09-23  51.970001  53.299999  51.970001  52.790001  52.790001
5468  2021-09-24  52.660000  54.220001  52.660000  54.040001  54.040001

      Volume
0       8564
1       3221
2       3111
3       2499
4       2891
...      ...
5464  137900
5465  134500
5466  176500
5467  334300
5468   26100

[5469 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5464    2021-09-20
5465    2021-09-21
5466    2021-09-22
5467    2021-09-23
5468    2021-09-24
Name: Date, Length: 5469, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BANR_ended_2021-09-25  1999-12-31         54.04  10.92  326.97      31.605

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    42.525     74.13   105.735    137.34   168.945    200.55   232.155

  markup_80 markup_90 markup_100
0    263.76   295.365     326.97
                   stock  start_date current_price minall  maxall each_markup  \
0  BANR_ended_2021-09-25  1999-12-31         54.04  10.92  326.97      31.605

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    42.525     74.13   105.735    137.34   168.945    200.55   232.155

  markup_80 markup_90 markup_100
0    263.76   295.365     326.97
./ticker_data/ticker_data_2021-09-25 - Copy/BANX_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2013-11-07  25.049999  25.240000  24.900000  25.000000  13.887175
1     2013-11-08  25.000000  25.049999  24.950001  24.990000  13.881620
2     2013-11-11  25.040001  27.450001  25.040001  25.250000  14.026047
3     2013-11-12  25.250000  25.500000  25.010000  25.010000  13.892732
4     2013-11-13  25.110001  25.490000  25.110001  25.209999  14.003826
...          ...        ...        ...        ...        ...        ...
1961  2021-08-31  21.900000  22.150000  21.900000  22.150000  22.150000
1962  2021-09-01  22.049999  22.139999  21.940001  22.030001  22.030001
1963  2021-09-02  21.920000  22.049999  21.920000  21.980000  21.980000
1964  2021-09-03  21.850000  22.250000  21.500000  21.920000  21.920000
1965  2021-09-20        NaN        NaN        NaN        NaN        NaN

        Volume
0     340200.0
1      61200.0
2      13700.0
3      40600.0
4       6300.0
...        ...
1961  690000.0
1962  690000.0
1963  940000.0
1964  720000.0
1965       NaN

[1966 rows x 7 columns]
tolistdate: 0       2013-11-07
1       2013-11-08
2       2013-11-11
3       2013-11-12
4       2013-11-13
           ...
1961    2021-08-31
1962    2021-09-01
1963    2021-09-02
1964    2021-09-03
1965    2021-09-20
Name: Date, Length: 1966, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BANX_ended_2021-09-25  2013-11-07           NaN   9.25   28.6       1.935

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.185     13.12    15.055     16.99    18.925     20.86    22.795

  markup_80 markup_90 markup_100
0     24.73    26.665       28.6
                   stock  start_date current_price minall maxall each_markup  \
0  BANX_ended_2021-09-25  2013-11-07           NaN   9.25   28.6       1.935

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.185     13.12    15.055     16.99    18.925     20.86    22.795

  markup_80 markup_90 markup_100
0     24.73    26.665       28.6
./ticker_data/ticker_data_2021-09-25 - Copy/BAOS_ended_2021-09-25.csv
           Date  Open    High    Low  Close  Adj Close    Volume
0    2021-02-08  8.25  10.200  7.800   8.86       8.86   2816800
1    2021-02-09  8.12   8.540  7.550   7.59       7.59    630200
2    2021-02-10  7.87   8.330  7.221   7.58       7.58    503100
3    2021-02-11  7.63   7.711  7.030   7.14       7.14    211900
4    2021-02-12  7.00   7.490  7.000   7.09       7.09    134300
..          ...   ...     ...    ...    ...        ...       ...
141  2021-08-30  2.30   2.340  2.230   2.24       2.24  15980000
142  2021-08-31  2.28   2.360  2.250   2.32       2.32  12980000
143  2021-09-01  2.33   2.400  2.290   2.35       2.35  14730000
144  2021-09-02  2.35   2.410  2.310   2.34       2.34  11790000
145  2021-09-03  2.34   2.420  2.240   2.25       2.25  10870000

[146 rows x 7 columns]
tolistdate: 0      2021-02-08
1      2021-02-09
2      2021-02-10
3      2021-02-11
4      2021-02-12
          ...
141    2021-08-30
142    2021-08-31
143    2021-09-01
144    2021-09-02
145    2021-09-03
Name: Date, Length: 146, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BAOS_ended_2021-09-25  2021-02-08          2.25  1.924   10.2      0.8276

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.7516    3.5792    4.4068    5.2344     6.062    6.8896    7.7172

  markup_80 markup_90 markup_100
0    8.5448    9.3724       10.2
                   stock  start_date current_price minall maxall each_markup  \
0  BAOS_ended_2021-09-25  2021-02-08          2.25  1.924   10.2      0.8276

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.7516    3.5792    4.4068    5.2344     6.062    6.8896    7.7172

  markup_80 markup_90 markup_100
0    8.5448    9.3724       10.2
./ticker_data/ticker_data_2021-09-25 - Copy/BATRA_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2016-04-18  36.000000  36.000000  19.860001  19.950001  19.950001
1     2016-04-19  20.280001  20.510000  17.809999  18.049999  18.049999
2     2016-04-20  18.260000  18.389000  17.309999  18.049999  18.049999
3     2016-04-21  17.930000  18.549999  17.799999  18.480000  18.480000
4     2016-04-22  18.480000  18.700001  17.740000  17.780001  17.780001
...          ...        ...        ...        ...        ...        ...
1351  2021-08-30  26.400000  26.400000  25.900000  26.090000  26.090000
1352  2021-08-31  26.110001  26.280001  25.910000  26.000000  26.000000
1353  2021-09-01  26.150000  26.480000  26.049999  26.250000  26.250000
1354  2021-09-02  26.280001  26.280001  26.000000  26.080000  26.080000
1355  2021-09-03  26.090000  26.090000  25.500000  25.620001  25.620001

       Volume
0      314700
1      802400
2     1062900
3      649900
4      467800
...       ...
1351  2830000
1352  4540000
1353  3720000
1354  2060000
1355  5030000

[1356 rows x 7 columns]
tolistdate: 0       2016-04-18
1       2016-04-19
2       2016-04-20
3       2016-04-21
4       2016-04-22
           ...
1351    2021-08-30
1352    2021-08-31
1353    2021-09-01
1354    2021-09-02
1355    2021-09-03
Name: Date, Length: 1356, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BATRA_ended_2021-09-25  2016-04-18         25.62  13.59     36       2.241

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.831    18.072    20.313    22.554    24.795    27.036    29.277

  markup_80 markup_90 markup_100
0    31.518    33.759         36
                    stock  start_date current_price minall maxall each_markup  \
0  BATRA_ended_2021-09-25  2016-04-18         25.62  13.59     36       2.241

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.831    18.072    20.313    22.554    24.795    27.036    29.277

  markup_80 markup_90 markup_100
0    31.518    33.759         36
./ticker_data/ticker_data_2021-09-25 - Copy/BATRK_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2016-04-18  27.000000  27.000000  18.760000  19.139999  19.139999
1     2016-04-19  18.879999  19.110001  17.270000  17.500000  17.500000
2     2016-04-20  17.059999  17.677000  17.000000  17.280001  17.280001
3     2016-04-21  17.049999  17.600000  16.930000  17.520000  17.520000
4     2016-04-22  17.510000  17.650000  16.940001  16.950001  16.950001
...          ...        ...        ...        ...        ...        ...
1352  2021-08-30  26.219999  26.330000  25.760000  25.889999  25.889999
1353  2021-08-31  25.969999  26.100000  25.750999  25.850000  25.850000
1354  2021-09-01  25.980000  26.360001  25.770000  26.129999  26.129999
1355  2021-09-02  26.250000  26.250000  25.830000  25.920000  25.920000
1356  2021-09-03  25.910000  25.910000  25.450001  25.530001  25.530001

        Volume
0       542900
1      1344000
2       978300
3       660600
4       383700
...        ...
1352   7280000
1353   9610000
1354   8300000
1355   4860000
1356  10640000

[1357 rows x 7 columns]
tolistdate: 0       2016-04-18
1       2016-04-19
2       2016-04-20
3       2016-04-21
4       2016-04-22
           ...
1352    2021-08-30
1353    2021-08-31
1354    2021-09-01
1355    2021-09-02
1356    2021-09-03
Name: Date, Length: 1357, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BATRK_ended_2021-09-25  2016-04-18         25.53   13.2  31.76       1.856

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.056    16.912    18.768    20.624     22.48    24.336    26.192

  markup_80 markup_90 markup_100
0    28.048    29.904      31.76
                    stock  start_date current_price minall maxall each_markup  \
0  BATRK_ended_2021-09-25  2016-04-18         25.53   13.2  31.76       1.856

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.056    16.912    18.768    20.624     22.48    24.336    26.192

  markup_80 markup_90 markup_100
0    28.048    29.904      31.76
./ticker_data/ticker_data_2021-09-25 - Copy/BBBY_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  17.000000  18.000000  16.968750  17.375000  15.070722
1     2000-01-03  16.875000  17.312500  16.343750  16.500000  14.311763
2     2000-01-04  16.937500  16.937500  15.406250  15.468750  13.417278
3     2000-01-05  15.468750  16.000000  15.312500  15.687500  13.607017
4     2000-01-06  15.562500  16.218750  15.437500  16.062500  13.932287
...          ...        ...        ...        ...        ...        ...
5450  2021-08-30  28.410000  28.950001  28.100000  28.440001  28.440001
5451  2021-08-31  28.090000  28.209999  27.389999  27.540001  27.540001
5452  2021-09-01  27.530001  27.879999  26.709999  27.740000  27.740000
5453  2021-09-02  27.250000  28.160000  27.160000  27.700001  27.700001
5454  2021-09-03  27.700001  27.730000  26.910000  27.020000  27.020000

         Volume
0       3591800
1       3056600
2       3169600
3       3022000
4       4017600
...         ...
5450  138220000
5451  205330000
5452  209560000
5453  115190000
5454  183460000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BBBY_ended_2021-09-25  1999-12-31         27.02   3.43  80.82       7.739

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.169    18.908    26.647    34.386    42.125    49.864    57.603

  markup_80 markup_90 markup_100

0    65.342    73.081      80.82
                   stock  start_date current_price minall maxall each_markup  \
0  BBBY_ended_2021-09-25  1999-12-31         27.02   3.43  80.82       7.739

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.169    18.908    26.647    34.386    42.125    49.864    57.603

  markup_80 markup_90 markup_100
0    65.342    73.081      80.82
./ticker_data/ticker_data_2021-09-25 - Copy/BBCP_ended_2021-09-25.csv
           Date  Open   High    Low  Close  Adj Close   Volume
0    2017-08-21  9.81  9.810  9.700  9.700      9.700    58700
1    2017-08-22  9.70  9.700  9.700  9.700      9.700    27300
2    2017-08-23  9.70  9.700  9.700  9.700      9.700        0
3    2017-08-24  9.70  9.700  9.700  9.700      9.700    10000
4    2017-08-25  9.70  9.713  9.700  9.713      9.713    29800
..          ...   ...    ...    ...    ...        ...      ...
962  2021-08-30  8.37  8.480  8.215  8.360      8.360  4710000
963  2021-08-31  8.33  8.430  8.300  8.310      8.310  7360000
964  2021-09-01  8.28  8.290  8.170  8.230      8.230  6010000
965  2021-09-02  8.26  8.640  8.240  8.620      8.620  8350000
966  2021-09-03  8.64  8.710  8.565  8.670      8.670  6300000

[967 rows x 7 columns]
tolistdate: 0      2017-08-21
1      2017-08-22
2      2017-08-23
3      2017-08-24
4      2017-08-25
          ...
962    2021-08-30
963    2021-08-31
964    2021-09-01
965    2021-09-02
966    2021-09-03
Name: Date, Length: 967, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BBCP_ended_2021-09-25  2017-08-21          8.67   1.82  15.25       1.343

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.163     4.506     5.849     7.192     8.535     9.878    11.221

  markup_80 markup_90 markup_100
0    12.564    13.907      15.25
                   stock  start_date current_price minall maxall each_markup  \
0  BBCP_ended_2021-09-25  2017-08-21          8.67   1.82  15.25       1.343

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.163     4.506     5.849     7.192     8.535     9.878    11.221

  markup_80 markup_90 markup_100
0    12.564    13.907      15.25
./ticker_data/ticker_data_2021-09-25 - Copy/BBGI_ended_2021-09-25.csv
            Date     Open     High     Low    Close  Adj Close   Volume
0     2000-02-11  15.0000  15.5000  13.875  14.1250   9.626338  7089100
1     2000-02-14  14.1250  14.1250  13.375  13.5000   9.200395   846200
2     2000-02-15  13.5000  13.5625  13.000  13.1250   8.944827   602500
3     2000-02-16  13.1250  14.0000  13.125  13.3125   9.072613   182300
4     2000-02-17  13.3125  14.0000  13.000  13.0000   8.859639   300800
...          ...      ...      ...     ...      ...        ...      ...
5375  2021-08-30   2.6500   2.6900   2.570   2.5700   2.570000  3380000
5376  2021-08-31   2.4800   2.5900   2.480   2.5300   2.530000  3880000
5377  2021-09-01   2.4700   2.5500   2.470   2.5000   2.500000  3930000
5378  2021-09-02   2.5700   2.6100   2.540   2.5700   2.570000  2450000
5379  2021-09-03   2.5700   2.6100   2.490   2.5800   2.580000  5070000

[5380 rows x 7 columns]
tolistdate: 0       2000-02-11
1       2000-02-14
2       2000-02-15
3       2000-02-16
4       2000-02-17
           ...
5375    2021-08-30
5376    2021-08-31
5377    2021-09-01
5378    2021-09-02
5379    2021-09-03
Name: Date, Length: 5380, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BBGI_ended_2021-09-25  2000-02-11          2.58   0.71  19.34       1.863

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.573     4.436     6.299     8.162    10.025    11.888    13.751

  markup_80 markup_90 markup_100
0    15.614    17.477      19.34
                   stock  start_date current_price minall maxall each_markup  \
0  BBGI_ended_2021-09-25  2000-02-11          2.58   0.71  19.34       1.863

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.573     4.436     6.299     8.162    10.025    11.888    13.751

  markup_80 markup_90 markup_100
0    15.614    17.477      19.34
./ticker_data/ticker_data_2021-09-25 - Copy/BBIG_ended_2021-09-25.csv
           Date  Open   High   Low  Close  Adj Close       Volume
0    2020-05-13  2.10   2.14  1.98   2.13       2.13       113000
1    2020-05-14  2.07   2.68  2.01   2.43       2.43       943100
2    2020-05-15  2.41   2.60  2.25   2.41       2.41       217000
3    2020-05-18  2.38   2.52  2.35   2.44       2.44       152300
4    2020-05-19  2.42   2.51  2.34   2.35       2.35        91400
..          ...   ...    ...   ...    ...        ...          ...
327  2021-08-30  9.10  10.00  6.48   7.06       7.06  33066970000
328  2021-08-31  6.90   8.34  5.51   8.15       8.15  18587060000
329  2021-09-01  7.89  11.90  7.31   9.42       9.42  31829500000
330  2021-09-02  9.13   9.53  7.90   7.99       7.99  10813740000
331  2021-09-03  7.80   8.68  6.87   7.98       7.98  12700870000

[332 rows x 7 columns]
tolistdate: 0      2020-05-13
1      2020-05-14
2      2020-05-15
3      2020-05-18
4      2020-05-19
          ...
327    2021-08-30
328    2021-08-31
329    2021-09-01
330    2021-09-02
331    2021-09-03
Name: Date, Length: 332, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BBIG_ended_2021-09-25  2020-05-13          7.98   1.11   11.9       1.079

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.189     3.268     4.347     5.426     6.505     7.584     8.663

  markup_80 markup_90 markup_100
0     9.742    10.821       11.9
                   stock  start_date current_price minall maxall each_markup  \
0  BBIG_ended_2021-09-25  2020-05-13          7.98   1.11   11.9       1.079

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.189     3.268     4.347     5.426     6.505     7.584     8.663

  markup_80 markup_90 markup_100
0     9.742    10.821       11.9
./ticker_data/ticker_data_2021-09-25 - Copy/BBIO_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-06-27  30.750000  31.200001  25.360001  27.549999  27.549999
1    2019-06-28  27.900000  28.000000  25.549999  26.969999  26.969999
2    2019-07-01  27.420000  27.865000  26.090000  27.370001  27.370001
3    2019-07-02  27.260000  27.549999  25.500000  27.040001  27.040001
4    2019-07-03  27.059999  29.100000  27.059999  28.610001  28.610001
..          ...        ...        ...        ...        ...        ...
547  2021-08-30  50.790001  51.639999  48.240002  48.590000  48.590000
548  2021-08-31  48.590000  50.320000  48.590000  50.110001  50.110001
549  2021-09-01  50.040001  51.380001  49.860001  50.639999  50.639999
550  2021-09-02  51.020000  51.310001  49.840000  51.180000  51.180000
551  2021-09-03  51.110001  52.060001  51.095001  51.619999  51.619999

       Volume
0     4986100
1      865500
2      324600
3      595500
4     2097800
..        ...
547  49710000
548  87200000
549  39950000
550  53610000
551  77920000

[552 rows x 7 columns]
tolistdate: 0      2019-06-27
1      2019-06-28
2      2019-07-01
3      2019-07-02
4      2019-07-03
          ...
547    2021-08-30
548    2021-08-31
549    2021-09-01
550    2021-09-02
551    2021-09-03
Name: Date, Length: 552, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BBIO_ended_2021-09-25  2019-06-27         51.62  14.23   73.5       5.927

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    20.157    26.084    32.011    37.938    43.865    49.792    55.719

  markup_80 markup_90 markup_100
0    61.646    67.573       73.5
                   stock  start_date current_price minall maxall each_markup  \
0  BBIO_ended_2021-09-25  2019-06-27         51.62  14.23   73.5       5.927

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    20.157    26.084    32.011    37.938    43.865    49.792    55.719

  markup_80 markup_90 markup_100
0    61.646    67.573       73.5
./ticker_data/ticker_data_2021-09-25 - Copy/BBI_ended_2021-09-25.csv
            Date      Open      High        Low      Close  Adj Close  Volume
0     1999-12-31  1977.500  2108.750  1960.0000  2095.6250  2095.6250    1370
1     2000-01-03  2130.625  2174.375  2012.5000  2104.3750  2104.3750    3976
2     2000-01-04  2100.000  2100.000  1855.0000  1876.8750  1876.8750    2441
3     2000-01-05  1911.875  2065.000  1890.0000  1999.3750  1999.3750    1987
4     2000-01-06  1977.500  2030.000  1911.8750  1960.0000  1960.0000     954
...          ...       ...       ...        ...        ...        ...     ...
5464  2021-09-20     0.720     0.750     0.7000     0.7100     0.7100  720900
5465  2021-09-21     0.710     0.740     0.7100     0.7200     0.7200  376000
5466  2021-09-22     0.720     0.740     0.7100     0.7300     0.7300  418700
5467  2021-09-23     0.720     0.740     0.7200     0.7300     0.7300  532600
5468  2021-09-24     0.729     0.745     0.7231     0.7387     0.7387  180290

[5469 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5464    2021-09-20
5465    2021-09-21
5466    2021-09-22
5467    2021-09-23
5468    2021-09-24
Name: Date, Length: 5469, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  BBI_ended_2021-09-25  1999-12-31        0.7387   0.47   5145     514.453

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   514.923   1029.38   1543.83   2058.28   2572.73   3087.19   3601.64

  markup_80 markup_90 markup_100
0   4116.09   4630.55       5145
                  stock  start_date current_price minall maxall each_markup  \
0  BBI_ended_2021-09-25  1999-12-31        0.7387   0.47   5145     514.453

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   514.923   1029.38   1543.83   2058.28   2572.73   3087.19   3601.64

  markup_80 markup_90 markup_100
0   4116.09   4630.55       5145
./ticker_data/ticker_data_2021-09-25 - Copy/BBQ_ended_2021-09-25.csv
            Date      Open      High      Low     Close  Adj Close   Volume
0     1999-12-31   2.03125   2.09375   2.0000   2.03125    2.03125    30500
1     2000-01-03   2.09375   2.25000   2.0625   2.25000    2.25000    36100
2     2000-01-04   2.12500   2.15625   2.0625   2.06250    2.06250    25700
3     2000-01-05   2.12500   2.18750   2.0625   2.12500    2.12500    25500
4     2000-01-06   2.18750   2.25000   2.1875   2.18750    2.18750    14700
...          ...       ...       ...      ...       ...        ...      ...
5449  2021-08-30  14.29000  14.64000  13.9600  14.04000   14.04000  1860000
5450  2021-08-31  14.19000  14.39000  13.3600  13.38000   13.38000  1520000
5451  2021-09-01  13.56000  14.60000  13.4600  14.09000   14.09000  3430000
5452  2021-09-02  14.12000  14.57000  13.9100  13.96000   13.96000   950000
5453  2021-09-03  13.96000  13.96000  13.4000  13.40000   13.40000  3000000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  BBQ_ended_2021-09-25  1999-12-31          13.4   1.51  34.72       3.321

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.831     8.152    11.473    14.794    18.115    21.436    24.757

  markup_80 markup_90 markup_100
0    28.078    31.399      34.72
                  stock  start_date current_price minall maxall each_markup  \
0  BBQ_ended_2021-09-25  1999-12-31          13.4   1.51  34.72       3.321

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.831     8.152    11.473    14.794    18.115    21.436    24.757

  markup_80 markup_90 markup_100
0    28.078    31.399      34.72
./ticker_data/ticker_data_2021-09-25 - Copy/BBSI_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   4.416667   4.416667   4.416667   4.416667   3.305468
1     2000-01-03   4.447917   4.458333   4.250000   4.458333   3.336652
2     2000-01-04   4.083333   4.458333   4.083333   4.166667   3.118366
3     2000-01-05   4.166667   4.166667   4.166667   4.166667   3.118366
4     2000-01-06   4.208333   4.208333   4.208333   4.208333   3.149550
...          ...        ...        ...        ...        ...        ...
5122  2021-08-30  76.779999  76.779999  76.019997  76.370003  76.370003
5123  2021-08-31  76.370003  77.989998  76.370003  77.500000  77.500000
5124  2021-09-01  76.300003  77.250000  76.209999  77.230003  77.230003
5125  2021-09-02  76.959999  78.389999  76.959999  77.870003  77.870003
5126  2021-09-03  77.320000  77.480003  76.010002  77.220001  77.220001

       Volume
0        3900
1        3600
2        6100
3        7200
4        2700
...       ...
5122  1760000
5123  3470000
5124   740000
5125  2120000
5126  1800000

[5127 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5122    2021-08-30
5123    2021-08-31
5124    2021-09-01
5125    2021-09-02
5126    2021-09-03
Name: Date, Length: 5127, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BBSI_ended_2021-09-25  1999-12-31         77.22   1.34  102.2      10.086

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.426    21.512    31.598    41.684     51.77    61.856    71.942

  markup_80 markup_90 markup_100
0    82.028    92.114      102.2
                   stock  start_date current_price minall maxall each_markup  \
0  BBSI_ended_2021-09-25  1999-12-31         77.22   1.34  102.2      10.086

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.426    21.512    31.598    41.684     51.77    61.856    71.942

  markup_80 markup_90 markup_100
0    82.028    92.114      102.2
./ticker_data/ticker_data_2021-09-25 - Copy/BCAB_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-12-16  30.549999  32.439999  27.150000  31.020000  31.020000
1    2020-12-17  31.172001  43.860001  31.160000  35.160000  35.160000
2    2020-12-18  35.310001  37.099998  31.620001  35.000000  35.000000
3    2020-12-21  33.430000  34.389999  31.080000  32.180000  32.180000
4    2020-12-22  32.630001  33.490002  31.000000  33.400002  33.400002
..          ...        ...        ...        ...        ...        ...
175  2021-08-30  41.099998  41.970001  40.044998  40.470001  40.470001
176  2021-08-31  40.619999  41.310001  39.959999  41.090000  41.090000
177  2021-09-01  41.290001  42.279999  40.605000  41.599998  41.599998
178  2021-09-02  41.919998  42.090000  41.599998  41.980000  41.980000
179  2021-09-03  42.070000  42.165001  40.939999  41.119999  41.119999

       Volume
0     4067500
1     1156700
2      686000
3      261600
4      223600
..        ...
175  17130000
176  36160000
177  22190000
178  14420000
179  20810000

[180 rows x 7 columns]
tolistdate: 0      2020-12-16
1      2020-12-17
2      2020-12-18
3      2020-12-21
4      2020-12-22
          ...
175    2021-08-30
176    2021-08-31
177    2021-09-01
178    2021-09-02
179    2021-09-03
Name: Date, Length: 180, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BCAB_ended_2021-09-25  2020-12-16         41.12  27.15  76.63       4.948

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    32.098    37.046    41.994    46.942     51.89    56.838    61.786

  markup_80 markup_90 markup_100
0    66.734    71.682      76.63
                   stock  start_date current_price minall maxall each_markup  \
0  BCAB_ended_2021-09-25  2020-12-16         41.12  27.15  76.63       4.948

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    32.098    37.046    41.994    46.942     51.89    56.838    61.786

  markup_80 markup_90 markup_100
0    66.734    71.682      76.63
./ticker_data/ticker_data_2021-09-25 - Copy/BCACU_ended_2021-09-25.csv
           Date   Open    High    Low   Close  Adj Close   Volume
0    2021-01-29  10.10  10.300  10.10  10.230     10.230  1042100
1    2021-02-01  10.49  10.490  10.18  10.300     10.300   187600
2    2021-02-02  10.30  10.500  10.29  10.300     10.300   122500
3    2021-02-03  10.30  10.470  10.30  10.300     10.300    59400
4    2021-02-04  10.50  10.580  10.37  10.500     10.500     6200
..          ...    ...     ...    ...     ...        ...      ...
146  2021-08-30  10.28  10.280  10.16  10.160     10.160   250000
147  2021-08-31  10.09  10.500  10.09  10.500     10.500   320000
148  2021-09-01  10.13  10.449  10.10  10.290     10.290   180000
149  2021-09-02  10.24  10.454  10.24  10.454     10.454   100000
150  2021-09-03  10.50  10.500  10.50  10.500     10.500    20000

[151 rows x 7 columns]
tolistdate: 0      2021-01-29
1      2021-02-01
2      2021-02-02
3      2021-02-03
4      2021-02-04
          ...
146    2021-08-30
147    2021-08-31
148    2021-09-01
149    2021-09-02
150    2021-09-03

Name: Date, Length: 151, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BCACU_ended_2021-09-25  2021-01-29          10.5   9.76  12.45       0.269

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.029    10.298    10.567    10.836    11.105    11.374    11.643

  markup_80 markup_90 markup_100
0    11.912    12.181      12.45
                    stock  start_date current_price minall maxall each_markup  \
0  BCACU_ended_2021-09-25  2021-01-29          10.5   9.76  12.45       0.269

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.029    10.298    10.567    10.836    11.105    11.374    11.643

  markup_80 markup_90 markup_100
0    11.912    12.181      12.45
./ticker_data/ticker_data_2021-09-25 - Copy/BCACW_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close  Volume
0    2021-02-22  2.660  5.010  2.180  2.620      2.620   18300
1    2021-02-23  2.680  5.460  2.680  3.400      3.400   44000
2    2021-02-24  3.500  4.000  2.840  3.000      3.000   56300
3    2021-02-25  3.300  3.300  2.700  2.840      2.840   10900
4    2021-02-26  2.750  2.910  2.480  2.486      2.486   39500
..          ...    ...    ...    ...    ...        ...     ...
131  2021-08-30  0.690  0.700  0.660  0.660      0.660  780000
132  2021-08-31  0.660  0.671  0.660  0.671      0.671  990000
133  2021-09-01  0.666  0.720  0.665  0.680      0.680  870000
134  2021-09-02  0.685  0.685  0.660  0.660      0.660  220000
135  2021-09-03  0.660  0.790  0.660  0.682      0.682  490000

[136 rows x 7 columns]
tolistdate: 0      2021-02-22
1      2021-02-23
2      2021-02-24
3      2021-02-25
4      2021-02-26
          ...
131    2021-08-30
132    2021-08-31
133    2021-09-01
134    2021-09-02
135    2021-09-03
Name: Date, Length: 136, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BCACW_ended_2021-09-25  2021-02-22         0.682   0.65   5.46       0.481

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.131     1.612     2.093     2.574     3.055     3.536     4.017

  markup_80 markup_90 markup_100
0     4.498     4.979       5.46
                    stock  start_date current_price minall maxall each_markup  \
0  BCACW_ended_2021-09-25  2021-02-22         0.682   0.65   5.46       0.481

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.131     1.612     2.093     2.574     3.055     3.536     4.017

  markup_80 markup_90 markup_100
0     4.498     4.979       5.46
./ticker_data/ticker_data_2021-09-25 - Copy/BCAC_ended_2021-09-25.csv
           Date   Open    High    Low   Close  Adj Close   Volume
0    2021-02-22  10.60  11.070  10.38  10.650     10.650    21400
1    2021-02-23  10.53  10.650   9.77  10.190     10.190    51400
2    2021-02-24  10.35  10.860  10.21  10.700     10.700    61200
3    2021-02-25  10.51  10.840  10.33  10.350     10.350    18300
4    2021-02-26  10.30  10.690  10.11  10.110     10.110    29600
..          ...    ...     ...    ...     ...        ...      ...
131  2021-08-30   9.90   9.930   9.90   9.915      9.915  1140000
132  2021-08-31   9.90   9.905   9.90   9.905      9.905   120000
133  2021-09-01   9.90   9.900   9.85   9.900      9.900  1870000
134  2021-09-02   9.90   9.900   9.85   9.890      9.890  6810000
135  2021-09-03   9.86   9.950   9.86   9.950      9.950  3990000

[136 rows x 7 columns]
tolistdate: 0      2021-02-22
1      2021-02-23
2      2021-02-24
3      2021-02-25
4      2021-02-26
          ...
131    2021-08-30
132    2021-08-31
133    2021-09-01
134    2021-09-02
135    2021-09-03
Name: Date, Length: 136, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BCAC_ended_2021-09-25  2021-02-22          9.95   9.11  11.07       0.196

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.306     9.502     9.698     9.894     10.09    10.286    10.482

  markup_80 markup_90 markup_100
0    10.678    10.874      11.07
                   stock  start_date current_price minall maxall each_markup  \
0  BCAC_ended_2021-09-25  2021-02-22          9.95   9.11  11.07       0.196

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.306     9.502     9.698     9.894     10.09    10.286    10.482

  markup_80 markup_90 markup_100
0    10.678    10.874      11.07
./ticker_data/ticker_data_2021-09-25 - Copy/BCBP_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2003-10-15   9.803637   9.803637   9.803637   9.803637   5.000462
1     2003-10-16   9.803637   9.803637   9.803637   9.803637   5.000462
2     2003-10-23   9.803637   9.890909   9.803637   9.890909   5.044977
3     2003-10-24   9.890909   9.890909   9.890909   9.890909   5.044977
4     2003-10-27   9.803637  10.472727   9.803637   9.832727   5.015300
...          ...        ...        ...        ...        ...        ...
4155  2021-08-30  15.110000  15.110000  14.920000  14.940000  14.940000
4156  2021-08-31  14.900000  14.970000  14.810000  14.870000  14.870000
4157  2021-09-01  14.940000  15.100000  14.770000  15.010000  15.010000
4158  2021-09-02  15.090000  15.090000  14.980000  15.090000  15.090000
4159  2021-09-03  15.100000  15.100000  14.820000  15.050000  15.050000

       Volume
0         300
1           0
2        2100
3        1600
4        4100
...       ...
4155  2650000
4156  4490000
4157  3520000
4158  3780000
4159  3720000

[4160 rows x 7 columns]
tolistdate: 0       2003-10-15
1       2003-10-16
2       2003-10-23
3       2003-10-24
4       2003-10-27
           ...
4155    2021-08-30
4156    2021-08-31
4157    2021-09-01
4158    2021-09-02
4159    2021-09-03
Name: Date, Length: 4160, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BCBP_ended_2021-09-25  2003-10-15         15.05      7  19.49       1.249

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.249     9.498    10.747    11.996    13.245    14.494    15.743

  markup_80 markup_90 markup_100
0    16.992    18.241      19.49
                   stock  start_date current_price minall maxall each_markup  \
0  BCBP_ended_2021-09-25  2003-10-15         15.05      7  19.49       1.249

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.249     9.498    10.747    11.996    13.245    14.494    15.743

  markup_80 markup_90 markup_100
0    16.992    18.241      19.49
./ticker_data/ticker_data_2021-09-25 - Copy/BCDAW_ended_2021-09-25.csv
         Date  Open  High   Low  Close  Adj Close  Volume
0  2021-09-22  1.43  2.01  1.56   2.01       2.01    4915
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BCDAW_ended_2021-09-25  2021-09-22          2.01   1.56   2.01       0.045

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.605      1.65     1.695      1.74     1.785      1.83     1.875

  markup_80 markup_90 markup_100
0      1.92     1.965       2.01
                    stock  start_date current_price minall maxall each_markup  \
0  BCDAW_ended_2021-09-25  2021-09-22          2.01   1.56   2.01       0.045

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.605      1.65     1.695      1.74     1.785      1.83     1.875

  markup_80 markup_90 markup_100
0      1.92     1.965       2.01
./ticker_data/ticker_data_2021-09-25 - Copy/BCDA_ended_2021-09-25.csv
            Date      Open      High      Low     Close  Adj Close   Volume
0     1999-12-31  2632.500  2700.000  2463.75  2598.750   2598.750       56
1     2000-01-03  2598.750  3223.125  2430.00  3105.000   3105.000      107
2     2000-01-04  3189.375  3189.375  2632.50  2632.500   2632.500       58
3     2000-01-05  2700.000  2835.000  2565.00  2700.000   2700.000       28
4     2000-01-06  2598.750  3577.500  2598.75  3223.125   3223.125      186
...          ...       ...       ...      ...       ...        ...      ...
3481  2021-09-20     3.100     3.170     2.90     3.000      3.000    36400
3482  2021-09-21     2.970     3.050     2.90     3.050      3.050    14600
3483  2021-09-22     3.110     3.960     2.91     3.510      3.510  5402900
3484  2021-09-23     3.440     3.670     3.24     3.580      3.580   641200
3485  2021-09-24     3.500     3.500     3.25     3.280      3.280   101368

[3486 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
3481    2021-09-20
3482    2021-09-21
3483    2021-09-22
3484    2021-09-23
3485    2021-09-24
Name: Date, Length: 3486, dtype: object
                   stock  start_date current_price minall   maxall  \
0  BCDA_ended_2021-09-25  1999-12-31          3.28   1.91  5231.25

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     522.934   524.844   1047.78   1570.71   2093.65   2616.58   3139.51

  markup_70 markup_80 markup_90 markup_100
0   3662.45   4185.38   4708.32    5231.25
                   stock  start_date current_price minall   maxall  \
0  BCDA_ended_2021-09-25  1999-12-31          3.28   1.91  5231.25

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     522.934   524.844   1047.78   1570.71   2093.65   2616.58   3139.51

  markup_70 markup_80 markup_90 markup_100
0   3662.45   4185.38   4708.32    5231.25
./ticker_data/ticker_data_2021-09-25 - Copy/BCEL_ended_2021-09-25.csv
           Date       Open    High        Low      Close  Adj Close    Volume
0    2019-06-20  19.900000  20.000  16.260000  18.049999  18.049999   2506900
1    2019-06-21  17.250000  18.000  17.000000  17.070000  17.070000    206100
2    2019-06-24  17.219999  18.230  16.920000  17.525000  17.525000    280700
3    2019-06-25  17.510000  18.100  17.010000  18.100000  18.100000     55100
4    2019-06-26  18.080000  18.528  17.059999  18.260000  18.260000     79500
..          ...        ...     ...        ...        ...        ...       ...
553  2021-08-30   5.890000   6.000   5.660000   5.730000   5.730000  29220000
554  2021-08-31   5.730000   5.920   5.725000   5.870000   5.870000  31150000
555  2021-09-01   5.900000   6.350   5.890000   6.340000   6.340000  37490000
556  2021-09-02   6.320000   6.425   6.140000   6.380000   6.380000  35570000
557  2021-09-03   6.280000   6.340   6.010000   6.120000   6.120000  42340000

[558 rows x 7 columns]
tolistdate: 0      2019-06-20
1      2019-06-21
2      2019-06-24
3      2019-06-25
4      2019-06-26
          ...
553    2021-08-30
554    2021-08-31
555    2021-09-01
556    2021-09-02
557    2021-09-03
Name: Date, Length: 558, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BCEL_ended_2021-09-25  2019-06-20          6.12    4.8  29.35       2.455

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.255      9.71    12.165     14.62    17.075     19.53    21.985

  markup_80 markup_90 markup_100
0     24.44    26.895      29.35
                   stock  start_date current_price minall maxall each_markup  \
0  BCEL_ended_2021-09-25  2019-06-20          6.12    4.8  29.35       2.455

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.255      9.71    12.165     14.62    17.075     19.53    21.985

  markup_80 markup_90 markup_100
0     24.44    26.895      29.35
./ticker_data/ticker_data_2021-09-25 - Copy/BCLI_ended_2021-09-25.csv
            Date  Open  High   Low  Close  Adj Close   Volume
0     2003-10-07  8.25  8.25  8.25   8.25       8.25        0
1     2003-10-08  7.65  7.65  7.65   7.65       7.65      200
2     2003-10-09  8.40  8.40  8.40   8.40       8.40      300
3     2003-10-10  8.40  8.40  8.40   8.40       8.40        0
4     2003-10-14  8.40  9.75  8.40   9.75       9.75     3000
...          ...   ...   ...   ...    ...        ...      ...
4159  2021-08-30  3.51  3.53  3.45   3.46       3.46  5480000
4160  2021-08-31  3.49  3.53  3.44   3.47       3.47  7340000
4161  2021-09-01  3.45  3.58  3.45   3.55       3.55  8860000
4162  2021-09-02  3.54  3.60  3.50   3.54       3.54  7110000
4163  2021-09-03  3.54  3.54  3.44   3.46       3.46  7370000

[4164 rows x 7 columns]
tolistdate: 0       2003-10-07
1       2003-10-08
2       2003-10-09
3       2003-10-10
4       2003-10-14
           ...
4159    2021-08-30
4160    2021-08-31
4161    2021-09-01
4162    2021-09-02
4163    2021-09-03
Name: Date, Length: 4164, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BCLI_ended_2021-09-25  2003-10-07          3.46   0.75   52.5       5.175

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.925      11.1    16.275     21.45    26.625      31.8    36.975

  markup_80 markup_90 markup_100
0     42.15    47.325       52.5
                   stock  start_date current_price minall maxall each_markup  \
0  BCLI_ended_2021-09-25  2003-10-07          3.46   0.75   52.5       5.175

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.925      11.1    16.275     21.45    26.625      31.8    36.975

  markup_80 markup_90 markup_100
0     42.15    47.325       52.5
./ticker_data/ticker_data_2021-09-25 - Copy/BCML_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2005-11-10  12.000000  12.000000  12.000000  12.000000  12.000000
1     2005-11-11  12.000000  12.000000  12.000000  12.000000  12.000000
2     2005-11-18  11.950000  12.300000  11.950000  12.300000  12.300000
3     2005-11-21  12.300000  12.300000  12.300000  12.300000  12.300000
4     2005-11-22  11.750000  11.750000  11.750000  11.750000  11.750000
...          ...        ...        ...        ...        ...        ...
2522  2021-08-30  17.250000  17.250000  17.190001  17.200001  17.200001
2523  2021-08-31  17.400000  17.400000  17.110001  17.309999  17.309999
2524  2021-09-01  17.330000  17.379999  17.240000  17.370001  17.370001
2525  2021-09-02  17.370001  17.490000  17.260000  17.410000  17.410000
2526  2021-09-03  17.500000  17.830000  17.280001  17.280001  17.280001

       Volume
0         200
1           0
2       14000
3           0
4         200
...       ...
2522   130000
2523  1740000
2524   810000
2525  1560000
2526  7250000

[2527 rows x 7 columns]
tolistdate: 0       2005-11-10
1       2005-11-11
2       2005-11-18
3       2005-11-21
4       2005-11-22
           ...
2522    2021-08-30
2523    2021-08-31
2524    2021-09-01
2525    2021-09-02
2526    2021-09-03
Name: Date, Length: 2527, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BCML_ended_2021-09-25  2005-11-10         17.28      6  26.94       2.094

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.094    10.188    12.282    14.376     16.47    18.564    20.658

  markup_80 markup_90 markup_100
0    22.752    24.846      26.94
                   stock  start_date current_price minall maxall each_markup  \
0  BCML_ended_2021-09-25  2005-11-10         17.28      6  26.94       2.094

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.094    10.188    12.282    14.376     16.47    18.564    20.658

  markup_80 markup_90 markup_100
0    22.752    24.846      26.94
./ticker_data/ticker_data_2021-09-25 - Copy/BCOR_ended_2021-09-25.csv
            Date        Open        High     Low       Close   Adj Close  \
0     1999-12-31  538.437500  542.500000  512.50  535.000000  197.742645
1     2000-01-03  565.937500  568.750000  505.00  531.875000  196.587616
2     2000-01-04  512.500000  525.000000  470.00  472.500000  174.641876
3     2000-01-05  469.687500  490.000000  402.50  477.500000  176.489929
4     2000-01-06  465.625000  475.000000  430.00  445.625000  164.708542
...          ...         ...         ...     ...         ...         ...
5449  2021-08-30   16.850000   16.850000   16.42   16.440001   16.440001
5450  2021-08-31   16.490000   16.559999   16.27   16.410000   16.410000
5451  2021-09-01   16.520000   16.610001   16.27   16.530001   16.530001
5452  2021-09-02   15.810000   16.520000   15.81   16.389999   16.389999
5453  2021-09-03   16.469999   16.469999   16.09   16.299999   16.299999

        Volume
0       233100
1       588200
2       418600
3       449400
4       267000
...        ...
5449  12200000
5450  13100000
5451  13520000
5452  12690000
5453  29270000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BCOR_ended_2021-09-25  1999-12-31          16.3    3.7   1385      138.13

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    141.83    279.96    418.09    556.22    694.35    832.48    970.61

  markup_80 markup_90 markup_100

0   1108.74   1246.87       1385
                   stock  start_date current_price minall maxall each_markup  \
0  BCOR_ended_2021-09-25  1999-12-31          16.3    3.7   1385      138.13

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    141.83    279.96    418.09    556.22    694.35    832.48    970.61

  markup_80 markup_90 markup_100
0   1108.74   1246.87       1385
./ticker_data/ticker_data_2021-09-25 - Copy/BCOV_ended_2021-09-25.csv
            Date   Open   High    Low  Close  Adj Close    Volume
0     2012-02-17  14.50  15.76  14.00  14.30      14.30   4350000
1     2012-02-21  14.47  15.15  14.20  15.15      15.15    527700
2     2012-02-22  15.50  15.50  14.51  14.84      14.84    205200
3     2012-02-23  14.57  15.20  14.50  14.95      14.95    102400
4     2012-02-24  15.33  15.33  14.67  15.10      15.10     63500
...          ...    ...    ...    ...    ...        ...       ...
2397  2021-08-30  11.68  11.68  11.40  11.43      11.43  11670000
2398  2021-08-31  11.53  11.53  11.34  11.36      11.36  26590000
2399  2021-09-01  11.36  11.61  11.36  11.49      11.49  19570000
2400  2021-09-02  11.49  11.68  11.44  11.66      11.66  13880000
2401  2021-09-03  11.75  12.12  11.70  11.85      11.85  23180000

[2402 rows x 7 columns]
tolistdate: 0       2012-02-17
1       2012-02-21
2       2012-02-22
3       2012-02-23
4       2012-02-24
           ...
2397    2021-08-30
2398    2021-08-31
2399    2021-09-01
2400    2021-09-02
2401    2021-09-03
Name: Date, Length: 2402, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BCOV_ended_2021-09-25  2012-02-17         11.85    4.7   25.5        2.08

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      6.78      8.86     10.94     13.02      15.1     17.18     19.26

  markup_80 markup_90 markup_100
0     21.34     23.42       25.5
                   stock  start_date current_price minall maxall each_markup  \
0  BCOV_ended_2021-09-25  2012-02-17         11.85    4.7   25.5        2.08

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      6.78      8.86     10.94     13.02      15.1     17.18     19.26

  markup_80 markup_90 markup_100
0     21.34     23.42       25.5
./ticker_data/ticker_data_2021-09-25 - Copy/BCOW_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-01-09   7.910334   7.978724   7.294833   7.294833   7.294833
1    2019-01-10   7.256839   7.674772   7.186170   7.598784   7.598784
2    2019-01-11   7.598784   7.598784   7.487842   7.489362   7.489362
3    2019-01-14   7.591186   7.591186   7.416413   7.522796   7.522796
4    2019-01-15   7.484802   7.621581   7.408814   7.621581   7.621581
..          ...        ...        ...        ...        ...        ...
627  2021-08-30  10.910000  10.970000  10.890000  10.955000  10.955000
628  2021-08-31  10.970000  10.970000  10.940000  10.940000  10.940000
629  2021-09-01  10.970000  10.990000  10.950000  10.950000  10.950000
630  2021-09-02  10.950000  10.960000  10.860000  10.960000  10.960000
631  2021-09-03  10.950000  10.960000  10.910000  10.950000  10.950000

      Volume
0     279500
1     358600
2      30900
3      24200
4      44300
..       ...
627  2940000
628   640000
629   920000
630  2000000
631  1250000

[632 rows x 7 columns]
tolistdate: 0      2019-01-09
1      2019-01-10
2      2019-01-11
3      2019-01-14
4      2019-01-15
          ...
627    2021-08-30
628    2021-08-31
629    2021-09-01
630    2021-09-02
631    2021-09-03
Name: Date, Length: 632, dtype: object
                   stock  start_date current_price  minall  maxall  \
0  BCOW_ended_2021-09-25  2019-01-09         10.95  5.6459  12.652

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0    0.700608    6.3465   7.04711   7.74772   8.44833   9.14894   9.84954

  markup_70 markup_80 markup_90 markup_100
0   10.5502   11.2508   11.9514     12.652
                   stock  start_date current_price  minall  maxall  \
0  BCOW_ended_2021-09-25  2019-01-09         10.95  5.6459  12.652

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0    0.700608    6.3465   7.04711   7.74772   8.44833   9.14894   9.84954

  markup_70 markup_80 markup_90 markup_100
0   10.5502   11.2508   11.9514     12.652
./ticker_data/ticker_data_2021-09-25 - Copy/BCPC_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31    1.580247    1.604938    1.580247    1.580247    1.440514
1     2000-01-03    1.555556    1.604938    1.530864    1.530864    1.395499
2     2000-01-04    1.506173    1.555556    1.481481    1.481481    1.350482
3     2000-01-05    1.456790    1.555556    1.382716    1.506173    1.372991
4     2000-01-06    1.530864    1.530864    1.456790    1.481481    1.350482
...          ...         ...         ...         ...         ...         ...
5446  2021-08-30  138.399994  140.369995  138.000000  139.369995  139.369995
5447  2021-08-31  139.000000  140.779999  138.660004  140.419998  140.419998
5448  2021-09-01  140.759995  141.169998  138.449997  139.919998  139.919998
5449  2021-09-02  140.250000  142.460007  140.250000  142.130005  142.130005
5450  2021-09-03  141.740005  142.250000  140.460007  140.720001  140.720001

        Volume
0        71100
1        46800
2        26200
3       178300
4        48700
...        ...
5446  14650000
5447  14010000
5448   6290000
5449  10910000
5450  11810000

[5451 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5446    2021-08-30
5447    2021-08-31
5448    2021-09-01
5449    2021-09-02
5450    2021-09-03
Name: Date, Length: 5451, dtype: object
                   stock  start_date current_price   minall  maxall  \
0  BCPC_ended_2021-09-25  1999-12-31        140.72  1.38272  142.46

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     14.1077   15.4904   29.5982   43.7059   57.8136   71.9214   86.0291

  markup_70 markup_80 markup_90 markup_100
0   100.137   114.245   128.352     142.46
                   stock  start_date current_price   minall  maxall  \
0  BCPC_ended_2021-09-25  1999-12-31        140.72  1.38272  142.46

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     14.1077   15.4904   29.5982   43.7059   57.8136   71.9214   86.0291

  markup_70 markup_80 markup_90 markup_100
0   100.137   114.245   128.352     142.46
./ticker_data/ticker_data_2021-09-25 - Copy/BCRX_ended_2021-09-25.csv
            Date     Open       High     Low   Close  Adj Close     Volume
0     1999-12-31  28.5625  29.750000  28.500  29.500     29.500      30500
1     2000-01-03  29.6250  29.875000  26.750  28.000     28.000      89800
2     2000-01-04  27.2500  27.375000  26.375  27.000     27.000      96000
3     2000-01-05  27.0625  27.750000  23.500  27.000     27.000     149200
4     2000-01-06  26.3750  29.000000  26.125  28.375     28.375      98800
...          ...      ...        ...     ...     ...        ...        ...
5450  2021-08-30  15.6500  15.940000  15.460  15.700     15.700  142250000
5451  2021-08-31  15.8100  16.280001  15.790  15.920     15.920  145690000
5452  2021-09-01  15.8900  16.200001  15.840  16.150     16.150  154610000
5453  2021-09-02  16.1700  16.219999  15.870  15.910     15.910  130360000
5454  2021-09-03  15.8400  15.900000  15.350  15.660     15.660  150020000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BCRX_ended_2021-09-25  1999-12-31         15.66    0.6  37.25       3.665

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.265      7.93    11.595     15.26    18.925     22.59    26.255

  markup_80 markup_90 markup_100
0     29.92    33.585      37.25
                   stock  start_date current_price minall maxall each_markup  \
0  BCRX_ended_2021-09-25  1999-12-31         15.66    0.6  37.25       3.665

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.265      7.93    11.595     15.26    18.925     22.59    26.255

  markup_80 markup_90 markup_100
0     29.92    33.585      37.25
./ticker_data/ticker_data_2021-09-25 - Copy/BCTG_ended_2021-09-25.csv
           Date   Open    High     Low  Close  Adj Close    Volume
0    2020-09-03   9.88  10.490   9.860  10.23      10.23    970400
1    2020-09-04  10.33  10.600  10.120  10.25      10.25    253400
2    2020-09-08  10.31  10.310  10.160  10.24      10.24     70300
3    2020-09-09  10.25  10.250  10.150  10.20      10.20     53100
4    2020-09-10  10.16  10.280  10.085  10.11      10.11     87300
..          ...    ...     ...     ...    ...        ...       ...
247  2021-08-30  12.72  12.720  11.900  11.92      11.92   9250000
248  2021-08-31  11.72  11.720  11.300  11.64      11.64   8630000
249  2021-09-01  11.52  12.330  11.170  12.01      12.01   6320000
250  2021-09-02  12.00  12.113  11.600  12.00      12.00   6060000
251  2021-09-03  11.89  13.500  11.890  12.93      12.93  38810000

[252 rows x 7 columns]
tolistdate: 0      2020-09-03
1      2020-09-04
2      2020-09-08
3      2020-09-09
4      2020-09-10
          ...
247    2021-08-30
248    2021-08-31
249    2021-09-01
250    2021-09-02
251    2021-09-03
Name: Date, Length: 252, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BCTG_ended_2021-09-25  2020-09-03         12.93    8.9     14        0.51

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.41      9.92     10.43     10.94     11.45     11.96     12.47

  markup_80 markup_90 markup_100
0     12.98     13.49         14
                   stock  start_date current_price minall maxall each_markup  \
0  BCTG_ended_2021-09-25  2020-09-03         12.93    8.9     14        0.51

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.41      9.92     10.43     10.94     11.45     11.96     12.47

  markup_80 markup_90 markup_100
0     12.98     13.49         14
./ticker_data/ticker_data_2021-09-25 - Copy/BCTXW_ended_2021-09-25.csv
         Date   Open  High   Low  Close  Adj Close  Volume
0  2021-09-22  2.095   3.8  2.91   3.46       3.46  813999
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BCTXW_ended_2021-09-25  2021-09-22          3.46   2.91    3.8       0.089

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.999     3.088     3.177     3.266     3.355     3.444     3.533

  markup_80 markup_90 markup_100
0     3.622     3.711        3.8
                    stock  start_date current_price minall maxall each_markup  \
0  BCTXW_ended_2021-09-25  2021-09-22          3.46   2.91    3.8       0.089

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.999     3.088     3.177     3.266     3.355     3.444     3.533

  markup_80 markup_90 markup_100
0     3.622     3.711        3.8
./ticker_data/ticker_data_2021-09-25 - Copy/BCTX_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2012-03-14  156.351791  156.351791  156.351791  156.351791  156.351791
1     2012-03-15  156.351791  156.351791  156.351791  156.351791  156.351791
2     2012-04-03  156.351791  156.351791  156.351791  156.351791  156.351791
3     2012-04-11  156.351791  156.351791  156.351791  156.351791  156.351791
4     2012-04-12  146.579803  146.579803  146.579803  146.579803  146.579803
...          ...         ...         ...         ...         ...         ...
1012  2021-09-20    7.500000    7.680000    7.030000    7.170000    7.170000
1013  2021-09-21    7.260000    7.620000    7.090000    7.510000    7.510000
1014  2021-09-22    7.710000    8.280000    7.380000    8.030000    8.030000
1015  2021-09-23    8.170000    8.530000    8.000000    8.280000    8.280000
1016  2021-09-24    8.200000    9.450000    8.120000    9.080000    9.080000

       Volume
0          57
1           0
2          18
3           5
4           1
...       ...
1012  1795100
1013  2025500
1014  5341600
1015  3195300
1016  6284469

[1017 rows x 7 columns]
tolistdate: 0       2012-03-14
1       2012-03-15
2       2012-04-03
3       2012-04-11
4       2012-04-12
           ...
1012    2021-09-20
1013    2021-09-21
1014    2021-09-22
1015    2021-09-23
1016    2021-09-24
Name: Date, Length: 1017, dtype: object
                   stock  start_date current_price minall   maxall  \
0  BCTX_ended_2021-09-25  2012-03-14          9.08   2.81  156.352

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     15.3542   18.1642   33.5184   48.8725   64.2267   79.5809   94.9351

  markup_70 markup_80 markup_90 markup_100
0   110.289   125.643   140.998    156.352
                   stock  start_date current_price minall   maxall  \
0  BCTX_ended_2021-09-25  2012-03-14          9.08   2.81  156.352

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     15.3542   18.1642   33.5184   48.8725   64.2267   79.5809   94.9351

  markup_70 markup_80 markup_90 markup_100
0   110.289   125.643   140.998    156.352
./ticker_data/ticker_data_2021-09-25 - Copy/BCYC_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-05-23  13.370000  13.750000  11.500000  12.000000  12.000000
1    2019-05-24  12.030000  13.190000  11.870000  13.050000  13.050000
2    2019-05-28  13.150000  13.150000  12.030000  12.280000  12.280000
3    2019-05-29  12.270000  12.750000  12.050000  12.340000  12.340000
4    2019-05-30  12.440000  12.700000  11.510000  11.930000  11.930000
..          ...        ...        ...        ...        ...        ...
571  2021-08-30  33.330002  36.435001  33.009998  35.430000  35.430000
572  2021-08-31  35.049999  37.689999  34.900002  35.700001  35.700001
573  2021-09-01  35.200001  38.509998  35.130001  37.810001  37.810001
574  2021-09-02  37.959999  41.459999  37.959999  40.709999  40.709999
575  2021-09-03  40.259998  41.619999  38.549999  40.000000  40.000000

       Volume
0      988500
1      179600
2       74200
3      128000
4      136400
..        ...
571  15980000
572  21120000
573  52700000
574  48320000
575  15340000

[576 rows x 7 columns]
tolistdate: 0      2019-05-23
1      2019-05-24
2      2019-05-28
3      2019-05-29
4      2019-05-30
          ...
571    2021-08-30
572    2021-08-31
573    2021-09-01
574    2021-09-02
575    2021-09-03
Name: Date, Length: 576, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BCYC_ended_2021-09-25  2019-05-23            40   6.24  41.62       3.538

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.778    13.316    16.854    20.392     23.93    27.468    31.006

  markup_80 markup_90 markup_100
0    34.544    38.082      41.62
                   stock  start_date current_price minall maxall each_markup  \
0  BCYC_ended_2021-09-25  2019-05-23            40   6.24  41.62       3.538

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.778    13.316    16.854    20.392     23.93    27.468    31.006

  markup_80 markup_90 markup_100
0    34.544    38.082      41.62
./ticker_data/ticker_data_2021-09-25 - Copy/BCYPU_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close   Volume
0    2021-01-12  10.15  10.40  10.15  10.40      10.40  2167300
1    2021-01-13  10.40  10.44  10.35  10.40      10.40   117400
2    2021-01-14  10.36  10.64  10.36  10.48      10.48   228000
3    2021-01-15  10.58  10.60  10.36  10.39      10.39   209000
4    2021-01-19  10.38  10.44  10.36  10.36      10.36    38300
..          ...    ...    ...    ...    ...        ...      ...
163  2021-09-15  10.30  10.30  10.26  10.28      10.28    23500
164  2021-09-21  10.28  11.26  10.28  10.33      10.33     5200
165  2021-09-22  11.06  11.49  10.29  10.50      10.50     4300
166  2021-09-23  10.47  10.52  10.41  10.52      10.52     1700
167  2021-09-24  10.60  10.60  10.60  10.60      10.60      200

[168 rows x 7 columns]
tolistdate: 0      2021-01-12
1      2021-01-13
2      2021-01-14
3      2021-01-15
4      2021-01-19
          ...
163    2021-09-15
164    2021-09-21
165    2021-09-22
166    2021-09-23
167    2021-09-24
Name: Date, Length: 168, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BCYPU_ended_2021-09-25  2021-01-12          10.6   9.88  11.49       0.161

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.041    10.202    10.363    10.524    10.685    10.846    11.007

  markup_80 markup_90 markup_100

0    11.168    11.329      11.49
                    stock  start_date current_price minall maxall each_markup  \
0  BCYPU_ended_2021-09-25  2021-01-12          10.6   9.88  11.49       0.161

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.041    10.202    10.363    10.524    10.685    10.846    11.007

  markup_80 markup_90 markup_100
0    11.168    11.329      11.49
./ticker_data/ticker_data_2021-09-25 - Copy/BCYPW_ended_2021-09-25.csv
         Date    Open  High     Low  Close  Adj Close  Volume
0  2021-09-22  0.5601  0.85  0.7201   0.83       0.83  128294
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price  minall maxall  \
0  BCYPW_ended_2021-09-25  2021-09-22          0.83  0.7201   0.85

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.01299   0.73309   0.74608   0.75907   0.77206   0.78505   0.79804

  markup_70 markup_80 markup_90 markup_100
0   0.81103   0.82402   0.83701       0.85
                    stock  start_date current_price  minall maxall  \
0  BCYPW_ended_2021-09-25  2021-09-22          0.83  0.7201   0.85

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.01299   0.73309   0.74608   0.75907   0.77206   0.78505   0.79804

  markup_70 markup_80 markup_90 markup_100
0   0.81103   0.82402   0.83701       0.85
./ticker_data/ticker_data_2021-09-25 - Copy/BCYP_ended_2021-09-25.csv
           Date    Open   High     Low   Close  Adj Close   Volume
0    2021-02-09  10.220  10.23  10.150  10.150     10.150    41500
1    2021-02-10  10.150  10.31  10.060  10.200     10.200   162700
2    2021-02-11  10.210  10.21  10.100  10.135     10.135    23200
3    2021-02-12  10.360  10.45  10.200  10.210     10.210   171200
4    2021-02-16  10.340  10.34  10.210  10.220     10.220     7300
..          ...     ...    ...     ...     ...        ...      ...
138  2021-08-30   9.970   9.97   9.910   9.965      9.965  1340000
139  2021-08-31   9.939   9.97   9.939   9.970      9.970  1850000
140  2021-09-01   9.940   9.97   9.920   9.970      9.970   170000
141  2021-09-02   9.950   9.97   9.945   9.970      9.970   460000
142  2021-09-03   9.980   9.99   9.963   9.990      9.990   360000

[143 rows x 7 columns]
tolistdate: 0      2021-02-09
1      2021-02-10
2      2021-02-11
3      2021-02-12
4      2021-02-16
          ...
138    2021-08-30
139    2021-08-31
140    2021-09-01
141    2021-09-02
142    2021-09-03
Name: Date, Length: 143, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BCYP_ended_2021-09-25  2021-02-09          9.99    9.7  10.75       0.105

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.805      9.91    10.015     10.12    10.225     10.33    10.435

  markup_80 markup_90 markup_100
0     10.54    10.645      10.75
                   stock  start_date current_price minall maxall each_markup  \
0  BCYP_ended_2021-09-25  2021-02-09          9.99    9.7  10.75       0.105

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.805      9.91    10.015     10.12    10.225     10.33    10.435

  markup_80 markup_90 markup_100
0     10.54    10.645      10.75
./ticker_data/ticker_data_2021-09-25 - Copy/BDSI_ended_2021-09-25.csv
            Date  Open  High   Low  Close  Adj Close    Volume
0     2002-07-25  3.80  3.80  3.30   3.30       3.30     19200
1     2002-07-26  3.30  3.50  3.30   3.30       3.30      8300
2     2002-07-29  3.25  3.50  3.25   3.30       3.30      6100
3     2002-07-30  3.30  3.35  3.25   3.25       3.25     15500
4     2002-07-31  3.25  3.25  3.00   3.00       3.00      9500
...          ...   ...   ...   ...    ...        ...       ...
4804  2021-08-30  3.85  3.90  3.74   3.78       3.78  70780000
4805  2021-08-31  3.79  3.87  3.76   3.86       3.86  57710000
4806  2021-09-01  3.84  3.87  3.80   3.83       3.83  45570000
4807  2021-09-02  3.82  3.90  3.81   3.86       3.86  54380000
4808  2021-09-03  3.86  3.88  3.76   3.81       3.81  48630000

[4809 rows x 7 columns]
tolistdate: 0       2002-07-25
1       2002-07-26
2       2002-07-29
3       2002-07-30
4       2002-07-31
           ...
4804    2021-08-30
4805    2021-08-31
4806    2021-09-01
4807    2021-09-02
4808    2021-09-03
Name: Date, Length: 4809, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BDSI_ended_2021-09-25  2002-07-25          3.81   0.77  18.48       1.771

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.541     4.312     6.083     7.854     9.625    11.396    13.167

  markup_80 markup_90 markup_100
0    14.938    16.709      18.48
                   stock  start_date current_price minall maxall each_markup  \
0  BDSI_ended_2021-09-25  2002-07-25          3.81   0.77  18.48       1.771

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.541     4.312     6.083     7.854     9.625    11.396    13.167

  markup_80 markup_90 markup_100
0    14.938    16.709      18.48
./ticker_data/ticker_data_2021-09-25 - Copy/BDSX_ended_2021-09-25.csv
           Date   Open    High     Low  Close  Adj Close   Volume
0    2020-10-28  13.59  15.000  12.810  12.81      12.81  2617000
1    2020-10-29  12.56  14.600  12.500  12.85      12.85  1130800
2    2020-10-30  13.74  13.740  11.730  12.43      12.43   405200
3    2020-11-02  12.50  13.980  12.004  13.57      13.57   288800
4    2020-11-03  13.60  14.340  13.000  13.83      13.83   247600
..          ...    ...     ...     ...    ...        ...      ...
209  2021-08-30   8.85   9.200   8.800   8.89       8.89  9010000
210  2021-08-31   8.88   9.105   8.693   9.02       9.02  6810000
211  2021-09-01   9.08   9.790   9.060   9.60       9.60  6390000
212  2021-09-02   9.81   9.929   9.550   9.84       9.84  5170000
213  2021-09-03   9.72   9.810   9.260   9.56       9.56  6720000

[214 rows x 7 columns]
tolistdate: 0      2020-10-28
1      2020-10-29
2      2020-10-30
3      2020-11-02
4      2020-11-03
          ...
209    2021-08-30
210    2021-08-31
211    2021-09-01
212    2021-09-02
213    2021-09-03
Name: Date, Length: 214, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BDSX_ended_2021-09-25  2020-10-28          9.56   6.52  31.99       2.547

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.067    11.614    14.161    16.708    19.255    21.802    24.349

  markup_80 markup_90 markup_100
0    26.896    29.443      31.99
                   stock  start_date current_price minall maxall each_markup  \
0  BDSX_ended_2021-09-25  2020-10-28          9.56   6.52  31.99       2.547

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.067    11.614    14.161    16.708    19.255    21.802    24.349

  markup_80 markup_90 markup_100
0    26.896    29.443      31.99
./ticker_data/ticker_data_2021-09-25 - Copy/BDTX_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-01-31  37.040001  37.955002  33.470001  37.500000  37.500000
1    2020-02-03  37.349998  39.900002  36.110001  38.000000  38.000000
2    2020-02-04  37.500000  41.790001  37.070000  39.299999  39.299999
3    2020-02-05  39.139999  39.900002  34.500000  37.880001  37.880001
4    2020-02-06  36.990002  39.009998  36.450001  38.740002  38.740002
..          ...        ...        ...        ...        ...        ...
398  2021-08-30   9.970000  10.230000   9.790000   9.880000   9.880000
399  2021-08-31   9.880000  10.230000   9.880000  10.100000  10.100000
400  2021-09-01  10.070000  10.400000   9.800000  10.380000  10.380000
401  2021-09-02  10.400000  10.450000   9.991000  10.090000  10.090000
402  2021-09-03  10.040000  10.200000   9.400000   9.810000   9.810000

       Volume
0      550200
1      601700
2      520100
3      894700
4      282600
..        ...
398  24710000
399  11620000
400  24380000
401  11890000
402  32270000

[403 rows x 7 columns]
tolistdate: 0      2020-01-31
1      2020-02-03
2      2020-02-04
3      2020-02-05
4      2020-02-06
          ...
398    2021-08-30
399    2021-08-31
400    2021-09-01
401    2021-09-02
402    2021-09-03
Name: Date, Length: 403, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BDTX_ended_2021-09-25  2020-01-31          9.81   8.75  46.25        3.75

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      12.5     16.25        20     23.75      27.5     31.25        35

  markup_80 markup_90 markup_100
0     38.75      42.5      46.25
                   stock  start_date current_price minall maxall each_markup  \
0  BDTX_ended_2021-09-25  2020-01-31          9.81   8.75  46.25        3.75

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      12.5     16.25        20     23.75      27.5     31.25        35

  markup_80 markup_90 markup_100
0     38.75      42.5      46.25
./ticker_data/ticker_data_2021-09-25 - Copy/BEAM_ended_2021-09-25.csv
           Date        Open        High         Low       Close   Adj Close  \
0    2020-02-06   24.000000   25.260000   18.549999   18.750000   18.750000
1    2020-02-07   19.190001   21.900000   19.000000   20.620001   20.620001
2    2020-02-10   21.370001   22.150000   21.100000   22.100000   22.100000
3    2020-02-11   22.150000   24.200001   21.500000   24.100000   24.100000
4    2020-02-12   24.400000   27.600000   24.100000   27.600000   27.600000
..          ...         ...         ...         ...         ...         ...
393  2021-08-30  108.014999  108.830002  103.750000  106.889999  106.889999
394  2021-08-31  107.449997  112.000000  106.059998  110.919998  110.919998
395  2021-09-01  110.360001  113.779999  109.099998  112.199997  112.199997
396  2021-09-02  113.199997  114.620003  110.669998  114.070000  114.070000
397  2021-09-03  113.483002  116.500000  110.535004  112.519997  112.519997

       Volume
0     5873300
1     1221500
2      727400
3      764300
4      862100
..        ...
393  64160000
394  84560000
395  64500000
396  76750000
397  64080000

[398 rows x 7 columns]
tolistdate: 0      2020-02-06
1      2020-02-07
2      2020-02-10
3      2020-02-11
4      2020-02-12
          ...
393    2021-08-30
394    2021-08-31
395    2021-09-01
396    2021-09-02
397    2021-09-03
Name: Date, Length: 398, dtype: object
                   stock  start_date current_price minall   maxall  \
0  BEAM_ended_2021-09-25  2020-02-06        112.52     13  138.522

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     12.5522   25.5522   38.1044   50.6566   63.2088    75.761   88.3132

  markup_70 markup_80 markup_90 markup_100
0   100.865   113.418    125.97    138.522
                   stock  start_date current_price minall   maxall  \
0  BEAM_ended_2021-09-25  2020-02-06        112.52     13  138.522

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     12.5522   25.5522   38.1044   50.6566   63.2088    75.761   88.3132

  markup_70 markup_80 markup_90 markup_100
0   100.865   113.418    125.97    138.522
./ticker_data/ticker_data_2021-09-25 - Copy/BECN_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2004-09-23   9.673333  10.926666   9.500000  10.660000  10.660000
1     2004-09-24  10.540000  10.666667  10.433333  10.633333  10.633333
2     2004-09-27  10.533334  10.666667  10.520000  10.533334  10.533334
3     2004-09-28  10.533334  11.000000  10.533334  10.633333  10.633333
4     2004-09-29  10.573334  10.973333  10.573334  10.913333  10.913333
...          ...        ...        ...        ...        ...        ...
4263  2021-08-30  54.599998  54.599998  52.570000  52.660000  52.660000
4264  2021-08-31  52.470001  52.820000  51.110001  51.480000  51.480000
4265  2021-09-01  51.540001  51.759998  50.150002  51.250000  51.250000
4266  2021-09-02  51.549999  52.070000  51.259998  51.900002  51.900002
4267  2021-09-03  51.709999  52.270000  51.009998  52.209999  52.209999

        Volume
0     13321300
1      1075000
2       576000
3      1054300
4      1097500
...        ...
4263  38100000
4264  58010000
4265  29900000
4266  43640000
4267  22080000

[4268 rows x 7 columns]
tolistdate: 0       2004-09-23
1       2004-09-24
2       2004-09-27
3       2004-09-28
4       2004-09-29
           ...
4263    2021-08-30
4264    2021-08-31
4265    2021-09-01
4266    2021-09-02
4267    2021-09-03
Name: Date, Length: 4268, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BECN_ended_2021-09-25  2004-09-23         52.21    6.7  66.47       5.977

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.677    18.654    24.631    30.608    36.585    42.562    48.539

  markup_80 markup_90 markup_100
0    54.516    60.493      66.47
                   stock  start_date current_price minall maxall each_markup  \
0  BECN_ended_2021-09-25  2004-09-23         52.21    6.7  66.47       5.977

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.677    18.654    24.631    30.608    36.585    42.562    48.539

  markup_80 markup_90 markup_100
0    54.516    60.493      66.47
./ticker_data/ticker_data_2021-09-25 - Copy/BEEMW_ended_2021-09-25.csv
         Date       Open   High        Low      Close  Adj Close  Volume
0  2021-09-24  21.610001  23.33  22.790001  22.790001  22.790001    1603
tolistdate: 0    2021-09-24
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BEEMW_ended_2021-09-25  2021-09-24         22.79  22.79  23.33   0.0539999

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    22.844    22.898    22.952    23.006     23.06    23.114    23.168

  markup_80 markup_90 markup_100
0    23.222    23.276      23.33
                    stock  start_date current_price minall maxall each_markup  \
0  BEEMW_ended_2021-09-25  2021-09-24         22.79  22.79  23.33   0.0539999

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    22.844    22.898    22.952    23.006     23.06    23.114    23.168

  markup_80 markup_90 markup_100
0    23.222    23.276      23.33
./ticker_data/ticker_data_2021-09-25 - Copy/BEEM_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-04-16        NaN        NaN        NaN        NaN        NaN
1    2020-03-16   7.000000   7.630000   6.870000   7.000000   7.000000
2    2020-03-17   7.040000   7.860000   6.964000   7.460000   7.460000
3    2020-03-18   7.250000   7.352000   6.120000   6.350000   6.350000
4    2020-03-19   6.440000   7.500000   6.095000   6.910000   6.910000
..          ...        ...        ...        ...        ...        ...
368  2021-08-30  28.959999  29.204000  27.655001  28.719999  28.719999
369  2021-08-31  29.080000  31.549999  28.600000  31.139999  31.139999
370  2021-09-01  31.000000  31.025000  29.273001  29.440001  29.440001
371  2021-09-02  30.219999  31.520000  29.580000  30.120001  30.120001
372  2021-09-03  30.120001  30.540001  28.750000  29.520000  29.520000

         Volume
0           NaN
1      103000.0
2       54800.0
3      127800.0
4       69000.0
..          ...
368  11810000.0
369  24640000.0
370  15010000.0
371  17850000.0
372  11780000.0

[373 rows x 7 columns]
tolistdate: 0      2019-04-16
1      2020-03-16
2      2020-03-17
3      2020-03-18
4      2020-03-19
          ...
368    2021-08-30
369    2021-08-31
370    2021-09-01
371    2021-09-02
372    2021-09-03
Name: Date, Length: 373, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BEEM_ended_2021-09-25  2019-04-16         29.52  6.095   75.9      6.9805

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   13.0755    20.056   27.0365    34.017   40.9975    47.978   54.9585

  markup_80 markup_90 markup_100
0    61.939   68.9195       75.9
                   stock  start_date current_price minall maxall each_markup  \
0  BEEM_ended_2021-09-25  2019-04-16         29.52  6.095   75.9      6.9805

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   13.0755    20.056   27.0365    34.017   40.9975    47.978   54.9585

  markup_80 markup_90 markup_100
0    61.939   68.9195       75.9
./ticker_data/ticker_data_2021-09-25 - Copy/BELFA_ended_2021-09-25.csv
            Date      Open    High      Low    Close  Adj Close  Volume
0     1999-12-31  27.50000  29.000  26.5000  27.8750  22.336342   13300
1     2000-01-03  25.50000  27.250  25.0625  25.6250  20.533401   29300
2     2000-01-04  25.15625  25.250  24.0000  24.4375  19.581844   26800
3     2000-01-05  24.50000  25.125  24.0625  25.1250  20.132751   10300
4     2000-01-06  25.75000  25.750  24.1250  24.2500  19.431606   13200
...          ...       ...     ...      ...      ...        ...     ...
5193  2021-08-27  15.76000  15.760  15.5000  15.5000  15.500000   50000
5194  2021-08-30  15.75000  15.750  15.7200  15.7500  15.750000  210000
5195  2021-08-31  14.90000  15.730  14.9000  15.7300  15.730000  170000
5196  2021-09-01  15.73000  15.730  15.7300  15.7300  15.730000       0
5197  2021-09-03  15.11000  15.120  15.1100  15.1100  15.110000   70000

[5198 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5193    2021-08-27
5194    2021-08-30
5195    2021-08-31
5196    2021-09-01
5197    2021-09-03
Name: Date, Length: 5198, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BELFA_ended_2021-09-25  1999-12-31         15.11   6.08     46       3.992

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.072    14.064    18.056    22.048     26.04    30.032    34.024

  markup_80 markup_90 markup_100

0    38.016    42.008         46
                    stock  start_date current_price minall maxall each_markup  \
0  BELFA_ended_2021-09-25  1999-12-31         15.11   6.08     46       3.992

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.072    14.064    18.056    22.048     26.04    30.032    34.024

  markup_80 markup_90 markup_100
0    38.016    42.008         46
./ticker_data/ticker_data_2021-09-25 - Copy/BELFB_ended_2021-09-25.csv
            Date      Open    High     Low    Close  Adj Close   Volume
0     1999-12-31  22.75000  24.375  22.500  23.9375  18.259785    35900
1     2000-01-03  22.31250  24.500  22.000  22.8750  17.449306    63000
2     2000-01-04  22.62500  22.875  21.625  22.0000  16.781853    46900
3     2000-01-05  22.09375  22.625  21.750  22.3750  17.067896    46600
4     2000-01-06  22.18750  22.500  20.500  21.7500  16.591150    37400
...          ...       ...     ...     ...      ...        ...      ...
5450  2021-08-30  14.28000  14.330  13.860  13.8700  13.870000  6960000
5451  2021-08-31  14.14000  14.190  13.780  14.1200  14.120000  5360000
5452  2021-09-01  14.18000  14.220  13.810  13.8500  13.850000  7110000
5453  2021-09-02  13.94000  14.230  13.660  13.6600  13.660000  7520000
5454  2021-09-03  13.71000  13.860  13.470  13.4700  13.470000  7290000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                    stock  start_date current_price minall   maxall  \
0  BELFB_ended_2021-09-25  1999-12-31         13.47    6.3  44.9375

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     3.86375   10.1638   14.0275   17.8913    21.755   25.6188   29.4825

  markup_70 markup_80 markup_90 markup_100
0   33.3463     37.21   41.0738    44.9375
                    stock  start_date current_price minall   maxall  \
0  BELFB_ended_2021-09-25  1999-12-31         13.47    6.3  44.9375

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     3.86375   10.1638   14.0275   17.8913    21.755   25.6188   29.4825

  markup_70 markup_80 markup_90 markup_100
0   33.3463     37.21   41.0738    44.9375
./ticker_data/ticker_data_2021-09-25 - Copy/BENER_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close  Volume
0    2021-01-28  0.300  0.400  0.300  0.400      0.400  241000
1    2021-01-29  0.400  0.450  0.325  0.325      0.325   44900
2    2021-02-01  0.350  0.450  0.345  0.450      0.450  960000
3    2021-02-02  0.495  0.608  0.450  0.500      0.500  356800
4    2021-02-03  0.500  0.500  0.460  0.488      0.488   87600
..          ...    ...    ...    ...    ...        ...     ...
146  2021-08-30  0.350  0.350  0.350  0.350      0.350       0
147  2021-08-31  0.350  0.350  0.330  0.330      0.330  600000
148  2021-09-01  0.330  0.348  0.330  0.348      0.348   90000
149  2021-09-02  0.338  0.338  0.337  0.337      0.337  100000
150  2021-09-03  0.330  0.330  0.320  0.320      0.320  360000

[151 rows x 7 columns]
tolistdate: 0      2021-01-28
1      2021-01-29
2      2021-02-01
3      2021-02-02
4      2021-02-03
          ...
146    2021-08-30
147    2021-08-31
148    2021-09-01
149    2021-09-02
150    2021-09-03
Name: Date, Length: 151, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BENER_ended_2021-09-25  2021-01-28          0.32   0.25  0.608      0.0358

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    0.2858    0.3216    0.3574    0.3932     0.429    0.4648    0.5006

  markup_80 markup_90 markup_100
0    0.5364    0.5722      0.608
                    stock  start_date current_price minall maxall each_markup  \
0  BENER_ended_2021-09-25  2021-01-28          0.32   0.25  0.608      0.0358

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    0.2858    0.3216    0.3574    0.3932     0.429    0.4648    0.5006

  markup_80 markup_90 markup_100
0    0.5364    0.5722      0.608
./ticker_data/ticker_data_2021-09-25 - Copy/BENEU_ended_2021-09-25.csv
           Date   Open    High    Low   Close  Adj Close   Volume
0    2021-01-05  10.15  10.350  10.15  10.300     10.300  3587900
1    2021-01-06  10.34  10.405  10.30  10.348     10.348   255300
2    2021-01-07  11.00  11.000  10.40  10.500     10.500   169300
3    2021-01-08  10.65  10.650  10.54  10.560     10.560    49600
4    2021-01-11  10.63  10.630  10.55  10.600     10.600    50700
..          ...    ...     ...    ...     ...        ...      ...
148  2021-08-23  10.78  10.780  10.78  10.780     10.780        0
149  2021-08-24  10.78  10.780  10.78  10.780     10.780    10000
150  2021-08-25  10.80  10.800  10.65  10.650     10.650   160000
151  2021-08-26  10.65  10.650  10.65  10.650     10.650        0
152  2021-08-27  10.75  11.000  10.68  10.700     10.700   730000

[153 rows x 7 columns]
tolistdate: 0      2021-01-05
1      2021-01-06
2      2021-01-07
3      2021-01-08
4      2021-01-11
          ...
148    2021-08-23
149    2021-08-24
150    2021-08-25
151    2021-08-26
152    2021-08-27
Name: Date, Length: 153, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BENEU_ended_2021-09-25  2021-01-05          10.7  10.15  11.36       0.121

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.271    10.392    10.513    10.634    10.755    10.876    10.997

  markup_80 markup_90 markup_100
0    11.118    11.239      11.36
                    stock  start_date current_price minall maxall each_markup  \
0  BENEU_ended_2021-09-25  2021-01-05          10.7  10.15  11.36       0.121

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.271    10.392    10.513    10.634    10.755    10.876    10.997

  markup_80 markup_90 markup_100
0    11.118    11.239      11.36
./ticker_data/ticker_data_2021-09-25 - Copy/BENEW_ended_2021-09-25.csv
           Date  Open   High    Low  Close  Adj Close   Volume
0    2021-01-28  0.70  0.700  0.700  0.700      0.700     6500
1    2021-01-29  0.70  0.700  0.492  0.580      0.580   148300
2    2021-02-01  0.57  0.980  0.560  0.889      0.889   881400
3    2021-02-02  0.90  0.900  0.690  0.700      0.700   497700
4    2021-02-03  0.73  0.790  0.730  0.760      0.760   509900
..          ...   ...    ...    ...    ...        ...      ...
147  2021-08-30  0.43  0.430  0.430  0.430      0.430    70000
148  2021-08-31  0.43  0.440  0.430  0.440      0.440   360000
149  2021-09-01  0.41  0.430  0.410  0.425      0.425  3490000
150  2021-09-02  0.42  0.455  0.420  0.450      0.450  2800000
151  2021-09-03  0.45  0.485  0.450  0.474      0.474  1450000

[152 rows x 7 columns]
tolistdate: 0      2021-01-28
1      2021-01-29
2      2021-02-01
3      2021-02-02
4      2021-02-03
          ...
147    2021-08-30
148    2021-08-31
149    2021-09-01
150    2021-09-02
151    2021-09-03
Name: Date, Length: 152, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BENEW_ended_2021-09-25  2021-01-28         0.474  0.361   1.15      0.0789

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    0.4399    0.5188    0.5977    0.6766    0.7555    0.8344    0.9133

  markup_80 markup_90 markup_100
0    0.9922    1.0711       1.15
                    stock  start_date current_price minall maxall each_markup  \
0  BENEW_ended_2021-09-25  2021-01-28         0.474  0.361   1.15      0.0789

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    0.4399    0.5188    0.5977    0.6766    0.7555    0.8344    0.9133

  markup_80 markup_90 markup_100
0    0.9922    1.0711       1.15
./ticker_data/ticker_data_2021-09-25 - Copy/BENE_ended_2021-09-25.csv
           Date   Open    High    Low  Close  Adj Close  Volume
0    2021-01-28  10.05  10.080   9.99  10.05      10.05  301500
1    2021-01-29  10.06  10.350  10.06  10.15      10.15  156700
2    2021-02-01  10.05  10.425  10.05  10.15      10.15   34500
3    2021-02-02  10.15  10.150  10.05  10.14      10.14  311400
4    2021-02-03  10.19  10.250  10.14  10.25      10.25   45000
..          ...    ...     ...    ...    ...        ...     ...
144  2021-08-30  10.05  10.050  10.05  10.05      10.05   20000
145  2021-08-31  10.04  10.050  10.04  10.05      10.05  360000
146  2021-09-01  10.05  10.050  10.05  10.05      10.05       0
147  2021-09-02  10.06  10.070  10.06  10.07      10.07  200000
148  2021-09-03  10.07  10.070  10.07  10.07      10.07       0

[149 rows x 7 columns]
tolistdate: 0      2021-01-28
1      2021-01-29
2      2021-02-01
3      2021-02-02
4      2021-02-03
          ...
144    2021-08-30
145    2021-08-31
146    2021-09-01
147    2021-09-02
148    2021-09-03
Name: Date, Length: 149, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BENE_ended_2021-09-25  2021-01-28         10.07   9.84  10.425      0.0585

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.8985     9.957   10.0155    10.074   10.1325    10.191   10.2495

  markup_80 markup_90 markup_100
0    10.308   10.3665     10.425
                   stock  start_date current_price minall  maxall each_markup  \
0  BENE_ended_2021-09-25  2021-01-28         10.07   9.84  10.425      0.0585

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.8985     9.957   10.0155    10.074   10.1325    10.191   10.2495

  markup_80 markup_90 markup_100
0    10.308   10.3665     10.425
./ticker_data/ticker_data_2021-09-25 - Copy/BFC_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2003-10-15  15.500000  15.500000  15.500000  15.500000  12.602839
1     2003-10-16  15.500000  15.500000  15.500000  15.500000  12.602839
2     2003-10-23  15.500000  15.500000  15.500000  15.500000  12.602839
3     2003-10-27  16.000000  16.000000  15.000000  15.250000  12.399564
4     2003-10-28  15.250000  15.250000  15.250000  15.250000  12.399564
...          ...        ...        ...        ...        ...        ...
2830  2021-08-30  70.919998  71.879997  69.720001  70.650002  70.650002
2831  2021-08-31  71.000000  71.300003  70.400002  71.000000  71.000000
2832  2021-09-01  69.900002  71.349998  69.900002  70.449997  70.449997
2833  2021-09-02  70.360001  70.370003  70.300003  70.370003  70.370003
2834  2021-09-03  70.919998  70.919998  69.720001  69.720001  69.720001

      Volume
0       1300
1          0
2       1500
3       3400
4          0
...      ...
2830  800000
2831  510000
2832  380000
2833  190000
2834  300000

[2835 rows x 7 columns]
tolistdate: 0       2003-10-15
1       2003-10-16
2       2003-10-23
3       2003-10-27
4       2003-10-28
           ...
2830    2021-08-30
2831    2021-08-31
2832    2021-09-01
2833    2021-09-02
2834    2021-09-03
Name: Date, Length: 2835, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  BFC_ended_2021-09-25  2003-10-15         69.72   5.25     77       7.175

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.425      19.6    26.775     33.95    41.125      48.3    55.475

  markup_80 markup_90 markup_100
0     62.65    69.825         77
                  stock  start_date current_price minall maxall each_markup  \
0  BFC_ended_2021-09-25  2003-10-15         69.72   5.25     77       7.175

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.425      19.6    26.775     33.95    41.125      48.3    55.475

  markup_80 markup_90 markup_100
0     62.65    69.825         77
./ticker_data/ticker_data_2021-09-25 - Copy/BFIIW_ended_2021-09-25.csv
         Date  Open  High     Low  Close  Adj Close  Volume
0  2021-09-22  1.61  1.79  1.6701    1.7        1.7   72734
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price  minall maxall  \
0  BFIIW_ended_2021-09-25  2021-09-22           1.7  1.6701   1.79

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.01199   1.68209   1.69408   1.70607   1.71806   1.73005   1.74204

  markup_70 markup_80 markup_90 markup_100
0   1.75403   1.76602   1.77801       1.79
                    stock  start_date current_price  minall maxall  \
0  BFIIW_ended_2021-09-25  2021-09-22           1.7  1.6701   1.79

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.01199   1.68209   1.69408   1.70607   1.71806   1.73005   1.74204

  markup_70 markup_80 markup_90 markup_100
0   1.75403   1.76602   1.77801       1.79
./ticker_data/ticker_data_2021-09-25 - Copy/BFIN_ended_2021-09-25.csv
            Date   Open   High    Low  Close  Adj Close    Volume
0     2005-06-28  13.40  13.60  13.25  13.40   9.743330    324400
1     2005-06-29  13.43  13.54  13.35  13.37   9.721517    451300
2     2005-06-30  13.30  13.40  13.13  13.33   9.692432    826700
3     2005-07-01  13.25  13.41  13.24  13.40   9.743330    363800
4     2005-07-05  13.49  13.49  13.30  13.30   9.670618    222700
...          ...    ...    ...    ...    ...        ...       ...
4070  2021-08-30  11.84  12.15  11.54  11.65  11.650000   4000000
4071  2021-08-31  11.66  11.85  11.54  11.60  11.600000  11800000
4072  2021-09-01  11.54  11.61  11.35  11.52  11.520000   5040000
4073  2021-09-02  11.64  11.68  11.44  11.48  11.480000   6890000
4074  2021-09-03  11.44  11.74  11.32  11.43  11.430000   3450000

[4075 rows x 7 columns]
tolistdate: 0       2005-06-28
1       2005-06-29
2       2005-06-30
3       2005-07-01
4       2005-07-05
           ...
4070    2021-08-30
4071    2021-08-31
4072    2021-09-01
4073    2021-09-02
4074    2021-09-03
Name: Date, Length: 4075, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BFIN_ended_2021-09-25  2005-06-28         11.43   5.25  18.62       1.337

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.587     7.924     9.261    10.598    11.935    13.272    14.609

  markup_80 markup_90 markup_100
0    15.946    17.283      18.62
                   stock  start_date current_price minall maxall each_markup  \
0  BFIN_ended_2021-09-25  2005-06-28         11.43   5.25  18.62       1.337

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.587     7.924     9.261    10.598    11.935    13.272    14.609

  markup_80 markup_90 markup_100
0    15.946    17.283      18.62
./ticker_data/ticker_data_2021-09-25 - Copy/BFI_ended_2021-09-25.csv
           Date  Open   High    Low  Close  Adj Close  Volume
0    2018-03-26  9.68  9.680  9.680  9.680      9.680  362200
1    2018-03-27  9.69  9.750  9.690  9.750      9.750    5100
2    2018-03-28  9.70  9.790  9.684  9.790      9.790   32800
3    2018-03-29  9.69  9.691  9.690  9.691      9.691    1000
4    2018-04-02  9.68  9.680  9.680  9.680      9.680  401000
..          ...   ...    ...    ...    ...        ...     ...
656  2021-09-20  9.21  9.210  8.665  8.900      8.900  389200
657  2021-09-21  9.22  9.250  8.900  9.160      9.160  130700
658  2021-09-22  9.26  9.320  8.830  9.060      9.060  103100
659  2021-09-23  9.12  9.145  8.990  9.000      9.000   99900
660  2021-09-24  8.94  9.100  8.810  9.100      9.100   56450

[661 rows x 7 columns]
tolistdate: 0      2018-03-26
1      2018-03-27
2      2018-03-28
3      2018-03-29
4      2018-04-02
          ...
656    2021-09-20
657    2021-09-21
658    2021-09-22
659    2021-09-23
660    2021-09-24
Name: Date, Length: 661, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  BFI_ended_2021-09-25  2018-03-26           9.1  8.665  19.92      1.1255

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.7905    10.916   12.0415    13.167   14.2925    15.418   16.5435

  markup_80 markup_90 markup_100
0    17.669   18.7945      19.92
                  stock  start_date current_price minall maxall each_markup  \
0  BFI_ended_2021-09-25  2018-03-26           9.1  8.665  19.92      1.1255

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    9.7905    10.916   12.0415    13.167   14.2925    15.418   16.5435

  markup_80 markup_90 markup_100
0    17.669   18.7945      19.92
./ticker_data/ticker_data_2021-09-25 - Copy/BFRA_ended_2021-09-25.csv
           Date    Open    High     Low  Close  Adj Close  Volume
0    2018-02-14  13.000  14.030  11.250  12.18      12.18  549400
1    2018-02-15  12.900  14.010  12.410  12.60      12.60  236300
2    2018-02-16  13.900  14.720  13.750  14.23      14.23  128600
3    2018-02-20  15.040  15.440  15.020  15.25      15.25   92200
4    2018-02-21  15.200  15.385  14.800  15.28      15.28   44000
..          ...     ...     ...     ...    ...        ...     ...
767  2021-09-20   5.595   5.595   5.265   5.38       5.38    1900
768  2021-09-21   5.540   5.540   5.110   5.35       5.35    2200
769  2021-09-22   5.350   5.360   5.350   5.35       5.35    1000
770  2021-09-23   5.490   5.500   5.330   5.47       5.47    1400
771  2021-09-24   5.430   5.610   5.410   5.57       5.57    1117

[772 rows x 7 columns]
tolistdate: 0      2018-02-14
1      2018-02-15
2      2018-02-16
3      2018-02-20
4      2018-02-21
          ...
767    2021-09-20
768    2021-09-21
769    2021-09-22
770    2021-09-23
771    2021-09-24
Name: Date, Length: 772, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BFRA_ended_2021-09-25  2018-02-14          5.57   4.67     55       5.033

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.703    14.736    19.769    24.802    29.835    34.868    39.901

  markup_80 markup_90 markup_100
0    44.934    49.967         55
                   stock  start_date current_price minall maxall each_markup  \
0  BFRA_ended_2021-09-25  2018-02-14          5.57   4.67     55       5.033

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.703    14.736    19.769    24.802    29.835    34.868    39.901

  markup_80 markup_90 markup_100
0    44.934    49.967         55
./ticker_data/ticker_data_2021-09-25 - Copy/BFST_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-04-23  27.000000  27.950001  25.000000  27.000000  25.438601
1    2018-04-24  25.600000  27.510000  25.000000  27.510000  25.919107
2    2018-04-25  27.510000  27.510000  27.510000  27.510000  25.919107
3    2018-04-26  27.500000  27.500000  25.500000  26.500000  24.967520
4    2018-04-27  26.500000  26.500000  26.000000  26.059999  24.552958
..          ...        ...        ...        ...        ...        ...
844  2021-08-30  24.180000  24.180000  23.719999  23.719999  23.719999
845  2021-08-31  23.879999  23.959999  23.549999  23.920000  23.920000
846  2021-09-01  23.750000  24.000000  23.639999  23.870001  23.870001
847  2021-09-02  23.990000  24.059999  23.690001  23.840000  23.840000
848  2021-09-03  23.650000  23.650000  23.459999  23.620001  23.620001

      Volume
0     136000
1     101400
2          0
3      84600
4        500
..       ...
844  2970000
845  2240000
846  2450000
847  2990000
848  1270000

[849 rows x 7 columns]
tolistdate: 0      2018-04-23
1      2018-04-24
2      2018-04-25
3      2018-04-26
4      2018-04-27
          ...
844    2021-08-30
845    2021-08-31
846    2021-09-01
847    2021-09-02
848    2021-09-03
Name: Date, Length: 849, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BFST_ended_2021-09-25  2018-04-23         23.62   9.17  27.95       1.878

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.048    12.926    14.804    16.682     18.56    20.438    22.316

  markup_80 markup_90 markup_100
0    24.194    26.072      27.95
                   stock  start_date current_price minall maxall each_markup  \
0  BFST_ended_2021-09-25  2018-04-23         23.62   9.17  27.95       1.878

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.048    12.926    14.804    16.682     18.56    20.438    22.316

  markup_80 markup_90 markup_100
0    24.194    26.072      27.95
./ticker_data/ticker_data_2021-09-25 - Copy/BGCP_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  26.527330  26.848875  22.668810  22.869776   8.546382
1     2000-01-03  25.361736  26.165594  24.397106  25.562700   9.552720
2     2000-01-04  23.713827  27.170418  23.472670  26.929260  10.063399
3     2000-01-05  27.813505  28.536978  25.723473  26.245981   9.808060
4     2000-01-06  26.245981  27.250803  25.080385  25.120579   9.387502
...          ...        ...        ...        ...        ...        ...
5436  2021-08-30   5.280000   5.300000   5.130000   5.130000   5.130000
5437  2021-08-31   5.160000   5.160000   5.020000   5.150000   5.150000
5438  2021-09-01   5.150000   5.240000   5.120000   5.180000   5.180000
5439  2021-09-02   5.200000   5.250000   5.140000   5.210000   5.210000
5440  2021-09-03   5.210000   5.230000   5.110000   5.160000   5.160000

         Volume
0        428500
1        886900
2        545900
3        685700
4        284000
...         ...
5436  187880000
5437  156820000
5438  142100000
5439  164760000
5440  176820000

[5441 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5436    2021-08-30
5437    2021-08-31
5438    2021-09-01
5439    2021-09-02
5440    2021-09-03
Name: Date, Length: 5441, dtype: object
                   stock  start_date current_price    minall   maxall  \
0  BGCP_ended_2021-09-25  1999-12-31          5.16  0.881029  57.7974

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     5.69164   6.57267   12.2643   17.9559   23.6476   29.3392   35.0309

  markup_70 markup_80 markup_90 markup_100
0   40.7225   46.4141   52.1058    57.7974
                   stock  start_date current_price    minall   maxall  \
0  BGCP_ended_2021-09-25  1999-12-31          5.16  0.881029  57.7974

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     5.69164   6.57267   12.2643   17.9559   23.6476   29.3392   35.0309

  markup_70 markup_80 markup_90 markup_100
0   40.7225   46.4141   52.1058    57.7974
./ticker_data/ticker_data_2021-09-25 - Copy/BGFV_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2002-06-25  13.010000  13.840000  12.900000  13.170000   6.784191
1     2002-06-26  13.100000  13.170000  12.990000  13.060000   6.727529
2     2002-06-27  13.030000  13.350000  13.010000  13.160000   6.779037
3     2002-06-28  13.140000  14.750000  13.000000  14.290000   7.361131
4     2002-07-01  14.270000  14.290000  13.180000  13.510000   6.959334
...          ...        ...        ...        ...        ...        ...
4829  2021-08-30  24.450001  29.180000  23.799999  28.100000  28.100000
4830  2021-08-31  27.870001  27.870001  25.209999  27.799999  27.799999
4831  2021-09-01  28.350000  32.250000  26.379999  32.029999  32.029999
4832  2021-09-02  32.029999  35.450001  29.090000  30.170000  30.170000
4833  2021-09-03  30.200001  31.950001  29.340000  31.610001  31.610001

         Volume
0       4647100
1        535700
2        208900
3        300900
4         83100
...         ...
4829  554120000
4830  281780000
4831  482780000
4832  763530000
4833  207220000

[4834 rows x 7 columns]
tolistdate: 0       2002-06-25
1       2002-06-26
2       2002-06-27
3       2002-06-28
4       2002-07-01
           ...
4829    2021-08-30
4830    2021-08-31
4831    2021-09-01
4832    2021-09-02
4833    2021-09-03
Name: Date, Length: 4834, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BGFV_ended_2021-09-25  2002-06-25         31.61   0.65  37.75        3.71

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      4.36      8.07     11.78     15.49      19.2     22.91     26.62

  markup_80 markup_90 markup_100
0     30.33     34.04      37.75
                   stock  start_date current_price minall maxall each_markup  \
0  BGFV_ended_2021-09-25  2002-06-25         31.61   0.65  37.75        3.71

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      4.36      8.07     11.78     15.49      19.2     22.91     26.62

  markup_80 markup_90 markup_100
0     30.33     34.04      37.75
./ticker_data/ticker_data_2021-09-25 - Copy/BGNE_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2016-02-03   28.969999   29.490000   27.049999   28.320000   28.320000
1     2016-02-04   28.150000   31.400000   27.610001   30.500000   30.500000
2     2016-02-05   31.299999   35.599998   30.629999   33.910000   33.910000
3     2016-02-08   34.000000   34.244999   31.370001   31.520000   31.520000
4     2016-02-09   30.860001   30.860001   27.000000   27.660000   27.660000
...          ...         ...         ...         ...         ...         ...
1402  2021-08-30  290.799988  303.269989  290.010010  301.820007  301.820007
1403  2021-08-31  305.549988  308.339996  294.369995  308.299988  308.299988
1404  2021-09-01  310.529999  328.649994  308.799988  327.260010  327.260010
1405  2021-09-02  330.000000  333.010010  320.609985  333.010010  333.010010
1406  2021-09-03  334.000000  339.089996  329.089996  336.320007  336.320007

        Volume
0      2064800
1       361600
2       376500
3       102700
4       360900
...        ...
1402  43890000
1403  51060000
1404  50840000
1405  29660000
1406  23250000

[1407 rows x 7 columns]
tolistdate: 0       2016-02-03
1       2016-02-04
2       2016-02-05
3       2016-02-08
4       2016-02-09
           ...
1402    2021-08-30
1403    2021-08-31
1404    2021-09-01
1405    2021-09-02
1406    2021-09-03
Name: Date, Length: 1407, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BGNE_ended_2021-09-25  2016-02-03        336.32  22.51  388.97      36.646

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    59.156    95.802   132.448   169.094    205.74   242.386   279.032

  markup_80 markup_90 markup_100
0   315.678   352.324     388.97
                   stock  start_date current_price minall  maxall each_markup  \
0  BGNE_ended_2021-09-25  2016-02-03        336.32  22.51  388.97      36.646

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    59.156    95.802   132.448   169.094    205.74   242.386   279.032

  markup_80 markup_90 markup_100
0   315.678   352.324     388.97
./ticker_data/ticker_data_2021-09-25 - Copy/BHAT_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close    Volume
0    2019-07-26  4.490  6.250  4.107  4.580      4.580   1751100
1    2019-07-29  4.720  4.900  4.200  4.310      4.310    276400
2    2019-07-30  4.270  4.300  3.900  3.970      3.970    162300
3    2019-07-31  3.900  4.240  3.650  3.820      3.820    438500
4    2019-08-01  3.800  4.020  3.690  3.700      3.700    166100
..          ...    ...    ...    ...    ...        ...       ...
528  2021-08-30  0.680  0.680  0.620  0.656      0.656  53810000
529  2021-08-31  0.646  0.655  0.620  0.650      0.650  33940000
530  2021-09-01  0.641  0.670  0.641  0.670      0.670  24390000
531  2021-09-02  0.670  0.690  0.643  0.655      0.655  27200000
532  2021-09-03  0.655  0.690  0.633  0.659      0.659  40450000

[533 rows x 7 columns]
tolistdate: 0      2019-07-26
1      2019-07-29
2      2019-07-30
3      2019-07-31
4      2019-08-01
          ...
528    2021-08-30
529    2021-08-31
530    2021-09-01
531    2021-09-02
532    2021-09-03
Name: Date, Length: 533, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BHAT_ended_2021-09-25  2019-07-26         0.659   0.55   6.25        0.57

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      1.12      1.69      2.26      2.83       3.4      3.97      4.54

  markup_80 markup_90 markup_100
0      5.11      5.68       6.25
                   stock  start_date current_price minall maxall each_markup  \
0  BHAT_ended_2021-09-25  2019-07-26         0.659   0.55   6.25        0.57

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      1.12      1.69      2.26      2.83       3.4      3.97      4.54

  markup_80 markup_90 markup_100
0      5.11      5.68       6.25
./ticker_data/ticker_data_2021-09-25 - Copy/BHFAL_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-09-14  24.920000  25.049999  24.879999  25.000000  21.558222
1    2018-09-17  25.000000  25.049999  24.950001  25.000000  21.558222
2    2018-09-18  24.950001  25.040001  24.900000  24.930000  21.497860
3    2018-09-19  24.990000  24.990000  24.650000  24.799999  21.385754
4    2018-09-20  24.840000  25.000000  24.799999  24.850000  21.428875
..          ...        ...        ...        ...        ...        ...
743  2021-08-30  27.690001  27.889999  27.690001  27.730000  27.730000
744  2021-08-31  27.700001  27.700001  27.330000  27.350000  27.350000
745  2021-09-01  27.719999  27.719999  27.420000  27.650000  27.650000
746  2021-09-02  27.580000  27.750000  27.490000  27.719999  27.719999
747  2021-09-03  27.790001  27.799999  27.540001  27.620001  27.620001

      Volume
0     412200
1     555800
2     254900
3     144800
4     157500
..       ...
743  1170000
744  5120000
745  1090000
746  1810000
747  1060000

[748 rows x 7 columns]
tolistdate: 0      2018-09-14
1      2018-09-17
2      2018-09-18
3      2018-09-19
4      2018-09-20
          ...
743    2021-08-30
744    2021-08-31
745    2021-09-01
746    2021-09-02
747    2021-09-03
Name: Date, Length: 748, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BHFAL_ended_2021-09-25  2018-09-14         27.62  13.81  28.44       1.463

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.273    16.736    18.199    19.662    21.125    22.588    24.051

  markup_80 markup_90 markup_100
0    25.514    26.977      28.44
                    stock  start_date current_price minall maxall each_markup  \
0  BHFAL_ended_2021-09-25  2018-09-14         27.62  13.81  28.44       1.463

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.273    16.736    18.199    19.662    21.125    22.588    24.051

  markup_80 markup_90 markup_100
0    25.514    26.977      28.44
./ticker_data/ticker_data_2021-09-25 - Copy/BHFAN_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-11-11  25.100000  25.260000  25.049999  25.200001  24.421732
1    2020-11-12  25.200001  25.250000  25.150000  25.230000  24.450804
2    2020-11-13  25.190001  25.440001  25.190001  25.299999  24.518642
3    2020-11-16  25.290001  25.450001  25.290001  25.440001  24.654320
4    2020-11-17  25.450001  25.750000  25.350000  25.650000  24.857834
..          ...        ...        ...        ...        ...        ...
199  2021-08-30  26.430000  26.480000  26.384001  26.400000  26.400000
200  2021-08-31  26.440001  26.480000  26.330000  26.330000  26.330000
201  2021-09-01  26.459999  26.620001  26.459999  26.620001  26.620001
202  2021-09-02  26.590000  26.820000  26.590000  26.790001  26.790001
203  2021-09-03  26.770000  26.940001  26.711000  26.940001  26.940001

      Volume
0    1434900
1    1166800
2    1924600
3     524700
4    1022900
..       ...
199  1960000
200  8520000
201  3600000
202  2160000
203   750000

[204 rows x 7 columns]
tolistdate: 0      2020-11-11
1      2020-11-12
2      2020-11-13
3      2020-11-16
4      2020-11-17
          ...
199    2021-08-30
200    2021-08-31
201    2021-09-01
202    2021-09-02
203    2021-09-03
Name: Date, Length: 204, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BHFAN_ended_2021-09-25  2020-11-11         26.94  24.48  27.69       0.321

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    24.801    25.122    25.443    25.764    26.085    26.406    26.727

  markup_80 markup_90 markup_100
0    27.048    27.369      27.69
                    stock  start_date current_price minall maxall each_markup  \
0  BHFAN_ended_2021-09-25  2020-11-11         26.94  24.48  27.69       0.321

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    24.801    25.122    25.443    25.764    26.085    26.406    26.727

  markup_80 markup_90 markup_100
0    27.048    27.369      27.69
./ticker_data/ticker_data_2021-09-25 - Copy/BHFAO_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-05-19  24.700001  24.770000  24.610001  24.650000  23.024445
1    2020-05-20  24.750000  24.760000  24.670000  24.730000  23.099167
2    2020-05-21  24.750000  24.980000  24.709999  24.889999  23.248615
3    2020-05-22  24.900000  25.040001  24.850000  25.000000  23.351364
4    2020-05-26  25.070000  25.400000  25.041000  25.360001  23.687624
..          ...        ...        ...        ...        ...        ...
322  2021-08-30  28.490000  28.490000  28.424999  28.490000  28.490000
323  2021-08-31  28.450001  28.650000  28.389999  28.510000  28.510000
324  2021-09-01  28.590000  28.709999  28.511000  28.709999  28.709999
325  2021-09-02  28.730000  28.900000  28.673000  28.840000  28.840000
326  2021-09-03  28.870001  28.870001  28.652000  28.830000  28.830000

      Volume
0    2359200
1    1120900
2     274800
3     317300
4    1335600
..       ...
322  1290000
323  3690000
324  1490000
325  2430000
326  1340000

[327 rows x 7 columns]
tolistdate: 0      2020-05-19
1      2020-05-20
2      2020-05-21
3      2020-05-22
4      2020-05-26
          ...
322    2021-08-30
323    2021-08-31
324    2021-09-01
325    2021-09-02
326    2021-09-03
Name: Date, Length: 327, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BHFAO_ended_2021-09-25  2020-05-19         28.83  24.34  29.34         0.5

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     24.84     25.34     25.84     26.34     26.84     27.34     27.84

  markup_80 markup_90 markup_100
0     28.34     28.84      29.34
                    stock  start_date current_price minall maxall each_markup  \
0  BHFAO_ended_2021-09-25  2020-05-19         28.83  24.34  29.34         0.5

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     24.84     25.34     25.84     26.34     26.84     27.34     27.84

  markup_80 markup_90 markup_100
0     28.34     28.84      29.34
./ticker_data/ticker_data_2021-09-25 - Copy/BHFAP_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-03-18  24.750000  24.750000  24.750000  24.750000  21.546579
1    2019-03-19  24.990000  25.100000  24.950001  25.059999  21.816456
2    2019-03-20  25.090000  25.200001  25.030001  25.170000  21.912220
3    2019-03-21  25.090000  25.350000  25.090000  25.299999  22.025393
4    2019-03-22  25.209999  25.450001  25.200001  25.250000  21.981863
..          ...        ...        ...        ...        ...        ...
618  2021-08-30  27.760000  27.840000  27.650000  27.840000  27.840000
619  2021-08-31  27.612000  27.870001  27.612000  27.709999  27.709999
620  2021-09-01  27.820000  27.959999  27.738001  27.879999  27.879999
621  2021-09-02  28.000000  28.021000  27.860001  27.860001  27.860001
622  2021-09-03  27.780001  27.889999  27.690001  27.830000  27.830000

      Volume
0    1290500
1    1880800
2    1193000
3     952400
4     609800
..       ...
618  1310000
619  3860000
620  1840000
621  1560000
622   870000

[623 rows x 7 columns]
tolistdate: 0      2019-03-18
1      2019-03-19
2      2019-03-20
3      2019-03-21
4      2019-03-22
          ...
618    2021-08-30
619    2021-08-31
620    2021-09-01
621    2021-09-02
622    2021-09-03
Name: Date, Length: 623, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BHFAP_ended_2021-09-25  2019-03-18         27.83  13.01   29.4       1.639

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    14.649    16.288    17.927    19.566    21.205    22.844    24.483

  markup_80 markup_90 markup_100

0    26.122    27.761       29.4
                    stock  start_date current_price minall maxall each_markup  \
0  BHFAP_ended_2021-09-25  2019-03-18         27.83  13.01   29.4       1.639

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    14.649    16.288    17.927    19.566    21.205    22.844    24.483

  markup_80 markup_90 markup_100
0    26.122    27.761       29.4
./ticker_data/ticker_data_2021-09-25 - Copy/BHF_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2017-07-17  75.000000  75.000000  70.000000  70.000000  70.000000
1     2017-07-18  70.500000  72.000000  69.919998  70.000000  70.000000
2     2017-07-19  67.919998  69.510002  67.800003  68.949997  68.949997
3     2017-07-20  69.749001  70.000000  69.000000  69.000000  69.000000
4     2017-07-21  70.000000  70.000000  68.559998  68.922997  68.922997
...          ...        ...        ...        ...        ...        ...
1037  2021-08-30  49.049999  49.049999  48.020000  48.259998  48.259998
1038  2021-08-31  48.369999  49.209999  48.270000  48.959999  48.959999
1039  2021-09-01  48.570000  49.540001  48.330002  49.060001  49.060001
1040  2021-09-02  48.669998  49.330002  48.419998  48.740002  48.740002
1041  2021-09-03  48.880001  49.189999  48.380001  48.650002  48.650002

        Volume
0        34000
1        35700
2         1800
3        28400
4         1600
...        ...
1037  38270000
1038  53370000
1039  47970000
1040  43580000
1041  39740000

[1042 rows x 7 columns]
tolistdate: 0       2017-07-17
1       2017-07-18
2       2017-07-19
3       2017-07-20
4       2017-07-21
           ...
1037    2021-08-30
1038    2021-08-31
1039    2021-09-01
1040    2021-09-02
1041    2021-09-03
Name: Date, Length: 1042, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  BHF_ended_2021-09-25  2017-07-17         48.65  12.05     75       6.295

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    18.345     24.64    30.935     37.23    43.525     49.82    56.115

  markup_80 markup_90 markup_100
0     62.41    68.705         75
                  stock  start_date current_price minall maxall each_markup  \
0  BHF_ended_2021-09-25  2017-07-17         48.65  12.05     75       6.295

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    18.345     24.64    30.935     37.23    43.525     49.82    56.115

  markup_80 markup_90 markup_100
0     62.41    68.705         75
./ticker_data/ticker_data_2021-09-25 - Copy/BHSEU_ended_2021-09-25.csv
           Date    Open    High     Low   Close  Adj Close   Volume
0    2020-10-30   9.850  10.130   9.800   9.880      9.880  3014400
1    2020-11-02   9.813   9.830   9.800   9.800      9.800   645200
2    2020-11-03   9.790   9.870   9.790   9.810      9.810    50100
3    2020-11-04   9.865   9.943   9.800   9.860      9.860    29500
4    2020-11-05   9.920   9.920   9.860   9.860      9.860      900
..          ...     ...     ...     ...     ...        ...      ...
128  2021-07-22  10.263  10.263  10.263  10.263     10.263      500
129  2021-07-23  10.409  10.409  10.409  10.409     10.409      300
130  2021-07-26  10.409  10.409  10.409  10.409     10.409        0
131  2021-08-03  10.170  10.230  10.170  10.230     10.230     1000
132  2021-08-04  10.230  10.230  10.230  10.230     10.230        0

[133 rows x 7 columns]
tolistdate: 0      2020-10-30
1      2020-11-02
2      2020-11-03
3      2020-11-04
4      2020-11-05
          ...
128    2021-07-22
129    2021-07-23
130    2021-07-26
131    2021-08-03
132    2021-08-04
Name: Date, Length: 133, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BHSEU_ended_2021-09-25  2020-10-30         10.23   9.79  12.24       0.245

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.035     10.28    10.525     10.77    11.015     11.26    11.505

  markup_80 markup_90 markup_100
0     11.75    11.995      12.24
                    stock  start_date current_price minall maxall each_markup  \
0  BHSEU_ended_2021-09-25  2020-10-30         10.23   9.79  12.24       0.245

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.035     10.28    10.525     10.77    11.015     11.26    11.505

  markup_80 markup_90 markup_100
0     11.75    11.995      12.24
./ticker_data/ticker_data_2021-09-25 - Copy/BHSEW_ended_2021-09-25.csv
         Date   Open    High     Low   Close  Adj Close  Volume
0  2021-09-22  0.345  0.3414  0.2999  0.3299     0.3299   54211
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price  minall  maxall  \
0  BHSEW_ended_2021-09-25  2021-09-22        0.3299  0.2999  0.3414

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00415   0.30405    0.3082   0.31235    0.3165   0.32065    0.3248

  markup_70 markup_80 markup_90 markup_100
0   0.32895    0.3331   0.33725     0.3414
                    stock  start_date current_price  minall  maxall  \
0  BHSEW_ended_2021-09-25  2021-09-22        0.3299  0.2999  0.3414

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00415   0.30405    0.3082   0.31235    0.3165   0.32065    0.3248

  markup_70 markup_80 markup_90 markup_100
0   0.32895    0.3331   0.33725     0.3414
./ticker_data/ticker_data_2021-09-25 - Copy/BHSE_ended_2021-09-25.csv
           Date  Open    High    Low  Close  Adj Close   Volume
0    2020-12-17  9.90  10.010  9.890  9.900      9.900    10500
1    2020-12-18  9.86   9.900  9.850  9.900      9.900     5100
2    2020-12-21  9.85  10.150  9.800  9.900      9.900   105500
3    2020-12-22  9.90   9.900  9.900  9.900      9.900        0
4    2020-12-23  9.90   9.918  9.900  9.918      9.918     3900
..          ...   ...     ...    ...    ...        ...      ...
172  2021-08-27  9.87   9.900  9.840  9.900      9.900  8210000
173  2021-08-31  9.88   9.910  9.880  9.900      9.900  5530000
174  2021-09-01  9.90   9.900  9.895  9.895      9.895    40000
175  2021-09-02  9.88   9.920  9.880  9.910      9.910  2620000
176  2021-09-03  9.91   9.910  9.910  9.910      9.910        0

[177 rows x 7 columns]
tolistdate: 0      2020-12-17
1      2020-12-18
2      2020-12-21
3      2020-12-22
4      2020-12-23
          ...
172    2021-08-27
173    2021-08-31
174    2021-09-01
175    2021-09-02
176    2021-09-03
Name: Date, Length: 177, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BHSE_ended_2021-09-25  2020-12-17          9.91   9.63  11.19       0.156

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.786     9.942    10.098    10.254     10.41    10.566    10.722

  markup_80 markup_90 markup_100
0    10.878    11.034      11.19
                   stock  start_date current_price minall maxall each_markup  \
0  BHSE_ended_2021-09-25  2020-12-17          9.91   9.63  11.19       0.156

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.786     9.942    10.098    10.254     10.41    10.566    10.722

  markup_80 markup_90 markup_100
0    10.878    11.034      11.19
./ticker_data/ticker_data_2021-09-25 - Copy/BHTG_ended_2021-09-25.csv
           Date  Open  High   Low  Close  Adj Close     Volume
0    2018-02-16  4.57  4.57  4.26   4.41       4.41      20400
1    2018-02-20  4.45  4.45  4.20   4.20       4.20      13900
2    2018-02-21  4.20  4.56  4.20   4.40       4.40       8800
3    2018-02-22  4.25  4.44  4.25   4.31       4.31       6000
4    2018-02-23  4.27  4.40  4.25   4.26       4.26       4100
..          ...   ...   ...   ...    ...        ...        ...
889  2021-08-30  1.35  1.39  1.30   1.34       1.34   16060000
890  2021-08-31  1.35  1.42  1.35   1.40       1.40   77760000
891  2021-09-01  1.39  1.50  1.38   1.43       1.43  158760000
892  2021-09-02  1.44  1.50  1.43   1.46       1.46   90280000
893  2021-09-03  1.48  1.50  1.42   1.49       1.49   60330000

[894 rows x 7 columns]
tolistdate: 0      2018-02-16
1      2018-02-20
2      2018-02-21
3      2018-02-22
4      2018-02-23
          ...
889    2021-08-30
890    2021-08-31
891    2021-09-01
892    2021-09-02
893    2021-09-03
Name: Date, Length: 894, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BHTG_ended_2021-09-25  2018-02-16          1.49   1.01   5.76       0.475

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.485      1.96     2.435      2.91     3.385      3.86     4.335

  markup_80 markup_90 markup_100
0      4.81     5.285       5.76
                   stock  start_date current_price minall maxall each_markup  \
0  BHTG_ended_2021-09-25  2018-02-16          1.49   1.01   5.76       0.475

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.485      1.96     2.435      2.91     3.385      3.86     4.335

  markup_80 markup_90 markup_100
0      4.81     5.285       5.76
./ticker_data/ticker_data_2021-09-25 - Copy/BIDU_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2005-08-05    6.600000   15.121000    6.000000   12.254000   12.254000
1     2005-08-08   13.775000   15.398000   11.524000   11.550000   11.550000
2     2005-08-09   12.050000   12.530000    9.569000    9.610000    9.610000
3     2005-08-10   10.100000   10.350000    8.830000    9.175000    9.175000
4     2005-08-11    9.120000   10.050000    9.060000    9.790000    9.790000
...          ...         ...         ...         ...         ...         ...
4044  2021-08-30  154.199997  154.610001  150.160004  153.179993  153.179993
4045  2021-08-31  155.500000  157.250000  153.360001  157.020004  157.020004
4046  2021-09-01  158.880005  166.490005  158.580002  165.179993  165.179993
4047  2021-09-02  165.860001  166.380005  161.240005  162.369995  162.369995
4048  2021-09-03  161.940002  164.679993  161.509995  162.979996  162.979996

         Volume
0     226811000
1     154889000
2      86677000
3      49638000
4      73248000
...         ...
4044  553140000
4045  582410000
4046  932030000
4047  630850000
4048  377500000

[4049 rows x 7 columns]
tolistdate: 0       2005-08-05
1       2005-08-08
2       2005-08-09
3       2005-08-10
4       2005-08-11
           ...
4044    2021-08-30
4045    2021-08-31
4046    2021-09-01
4047    2021-09-02
4048    2021-09-03
Name: Date, Length: 4049, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BIDU_ended_2021-09-25  2005-08-05        162.98  4.444  354.82     35.0376

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   39.4816   74.5192   109.557   144.594   179.632    214.67   249.707

  markup_80 markup_90 markup_100
0   284.745   319.782     354.82
                   stock  start_date current_price minall  maxall each_markup  \
0  BIDU_ended_2021-09-25  2005-08-05        162.98  4.444  354.82     35.0376

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   39.4816   74.5192   109.557   144.594   179.632    214.67   249.707

  markup_80 markup_90 markup_100
0   284.745   319.782     354.82
./ticker_data/ticker_data_2021-09-25 - Copy/BIGC_ended_2021-09-25.csv
           Date       Open        High        Low      Close  Adj Close  \
0    2020-08-05  68.000000   93.989998  67.120003  72.269997  72.269997
1    2020-08-06  83.000000  104.000000  79.260002  93.510002  93.510002
2    2020-08-07  95.599998   98.974998  78.209999  79.000000  79.000000
3    2020-08-10  85.989998   87.000000  70.000000  76.720001  76.720001
4    2020-08-11  74.500000   76.300003  70.765999  72.570000  72.570000
..          ...        ...         ...        ...        ...        ...
283  2021-09-20  55.980000   56.099998  52.861000  54.730000  54.730000
284  2021-09-21  55.349998   55.629002  53.150002  53.950001  53.950001
285  2021-09-22  54.610001   55.360001  53.380001  54.230000  54.230000
286  2021-09-23  54.950001   55.000000  53.769001  54.590000  54.590000
287  2021-09-24  54.000000   54.049999  52.599998  53.619999  53.619999

       Volume
0    11715000
1     8038300
2     3357500
3     2871300
4     1839100
..        ...
283   1947700
284   1189600
285    848000
286    714400
287    477505

[288 rows x 7 columns]
tolistdate: 0      2020-08-05
1      2020-08-06
2      2020-08-07
3      2020-08-10
4      2020-08-11
          ...
283    2021-09-20
284    2021-09-21
285    2021-09-22
286    2021-09-23
287    2021-09-24
Name: Date, Length: 288, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BIGC_ended_2021-09-25  2020-08-05         53.62  42.17  162.5      12.033

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    54.203    66.236    78.269    90.302   102.335   114.368   126.401

  markup_80 markup_90 markup_100
0   138.434   150.467      162.5
                   stock  start_date current_price minall maxall each_markup  \
0  BIGC_ended_2021-09-25  2020-08-05         53.62  42.17  162.5      12.033

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    54.203    66.236    78.269    90.302   102.335   114.368   126.401

  markup_80 markup_90 markup_100
0   138.434   150.467      162.5
./ticker_data/ticker_data_2021-09-25 - Copy/BIIB_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     1999-12-31   31.312500   33.000000   30.416666   32.750000   32.750000
1     2000-01-03   32.791668   32.833332   28.645834   31.083334   31.083334
2     2000-01-04   29.875000   30.916666   28.583334   28.979166   28.979166
3     2000-01-05   28.708334   31.500000   25.000000   31.000000   31.000000
4     2000-01-06   30.166666   32.833332   29.666666   32.375000   32.375000
...          ...         ...         ...         ...         ...         ...
5448  2021-08-30  342.920013  345.779999  340.750000  344.420013  344.420013
5449  2021-08-31  344.619995  345.609985  337.899994  338.910004  338.910004
5450  2021-09-01  340.779999  341.290009  336.440002  338.239990  338.239990
5451  2021-09-02  338.670013  338.690002  327.799988  335.570007  335.570007
5452  2021-09-03  336.799988  337.799988  333.059998  333.600006  333.600006

         Volume
0       1224300
1       2792700
2       2935500
3       3390000
4       2742300
...         ...
5448   55510000
5449   98440000
5450   79150000
5451  122160000
5452   54920000

[5453 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5448    2021-08-30
5449    2021-08-31
5450    2021-09-01
5451    2021-09-02
5452    2021-09-03
Name: Date, Length: 5453, dtype: object
                   stock  start_date current_price   minall  maxall  \
0  BIIB_ended_2021-09-25  1999-12-31         333.6  18.5417  480.18

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     46.1638   64.7055   110.869   157.033   203.197   249.361   295.525

  markup_70 markup_80 markup_90 markup_100
0   341.688   387.852   434.016     480.18
                   stock  start_date current_price   minall  maxall  \
0  BIIB_ended_2021-09-25  1999-12-31         333.6  18.5417  480.18

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     46.1638   64.7055   110.869   157.033   203.197   249.361   295.525

  markup_70 markup_80 markup_90 markup_100
0   341.688   387.852   434.016     480.18
./ticker_data/ticker_data_2021-09-25 - Copy/BILI_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-03-28   9.800000  11.260000   9.620000  11.240000  11.240000
1    2018-03-29  11.500000  11.800000  10.650000  11.000000  11.000000
2    2018-04-02  11.050000  11.500000  10.910000  11.000000  11.000000
3    2018-04-03  11.500000  11.500000  10.791000  10.910000  10.910000
4    2018-04-04  10.750000  11.080000  10.550000  10.970000  10.970000
..          ...        ...        ...        ...        ...        ...
876  2021-09-20  71.070000  73.330002  68.644997  69.779999  69.779999
877  2021-09-21  71.019997  71.480003  69.349998  70.559998  70.559998
878  2021-09-22  71.120003  74.910004  71.120003  73.779999  73.779999
879  2021-09-23  74.559998  74.779999  72.050003  74.339996  74.339996
880  2021-09-24  71.300003  72.190002  70.040001  71.135002  71.135002

       Volume
0    23929600
1     5863900
2     2771000
3     2509600
4     1498200
..        ...
876   4432200
877   2526700
878   3334000
879   2958800
880   1488426

[881 rows x 7 columns]
tolistdate: 0      2018-03-28
1      2018-03-29
2      2018-04-02
3      2018-04-03
4      2018-04-04
          ...
876    2021-09-20
877    2021-09-21
878    2021-09-22
879    2021-09-23
880    2021-09-24
Name: Date, Length: 881, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BILI_ended_2021-09-25  2018-03-28        71.135   9.09  157.66      14.857

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    23.947    38.804    53.661    68.518    83.375    98.232   113.089

  markup_80 markup_90 markup_100
0   127.946   142.803     157.66
                   stock  start_date current_price minall  maxall each_markup  \
0  BILI_ended_2021-09-25  2018-03-28        71.135   9.09  157.66      14.857

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    23.947    38.804    53.661    68.518    83.375    98.232   113.089

  markup_80 markup_90 markup_100
0   127.946   142.803     157.66
./ticker_data/ticker_data_2021-09-25 - Copy/BIMI_ended_2021-09-25.csv
            Date    Open   High    Low   Close  Adj Close  Volume
0     2006-10-18  9.0000  9.000  8.250  8.2500     8.2500     253
1     2006-10-19  8.2500  8.250  7.575  7.5750     7.5750      93
2     2006-10-20  7.5750  7.575  7.575  7.5750     7.5750       0
3     2006-10-23  5.6250  5.625  5.625  5.6250     5.6250      67
4     2006-10-24  5.6250  5.625  5.625  5.6250     5.6250       0
...          ...     ...    ...    ...     ...        ...     ...
3281  2021-09-20  0.7100  0.720  0.670  0.6800     0.6800  178100
3282  2021-09-21  0.6900  0.690  0.660  0.6700     0.6700  163500
3283  2021-09-22  0.6900  0.700  0.640  0.6600     0.6600  273000
3284  2021-09-23  0.6500  0.680  0.650  0.6800     0.6800  207800
3285  2021-09-24  0.6614  0.670  0.657  0.6587     0.6587  149350

[3286 rows x 7 columns]
tolistdate: 0       2006-10-18
1       2006-10-19
2       2006-10-20
3       2006-10-23
4       2006-10-24
           ...
3281    2021-09-20
3282    2021-09-21
3283    2021-09-22
3284    2021-09-23
3285    2021-09-24
Name: Date, Length: 3286, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BIMI_ended_2021-09-25  2006-10-18        0.6587    0.3     50        4.97

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      5.27     10.24     15.21     20.18     25.15     30.12     35.09

  markup_80 markup_90 markup_100
0     40.06     45.03         50
                   stock  start_date current_price minall maxall each_markup  \
0  BIMI_ended_2021-09-25  2006-10-18        0.6587    0.3     50        4.97

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      5.27     10.24     15.21     20.18     25.15     30.12     35.09

  markup_80 markup_90 markup_100
0     40.06     45.03         50
./ticker_data/ticker_data_2021-09-25 - Copy/BIOC_ended_2021-09-25.csv
            Date     Open     High      Low    Close  Adj Close    Volume
0     2014-02-05  9000.00  9018.00  8343.00  8460.00    8460.00       800
1     2014-02-06  8361.00  8415.00  7668.00  7785.00    7785.00       300
2     2014-02-07  7875.00  8010.00  7605.00  8010.00    8010.00         0
3     2014-02-10  8055.00  8100.00  7830.00  8019.00    8019.00         0
4     2014-02-11  7974.00  8010.00  7695.00  7983.00    7983.00         0
...          ...      ...      ...      ...      ...        ...       ...
1901  2021-08-30     3.53     3.62     3.43     3.54       3.54  30420000
1902  2021-08-31     3.56     3.69     3.56     3.62       3.62  29960000
1903  2021-09-01     3.60     3.74     3.60     3.67       3.67  27260000
1904  2021-09-02     3.74     3.82     3.67     3.76       3.76  56250000
1905  2021-09-03     3.79     3.84     3.65     3.66       3.66  46840000

[1906 rows x 7 columns]
tolistdate: 0       2014-02-05
1       2014-02-06
2       2014-02-07
3       2014-02-10
4       2014-02-11
           ...
1901    2021-08-30
1902    2021-08-31
1903    2021-09-01
1904    2021-09-02
1905    2021-09-03
Name: Date, Length: 1906, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BIOC_ended_2021-09-25  2014-02-05          3.66    2.1   9018      901.59

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    903.69   1805.28   2706.87   3608.46   4510.05   5411.64   6313.23

  markup_80 markup_90 markup_100
0   7214.82   8116.41       9018
                   stock  start_date current_price minall maxall each_markup  \
0  BIOC_ended_2021-09-25  2014-02-05          3.66    2.1   9018      901.59

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    903.69   1805.28   2706.87   3608.46   4510.05   5411.64   6313.23

  markup_80 markup_90 markup_100
0   7214.82   8116.41       9018
./ticker_data/ticker_data_2021-09-25 - Copy/BIOL_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  11.087350  12.671257  10.943358  12.383274  12.289190
1     2000-01-03  12.815248  13.247223  12.383274  12.959240  12.860781
2     2000-01-04  13.031236  13.247223  12.527266  12.671257  12.574984
3     2000-01-05  12.671257  12.671257  12.095290  12.527266  12.432088
4     2000-01-06  12.599261  13.103231  12.383274  12.815248  12.717883
...          ...        ...        ...        ...        ...        ...
5449  2021-08-30   0.720000   0.810000   0.720000   0.780000   0.780000
5450  2021-08-31   0.790000   0.820000   0.760000   0.770000   0.770000
5451  2021-09-01   0.780000   0.780000   0.740000   0.740000   0.740000
5452  2021-09-02   0.750000   0.760000   0.740000   0.750000   0.750000
5453  2021-09-03   0.750000   0.750000   0.720000   0.730000   0.730000

         Volume
0         64700
1         96500
2         61000
3         20000
4         46900
...         ...
5449  657410000
5450  274300000
5451  265050000
5452  196310000
5453  180690000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall   maxall  \
0  BIOL_ended_2021-09-25  1999-12-31          0.73   0.21  98.5593

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     9.83493   10.0449   19.8799   29.7148   39.5497   49.3847   59.2196

  markup_70 markup_80 markup_90 markup_100
0   69.0545   78.8895   88.7244    98.5593
                   stock  start_date current_price minall   maxall  \
0  BIOL_ended_2021-09-25  1999-12-31          0.73   0.21  98.5593

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     9.83493   10.0449   19.8799   29.7148   39.5497   49.3847   59.2196

  markup_70 markup_80 markup_90 markup_100
0   69.0545   78.8895   88.7244    98.5593
./ticker_data/ticker_data_2021-09-25 - Copy/BIOTU_ended_2021-09-25.csv
           Date    Open    High     Low   Close  Adj Close   Volume
0    2021-01-26  10.400  10.400  10.300  10.310     10.310  7184900
1    2021-01-27  10.390  10.390  10.230  10.300     10.300   896000
2    2021-01-28  10.270  10.400  10.250  10.300     10.300   344200
3    2021-01-29  10.390  10.390  10.260  10.290     10.290   109300
4    2021-02-01  10.390  10.390  10.310  10.350     10.350   329800
..          ...     ...     ...     ...     ...        ...      ...
147  2021-08-27   9.950   9.990   9.920   9.990      9.990  3570000
148  2021-08-30   9.990   9.990   9.990   9.990      9.990        0
149  2021-09-01   9.880   9.980   9.880   9.980      9.980    70000
150  2021-09-02   9.980   9.980   9.930   9.980      9.980   110000
151  2021-09-03   9.935   9.935   9.935   9.935      9.935    10000

[152 rows x 7 columns]
tolistdate: 0      2021-01-26
1      2021-01-27
2      2021-01-28
3      2021-01-29
4      2021-02-01
          ...
147    2021-08-27
148    2021-08-30
149    2021-09-01
150    2021-09-02
151    2021-09-03
Name: Date, Length: 152, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BIOTU_ended_2021-09-25  2021-01-26         9.935   9.79  10.95       0.116

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.906    10.022    10.138    10.254     10.37    10.486    10.602

  markup_80 markup_90 markup_100
0    10.718    10.834      10.95
                    stock  start_date current_price minall maxall each_markup  \
0  BIOTU_ended_2021-09-25  2021-01-26         9.935   9.79  10.95       0.116

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.906    10.022    10.138    10.254     10.37    10.486    10.602

  markup_80 markup_90 markup_100
0    10.718    10.834      10.95
./ticker_data/ticker_data_2021-09-25 - Copy/BIOTW_ended_2021-09-25.csv
         Date  Open  High   Low  Close  Adj Close  Volume
0  2021-09-22  0.62  0.58  0.56   0.58       0.58   15790
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BIOTW_ended_2021-09-25  2021-09-22          0.58   0.56   0.58       0.002

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.562     0.564     0.566     0.568      0.57     0.572     0.574

  markup_80 markup_90 markup_100
0     0.576     0.578       0.58
                    stock  start_date current_price minall maxall each_markup  \
0  BIOTW_ended_2021-09-25  2021-09-22          0.58   0.56   0.58       0.002

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.562     0.564     0.566     0.568      0.57     0.572     0.574

  markup_80 markup_90 markup_100
0     0.576     0.578       0.58
./ticker_data/ticker_data_2021-09-25 - Copy/BIOT_ended_2021-09-25.csv
           Date   Open   High   Low  Close  Adj Close    Volume
0    2021-03-22  9.640  9.700  9.63  9.700      9.700      5000
1    2021-03-23  9.775  9.775  9.68  9.693      9.693     10300
2    2021-03-24  9.650  9.730  9.65  9.730      9.730      1100
3    2021-03-25  9.950  9.950  9.54  9.560      9.560     11200
4    2021-03-26  9.950  9.950  9.73  9.730      9.730      1000
..          ...    ...    ...   ...    ...        ...       ...
109  2021-08-27  9.691  9.710  9.65  9.690      9.690   6020000
110  2021-08-30  9.720  9.720  9.64  9.660      9.660   4920000
111  2021-08-31  9.650  9.670  9.63  9.660      9.660  32580000
112  2021-09-02  9.650  9.700  9.65  9.700      9.700    240000
113  2021-09-03  9.750  9.750  9.67  9.690      9.690    300000

[114 rows x 7 columns]
tolistdate: 0      2021-03-22
1      2021-03-23
2      2021-03-24
3      2021-03-25
4      2021-03-26
          ...
109    2021-08-27
110    2021-08-30
111    2021-08-31
112    2021-09-02
113    2021-09-03
Name: Date, Length: 114, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BIOT_ended_2021-09-25  2021-03-22          9.69   9.54   9.95       0.041

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.581     9.622     9.663     9.704     9.745     9.786     9.827

  markup_80 markup_90 markup_100
0     9.868     9.909       9.95
                   stock  start_date current_price minall maxall each_markup  \
0  BIOT_ended_2021-09-25  2021-03-22          9.69   9.54   9.95       0.041

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.581     9.622     9.663     9.704     9.745     9.786     9.827

  markup_80 markup_90 markup_100
0     9.868     9.909       9.95
./ticker_data/ticker_data_2021-09-25 - Copy/BIOX_ended_2021-09-25.csv
           Date    Open    High    Low  Close  Adj Close   Volume
0    2018-03-22   9.700   9.700   9.60   9.60       9.60  1102400
1    2018-03-23   9.600   9.640   9.60   9.64       9.64   152000
2    2018-03-26   9.640   9.640   9.64   9.64       9.64        0
3    2018-03-27   9.620   9.620   9.60   9.60       9.60     5400
4    2018-03-28   9.600   9.600   9.60   9.60       9.60        0
..          ...     ...     ...    ...    ...        ...      ...
779  2021-08-30  13.590  13.600  13.30  13.57      13.57  2030000
780  2021-08-31  13.520  14.180  13.30  13.99      13.99  3670000
781  2021-09-01  14.110  14.440  13.70  13.90      13.90  1080000
782  2021-09-02  13.900  14.405  13.79  13.89      13.89  1350000
783  2021-09-03  14.169  14.169  13.86  13.95      13.95  1750000

[784 rows x 7 columns]
tolistdate: 0      2018-03-22
1      2018-03-23
2      2018-03-26
3      2018-03-27
4      2018-03-28
          ...
779    2021-08-30
780    2021-08-31
781    2021-09-01
782    2021-09-02
783    2021-09-03
Name: Date, Length: 784, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BIOX_ended_2021-09-25  2018-03-22         13.95   4.01  17.94       1.393

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.403     6.796     8.189     9.582    10.975    12.368    13.761

  markup_80 markup_90 markup_100
0    15.154    16.547      17.94
                   stock  start_date current_price minall maxall each_markup  \
0  BIOX_ended_2021-09-25  2018-03-22         13.95   4.01  17.94       1.393

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.403     6.796     8.189     9.582    10.975    12.368    13.761

  markup_80 markup_90 markup_100
0    15.154    16.547      17.94
./ticker_data/ticker_data_2021-09-25 - Copy/BIVI_ended_2021-09-25.csv
           Date   Open   High   Low  Close  Adj Close   Volume
0    2020-09-18  10.50  10.99  9.70   9.99       9.99   553500
1    2020-09-21  10.00  10.00  9.31   9.75       9.75   163900
2    2020-09-22   9.60   9.86  9.55   9.55       9.55    32100
3    2020-09-23   9.71   9.85  9.30   9.30       9.30    35400
4    2020-09-24   9.26   9.45  9.00   9.40       9.40    49800
..          ...    ...    ...   ...    ...        ...      ...
237  2021-08-30   7.86   8.20  7.70   8.19       8.19  9500000
238  2021-08-31   8.33   8.33  7.90   7.98       7.98  6730000
239  2021-09-01   7.98   8.27  7.90   7.99       7.99  5150000
240  2021-09-02   8.00   8.14  7.70   7.79       7.79  5680000
241  2021-09-03   7.85   7.97  7.60   7.77       7.77  4580000

[242 rows x 7 columns]
tolistdate: 0      2020-09-18
1      2020-09-21
2      2020-09-22
3      2020-09-23
4      2020-09-24
          ...
237    2021-08-30
238    2021-08-31
239    2021-09-01
240    2021-09-02
241    2021-09-03
Name: Date, Length: 242, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BIVI_ended_2021-09-25  2020-09-18          7.77    7.5  46.098      3.8598

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   11.3598   15.2196   19.0794   22.9392    26.799   30.6588   34.5186

  markup_80 markup_90 markup_100
0   38.3784   42.2382     46.098
                   stock  start_date current_price minall  maxall each_markup  \
0  BIVI_ended_2021-09-25  2020-09-18          7.77    7.5  46.098      3.8598

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   11.3598   15.2196   19.0794   22.9392    26.799   30.6588   34.5186

  markup_80 markup_90 markup_100
0   38.3784   42.2382     46.098
./ticker_data/ticker_data_2021-09-25 - Copy/BJRI_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   1.125000   1.187500   1.125000   1.156250   1.125046
1     2000-01-03   1.187500   1.218750   1.187500   1.218750   1.185859
2     2000-01-04   1.250000   1.250000   1.156250   1.156250   1.125046
3     2000-01-05   1.156250   1.250000   1.156250   1.250000   1.216266
4     2000-01-06   1.125000   1.250000   1.125000   1.250000   1.216266
...          ...        ...        ...        ...        ...        ...
5440  2021-08-30  43.709999  43.770000  42.139999  42.470001  42.470001
5441  2021-08-31  42.200001  42.830002  41.520000  42.759998  42.759998
5442  2021-09-01  42.900002  43.389999  42.150002  42.759998  42.759998
5443  2021-09-02  43.119999  43.570000  41.610001  41.630001  41.630001
5444  2021-09-03  41.639999  41.750000  39.730000  39.790001  39.790001

        Volume
0        50200
1         3400
2        13200
3         1600
4        18500
...        ...
5440  28700000
5441  26280000
5442  19410000
5443  16430000
5444  27270000

[5445 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5440    2021-08-30
5441    2021-08-31
5442    2021-09-01
5443    2021-09-02
5444    2021-09-03
Name: Date, Length: 5445, dtype: object
                   stock  start_date current_price   minall maxall  \
0  BJRI_ended_2021-09-25  1999-12-31         39.79  1.09375   76.5

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     7.54063   8.63438    16.175   23.7156   31.2563   38.7969   46.3375

  markup_70 markup_80 markup_90 markup_100
0   53.8781   61.4188   68.9594       76.5
                   stock  start_date current_price   minall maxall  \
0  BJRI_ended_2021-09-25  1999-12-31         39.79  1.09375   76.5

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     7.54063   8.63438    16.175   23.7156   31.2563   38.7969   46.3375

  markup_70 markup_80 markup_90 markup_100

0   53.8781   61.4188   68.9594       76.5
./ticker_data/ticker_data_2021-09-25 - Copy/BKCC_ended_2021-09-25.csv
            Date   Open   High    Low  Close  Adj Close    Volume
0     2007-06-27  14.90  15.00  14.05  14.55   3.036348         0
1     2007-06-28  14.60  14.87  14.50  14.75   3.078085    531900
2     2007-06-29  14.75  14.95  14.55  14.75   3.078085    396100
3     2007-07-02  14.70  14.86  14.70  14.80   3.088520    142200
4     2007-07-03  14.70  14.95  14.70  14.90   3.109388     91300
...          ...    ...    ...    ...    ...        ...       ...
3568  2021-08-30   4.15   4.16   4.10   4.10   4.100000  20420000
3569  2021-08-31   4.12   4.20   4.10   4.19   4.190000  46190000
3570  2021-09-01   4.20   4.22   4.13   4.15   4.150000  30720000
3571  2021-09-02   4.18   4.18   4.11   4.14   4.140000  22820000
3572  2021-09-03   4.15   4.20   4.12   4.18   4.180000  21520000

[3573 rows x 7 columns]
tolistdate: 0       2007-06-27
1       2007-06-28
2       2007-06-29
3       2007-07-02
4       2007-07-03
           ...
3568    2021-08-30
3569    2021-08-31
3570    2021-09-01
3571    2021-09-02
3572    2021-09-03
Name: Date, Length: 3573, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BKCC_ended_2021-09-25  2007-06-27          4.18   1.47  15.99       1.452

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.922     4.374     5.826     7.278      8.73    10.182    11.634

  markup_80 markup_90 markup_100
0    13.086    14.538      15.99
                   stock  start_date current_price minall maxall each_markup  \
0  BKCC_ended_2021-09-25  2007-06-27          4.18   1.47  15.99       1.452

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.922     4.374     5.826     7.278      8.73    10.182    11.634

  markup_80 markup_90 markup_100
0    13.086    14.538      15.99
./ticker_data/ticker_data_2021-09-25 - Copy/BKEPP_ended_2021-09-25.csv
            Date  Open  High   Low  Close  Adj Close   Volume
0     2012-03-05  9.00  9.00  8.65   8.99   3.542415     7300
1     2012-03-06  8.69  8.69  8.17   8.21   3.235065    49200
2     2012-03-07  8.21  8.61  8.21   8.61   3.392680     2100
3     2012-03-08  8.58  8.61  8.58   8.60   3.388740     5500
4     2012-03-09  8.41  8.60  8.40   8.60   3.388740     1600
...          ...   ...   ...   ...    ...        ...      ...
2338  2021-08-30  8.10  8.15  8.08   8.09   8.090000   740000
2339  2021-08-31  8.09  8.13  8.09   8.13   8.130000   120000
2340  2021-09-01  8.12  8.19  8.10   8.19   8.190000  1410000
2341  2021-09-02  8.22  8.22  8.13   8.13   8.130000   460000
2342  2021-09-03  8.12  8.15  8.11   8.13   8.130000  1190000

[2343 rows x 7 columns]
tolistdate: 0       2012-03-05
1       2012-03-06
2       2012-03-07
3       2012-03-08
4       2012-03-09
           ...
2338    2021-08-30
2339    2021-08-31
2340    2021-09-01
2341    2021-09-02
2342    2021-09-03
Name: Date, Length: 2343, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BKEPP_ended_2021-09-25  2012-03-05          8.13   2.84  11.41       0.857

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.697     4.554     5.411     6.268     7.125     7.982     8.839

  markup_80 markup_90 markup_100
0     9.696    10.553      11.41
                    stock  start_date current_price minall maxall each_markup  \
0  BKEPP_ended_2021-09-25  2012-03-05          8.13   2.84  11.41       0.857

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.697     4.554     5.411     6.268     7.125     7.982     8.839

  markup_80 markup_90 markup_100
0     9.696    10.553      11.41
./ticker_data/ticker_data_2021-09-25 - Copy/BKEP_ended_2021-09-25.csv
            Date  Open  High   Low  Close  Adj Close    Volume
0     2010-12-31  7.60  7.75  7.60   7.75   3.226757     11400
1     2011-01-03  7.75  7.80  7.72   7.80   3.247575      5700
2     2011-01-04  7.75  7.77  7.55   7.75   3.226757      5900
3     2011-01-05  7.75  7.75  7.60   7.60   3.164303     39400
4     2011-01-06  7.60  7.78  7.60   7.75   3.226757    228700
...          ...   ...   ...   ...    ...        ...       ...
2682  2021-08-30  3.26  3.26  3.18   3.21   3.210000  11060000
2683  2021-08-31  3.23  3.28  3.18   3.28   3.280000  12380000
2684  2021-09-01  3.20  3.25  3.19   3.23   3.230000   5920000
2685  2021-09-02  3.23  3.28  3.19   3.26   3.260000   9820000
2686  2021-09-03  3.23  3.24  3.20   3.22   3.220000   4860000

[2687 rows x 7 columns]
tolistdate: 0       2010-12-31
1       2011-01-03
2       2011-01-04
3       2011-01-05
4       2011-01-06
           ...
2682    2021-08-30
2683    2021-08-31
2684    2021-09-01
2685    2021-09-02
2686    2021-09-03
Name: Date, Length: 2687, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BKEP_ended_2021-09-25  2010-12-31          3.22   0.53    9.5       0.897

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.427     2.324     3.221     4.118     5.015     5.912     6.809

  markup_80 markup_90 markup_100
0     7.706     8.603        9.5
                   stock  start_date current_price minall maxall each_markup  \
0  BKEP_ended_2021-09-25  2010-12-31          3.22   0.53    9.5       0.897

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.427     2.324     3.221     4.118     5.015     5.912     6.809

  markup_80 markup_90 markup_100
0     7.706     8.603        9.5
./ticker_data/ticker_data_2021-09-25 - Copy/BKNG_ended_2021-09-25.csv
            Date         Open         High          Low        Close  \
0     1999-12-31   282.375000   296.250000   280.875000   284.250000
1     2000-01-03   315.000000   318.000000   288.000000   307.500000
2     2000-01-04   308.250000   343.500000   307.500000   324.000000
3     2000-01-05   331.500000   385.312500   327.750000   359.625000
4     2000-01-06   368.250000   384.750000   326.250000   345.000000
...          ...          ...          ...          ...          ...
5449  2021-08-30  2300.000000  2306.570068  2270.419922  2277.709961
5450  2021-08-31  2286.020020  2316.080078  2284.139893  2299.669922
5451  2021-09-01  2305.860107  2330.000000  2285.000000  2286.850098
5452  2021-09-02  2304.239990  2326.790039  2282.770020  2300.459961
5453  2021-09-03  2284.280029  2311.739990  2276.500000  2304.449951

        Adj Close    Volume
0      284.250000    410100
1      307.500000    847700
2      324.000000    972700
3      359.625000   1605400
4      345.000000   1175200
...           ...       ...
5449  2277.709961  24490000
5450  2299.669922  38840000
5451  2286.850098  32470000
5452  2300.459961  23180000
5453  2304.449951  19650000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BKNG_ended_2021-09-25  1999-12-31       2304.45    6.3   2516      250.97

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    257.27    508.24    759.21   1010.18   1261.15   1512.12   1763.09

  markup_80 markup_90 markup_100
0   2014.06   2265.03       2516
                   stock  start_date current_price minall maxall each_markup  \
0  BKNG_ended_2021-09-25  1999-12-31       2304.45    6.3   2516      250.97

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    257.27    508.24    759.21   1010.18   1261.15   1512.12   1763.09

  markup_80 markup_90 markup_100
0   2014.06   2265.03       2516
./ticker_data/ticker_data_2021-09-25 - Copy/BKSC_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   7.786353   7.786353   7.786353   7.786353   3.506586
1     2000-01-03   7.513148   7.513148   7.513148   7.513148   3.383547
2     2000-01-04   7.513148   7.513148   7.513148   7.513148   3.383547
3     2000-01-05   7.513148   7.513148   7.513148   7.513148   3.383547
4     2000-01-06   7.513148   7.649751   7.513148   7.649751   3.445067
...          ...        ...        ...        ...        ...        ...
4898  2021-09-20  20.240000  20.440001  19.950001  20.049999  20.049999
4899  2021-09-21  20.200001  20.280001  19.920000  20.160000  20.160000
4900  2021-09-22  20.180000  20.290001  20.000000  20.120001  20.120001
4901  2021-09-23  20.000000  20.389999  20.000000  20.059999  20.059999
4902  2021-09-24  20.190001  20.499901  20.190001  20.480000  20.480000

      Volume
0        183
1       2928
2       1647
3          0
4      13726
...      ...
4898    4500
4899    2600
4900    2800
4901    4000
4902    1876

[4903 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
4898    2021-09-20
4899    2021-09-21
4900    2021-09-22
4901    2021-09-23
4902    2021-09-24
Name: Date, Length: 4903, dtype: object
                   stock  start_date current_price   minall maxall  \
0  BKSC_ended_2021-09-25  1999-12-31         20.48  5.96134  25.65

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     1.96887   7.93021   9.89907   11.8679   13.8368   15.8057   17.7745

  markup_70 markup_80 markup_90 markup_100
0   19.7434   21.7123   23.6811      25.65
                   stock  start_date current_price   minall maxall  \
0  BKSC_ended_2021-09-25  1999-12-31         20.48  5.96134  25.65

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     1.96887   7.93021   9.89907   11.8679   13.8368   15.8057   17.7745

  markup_70 markup_80 markup_90 markup_100
0   19.7434   21.7123   23.6811      25.65
./ticker_data/ticker_data_2021-09-25 - Copy/BKYI_ended_2021-09-25.csv
            Date   Open   High    Low  Close  Adj Close    Volume
0     1999-12-31  54.00  60.00  54.00  60.00      60.00       900
1     2000-01-03  60.00  66.00  60.00  66.00      66.00       200
2     2000-01-04  63.00  63.00  60.00  60.00      60.00       100
3     2000-01-05  60.00  60.00  60.00  60.00      60.00       100
4     2000-01-06  60.00  63.00  57.00  60.00      60.00       500
...          ...    ...    ...    ...    ...        ...       ...
4549  2021-08-30   3.20   3.22   3.11   3.15       3.15   3840000
4550  2021-08-31   3.13   3.24   3.12   3.16       3.16   3060000
4551  2021-09-01   3.15   3.20   3.15   3.16       3.16   1320000
4552  2021-09-02   3.19   3.37   3.16   3.34       3.34  11480000
4553  2021-09-03   3.31   3.34   3.25   3.27       3.27   4130000

[4554 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
4549    2021-08-30
4550    2021-08-31
4551    2021-09-01
4552    2021-09-02
4553    2021-09-03
Name: Date, Length: 4554, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BKYI_ended_2021-09-25  1999-12-31          3.27   2.75    288      28.525

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    31.275      59.8    88.325    116.85   145.375     173.9   202.425

  markup_80 markup_90 markup_100
0    230.95   259.475        288
                   stock  start_date current_price minall maxall each_markup  \
0  BKYI_ended_2021-09-25  1999-12-31          3.27   2.75    288      28.525

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    31.275      59.8    88.325    116.85   145.375     173.9   202.425

  markup_80 markup_90 markup_100
0    230.95   259.475        288
./ticker_data/ticker_data_2021-09-25 - Copy/BLBD_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2014-03-20   9.600000   9.620000   9.600000   9.620000   9.620000
1     2014-03-21   9.500000   9.500000   9.500000   9.500000   9.500000
2     2014-03-24   9.500000   9.500000   9.500000   9.500000   9.500000
3     2014-03-27   9.560000   9.560000   9.560000   9.560000   9.560000
4     2014-03-28   9.560000   9.560000   9.560000   9.560000   9.560000
...          ...        ...        ...        ...        ...        ...
1792  2021-08-30  21.219999  21.540001  20.900000  21.200001  21.200001
1793  2021-08-31  21.160000  21.730000  21.040001  21.650000  21.650000
1794  2021-09-01  21.570000  21.930000  20.840000  20.860001  20.860001
1795  2021-09-02  21.020000  21.156000  20.730000  20.930000  20.930000
1796  2021-09-03  21.049999  21.100000  20.280001  20.320000  20.320000

        Volume
0        10200
1          200
2            0
3          400
4            0
...        ...
1792  16080000
1793   6080000
1794   9930000
1795   5410000
1796   4300000

[1797 rows x 7 columns]
tolistdate: 0       2014-03-20
1       2014-03-21
2       2014-03-24
3       2014-03-27
4       2014-03-28
           ...
1792    2021-08-30
1793    2021-08-31
1794    2021-09-01
1795    2021-09-02
1796    2021-09-03
Name: Date, Length: 1797, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BLBD_ended_2021-09-25  2014-03-20         20.32   7.61   28.9       2.129

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.739    11.868    13.997    16.126    18.255    20.384    22.513

  markup_80 markup_90 markup_100
0    24.642    26.771       28.9
                   stock  start_date current_price minall maxall each_markup  \
0  BLBD_ended_2021-09-25  2014-03-20         20.32   7.61   28.9       2.129

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.739    11.868    13.997    16.126    18.255    20.384    22.513

  markup_80 markup_90 markup_100
0    24.642    26.771       28.9
./ticker_data/ticker_data_2021-09-25 - Copy/BLCM_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2014-12-18  245.600006  273.799988  235.000000  238.800003  238.800003
1     2014-12-19  228.699997  232.000000  197.100006  197.699997  197.699997
2     2014-12-22  202.800003  213.399994  199.699997  201.100006  201.100006
3     2014-12-23  200.500000  201.000000  182.000000  191.199997  191.199997
4     2014-12-24  192.500000  199.149994  188.000000  193.000000  193.000000
...          ...         ...         ...         ...         ...         ...
1684  2021-08-30    3.230000    3.315000    3.050000    3.100000    3.100000
1685  2021-08-31    3.120000    3.140000    3.020000    3.030000    3.030000
1686  2021-09-01    3.474000    4.040000    3.190000    3.540000    3.540000
1687  2021-09-02    3.390000    3.430000    3.255000    3.340000    3.340000
1688  2021-09-03    3.290000    3.310000    3.060000    3.090000    3.090000

          Volume
0         951600
1         222400
2          64900
3          74100
4          13800
...          ...
1684     8330000
1685     5950000
1686  1307910000
1687    64470000
1688    36870000

[1689 rows x 7 columns]
tolistdate: 0       2014-12-18
1       2014-12-19
2       2014-12-22
3       2014-12-23
4       2014-12-24
           ...
1684    2021-08-30
1685    2021-08-31
1686    2021-09-01
1687    2021-09-02
1688    2021-09-03
Name: Date, Length: 1689, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BLCM_ended_2021-09-25  2014-12-18          3.09   2.57  336.3      33.373

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    35.943    69.316   102.689   136.062   169.435   202.808   236.181

  markup_80 markup_90 markup_100
0   269.554   302.927      336.3
                   stock  start_date current_price minall maxall each_markup  \
0  BLCM_ended_2021-09-25  2014-12-18          3.09   2.57  336.3      33.373

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    35.943    69.316   102.689   136.062   169.435   202.808   236.181

  markup_80 markup_90 markup_100
0   269.554   302.927      336.3
./ticker_data/ticker_data_2021-09-25 - Copy/BLCT_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-07-08  20.450001  35.889999  20.030001  23.430000  23.430000
1    2020-07-09  27.969999  28.000000  24.799999  25.990000  25.990000
2    2020-07-10  24.309999  25.264999  23.350000  24.500000  24.500000
3    2020-07-13  23.290001  23.476000  19.820000  19.820000  19.820000
4    2020-07-14  19.209999  19.454000  17.000000  17.530001  17.530001
..          ...        ...        ...        ...        ...        ...
288  2021-08-30   3.320000   3.752000   3.220000   3.600000   3.600000
289  2021-08-31   3.580000   3.850000   3.424000   3.650000   3.650000
290  2021-09-01   3.680000   3.830000   3.680000   3.760000   3.760000
291  2021-09-02   3.760000   3.840000   3.700000   3.760000   3.760000
292  2021-09-03   3.760000   3.765000   3.504000   3.570000   3.570000

       Volume
0     5179500
1     2728300
2      829100
3     1369300
4      678800
..        ...
288  51200000
289  23900000
290   4830000
291   4760000
292   7200000

[293 rows x 7 columns]
tolistdate: 0      2020-07-08
1      2020-07-09
2      2020-07-10
3      2020-07-13
4      2020-07-14
          ...
288    2021-08-30
289    2021-08-31
290    2021-09-01
291    2021-09-02
292    2021-09-03
Name: Date, Length: 293, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BLCT_ended_2021-09-25  2020-07-08          3.57   3.21  35.89       3.268

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.478     9.746    13.014    16.282     19.55    22.818    26.086

  markup_80 markup_90 markup_100
0    29.354    32.622      35.89
                   stock  start_date current_price minall maxall each_markup  \
0  BLCT_ended_2021-09-25  2020-07-08          3.57   3.21  35.89       3.268

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.478     9.746    13.014    16.282     19.55    22.818    26.086

  markup_80 markup_90 markup_100
0    29.354    32.622      35.89
./ticker_data/ticker_data_2021-09-25 - Copy/BLDEW_ended_2021-09-25.csv
         Date  Open  High   Low  Close  Adj Close  Volume
0  2021-09-22  1.66  3.09  2.83   3.09       3.09   62955
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BLDEW_ended_2021-09-25  2021-09-22          3.09   2.83   3.09       0.026

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.856     2.882     2.908     2.934      2.96     2.986     3.012

  markup_80 markup_90 markup_100
0     3.038     3.064       3.09
                    stock  start_date current_price minall maxall each_markup  \
0  BLDEW_ended_2021-09-25  2021-09-22          3.09   2.83   3.09       0.026

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.856     2.882     2.908     2.934      2.96     2.986     3.012

  markup_80 markup_90 markup_100
0     3.038     3.064       3.09
./ticker_data/ticker_data_2021-09-25 - Copy/BLDE_ended_2021-09-25.csv
           Date   Open   High   Low  Close  Adj Close     Volume
0    2020-11-11  9.930  9.930  9.92   9.92       9.92        600
1    2020-11-12  9.920  9.920  9.92   9.92       9.92          0
2    2020-11-13  9.920  9.920  9.92   9.92       9.92        200
3    2020-11-16  9.967  9.967  9.95   9.95       9.95        500
4    2020-11-17  9.969  9.969  9.94   9.94       9.94       1800
..          ...    ...    ...   ...    ...        ...        ...
136  2021-08-30  9.030  9.070  8.36   8.64       8.64   64490000
137  2021-08-31  8.610  8.755  8.33   8.51       8.51   52120000
138  2021-09-01  8.650  8.920  8.52   8.85       8.85   85170000
139  2021-09-02  8.950  9.160  8.77   8.99       8.99  164920000
140  2021-09-03  8.980  9.090  8.76   8.85       8.85   96990000

[141 rows x 7 columns]
tolistdate: 0      2020-11-11
1      2020-11-12
2      2020-11-13
3      2020-11-16
4      2020-11-17
          ...
136    2021-08-30
137    2021-08-31
138    2021-09-01
139    2021-09-02
140    2021-09-03
Name: Date, Length: 141, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BLDE_ended_2021-09-25  2020-11-11          8.85   6.41  16.18       0.977

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.387     8.364     9.341    10.318    11.295    12.272    13.249

  markup_80 markup_90 markup_100
0    14.226    15.203      16.18
                   stock  start_date current_price minall maxall each_markup  \
0  BLDE_ended_2021-09-25  2020-11-11          8.85   6.41  16.18       0.977

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.387     8.364     9.341    10.318    11.295    12.272    13.249

  markup_80 markup_90 markup_100
0    14.226    15.203      16.18
./ticker_data/ticker_data_2021-09-25 - Copy/BLDP_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  27.812500  28.437500  27.625000  28.187500  28.187500
1     2000-01-03  28.750000  34.000000  27.812500  33.250000  33.250000
2     2000-01-04  32.125000  32.250000  29.250000  30.750000  30.750000
3     2000-01-05  31.187500  33.500000  30.750000  32.750000  32.750000
4     2000-01-06  33.625000  34.625000  32.953125  34.625000  34.625000
...          ...        ...        ...        ...        ...        ...
5450  2021-08-30  16.420000  16.639999  15.930000  16.490000  16.490000
5451  2021-08-31  16.510000  17.180000  16.490000  16.799999  16.799999
5452  2021-09-01  16.719999  17.070000  16.559999  16.639999  16.639999
5453  2021-09-02  16.790001  17.170000  16.629999  16.870001  16.870001
5454  2021-09-03  16.950001  16.980000  16.270000  16.400000  16.400000

         Volume
0         66800
1        408200
2        380300
3        376800
4        590700
...         ...
5450  348310000
5451  398760000
5452  280110000
5453  252940000
5454  284930000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price minall   maxall  \
0  BLDP_ended_2021-09-25  1999-12-31          16.4   0.56  144.938

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     14.4377   14.9978   29.4355   43.8733    58.311   72.7488   87.1865

  markup_70 markup_80 markup_90 markup_100
0   101.624   116.062     130.5    144.938
                   stock  start_date current_price minall   maxall  \
0  BLDP_ended_2021-09-25  1999-12-31          16.4   0.56  144.938

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     14.4377   14.9978   29.4355   43.8733    58.311   72.7488   87.1865

  markup_70 markup_80 markup_90 markup_100
0   101.624   116.062     130.5    144.938
./ticker_data/ticker_data_2021-09-25 - Copy/BLDR_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2005-06-28  15.200000  15.990000  15.200000  15.990000  15.990000
1     2005-06-29  16.000000  16.080000  15.800000  16.030001  16.030001
2     2005-06-30  16.000000  16.250000  15.900000  16.200001  16.200001
3     2005-07-01  16.299999  16.400000  16.139999  16.240000  16.240000
4     2005-07-05  16.250000  16.250000  16.000000  16.049999  16.049999
...          ...        ...        ...        ...        ...        ...
4070  2021-08-30  53.560001  53.959999  52.639999  53.419998  53.419998
4071  2021-08-31  53.450001  53.900002  52.820000  53.290001  53.290001
4072  2021-09-01  53.540001  54.070000  52.590000  53.590000  53.590000
4073  2021-09-02  54.169998  55.169998  54.160000  54.610001  54.610001
4074  2021-09-03  54.220001  54.730000  53.720001  54.490002  54.490002

         Volume
0        521800
1        230300
2        479400
3        148000
4        336500
...         ...
4070  182220000
4071  204690000
4072  219070000
4073  183700000
4074  136000000

[4075 rows x 7 columns]
tolistdate: 0       2005-06-28
1       2005-06-29
2       2005-06-30
3       2005-07-01
4       2005-07-05
           ...
4070    2021-08-30
4071    2021-08-31
4072    2021-09-01
4073    2021-09-02
4074    2021-09-03
Name: Date, Length: 4075, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BLDR_ended_2021-09-25  2005-06-28         54.49   0.82  55.17       5.435

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.255     11.69    17.125     22.56    27.995     33.43    38.865

  markup_80 markup_90 markup_100
0      44.3    49.735      55.17
                   stock  start_date current_price minall maxall each_markup  \
0  BLDR_ended_2021-09-25  2005-06-28         54.49   0.82  55.17       5.435

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.255     11.69    17.125     22.56    27.995     33.43    38.865

  markup_80 markup_90 markup_100
0      44.3    49.735      55.17
./ticker_data/ticker_data_2021-09-25 - Copy/BLFS_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  10.937500  10.937500   9.843750  10.937500  10.937500
1     2000-01-03  10.937500  13.125000  10.937500  13.125000  13.125000
2     2000-01-04  13.125000  13.125000  12.031250  12.031250  12.031250
3     2000-01-05  14.218750  14.218750  13.125000  14.218750  14.218750
4     2000-01-06  14.218750  14.218750  13.125000  13.125000  13.125000
...          ...        ...        ...        ...        ...        ...
3858  2021-08-30  55.590000  59.410000  55.560001  58.320000  58.320000
3859  2021-08-31  58.700001  59.650002  58.029999  58.360001  58.360001
3860  2021-09-01  58.209999  60.669998  57.259998  60.500000  60.500000
3861  2021-09-02  60.230000  60.230000  55.139999  55.860001  55.860001
3862  2021-09-03  55.889999  55.889999  52.590000  53.259998  53.259998

        Volume
0         4500
1         1800
2          100
3          300
4          200
...        ...
3858  60640000
3859  51460000
3860  48850000
3861  82470000
3862  66620000

[3863 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
3858    2021-08-30
3859    2021-08-31
3860    2021-09-01
3861    2021-09-02
3862    2021-09-03
Name: Date, Length: 3863, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BLFS_ended_2021-09-25  1999-12-31         53.26   0.14   66.5       6.636

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.776    13.412    20.048    26.684     33.32    39.956    46.592

  markup_80 markup_90 markup_100
0    53.228    59.864       66.5
                   stock  start_date current_price minall maxall each_markup  \
0  BLFS_ended_2021-09-25  1999-12-31         53.26   0.14   66.5       6.636

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.776    13.412    20.048    26.684     33.32    39.956    46.592

  markup_80 markup_90 markup_100
0    53.228    59.864       66.5
./ticker_data/ticker_data_2021-09-25 - Copy/BLIN_ended_2021-09-25.csv
            Date     Open     High      Low    Close  Adj Close      Volume
0     2007-06-29  6250.00  6312.50  5375.00  6250.00    6250.00         800
1     2007-07-02  6250.00  6362.50  5662.50  6250.00    6250.00         100
2     2007-07-03  6250.00  6312.50  6075.00  6312.50    6312.50           0
3     2007-07-05  6312.50  6312.50  5975.00  6125.00    6125.00           0
4     2007-07-06  6087.50  6250.00  6087.50  6250.00    6250.00           0
...          ...      ...      ...      ...      ...        ...         ...
3327  2021-08-30     5.81     6.08     5.12     5.47       5.47  1349470000
3328  2021-08-31     5.34     5.34     4.93     5.15       5.15   128890000
3329  2021-09-01     5.05     5.30     4.93     5.06       5.06    64600000
3330  2021-09-02     5.11     5.18     5.00     5.06       5.06    48790000
3331  2021-09-03     5.00     5.05     4.62     4.68       4.68    77630000

[3332 rows x 7 columns]
tolistdate: 0       2007-06-29
1       2007-07-02
2       2007-07-03
3       2007-07-05
4       2007-07-06
           ...
3327    2021-08-30
3328    2021-08-31
3329    2021-09-01
3330    2021-09-02
3331    2021-09-03
Name: Date, Length: 3332, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BLIN_ended_2021-09-25  2007-06-29          4.68   0.53  6362.5     636.197

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   636.727   1272.92   1909.12   2545.32   3181.51   3817.71   4453.91

  markup_80 markup_90 markup_100
0   5090.11    5726.3     6362.5
                   stock  start_date current_price minall  maxall each_markup  \
0  BLIN_ended_2021-09-25  2007-06-29          4.68   0.53  6362.5     636.197

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   636.727   1272.92   1909.12   2545.32   3181.51   3817.71   4453.91

  markup_80 markup_90 markup_100
0   5090.11    5726.3     6362.5
./ticker_data/ticker_data_2021-09-25 - Copy/BLI_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-07-17  51.005001  68.379997  50.259998  65.449997  65.449997
1    2020-07-20  58.509998  64.500000  58.509998  62.099998  62.099998
2    2020-07-21  65.209999  65.690002  57.509998  58.500000  58.500000
3    2020-07-22  56.980000  57.790001  55.000000  56.000000  56.000000
4    2020-07-23  56.669998  61.990002  55.400002  58.099998  58.099998
..          ...        ...        ...        ...        ...        ...
281  2021-08-30  34.250000  37.349998  33.849998  36.799999  36.799999
282  2021-08-31  36.700001  37.049999  34.410000  35.560001  35.560001
283  2021-09-01  35.720001  36.500000  35.119999  35.430000  35.430000
284  2021-09-02  35.630001  37.320000  34.889999  36.919998  36.919998
285  2021-09-03  36.730000  37.860001  36.320000  36.709999  36.709999

        Volume
0      4507100
1       360800
2       379500
3       251600
4       761400
..         ...
281  119060000
282  108830000
283   90360000
284   98620000
285   32000000

[286 rows x 7 columns]
tolistdate: 0      2020-07-17
1      2020-07-20
2      2020-07-21
3      2020-07-22
4      2020-07-23
          ...
281    2021-08-30
282    2021-08-31
283    2021-09-01
284    2021-09-02
285    2021-09-03
Name: Date, Length: 286, dtype: object
                  stock  start_date current_price minall  maxall each_markup  \
0  BLI_ended_2021-09-25  2020-07-17         36.71  33.85  113.53       7.968

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    41.818    49.786    57.754    65.722     73.69    81.658    89.626

  markup_80 markup_90 markup_100

0    97.594   105.562     113.53
                  stock  start_date current_price minall  maxall each_markup  \
0  BLI_ended_2021-09-25  2020-07-17         36.71  33.85  113.53       7.968

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    41.818    49.786    57.754    65.722     73.69    81.658    89.626

  markup_80 markup_90 markup_100
0    97.594   105.562     113.53
./ticker_data/ticker_data_2021-09-25 - Copy/BLKB_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2004-07-26   8.540000   8.750000   8.300000   8.750000   7.101104
1     2004-07-27   8.750000   8.750000   8.470000   8.480000   6.881984
2     2004-07-28   8.520000   8.700000   8.460000   8.560000   6.946910
3     2004-07-29   8.650000   8.650000   8.470000   8.600000   6.979369
4     2004-07-30   8.630000   9.200000   8.630000   9.000000   7.303990
...          ...        ...        ...        ...        ...        ...
4304  2021-08-30  70.309998  70.309998  69.269997  69.489998  69.489998
4305  2021-08-31  68.010002  70.269997  68.010002  69.690002  69.690002
4306  2021-09-01  70.139999  71.209999  69.040001  70.680000  70.680000
4307  2021-09-02  70.900002  71.400002  70.410004  71.050003  71.050003
4308  2021-09-03  71.180000  71.970001  70.000000  71.360001  71.360001

        Volume
0       217400
1        82100
2       129300
3        74800
4       117700
...        ...
4304  16230000
4305  22050000
4306  24000000
4307  14000000
4308  14120000

[4309 rows x 7 columns]
tolistdate: 0       2004-07-26
1       2004-07-27
2       2004-07-28
3       2004-07-29
4       2004-07-30
           ...
4304    2021-08-30
4305    2021-08-31
4306    2021-09-01
4307    2021-09-02
4308    2021-09-03
Name: Date, Length: 4309, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BLKB_ended_2021-09-25  2004-07-26         71.36    8.3  120.35      11.205

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    19.505     30.71    41.915     53.12    64.325     75.53    86.735

  markup_80 markup_90 markup_100
0     97.94   109.145     120.35
                   stock  start_date current_price minall  maxall each_markup  \
0  BLKB_ended_2021-09-25  2004-07-26         71.36    8.3  120.35      11.205

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    19.505     30.71    41.915     53.12    64.325     75.53    86.735

  markup_80 markup_90 markup_100
0     97.94   109.145     120.35
./ticker_data/ticker_data_2021-09-25 - Copy/BLMN_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2012-08-08  11.600000  13.080000  11.570000  12.410000  11.321233
1     2012-08-09  12.530000  13.670000  12.510000  13.490000  12.306483
2     2012-08-10  14.000000  14.000000  12.800000  12.860000  11.731753
3     2012-08-13  12.910000  13.100000  12.500000  12.910000  11.777369
4     2012-08-14  13.050000  13.060000  12.860000  12.930000  11.795613
...          ...        ...        ...        ...        ...        ...
2293  2021-09-20  24.629999  25.120001  24.270000  24.879999  24.879999
2294  2021-09-21  24.860001  25.170000  24.299999  24.559999  24.559999
2295  2021-09-22  24.910000  25.490000  24.870001  25.150000  25.150000
2296  2021-09-23  25.600000  26.559999  25.450001  26.059999  26.059999
2297  2021-09-24  26.150000  27.170000  26.080000  26.250000  26.250000

        Volume
0     10939900
1      1560700
2      1070500
3       395100
4       490400
...        ...
2293   1156200
2294   1226300
2295   1264600
2296   2064200
2297    488748

[2298 rows x 7 columns]
tolistdate: 0       2012-08-08
1       2012-08-09
2       2012-08-10
3       2012-08-13
4       2012-08-14
           ...
2293    2021-09-20
2294    2021-09-21
2295    2021-09-22
2296    2021-09-23
2297    2021-09-24
Name: Date, Length: 2298, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BLMN_ended_2021-09-25  2012-08-08         26.25   4.54  32.81       2.827

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.367    10.194    13.021    15.848    18.675    21.502    24.329

  markup_80 markup_90 markup_100
0    27.156    29.983      32.81
                   stock  start_date current_price minall maxall each_markup  \
0  BLMN_ended_2021-09-25  2012-08-08         26.25   4.54  32.81       2.827

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.367    10.194    13.021    15.848    18.675    21.502    24.329

  markup_80 markup_90 markup_100
0    27.156    29.983      32.81
./ticker_data/ticker_data_2021-09-25 - Copy/BLNKW_ended_2021-09-25.csv
         Date     Open       High        Low    Close  Adj Close  Volume
0  2021-09-22  26.4601  25.959999  25.820101  25.9401    25.9401    1117
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price   minall maxall  \
0  BLNKW_ended_2021-09-25  2021-09-22       25.9401  25.8201  25.96

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0   0.0139898   25.8341   25.8481   25.8621   25.8761     25.89    25.904

  markup_70 markup_80 markup_90 markup_100
0    25.918    25.932    25.946      25.96
                    stock  start_date current_price   minall maxall  \
0  BLNKW_ended_2021-09-25  2021-09-22       25.9401  25.8201  25.96

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0   0.0139898   25.8341   25.8481   25.8621   25.8761     25.89    25.904

  markup_70 markup_80 markup_90 markup_100
0    25.918    25.932    25.946      25.96
./ticker_data/ticker_data_2021-09-25 - Copy/BLNK_ended_2021-09-25.csv
            Date         Open         High          Low        Close  \
0     2009-12-21  2525.000000  2525.000000  2525.000000  2525.000000
1     2009-12-28  1500.000000  1500.000000  1475.000000  1475.000000
2     2009-12-29  1475.000000  2125.000000  1475.000000  1950.000000
3     2009-12-30  2125.000000  2125.000000  2125.000000  2125.000000
4     2009-12-31  2250.000000  2250.000000  2250.000000  2250.000000
...          ...          ...          ...          ...          ...
2810  2021-08-30    31.590000    31.650000    30.660000    31.240000
2811  2021-08-31    31.190001    32.840000    31.190001    32.430000
2812  2021-09-01    32.470001    33.610001    32.110001    32.939999
2813  2021-09-02    33.901001    34.660000    32.910000    33.299999
2814  2021-09-03    32.900002    33.730000    32.450001    32.970001

        Adj Close     Volume
0     2525.000000          0
1     1475.000000          0
2     1950.000000          0
3     2125.000000          0
4     2250.000000          0
...           ...        ...
2810    31.240000   83430000
2811    32.430000  150820000
2812    32.939999  118570000
2813    33.299999  216620000
2814    32.970001   80100000

[2815 rows x 7 columns]
tolistdate: 0       2009-12-21
1       2009-12-28
2       2009-12-29
3       2009-12-30
4       2009-12-31
           ...
2810    2021-08-30
2811    2021-08-31
2812    2021-09-01
2813    2021-09-02
2814    2021-09-03
Name: Date, Length: 2815, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BLNK_ended_2021-09-25  2009-12-21         32.97   1.25   3750     374.875

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   376.125       751   1125.88   1500.75   1875.62    2250.5   2625.38

  markup_80 markup_90 markup_100
0   3000.25   3375.12       3750
                   stock  start_date current_price minall maxall each_markup  \
0  BLNK_ended_2021-09-25  2009-12-21         32.97   1.25   3750     374.875

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   376.125       751   1125.88   1500.75   1875.62    2250.5   2625.38

  markup_80 markup_90 markup_100
0   3000.25   3375.12       3750
./ticker_data/ticker_data_2021-09-25 - Copy/BLPH_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2015-02-13  150.000000  153.750000  120.150002  134.550003  134.550003
1     2015-02-17  134.850006  138.899994  131.250000  138.600006  138.600006
2     2015-02-18  147.449997  147.449997  135.750000  138.600006  138.600006
3     2015-02-19  138.750000  142.500000  136.050003  138.600006  138.600006
4     2015-02-20  150.000000  150.000000  135.000000  141.300003  141.300003
...          ...         ...         ...         ...         ...         ...
1646  2021-08-30    4.010000    4.240000    4.010000    4.050000    4.050000
1647  2021-08-31    4.140000    4.380000    4.082000    4.200000    4.200000
1648  2021-09-01    4.121000    4.350000    4.120000    4.200000    4.200000
1649  2021-09-02    4.200000    4.290000    4.050000    4.100000    4.100000
1650  2021-09-03    4.064000    4.130000    3.970000    3.980000    3.980000

       Volume
0      101800
1        2600
2        2800
3        1200
4        1300
...       ...
1646  1730000
1647  5330000
1648  4360000
1649  6180000
1650  5600000

[1651 rows x 7 columns]
tolistdate: 0       2015-02-13
1       2015-02-17
2       2015-02-18
3       2015-02-19
4       2015-02-20
           ...
1646    2021-08-30
1647    2021-08-31
1648    2021-09-01
1649    2021-09-02
1650    2021-09-03
Name: Date, Length: 1651, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BLPH_ended_2021-09-25  2015-02-13          3.98  3.186  193.8     19.0614

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   22.2474   41.3088   60.3702   79.4316    98.493   117.554   136.616

  markup_80 markup_90 markup_100
0   155.677   174.739      193.8
                   stock  start_date current_price minall maxall each_markup  \
0  BLPH_ended_2021-09-25  2015-02-13          3.98  3.186  193.8     19.0614

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   22.2474   41.3088   60.3702   79.4316    98.493   117.554   136.616

  markup_80 markup_90 markup_100
0   155.677   174.739      193.8
./ticker_data/ticker_data_2021-09-25 - Copy/BLRX_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2011-07-27  75.150002  75.449997  75.000000  75.449997  75.449997
1     2011-07-28  73.500000  73.500000  71.099998  71.099998  71.099998
2     2011-07-29  78.599998  78.599998  77.849998  78.599998  78.599998
3     2011-08-01  78.599998  81.599998  78.599998  81.599998  81.599998
4     2011-08-02  74.250000  74.250000  72.750000  72.750000  72.750000
...          ...        ...        ...        ...        ...        ...
2501  2021-08-30   2.860000   2.880000   2.780000   2.800000   2.800000
2502  2021-08-31   2.800000   2.900000   2.780000   2.870000   2.870000
2503  2021-09-01   2.840000   2.940000   2.840000   2.910000   2.910000
2504  2021-09-02   2.910000   3.010000   2.860000   2.910000   2.910000
2505  2021-09-03   2.900000   2.940000   2.780000   2.780000   2.780000

        Volume
0          100
1            0
2            0
3          200
4            0
...        ...
2501  34760000
2502  41640000
2503  26580000
2504  41390000
2505  45850000

[2506 rows x 7 columns]
tolistdate: 0       2011-07-27
1       2011-07-28
2       2011-07-29
3       2011-08-01
4       2011-08-02
           ...
2501    2021-08-30
2502    2021-08-31
2503    2021-09-01
2504    2021-09-02
2505    2021-09-03
Name: Date, Length: 2506, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BLRX_ended_2021-09-25  2011-07-27          2.78   1.06  103.05      10.199

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.259    21.458    31.657    41.856    52.055    62.254    72.453

  markup_80 markup_90 markup_100
0    82.652    92.851     103.05
                   stock  start_date current_price minall  maxall each_markup  \
0  BLRX_ended_2021-09-25  2011-07-27          2.78   1.06  103.05      10.199

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.259    21.458    31.657    41.856    52.055    62.254    72.453

  markup_80 markup_90 markup_100
0    82.652    92.851     103.05
./ticker_data/ticker_data_2021-09-25 - Copy/BLSA_ended_2021-09-25.csv
           Date    Open    High     Low  Close  Adj Close  Volume
0    2020-10-22  10.280  10.440  10.150  10.18      10.18  999300
1    2020-10-23  10.180  11.125  10.180  10.27      10.27  461600
2    2020-10-26  10.210  10.440  10.210  10.26      10.26  224500
3    2020-10-27  10.390  10.500  10.260  10.35      10.35  326900
4    2020-10-28  10.360  10.410  10.350  10.40      10.40   60100
..          ...     ...     ...     ...    ...        ...     ...
212  2021-08-30   9.760   9.820   9.750   9.82       9.82   80000
213  2021-08-31   9.812   9.880   9.812   9.88       9.88  270000
214  2021-09-01   9.810   9.810   9.810   9.81       9.81   30000
215  2021-09-02   9.800   9.880   9.800   9.88       9.88  100000
216  2021-09-03   9.800   9.850   9.800   9.84       9.84  270000

[217 rows x 7 columns]
tolistdate: 0      2020-10-22
1      2020-10-23
2      2020-10-26
3      2020-10-27
4      2020-10-28
          ...
212    2021-08-30
213    2021-08-31
214    2021-09-01
215    2021-09-02
216    2021-09-03
Name: Date, Length: 217, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BLSA_ended_2021-09-25  2020-10-22          9.84   9.68     14       0.432

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.112    10.544    10.976    11.408     11.84    12.272    12.704

  markup_80 markup_90 markup_100
0    13.136    13.568         14
                   stock  start_date current_price minall maxall each_markup  \
0  BLSA_ended_2021-09-25  2020-10-22          9.84   9.68     14       0.432

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.112    10.544    10.976    11.408     11.84    12.272    12.704

  markup_80 markup_90 markup_100
0    13.136    13.568         14
./ticker_data/ticker_data_2021-09-25 - Copy/BLTSU_ended_2021-09-25.csv
           Date    Open    High     Low   Close  Adj Close   Volume
0    2021-01-07  10.550  10.620  10.370  10.520     10.520  6034700
1    2021-01-08  10.550  10.550  10.400  10.430     10.430   329400
2    2021-01-11  10.680  10.680  10.430  10.500     10.500    61600
3    2021-01-12  10.510  10.670  10.500  10.550     10.550   321500
4    2021-01-13  10.610  10.750  10.550  10.550     10.550    98400
..          ...     ...     ...     ...     ...        ...      ...
157  2021-08-26  10.010  10.010  10.010  10.010     10.010        0
158  2021-08-30  10.010  10.035  10.010  10.035     10.035    60000
159  2021-08-31  10.035  10.035  10.035  10.035     10.035        0
160  2021-09-02  10.030  10.030  10.030  10.030     10.030    10000
161  2021-09-03  10.030  10.030  10.030  10.030     10.030    30000

[162 rows x 7 columns]
tolistdate: 0      2021-01-07
1      2021-01-08
2      2021-01-11
3      2021-01-12
4      2021-01-13
          ...
157    2021-08-26
158    2021-08-30
159    2021-08-31
160    2021-09-02
161    2021-09-03
Name: Date, Length: 162, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BLTSU_ended_2021-09-25  2021-01-07         10.03   9.86   10.9       0.104

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.964    10.068    10.172    10.276     10.38    10.484    10.588

  markup_80 markup_90 markup_100
0    10.692    10.796       10.9
                    stock  start_date current_price minall maxall each_markup  \
0  BLTSU_ended_2021-09-25  2021-01-07         10.03   9.86   10.9       0.104

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.964    10.068    10.172    10.276     10.38    10.484    10.588

  markup_80 markup_90 markup_100
0    10.692    10.796       10.9
./ticker_data/ticker_data_2021-09-25 - Copy/BLTSW_ended_2021-09-25.csv
         Date    Open  High   Low  Close  Adj Close  Volume
0  2021-09-21  0.7002  0.73  0.73   0.73       0.73     200
tolistdate: 0    2021-09-21

Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BLTSW_ended_2021-09-25  2021-09-21          0.73   0.73   0.73           0

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      0.73      0.73      0.73      0.73      0.73      0.73      0.73

  markup_80 markup_90 markup_100
0      0.73      0.73       0.73
                    stock  start_date current_price minall maxall each_markup  \
0  BLTSW_ended_2021-09-25  2021-09-21          0.73   0.73   0.73           0

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      0.73      0.73      0.73      0.73      0.73      0.73      0.73

  markup_80 markup_90 markup_100
0      0.73      0.73       0.73
./ticker_data/ticker_data_2021-09-25 - Copy/BLTS_ended_2021-09-25.csv
           Date    Open    High    Low  Close  Adj Close  Volume
0    2021-03-01  10.500  10.500  9.900  9.900      9.900   38400
1    2021-03-02   9.960  10.030  9.860  9.980      9.980  209700
2    2021-03-03   9.980  10.000  9.810  9.900      9.900   76500
3    2021-03-04   9.820  10.135  9.700  9.830      9.830   83200
4    2021-03-05   9.807   9.990  9.807  9.980      9.980  218200
..          ...     ...     ...    ...    ...        ...     ...
124  2021-08-30   9.705   9.705  9.705  9.705      9.705       0
125  2021-08-31   9.690   9.720  9.690  9.720      9.720  910000
126  2021-09-01   9.720   9.720  9.720  9.720      9.720   80000
127  2021-09-02   9.720   9.720  9.720  9.720      9.720  280000
128  2021-09-03   9.690   9.730  9.690  9.730      9.730  450000

[129 rows x 7 columns]
tolistdate: 0      2021-03-01
1      2021-03-02
2      2021-03-03
3      2021-03-04
4      2021-03-05
          ...
124    2021-08-30
125    2021-08-31
126    2021-09-01
127    2021-09-02
128    2021-09-03
Name: Date, Length: 129, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BLTS_ended_2021-09-25  2021-03-01          9.73   9.56   10.5       0.094

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.654     9.748     9.842     9.936     10.03    10.124    10.218

  markup_80 markup_90 markup_100
0    10.312    10.406       10.5
                   stock  start_date current_price minall maxall each_markup  \
0  BLTS_ended_2021-09-25  2021-03-01          9.73   9.56   10.5       0.094

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.654     9.748     9.842     9.936     10.03    10.124    10.218

  markup_80 markup_90 markup_100
0    10.312    10.406       10.5
./ticker_data/ticker_data_2021-09-25 - Copy/BLUE_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2013-06-19  25.500000  27.000000  24.950001  26.910000  26.910000
1     2013-06-20  26.000000  26.389999  25.030001  26.090000  26.090000
2     2013-06-21  26.000000  26.219999  25.500000  25.500000  25.500000
3     2013-06-24  25.000000  25.459999  24.719999  25.100000  25.100000
4     2013-06-25  25.500000  25.500000  25.000000  25.209999  25.209999
...          ...        ...        ...        ...        ...        ...
2063  2021-08-30  18.129999  18.230000  17.680000  17.850000  17.850000
2064  2021-08-31  17.770000  18.389999  17.750000  18.299999  18.299999
2065  2021-09-01  18.389999  18.510000  18.120001  18.320000  18.320000
2066  2021-09-02  18.219999  18.650000  18.120001  18.400000  18.400000
2067  2021-09-03  18.400000  18.400000  17.730000  18.000000  18.000000

         Volume
0       5305200
1        336400
2        149200
3        162700
4        143000
...         ...
2063  101890000
2064  157260000
2065   71420000
2066   79090000
2067   82940000

[2068 rows x 7 columns]
tolistdate: 0       2013-06-19
1       2013-06-20
2       2013-06-21
3       2013-06-24
4       2013-06-25
           ...
2063    2021-08-30
2064    2021-08-31
2065    2021-09-01
2066    2021-09-02
2067    2021-09-03
Name: Date, Length: 2068, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BLUE_ended_2021-09-25  2013-06-19            18  17.03  236.17      21.914

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    38.944    60.858    82.772   104.686     126.6   148.514   170.428

  markup_80 markup_90 markup_100
0   192.342   214.256     236.17
                   stock  start_date current_price minall  maxall each_markup  \
0  BLUE_ended_2021-09-25  2013-06-19            18  17.03  236.17      21.914

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    38.944    60.858    82.772   104.686     126.6   148.514   170.428

  markup_80 markup_90 markup_100
0   192.342   214.256     236.17
./ticker_data/ticker_data_2021-09-25 - Copy/BLUWU_ended_2021-09-25.csv
           Date   Open    High     Low   Close  Adj Close   Volume
0    2020-12-15  10.12  10.250  10.120  10.150     10.150   990100
1    2020-12-16  10.15  10.250  10.150  10.160     10.160   193900
2    2020-12-17  10.25  10.250  10.160  10.175     10.175    44400
3    2020-12-18  10.25  10.250  10.180  10.250     10.250    61500
4    2020-12-21  10.25  10.250  10.180  10.190     10.190    38500
..          ...    ...     ...     ...     ...        ...      ...
155  2021-08-30   9.06   9.070   7.900   7.900      7.900  1220000
156  2021-08-31   7.97   8.258   7.960   7.960      7.960   290000
157  2021-09-01   7.95   8.415   7.650   8.200      8.200  1210000
158  2021-09-02   8.28   8.960   8.240   8.450      8.450  3870000
159  2021-09-03   8.34   8.352   8.205   8.205      8.205   370000

[160 rows x 7 columns]
tolistdate: 0      2020-12-15
1      2020-12-16
2      2020-12-17
3      2020-12-18
4      2020-12-21
          ...
155    2021-08-30
156    2021-08-31
157    2021-09-01
158    2021-09-02
159    2021-09-03
Name: Date, Length: 160, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BLUWU_ended_2021-09-25  2020-12-15         8.205   7.65     32       2.435

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.085     12.52    14.955     17.39    19.825     22.26    24.695

  markup_80 markup_90 markup_100
0     27.13    29.565         32
                    stock  start_date current_price minall maxall each_markup  \
0  BLUWU_ended_2021-09-25  2020-12-15         8.205   7.65     32       2.435

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.085     12.52    14.955     17.39    19.825     22.26    24.695

  markup_80 markup_90 markup_100
0     27.13    29.565         32
./ticker_data/ticker_data_2021-09-25 - Copy/BLUWW_ended_2021-09-25.csv
         Date    Open    High     Low   Close  Adj Close  Volume
0  2021-09-09  0.6612  0.9739  0.7807  0.8801     0.8801  277090
tolistdate: 0    2021-09-09
Name: Date, dtype: object
                    stock  start_date current_price  minall  maxall  \
0  BLUWW_ended_2021-09-25  2021-09-09        0.8801  0.7807  0.9739

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.01932   0.80002   0.81934   0.83866   0.85798    0.8773   0.89662

  markup_70 markup_80 markup_90 markup_100
0   0.91594   0.93526   0.95458     0.9739
                    stock  start_date current_price  minall  maxall  \
0  BLUWW_ended_2021-09-25  2021-09-09        0.8801  0.7807  0.9739

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.01932   0.80002   0.81934   0.83866   0.85798    0.8773   0.89662

  markup_70 markup_80 markup_90 markup_100
0   0.91594   0.93526   0.95458     0.9739
./ticker_data/ticker_data_2021-09-25 - Copy/BLUW_ended_2021-09-25.csv
           Date    Open    High    Low  Close  Adj Close     Volume
0    2021-02-09  10.210  10.210  10.14  10.18      10.18     265700
1    2021-02-10  10.150  10.200  10.15  10.19      10.19     101400
2    2021-02-11  10.190  10.670  10.14  10.29      10.29     116100
3    2021-02-12  10.290  10.300  10.20  10.20      10.20       7800
4    2021-02-16  10.281  10.300  10.15  10.19      10.19      21800
..          ...     ...     ...    ...    ...        ...        ...
133  2021-08-30   8.040   8.100   7.08   7.15       7.15  100750000
134  2021-08-31   7.110   7.550   7.02   7.09       7.09   50940000
135  2021-09-01   7.170   7.680   6.76   7.32       7.32   84590000
136  2021-09-02   7.450   7.981   7.35   7.59       7.59   78320000
137  2021-09-03   7.590   7.790   7.32   7.66       7.66   34860000

[138 rows x 7 columns]
tolistdate: 0      2021-02-09
1      2021-02-10
2      2021-02-11
3      2021-02-12
4      2021-02-16
          ...
133    2021-08-30
134    2021-08-31
135    2021-09-01
136    2021-09-02
137    2021-09-03
Name: Date, Length: 138, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BLUW_ended_2021-09-25  2021-02-09          7.66   6.76  31.24       2.448

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.208    11.656    14.104    16.552        19    21.448    23.896

  markup_80 markup_90 markup_100
0    26.344    28.792      31.24
                   stock  start_date current_price minall maxall each_markup  \
0  BLUW_ended_2021-09-25  2021-02-09          7.66   6.76  31.24       2.448

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.208    11.656    14.104    16.552        19    21.448    23.896

  markup_80 markup_90 markup_100
0    26.344    28.792      31.24
./ticker_data/ticker_data_2021-09-25 - Copy/BLU_ended_2021-09-25.csv
            Date         Open         High          Low        Close  \
0     2003-09-18  1219.494629  1947.292358  1218.411499  1401.444092
1     2003-09-19  1376.534302  1390.613770  1286.642578  1321.299683
2     2003-09-22  1334.296021  1361.371826  1299.639038  1342.960327
3     2003-09-23  1345.126343  1442.599243  1327.797852  1418.772583
4     2003-09-24  1414.440430  1488.086670  1366.786987  1397.111938
...          ...          ...          ...          ...          ...
3495  2021-08-30     3.670000     3.830000     3.560000     3.670000
3496  2021-08-31     3.680000     3.740000     3.640000     3.700000
3497  2021-09-01     3.750000     3.750000     3.500000     3.500000
3498  2021-09-02     3.620000     3.860000     3.600000     3.800000
3499  2021-09-03     3.770000     3.880000     3.700000     3.840000

        Adj Close     Volume
0     1401.444092      29900
1     1321.299683       4000
2     1342.960327       1800
3     1418.772583       4400
4     1397.111938       2400
...           ...        ...
3495     3.670000  212140000
3496     3.700000   46030000
3497     3.500000   75960000
3498     3.800000  118040000
3499     3.840000   41230000

[3500 rows x 7 columns]
tolistdate: 0       2003-09-18
1       2003-09-19
2       2003-09-22
3       2003-09-23
4       2003-09-24
           ...
3495    2021-08-30
3496    2021-08-31
3497    2021-09-01
3498    2021-09-02
3499    2021-09-03
Name: Date, Length: 3500, dtype: object
                  stock  start_date current_price    minall   maxall  \
0  BLU_ended_2021-09-25  2003-09-18          3.84  0.613718  2970.76

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     297.014   297.628   594.643   891.657   1188.67   1485.69    1782.7

  markup_70 markup_80 markup_90 markup_100
0   2079.71   2376.73   2673.74    2970.76
                  stock  start_date current_price    minall   maxall  \
0  BLU_ended_2021-09-25  2003-09-18          3.84  0.613718  2970.76

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     297.014   297.628   594.643   891.657   1188.67   1485.69    1782.7

  markup_70 markup_80 markup_90 markup_100
0   2079.71   2376.73   2673.74    2970.76
./ticker_data/ticker_data_2021-09-25 - Copy/BL_ended_2021-09-25.csv
            Date        Open        High         Low       Close   Adj Close  \
0     2016-10-28   24.520000   25.750000   23.000000   23.700001   23.700001
1     2016-10-31   24.000000   24.230000   22.700001   22.750000   22.750000
2     2016-11-01   22.350000   23.344999   22.350000   22.490000   22.490000
3     2016-11-02   22.350000   23.000000   22.100000   22.150000   22.150000
4     2016-11-03   22.150000   22.290001   21.660000   21.980000   21.980000
...          ...         ...         ...         ...         ...         ...
1215  2021-08-30  110.610001  111.459999  109.930000  110.809998  110.809998
1216  2021-08-31  110.529999  110.529999  108.320000  109.099998  109.099998
1217  2021-09-01  109.279999  111.589996  108.805000  111.180000  111.180000
1218  2021-09-02  111.989998  113.949997  111.570000  113.830002  113.830002
1219  2021-09-03  113.889999  118.360001  113.662003  117.879997  117.879997

        Volume
0      7489300
1       519600
2       396200
3       322300
4       304900
...        ...
1215  21110000
1216  22760000
1217  27460000
1218  29900000
1219  56240000

[1220 rows x 7 columns]
tolistdate: 0       2016-10-28
1       2016-10-31
2       2016-11-01
3       2016-11-02
4       2016-11-03
           ...
1215    2021-08-30
1216    2021-08-31
1217    2021-09-01
1218    2021-09-02
1219    2021-09-03
Name: Date, Length: 1220, dtype: object
                 stock  start_date current_price minall  maxall each_markup  \
0  BL_ended_2021-09-25  2016-10-28        117.88  21.66  154.61      13.295

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    34.955     48.25    61.545     74.84    88.135    101.43   114.725

  markup_80 markup_90 markup_100
0    128.02   141.315     154.61
                 stock  start_date current_price minall  maxall each_markup  \
0  BL_ended_2021-09-25  2016-10-28        117.88  21.66  154.61      13.295

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    34.955     48.25    61.545     74.84    88.135    101.43   114.725

  markup_80 markup_90 markup_100
0    128.02   141.315     154.61
./ticker_data/ticker_data_2021-09-25 - Copy/BMBL_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2021-02-11  76.000000  79.599998  70.000000  70.309998  70.309998
1    2021-02-12  75.709999  84.800003  71.510002  75.459999  75.459999
2    2021-02-16  79.150002  79.599998  70.377998  78.889999  78.889999
3    2021-02-17  76.779999  78.697998  75.000000  77.320000  77.320000
4    2021-02-18  75.449997  76.400002  73.629997  74.000000  74.000000
..          ...        ...        ...        ...        ...        ...
138  2021-08-30  55.599998  56.480000  53.630001  55.500000  55.500000
139  2021-08-31  55.619999  55.849998  54.110001  54.500000  54.500000
140  2021-09-01  54.500000  55.680000  54.110001  55.290001  55.290001
141  2021-09-02  55.490002  58.240002  55.490002  57.730000  57.730000
142  2021-09-03  57.900002  60.000000  57.110001  59.939999  59.939999

        Volume
0     43502700
1     21414200
2     13163000
3      3769600
4      3166400
..         ...
138  114010000
139  102320000
140  164010000
141  144810000
142  141030000

[143 rows x 7 columns]
tolistdate: 0      2021-02-11
1      2021-02-12
2      2021-02-16
3      2021-02-17
4      2021-02-18
          ...
138    2021-08-30
139    2021-08-31
140    2021-09-01
141    2021-09-02
142    2021-09-03
Name: Date, Length: 143, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BMBL_ended_2021-09-25  2021-02-11         59.94  38.91   84.8       4.589

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    43.499    48.088    52.677    57.266    61.855    66.444    71.033

  markup_80 markup_90 markup_100
0    75.622    80.211       84.8
                   stock  start_date current_price minall maxall each_markup  \
0  BMBL_ended_2021-09-25  2021-02-11         59.94  38.91   84.8       4.589

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    43.499    48.088    52.677    57.266    61.855    66.444    71.033

  markup_80 markup_90 markup_100
0    75.622    80.211       84.8
./ticker_data/ticker_data_2021-09-25 - Copy/BMEA_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2021-04-16  20.400000  22.219999  16.549999  18.600000  18.600000
1    2021-04-19  17.260000  19.540001  16.900000  17.000000  17.000000
2    2021-04-20  17.000000  17.000000  15.150000  16.790001  16.790001
3    2021-04-21  16.330000  18.090000  15.530000  17.459999  17.459999
4    2021-04-22  17.200001  17.980000  16.320000  17.610001  17.610001
..          ...        ...        ...        ...        ...        ...
108  2021-09-20  10.610000  10.948000  10.340000  10.350000  10.350000
109  2021-09-21  10.300000  10.715000   9.720000  10.000000  10.000000
110  2021-09-22  10.550000  10.550000   9.890000  10.340000  10.340000
111  2021-09-23  10.370000  10.447000  10.090000  10.330000  10.330000
112  2021-09-24  10.370000  10.600000  10.205000  10.500000  10.500000

      Volume
0    3590100
1     677700
2     168100
3     134300
4      67300
..       ...
108    74900
109   224600
110    57300
111    47100
112     9601

[113 rows x 7 columns]
tolistdate: 0      2021-04-16
1      2021-04-19
2      2021-04-20
3      2021-04-21
4      2021-04-22
          ...
108    2021-09-20
109    2021-09-21
110    2021-09-22
111    2021-09-23
112    2021-09-24
Name: Date, Length: 113, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BMEA_ended_2021-09-25  2021-04-16          10.5   9.72  22.22        1.25

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     10.97     12.22     13.47     14.72     15.97     17.22     18.47

  markup_80 markup_90 markup_100
0     19.72     20.97      22.22
                   stock  start_date current_price minall maxall each_markup  \
0  BMEA_ended_2021-09-25  2021-04-16          10.5   9.72  22.22        1.25

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     10.97     12.22     13.47     14.72     15.97     17.22     18.47

  markup_80 markup_90 markup_100
0     19.72     20.97      22.22
./ticker_data/ticker_data_2021-09-25 - Copy/BMRA_ended_2021-09-25.csv
            Date     Open     High     Low   Close  Adj Close    Volume
0     1999-12-31  3.06250  3.12500  2.8750  2.9375     2.9375     23400
1     2000-01-03  2.93750  3.12500  2.8125  3.0625     3.0625     24400
2     2000-01-04  3.12500  3.12500  2.8125  2.8125     2.8125     22800
3     2000-01-05  3.00000  3.09375  2.8125  3.0000     3.0000      6900
4     2000-01-06  2.96875  2.96875  2.8750  2.8750     2.8750      3400
...          ...      ...      ...     ...     ...        ...       ...
4198  2021-08-30  4.11000  4.47000  4.1000  4.3600     4.3600  12060000
4199  2021-08-31  4.39000  4.74000  4.3400  4.4800     4.4800  11370000
4200  2021-09-01  4.48000  4.70000  4.4500  4.6000     4.6000   3640000
4201  2021-09-02  4.60000  4.79000  4.5100  4.5700     4.5700   6210000
4202  2021-09-03  4.62000  4.79000  4.6200  4.7200     4.7200   7200000

[4203 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
4198    2021-08-30
4199    2021-08-31
4200    2021-09-01
4201    2021-09-02
4202    2021-09-03
Name: Date, Length: 4203, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BMRA_ended_2021-09-25  1999-12-31          4.72   0.17  23.39       2.322

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.492     4.814     7.136     9.458     11.78    14.102    16.424

  markup_80 markup_90 markup_100
0    18.746    21.068      23.39
                   stock  start_date current_price minall maxall each_markup  \
0  BMRA_ended_2021-09-25  1999-12-31          4.72   0.17  23.39       2.322

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.492     4.814     7.136     9.458     11.78    14.102    16.424

  markup_80 markup_90 markup_100
0    18.746    21.068      23.39
./ticker_data/ticker_data_2021-09-25 - Copy/BMRC_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   6.218462   6.218462   6.218462   6.218462   4.535152
1     2000-01-03   5.923085   6.218462   5.923085   6.218462   4.535152
2     2000-01-04   6.218462   6.218462   6.218462   6.218462   4.535152
3     2000-01-05   5.720985   6.094092   5.720985   6.094092   4.444450
4     2000-01-06   5.845354   5.969723   5.845354   5.969723   4.353746
...          ...        ...        ...        ...        ...        ...
5227  2021-08-30  36.040001  36.259998  35.860001  35.930000  35.930000
5228  2021-08-31  36.090000  36.369999  35.950001  36.200001  36.200001
5229  2021-09-01  36.259998  36.270000  35.540001  36.090000  36.090000
5230  2021-09-02  36.080002  36.310001  35.450001  35.689999  35.689999
5231  2021-09-03  35.750000  36.020000  35.299999  35.770000  35.770000

       Volume
0         200
1         800
2           0
3        3600
4        5200
...       ...
5227  6110000
5228  6910000
5229  5700000
5230  7770000
5231  4680000

[5232 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5227    2021-08-30
5228    2021-08-31
5229    2021-09-01
5230    2021-09-02
5231    2021-09-03
Name: Date, Length: 5232, dtype: object
                   stock  start_date current_price   minall maxall  \
0  BMRC_ended_2021-09-25  1999-12-31         35.77  5.03695  47.77

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      4.2733   9.31026   13.5836   17.8569   22.1302   26.4035   30.6768

  markup_70 markup_80 markup_90 markup_100
0   34.9501   39.2234   43.4967      47.77
                   stock  start_date current_price   minall maxall  \
0  BMRC_ended_2021-09-25  1999-12-31         35.77  5.03695  47.77

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      4.2733   9.31026   13.5836   17.8569   22.1302   26.4035   30.6768

  markup_70 markup_80 markup_90 markup_100
0   34.9501   39.2234   43.4967      47.77
./ticker_data/ticker_data_2021-09-25 - Copy/BMRN_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  11.500000  11.750000  11.500000  11.750000  11.750000
1     2000-01-03  12.250000  12.750000  11.750000  12.750000  12.750000
2     2000-01-04  13.125000  13.562500  12.687500  13.562500  13.562500
3     2000-01-05  13.000000  13.062500  12.875000  12.875000  12.875000
4     2000-01-06  12.750000  13.000000  12.750000  12.750000  12.750000
...          ...        ...        ...        ...        ...        ...
5449  2021-08-30  83.760002  85.010002  83.059998  83.269997  83.269997
5450  2021-08-31  82.480003  84.500000  82.250000  84.209999  84.209999
5451  2021-09-01  84.519997  85.279999  83.690002  84.269997  84.269997
5452  2021-09-02  84.139999  85.239998  83.330002  85.150002  85.150002
5453  2021-09-03  85.150002  85.239998  84.360001  84.949997  84.949997

         Volume
0          4400
1          6300
2          3200
3          4700
4         12200
...         ...
5449  159910000
5450  156840000
5451   84810000
5452   99570000
5453  104670000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BMRN_ended_2021-09-25  1999-12-31         84.95   3.57  151.75      14.818

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    18.388    33.206    48.024    62.842     77.66    92.478   107.296

  markup_80 markup_90 markup_100
0   122.114   136.932     151.75
                   stock  start_date current_price minall  maxall each_markup  \
0  BMRN_ended_2021-09-25  1999-12-31         84.95   3.57  151.75      14.818

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    18.388    33.206    48.024    62.842     77.66    92.478   107.296

  markup_80 markup_90 markup_100
0   122.114   136.932     151.75
./ticker_data/ticker_data_2021-09-25 - Copy/BMTC_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  12.125000  12.125000  11.937500  11.937500   6.758844
1     2000-01-03  11.937500  11.937500  11.562500  11.562500   6.546523
2     2000-01-04  11.500000  11.500000  11.312500  11.312500   6.404977
3     2000-01-05  11.250000  11.250000  11.250000  11.250000   6.369590
4     2000-01-06  11.187500  11.187500  11.187500  11.187500   6.334204
...          ...        ...        ...        ...        ...        ...
5406  2021-08-30  41.029999  41.029999  40.130001  40.209999  40.209999
5407  2021-08-31  40.419998  40.869999  40.150002  40.799999  40.799999
5408  2021-09-01  41.119999  41.119999  39.970001  40.700001  40.700001
5409  2021-09-02  40.889999  41.230000  40.270000  40.669998  40.669998
5410  2021-09-03  40.770000  40.880001  40.230000  40.430000  40.430000

       Volume
0       20000
1       12200
2       13000
3        7000
4        1200
...       ...
5406  5110000
5407  5840000
5408  4220000
5409  4090000
5410  2450000

[5411 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5406    2021-08-30
5407    2021-08-31
5408    2021-09-01
5409    2021-09-02
5410    2021-09-03
Name: Date, Length: 5411, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BMTC_ended_2021-09-25  1999-12-31         40.43   9.75  50.35        4.06

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     13.81     17.87     21.93     25.99     30.05     34.11     38.17

  markup_80 markup_90 markup_100
0     42.23     46.29      50.35
                   stock  start_date current_price minall maxall each_markup  \
0  BMTC_ended_2021-09-25  1999-12-31         40.43   9.75  50.35        4.06

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     13.81     17.87     21.93     25.99     30.05     34.11     38.17

  markup_80 markup_90 markup_100
0     42.23     46.29      50.35
./ticker_data/ticker_data_2021-09-25 - Copy/BNFT_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2013-09-18  42.500000  55.869999  41.500000  53.549999  53.549999
1     2013-09-19  53.349998  55.400002  48.099998  50.299999  50.299999
2     2013-09-20  49.740002  51.560001  49.099998  50.910000  50.910000
3     2013-09-23  51.849998  51.849998  48.529999  49.570000  49.570000
4     2013-09-24  49.119999  50.450001  47.599998  47.950001  47.950001
...          ...        ...        ...        ...        ...        ...
2000  2021-08-30  11.960000  12.220000  11.910000  12.200000  12.200000
2001  2021-08-31  12.170000  12.330000  12.040000  12.070000  12.070000
2002  2021-09-01  12.140000  12.230000  11.850000  11.930000  11.930000
2003  2021-09-02  12.010000  12.010000  11.780000  11.950000  11.950000
2004  2021-09-03  11.960000  11.960000  11.680000  11.850000  11.850000

        Volume
0      6191300
1       535600
2       164700
3       335400
4        47500
...        ...
2000  15630000
2001  12180000
2002  18570000
2003  10020000
2004  17130000

[2005 rows x 7 columns]
tolistdate: 0       2013-09-18
1       2013-09-19
2       2013-09-20
3       2013-09-23
4       2013-09-24
           ...
2000    2021-08-30
2001    2021-08-31
2002    2021-09-01
2003    2021-09-02
2004    2021-09-03
Name: Date, Length: 2005, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BNFT_ended_2021-09-25  2013-09-18         11.85   6.09     77       7.091

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.181    20.272    27.363    34.454    41.545    48.636    55.727

  markup_80 markup_90 markup_100
0    62.818    69.909         77
                   stock  start_date current_price minall maxall each_markup  \
0  BNFT_ended_2021-09-25  2013-09-18         11.85   6.09     77       7.091

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.181    20.272    27.363    34.454    41.545    48.636    55.727

  markup_80 markup_90 markup_100
0    62.818    69.909         77
./ticker_data/ticker_data_2021-09-25 - Copy/BNGOW_ended_2021-09-25.csv
         Date  Open  High   Low  Close  Adj Close  Volume
0  2021-09-24  2.25  2.37  2.36   2.36       2.36    1760
tolistdate: 0    2021-09-24
Name: Date, dtype: object
                    stock  start_date current_price minall maxall  \
0  BNGOW_ended_2021-09-25  2021-09-24          2.36   2.36   2.37

   each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0  0.000999999     2.361     2.362     2.363     2.364     2.365     2.366

  markup_70 markup_80 markup_90 markup_100
0     2.367     2.368     2.369       2.37
                    stock  start_date current_price minall maxall  \
0  BNGOW_ended_2021-09-25  2021-09-24          2.36   2.36   2.37

   each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0  0.000999999     2.361     2.362     2.363     2.364     2.365     2.366

  markup_70 markup_80 markup_90 markup_100
0     2.367     2.368     2.369       2.37
./ticker_data/ticker_data_2021-09-25 - Copy/BNGO_ended_2021-09-25.csv
           Date  Open  High   Low  Close  Adj Close    Volume
0    2018-08-21  6.00  6.74  5.70  6.150      6.150    272800
1    2018-08-22  6.44  6.55  6.18  6.300      6.300     45600
2    2018-08-23  6.79  6.79  6.30  6.350      6.350     27400
3    2018-08-24  6.58  6.60  6.30  6.360      6.360     29900
4    2018-08-27  6.50  6.50  6.00  6.150      6.150     35200
..          ...   ...   ...   ...    ...        ...       ...
773  2021-09-20  5.32  5.38  5.06  5.170      5.170  13106700
774  2021-09-21  5.22  5.30  5.13  5.190      5.190   6526300
775  2021-09-22  5.27  5.56  5.20  5.460      5.460   9949900
776  2021-09-23  5.52  5.65  5.43  5.640      5.640   6734400
777  2021-09-24  5.55  5.60  5.46  5.575      5.575   2593278

[778 rows x 7 columns]
tolistdate: 0      2018-08-21
1      2018-08-22
2      2018-08-23
3      2018-08-24
4      2018-08-27
          ...
773    2021-09-20
774    2021-09-21
775    2021-09-22
776    2021-09-23
777    2021-09-24
Name: Date, Length: 778, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BNGO_ended_2021-09-25  2018-08-21         5.575   0.25  15.69       1.544

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.794     3.338     4.882     6.426      7.97     9.514    11.058

  markup_80 markup_90 markup_100
0    12.602    14.146      15.69
                   stock  start_date current_price minall maxall each_markup  \
0  BNGO_ended_2021-09-25  2018-08-21         5.575   0.25  15.69       1.544

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.794     3.338     4.882     6.426      7.97     9.514    11.058

  markup_80 markup_90 markup_100
0    12.602    14.146      15.69
./ticker_data/ticker_data_2021-09-25 - Copy/BNR_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-06-12  22.799999  26.370001  22.500000  24.629999  24.629999
1    2020-06-15  22.629999  25.959999  22.500000  23.209999  23.209999
2    2020-06-16  24.010000  25.000000  23.610001  24.350000  24.350000
3    2020-06-17  24.600000  24.900000  24.040001  24.389999  24.389999
4    2020-06-18  24.400000  26.590000  24.250000  26.590000  26.590000
..          ...        ...        ...        ...        ...        ...
305  2021-08-30  19.440001  20.340000  18.660000  19.930000  19.930000
306  2021-08-31  18.320000  19.358999  17.559999  18.629999  18.629999
307  2021-09-01  18.799999  20.340000  18.799999  19.160000  19.160000
308  2021-09-02  19.200001  20.525999  18.799999  19.790001  19.790001
309  2021-09-03  19.940001  20.900000  19.500000  20.510000  20.510000

       Volume
0     5021700
1     1238300
2      262500
3       91600
4      441900
..        ...
305  38140000
306  71560000
307  21760000
308  21070000
309  11850000

[310 rows x 7 columns]
tolistdate: 0      2020-06-12
1      2020-06-15
2      2020-06-16
3      2020-06-17
4      2020-06-18
          ...
305    2021-08-30
306    2021-08-31
307    2021-09-01
308    2021-09-02
309    2021-09-03
Name: Date, Length: 310, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  BNR_ended_2021-09-25  2020-06-12         20.51  17.56  39.75       2.219

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    19.779    21.998    24.217    26.436    28.655    30.874    33.093

  markup_80 markup_90 markup_100
0    35.312    37.531      39.75
                  stock  start_date current_price minall maxall each_markup  \
0  BNR_ended_2021-09-25  2020-06-12         20.51  17.56  39.75       2.219

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    19.779    21.998    24.217    26.436    28.655    30.874    33.093

  markup_80 markup_90 markup_100
0    35.312    37.531      39.75
./ticker_data/ticker_data_2021-09-25 - Copy/BNSO_ended_2021-09-25.csv
            Date     Open     High     Low    Close  Adj Close   Volume
0     1999-12-31  8.12500  8.40625  8.1250  8.40625   7.468981    13900
1     2000-01-03  8.40625  8.75000  8.3750  8.68750   7.718873    37100
2     2000-01-04  8.50000  8.68750  8.3125  8.50000   7.552278    11600
3     2000-01-05  8.43750  8.46875  8.3125  8.34375   7.413450    11200
4     2000-01-06  8.28125  8.37500  8.1875  8.31250   7.385684    26300
...          ...      ...      ...     ...      ...        ...      ...
5044  2021-08-30  6.45000  6.60000  6.3000  6.50000   6.500000   370000
5045  2021-08-31  6.43000  6.94000  6.4000  6.87000   6.870000  2390000
5046  2021-09-01  6.86000  7.07000  6.5700  6.70000   6.700000  7450000
5047  2021-09-02  6.80000  6.94000  6.5500  6.69000   6.690000   800000
5048  2021-09-03  6.77000  6.80000  6.5200  6.69000   6.690000   220000

[5049 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5044    2021-08-30
5045    2021-08-31
5046    2021-09-01
5047    2021-09-02
5048    2021-09-03
Name: Date, Length: 5049, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BNSO_ended_2021-09-25  1999-12-31          6.69   0.03  21.375      2.1345

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.1645     4.299    6.4335     8.568   10.7025    12.837   14.9715

  markup_80 markup_90 markup_100
0    17.106   19.2405     21.375
                   stock  start_date current_price minall  maxall each_markup  \
0  BNSO_ended_2021-09-25  1999-12-31          6.69   0.03  21.375      2.1345

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    2.1645     4.299    6.4335     8.568   10.7025    12.837   14.9715

  markup_80 markup_90 markup_100
0    17.106   19.2405     21.375
./ticker_data/ticker_data_2021-09-25 - Copy/BNTC_ended_2021-09-25.csv
            Date    Open    High     Low   Close   Adj Close    Volume
0     2014-06-24  348.00  348.00  348.00  348.00  347.606049         0
1     2014-06-26  342.00  342.00  342.00  342.00  341.612823         0
2     2014-06-27  318.00  342.00  318.00  336.00  335.619629         0
3     2014-06-30  342.00  342.00  330.00  330.00  329.626404         0
4     2014-07-01  330.00  330.00  330.00  330.00  329.626404         0
...          ...     ...     ...     ...     ...         ...       ...
1755  2021-08-30    4.12    4.49    3.95    4.26    4.260000  13650000
1756  2021-08-31    4.15    4.30    3.91    3.96    3.960000  38810000
1757  2021-09-01    3.96    4.09    3.88    3.98    3.980000  10870000
1758  2021-09-02    3.96    4.00    3.85    3.95    3.950000   6820000
1759  2021-09-03    3.96    4.03    3.84    3.93    3.930000  11610000

[1760 rows x 7 columns]
tolistdate: 0       2014-06-24
1       2014-06-26
2       2014-06-27
3       2014-06-30
4       2014-07-01
           ...
1755    2021-08-30
1756    2021-08-31
1757    2021-09-01
1758    2021-09-02
1759    2021-09-03
Name: Date, Length: 1760, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BNTC_ended_2021-09-25  2014-06-24          3.93    2.3    348       34.57

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     36.87     71.44    106.01    140.58    175.15    209.72    244.29

  markup_80 markup_90 markup_100
0    278.86    313.43        348
                   stock  start_date current_price minall maxall each_markup  \
0  BNTC_ended_2021-09-25  2014-06-24          3.93    2.3    348       34.57

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     36.87     71.44    106.01    140.58    175.15    209.72    244.29

  markup_80 markup_90 markup_100
0    278.86    313.43        348
./ticker_data/ticker_data_2021-09-25 - Copy/BNTX_ended_2021-09-25.csv
           Date        Open        High         Low       Close   Adj Close  \
0    2019-10-10   16.500000   16.698999   13.010000   14.240000   14.240000
1    2019-10-11   15.340000   15.340000   13.500000   13.820000   13.820000
2    2019-10-14   13.830000   13.910000   12.525000   12.750000   12.750000
3    2019-10-15   12.990000   13.000000   12.530000   12.920000   12.920000
4    2019-10-16   13.200000   13.880000   12.610000   12.940000   12.940000
..          ...         ...         ...         ...         ...         ...
475  2021-08-30  351.000000  360.329987  342.789001  345.000000  345.000000
476  2021-08-31  340.260010  349.339996  327.100006  329.190002  329.190002
477  2021-09-01  334.250000  336.500000  326.500000  332.500000  332.500000
478  2021-09-02  334.859985  341.763000  326.660004  328.529999  328.529999
479  2021-09-03  328.489990  334.309998  320.709991  334.299988  334.299988

        Volume
0      2805800
1      1364300
2       899100
3       484700
4       524200
..         ...
475  301000000
476  332340000
477  263220000
478  211600000
479  223840000

[480 rows x 7 columns]
tolistdate: 0      2019-10-10
1      2019-10-11
2      2019-10-14
3      2019-10-15
4      2019-10-16
          ...
475    2021-08-30
476    2021-08-31
477    2021-09-01
478    2021-09-02
479    2021-09-03
Name: Date, Length: 480, dtype: object
                   stock  start_date current_price  minall maxall each_markup  \
0  BNTX_ended_2021-09-25  2019-10-10         334.3  12.525    464     45.1475

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   57.6725    102.82   147.967   193.115   238.262    283.41   328.557

  markup_80 markup_90 markup_100
0   373.705   418.852        464
                   stock  start_date current_price  minall maxall each_markup  \
0  BNTX_ended_2021-09-25  2019-10-10         334.3  12.525    464     45.1475

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   57.6725    102.82   147.967   193.115   238.262    283.41   328.557

  markup_80 markup_90 markup_100
0   373.705   418.852        464
./ticker_data/ticker_data_2021-09-25 - Copy/BOCH_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   6.666667   6.666667   6.666667   6.666667   3.842015
1     2000-01-03   6.363636   6.363636   6.363636   6.363636   3.667379
2     2000-01-04   6.363636   6.363636   6.363636   6.363636   3.667379
3     2000-01-05   6.363636   6.363636   6.363636   6.363636   3.667379
4     2000-01-12   6.363636   6.363636   6.363636   6.363636   3.667379
...          ...        ...        ...        ...        ...        ...
4707  2021-09-20  12.870000  13.030000  12.720000  12.990000  12.990000
4708  2021-09-21  13.090000  13.340000  12.980000  13.210000  13.210000
4709  2021-09-22  13.350000  13.910000  13.350000  13.570000  13.570000
4710  2021-09-23  13.590000  14.440000  13.590000  14.330000  14.330000
4711  2021-09-24  14.170000  14.740000  14.170000  14.730000  14.730000

       Volume
0           0
1        1980
2           0
3       29040
4         660
...       ...
4707    24500
4708    38200
4709  1107300
4710   250900
4711    74926

[4712 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-12
           ...
4707    2021-09-20
4708    2021-09-21
4709    2021-09-22
4710    2021-09-23
4711    2021-09-24
Name: Date, Length: 4712, dtype: object
                   stock  start_date current_price minall   maxall  \
0  BOCH_ended_2021-09-25  1999-12-31         14.73    2.9  17.3167

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     1.44167   4.34167   5.78333     7.225   8.66667   10.1083     11.55

  markup_70 markup_80 markup_90 markup_100
0   12.9917   14.4333    15.875    17.3167
                   stock  start_date current_price minall   maxall  \
0  BOCH_ended_2021-09-25  1999-12-31         14.73    2.9  17.3167

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     1.44167   4.34167   5.78333     7.225   8.66667   10.1083     11.55

  markup_70 markup_80 markup_90 markup_100
0   12.9917   14.4333    15.875    17.3167
./ticker_data/ticker_data_2021-09-25 - Copy/BOKFL_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2016-06-30  24.950001  25.090000  24.900000  25.039000  20.231684
1     2016-07-01  25.100000  25.100000  24.950001  24.950001  20.159773
2     2016-07-05  25.000000  25.020000  24.959999  25.000000  20.200176
3     2016-07-06  25.000000  25.100000  24.959999  25.059999  20.248652
4     2016-07-07  25.100000  25.150000  24.980000  25.059999  20.248652
...          ...        ...        ...        ...        ...        ...
1289  2021-08-16  25.180000  25.200001  25.170000  25.197001  25.197001
1290  2021-08-17  25.200001  25.209999  25.170000  25.170000  25.170000
1291  2021-08-18  25.180000  25.200001  25.180000  25.200001  25.200001
1292  2021-08-19  25.200001  25.200001  25.180000  25.190001  25.190001
1293  2021-08-20  25.190001  25.200001  25.180000  25.190001  25.190001

       Volume
0      202700
1      145500
2      105600
3      241400
4      165300
...       ...
1289  1440000
1290  2210000
1291  1390000
1292   240000
1293   770000

[1294 rows x 7 columns]
tolistdate: 0       2016-06-30
1       2016-07-01
2       2016-07-05
3       2016-07-06
4       2016-07-07
           ...
1289    2021-08-16
1290    2021-08-17
1291    2021-08-18
1292    2021-08-19
1293    2021-08-20
Name: Date, Length: 1294, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BOKFL_ended_2021-09-25  2016-06-30         25.19  16.01  26.75       1.074

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.084    18.158    19.232    20.306     21.38    22.454    23.528

  markup_80 markup_90 markup_100
0    24.602    25.676      26.75
                    stock  start_date current_price minall maxall each_markup  \
0  BOKFL_ended_2021-09-25  2016-06-30         25.19  16.01  26.75       1.074

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    17.084    18.158    19.232    20.306     21.38    22.454    23.528

  markup_80 markup_90 markup_100
0    24.602    25.676      26.75
./ticker_data/ticker_data_2021-09-25 - Copy/BOKF_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  17.950214  17.950214  17.950214  17.950214  12.352900
1     2000-01-03  17.936333  18.602697  17.714211  18.158455  12.496205
2     2000-01-04  17.741976  17.769741  17.714211  17.714211  12.190490
3     2000-01-05  17.492088  18.269514  17.464323  18.269514  12.572636
4     2000-01-06  17.769741  18.213984  17.769741  18.213984  12.534422
...          ...        ...        ...        ...        ...        ...
5450  2021-08-30  88.800003  89.279999  86.849998  87.050003  87.050003
5451  2021-08-31  87.199997  88.129997  86.639999  88.050003  88.050003
5452  2021-09-01  88.209999  88.209999  85.980003  86.980003  86.980003
5453  2021-09-02  87.739998  87.739998  86.169998  86.330002  86.330002
5454  2021-09-03  86.570000  86.910004  85.449997  86.349998  86.349998

        Volume
0         1400
1        23100
2         2700
3         5300
4         2100
...        ...
5450   8340000
5451  18290000
5452  12960000
5453  10870000
5454  12090000

[5455 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5450    2021-08-30
5451    2021-08-31
5452    2021-09-01
5453    2021-09-02
5454    2021-09-03
Name: Date, Length: 5455, dtype: object
                   stock  start_date current_price   minall maxall  \
0  BOKF_ended_2021-09-25  1999-12-31         86.35  13.2162    107

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     9.37838   22.5946    31.973   41.3514   50.7297   60.1081   69.4865

  markup_70 markup_80 markup_90 markup_100
0   78.8649   88.2432   97.6216        107
                   stock  start_date current_price   minall maxall  \
0  BOKF_ended_2021-09-25  1999-12-31         86.35  13.2162    107

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     9.37838   22.5946    31.973   41.3514   50.7297   60.1081   69.4865

  markup_70 markup_80 markup_90 markup_100
0   78.8649   88.2432   97.6216        107
./ticker_data/ticker_data_2021-09-25 - Copy/BOLT_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2021-02-05  26.100000  33.959999  22.629999  32.150002  32.150002
1    2021-02-08  28.400000  34.880001  28.110001  32.599998  32.599998
2    2021-02-09  32.700001  34.500000  30.020000  33.900002  33.900002
3    2021-02-10  34.000000  35.195000  33.035000  34.540001  34.540001
4    2021-02-11  35.880001  35.880001  32.009998  34.509998  34.509998
..          ...        ...        ...        ...        ...        ...
142  2021-08-30  17.610001  17.790001  16.285000  16.940001  16.940001
143  2021-08-31  17.000000  18.200001  17.000000  17.760000  17.760000
144  2021-09-01  17.850000  18.500000  16.920000  17.360001  17.360001
145  2021-09-02  17.480000  18.440001  17.389999  18.240000  18.240000
146  2021-09-03  18.330000  18.834999  17.610001  18.600000  18.600000

       Volume
0     6910800
1      720400
2      623900
3      315200
4      488800
..        ...
142  30630000
143  23900000
144  23640000
145  21550000
146  31800000

[147 rows x 7 columns]
tolistdate: 0      2021-02-05
1      2021-02-08
2      2021-02-09
3      2021-02-10
4      2021-02-11
          ...
142    2021-08-30
143    2021-08-31
144    2021-09-01
145    2021-09-02
146    2021-09-03
Name: Date, Length: 147, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BOLT_ended_2021-09-25  2021-02-05          18.6  10.75  43.07       3.232

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.982    17.214    20.446    23.678     26.91    30.142    33.374

  markup_80 markup_90 markup_100
0    36.606    39.838      43.07
                   stock  start_date current_price minall maxall each_markup  \
0  BOLT_ended_2021-09-25  2021-02-05          18.6  10.75  43.07       3.232

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    13.982    17.214    20.446    23.678     26.91    30.142    33.374

  markup_80 markup_90 markup_100
0    36.606    39.838      43.07
./ticker_data/ticker_data_2021-09-25 - Copy/BOMN_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2017-06-13  22.000000  22.000000  22.000000  22.000000  22.000000
1     2017-06-14  22.000000  22.000000  22.000000  22.000000  22.000000
2     2017-06-16  13.000000  14.990000  12.960000  13.200000  13.200000
3     2017-06-19  17.260000  18.840000  13.270000  13.560000  13.560000
4     2017-06-20  13.250000  13.730000  13.050000  13.210000  13.210000
...          ...        ...        ...        ...        ...        ...
1059  2021-08-30  36.250000  36.744999  34.279999  35.075001  35.075001
1060  2021-08-31  34.840000  35.900002  34.689999  35.750000  35.750000
1061  2021-09-01  35.799999  36.283001  35.009998  35.169998  35.169998
1062  2021-09-02  35.400002  35.830002  34.990002  35.230000  35.230000
1063  2021-09-03  35.630001  35.630001  33.779999  33.880001  33.880001

        Volume
0          100
1            0
2       444100
3        87600
4        29200
...        ...
1059  13070000
1060  14380000
1061   9630000
1062   8260000
1063   9920000

[1064 rows x 7 columns]
tolistdate: 0       2017-06-13
1       2017-06-14
2       2017-06-16
3       2017-06-19
4       2017-06-20
           ...
1059    2021-08-30
1060    2021-08-31
1061    2021-09-01
1062    2021-09-02
1063    2021-09-03
Name: Date, Length: 1064, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BOMN_ended_2021-09-25  2017-06-13         33.88  12.15  49.92       3.777

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.927    19.704    23.481    27.258    31.035    34.812    38.589

  markup_80 markup_90 markup_100
0    42.366    46.143      49.92
                   stock  start_date current_price minall maxall each_markup  \
0  BOMN_ended_2021-09-25  2017-06-13         33.88  12.15  49.92       3.777

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.927    19.704    23.481    27.258    31.035    34.812    38.589

  markup_80 markup_90 markup_100
0    42.366    46.143      49.92
./ticker_data/ticker_data_2021-09-25 - Copy/BOOM_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   0.687500   0.687500   0.562500   0.593750   0.531738
1     2000-01-03   0.625000   1.375000   0.625000   0.937500   0.839587
2     2000-01-04   0.750000   1.062500   0.750000   1.062500   0.951532
3     2000-01-05   1.093750   1.125000   1.062500   1.062500   0.951532
4     2000-01-06   1.125000   1.125000   0.812500   0.968750   0.867573
...          ...        ...        ...        ...        ...        ...
5376  2021-08-30  41.509998  41.980000  39.689999  40.070000  40.070000
5377  2021-08-31  39.950001  41.840000  39.720001  40.169998  40.169998
5378  2021-09-01  40.209999  41.070000  39.279999  40.970001  40.970001
5379  2021-09-02  41.209999  41.810001  40.660000  40.779999  40.779999
5380  2021-09-03  40.720001  41.150002  39.500000  39.950001  39.950001

        Volume
0        91800
1       109600
2        36600
3        19000
4        40800
...        ...
5376  13170000
5377   9110000
5378   8610000
5379   4310000
5380   5550000

[5381 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5376    2021-08-30
5377    2021-08-31
5378    2021-09-01
5379    2021-09-02
5380    2021-09-03
Name: Date, Length: 5381, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BOOM_ended_2021-09-25  1999-12-31         39.95  0.375  76.68      7.6305

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    8.0055    15.636   23.2665    30.897   38.5275    46.158   53.7885

  markup_80 markup_90 markup_100
0    61.419   69.0495      76.68
                   stock  start_date current_price minall maxall each_markup  \
0  BOOM_ended_2021-09-25  1999-12-31         39.95  0.375  76.68      7.6305

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    8.0055    15.636   23.2665    30.897   38.5275    46.158   53.7885

  markup_80 markup_90 markup_100
0    61.419   69.0495      76.68
./ticker_data/ticker_data_2021-09-25 - Copy/BOSC_ended_2021-09-25.csv
            Date    Open    High     Low   Close  Adj Close    Volume
0     1999-12-31  660.00  660.00  620.00  655.00     655.00       100
1     2000-01-03  680.00  730.00  670.00  690.00     690.00      3300
2     2000-01-04  685.00  685.00  630.00  630.00     630.00       800
3     2000-01-05  620.00  645.00  600.00  605.00     605.00      1100
4     2000-01-06  612.50  620.00  600.00  605.00     605.00      1000
...          ...     ...     ...     ...     ...        ...       ...
5094  2021-08-30    4.26    4.31    4.02    4.05       4.05   8670000
5095  2021-08-31    4.21    4.29    4.01    4.11       4.11   7420000
5096  2021-09-01    4.07    4.15    4.00    4.08       4.08   2530000
5097  2021-09-02    4.04    4.30    4.04    4.16       4.16  11850000
5098  2021-09-03    4.20    4.20    4.15    4.17       4.17    650000

[5099 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5094    2021-08-30
5095    2021-08-31
5096    2021-09-01
5097    2021-09-02
5098    2021-09-03
Name: Date, Length: 5099, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BOSC_ended_2021-09-25  1999-12-31          4.17   1.02   1490     148.898

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   149.918   298.816   447.714   596.612    745.51   894.408   1043.31

  markup_80 markup_90 markup_100
0    1192.2    1341.1       1490
                   stock  start_date current_price minall maxall each_markup  \
0  BOSC_ended_2021-09-25  1999-12-31          4.17   1.02   1490     148.898

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   149.918   298.816   447.714   596.612    745.51   894.408   1043.31

  markup_80 markup_90 markup_100
0    1192.2    1341.1       1490

./ticker_data/ticker_data_2021-09-25 - Copy/BOTJ_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2000-08-10   3.816202   3.816202   3.816202   3.816202   3.323512
1     2000-08-11   3.816202   3.816202   3.816202   3.816202   3.323512
2     2000-08-16   4.163130   4.163130   3.816202   4.163130   3.625650
3     2000-08-17   4.163130   4.163130   4.163130   4.163130   3.625650
4     2000-09-08   3.816202   3.989666   3.816202   3.989666   3.474581
...          ...        ...        ...        ...        ...        ...
3630  2021-08-30  14.030000  14.050000  14.000000  14.000000  14.000000
3631  2021-08-31  14.000000  14.270000  14.000000  14.150000  14.150000
3632  2021-09-01  14.150000  14.150000  14.150000  14.150000  14.150000
3633  2021-09-02  14.450000  14.740000  14.250000  14.250000  14.250000
3634  2021-09-03  14.100000  14.100000  14.100000  14.100000  14.100000

      Volume
0        900
1          0
2        900
3          0
4      14100
...      ...
3630  120000
3631  150000
3632   40000
3633  250000
3634   70000

[3635 rows x 7 columns]
tolistdate: 0       2000-08-10
1       2000-08-11
2       2000-08-16
3       2000-08-17
4       2000-09-08
           ...
3630    2021-08-30
3631    2021-08-31
3632    2021-09-01
3633    2021-09-02
3634    2021-09-03
Name: Date, Length: 3635, dtype: object
                   stock  start_date current_price   minall   maxall  \
0  BOTJ_ended_2021-09-25  2000-08-10          14.1  1.81818  19.6818

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     1.78636   3.60455   5.39091   7.17727   8.96364     10.75   12.5364

  markup_70 markup_80 markup_90 markup_100
0   14.3227   16.1091   17.8955    19.6818
                   stock  start_date current_price   minall   maxall  \
0  BOTJ_ended_2021-09-25  2000-08-10          14.1  1.81818  19.6818

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     1.78636   3.60455   5.39091   7.17727   8.96364     10.75   12.5364

  markup_70 markup_80 markup_90 markup_100
0   14.3227   16.1091   17.8955    19.6818
./ticker_data/ticker_data_2021-09-25 - Copy/BOWXU_ended_2021-09-25.csv
           Date    Open    High     Low   Close  Adj Close    Volume
0    2020-08-05  10.020  10.050  10.010  10.030     10.030  10790100
1    2020-08-06  10.050  10.080  10.020  10.080     10.080    551900
2    2020-08-07  10.080  10.100  10.060  10.100     10.100    170000
3    2020-08-10  10.100  10.118  10.060  10.095     10.095     58100
4    2020-08-11  10.100  10.110  10.060  10.100     10.100    175300
..          ...     ...     ...     ...     ...        ...       ...
258  2021-08-23  10.445  10.500  10.400  10.460     10.460    300000
259  2021-08-24  10.790  10.790  10.314  10.314     10.314    440000
260  2021-08-25  10.314  10.314  10.314  10.314     10.314         0
261  2021-08-30  10.610  10.610  10.610  10.610     10.610     20000
262  2021-08-31  10.610  10.610  10.610  10.610     10.610         0

[263 rows x 7 columns]
tolistdate: 0      2020-08-05
1      2020-08-06
2      2020-08-07
3      2020-08-10
4      2020-08-11
          ...
258    2021-08-23
259    2021-08-24
260    2021-08-25
261    2021-08-30
262    2021-08-31
Name: Date, Length: 263, dtype: object
                    stock  start_date current_price minall  maxall  \
0  BOWXU_ended_2021-09-25  2020-08-05         10.61    9.9  14.945

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      0.5045   10.4045    10.909   11.4135    11.918   12.4225    12.927

  markup_70 markup_80 markup_90 markup_100
0   13.4315    13.936   14.4405     14.945
                    stock  start_date current_price minall  maxall  \
0  BOWXU_ended_2021-09-25  2020-08-05         10.61    9.9  14.945

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      0.5045   10.4045    10.909   11.4135    11.918   12.4225    12.927

  markup_70 markup_80 markup_90 markup_100
0   13.4315    13.936   14.4405     14.945
./ticker_data/ticker_data_2021-09-25 - Copy/BOWXW_ended_2021-09-25.csv
           Date  Open  High   Low  Close  Adj Close  Volume
0    2020-10-21  1.20  1.50  1.20   1.50       1.50    2100
1    2020-10-22  1.30  1.30  1.30   1.30       1.30    1000
2    2020-10-23  1.30  1.30  1.30   1.30       1.30       0
3    2020-10-26  1.28  1.28  1.28   1.28       1.28     500
4    2020-10-27  1.27  1.30  1.27   1.30       1.30    1400
..          ...   ...   ...   ...    ...        ...     ...
229  2021-09-20  1.82  1.97  1.82   1.96       1.96   79500
230  2021-09-21  2.09  2.09  1.96   2.06       2.06   29700
231  2021-09-22  2.06  2.15  2.00   2.05       2.05   43700
232  2021-09-23  2.18  2.18  2.09   2.15       2.15   42700
233  2021-09-24  1.82  2.18  2.00   2.12       2.12    9310

[234 rows x 7 columns]
tolistdate: 0      2020-10-21
1      2020-10-22
2      2020-10-23
3      2020-10-26
4      2020-10-27
          ...
229    2021-09-20
230    2021-09-21
231    2021-09-22
232    2021-09-23
233    2021-09-24
Name: Date, Length: 234, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BOWXW_ended_2021-09-25  2020-10-21          2.12   0.96   3.74       0.278

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.238     1.516     1.794     2.072      2.35     2.628     2.906

  markup_80 markup_90 markup_100
0     3.184     3.462       3.74
                    stock  start_date current_price minall maxall each_markup  \
0  BOWXW_ended_2021-09-25  2020-10-21          2.12   0.96   3.74       0.278

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.238     1.516     1.794     2.072      2.35     2.628     2.906

  markup_80 markup_90 markup_100
0     3.184     3.462       3.74
./ticker_data/ticker_data_2021-09-25 - Copy/BOWX_ended_2021-09-25.csv
           Date    Open    High    Low  Close  Adj Close    Volume
0    2020-10-21  10.000  10.000  9.800   9.80       9.80      5500
1    2020-10-22  10.300  10.300  9.820   9.82       9.82      1200
2    2020-10-23   9.820   9.820  9.820   9.82       9.82         0
3    2020-10-26   9.750   9.750  9.750   9.75       9.75       300
4    2020-10-27   9.750   9.750  9.750   9.75       9.75         0
..          ...     ...     ...    ...    ...        ...       ...
212  2021-08-30   9.910   9.950  9.910   9.92       9.92  25400000
213  2021-08-31   9.920   9.960  9.920   9.93       9.93  27950000
214  2021-09-01   9.930   9.950  9.920   9.94       9.94  26320000
215  2021-09-02   9.930   9.950  9.925   9.94       9.94  37030000
216  2021-09-03   9.957   9.975  9.930   9.94       9.94  23000000

[217 rows x 7 columns]
tolistdate: 0      2020-10-21
1      2020-10-22
2      2020-10-23
3      2020-10-26
4      2020-10-27
          ...
212    2021-08-30
213    2021-08-31
214    2021-09-01
215    2021-09-02
216    2021-09-03
Name: Date, Length: 217, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BOWX_ended_2021-09-25  2020-10-21          9.94   9.65  13.93       0.428

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.078    10.506    10.934    11.362     11.79    12.218    12.646

  markup_80 markup_90 markup_100
0    13.074    13.502      13.93
                   stock  start_date current_price minall maxall each_markup  \
0  BOWX_ended_2021-09-25  2020-10-21          9.94   9.65  13.93       0.428

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.078    10.506    10.934    11.362     11.79    12.218    12.646

  markup_80 markup_90 markup_100
0    13.074    13.502      13.93
./ticker_data/ticker_data_2021-09-25 - Copy/BOXL_ended_2021-09-25.csv
           Date   Open  High    Low  Close  Adj Close     Volume
0    2017-11-30  9.170  9.17  7.963  7.980      7.980      18900
1    2017-12-01  7.900  7.90  6.880  6.880      6.880       4900
2    2017-12-04  7.036  7.57  6.880  7.324      7.324       3900
3    2017-12-05  7.320  7.32  6.800  6.900      6.900      11700
4    2017-12-06  6.930  7.32  6.930  7.249      7.249       8700
..          ...    ...   ...    ...    ...        ...        ...
926  2021-08-30  2.560  2.67  2.465  2.610      2.610  232570000
927  2021-08-31  2.610  2.67  2.570  2.600      2.600  259970000
928  2021-09-01  2.590  2.72  2.535  2.600      2.600  276960000
929  2021-09-02  2.590  2.70  2.585  2.670      2.670  180650000
930  2021-09-03  2.660  2.67  2.530  2.600      2.600  226830000

[931 rows x 7 columns]
tolistdate: 0      2017-11-30
1      2017-12-01
2      2017-12-04
3      2017-12-05
4      2017-12-06
          ...
926    2021-08-30
927    2021-08-31
928    2021-09-01
929    2021-09-02
930    2021-09-03
Name: Date, Length: 931, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BOXL_ended_2021-09-25  2017-11-30           2.6   0.33   17.4       1.707

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.037     3.744     5.451     7.158     8.865    10.572    12.279

  markup_80 markup_90 markup_100
0    13.986    15.693       17.4
                   stock  start_date current_price minall maxall each_markup  \
0  BOXL_ended_2021-09-25  2017-11-30           2.6   0.33   17.4       1.707

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     2.037     3.744     5.451     7.158     8.865    10.572    12.279

  markup_80 markup_90 markup_100
0    13.986    15.693       17.4
./ticker_data/ticker_data_2021-09-25 - Copy/BPMC_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2015-04-30  23.400000  23.889999  18.000000  18.870001  18.870001
1     2015-05-01  18.790001  20.469999  18.530001  18.530001  18.530001
2     2015-05-04  18.600000  20.820000  18.600000  20.809999  20.809999
3     2015-05-05  20.500000  21.170000  20.160000  20.820000  20.820000
4     2015-05-06  20.950001  21.850000  20.500000  21.370001  21.370001
...          ...        ...        ...        ...        ...        ...
1594  2021-08-30  94.269997  95.160004  93.269997  94.050003  94.050003
1595  2021-08-31  94.419998  95.190002  92.370003  93.269997  93.269997
1596  2021-09-01  93.750000  96.279999  93.750000  96.129997  96.129997
1597  2021-09-02  96.690002  98.620003  95.250000  98.599998  98.599998
1598  2021-09-03  98.209999  99.230003  97.580002  97.809998  97.809998

        Volume
0      7157700
1       511400
2       432400
3       213900
4       243500
...        ...
1594  47190000
1595  53860000
1596  79630000
1597  34020000
1598  41390000

[1599 rows x 7 columns]
tolistdate: 0       2015-04-30
1       2015-05-01
2       2015-05-04
3       2015-05-05
4       2015-05-06
           ...
1594    2021-08-30
1595    2021-08-31
1596    2021-09-01
1597    2021-09-02
1598    2021-09-03
Name: Date, Length: 1599, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BPMC_ended_2021-09-25  2015-04-30         97.81  13.04  125.61      11.257

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    24.297    35.554    46.811    58.068    69.325    80.582    91.839

  markup_80 markup_90 markup_100
0   103.096   114.353     125.61
                   stock  start_date current_price minall  maxall each_markup  \
0  BPMC_ended_2021-09-25  2015-04-30         97.81  13.04  125.61      11.257

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    24.297    35.554    46.811    58.068    69.325    80.582    91.839

  markup_80 markup_90 markup_100
0   103.096   114.353     125.61
./ticker_data/ticker_data_2021-09-25 - Copy/BPOPM_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2008-11-19  19.000000  19.010000  19.000000  19.000000   7.705999
1     2008-11-20  19.920000  19.959999  19.010000  19.740000   8.006123
2     2008-11-21  19.030001  19.030001  19.000000  19.000000   7.705999
3     2008-11-24  19.000000  19.000000  19.000000  19.000000   7.705999
4     2008-11-25  19.010000  19.010000  19.010000  19.010000   7.710051
...          ...        ...        ...        ...        ...        ...
3038  2021-09-20  27.480000  27.480000  27.480000  27.480000  27.480000
3039  2021-09-21  27.400000  27.400000  26.950001  27.290001  27.290001
3040  2021-09-22  27.010000  27.500000  26.910000  27.469999  27.469999
3041  2021-09-23  27.410000  27.670000  27.410000  27.639999  27.639999
3042  2021-09-24  27.410000  27.410000  27.410000  27.410000  27.410000

      Volume
0       2000
1       3100
2       1000
3          0
4        200
...      ...
3038       0
3039    5000
3040    4000
3041    2300
3042       1

[3043 rows x 7 columns]
tolistdate: 0       2008-11-19
1       2008-11-20
2       2008-11-21
3       2008-11-24
4       2008-11-25
           ...
3038    2021-09-20
3039    2021-09-21
3040    2021-09-22
3041    2021-09-23
3042    2021-09-24
Name: Date, Length: 3043, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BPOPM_ended_2021-09-25  2008-11-19         27.41   4.26  28.81       2.455

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.715      9.17    11.625     14.08    16.535     18.99    21.445

  markup_80 markup_90 markup_100
0      23.9    26.355      28.81
                    stock  start_date current_price minall maxall each_markup  \
0  BPOPM_ended_2021-09-25  2008-11-19         27.41   4.26  28.81       2.455

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.715      9.17    11.625     14.08    16.535     18.99    21.445

  markup_80 markup_90 markup_100
0      23.9    26.355      28.81
./ticker_data/ticker_data_2021-09-25 - Copy/BPOPN_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2003-12-02  25.000000  25.000000  24.750000  24.750000   6.650838
1     2003-12-03  25.000000  25.000000  25.000000  25.000000   6.718018
2     2003-12-04  25.100000  25.100000  25.100000  25.100000   6.744888
3     2003-12-08  25.120001  25.250000  25.000000  25.200001   6.771758
4     2003-12-09  25.250000  25.650000  25.250000  25.250000   6.785196
...          ...        ...        ...        ...        ...        ...
4357  2021-08-30  27.230000  27.230000  27.230000  27.230000  27.230000
4358  2021-08-31  27.209999  27.209999  27.170000  27.170000  27.170000
4359  2021-09-01  27.100000  27.340000  27.080000  27.340000  27.340000
4360  2021-09-02  27.469999  27.969999  27.219999  27.969999  27.969999
4361  2021-09-03  28.020000  28.540001  27.770000  27.990000  27.990000

         Volume
0        2900.0
1        1800.0
2        1900.0
3       27600.0
4        6900.0
...         ...
4357    60000.0
4358   210000.0
4359   510000.0
4360  1350000.0
4361   330000.0

[4362 rows x 7 columns]
tolistdate: 0       2003-12-02
1       2003-12-03
2       2003-12-04
3       2003-12-08
4       2003-12-09
           ...
4357    2021-08-30
4358    2021-08-31
4359    2021-09-01
4360    2021-09-02
4361    2021-09-03
Name: Date, Length: 4362, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BPOPN_ended_2021-09-25  2003-12-02         27.99   9.71  31.97       2.226

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.936    14.162    16.388    18.614     20.84    23.066    25.292

  markup_80 markup_90 markup_100
0    27.518    29.744      31.97
                    stock  start_date current_price minall maxall each_markup  \
0  BPOPN_ended_2021-09-25  2003-12-02         27.99   9.71  31.97       2.226

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.936    14.162    16.388    18.614     20.84    23.066    25.292

  markup_80 markup_90 markup_100
0    27.518    29.744      31.97
./ticker_data/ticker_data_2021-09-25 - Copy/BPOP_ended_2021-09-25.csv
            Date        Open        High         Low       Close  Adj Close  \
0     1999-12-31  129.375000  141.250000  129.375000  139.687500  88.669518
1     2000-01-03  138.906250  140.000000  128.125000  134.375000  85.297287
2     2000-01-04  131.562500  136.250000  126.250000  130.000000  82.520180
3     2000-01-05  130.312500  133.750000  124.375000  125.312500  79.544693
4     2000-01-06  124.687500  127.187500  122.812500  124.687500  79.147957
...          ...         ...         ...         ...         ...        ...
5451  2021-08-30   77.309998   77.309998   75.889999   75.980003  75.980003
5452  2021-08-31   76.290001   77.120003   75.699997   75.940002  75.940002
5453  2021-09-01   76.110001   76.110001   74.489998   74.940002  74.940002
5454  2021-09-02   75.150002   75.540001   74.570000   75.480003  75.480003
5455  2021-09-03   76.449997   76.449997   74.260002   74.750000  74.750000

          Volume
0        13800.0
1        11900.0
2        28900.0
3        25300.0
4        37600.0
...          ...
5451  70090000.0
5452  40400000.0
5453  77700000.0
5454  38810000.0
5455  31530000.0

[5456 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5451    2021-08-30
5452    2021-08-31
5453    2021-09-01
5454    2021-09-02
5455    2021-09-03
Name: Date, Length: 5456, dtype: object

                   stock  start_date current_price minall maxall each_markup  \
0  BPOP_ended_2021-09-25  1999-12-31         74.75     10    290          28

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0        38        66        94       122       150       178       206

  markup_80 markup_90 markup_100
0       234       262        290
                   stock  start_date current_price minall maxall each_markup  \
0  BPOP_ended_2021-09-25  1999-12-31         74.75     10    290          28

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0        38        66        94       122       150       178       206

  markup_80 markup_90 markup_100
0       234       262        290
./ticker_data/ticker_data_2021-09-25 - Copy/BPRN_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2017-05-31  32.610001  32.610001  32.610001  32.610001  31.455797
1     2017-06-01  33.000000  33.000000  33.000000  33.000000  31.831989
2     2017-06-02  33.000000  33.000000  33.000000  33.000000  31.831989
3     2017-07-03  33.000000  33.000000  33.000000  33.000000  31.831989
4     2017-07-24  33.500000  33.500000  33.250000  33.250000  32.073147
...          ...        ...        ...        ...        ...        ...
1034  2021-08-30  30.500000  30.575001  30.450001  30.469999  30.469999
1035  2021-08-31  30.340000  30.730000  30.340000  30.500000  30.500000
1036  2021-09-01  30.440001  30.500000  29.600000  30.250000  30.250000
1037  2021-09-02  30.125000  30.480000  30.040001  30.040001  30.040001
1038  2021-09-03  30.315001  30.315001  30.160000  30.160000  30.160000

       Volume
0         800
1         200
2           0
3         600
4        1100
...       ...
1034   300000
1035  1060000
1036   740000
1037   140000
1038   170000

[1039 rows x 7 columns]
tolistdate: 0       2017-05-31
1       2017-06-01
2       2017-06-02
3       2017-07-03
4       2017-07-24
           ...
1034    2021-08-30
1035    2021-08-31
1036    2021-09-01
1037    2021-09-02
1038    2021-09-03
Name: Date, Length: 1039, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BPRN_ended_2021-09-25  2017-05-31         30.16   17.4     39        2.16

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     19.56     21.72     23.88     26.04      28.2     30.36     32.52

  markup_80 markup_90 markup_100
0     34.68     36.84         39
                   stock  start_date current_price minall maxall each_markup  \
0  BPRN_ended_2021-09-25  2017-05-31         30.16   17.4     39        2.16

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     19.56     21.72     23.88     26.04      28.2     30.36     32.52

  markup_80 markup_90 markup_100
0     34.68     36.84         39
./ticker_data/ticker_data_2021-09-25 - Copy/BPTH_ended_2021-09-25.csv
            Date    Open    High     Low   Close  Adj Close  Volume
0     2008-03-04  180.00  180.00  180.00  180.00     180.00      17
1     2008-03-05  104.00  104.00  104.00  104.00     104.00       2
2     2008-03-06  104.00  104.00  104.00  104.00     104.00       0
3     2008-03-07  180.00  180.00  180.00  180.00     180.00       5
4     2008-03-10  180.00  180.00  180.00  180.00     180.00       0
...          ...     ...     ...     ...     ...        ...     ...
3090  2021-09-20    5.34    5.45    5.23    5.26       5.26   58800
3091  2021-09-21    5.25    5.37    5.18    5.29       5.29   41700
3092  2021-09-22    5.33    5.45    5.26    5.42       5.42   43700
3093  2021-09-23    5.43    5.48    5.32    5.39       5.39   56700
3094  2021-09-24    5.35    5.40    5.22    5.34       5.34   27993

[3095 rows x 7 columns]
tolistdate: 0       2008-03-04
1       2008-03-05
2       2008-03-06
3       2008-03-07
4       2008-03-10
           ...
3090    2021-09-20
3091    2021-09-21
3092    2021-09-22
3093    2021-09-23
3094    2021-09-24
Name: Date, Length: 3095, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BPTH_ended_2021-09-25  2008-03-04          5.34   1.61   1200     119.839

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   121.449   241.288   361.127   480.966   600.805   720.644   840.483

  markup_80 markup_90 markup_100
0   960.322   1080.16       1200
                   stock  start_date current_price minall maxall each_markup  \
0  BPTH_ended_2021-09-25  2008-03-04          5.34   1.61   1200     119.839

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   121.449   241.288   361.127   480.966   600.805   720.644   840.483

  markup_80 markup_90 markup_100
0   960.322   1080.16       1200
./ticker_data/ticker_data_2021-09-25 - Copy/BPTS_ended_2021-09-25.csv
           Date       Open       High    Low  Close  Adj Close   Volume
0    2021-02-10  18.500000  18.500000  14.72  16.50      16.50  1128500
1    2021-02-11  16.350000  17.000000  15.55  16.75      16.75   308000
2    2021-02-12  16.850000  17.030001  16.50  17.02      17.02   165300
3    2021-02-16  16.700001  16.700001  15.46  15.53      15.53    54500
4    2021-02-17  15.630000  15.630000  14.90  15.30      15.30    30300
..          ...        ...        ...    ...    ...        ...      ...
119  2021-08-25   8.580000   8.580000   8.58   8.58       8.58        0
120  2021-08-26   9.020000   9.020000   9.02   9.02       9.02    30000
121  2021-08-27   9.020000   9.020000   9.02   9.02       9.02        0
122  2021-09-02   9.160000   9.600000   9.16   9.30       9.30   140000
123  2021-09-03   9.300000   9.300000   9.30   9.30       9.30        0

[124 rows x 7 columns]
tolistdate: 0      2021-02-10
1      2021-02-11
2      2021-02-12
3      2021-02-16
4      2021-02-17
          ...
119    2021-08-25
120    2021-08-26
121    2021-08-27
122    2021-09-02
123    2021-09-03
Name: Date, Length: 124, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BPTS_ended_2021-09-25  2021-02-10           9.3    8.2   18.5        1.03

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.23     10.26     11.29     12.32     13.35     14.38     15.41

  markup_80 markup_90 markup_100
0     16.44     17.47       18.5
                   stock  start_date current_price minall maxall each_markup  \
0  BPTS_ended_2021-09-25  2021-02-10           9.3    8.2   18.5        1.03

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      9.23     10.26     11.29     12.32     13.35     14.38     15.41

  markup_80 markup_90 markup_100
0     16.44     17.47       18.5
./ticker_data/ticker_data_2021-09-25 - Copy/BPYPN_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-02-11  25.190001  25.379999  25.190001  25.350000  23.086535
1    2020-02-12  25.549999  25.549999  25.299999  25.379999  23.113855
2    2020-02-13  25.379999  25.379999  25.250000  25.379999  23.113855
3    2020-02-14  25.379999  25.450001  25.360001  25.370001  23.104748
4    2020-02-18  25.385000  25.430000  25.350000  25.400000  23.132069
..          ...        ...        ...        ...        ...        ...
390  2021-08-30  24.840000  24.886000  24.795000  24.850000  24.850000
391  2021-08-31  24.639999  24.662001  24.450001  24.450001  24.450001
392  2021-09-01  24.430000  24.730000  24.430000  24.670000  24.670000
393  2021-09-02  24.608000  24.620001  24.540001  24.610001  24.610001
394  2021-09-03  24.589001  24.610001  24.580000  24.610001  24.610001

      Volume
0    1377100
1     410800
2     121600
3     128100
4     111800
..       ...
390  2070000
391  5330000
392   760000
393  1200000
394   180000

[395 rows x 7 columns]
tolistdate: 0      2020-02-11
1      2020-02-12
2      2020-02-13
3      2020-02-14
4      2020-02-18
          ...
390    2021-08-30
391    2021-08-31
392    2021-09-01
393    2021-09-02
394    2021-09-03
Name: Date, Length: 395, dtype: object
                    stock  start_date current_price minall  maxall  \
0  BPYPN_ended_2021-09-25  2020-02-11         24.61      8  25.594

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      1.7594    9.7594   11.5188   13.2782   15.0376    16.797   18.5564

  markup_70 markup_80 markup_90 markup_100
0   20.3158   22.0752   23.8346     25.594
                    stock  start_date current_price minall  maxall  \
0  BPYPN_ended_2021-09-25  2020-02-11         24.61      8  25.594

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      1.7594    9.7594   11.5188   13.2782   15.0376    16.797   18.5564

  markup_70 markup_80 markup_90 markup_100
0   20.3158   22.0752   23.8346     25.594
./ticker_data/ticker_data_2021-09-25 - Copy/BPYPO_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  Volume
0    2019-08-21  25.200001  25.280001  25.180000  25.230000  21.534103  261000
1    2019-08-22  25.250000  25.350000  25.230000  25.347000  21.633966  156700
2    2019-08-23  25.260000  25.350000  25.230000  25.247000  21.548615   81900
3    2019-08-26  25.370001  25.370001  25.250000  25.350000  21.636524  131100
4    2019-08-27  25.400000  25.400000  25.250000  25.290001  21.585318  112700
..          ...        ...        ...        ...        ...        ...     ...
524  2021-09-20  24.990000  25.080000  24.840000  24.969999  24.969999   11500
525  2021-09-21  25.020000  25.020000  24.910000  24.980000  24.980000    5600
526  2021-09-22  25.020000  25.309999  25.020000  25.309999  25.309999   12700
527  2021-09-23  25.340000  25.340000  25.129999  25.209999  25.209999    4600
528  2021-09-24  25.190001  25.190001  25.110001  25.110001  25.110001    2214

[529 rows x 7 columns]
tolistdate: 0      2019-08-21
1      2019-08-22
2      2019-08-23
3      2019-08-26
4      2019-08-27
          ...
524    2021-09-20
525    2021-09-21
526    2021-09-22
527    2021-09-23
528    2021-09-24
Name: Date, Length: 529, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BPYPO_ended_2021-09-25  2019-08-21         25.11   8.13  27.52       1.939

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.069    12.008    13.947    15.886    17.825    19.764    21.703

  markup_80 markup_90 markup_100
0    23.642    25.581      27.52
                    stock  start_date current_price minall maxall each_markup  \
0  BPYPO_ended_2021-09-25  2019-08-21         25.11   8.13  27.52       1.939

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.069    12.008    13.947    15.886    17.825    19.764    21.703

  markup_80 markup_90 markup_100
0    23.642    25.581      27.52
./ticker_data/ticker_data_2021-09-25 - Copy/BPYPP_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-03-14  24.629999  24.629999  24.629999  24.629999  21.150820
1    2019-03-15  24.830000  24.850000  24.750000  24.799999  21.296803
2    2019-03-18  24.799999  24.879999  24.775000  24.820000  21.313982
3    2019-03-19  24.850000  24.885000  24.799999  24.850000  21.339741
4    2019-03-20  24.850000  24.850000  24.600000  24.820000  21.313982
..          ...        ...        ...        ...        ...        ...
620  2021-08-30  26.530001  26.530001  26.290001  26.520000  26.520000
621  2021-08-31  26.400000  26.400000  26.190001  26.260000  26.260000
622  2021-09-01  26.219999  26.480000  26.141001  26.430000  26.430000
623  2021-09-02  26.260000  26.500000  26.200001  26.480000  26.480000
624  2021-09-03  26.320000  26.530001  26.320000  26.450001  26.450001

      Volume
0     369000
1    2741900
2     677700
3     375900
4      67800
..       ...
620   640000
621  1860000
622   440000
623  1870000
624   910000

[625 rows x 7 columns]
tolistdate: 0      2019-03-14
1      2019-03-15
2      2019-03-18
3      2019-03-19
4      2019-03-20
          ...
620    2021-08-30
621    2021-08-31
622    2021-09-01
623    2021-09-02
624    2021-09-03
Name: Date, Length: 625, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BPYPP_ended_2021-09-25  2019-03-14         26.45     11  27.22       1.622

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.622    14.244    15.866    17.488     19.11    20.732    22.354

  markup_80 markup_90 markup_100
0    23.976    25.598      27.22
                    stock  start_date current_price minall maxall each_markup  \
0  BPYPP_ended_2021-09-25  2019-03-14         26.45     11  27.22       1.622

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.622    14.244    15.866    17.488     19.11    20.732    22.354

  markup_80 markup_90 markup_100
0    23.976    25.598      27.22
./ticker_data/ticker_data_2021-09-25 - Copy/BPYUP_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-08-29  24.170000  24.700001  24.170000  24.700001  20.064796
1    2018-08-30  24.700001  24.700001  24.530001  24.700001  20.064796
2    2018-08-31  24.750000  24.950001  24.680000  24.830000  20.170403
3    2018-09-04  24.820000  24.900000  24.570000  24.650000  20.024176
4    2018-09-05  24.559999  24.900000  24.549999  24.900000  20.227261
..          ...        ...        ...        ...        ...        ...
742  2021-08-12  25.180000  25.190001  25.170000  25.190001  25.190001
743  2021-08-13  25.180000  25.200001  25.170000  25.180000  25.180000
744  2021-08-16  25.180000  25.200001  25.180000  25.190001  25.190001
745  2021-08-17  25.190001  25.209999  25.190001  25.200001  25.200001
746  2021-08-18  25.209999  25.209999  25.190001  25.200001  25.200001

       Volume
0        3800
1       14000
2       14400
3       14200
4       11500
..        ...
742   2270000
743   5660000
744   1400000
745  24150000
746   2870000

[747 rows x 7 columns]
tolistdate: 0      2018-08-29
1      2018-08-30
2      2018-08-31
3      2018-09-04
4      2018-09-05
          ...
742    2021-08-12
743    2021-08-13
744    2021-08-16
745    2021-08-17
746    2021-08-18
Name: Date, Length: 747, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BPYUP_ended_2021-09-25  2018-08-29          25.2   6.63  25.88       1.925

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.555     10.48    12.405     14.33    16.255     18.18    20.105

  markup_80 markup_90 markup_100
0     22.03    23.955      25.88
                    stock  start_date current_price minall maxall each_markup  \
0  BPYUP_ended_2021-09-25  2018-08-29          25.2   6.63  25.88       1.925

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.555     10.48    12.405     14.33    16.255     18.18    20.105

  markup_80 markup_90 markup_100
0     22.03    23.955      25.88
./ticker_data/ticker_data_2021-09-25 - Copy/BPYU_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-08-28  21.000000  21.160000  20.410000  20.799999  16.756809
1    2018-08-29  20.799999  20.930000  20.570000  20.639999  16.627914
2    2018-08-30  20.350000  20.580000  20.080000  20.250000  16.566559
3    2018-08-31  20.000000  20.420000  19.900000  20.020000  16.378395
4    2018-09-04  19.950001  19.950001  19.389999  19.459999  15.920254
..          ...        ...        ...        ...        ...        ...
728  2021-07-21  18.480000  18.790001  18.370001  18.650000  18.650000
729  2021-07-22  18.600000  18.750000  18.510000  18.709999  18.709999
730  2021-07-23  18.790001  18.799999  18.610001  18.680000  18.680000
731  2021-07-26  18.485001  18.750000  18.485001  18.520000  18.520000
732  2021-07-28  18.520000  18.520000  18.520000  18.520000  18.520000

       Volume
0    13771100
1     3663700
2     5911600
3    10581800
4     4864200
..        ...
728    965400
729    638800
730    638200
731   9382235
732         0

[733 rows x 7 columns]
tolistdate: 0      2018-08-28
1      2018-08-29
2      2018-08-30
3      2018-08-31
4      2018-09-04
          ...
728    2021-07-21
729    2021-07-22
730    2021-07-23
731    2021-07-26
732    2021-07-28
Name: Date, Length: 733, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BPYU_ended_2021-09-25  2018-08-28         18.52   7.15  21.19       1.404

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.554     9.958    11.362    12.766     14.17    15.574    16.978

  markup_80 markup_90 markup_100
0    18.382    19.786      21.19
                   stock  start_date current_price minall maxall each_markup  \
0  BPYU_ended_2021-09-25  2018-08-28         18.52   7.15  21.19       1.404

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.554     9.958    11.362    12.766     14.17    15.574    16.978

  markup_80 markup_90 markup_100
0    18.382    19.786      21.19
./ticker_data/ticker_data_2021-09-25 - Copy/BPY_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2013-04-12  22.270000  22.270000  20.900000  21.110001  12.427116
1     2013-04-15  21.639999  22.440001  21.280001  22.309999  13.133539
2     2013-04-16  22.010000  22.270000  21.760000  22.049999  12.980477
3     2013-04-17  22.040001  22.600000  21.809999  21.930000  12.909839
4     2013-04-18  22.230000  22.230000  21.540001  21.690001  12.768551
...          ...        ...        ...        ...        ...        ...
2102  2021-08-31   1.100000   1.100000   1.100000   1.100000   1.100000
2103  2021-09-07   1.120000   1.120000   1.120000   1.120000   1.120000
2104  2021-09-08   1.100000   1.100000   1.090000   1.100000   1.100000
2105  2021-09-15   1.080000   1.080000   1.080000   1.080000   1.080000
2106  2021-09-20   1.080000   1.080000   1.080000   1.080000   1.080000

         Volume
0      964800.0
1     1701700.0
2     1170900.0
3      744900.0
4      481400.0
...         ...
2102     4000.0
2103      270.0
2104    12825.0
2105      500.0
2106      450.0

[2107 rows x 7 columns]
tolistdate: 0       2013-04-12
1       2013-04-15
2       2013-04-16
3       2013-04-17
4       2013-04-18
           ...
2102    2021-08-31
2103    2021-09-07
2104    2021-09-08
2105    2021-09-15
2106    2021-09-20
Name: Date, Length: 2107, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  BPY_ended_2021-09-25  2013-04-12          1.08   1.08  26.54       2.546

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.626     6.172     8.718    11.264     13.81    16.356    18.902

  markup_80 markup_90 markup_100
0    21.448    23.994      26.54
                  stock  start_date current_price minall maxall each_markup  \
0  BPY_ended_2021-09-25  2013-04-12          1.08   1.08  26.54       2.546

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.626     6.172     8.718    11.264     13.81    16.356    18.902

  markup_80 markup_90 markup_100
0    21.448    23.994      26.54
./ticker_data/ticker_data_2021-09-25 - Copy/BRCN_ended_2021-09-25.csv
           Date  Open  High   Low  Close  Adj Close   Volume
0    2020-11-27  1.74  1.89  1.74   1.85       1.85    55600
1    2020-11-30  1.85  1.86  1.80   1.84       1.84    32900
2    2020-12-01  1.77  1.87  1.77   1.87       1.87    25600
3    2020-12-02  1.86  1.88  1.80   1.88       1.88    29000
4    2020-12-03  1.88  1.88  1.83   1.84       1.84    71800
..          ...   ...   ...   ...    ...        ...      ...
113  2021-08-30  2.41  2.41  2.29   2.29       2.29  1700000
114  2021-08-31  2.32  2.45  2.27   2.45       2.45  2800000

Name: Date, Length: 118, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BRCN_ended_2021-09-25  2020-11-27          2.43   1.74   4.29       0.255

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.995      2.25     2.505      2.76     3.015      3.27     3.525

  markup_80 markup_90 markup_100
0      3.78     4.035       4.29
                   stock  start_date current_price minall maxall each_markup  \
0  BRCN_ended_2021-09-25  2020-11-27          2.43   1.74   4.29       0.255

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.995      2.25     2.505      2.76     3.015      3.27     3.525

  markup_80 markup_90 markup_100
0      3.78     4.035       4.29
./ticker_data/ticker_data_2021-09-25 - Copy/BREZR_ended_2021-09-25.csv
         Date   Open  High   Low  Close  Adj Close  Volume
0  2021-09-22  0.189   0.2  0.19    0.2        0.2   11639
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BREZR_ended_2021-09-25  2021-09-22           0.2   0.19    0.2       0.001

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.191     0.192     0.193     0.194     0.195     0.196     0.197

  markup_80 markup_90 markup_100
0     0.198     0.199        0.2
                    stock  start_date current_price minall maxall each_markup  \
0  BREZR_ended_2021-09-25  2021-09-22           0.2   0.19    0.2       0.001

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.191     0.192     0.193     0.194     0.195     0.196     0.197

  markup_80 markup_90 markup_100
0     0.198     0.199        0.2
./ticker_data/ticker_data_2021-09-25 - Copy/BREZW_ended_2021-09-25.csv
         Date  Open  High     Low   Close  Adj Close  Volume
0  2021-09-22  0.55  0.49  0.4897  0.4897     0.4897    9667
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price  minall maxall  \
0  BREZW_ended_2021-09-25  2021-09-22        0.4897  0.4897   0.49

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0  3.0002e-05   0.48973   0.48976   0.48979   0.48982   0.48985   0.48988

  markup_70 markup_80 markup_90 markup_100
0   0.48991   0.48994   0.48997       0.49
                    stock  start_date current_price  minall maxall  \
0  BREZW_ended_2021-09-25  2021-09-22        0.4897  0.4897   0.49

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0  3.0002e-05   0.48973   0.48976   0.48979   0.48982   0.48985   0.48988

  markup_70 markup_80 markup_90 markup_100
0   0.48991   0.48994   0.48997       0.49
./ticker_data/ticker_data_2021-09-25 - Copy/BREZ_ended_2021-09-25.csv
           Date    Open    High    Low  Close  Adj Close   Volume
0    2020-11-24  10.050  10.050  10.04  10.04      10.04    60700
1    2020-11-25  10.047  10.121  10.04  10.09      10.09    56100
2    2020-11-27  10.130  10.130  10.05  10.09      10.09    27700
3    2020-11-30  10.040  10.130  10.03  10.10      10.10    18500
4    2020-12-01  10.080  10.100  10.06  10.09      10.09    20600
..          ...     ...     ...    ...    ...        ...      ...
170  2021-08-30  10.050  10.070  10.05  10.06      10.06   210000
171  2021-08-31  10.050  10.068  10.05  10.05      10.05   240000
172  2021-09-01  10.051  10.051  10.05  10.05      10.05   550000
173  2021-09-02  10.050  10.060  10.05  10.06      10.06  2180000
174  2021-09-03  10.090  10.090  10.09  10.09      10.09    40000

[175 rows x 7 columns]
tolistdate: 0      2020-11-24
1      2020-11-25
2      2020-11-27
3      2020-11-30
4      2020-12-01
          ...
170    2021-08-30
171    2021-08-31
172    2021-09-01
173    2021-09-02
174    2021-09-03
Name: Date, Length: 175, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BREZ_ended_2021-09-25  2020-11-24         10.09   9.82     16       0.618

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.438    11.056    11.674    12.292     12.91    13.528    14.146

  markup_80 markup_90 markup_100
0    14.764    15.382         16
                   stock  start_date current_price minall maxall each_markup  \
0  BREZ_ended_2021-09-25  2020-11-24         10.09   9.82     16       0.618

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.438    11.056    11.674    12.292     12.91    13.528    14.146

  markup_80 markup_90 markup_100
0    14.764    15.382         16
./ticker_data/ticker_data_2021-09-25 - Copy/BRID_ended_2021-09-25.csv
            Date     Open     High     Low    Close  Adj Close  Volume
0     1999-12-31   9.6875   9.6875   9.500   9.6875   8.637792    9700
1     2000-01-03   9.6250   9.7500   9.375   9.6875   8.637792  107000
2     2000-01-04   9.4375   9.6250   9.000   9.2500   8.247696  103000
3     2000-01-05   8.8750   9.1250   8.875   9.1250   8.136243    1900
4     2000-01-06   8.8750   9.5000   8.875   9.0000   8.024785   77400
...          ...      ...      ...     ...      ...        ...     ...
4798  2021-08-30  13.2000  13.2000  13.200  13.2000  13.200000   40000
4799  2021-08-31  13.0200  13.0200  12.950  12.9500  12.950000  190000
4800  2021-09-01  13.0600  13.2000  12.890  13.2000  13.200000  100000
4801  2021-09-02  13.1800  13.3000  12.900  13.1900  13.190000  170000
4802  2021-09-03  12.9200  13.2900  12.900  13.0500  13.050000  320000

[4803 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
4798    2021-08-30
4799    2021-08-31
4800    2021-09-01
4801    2021-09-02
4802    2021-09-03
Name: Date, Length: 4803, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BRID_ended_2021-09-25  1999-12-31         13.05   2.53     38       3.547

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.077     9.624    13.171    16.718    20.265    23.812    27.359

  markup_80 markup_90 markup_100
0    30.906    34.453         38
                   stock  start_date current_price minall maxall each_markup  \
0  BRID_ended_2021-09-25  1999-12-31         13.05   2.53     38       3.547

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.077     9.624    13.171    16.718    20.265    23.812    27.359

  markup_80 markup_90 markup_100
0    30.906    34.453         38
./ticker_data/ticker_data_2021-09-25 - Copy/BRIVU_ended_2021-09-25.csv
          Date    Open    High    Low   Close  Adj Close   Volume
0   2021-05-07  10.000  10.010  9.970  10.000     10.000  3463600
1   2021-05-10  10.000  10.000  9.960  10.000     10.000   484800
2   2021-05-11   9.970  10.000  9.970   9.990      9.990    75800
3   2021-05-12   9.970  10.000  9.970  10.000     10.000    17000
4   2021-05-13  10.030  10.030  9.970   9.990      9.990    30000
..         ...     ...     ...    ...     ...        ...      ...
68  2021-08-26   9.905   9.905  9.905   9.905      9.905   100000
69  2021-08-27   9.905   9.905  9.905   9.905      9.905    50000
70  2021-08-30   9.905   9.905  9.905   9.905      9.905        0
71  2021-09-01   9.905   9.960  9.905   9.950      9.950   340000
72  2021-09-03   9.885   9.885  9.885   9.885      9.885    50000

[73 rows x 7 columns]
tolistdate: 0     2021-05-07
1     2021-05-10
2     2021-05-11
3     2021-05-12
4     2021-05-13
         ...
68    2021-08-26
69    2021-08-27
70    2021-08-30
71    2021-09-01
72    2021-09-03
Name: Date, Length: 73, dtype: object
                    stock  start_date current_price minall  maxall  \
0  BRIVU_ended_2021-09-25  2021-05-07         9.885  9.885  10.083

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      0.0198    9.9048    9.9246    9.9444    9.9642     9.984   10.0038

  markup_70 markup_80 markup_90 markup_100
0   10.0236   10.0434   10.0632     10.083
                    stock  start_date current_price minall  maxall  \
0  BRIVU_ended_2021-09-25  2021-05-07         9.885  9.885  10.083

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      0.0198    9.9048    9.9246    9.9444    9.9642     9.984   10.0038

  markup_70 markup_80 markup_90 markup_100
0   10.0236   10.0434   10.0632     10.083
./ticker_data/ticker_data_2021-09-25 - Copy/BRKL_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31   4.515318   4.529607   4.458162   4.458162   1.905152
1     2000-01-03   4.458162   4.501029   4.401006   4.401006   1.880728
2     2000-01-04   4.451017   4.458162   4.343850   4.343850   1.856303
3     2000-01-05   4.343850   4.443873   4.343850   4.343850   1.856303
4     2000-01-06   4.372428   4.401006   4.315272   4.358139   1.862408
...          ...        ...        ...        ...        ...        ...
5449  2021-08-30  14.980000  14.980000  14.680000  14.750000  14.750000
5450  2021-08-31  14.850000  15.010000  14.710000  14.970000  14.970000
5451  2021-09-01  15.050000  15.050000  14.680000  14.850000  14.850000
5452  2021-09-02  14.890000  15.010000  14.790000  14.850000  14.850000
5453  2021-09-03  14.870000  14.870000  14.670000  14.870000  14.870000

        Volume
0        27300
1       176900
2       423100
3       168800
4       240500
...        ...
5449  25620000
5450  39850000
5451  29810000
5452  15540000
5453  25460000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price   minall maxall  \
0  BRKL_ended_2021-09-25  1999-12-31         14.87  3.94376  19.35

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     1.54062   5.48438   7.02501   8.56563   10.1063   11.6469   13.1875

  markup_70 markup_80 markup_90 markup_100
0   14.7281   16.2688   17.8094      19.35
                   stock  start_date current_price   minall maxall  \
0  BRKL_ended_2021-09-25  1999-12-31         14.87  3.94376  19.35

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     1.54062   5.48438   7.02501   8.56563   10.1063   11.6469   13.1875

  markup_70 markup_80 markup_90 markup_100
0   14.7281   16.2688   17.8094      19.35
./ticker_data/ticker_data_2021-09-25 - Copy/BRKR_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2000-08-04  20.468750  25.187500  19.187500  23.062500  22.468060
1     2000-08-07  23.125000  24.750000  22.500000  23.875000  23.259615
2     2000-08-08  23.625000  26.359375  23.625000  25.000000  24.355621
3     2000-08-09  25.125000  25.625000  25.000000  25.375000  24.720953
4     2000-08-10  24.937500  25.125000  24.500000  24.750000  24.112068
...          ...        ...        ...        ...        ...        ...
5314  2021-09-20  82.089996  83.510002  81.120003  82.699997  82.699997
5315  2021-09-21  83.360001  83.470001  81.919998  82.190002  82.190002
5316  2021-09-22  82.220001  83.860001  81.820000  83.430000  83.430000
5317  2021-09-23  84.019997  85.470001  83.900002  84.870003  84.870003
5318  2021-09-24  84.370003  84.680000  83.680000  84.680000  84.680000

       Volume
0     9184900
1     1006600
2      483700
3      487200
4      767000
...       ...
5314   623300
5315   404000
5316   577200
5317   470300
5318   102937

[5319 rows x 7 columns]
tolistdate: 0       2000-08-04
1       2000-08-07
2       2000-08-08
3       2000-08-09
4       2000-08-10
           ...
5314    2021-09-20
5315    2021-09-21
5316    2021-09-22
5317    2021-09-23
5318    2021-09-24
Name: Date, Length: 5319, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BRKR_ended_2021-09-25  2000-08-04         84.68   2.59  92.35       8.976

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.566    20.542    29.518    38.494     47.47    56.446    65.422

  markup_80 markup_90 markup_100
0    74.398    83.374      92.35
                   stock  start_date current_price minall maxall each_markup  \
0  BRKR_ended_2021-09-25  2000-08-04         84.68   2.59  92.35       8.976

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.566    20.542    29.518    38.494     47.47    56.446    65.422

  markup_80 markup_90 markup_100
0    74.398    83.374      92.35
./ticker_data/ticker_data_2021-09-25 - Copy/BRKS_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  32.625000  33.250000  32.562500  32.562500  25.641531
1     2000-01-03  32.500000  32.625000  30.375000  32.375000  25.493883
2     2000-01-04  31.250000  31.500000  30.125000  30.625000  24.115833
3     2000-01-05  30.125000  30.625000  29.750000  30.312500  23.869751
4     2000-01-06  30.250000  30.875000  29.750000  30.250000  23.820538
...          ...        ...        ...        ...        ...        ...
5449  2021-08-30  85.480003  86.059998  84.000000  85.150002  85.150002
5450  2021-08-31  85.309998  86.279999  84.360001  84.959999  84.959999
5451  2021-09-01  85.400002  86.129997  84.080002  85.339996  85.339996
5452  2021-09-02  85.449997  86.059998  84.790001  85.720001  85.720001
5453  2021-09-03  85.529999  86.879997  85.320000  85.650002  85.650002

        Volume
0        20400
1        58000
2        74000
3        86000
4       170200
...        ...
5449  37790000
5450  62700000
5451  37010000
5452  25300000
5453  24310000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BRKS_ended_2021-09-25  1999-12-31         85.65   2.52  108.72       10.62

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     13.14     23.76     34.38        45     55.62     66.24     76.86

  markup_80 markup_90 markup_100
0     87.48      98.1     108.72
                   stock  start_date current_price minall  maxall each_markup  \
0  BRKS_ended_2021-09-25  1999-12-31         85.65   2.52  108.72       10.62

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     13.14     23.76     34.38        45     55.62     66.24     76.86

  markup_80 markup_90 markup_100
0     87.48      98.1     108.72
./ticker_data/ticker_data_2021-09-25 - Copy/BRLIR_ended_2021-09-25.csv
         Date  Open  High   Low  Close  Adj Close  Volume
0  2021-09-24  0.35  0.35  0.34   0.34       0.34   12417
tolistdate: 0    2021-09-24
Name: Date, dtype: object
                    stock  start_date current_price minall maxall  \
0  BRLIR_ended_2021-09-25  2021-09-24          0.34   0.34   0.35

   each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0  0.000999999     0.341     0.342     0.343     0.344     0.345     0.346

  markup_70 markup_80 markup_90 markup_100

0     0.347     0.348     0.349       0.35
                    stock  start_date current_price minall maxall  \
0  BRLIR_ended_2021-09-25  2021-09-24          0.34   0.34   0.35

   each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0  0.000999999     0.341     0.342     0.343     0.344     0.345     0.346

  markup_70 markup_80 markup_90 markup_100
0     0.347     0.348     0.349       0.35
./ticker_data/ticker_data_2021-09-25 - Copy/BRLIW_ended_2021-09-25.csv
         Date  Open  High   Low  Close  Adj Close  Volume
0  2021-09-21  0.37   0.4  0.39   0.39       0.39    7905
tolistdate: 0    2021-09-21
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BRLIW_ended_2021-09-25  2021-09-21          0.39   0.39    0.4       0.001

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.391     0.392     0.393     0.394     0.395     0.396     0.397

  markup_80 markup_90 markup_100
0     0.398     0.399        0.4
                    stock  start_date current_price minall maxall each_markup  \
0  BRLIW_ended_2021-09-25  2021-09-21          0.39   0.39    0.4       0.001

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.391     0.392     0.393     0.394     0.395     0.396     0.397

  markup_80 markup_90 markup_100
0     0.398     0.399        0.4
./ticker_data/ticker_data_2021-09-25 - Copy/BRLI_ended_2021-09-25.csv
           Date   Open    High    Low   Close  Adj Close  Volume
0    2020-07-22   9.81   9.810   9.74   9.750      9.750   13200
1    2020-07-23   9.80   9.800   9.75   9.760      9.760   59000
2    2020-07-24   9.75   9.880   9.75   9.810      9.810   23200
3    2020-07-27   9.80   9.811   9.80   9.811      9.811   25700
4    2020-07-28   9.81   9.810   9.80   9.800      9.800     600
..          ...    ...     ...    ...     ...        ...     ...
252  2021-08-25  10.07  10.070  10.07  10.070     10.070   40000
253  2021-08-26  10.07  10.070  10.07  10.070     10.070   20000
254  2021-08-27  10.07  10.070  10.07  10.070     10.070       0
255  2021-08-30  10.07  10.070  10.07  10.070     10.070  210000
256  2021-08-31  10.07  10.070  10.07  10.070     10.070   10000

[257 rows x 7 columns]
tolistdate: 0      2020-07-22
1      2020-07-23
2      2020-07-24
3      2020-07-27
4      2020-07-28
          ...
252    2021-08-25
253    2021-08-26
254    2021-08-27
255    2021-08-30
256    2021-08-31
Name: Date, Length: 257, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BRLI_ended_2021-09-25  2020-07-22         10.07   9.74  10.58       0.084

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.824     9.908     9.992    10.076     10.16    10.244    10.328

  markup_80 markup_90 markup_100
0    10.412    10.496      10.58
                   stock  start_date current_price minall maxall each_markup  \
0  BRLI_ended_2021-09-25  2020-07-22         10.07   9.74  10.58       0.084

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.824     9.908     9.992    10.076     10.16    10.244    10.328

  markup_80 markup_90 markup_100
0    10.412    10.496      10.58
./ticker_data/ticker_data_2021-09-25 - Copy/BROGW_ended_2021-09-25.csv
         Date    Open    High     Low  Close  Adj Close  Volume
0  2021-09-17  0.4101  0.4962  0.4612   0.49       0.49     500
tolistdate: 0    2021-09-17
Name: Date, dtype: object
                    stock  start_date current_price  minall  maxall  \
0  BROGW_ended_2021-09-25  2021-09-17          0.49  0.4612  0.4962

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      0.0035    0.4647    0.4682    0.4717    0.4752    0.4787    0.4822

  markup_70 markup_80 markup_90 markup_100
0    0.4857    0.4892    0.4927     0.4962
                    stock  start_date current_price  minall  maxall  \
0  BROGW_ended_2021-09-25  2021-09-17          0.49  0.4612  0.4962

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0      0.0035    0.4647    0.4682    0.4717    0.4752    0.4787    0.4822

  markup_70 markup_80 markup_90 markup_100
0    0.4857    0.4892    0.4927     0.4962
./ticker_data/ticker_data_2021-09-25 - Copy/BROG_ended_2021-09-25.csv
           Date   Open    High    Low   Close  Adj Close   Volume
0    2018-07-13  9.600  9.6000  9.520  9.5300     9.5300  1833600
1    2018-07-16  9.560  9.5600  9.530  9.5600     9.5600   677800
2    2018-07-17  9.560  9.5600  9.540  9.5400     9.5400   142400
3    2018-07-18  9.540  9.9400  9.520  9.5500     9.5500   605700
4    2018-07-19  9.540  9.5500  9.540  9.5400     9.5400   205200
..          ...    ...     ...    ...     ...        ...      ...
697  2021-09-20  9.400  9.4000  8.810  8.8100     8.8100      600
698  2021-09-21  9.400  9.4000  9.175  9.1750     9.1750     1200
699  2021-09-22  9.180  9.4000  9.180  9.2250     9.2250     2200
700  2021-09-23  9.404  9.5000  9.190  9.2500     9.2500     1500
701  2021-09-24  9.300  9.4999  9.300  9.4999     9.4999     1722

[702 rows x 7 columns]
tolistdate: 0      2018-07-13
1      2018-07-16
2      2018-07-17
3      2018-07-18
4      2018-07-19
          ...
697    2021-09-20
698    2021-09-21
699    2021-09-22
700    2021-09-23
701    2021-09-24
Name: Date, Length: 702, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BROG_ended_2021-09-25  2018-07-13        9.4999   7.36  13.98       0.662

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.022     8.684     9.346    10.008     10.67    11.332    11.994

  markup_80 markup_90 markup_100
0    12.656    13.318      13.98
                   stock  start_date current_price minall maxall each_markup  \
0  BROG_ended_2021-09-25  2018-07-13        9.4999   7.36  13.98       0.662

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     8.022     8.684     9.346    10.008     10.67    11.332    11.994

  markup_80 markup_90 markup_100
0    12.656    13.318      13.98
./ticker_data/ticker_data_2021-09-25 - Copy/BRPMU_ended_2021-09-25.csv
           Date   Open   High    Low   Close  Adj Close   Volume
0    2021-02-19  10.61  10.90  10.50  10.800     10.800  4691900
1    2021-02-22  10.80  10.98  10.71  10.775     10.775   500100
2    2021-02-23  10.53  10.70  10.50  10.560     10.560   385000
3    2021-02-24  10.60  10.89  10.53  10.600     10.600   520400
4    2021-02-25  10.59  10.73  10.40  10.410     10.410   631000
..          ...    ...    ...    ...     ...        ...      ...
128  2021-08-27   9.99   9.99   9.99   9.990      9.990   450000
129  2021-08-30   9.90   9.94   9.86   9.930      9.930  2010000
130  2021-08-31   9.93   9.93   9.93   9.930      9.930        0
131  2021-09-01   9.94   9.94   9.92   9.920      9.920   640000
132  2021-09-02   9.92   9.92   9.92   9.920      9.920        0

[133 rows x 7 columns]
tolistdate: 0      2021-02-19
1      2021-02-22
2      2021-02-23
3      2021-02-24
4      2021-02-25
          ...
128    2021-08-27
129    2021-08-30
130    2021-08-31
131    2021-09-01
132    2021-09-02
Name: Date, Length: 133, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BRPMU_ended_2021-09-25  2021-02-19          9.92    9.8  10.98       0.118

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.918    10.036    10.154    10.272     10.39    10.508    10.626

  markup_80 markup_90 markup_100
0    10.744    10.862      10.98
                    stock  start_date current_price minall maxall each_markup  \
0  BRPMU_ended_2021-09-25  2021-02-19          9.92    9.8  10.98       0.118

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.918    10.036    10.154    10.272     10.39    10.508    10.626

  markup_80 markup_90 markup_100
0    10.744    10.862      10.98
./ticker_data/ticker_data_2021-09-25 - Copy/BRPMW_ended_2021-09-25.csv
         Date  Open    High     Low   Close  Adj Close  Volume
0  2021-09-22  0.95  0.8299  0.7599  0.8299     0.8299   12183
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price  minall  maxall  \
0  BRPMW_ended_2021-09-25  2021-09-22        0.8299  0.7599  0.8299

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0  0.00700001    0.7669    0.7739    0.7809    0.7879    0.7949    0.8019

  markup_70 markup_80 markup_90 markup_100
0    0.8089    0.8159    0.8229     0.8299
                    stock  start_date current_price  minall  maxall  \
0  BRPMW_ended_2021-09-25  2021-09-22        0.8299  0.7599  0.8299

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0  0.00700001    0.7669    0.7739    0.7809    0.7879    0.7949    0.8019

  markup_70 markup_80 markup_90 markup_100
0    0.8089    0.8159    0.8229     0.8299
./ticker_data/ticker_data_2021-09-25 - Copy/BRPM_ended_2021-09-25.csv
          Date    Open   High    Low  Close  Adj Close    Volume
0   2021-04-13  11.000  11.00  9.700   9.70       9.70      5200
1   2021-04-14   9.741   9.88  9.741   9.80       9.80    129400
2   2021-04-15   9.800   9.86  9.800   9.82       9.82     34600
3   2021-04-16   9.820   9.83  9.775   9.83       9.83    104000
4   2021-04-19   9.800   9.85  9.750   9.81       9.81      5400
..         ...     ...    ...    ...    ...        ...       ...
91  2021-08-27   9.740   9.74  9.670   9.67       9.67    120000
92  2021-08-30   9.620   9.73  9.620   9.63       9.63  10890000
93  2021-08-31   9.630   9.63  9.630   9.63       9.63         0
94  2021-09-01   9.640   9.70  9.640   9.70       9.70    120000
95  2021-09-02   9.688   9.70  9.650   9.70       9.70    420000

[96 rows x 7 columns]
tolistdate: 0     2021-04-13
1     2021-04-14
2     2021-04-15
3     2021-04-16
4     2021-04-19
         ...
91    2021-08-27
92    2021-08-30
93    2021-08-31
94    2021-09-01
95    2021-09-02
Name: Date, Length: 96, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BRPM_ended_2021-09-25  2021-04-13           9.7   9.62     11       0.138

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.758     9.896    10.034    10.172     10.31    10.448    10.586

  markup_80 markup_90 markup_100
0    10.724    10.862         11
                   stock  start_date current_price minall maxall each_markup  \
0  BRPM_ended_2021-09-25  2021-04-13           9.7   9.62     11       0.138

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.758     9.896    10.034    10.172     10.31    10.448    10.586

  markup_80 markup_90 markup_100
0    10.724    10.862         11
./ticker_data/ticker_data_2021-09-25 - Copy/BRP_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-10-24  17.299999  17.799999  15.840000  16.370001  16.370001
1    2019-10-25  16.160000  16.650000  16.000000  16.150000  16.150000
2    2019-10-28  16.209999  16.350000  15.470000  15.700000  15.700000
3    2019-10-29  15.400000  15.980000  15.400000  15.410000  15.410000
4    2019-10-30  15.300000  15.800000  15.285000  15.750000  15.750000
..          ...        ...        ...        ...        ...        ...
464  2021-08-30  34.070000  35.040001  33.619999  34.860001  34.860001
465  2021-08-31  34.689999  38.040001  34.521999  37.650002  37.650002
466  2021-09-01  37.689999  38.360001  37.044998  38.119999  38.119999
467  2021-09-02  38.410000  39.520000  37.990002  39.400002  39.400002
468  2021-09-03  39.439999  40.320000  38.939999  40.250000  40.250000

       Volume
0     6707400
1      600700
2      577800
3      655100
4      133300
..        ...
464  35580000
465  61180000
466  34360000
467  19520000
468  31670000

[469 rows x 7 columns]
tolistdate: 0      2019-10-24
1      2019-10-25
2      2019-10-28
3      2019-10-29
4      2019-10-30
          ...
464    2021-08-30
465    2021-08-31
466    2021-09-01
467    2021-09-02
468    2021-09-03
Name: Date, Length: 469, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  BRP_ended_2021-09-25  2019-10-24         40.25   8.35  40.32       3.197

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.547    14.744    17.941    21.138    24.335    27.532    30.729

  markup_80 markup_90 markup_100
0    33.926    37.123      40.32
                  stock  start_date current_price minall maxall each_markup  \
0  BRP_ended_2021-09-25  2019-10-24         40.25   8.35  40.32       3.197

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.547    14.744    17.941    21.138    24.335    27.532    30.729

  markup_80 markup_90 markup_100
0    33.926    37.123      40.32
./ticker_data/ticker_data_2021-09-25 - Copy/BRQS_ended_2021-09-25.csv
            Date   Open   High    Low  Close  Adj Close     Volume
0     2015-11-05  9.920  9.920  9.920  9.920      9.920      18700
1     2015-11-06  9.910  9.910  9.910  9.910      9.910       3800
2     2015-11-13  9.870  9.870  9.870  9.870      9.870       1000
3     2015-11-16  9.860  9.860  9.860  9.860      9.860     100000
4     2015-11-17  9.900  9.900  9.850  9.850      9.850      11400
...          ...    ...    ...    ...    ...        ...        ...
1092  2021-08-30  0.791  0.817  0.752  0.772      0.772  213740000
1093  2021-08-31  0.755  0.787  0.755  0.773      0.773  164560000
1094  2021-09-01  0.786  0.827  0.770  0.807      0.807  414930000
1095  2021-09-02  0.800  0.826  0.790  0.802      0.802  201180000
1096  2021-09-03  0.812  0.845  0.803  0.837      0.837  359090000

[1097 rows x 7 columns]
tolistdate: 0       2015-11-05
1       2015-11-06
2       2015-11-13
3       2015-11-16
4       2015-11-17
           ...
1092    2021-08-30
1093    2021-08-31
1094    2021-09-01
1095    2021-09-02
1096    2021-09-03
Name: Date, Length: 1097, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BRQS_ended_2021-09-25  2015-11-05         0.837    0.7     13        1.23

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      1.93      3.16      4.39      5.62      6.85      8.08      9.31

  markup_80 markup_90 markup_100
0     10.54     11.77         13
                   stock  start_date current_price minall maxall each_markup  \
0  BRQS_ended_2021-09-25  2015-11-05         0.837    0.7     13        1.23

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      1.93      3.16      4.39      5.62      6.85      8.08      9.31

  markup_80 markup_90 markup_100
0     10.54     11.77         13
./ticker_data/ticker_data_2021-09-25 - Copy/BRY_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close    Volume
0    2018-07-18  13.50  13.75  13.50  13.75  12.266175      6900
1    2018-07-19  14.50  14.50  14.50  14.50  12.935239       400
2    2018-07-20  14.50  16.00  14.50  16.00  14.273367      2900
3    2018-07-23  16.00  16.00  16.00  16.00  14.273367       200
4    2018-07-25  17.00  17.00  14.50  14.50  12.935239      3400
..          ...    ...    ...    ...    ...        ...       ...
783  2021-08-30   5.89   5.89   5.65   5.84   5.840000  23340000
784  2021-08-31   5.80   6.02   5.76   6.00   6.000000  25880000
785  2021-09-01   6.00   6.12   5.87   6.01   6.010000  42480000
786  2021-09-02   6.08   6.23   6.04   6.11   6.110000  28450000
787  2021-09-03   6.17   6.18   5.98   6.13   6.130000  33760000

[788 rows x 7 columns]
tolistdate: 0      2018-07-18
1      2018-07-19
2      2018-07-20
3      2018-07-23
4      2018-07-25
          ...
783    2021-08-30
784    2021-08-31
785    2021-09-01
786    2021-09-02
787    2021-09-03

Name: Date, Length: 788, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  BRY_ended_2021-09-25  2018-07-18          6.13   1.82  18.55       1.673

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.493     5.166     6.839     8.512    10.185    11.858    13.531

  markup_80 markup_90 markup_100
0    15.204    16.877      18.55
                  stock  start_date current_price minall maxall each_markup  \
0  BRY_ended_2021-09-25  2018-07-18          6.13   1.82  18.55       1.673

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.493     5.166     6.839     8.512    10.185    11.858    13.531

  markup_80 markup_90 markup_100
0    15.204    16.877      18.55
./ticker_data/ticker_data_2021-09-25 - Copy/BSBK_ended_2021-09-25.csv
           Date    Open    High    Low   Close  Adj Close   Volume
0    2020-01-16  11.400  11.970  11.35  11.590     11.590  1142100
1    2020-01-17  11.590  11.700  11.50  11.630     11.630   215500
2    2020-01-21  11.650  11.900  11.55  11.890     11.890   166200
3    2020-01-22  11.890  11.890  11.60  11.790     11.790    95000
4    2020-01-23  11.600  11.790  11.50  11.680     11.680   124000
..          ...     ...     ...    ...     ...        ...      ...
407  2021-08-30  10.550  10.550  10.45  10.450     10.450    70000
408  2021-08-31  10.426  10.500  10.40  10.400     10.400   420000
409  2021-09-01  10.410  10.499  10.40  10.499     10.499   140000
410  2021-09-02  10.420  10.610  10.42  10.450     10.450    70000
411  2021-09-03  10.550  10.550  10.55  10.550     10.550    40000

[412 rows x 7 columns]
tolistdate: 0      2020-01-16
1      2020-01-17
2      2020-01-21
3      2020-01-22
4      2020-01-23
          ...
407    2021-08-30
408    2021-08-31
409    2021-09-01
410    2021-09-02
411    2021-09-03
Name: Date, Length: 412, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BSBK_ended_2021-09-25  2020-01-16         10.55   6.07  11.97        0.59

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      6.66      7.25      7.84      8.43      9.02      9.61      10.2

  markup_80 markup_90 markup_100
0     10.79     11.38      11.97
                   stock  start_date current_price minall maxall each_markup  \
0  BSBK_ended_2021-09-25  2020-01-16         10.55   6.07  11.97        0.59

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      6.66      7.25      7.84      8.43      9.02      9.61      10.2

  markup_80 markup_90 markup_100
0     10.79     11.38      11.97
./ticker_data/ticker_data_2021-09-25 - Copy/BSET_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  15.937500  16.000000  15.562500  16.000000   5.895109
1     2000-01-03  15.500000  15.812500  15.125000  15.562500   5.733915
2     2000-01-04  15.375000  16.000000  15.375000  15.375000   5.664831
3     2000-01-05  15.437500  15.437500  15.000000  15.000000   5.526667
4     2000-01-06  15.000000  16.000000  15.000000  15.125000   5.572719
...          ...        ...        ...        ...        ...        ...
5449  2021-08-30  22.340000  22.340000  21.450001  21.629999  21.629999
5450  2021-08-31  21.639999  21.910000  21.129999  21.490000  21.490000
5451  2021-09-01  21.450001  21.889999  21.080000  21.570000  21.570000
5452  2021-09-02  21.650000  21.900000  21.180000  21.180000  21.180000
5453  2021-09-03  21.190001  21.209999  20.430000  21.120001  21.120001

       Volume
0        9100
1       23700
2       41300
3       25600
4       35300
...       ...
5449  3790000
5450  5550000
5451  4390000
5452  4070000
5453  4010000

[5454 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5449    2021-08-30
5450    2021-08-31
5451    2021-09-01
5452    2021-09-02
5453    2021-09-03
Name: Date, Length: 5454, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BSET_ended_2021-09-25  1999-12-31         21.12   0.62   41.3       4.068

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.688     8.756    12.824    16.892     20.96    25.028    29.096

  markup_80 markup_90 markup_100
0    33.164    37.232       41.3
                   stock  start_date current_price minall maxall each_markup  \
0  BSET_ended_2021-09-25  1999-12-31         21.12   0.62   41.3       4.068

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.688     8.756    12.824    16.892     20.96    25.028    29.096

  markup_80 markup_90 markup_100
0    33.164    37.232       41.3
./ticker_data/ticker_data_2021-09-25 - Copy/BSGM_ended_2021-09-25.csv
            Date   Open    High    Low  Close  Adj Close  Volume
0     2014-10-31  8.750  8.7500  8.750  8.750      8.750      40
1     2014-11-03  8.750  8.7500  8.750  8.750      8.750     360
2     2014-11-04  8.250  8.2500  8.125  8.125      8.125     440
3     2014-11-05  7.875  7.8750  7.875  7.875      7.875     200
4     2014-11-06  7.875  8.1250  7.500  7.500      7.500     520
...          ...    ...     ...    ...    ...        ...     ...
1728  2021-09-20  2.740  2.8800  2.710  2.800      2.800  155100
1729  2021-09-21  2.810  2.8600  2.750  2.850      2.850   80500
1730  2021-09-22  2.890  3.0300  2.810  2.980      2.980  114300
1731  2021-09-23  3.000  3.0400  2.830  3.030      3.030  149400
1732  2021-09-24  3.000  3.0399  2.930  3.000      3.000   56963

[1733 rows x 7 columns]
tolistdate: 0       2014-10-31
1       2014-11-03
2       2014-11-04
3       2014-11-05
4       2014-11-06
           ...
1728    2021-09-20
1729    2021-09-21
1730    2021-09-22
1731    2021-09-23
1732    2021-09-24
Name: Date, Length: 1733, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BSGM_ended_2021-09-25  2014-10-31             3   2.25  12.43       1.018

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.268     4.286     5.304     6.322      7.34     8.358     9.376

  markup_80 markup_90 markup_100
0    10.394    11.412      12.43
                   stock  start_date current_price minall maxall each_markup  \
0  BSGM_ended_2021-09-25  2014-10-31             3   2.25  12.43       1.018

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.268     4.286     5.304     6.322      7.34     8.358     9.376

  markup_80 markup_90 markup_100
0    10.394    11.412      12.43
./ticker_data/ticker_data_2021-09-25 - Copy/BSKYU_ended_2021-09-25.csv
          Date   Open   High    Low  Close  Adj Close   Volume
0   2021-04-28  10.00  10.00  10.00  10.00      10.00      100
1   2021-04-29   9.92   9.99   9.92   9.96       9.96  3867600
2   2021-04-30   9.95  10.01   9.95  10.00      10.00   828400
3   2021-05-03   9.99  10.07   9.97  10.00      10.00   292400
4   2021-05-04  10.00  10.05  10.00  10.01      10.01   117700
..         ...    ...    ...    ...    ...        ...      ...
76  2021-08-30   9.90   9.95   9.90   9.95       9.95   200000
77  2021-08-31   9.89   9.89   9.89   9.89       9.89    60000
78  2021-09-01   9.89   9.89   9.89   9.89       9.89    20000
79  2021-09-02   9.97   9.97   9.96   9.96       9.96   130000
80  2021-09-03   9.96   9.96   9.96   9.96       9.96    50000

[81 rows x 7 columns]
tolistdate: 0     2021-04-28
1     2021-04-29
2     2021-04-30
3     2021-05-03
4     2021-05-04
         ...
76    2021-08-30
77    2021-08-31
78    2021-09-01
79    2021-09-02
80    2021-09-03
Name: Date, Length: 81, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BSKYU_ended_2021-09-25  2021-04-28          9.96   9.89  11.58       0.169

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.059    10.228    10.397    10.566    10.735    10.904    11.073

  markup_80 markup_90 markup_100
0    11.242    11.411      11.58
                    stock  start_date current_price minall maxall each_markup  \
0  BSKYU_ended_2021-09-25  2021-04-28          9.96   9.89  11.58       0.169

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.059    10.228    10.397    10.566    10.735    10.904    11.073

  markup_80 markup_90 markup_100
0    11.242    11.411      11.58
./ticker_data/ticker_data_2021-09-25 - Copy/BSQR_ended_2021-09-25.csv
            Date     Open    High     Low   Close  Adj Close     Volume
0     1999-12-31  149.500  169.00  147.00  167.75     167.75      51600
1     2000-01-03  169.000  176.25  150.00  168.00     168.00      73800
2     2000-01-04  162.750  181.50  162.50  165.00     165.00     195400
3     2000-01-05  163.000  174.00  152.00  169.00     169.00      30600
4     2000-01-06  169.125  175.00  158.00  164.75     164.75      27100
...          ...      ...     ...     ...     ...        ...        ...
5448  2021-08-30    2.850    2.89    2.66    2.77       2.77  163610000
5449  2021-08-31    2.750    2.75    2.58    2.67       2.67   90510000
5450  2021-09-01    2.720    2.72    2.59    2.60       2.60   69440000
5451  2021-09-02    2.610    2.69    2.57    2.62       2.62   63690000
5452  2021-09-03    2.600    2.65    2.52    2.56       2.56   42250000

[5453 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5448    2021-08-30
5449    2021-08-31
5450    2021-09-01
5451    2021-09-02
5452    2021-09-03
Name: Date, Length: 5453, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BSQR_ended_2021-09-25  1999-12-31          2.56   0.83    214      21.317

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    22.147    43.464    64.781    86.098   107.415   128.732   150.049

  markup_80 markup_90 markup_100
0   171.366   192.683        214
                   stock  start_date current_price minall maxall each_markup  \
0  BSQR_ended_2021-09-25  1999-12-31          2.56   0.83    214      21.317

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    22.147    43.464    64.781    86.098   107.415   128.732   150.049

  markup_80 markup_90 markup_100
0   171.366   192.683        214
./ticker_data/ticker_data_2021-09-25 - Copy/BSRR_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  10.000000  10.000000   9.250000   9.250000   5.338601
1     2000-01-03   9.125000   9.250000   9.000000   9.000000   5.194317
2     2000-01-04   9.500000   9.500000   9.125000   9.125000   5.266461
3     2000-01-05   9.375000   9.375000   9.375000   9.375000   5.410745
4     2000-01-10   9.375000   9.375000   9.375000   9.375000   5.410745
...          ...        ...        ...        ...        ...        ...
5374  2021-09-20  22.660000  22.850000  22.400000  22.740000  22.740000
5375  2021-09-21  22.690001  22.770000  22.490000  22.580000  22.580000
5376  2021-09-22  22.850000  23.139999  22.709999  22.850000  22.850000
5377  2021-09-23  23.000000  23.270000  22.950001  23.020000  23.020000
5378  2021-09-24  23.020000  23.430901  23.020000  23.219999  23.219999

      Volume
0      12100
1       1500
2       3400
3        100
4        400
...      ...
5374   22600
5375   14300
5376   14400
5377   68000
5378    9580

[5379 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-10
           ...
5374    2021-09-20
5375    2021-09-21
5376    2021-09-22
5377    2021-09-23
5378    2021-09-24
Name: Date, Length: 5379, dtype: object
                   stock  start_date current_price  minall maxall each_markup  \
0  BSRR_ended_2021-09-25  1999-12-31         23.22  5.6875  35.36     2.96725

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   8.65475    11.622   14.5893   17.5565   20.5238    23.491   26.4583

  markup_80 markup_90 markup_100
0   29.4255   32.3928      35.36
                   stock  start_date current_price  minall maxall each_markup  \
0  BSRR_ended_2021-09-25  1999-12-31         23.22  5.6875  35.36     2.96725

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   8.65475    11.622   14.5893   17.5565   20.5238    23.491   26.4583

  markup_80 markup_90 markup_100
0   29.4255   32.3928      35.36
./ticker_data/ticker_data_2021-09-25 - Copy/BSVN_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-09-20  20.000000  20.740000  19.040001  19.090000  17.532957
1    2018-09-21  19.150000  19.600000  18.900000  19.100000  17.542147
2    2018-09-24  19.049999  19.350000  19.049999  19.110001  17.551329
3    2018-09-25  19.090000  19.200001  19.000000  19.090000  17.532957
4    2018-09-26  19.090000  19.090000  19.000000  19.000000  17.450300
..          ...        ...        ...        ...        ...        ...
739  2021-08-30  20.969999  22.400000  20.900000  22.100000  22.100000
740  2021-08-31  21.910000  22.990000  21.910000  22.700001  22.700001
741  2021-09-01  21.280001  22.700001  21.190001  22.160000  22.160000
742  2021-09-02  21.680000  23.600000  21.520000  22.170000  22.170000
743  2021-09-03  22.010000  22.990000  21.650000  21.650000  21.650000

      Volume
0    1405000
1     214300
2      54500
3      29200
4      80900
..       ...
739   920000
740   800000
741  1480000
742  1010000
743  1040000

[744 rows x 7 columns]
tolistdate: 0      2018-09-20
1      2018-09-21
2      2018-09-24
3      2018-09-25
4      2018-09-26
          ...
739    2021-08-30
740    2021-08-31
741    2021-09-01
742    2021-09-02
743    2021-09-03
Name: Date, Length: 744, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BSVN_ended_2021-09-25  2018-09-20         21.65   5.58  24.23       1.865

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.445      9.31    11.175     13.04    14.905     16.77    18.635

  markup_80 markup_90 markup_100
0      20.5    22.365      24.23
                   stock  start_date current_price minall maxall each_markup  \
0  BSVN_ended_2021-09-25  2018-09-20         21.65   5.58  24.23       1.865

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     7.445      9.31    11.175     13.04    14.905     16.77    18.635

  markup_80 markup_90 markup_100
0      20.5    22.365      24.23
./ticker_data/ticker_data_2021-09-25 - Copy/BSY_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2020-09-23  28.000000  33.490002  27.000000  33.490002  33.420258
1    2020-09-24  30.190001  33.500000  30.160000  32.000000  31.933359
2    2020-09-25  31.309999  35.250000  31.000000  34.790001  34.717552
3    2020-09-28  35.139999  35.349998  30.299999  32.119999  32.053112
4    2020-09-29  30.809999  32.090000  28.639999  30.020000  29.957481
..          ...        ...        ...        ...        ...        ...
235  2021-08-30  66.050003  66.875000  64.320000  64.669998  64.669998
236  2021-08-31  64.570000  64.599998  63.430000  64.489998  64.489998
237  2021-09-01  64.769997  66.790001  64.580002  66.199997  66.199997
238  2021-09-02  66.690002  66.820000  65.809998  66.360001  66.360001
239  2021-09-03  66.099998  67.849998  66.099998  67.180000  67.180000

        Volume
0      7934400
1       701900
2       335900
3       795400
4       572800
..         ...
235   42680000
236  135960000
237  122610000
238   62800000
239   80740000

[240 rows x 7 columns]
tolistdate: 0      2020-09-23
1      2020-09-24
2      2020-09-25
3      2020-09-28
4      2020-09-29
          ...
235    2021-08-30
236    2021-08-31
237    2021-09-01
238    2021-09-02
239    2021-09-03
Name: Date, Length: 240, dtype: object
                  stock  start_date current_price minall  maxall each_markup  \
0  BSY_ended_2021-09-25  2020-09-23         67.18     27  68.447      4.1447

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   31.1447   35.2894   39.4341   43.5788   47.7235   51.8682   56.0129

  markup_80 markup_90 markup_100

0   60.1576   64.3023     68.447
                  stock  start_date current_price minall  maxall each_markup  \
0  BSY_ended_2021-09-25  2020-09-23         67.18     27  68.447      4.1447

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   31.1447   35.2894   39.4341   43.5788   47.7235   51.8682   56.0129

  markup_80 markup_90 markup_100
0   60.1576   64.3023     68.447
./ticker_data/ticker_data_2021-09-25 - Copy/BTAI_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2018-03-08  11.020000  11.940000  10.670000  11.030000  11.030000
1    2018-03-09  11.100000  11.430000  11.000000  11.000000  11.000000
2    2018-03-12  11.030000  11.030000  10.310000  10.430000  10.430000
3    2018-03-13  10.250000  10.600000  10.140000  10.310000  10.310000
4    2018-03-14  10.330000  10.470000  10.330000  10.470000  10.470000
..          ...        ...        ...        ...        ...        ...
875  2021-08-30  28.430000  28.990000  27.870001  28.180000  28.180000
876  2021-08-31  28.080000  29.660000  28.080000  29.450001  29.450001
877  2021-09-01  29.000000  30.549999  29.000000  30.139999  30.139999
878  2021-09-02  30.219999  31.000000  29.500000  30.750000  30.750000
879  2021-09-03  30.900000  31.780001  29.020000  29.180000  29.180000

       Volume
0     1909800
1      275800
2      259500
3      133700
4       44800
..        ...
875  25630000
876  20730000
877  25470000
878  21310000
879  38670000

[880 rows x 7 columns]
tolistdate: 0      2018-03-08
1      2018-03-09
2      2018-03-12
3      2018-03-13
4      2018-03-14
          ...
875    2021-08-30
876    2021-08-31
877    2021-09-01
878    2021-09-02
879    2021-09-03
Name: Date, Length: 880, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BTAI_ended_2021-09-25  2018-03-08         29.18   2.41   71.5       6.909

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.319    16.228    23.137    30.046    36.955    43.864    50.773

  markup_80 markup_90 markup_100
0    57.682    64.591       71.5
                   stock  start_date current_price minall maxall each_markup  \
0  BTAI_ended_2021-09-25  2018-03-08         29.18   2.41   71.5       6.909

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.319    16.228    23.137    30.046    36.955    43.864    50.773

  markup_80 markup_90 markup_100
0    57.682    64.591       71.5
./ticker_data/ticker_data_2021-09-25 - Copy/BTAQU_ended_2021-09-25.csv
           Date    Open    High     Low   Close  Adj Close   Volume
0    2020-08-27  10.000  10.020   9.920   9.980      9.980  8521100
1    2020-08-28  10.490  10.490   9.940   9.990      9.990   957000
2    2020-08-31   9.967   9.970   9.950   9.950      9.950    98400
3    2020-09-01   9.970   9.990   9.940   9.980      9.980   215900
4    2020-09-02   9.940   9.970   9.940   9.960      9.960   360500
..          ...     ...     ...     ...     ...        ...      ...
242  2021-08-30  10.180  10.180  10.159  10.159     10.159    40000
243  2021-08-31  10.170  10.170  10.170  10.170     10.170    10000
244  2021-09-01  10.191  10.211  10.170  10.170     10.170    90000
245  2021-09-02  10.190  10.270  10.190  10.270     10.270    30000
246  2021-09-03  10.190  10.270  10.190  10.270     10.270    40000

[247 rows x 7 columns]
tolistdate: 0      2020-08-27
1      2020-08-28
2      2020-08-31
3      2020-09-01
4      2020-09-02
          ...
242    2021-08-30
243    2021-08-31
244    2021-09-01
245    2021-09-02
246    2021-09-03
Name: Date, Length: 247, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BTAQU_ended_2021-09-25  2020-08-27         10.27    9.3  13.55       0.425

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.725     10.15    10.575        11    11.425     11.85    12.275

  markup_80 markup_90 markup_100
0      12.7    13.125      13.55
                    stock  start_date current_price minall maxall each_markup  \
0  BTAQU_ended_2021-09-25  2020-08-27         10.27    9.3  13.55       0.425

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.725     10.15    10.575        11    11.425     11.85    12.275

  markup_80 markup_90 markup_100
0      12.7    13.125      13.55
./ticker_data/ticker_data_2021-09-25 - Copy/BTAQW_ended_2021-09-25.csv
         Date  Open    High   Low   Close  Adj Close  Volume
0  2021-09-22  0.67  0.6701  0.62  0.6499     0.6499   74580
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall  maxall  \
0  BTAQW_ended_2021-09-25  2021-09-22        0.6499   0.62  0.6701

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00501   0.62501   0.63002   0.63503   0.64004   0.64505   0.65006

  markup_70 markup_80 markup_90 markup_100
0   0.65507   0.66008   0.66509     0.6701
                    stock  start_date current_price minall  maxall  \
0  BTAQW_ended_2021-09-25  2021-09-22        0.6499   0.62  0.6701

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00501   0.62501   0.63002   0.63503   0.64004   0.64505   0.65006

  markup_70 markup_80 markup_90 markup_100
0   0.65507   0.66008   0.66509     0.6701
./ticker_data/ticker_data_2021-09-25 - Copy/BTAQ_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close    Volume
0    2020-10-08  9.750  9.750  9.725  9.730      9.730   1165200
1    2020-10-09  9.735  9.740  9.730  9.740      9.740    311500
2    2020-10-12  9.730  9.740  9.730  9.730      9.730    130000
3    2020-10-13  9.730  9.730  9.730  9.730      9.730   1525800
4    2020-10-14  9.753  9.765  9.735  9.735      9.735   1007400
..          ...    ...    ...    ...    ...        ...       ...
221  2021-08-30  9.860  9.890  9.860  9.880      9.880   3380000
222  2021-08-31  9.870  9.900  9.870  9.890      9.890   7100000
223  2021-09-01  9.880  9.900  9.880  9.890      9.890   1990000
224  2021-09-02  9.880  9.910  9.870  9.910      9.910  11220000
225  2021-09-03  9.890  9.900  9.873  9.900      9.900   7000000

[226 rows x 7 columns]
tolistdate: 0      2020-10-08
1      2020-10-09
2      2020-10-12
3      2020-10-13
4      2020-10-14
          ...
221    2021-08-30
222    2021-08-31
223    2021-09-01
224    2021-09-02
225    2021-09-03
Name: Date, Length: 226, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BTAQ_ended_2021-09-25  2020-10-08           9.9   9.64   11.9       0.226

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.866    10.092    10.318    10.544     10.77    10.996    11.222

  markup_80 markup_90 markup_100
0    11.448    11.674       11.9
                   stock  start_date current_price minall maxall each_markup  \
0  BTAQ_ended_2021-09-25  2020-10-08           9.9   9.64   11.9       0.226

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.866    10.092    10.318    10.544     10.77    10.996    11.222

  markup_80 markup_90 markup_100
0    11.448    11.674       11.9
./ticker_data/ticker_data_2021-09-25 - Copy/BTBT_ended_2021-09-25.csv
           Date    Open    High     Low  Close  Adj Close      Volume
0    2020-02-07   0.400   0.400   0.400   0.40       0.40           0
1    2020-03-25   0.380   0.380   0.280   0.33       0.33      389900
2    2020-03-26   0.340   0.560   0.340   0.44       0.44      251900
3    2020-03-27   0.360   0.478   0.360   0.46       0.46      186900
4    2020-03-30   0.580   0.580   0.405   0.42       0.42       53000
..          ...     ...     ...     ...    ...        ...         ...
362  2021-08-30  12.020  13.500  11.532  12.81      12.81  1428920000
363  2021-08-31  12.642  12.950  12.000  12.82      12.82   947840000
364  2021-09-01  12.750  13.350  12.430  12.63      12.63   946880000
365  2021-09-02  13.397  13.980  12.630  12.72      12.72  1166430000
366  2021-09-03  13.000  14.550  12.320  12.97      12.97  2932840000

[367 rows x 7 columns]
tolistdate: 0      2020-02-07
1      2020-03-25
2      2020-03-26
3      2020-03-27
4      2020-03-30
          ...
362    2021-08-30
363    2021-08-31
364    2021-09-01
365    2021-09-02
366    2021-09-03
Name: Date, Length: 367, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BTBT_ended_2021-09-25  2020-02-07         12.97   0.28     33       3.272

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.552     6.824    10.096    13.368     16.64    19.912    23.184

  markup_80 markup_90 markup_100
0    26.456    29.728         33
                   stock  start_date current_price minall maxall each_markup  \
0  BTBT_ended_2021-09-25  2020-02-07         12.97   0.28     33       3.272

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.552     6.824    10.096    13.368     16.64    19.912    23.184

  markup_80 markup_90 markup_100
0    26.456    29.728         33
./ticker_data/ticker_data_2021-09-25 - Copy/BTNB_ended_2021-09-25.csv
           Date    Open   High     Low  Close  Adj Close   Volume
0    2021-01-26  12.000  13.19  11.990  13.00      13.00  7241600
1    2021-01-27  12.800  12.97  11.990  12.05      12.05  1797000
2    2021-01-28  12.200  12.49  12.050  12.16      12.16  1037400
3    2021-01-29  12.200  12.54  12.120  12.20      12.20   544400
4    2021-02-01  12.500  12.55  12.140  12.24      12.24   620000
..          ...     ...    ...     ...    ...        ...      ...
149  2021-08-30   9.850   9.88   9.840   9.86       9.86  3580000
150  2021-08-31   9.870   9.89   9.850   9.88       9.88  5710000
151  2021-09-01   9.880   9.88   9.830   9.85       9.85  2630000
152  2021-09-02   9.850   9.92   9.840   9.91       9.91  5170000
153  2021-09-03   9.875   9.91   9.871   9.90       9.90  1310000

[154 rows x 7 columns]
tolistdate: 0      2021-01-26
1      2021-01-27
2      2021-01-28
3      2021-01-29
4      2021-02-01
          ...
149    2021-08-30
150    2021-08-31
151    2021-09-01
152    2021-09-02
153    2021-09-03
Name: Date, Length: 154, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BTNB_ended_2021-09-25  2021-01-26           9.9   9.79     14       0.421

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.211    10.632    11.053    11.474    11.895    12.316    12.737

  markup_80 markup_90 markup_100
0    13.158    13.579         14
                   stock  start_date current_price minall maxall each_markup  \
0  BTNB_ended_2021-09-25  2021-01-26           9.9   9.79     14       0.421

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.211    10.632    11.053    11.474    11.895    12.316    12.737

  markup_80 markup_90 markup_100
0    13.158    13.579         14
./ticker_data/ticker_data_2021-09-25 - Copy/BTRSW_ended_2021-09-25.csv
         Date  Open  High   Low  Close  Adj Close  Volume
0  2021-09-22  2.74  2.78  2.68   2.68       2.68    4410
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BTRSW_ended_2021-09-25  2021-09-22          2.68   2.68   2.78  0.00999999

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      2.69       2.7      2.71      2.72      2.73      2.74      2.75

  markup_80 markup_90 markup_100
0      2.76      2.77       2.78
                    stock  start_date current_price minall maxall each_markup  \
0  BTRSW_ended_2021-09-25  2021-09-22          2.68   2.68   2.78  0.00999999

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      2.69       2.7      2.71      2.72      2.73      2.74      2.75

  markup_80 markup_90 markup_100
0      2.76      2.77       2.78
./ticker_data/ticker_data_2021-09-25 - Copy/BTRS_ended_2021-09-25.csv
           Date    Open    High     Low   Close  Adj Close    Volume
0    2020-07-15  10.200  10.270  10.200  10.270     10.270    257000
1    2020-07-16  10.220  10.260  10.220  10.250     10.250      5700
2    2020-07-17  10.250  10.350  10.250  10.310     10.310    114600
3    2020-07-20  10.340  10.400  10.340  10.355     10.355     29700
4    2020-07-21  10.313  10.450  10.313  10.400     10.400    115200
..          ...     ...     ...     ...     ...        ...       ...
283  2021-08-30  11.300  11.320  10.960  11.020     11.020  58440000
284  2021-08-31  10.980  11.140  10.850  10.910     10.910  58900000
285  2021-09-01  10.910  11.320  10.710  11.250     11.250  57650000
286  2021-09-02  11.300  11.955  11.190  11.480     11.480  81250000
287  2021-09-03  11.390  11.485  11.130  11.280     11.280  48880000

[288 rows x 7 columns]
tolistdate: 0      2020-07-15
1      2020-07-16
2      2020-07-17
3      2020-07-20
4      2020-07-21
          ...
283    2021-08-30
284    2021-08-31
285    2021-09-01
286    2021-09-02
287    2021-09-03
Name: Date, Length: 288, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BTRS_ended_2021-09-25  2020-07-15         11.28  10.02  19.76       0.974

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.994    11.968    12.942    13.916     14.89    15.864    16.838

  markup_80 markup_90 markup_100
0    17.812    18.786      19.76
                   stock  start_date current_price minall maxall each_markup  \
0  BTRS_ended_2021-09-25  2020-07-15         11.28  10.02  19.76       0.974

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.994    11.968    12.942    13.916     14.89    15.864    16.838

  markup_80 markup_90 markup_100
0    17.812    18.786      19.76
./ticker_data/ticker_data_2021-09-25 - Copy/BTWNU_ended_2021-09-25.csv
           Date   Open    High    Low   Close  Adj Close    Volume
0    2020-10-16  10.00  10.050   9.96  10.040     10.040  20067700
1    2020-10-19  10.05  10.250  10.05  10.160     10.160   1096900
2    2020-10-20  10.25  10.250  10.18  10.200     10.200    576300
3    2020-10-21  10.23  10.250  10.15  10.200     10.200    827700
4    2020-10-22  10.30  10.300  10.20  10.220     10.220     75100
..          ...    ...     ...    ...     ...        ...       ...
217  2021-08-30  10.14  10.160  10.12  10.120     10.120   1020000
218  2021-08-31  10.11  10.250  10.11  10.250     10.250   1020000
219  2021-09-01  10.25  10.250  10.19  10.225     10.225    810000
220  2021-09-02  10.16  10.246  10.16  10.210     10.210   1070000
221  2021-09-03  10.27  10.340  10.16  10.340     10.340    360000

[222 rows x 7 columns]
tolistdate: 0      2020-10-16
1      2020-10-19
2      2020-10-20
3      2020-10-21
4      2020-10-22
          ...
217    2021-08-30
218    2021-08-31
219    2021-09-01
220    2021-09-02
221    2021-09-03
Name: Date, Length: 222, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BTWNU_ended_2021-09-25  2020-10-16         10.34   9.96   20.5       1.054

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.014    12.068    13.122    14.176     15.23    16.284    17.338

  markup_80 markup_90 markup_100
0    18.392    19.446       20.5
                    stock  start_date current_price minall maxall each_markup  \
0  BTWNU_ended_2021-09-25  2020-10-16         10.34   9.96   20.5       1.054

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.014    12.068    13.122    14.176     15.23    16.284    17.338

  markup_80 markup_90 markup_100
0    18.392    19.446       20.5
./ticker_data/ticker_data_2021-09-25 - Copy/BTWNW_ended_2021-09-25.csv
           Date  Open   High   Low  Close  Adj Close   Volume
0    2020-12-07  2.35  3.500  2.31  2.480      2.480   232400
1    2020-12-08  2.75  3.250  2.42  2.610      2.610   443900
2    2020-12-09  2.90  3.250  2.59  2.600      2.600   285400
3    2020-12-10  3.50  3.538  2.45  2.610      2.610   422200
4    2020-12-11  3.00  3.200  2.61  2.840      2.840   238500
..          ...   ...    ...   ...    ...        ...      ...
182  2021-08-30  1.12  1.190  1.11  1.160      1.160  9710000
183  2021-08-31  1.17  1.300  1.12  1.280      1.280  5090000
184  2021-09-01  1.25  1.350  1.25  1.330      1.330  2910000
185  2021-09-02  1.28  1.350  1.28  1.315      1.315  2420000
186  2021-09-03  1.26  1.380  1.26  1.375      1.375  4200000

[187 rows x 7 columns]
tolistdate: 0      2020-12-07
1      2020-12-08
2      2020-12-09
3      2020-12-10
4      2020-12-11
          ...
182    2021-08-30
183    2021-08-31
184    2021-09-01
185    2021-09-02
186    2021-09-03

Name: Date, Length: 187, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BTWNW_ended_2021-09-25  2020-12-07         1.375    1.1   5.99       0.489

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.589     2.078     2.567     3.056     3.545     4.034     4.523

  markup_80 markup_90 markup_100
0     5.012     5.501       5.99
                    stock  start_date current_price minall maxall each_markup  \
0  BTWNW_ended_2021-09-25  2020-12-07         1.375    1.1   5.99       0.489

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.589     2.078     2.567     3.056     3.545     4.034     4.523

  markup_80 markup_90 markup_100
0     5.012     5.501       5.99
./ticker_data/ticker_data_2021-09-25 - Copy/BTWN_ended_2021-09-25.csv
           Date       Open   High    Low  Close  Adj Close    Volume
0    2020-12-07  23.799999  25.84  10.50  10.70      10.70    601000
1    2020-12-08  11.250000  13.00  10.85  11.15      11.15   2191700
2    2020-12-09  11.200000  11.60  10.92  11.21      11.21   1698200
3    2020-12-10  11.200000  11.55  11.00  11.04      11.04    961100
4    2020-12-11  11.440000  11.47  10.90  11.15      11.15    885900
..          ...        ...    ...    ...    ...        ...       ...
182  2021-08-30   9.730000   9.77   9.73   9.77       9.77  24690000
183  2021-08-31   9.750000   9.85   9.74   9.81       9.81  46690000
184  2021-09-01   9.760000   9.82   9.76   9.81       9.81  30050000
185  2021-09-02   9.810000   9.81   9.78   9.79       9.79  16920000
186  2021-09-03   9.780000  10.00   9.78   9.97       9.97  74200000

[187 rows x 7 columns]
tolistdate: 0      2020-12-07
1      2020-12-08
2      2020-12-09
3      2020-12-10
4      2020-12-11
          ...
182    2021-08-30
183    2021-08-31
184    2021-09-01
185    2021-09-02
186    2021-09-03
Name: Date, Length: 187, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BTWN_ended_2021-09-25  2020-12-07          9.97   9.71  25.84       1.613

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.323    12.936    14.549    16.162    17.775    19.388    21.001

  markup_80 markup_90 markup_100
0    22.614    24.227      25.84
                   stock  start_date current_price minall maxall each_markup  \
0  BTWN_ended_2021-09-25  2020-12-07          9.97   9.71  25.84       1.613

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.323    12.936    14.549    16.162    17.775    19.388    21.001

  markup_80 markup_90 markup_100
0    22.614    24.227      25.84
./ticker_data/ticker_data_2021-09-25 - Copy/BUSE_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  43.500000  48.750000  43.000000  45.250000  21.923233
1     2000-01-03  44.750000  45.500000  44.500000  45.250000  21.923233
2     2000-01-04  46.000000  46.000000  44.500000  44.500000  21.559855
3     2000-01-05  44.125000  45.250000  43.125000  44.000000  21.317610
4     2000-01-06  44.000000  44.125000  44.000000  44.125000  21.378174
...          ...        ...        ...        ...        ...        ...
5444  2021-08-30  24.520000  24.520000  23.570000  23.620001  23.620001
5445  2021-08-31  23.540001  23.950001  23.540001  23.700001  23.700001
5446  2021-09-01  23.820000  23.910000  23.440001  23.860001  23.860001
5447  2021-09-02  23.820000  24.200001  23.730000  24.120001  24.120001
5448  2021-09-03  24.150000  24.309999  24.000000  24.020000  24.020000

        Volume
0        18600
1        24700
2          600
3         2500
4         1300
...        ...
5444  11910000
5445  15640000
5446  14370000
5447  16180000
5448  13770000

[5449 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5444    2021-08-30
5445    2021-08-31
5446    2021-09-01
5447    2021-09-02
5448    2021-09-03
Name: Date, Length: 5449, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BUSE_ended_2021-09-25  1999-12-31         24.02      9  72.21       6.321

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.321    21.642    27.963    34.284    40.605    46.926    53.247

  markup_80 markup_90 markup_100
0    59.568    65.889      72.21
                   stock  start_date current_price minall maxall each_markup  \
0  BUSE_ended_2021-09-25  1999-12-31         24.02      9  72.21       6.321

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    15.321    21.642    27.963    34.284    40.605    46.926    53.247

  markup_80 markup_90 markup_100
0    59.568    65.889      72.21
./ticker_data/ticker_data_2021-09-25 - Copy/BVS_ended_2021-09-25.csv
           Date   Open       High        Low      Close  Adj Close    Volume
0    2021-02-11  15.10  19.510000  15.040000  19.209999  19.209999   3484400
1    2021-02-12  18.76  18.969999  16.799999  17.219999  17.219999    809600
2    2021-02-16  17.50  17.500000  14.360000  16.280001  16.280001    594500
3    2021-02-17  16.02  16.040001  14.740000  14.750000  14.750000    331100
4    2021-02-18  14.80  15.410000  13.600000  13.600000  13.600000    394500
..          ...    ...        ...        ...        ...        ...       ...
137  2021-08-30  15.04  15.200000  14.630000  14.700000  14.700000  16380000
138  2021-08-31  14.78  15.130000  14.440000  14.510000  14.510000  23470000
139  2021-09-01  14.59  15.070000  14.530000  14.980000  14.980000  19040000
140  2021-09-02  15.04  15.210000  14.855000  15.160000  15.160000  14080000
141  2021-09-03  15.15  15.370000  14.810000  15.010000  15.010000  17750000

[142 rows x 7 columns]
tolistdate: 0      2021-02-11
1      2021-02-12
2      2021-02-16
3      2021-02-17
4      2021-02-18
          ...
137    2021-08-30
138    2021-08-31
139    2021-09-01
140    2021-09-02
141    2021-09-03
Name: Date, Length: 142, dtype: object
                  stock  start_date current_price minall  maxall each_markup  \
0  BVS_ended_2021-09-25  2021-02-11         15.01  10.74  19.941      0.9201

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   11.6601   12.5802   13.5003   14.4204   15.3405   16.2606   17.1807

  markup_80 markup_90 markup_100
0   18.1008   19.0209     19.941
                  stock  start_date current_price minall  maxall each_markup  \
0  BVS_ended_2021-09-25  2021-02-11         15.01  10.74  19.941      0.9201

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   11.6601   12.5802   13.5003   14.4204   15.3405   16.2606   17.1807

  markup_80 markup_90 markup_100
0   18.1008   19.0209     19.941
./ticker_data/ticker_data_2021-09-25 - Copy/BVXV_ended_2021-09-25.csv
            Date  Open  High    Low  Close  Adj Close    Volume
0     2015-05-11  5.00  5.00  5.000   5.00       5.00         0
1     2015-05-12  4.89  4.89  3.810   3.99       3.99    496900
2     2015-05-13  4.34  4.69  4.120   4.69       4.69    287100
3     2015-05-14  4.59  4.59  4.090   4.24       4.24    152400
4     2015-05-15  4.20  4.98  4.155   4.48       4.48    525100
...          ...   ...   ...    ...    ...        ...       ...
1552  2021-08-30  2.42  2.52  2.400   2.48       2.48   5100000
1553  2021-08-31  2.48  2.80  2.460   2.69       2.69  33100000
1554  2021-09-01  2.65  2.71  2.540   2.59       2.59  16210000
1555  2021-09-02  2.57  2.64  2.450   2.50       2.50  12160000
1556  2021-09-03  2.48  2.55  2.430   2.46       2.46   9300000

[1557 rows x 7 columns]
tolistdate: 0       2015-05-11
1       2015-05-12
2       2015-05-13
3       2015-05-14
4       2015-05-15
           ...
1552    2021-08-30
1553    2021-08-31
1554    2021-09-01
1555    2021-09-02
1556    2021-09-03
Name: Date, Length: 1557, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BVXV_ended_2021-09-25  2015-05-11          2.46    2.1     62        5.99

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      8.09     14.08     20.07     26.06     32.05     38.04     44.03

  markup_80 markup_90 markup_100
0     50.02     56.01         62
                   stock  start_date current_price minall maxall each_markup  \
0  BVXV_ended_2021-09-25  2015-05-11          2.46    2.1     62        5.99

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0      8.09     14.08     20.07     26.06     32.05     38.04     44.03

  markup_80 markup_90 markup_100
0     50.02     56.01         62
./ticker_data/ticker_data_2021-09-25 - Copy/BWACU_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close   Volume
0    2020-11-13  10.00  10.02  10.00  10.00      10.00  1751600
1    2020-11-16  10.00  10.02  10.00  10.00      10.00    45800
2    2020-11-17  10.00  10.05  10.00  10.01      10.01    63300
3    2020-11-18  10.02  10.02  10.01  10.02      10.02    15800
4    2020-11-19  10.05  10.05  10.03  10.05      10.05    37200
..          ...    ...    ...    ...    ...        ...      ...
157  2021-08-19  10.71  10.71  10.71  10.71      10.71        0
158  2021-08-26  10.70  10.70  10.70  10.70      10.70   100000
159  2021-08-27  10.70  10.70  10.70  10.70      10.70        0
160  2021-08-30  10.62  10.62  10.62  10.62      10.62    20000
161  2021-08-31  10.62  10.62  10.62  10.62      10.62        0

[162 rows x 7 columns]
tolistdate: 0      2020-11-13
1      2020-11-16
2      2020-11-17
3      2020-11-18
4      2020-11-19
          ...
157    2021-08-19
158    2021-08-26
159    2021-08-27
160    2021-08-30
161    2021-08-31
Name: Date, Length: 162, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BWACU_ended_2021-09-25  2020-11-13         10.62   9.77  13.75       0.398

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.168    10.566    10.964    11.362     11.76    12.158    12.556

  markup_80 markup_90 markup_100
0    12.954    13.352      13.75
                    stock  start_date current_price minall maxall each_markup  \
0  BWACU_ended_2021-09-25  2020-11-13         10.62   9.77  13.75       0.398

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.168    10.566    10.964    11.362     11.76    12.158    12.556

  markup_80 markup_90 markup_100
0    12.954    13.352      13.75
./ticker_data/ticker_data_2021-09-25 - Copy/BWACW_ended_2021-09-25.csv
         Date    Open  High   Low  Close  Adj Close  Volume
0  2021-09-22  0.7201  0.61  0.58   0.61       0.61   18411
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BWACW_ended_2021-09-25  2021-09-22          0.61   0.58   0.61       0.003

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.583     0.586     0.589     0.592     0.595     0.598     0.601

  markup_80 markup_90 markup_100
0     0.604     0.607       0.61
                    stock  start_date current_price minall maxall each_markup  \
0  BWACW_ended_2021-09-25  2021-09-22          0.61   0.58   0.61       0.003

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     0.583     0.586     0.589     0.592     0.595     0.598     0.601

  markup_80 markup_90 markup_100
0     0.604     0.607       0.61
./ticker_data/ticker_data_2021-09-25 - Copy/BWAC_ended_2021-09-25.csv
           Date    Open    High    Low   Close  Adj Close  Volume
0    2020-12-28  10.660  10.660  10.10  10.150     10.150  288200
1    2020-12-29  10.200  10.250  10.10  10.120     10.120   94600
2    2020-12-30  10.200  10.390  10.15  10.200     10.200  158200
3    2020-12-31  10.180  10.230  10.14  10.150     10.150   87300
4    2021-01-04  10.250  10.250  10.13  10.175     10.175   14300
..          ...     ...     ...    ...     ...        ...     ...
183  2021-09-20  10.070  10.070  10.06  10.070     10.070    5000
184  2021-09-21  10.061  10.070  10.06  10.070     10.070    2300
185  2021-09-22  10.050  10.073  10.05  10.070     10.070    9700
186  2021-09-23  10.060  10.070  10.05  10.060     10.060   13100
187  2021-09-24  10.060  10.060  10.06  10.060     10.060    9005

[188 rows x 7 columns]
tolistdate: 0      2020-12-28
1      2020-12-29
2      2020-12-30
3      2020-12-31
4      2021-01-04
          ...
183    2021-09-20
184    2021-09-21
185    2021-09-22
186    2021-09-23
187    2021-09-24
Name: Date, Length: 188, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BWAC_ended_2021-09-25  2020-12-28         10.06   9.87   11.2       0.133

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.003    10.136    10.269    10.402    10.535    10.668    10.801

  markup_80 markup_90 markup_100
0    10.934    11.067       11.2
                   stock  start_date current_price minall maxall each_markup  \
0  BWAC_ended_2021-09-25  2020-12-28         10.06   9.87   11.2       0.133

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.003    10.136    10.269    10.402    10.535    10.668    10.801

  markup_80 markup_90 markup_100
0    10.934    11.067       11.2
./ticker_data/ticker_data_2021-09-25 - Copy/BWAY_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close    Volume
0    2019-04-17  11.13  12.39  10.74  11.09      11.09   1286600
1    2019-04-18  11.03  11.45  10.80  11.25      11.25    165800
2    2019-04-22  11.40  11.50  11.30  11.50      11.50     50200
3    2019-04-23  11.55  11.55  11.04  11.31      11.31     26300
4    2019-04-24  11.22  11.28  11.00  11.25      11.25     20900
..          ...    ...    ...    ...    ...        ...       ...
596  2021-08-30   7.53   8.05   7.22   7.95       7.95  10550000
597  2021-08-31   7.83   7.98   7.49   7.94       7.94   5550000
598  2021-09-01   8.00   8.00   7.90   7.97       7.97   5610000
599  2021-09-02   7.91   7.98   7.87   7.90       7.90   2340000
600  2021-09-03   7.96   8.04   7.95   8.00       8.00   2660000

[601 rows x 7 columns]
tolistdate: 0      2019-04-17
1      2019-04-18
2      2019-04-22
3      2019-04-23
4      2019-04-24
          ...
596    2021-08-30
597    2021-08-31
598    2021-09-01
599    2021-09-02
600    2021-09-03
Name: Date, Length: 601, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BWAY_ended_2021-09-25  2019-04-17             8    5.1  12.53       0.743

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.843     6.586     7.329     8.072     8.815     9.558    10.301

  markup_80 markup_90 markup_100
0    11.044    11.787      12.53
                   stock  start_date current_price minall maxall each_markup  \
0  BWAY_ended_2021-09-25  2019-04-17             8    5.1  12.53       0.743

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     5.843     6.586     7.329     8.072     8.815     9.558    10.301

  markup_80 markup_90 markup_100
0    11.044    11.787      12.53
./ticker_data/ticker_data_2021-09-25 - Copy/BWB_ended_2021-09-25.csv
           Date       Open       High        Low  Close  Adj Close   Volume
0    2018-03-14  12.660000  13.000000  12.600000  12.62      12.62  2694300
1    2018-03-15  12.620000  13.330000  12.620000  13.02      13.02   299300
2    2018-03-16  13.080000  13.080000  12.780000  12.86      12.86   177100
3    2018-03-19  12.900000  12.980000  12.750000  12.75      12.75    98100
4    2018-03-20  12.880000  13.000000  12.740000  12.79      12.79    96400
..          ...        ...        ...        ...    ...        ...      ...
871  2021-08-30  16.719999  16.719999  16.240000  16.27      16.27  1670000
872  2021-08-31  16.270000  16.580000  16.209999  16.35      16.35  3280000
873  2021-09-01  16.280001  16.555000  16.160000  16.16      16.16  2380000
874  2021-09-02  16.160000  16.209999  16.070000  16.07      16.07  2270000
875  2021-09-03  16.379999  16.379999  16.000000  16.00      16.00  2760000

[876 rows x 7 columns]
tolistdate: 0      2018-03-14
1      2018-03-15
2      2018-03-16
3      2018-03-19
4      2018-03-20
          ...
871    2021-08-30
872    2021-08-31
873    2021-09-01
874    2021-09-02
875    2021-09-03
Name: Date, Length: 876, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  BWB_ended_2021-09-25  2018-03-14            16   7.99  18.25       1.026

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.016    10.042    11.068    12.094     13.12    14.146    15.172

  markup_80 markup_90 markup_100

0    16.198    17.224      18.25
                  stock  start_date current_price minall maxall each_markup  \
0  BWB_ended_2021-09-25  2018-03-14            16   7.99  18.25       1.026

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.016    10.042    11.068    12.094     13.12    14.146    15.172

  markup_80 markup_90 markup_100
0    16.198    17.224      18.25
./ticker_data/ticker_data_2021-09-25 - Copy/BWEN_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2005-11-10  35.500000  35.500000  31.700001  33.000000  33.000000
1     2005-11-11  32.700001  32.700001  31.000000  31.000000  31.000000
2     2005-11-14  31.000000  34.400002  30.000000  34.299999  34.299999
3     2005-11-15  35.000000  36.799999  35.000000  35.000000  35.000000
4     2005-11-16  35.500000  38.000000  35.000000  35.000000  35.000000
...          ...        ...        ...        ...        ...        ...
3955  2021-08-30   3.350000   3.350000   3.100000   3.140000   3.140000
3956  2021-08-31   3.190000   3.260000   3.130000   3.200000   3.200000
3957  2021-09-01   3.210000   3.240000   3.130000   3.170000   3.170000
3958  2021-09-02   3.190000   3.250000   3.170000   3.240000   3.240000
3959  2021-09-03   3.230000   3.260000   3.170000   3.230000   3.230000

        Volume
0          400
1         1000
2         1000
3          500
4         1200
...        ...
3955  15290000
3956  22910000
3957  11830000
3958  12030000
3959  12520000

[3960 rows x 7 columns]
tolistdate: 0       2005-11-10
1       2005-11-11
2       2005-11-14
3       2005-11-15
4       2005-11-16
           ...
3955    2021-08-30
3956    2021-08-31
3957    2021-09-01
3958    2021-09-02
3959    2021-09-03
Name: Date, Length: 3960, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BWEN_ended_2021-09-25  2005-11-10          3.23   1.12    290      28.888

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    30.008    58.896    87.784   116.672    145.56   174.448   203.336

  markup_80 markup_90 markup_100
0   232.224   261.112        290
                   stock  start_date current_price minall maxall each_markup  \
0  BWEN_ended_2021-09-25  2005-11-10          3.23   1.12    290      28.888

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    30.008    58.896    87.784   116.672    145.56   174.448   203.336

  markup_80 markup_90 markup_100
0   232.224   261.112        290
./ticker_data/ticker_data_2021-09-25 - Copy/BWFG_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2010-04-05  17.000000  17.000000  17.000000  17.000000  15.311962
1     2010-04-28  19.000000  19.000000  19.000000  19.000000  17.113371
2     2010-04-29  19.000000  19.000000  19.000000  19.000000  17.113371
3     2010-05-18  22.000000  22.000000  21.990000  21.990000  19.806479
4     2010-05-19  22.000000  22.000000  22.000000  22.000000  19.815481
...          ...        ...        ...        ...        ...        ...
1981  2021-08-30  30.510000  30.510000  29.969999  30.090000  30.090000
1982  2021-08-31  30.389999  30.389999  29.910000  30.090000  30.090000
1983  2021-09-01  29.969999  30.200001  29.760000  29.879999  29.879999
1984  2021-09-02  29.799999  30.120001  29.799999  29.940001  29.940001
1985  2021-09-03  29.850000  29.910000  29.400000  29.870001  29.870001

       Volume
0           0
1         200
2           0
3         400
4         200
...       ...
1981   760000
1982   990000
1983  1620000
1984  1430000
1985  2250000

[1986 rows x 7 columns]
tolistdate: 0       2010-04-05
1       2010-04-28
2       2010-04-29
3       2010-05-18
4       2010-05-19
           ...
1981    2021-08-30
1982    2021-08-31
1983    2021-09-01
1984    2021-09-02
1985    2021-09-03
Name: Date, Length: 1986, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BWFG_ended_2021-09-25  2010-04-05         29.87  12.07   38.5       2.643

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    14.713    17.356    19.999    22.642    25.285    27.928    30.571

  markup_80 markup_90 markup_100
0    33.214    35.857       38.5
                   stock  start_date current_price minall maxall each_markup  \
0  BWFG_ended_2021-09-25  2010-04-05         29.87  12.07   38.5       2.643

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    14.713    17.356    19.999    22.642    25.285    27.928    30.571

  markup_80 markup_90 markup_100
0    33.214    35.857       38.5
./ticker_data/ticker_data_2021-09-25 - Copy/BWMN_ended_2021-09-25.csv
          Date    Open    High    Low  Close  Adj Close   Volume
0   2021-05-07  14.000  14.900  12.60  14.00      14.00  2471400
1   2021-05-10  14.150  14.300  14.00  14.00      14.00   324800
2   2021-05-11  14.000  14.080  13.75  13.95      13.95   177400
3   2021-05-12  13.910  14.073  13.75  13.75      13.75    29200
4   2021-05-13  13.850  13.940  13.80  13.90      13.90     4600
..         ...     ...     ...    ...    ...        ...      ...
78  2021-08-30  13.600  13.700  13.26  13.28      13.28  1180000
79  2021-08-31  13.555  13.910  13.33  13.33      13.33   440000
80  2021-09-01  13.330  13.330  13.33  13.33      13.33        0
81  2021-09-02  13.620  13.620  13.62  13.62      13.62    50000
82  2021-09-03  13.550  13.670  13.48  13.48      13.48   170000

[83 rows x 7 columns]
tolistdate: 0     2021-05-07
1     2021-05-10
2     2021-05-11
3     2021-05-12
4     2021-05-13
         ...
78    2021-08-30
79    2021-08-31
80    2021-09-01
81    2021-09-02
82    2021-09-03
Name: Date, Length: 83, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BWMN_ended_2021-09-25  2021-05-07         13.48   12.6   14.9        0.23

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     12.83     13.06     13.29     13.52     13.75     13.98     14.21

  markup_80 markup_90 markup_100
0     14.44     14.67       14.9
                   stock  start_date current_price minall maxall each_markup  \
0  BWMN_ended_2021-09-25  2021-05-07         13.48   12.6   14.9        0.23

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     12.83     13.06     13.29     13.52     13.75     13.98     14.21

  markup_80 markup_90 markup_100
0     14.44     14.67       14.9
./ticker_data/ticker_data_2021-09-25 - Copy/BWMX_ended_2021-09-25.csv
           Date       Open       High        Low      Close  Adj Close  \
0    2019-01-03   9.800000   9.800000   9.800000   9.800000   9.049182
1    2019-01-29   9.700000   9.750000   9.700000   9.708000   8.964231
2    2019-01-30   9.708000   9.708000   9.708000   9.708000   8.964231
3    2019-01-31   9.820000   9.820000   9.820000   9.820000   9.067650
4    2019-02-01   9.820000   9.820000   9.820000   9.820000   9.067650
..          ...        ...        ...        ...        ...        ...
534  2021-08-30  39.610001  41.740002  39.220001  40.930000  40.930000
535  2021-08-31  41.000000  42.490002  40.450001  42.290001  42.290001
536  2021-09-01  42.500000  42.500000  39.680000  40.150002  40.150002
537  2021-09-02  40.549999  40.549999  39.009998  39.240002  39.240002
538  2021-09-03  39.450001  40.029999  39.450001  39.915001  39.915001

      Volume
0          0
1       3500
2          0
3        200
4          0
..       ...
534  4640000
535  9950000
536  4240000
537  2640000
538  1430000

[539 rows x 7 columns]
tolistdate: 0      2019-01-03
1      2019-01-29
2      2019-01-30
3      2019-01-31
4      2019-02-01
          ...
534    2021-08-30
535    2021-08-31
536    2021-09-01
537    2021-09-02
538    2021-09-03
Name: Date, Length: 539, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BWMX_ended_2021-09-25  2019-01-03        39.915   5.67  50.105      4.4435

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   10.1135    14.557   19.0005    23.444   27.8875    32.331   36.7745

  markup_80 markup_90 markup_100
0    41.218   45.6615     50.105
                   stock  start_date current_price minall  maxall each_markup  \
0  BWMX_ended_2021-09-25  2019-01-03        39.915   5.67  50.105      4.4435

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0   10.1135    14.557   19.0005    23.444   27.8875    32.331   36.7745

  markup_80 markup_90 markup_100
0    41.218   45.6615     50.105
./ticker_data/ticker_data_2021-09-25 - Copy/BXRX_ended_2021-09-25.csv
           Date   Open   High    Low  Close  Adj Close      Volume
0    2019-11-14  5.200  9.000  5.200  7.000      7.000        3800
1    2019-11-15  7.000  7.200  6.317  6.317      6.317       61700
2    2019-11-18  6.000  6.300  6.000  6.050      6.050       64400
3    2019-11-19  5.500  5.500  5.000  5.250      5.250        7000
4    2019-11-20  5.830  5.830  5.250  5.510      5.510       14200
..          ...    ...    ...    ...    ...        ...         ...
450  2021-08-30  0.600  0.619  0.593  0.610      0.610   134870000
451  2021-08-31  0.606  0.639  0.601  0.630      0.630   297020000
452  2021-09-01  0.698  0.760  0.677  0.710      0.710  2193410000
453  2021-09-02  0.693  0.719  0.682  0.713      0.713   315300000
454  2021-09-03  0.710  0.723  0.691  0.701      0.701   184030000

[455 rows x 7 columns]
tolistdate: 0      2019-11-14
1      2019-11-15
2      2019-11-18
3      2019-11-19
4      2019-11-20
          ...
450    2021-08-30
451    2021-08-31
452    2021-09-01
453    2021-09-02
454    2021-09-03
Name: Date, Length: 455, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BXRX_ended_2021-09-25  2019-11-14         0.701  0.502  10.14      0.9638

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    1.4658    2.4296    3.3934    4.3572     5.321    6.2848    7.2486

  markup_80 markup_90 markup_100
0    8.2124    9.1762      10.14
                   stock  start_date current_price minall maxall each_markup  \
0  BXRX_ended_2021-09-25  2019-11-14         0.701  0.502  10.14      0.9638

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    1.4658    2.4296    3.3934    4.3572     5.321    6.2848    7.2486

  markup_80 markup_90 markup_100
0    8.2124    9.1762      10.14
./ticker_data/ticker_data_2021-09-25 - Copy/BYFC_ended_2021-09-25.csv
            Date    Open    High      Low    Close  Adj Close    Volume
0     1999-12-31  2.4375  2.4375  2.40625  2.40625   1.931196      6400
1     2000-01-03  2.5000  3.1250  2.50000  3.00000   2.407726      3200
2     2000-01-04  3.0000  3.2500  3.00000  3.25000   2.608370     12600
3     2000-01-05  3.2500  3.2500  3.25000  3.25000   2.608370         0
4     2000-01-06  3.1250  3.1250  3.12500  3.12500   2.508047      1000
...          ...     ...     ...      ...      ...        ...       ...
4270  2021-08-30  3.5200  3.8900  3.41000  3.69000   3.690000  55420000
4271  2021-08-31  3.7100  3.7700  3.60000  3.67000   3.670000  33780000
4272  2021-09-01  3.6500  3.8400  3.60000  3.78000   3.780000  22480000
4273  2021-09-02  3.7900  3.8800  3.66000  3.83000   3.830000  14560000
4274  2021-09-03  3.7800  4.0000  3.55000  3.80000   3.800000  21630000

[4275 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
4270    2021-08-30
4271    2021-08-31
4272    2021-09-01
4273    2021-09-02
4274    2021-09-03
Name: Date, Length: 4275, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BYFC_ended_2021-09-25  1999-12-31           3.8   0.52     15       1.448

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.968     3.416     4.864     6.312      7.76     9.208    10.656

  markup_80 markup_90 markup_100
0    12.104    13.552         15
                   stock  start_date current_price minall maxall each_markup  \
0  BYFC_ended_2021-09-25  1999-12-31           3.8   0.52     15       1.448

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     1.968     3.416     4.864     6.312      7.76     9.208    10.656

  markup_80 markup_90 markup_100
0    12.104    13.552         15
./ticker_data/ticker_data_2021-09-25 - Copy/BYND_ended_2021-09-25.csv
           Date        Open        High         Low       Close   Adj Close  \
0    2019-05-02   46.000000   72.949997   45.000000   65.750000   65.750000
1    2019-05-03   72.000000   74.000000   65.660004   66.790001   66.790001
2    2019-05-06   62.730000   74.839996   62.500000   74.790001   74.790001
3    2019-05-07   77.139999   85.449997   75.000000   79.169998   79.169998
4    2019-05-08   83.610001   85.379997   70.785004   72.250000   72.250000
..          ...         ...         ...         ...         ...         ...
587  2021-08-30  121.459999  121.849998  119.099998  120.300003  120.300003
588  2021-08-31  121.309998  122.355003  118.910004  119.639999  119.639999
589  2021-09-01  119.080002  122.320000  119.000999  120.760002  120.760002
590  2021-09-02  120.529999  122.264999  119.349998  119.739998  119.739998
591  2021-09-03  118.000000  118.570000  113.629997  114.970001  114.970001

        Volume
0     23119000
1     13139400
2      8746200
3     16532100
4     14696300
..         ...
587  117070000
588  180660000
589  149900000
590  122580000
591  431090000

[592 rows x 7 columns]
tolistdate: 0      2019-05-02
1      2019-05-03
2      2019-05-06
3      2019-05-07
4      2019-05-08
          ...
587    2021-08-30
588    2021-08-31
589    2021-09-01
590    2021-09-02
591    2021-09-03
Name: Date, Length: 592, dtype: object
                   stock  start_date current_price minall  maxall each_markup  \
0  BYND_ended_2021-09-25  2019-05-02        114.97     45  239.71      19.471

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    64.471    83.942   103.413   122.884   142.355   161.826   181.297

  markup_80 markup_90 markup_100
0   200.768   220.239     239.71
                   stock  start_date current_price minall  maxall each_markup  \
0  BYND_ended_2021-09-25  2019-05-02        114.97     45  239.71      19.471

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    64.471    83.942   103.413   122.884   142.355   161.826   181.297

  markup_80 markup_90 markup_100
0   200.768   220.239     239.71
./ticker_data/ticker_data_2021-09-25 - Copy/BYRN_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2006-09-12   0.150000   0.450000   0.150000   0.300000   0.300000
1     2006-09-13   0.530000   0.750000   0.500000   0.580000   0.580000
2     2006-09-14   0.630000   0.630000   0.630000   0.630000   0.630000
3     2006-09-15   0.630000   0.630000   0.500000   0.530000   0.530000
4     2006-09-18   0.530000   0.530000   0.530000   0.530000   0.530000
...          ...        ...        ...        ...        ...        ...
2154  2021-08-30  29.590000  29.889999  28.730000  29.049999  29.049999
2155  2021-08-31  29.190001  29.459999  28.469999  29.280001  29.280001
2156  2021-09-01  29.400000  29.980000  28.870001  29.000000  29.000000
2157  2021-09-02  29.020000  29.360001  28.450001  29.020000  29.020000
2158  2021-09-03  28.959999  30.000000  28.629999  29.780001  29.780001

          Volume
0       215000.0
1       140500.0
2        46200.0
3        15000.0
4            0.0
...          ...
2154  43610000.0
2155  32430000.0
2156  29490000.0
2157  52480000.0
2158  45150000.0

[2159 rows x 7 columns]
tolistdate: 0       2006-09-12
1       2006-09-13
2       2006-09-14
3       2006-09-15
4       2006-09-18
           ...
2154    2021-08-30
2155    2021-08-31
2156    2021-09-01
2157    2021-09-02
2158    2021-09-03
Name: Date, Length: 2159, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BYRN_ended_2021-09-25  2006-09-12         29.78   0.04  30.55       3.051

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.091     6.142     9.193    12.244    15.295    18.346    21.397

  markup_80 markup_90 markup_100
0    24.448    27.499      30.55
                   stock  start_date current_price minall maxall each_markup  \
0  BYRN_ended_2021-09-25  2006-09-12         29.78   0.04  30.55       3.051

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     3.091     6.142     9.193    12.244    15.295    18.346    21.397

  markup_80 markup_90 markup_100
0    24.448    27.499      30.55
./ticker_data/ticker_data_2021-09-25 - Copy/BYSI_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2017-03-09  20.000000  21.908001  16.549999  16.799999  16.799999
1     2017-03-10  17.740000  19.750000  17.260000  19.250000  19.250000
2     2017-03-13  19.010000  19.860001  19.010000  19.700001  19.700001
3     2017-03-14  19.450001  19.500000  18.115999  18.337999  18.337999
4     2017-03-15  19.400000  19.400000  18.549999  18.780001  18.780001
...          ...        ...        ...        ...        ...        ...
1126  2021-08-30  28.400000  29.330000  26.830000  27.590000  27.590000
1127  2021-08-31  27.660000  33.000000  27.660000  31.309999  31.309999
1128  2021-09-01  31.680000  31.700001  28.030001  28.480000  28.480000
1129  2021-09-02  28.709999  28.870001  27.540001  28.049999  28.049999
1130  2021-09-03  27.620001  28.370001  26.549999  26.840000  26.840000

         Volume
0        160300
1         50900
2         17000
3          6000
4         11900
...         ...
1126  111740000
1127  279810000
1128  192550000
1129  104020000
1130  110990000

[1131 rows x 7 columns]
tolistdate: 0       2017-03-09
1       2017-03-10
2       2017-03-13
3       2017-03-14
4       2017-03-15
           ...
1126    2021-08-30
1127    2021-08-31
1128    2021-09-01
1129    2021-09-02
1130    2021-09-03
Name: Date, Length: 1131, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BYSI_ended_2021-09-25  2017-03-09         26.84    8.9  48.49       3.959

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.859    16.818    20.777    24.736    28.695    32.654    36.613

  markup_80 markup_90 markup_100
0    40.572    44.531      48.49
                   stock  start_date current_price minall maxall each_markup  \
0  BYSI_ended_2021-09-25  2017-03-09         26.84    8.9  48.49       3.959

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    12.859    16.818    20.777    24.736    28.695    32.654    36.613

  markup_80 markup_90 markup_100

0    40.572    44.531      48.49
./ticker_data/ticker_data_2021-09-25 - Copy/BYTSU_ended_2021-09-25.csv
          Date   Open    High    Low   Close  Adj Close   Volume
0   2021-03-19  9.930   9.950  9.920   9.950      9.950  4481400
1   2021-03-22  9.950   9.990  9.920   9.990      9.990  1467400
2   2021-03-23  9.980  10.000  9.960  10.000     10.000   409800
3   2021-03-24  9.990   9.990  9.920   9.990      9.990  1319800
4   2021-03-25  9.980   9.980  9.900   9.980      9.980   303300
..         ...    ...     ...    ...     ...        ...      ...
85  2021-08-24  9.910   9.910  9.910   9.910      9.910    30000
86  2021-08-25  9.910   9.910  9.910   9.910      9.910        0
87  2021-09-01  9.864   9.864  9.864   9.864      9.864   200000
88  2021-09-02  9.864   9.864  9.864   9.864      9.864        0
89  2021-09-03  9.810   9.890  9.810   9.890      9.890    30000

[90 rows x 7 columns]
tolistdate: 0     2021-03-19
1     2021-03-22
2     2021-03-23
3     2021-03-24
4     2021-03-25
         ...
85    2021-08-24
86    2021-08-25
87    2021-09-01
88    2021-09-02
89    2021-09-03
Name: Date, Length: 90, dtype: object
                    stock  start_date current_price minall maxall each_markup  \
0  BYTSU_ended_2021-09-25  2021-03-19          9.89   9.81   10.2   0.0389999

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.849     9.888     9.927     9.966    10.005    10.044    10.083

  markup_80 markup_90 markup_100
0    10.122    10.161       10.2
                    stock  start_date current_price minall maxall each_markup  \
0  BYTSU_ended_2021-09-25  2021-03-19          9.89   9.81   10.2   0.0389999

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.849     9.888     9.927     9.966    10.005    10.044    10.083

  markup_80 markup_90 markup_100
0    10.122    10.161       10.2
./ticker_data/ticker_data_2021-09-25 - Copy/BYTSW_ended_2021-09-25.csv
         Date  Open    High   Low   Close  Adj Close  Volume
0  2021-09-22  0.62  0.6399  0.57  0.6018     0.6018    8261
tolistdate: 0    2021-09-22
Name: Date, dtype: object
                    stock  start_date current_price minall  maxall  \
0  BYTSW_ended_2021-09-25  2021-09-22        0.6018   0.57  0.6399

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00699   0.57699   0.58398   0.59097   0.59796   0.60495   0.61194

  markup_70 markup_80 markup_90 markup_100
0   0.61893   0.62592   0.63291     0.6399
                    stock  start_date current_price minall  maxall  \
0  BYTSW_ended_2021-09-25  2021-09-22        0.6018   0.57  0.6399

  each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0     0.00699   0.57699   0.58398   0.59097   0.59796   0.60495   0.61194

  markup_70 markup_80 markup_90 markup_100
0   0.61893   0.62592   0.63291     0.6399
./ticker_data/ticker_data_2021-09-25 - Copy/BYTS_ended_2021-09-25.csv
          Date   Open   High    Low  Close  Adj Close  Volume
0   2021-05-10  9.910   9.91  9.800  9.800      9.800   17700
1   2021-05-11  9.997  10.00  9.800  9.997      9.997    6000
2   2021-05-12  9.800   9.82  9.755  9.755      9.755   12700
3   2021-05-13  9.760   9.77  9.750  9.770      9.770   14500
4   2021-05-14  9.790   9.79  9.750  9.750      9.750   18100
..         ...    ...    ...    ...    ...        ...     ...
65  2021-08-23  9.620   9.63  9.620  9.630      9.630  140000
66  2021-08-26  9.640   9.64  9.640  9.640      9.640   20000
67  2021-08-27  9.630   9.63  9.630  9.630      9.630   10000
68  2021-09-02  9.630   9.63  9.630  9.630      9.630  470000
69  2021-09-03  9.630   9.67  9.630  9.670      9.670   40000

[70 rows x 7 columns]
tolistdate: 0     2021-05-10
1     2021-05-11
2     2021-05-12
3     2021-05-13
4     2021-05-14
         ...
65    2021-08-23
66    2021-08-26
67    2021-08-27
68    2021-09-02
69    2021-09-03
Name: Date, Length: 70, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BYTS_ended_2021-09-25  2021-05-10          9.67    9.6  10.11   0.0509999

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.651     9.702     9.753     9.804     9.855     9.906     9.957

  markup_80 markup_90 markup_100
0    10.008    10.059      10.11
                   stock  start_date current_price minall maxall each_markup  \
0  BYTS_ended_2021-09-25  2021-05-10          9.67    9.6  10.11   0.0509999

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     9.651     9.702     9.753     9.804     9.855     9.906     9.957

  markup_80 markup_90 markup_100
0    10.008    10.059      10.11
./ticker_data/ticker_data_2021-09-25 - Copy/BZUN_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     2015-05-20  10.000000  10.000000  10.000000  10.000000  10.000000
1     2015-05-21  10.250000  10.890000   9.230000  10.440000  10.440000
2     2015-05-22  10.800000  11.220000  10.500000  11.080000  11.080000
3     2015-05-26  11.400000  13.700000  11.200000  12.780000  12.780000
4     2015-05-27  13.580000  14.770000  12.050000  12.240000  12.240000
...          ...        ...        ...        ...        ...        ...
1580  2021-08-30  22.500000  22.639999  21.590000  21.959999  21.959999
1581  2021-08-31  22.680000  24.080000  22.305000  24.080000  24.080000
1582  2021-09-01  24.010000  24.770000  23.780001  24.200001  24.200001
1583  2021-09-02  24.270000  24.770000  23.660000  24.270000  24.270000
1584  2021-09-03  24.030001  24.530001  23.700001  24.389999  24.389999

         Volume
0             0
1       9553400
2       2806600
3       4898900
4       4104300
...         ...
1580  120850000
1581  210410000
1582  122660000
1583   68020000
1584   59940000

[1585 rows x 7 columns]
tolistdate: 0       2015-05-20
1       2015-05-21
2       2015-05-22
3       2015-05-26
4       2015-05-27
           ...
1580    2021-08-30
1581    2021-08-31
1582    2021-09-01
1583    2021-09-02
1584    2021-09-03
Name: Date, Length: 1585, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  BZUN_ended_2021-09-25  2015-05-20         24.39      4  67.41       6.341

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.341    16.682    23.023    29.364    35.705    42.046    48.387

  markup_80 markup_90 markup_100
0    54.728    61.069      67.41
                   stock  start_date current_price minall maxall each_markup  \
0  BZUN_ended_2021-09-25  2015-05-20         24.39      4  67.41       6.341

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    10.341    16.682    23.023    29.364    35.705    42.046    48.387

  markup_80 markup_90 markup_100
0    54.728    61.069      67.41
./ticker_data/ticker_data_2021-09-25 - Copy/CAAS_ended_2021-09-25.csv
            Date  Open  High   Low  Close  Adj Close   Volume
0     2003-10-07  4.95  4.95  4.80   4.95   4.850668     6300
1     2003-10-08  4.90  4.95  4.90   4.95   4.850668     2200
2     2003-10-09  4.90  4.95  4.90   4.90   4.801672    17700
3     2003-10-10  5.00  5.00  4.90   4.90   4.801672    16600
4     2003-10-13  5.00  5.00  5.00   5.00   4.899665      600
...          ...   ...   ...   ...    ...        ...      ...
4504  2021-08-30  3.60  3.72  3.42   3.50   3.500000  4530000
4505  2021-08-31  3.52  3.61  3.47   3.53   3.530000  2420000
4506  2021-09-01  3.53  3.62  3.44   3.55   3.550000  3620000
4507  2021-09-02  3.54  3.68  3.50   3.56   3.560000  4910000
4508  2021-09-03  3.52  3.62  3.50   3.58   3.580000  1000000

[4509 rows x 7 columns]
tolistdate: 0       2003-10-07
1       2003-10-08
2       2003-10-09
3       2003-10-10
4       2003-10-13
           ...
4504    2021-08-30
4505    2021-08-31
4506    2021-09-01
4507    2021-09-02
4508    2021-09-03
Name: Date, Length: 4509, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  CAAS_ended_2021-09-25  2003-10-07          3.58   1.43  27.17       2.574

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.004     6.578     9.152    11.726      14.3    16.874    19.448

  markup_80 markup_90 markup_100
0    22.022    24.596      27.17
                   stock  start_date current_price minall maxall each_markup  \
0  CAAS_ended_2021-09-25  2003-10-07          3.58   1.43  27.17       2.574

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     4.004     6.578     9.152    11.726      14.3    16.874    19.448

  markup_80 markup_90 markup_100
0    22.022    24.596      27.17
./ticker_data/ticker_data_2021-09-25 - Copy/CABA_ended_2021-09-25.csv
           Date   Open    High     Low  Close  Adj Close    Volume
0    2019-10-25   9.00  10.000   8.580  10.00      10.00    971500
1    2019-10-28  10.25  10.670   9.990  10.01      10.01    285700
2    2019-10-29  10.01  10.780   9.590  10.51      10.51    151800
3    2019-10-30  10.53  10.790  10.280  10.65      10.65    107500
4    2019-10-31  10.64  10.740  10.110  10.50      10.50    115000
..          ...    ...     ...     ...    ...        ...       ...
463  2021-08-30  10.46  11.060   9.920  10.09      10.09  30600000
464  2021-08-31  10.20  10.367   9.915  10.18      10.18  19700000
465  2021-09-01  10.16  11.000  10.160  10.93      10.93  13480000
466  2021-09-02  10.90  11.665  10.820  11.07      11.07  16930000
467  2021-09-03  11.10  11.220  10.850  11.06      11.06   8130000

[468 rows x 7 columns]
tolistdate: 0      2019-10-25
1      2019-10-28
2      2019-10-29
3      2019-10-30
4      2019-10-31
          ...
463    2021-08-30
464    2021-08-31
465    2021-09-01
466    2021-09-02
467    2021-09-03
Name: Date, Length: 468, dtype: object
                   stock  start_date current_price minall maxall each_markup  \
0  CABA_ended_2021-09-25  2019-10-25         11.06   5.51  19.63       1.412

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.922     8.334     9.746    11.158     12.57    13.982    15.394

  markup_80 markup_90 markup_100
0    16.806    18.218      19.63
                   stock  start_date current_price minall maxall each_markup  \
0  CABA_ended_2021-09-25  2019-10-25         11.06   5.51  19.63       1.412

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0     6.922     8.334     9.746    11.158     12.57    13.982    15.394

  markup_80 markup_90 markup_100
0    16.806    18.218      19.63
./ticker_data/ticker_data_2021-09-25 - Copy/CAC_ended_2021-09-25.csv
            Date       Open       High        Low      Close  Adj Close  \
0     1999-12-31  11.166667  11.166667  11.166667  11.166667   5.556301
1     2000-01-03  11.000000  11.125000  10.833333  10.833333   5.390442
2     2000-01-04  11.000000  11.000000  10.791667  10.791667   5.369709
3     2000-01-05  10.791667  10.875000  10.791667  10.875000   5.411172
4     2000-01-06  10.916667  10.916667  10.791667  10.916667   5.431904
...          ...        ...        ...        ...        ...        ...
5444  2021-08-30  47.259998  47.259998  46.180000  46.320000  46.320000
5445  2021-08-31  46.459999  47.020000  46.130001  46.669998  46.669998
5446  2021-09-01  46.790001  46.880001  46.310001  46.880001  46.880001
5447  2021-09-02  46.919998  47.200001  46.500000  46.680000  46.680000
5448  2021-09-03  46.639999  46.880001  46.389999  46.759998  46.759998

       Volume
0        3000
1        3900
2         900
3         400
4        4500
...       ...
5444  3150000
5445  2140000
5446  2160000
5447  1950000
5448  1710000

[5449 rows x 7 columns]
tolistdate: 0       1999-12-31
1       2000-01-03
2       2000-01-04
3       2000-01-05
4       2000-01-06
           ...
5444    2021-08-30
5445    2021-08-31
5446    2021-09-01
5447    2021-09-02
5448    2021-09-03
Name: Date, Length: 5449, dtype: object
                  stock  start_date current_price minall maxall each_markup  \
0  CAC_ended_2021-09-25  1999-12-31         46.76   6.75  49.66       4.291

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.041    15.332    19.623    23.914    28.205    32.496    36.787

  markup_80 markup_90 markup_100
0    41.078    45.369      49.66
                  stock  start_date current_price minall maxall each_markup  \
0  CAC_ended_2021-09-25  1999-12-31         46.76   6.75  49.66       4.291

  markup_10 markup_20 markup_30 markup_40 markup_50 markup_60 markup_70  \
0    11.041    15.332    19.623    23.914    28.205    32.496    36.787

  markup_80 markup_90 markup_100
0    41.078    45.369      49.66
                    stock  start_date current_price    minall  maxall  \
0                       A  2005-09-27         19.37      1.45   63.27
0   AAME_ended_2021-09-25  1999-12-31          3.99      0.45   15.97
0   AAOI_ended_2021-09-25  2013-09-26          7.72         5  103.41
0   AAON_ended_2021-09-25  1999-12-31         67.21   1.18519   81.25
0   AAPL_ended_2021-09-25  1999-12-31         154.3  0.227143  154.98
..                    ...         ...           ...       ...     ...
0   BYTS_ended_2021-09-25  2021-05-10          9.67       9.6   10.11
0   BZUN_ended_2021-09-25  2015-05-20         24.39         4   67.41
0   CAAS_ended_2021-09-25  2003-10-07          3.58      1.43   27.17
0   CABA_ended_2021-09-25  2019-10-25         11.06      5.51   19.63
0    CAC_ended_2021-09-25  1999-12-31         46.76      6.75   49.66

   each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0        6.182     7.632    13.814    19.996    26.178     32.36    38.542
0        1.552     2.002     3.554     5.106     6.658      8.21     9.762
0        9.841    14.841    24.682    34.523    44.364    54.205    64.046
0      8.00648   9.19167   17.1981   25.2046   33.2111   41.2176   49.2241
0      15.4753   15.7024   31.1777    46.653   62.1283   77.6036   93.0789
..         ...       ...       ...       ...       ...       ...       ...
0    0.0509999     9.651     9.702     9.753     9.804     9.855     9.906
0        6.341    10.341    16.682    23.023    29.364    35.705    42.046
0        2.574     4.004     6.578     9.152    11.726      14.3    16.874
0        1.412     6.922     8.334     9.746    11.158     12.57    13.982
0        4.291    11.041    15.332    19.623    23.914    28.205    32.496

   markup_70 markup_80 markup_90 markup_100
0     44.724    50.906    57.088      63.27
0     11.314    12.866    14.418      15.97
0     73.887    83.728    93.569     103.41
0    57.2306    65.237   73.2435      81.25
0    108.554   124.029   139.505     154.98
..       ...       ...       ...        ...
0      9.957    10.008    10.059      10.11
0     48.387    54.728    61.069      67.41
0     19.448    22.022    24.596      27.17
0     15.394    16.806    18.218      19.63
0     36.787    41.078    45.369      49.66

[637 rows x 16 columns]

In [23]:
print(df1)

                    stock  start_date current_price    minall  maxall  \
0                       A  2005-09-27         19.37      1.45   63.27
0   AAME_ended_2021-09-25  1999-12-31          3.99      0.45   15.97
0   AAOI_ended_2021-09-25  2013-09-26          7.72         5  103.41
0   AAON_ended_2021-09-25  1999-12-31         67.21   1.18519   81.25
0   AAPL_ended_2021-09-25  1999-12-31         154.3  0.227143  154.98
..                    ...         ...           ...       ...     ...
0   BYTS_ended_2021-09-25  2021-05-10          9.67       9.6   10.11
0   BZUN_ended_2021-09-25  2015-05-20         24.39         4   67.41
0   CAAS_ended_2021-09-25  2003-10-07          3.58      1.43   27.17
0   CABA_ended_2021-09-25  2019-10-25         11.06      5.51   19.63
0    CAC_ended_2021-09-25  1999-12-31         46.76      6.75   49.66

   each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0        6.182     7.632    13.814    19.996    26.178     32.36    38.542
0        1.552     2.002     3.554     5.106     6.658      8.21     9.762
0        9.841    14.841    24.682    34.523    44.364    54.205    64.046
0      8.00648   9.19167   17.1981   25.2046   33.2111   41.2176   49.2241
0      15.4753   15.7024   31.1777    46.653   62.1283   77.6036   93.0789
..         ...       ...       ...       ...       ...       ...       ...
0    0.0509999     9.651     9.702     9.753     9.804     9.855     9.906
0        6.341    10.341    16.682    23.023    29.364    35.705    42.046
0        2.574     4.004     6.578     9.152    11.726      14.3    16.874
0        1.412     6.922     8.334     9.746    11.158     12.57    13.982
0        4.291    11.041    15.332    19.623    23.914    28.205    32.496

   markup_70 markup_80 markup_90 markup_100
0     44.724    50.906    57.088      63.27
0     11.314    12.866    14.418      15.97
0     73.887    83.728    93.569     103.41
0    57.2306    65.237   73.2435      81.25
0    108.554   124.029   139.505     154.98
..       ...       ...       ...        ...
0      9.957    10.008    10.059      10.11
0     48.387    54.728    61.069      67.41
0     19.448    22.022    24.596      27.17
0     15.394    16.806    18.218      19.63
0     36.787    41.078    45.369      49.66

[637 rows x 16 columns]

In [24]:
# print(df1)
df = df1.copy()
df['perc_from_ATH'] = df['current_price']/df['maxall']

In [25]:
print(df)

                    stock  start_date current_price    minall  maxall  \
0                       A  2005-09-27         19.37      1.45   63.27
0   AAME_ended_2021-09-25  1999-12-31          3.99      0.45   15.97
0   AAOI_ended_2021-09-25  2013-09-26          7.72         5  103.41
0   AAON_ended_2021-09-25  1999-12-31         67.21   1.18519   81.25
0   AAPL_ended_2021-09-25  1999-12-31         154.3  0.227143  154.98
..                    ...         ...           ...       ...     ...
0   BYTS_ended_2021-09-25  2021-05-10          9.67       9.6   10.11
0   BZUN_ended_2021-09-25  2015-05-20         24.39         4   67.41
0   CAAS_ended_2021-09-25  2003-10-07          3.58      1.43   27.17
0   CABA_ended_2021-09-25  2019-10-25         11.06      5.51   19.63
0    CAC_ended_2021-09-25  1999-12-31         46.76      6.75   49.66

   each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0        6.182     7.632    13.814    19.996    26.178     32.36    38.542
0        1.552     2.002     3.554     5.106     6.658      8.21     9.762
0        9.841    14.841    24.682    34.523    44.364    54.205    64.046
0      8.00648   9.19167   17.1981   25.2046   33.2111   41.2176   49.2241
0      15.4753   15.7024   31.1777    46.653   62.1283   77.6036   93.0789
..         ...       ...       ...       ...       ...       ...       ...
0    0.0509999     9.651     9.702     9.753     9.804     9.855     9.906
0        6.341    10.341    16.682    23.023    29.364    35.705    42.046
0        2.574     4.004     6.578     9.152    11.726      14.3    16.874
0        1.412     6.922     8.334     9.746    11.158     12.57    13.982
0        4.291    11.041    15.332    19.623    23.914    28.205    32.496

   markup_70 markup_80 markup_90 markup_100 perc_from_ATH
0     44.724    50.906    57.088      63.27      0.306148
0     11.314    12.866    14.418      15.97      0.249843
0     73.887    83.728    93.569     103.41     0.0746543
0    57.2306    65.237   73.2435      81.25        0.8272
0    108.554   124.029   139.505     154.98      0.995612
..       ...       ...       ...        ...           ...
0      9.957    10.008    10.059      10.11      0.956479
0     48.387    54.728    61.069      67.41      0.361816
0     19.448    22.022    24.596      27.17      0.131763
0     15.394    16.806    18.218      19.63      0.563423
0     36.787    41.078    45.369      49.66      0.941603

[637 rows x 17 columns]

In [36]:
# df.to_csv('C:/Users/malco/Desktop/Server Data 2/all_stock_price_info.csv')
print(pathtosave+'all_stock_price_info.csv')
df.to_csv(pathtosave+'all_stock_price_info.csv')

./ticker_data/ticker_data_2021-09-25_processed/all_stock_price_info.csv

In [31]:
# import datetime as dt
# df = pd.read_csv('C:/Users/malco/Desktop/Server Data 2/all stock price/A.csv')
# print(df)
# # df['Date'].apply(lambda x: dt.datetime.strptime(x, '%Y-%m-%d'))

In [32]:
# df['month_year'] = df['Date'].dt.to_period('M')
print(df)

                    stock  start_date current_price    minall  maxall  \
0                       A  2005-09-27         19.37      1.45   63.27
0   AAME_ended_2021-09-25  1999-12-31          3.99      0.45   15.97
0   AAOI_ended_2021-09-25  2013-09-26          7.72         5  103.41
0   AAON_ended_2021-09-25  1999-12-31         67.21   1.18519   81.25
0   AAPL_ended_2021-09-25  1999-12-31         154.3  0.227143  154.98
..                    ...         ...           ...       ...     ...
0   BYTS_ended_2021-09-25  2021-05-10          9.67       9.6   10.11
0   BZUN_ended_2021-09-25  2015-05-20         24.39         4   67.41
0   CAAS_ended_2021-09-25  2003-10-07          3.58      1.43   27.17
0   CABA_ended_2021-09-25  2019-10-25         11.06      5.51   19.63
0    CAC_ended_2021-09-25  1999-12-31         46.76      6.75   49.66

   each_markup markup_10 markup_20 markup_30 markup_40 markup_50 markup_60  \
0        6.182     7.632    13.814    19.996    26.178     32.36    38.542
0        1.552     2.002     3.554     5.106     6.658      8.21     9.762
0        9.841    14.841    24.682    34.523    44.364    54.205    64.046
0      8.00648   9.19167   17.1981   25.2046   33.2111   41.2176   49.2241
0      15.4753   15.7024   31.1777    46.653   62.1283   77.6036   93.0789
..         ...       ...       ...       ...       ...       ...       ...
0    0.0509999     9.651     9.702     9.753     9.804     9.855     9.906
0        6.341    10.341    16.682    23.023    29.364    35.705    42.046
0        2.574     4.004     6.578     9.152    11.726      14.3    16.874
0        1.412     6.922     8.334     9.746    11.158     12.57    13.982
0        4.291    11.041    15.332    19.623    23.914    28.205    32.496

   markup_70 markup_80 markup_90 markup_100 perc_from_ATH
0     44.724    50.906    57.088      63.27      0.306148
0     11.314    12.866    14.418      15.97      0.249843
0     73.887    83.728    93.569     103.41     0.0746543
0    57.2306    65.237   73.2435      81.25        0.8272
0    108.554   124.029   139.505     154.98      0.995612
..       ...       ...       ...        ...           ...
0      9.957    10.008    10.059      10.11      0.956479
0     48.387    54.728    61.069      67.41      0.361816
0     19.448    22.022    24.596      27.17      0.131763
0     15.394    16.806    18.218      19.63      0.563423
0     36.787    41.078    45.369      49.66      0.941603

[637 rows x 17 columns]