# Get All Stock available

https://pypi.org/project/yfinance/

In [1]:
import bs4 as bs
import pandas as pd
import numpy as np
import requests

# Temlate for all

In [2]:
import yfinance as yf

msft = yf.Ticker("MSFT")

# get stock info
msft.info

# # get historical market data
hist = msft.history(period="max")

# # show actions (dividends, splits)
msft.actions

# # show dividends
msft.dividends

# # show splits
# msft.splits

# # show financials
# msft.financials
# msft.quarterly_financials

# # show major holders
# msft.major_holders

# # show institutional holders
# msft.institutional_holders

# # show balance sheet
# msft.balance_sheet
# msft.quarterly_balance_sheet

# # show cashflow
# msft.cashflow
# msft.quarterly_cashflow

# # show earnings
# msft.earnings
# msft.quarterly_earnings

# # show sustainability
# msft.sustainability

# # show analysts recommendations
# msft.recommendations

# # show next event (earnings, etc)
# msft.calendar

# # show ISIN code - *experimental*
# # ISIN = International Securities Identification Number
# msft.isin

# # show options expirations
# msft.options

# # # get option chain for specific expiration
# # opt = msft.option_chain('YYYY-MM-DD')
# # # data available via: opt.calls, opt.puts
# msft.info

Date
2003-02-19    0.08
2003-10-15    0.16
2004-08-23    0.08
2004-11-15    3.08
2005-02-15    0.08
              ...
2020-08-19    0.51
2020-11-18    0.56
2021-02-17    0.56
2021-05-19    0.56
2021-08-18    0.56
Name: Dividends, Length: 71, dtype: float64

# Get Trading Data  (Quantitative)

In [5]:
data = yf.download(  # or pdr.get_data_yahoo(...
        # tickers list or string as well
        tickers = "AAPL",

        # use "period" instead of start/end
        # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        # (optional, default is '1mo')
        period = "1mo",

        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "15m",

        # group by ticker (to access via data['SPY'])
        # (optional, default is 'column')
        group_by = 'ticker',

        # adjust all OHLC automatically
        # (optional, default is False)
        auto_adjust = True,

        # download pre/post regular market hours data
        # (optional, default is False)
        prepost = True,

        # use threads for mass downloading? (True/False/Integer)
        # (optional, default is True)
        threads = True,

        # proxy URL scheme use use when downloading?
        # (optional, default is None)
        proxy = None
    )

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [3]:
data

NameError: name 'data' is not defined

# Get Qualitative Data

In [4]:
msft.info

{'zip': '98052-6399',
 'sector': 'Technology',
 'fullTimeEmployees': 181000,
 'longBusinessSummary': 'Microsoft Corporation develops, licenses, and supports software, services, devices, and solutions worldwide. Its Productivity and Business Processes segment offers Office, Exchange, SharePoint, Microsoft Teams, Office 365 Security and Compliance, and Skype for Business, as well as related Client Access Licenses (CAL); Skype, Outlook.com, OneDrive, and LinkedIn; and Dynamics 365, a set of cloud-based and on-premises business solutions for organizations and enterprise divisions. Its Intelligent Cloud segment licenses SQL, Windows Servers, Visual Studio, System Center, and related CALs; GitHub that provides a collaboration platform and code hosting service for developers; and Azure, a cloud platform. It also offers support services and Microsoft consulting services to assist customers in developing, deploying, and managing Microsoft server and desktop solutions; and training and certification on Microsoft products. Its More Personal Computing segment provides Windows original equipment manufacturer (OEM) licensing and other non-volume licensing of the Windows operating system; Windows Commercial, such as volume licensing of the Windows operating system, Windows cloud services, and other Windows commercial offerings; patent licensing; Windows Internet of Things; and MSN advertising. It also offers Surface, PC accessories, PCs, tablets, gaming and entertainment consoles, and other devices; Gaming, including Xbox hardware, and Xbox content and services; video games and third-party video game royalties; and Search, including Bing and Microsoft advertising. It sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online stores, and retail stores. It has collaborations with Dynatrace, Inc., Morgan Stanley, Micro Focus, WPP plc, ACI Worldwide, Inc., and iCIMS, Inc., as well as a strategic relationship with Avaya Holdings Corp. Microsoft Corporation was founded in 1975 and is headquartered in Redmond, Washington.',
 'city': 'Redmond',
 'phone': '425 882 8080',
 'state': 'WA',
 'country': 'United States',
 'companyOfficers': [],
 'website': 'http://www.microsoft.com',
 'maxAge': 1,
 'address1': 'One Microsoft Way',
 'industry': 'Software—Infrastructure',
 'ebitdaMargins': 0.48080003,
 'profitMargins': 0.36451998,
 'grossMargins': 0.68926,
 'operatingCashflow': 76740001792,
 'revenueGrowth': 0.213,
 'operatingMargins': 0.41595,
 'ebitda': 80815996928,
 'targetLowPrice': 280,
 'recommendationKey': 'buy',
 'grossProfits': 115856000000,
 'freeCashflow': 41337249792,
 'targetMedianPrice': 338,
 'currentPrice': 289.1,
 'earningsGrowth': 0.486,
 'currentRatio': 2.08,
 'returnOnAssets': 0.13761,
 'numberOfAnalystOpinions': 37,
 'targetMeanPrice': 336.28,
 'debtToEquity': 57.947,
 'returnOnEquity': 0.47079,
 'targetHighPrice': 411,
 'totalCash': 130256003072,
 'totalDebt': 82277998592,
 'totalRevenue': 168087994368,
 'totalCashPerShare': 17.333,
 'financialCurrency': 'USD',
 'revenuePerShare': 22.272,
 'quickRatio': 1.898,
 'recommendationMean': 1.7,
 'exchange': 'NMS',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'exchangeTimezoneName': 'America/New_York',
 'exchangeTimezoneShortName': 'EDT',
 'isEsgPopulated': False,
 'gmtOffSetMilliseconds': '-14400000',
 'quoteType': 'EQUITY',
 'symbol': 'MSFT',
 'messageBoardId': 'finmb_21835',
 'market': 'us_market',
 'annualHoldingsTurnover': None,
 'enterpriseToRevenue': 12.319,
 'beta3Year': None,
 'enterpriseToEbitda': 25.621,
 '52WeekChange': 0.3400513,
 'morningStarRiskRating': None,
 'forwardEps': 10.11,
 'revenueQuarterlyGrowth': None,
 'sharesOutstanding': 7514890240,
 'fundInceptionDate': None,
 'annualReportExpenseRatio': None,
 'totalAssets': None,
 'bookValue': 18.884,
 'sharesShort': 44204519,
 'sharesPercentSharesOut': 0.0058999998,
 'fundFamily': None,
 'lastFiscalYearEnd': 1625011200,
 'heldPercentInstitutions': 0.71692,
 'netIncomeToCommon': 61270999040,
 'trailingEps': 8.05,
 'lastDividendValue': None,
 'SandP52WeekChange': 0.26372707,
 'priceToBook': 15.309257,
 'heldPercentInsiders': 0.00079,
 'nextFiscalYearEnd': 1688083200,
 'yield': None,
 'mostRecentQuarter': 1625011200,
 'shortRatio': 2.05,
 'sharesShortPreviousMonthDate': 1628812800,
 'floatShares': 7506925463,
 'beta': 0.77893,
 'enterpriseValue': 2070620143616,
 'priceHint': 2,
 'threeYearAverageReturn': None,
 'lastSplitDate': None,
 'lastSplitFactor': None,
 'legalType': None,
 'lastDividendDate': None,
 'morningStarOverallRating': None,
 'earningsQuarterlyGrowth': 0.469,
 'priceToSalesTrailing12Months': 12.925104,
 'dateShortInterest': 1631664000,
 'pegRatio': 2.25,
 'ytdReturn': None,
 'forwardPE': 28.595451,
 'lastCapGain': None,
 'shortPercentOfFloat': 0.0058999998,
 'sharesShortPriorMonth': 41985444,
 'impliedSharesOutstanding': None,
 'category': None,
 'fiveYearAverageReturn': None,
 'previousClose': 281.92,
 'regularMarketOpen': 282.1217,
 'twoHundredDayAverage': 269.4305,
 'trailingAnnualDividendYield': 0.007945516,
 'payoutRatio': 0.272,
 'volume24Hr': None,
 'regularMarketDayHigh': 289.98,
 'navPrice': None,
 'averageDailyVolume10Day': 26523900,
 'regularMarketPreviousClose': 281.92,
 'fiftyDayAverage': 297.6562,
 'trailingAnnualDividendRate': 2.24,
 'open': 282.1217,
 'toCurrency': None,
 'averageVolume10days': 26523900,
 'expireDate': None,
 'algorithm': None,
 'dividendRate': 2.48,
 'exDividendDate': 1637107200,
 'circulatingSupply': None,
 'startDate': None,
 'regularMarketDayLow': 281.31,
 'currency': 'USD',
 'trailingPE': 35.913044,
 'regularMarketVolume': 27421895,
 'lastMarket': None,
 'maxSupply': None,
 'openInterest': None,
 'marketCap': 2172554838016,
 'volumeAllCurrencies': None,
 'strikePrice': None,
 'averageVolume': 23017260,
 'dayLow': 281.31,
 'ask': 288.6,
 'askSize': 800,
 'volume': 27421895,
 'fiftyTwoWeekHigh': 305.84,
 'fromCurrency': None,
 'fiveYearAvgDividendYield': 1.48,
 'fiftyTwoWeekLow': 199.62,
 'bid': 288.54,
 'tradeable': False,
 'dividendYield': 0.0088,
 'bidSize': 900,
 'dayHigh': 289.98,
 'regularMarketPrice': 289.1,
 'logo_url': 'https://logo.clearbit.com/microsoft.com'}

In [5]:
hist = msft.history(period="max")
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1986-03-13,0.056001,0.064236,0.056001,0.061491,1031788800,0.0,0.0
1986-03-14,0.061491,0.064785,0.061491,0.063687,308160000,0.0,0.0
1986-03-17,0.063687,0.065334,0.063687,0.064785,133171200,0.0,0.0
1986-03-18,0.064785,0.065334,0.062589,0.063138,67766400,0.0,0.0
1986-03-19,0.063138,0.063687,0.061491,0.062040,47894400,0.0,0.0
...,...,...,...,...,...,...,...
2021-09-27,296.140015,296.470001,292.940002,294.170013,23571700,0.0,0.0
2021-09-28,289.799988,290.779999,282.750000,283.519989,43186200,0.0,0.0
2021-09-29,285.100006,286.769989,283.010010,284.000000,26353700,0.0,0.0
2021-09-30,285.709991,287.829987,281.619995,281.920013,32325800,0.0,0.0
2021-10-01,282.121704,289.980011,281.309998,289.100006,27421895,0.0,0.0

In [6]:
msft.actions

            Dividends  Stock Splits
Date
1987-09-21       0.00           2.0
1990-04-16       0.00           2.0
1991-06-27       0.00           1.5
1992-06-15       0.00           1.5
1994-05-23       0.00           2.0
...               ...           ...
2020-08-19       0.51           0.0
2020-11-18       0.56           0.0
2021-02-17       0.56           0.0
2021-05-19       0.56           0.0
2021-08-18       0.56           0.0

[80 rows x 2 columns]

In [7]:
msft.dividends

Date
2003-02-19    0.08
2003-10-15    0.16
2004-08-23    0.08
2004-11-15    3.08
2005-02-15    0.08
              ...
2020-08-19    0.51
2020-11-18    0.56
2021-02-17    0.56
2021-05-19    0.56
2021-08-18    0.56
Name: Dividends, Length: 71, dtype: float64

In [8]:
msft.splits

Date
1987-09-21    2.0
1990-04-16    2.0
1991-06-27    1.5
1992-06-15    1.5
1994-05-23    2.0
1996-12-09    2.0
1998-02-23    2.0
1999-03-29    2.0
2003-02-18    2.0
Name: Stock Splits, dtype: float64

In [9]:
msft.financials

,2021-06-30,2020-06-30,2019-06-30,2018-06-30
Research Development,2.0716e+10,1.9269e+10,1.6876e+10,1.4726e+10
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,7.1102e+10,5.3036e+10,4.3688e+10,3.6474e+10
Minority Interest,None,None,None,None
Net Income,6.1271e+10,4.4281e+10,3.924e+10,1.6571e+10
Selling General Administrative,2.5224e+10,2.4523e+10,2.3098e+10,2.2223e+10
Gross Profit,1.15856e+11,9.6937e+10,8.2933e+10,7.2007e+10
Ebit,6.9916e+10,5.3145e+10,4.2959e+10,3.5058e+10
Operating Income,6.9916e+10,5.3145e+10,4.2959e+10,3.5058e+10
Other Operating Expenses,None,None,None,None
Interest Expense,-2.33e+09,-2.591e+09,-2.686e+09,-2.733e+09
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,9.831e+09,8.755e+09,4.448e+09,1.9903e+10
Total Revenue,1.68088e+11,1.43015e+11,1.25843e+11,1.1036e+11
Total Operating Expenses,9.8172e+10,8.987e+10,8.2884e+10,7.5302e+10
Cost Of Revenue,5.2232e+10,4.6078e+10,4.291e+10,3.8353e+10
Total Other Income Expense Net,1.186e+09,-1.09e+08,7.29e+08,1.416e+09
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,6.1271e+10,4.4281e+10,3.924e+10,1.6571e+10
Net Income Applicable To Common Shares,6.1271e+10,4.4281e+10,3.924e+10,1.6571e+10

In [10]:
msft.quarterly_financials

,2021-06-30,2021-03-31,2020-12-31,2020-09-30
Research Development,5.687e+09,5.204e+09,4.899e+09,4.926e+09
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,1.9405e+10,1.7236e+10,1.8337e+10,1.6124e+10
Minority Interest,None,None,None,None
Net Income,1.6458e+10,1.5457e+10,1.5463e+10,1.3893e+10
Selling General Administrative,7.379e+09,6.409e+09,6.086e+09,5.35e+09
Gross Profit,3.2161e+10,2.8661e+10,2.8882e+10,2.6152e+10
Ebit,1.9095e+10,1.7048e+10,1.7897e+10,1.5876e+10
Operating Income,1.9095e+10,1.7048e+10,1.7897e+10,1.5876e+10
Other Operating Expenses,None,None,None,None
Interest Expense,-5.49e+08,-6.28e+08,-5.68e+08,-5.85e+08
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,2.947e+09,1.779e+09,2.874e+09,2.231e+09
Total Revenue,4.6152e+10,4.1706e+10,4.3076e+10,3.7154e+10
Total Operating Expenses,2.7057e+10,2.4658e+10,2.5179e+10,2.1278e+10
Cost Of Revenue,1.3991e+10,1.3045e+10,1.4194e+10,1.1002e+10
Total Other Income Expense Net,3.1e+08,1.88e+08,4.4e+08,2.48e+08
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,1.6458e+10,1.5457e+10,1.5463e+10,1.3893e+10
Net Income Applicable To Common Shares,1.6458e+10,1.5457e+10,1.5463e+10,1.3893e+10

In [11]:
msft.quarterly_financials

,2021-06-30,2021-03-31,2020-12-31,2020-09-30
Research Development,5.687e+09,5.204e+09,4.899e+09,4.926e+09
Effect Of Accounting Charges,None,None,None,None
Income Before Tax,1.9405e+10,1.7236e+10,1.8337e+10,1.6124e+10
Minority Interest,None,None,None,None
Net Income,1.6458e+10,1.5457e+10,1.5463e+10,1.3893e+10
Selling General Administrative,7.379e+09,6.409e+09,6.086e+09,5.35e+09
Gross Profit,3.2161e+10,2.8661e+10,2.8882e+10,2.6152e+10
Ebit,1.9095e+10,1.7048e+10,1.7897e+10,1.5876e+10
Operating Income,1.9095e+10,1.7048e+10,1.7897e+10,1.5876e+10
Other Operating Expenses,None,None,None,None
Interest Expense,-5.49e+08,-6.28e+08,-5.68e+08,-5.85e+08
Extraordinary Items,None,None,None,None
Non Recurring,None,None,None,None
Other Items,None,None,None,None
Income Tax Expense,2.947e+09,1.779e+09,2.874e+09,2.231e+09
Total Revenue,4.6152e+10,4.1706e+10,4.3076e+10,3.7154e+10
Total Operating Expenses,2.7057e+10,2.4658e+10,2.5179e+10,2.1278e+10
Cost Of Revenue,1.3991e+10,1.3045e+10,1.4194e+10,1.1002e+10
Total Other Income Expense Net,3.1e+08,1.88e+08,4.4e+08,2.48e+08
Discontinued Operations,None,None,None,None
Net Income From Continuing Ops,1.6458e+10,1.5457e+10,1.5463e+10,1.3893e+10
Net Income Applicable To Common Shares,1.6458e+10,1.5457e+10,1.5463e+10,1.3893e+10

In [12]:
msft.institutional_holders

,Holder,Shares,Date Reported,% Out,Value
0,"Vanguard Group, Inc. (The)",610974647,2021-06-29,0.0813,165513031872
1,Blackrock Inc.,505662500,2021-06-29,0.0673,136983971250
2,State Street Corporation,294824958,2021-06-29,0.0392,79868081122
3,"FMR, LLC",218007132,2021-06-29,0.0290,59058132058
4,Price (T.Rowe) Associates Inc,192408922,2021-06-29,0.0256,52123576969
5,"Geode Capital Management, LLC",123322145,2021-06-29,0.0164,33407969080
6,Capital World Investors,110830050,2021-06-29,0.0147,30023860545
7,Capital Research Global Investors,94576657,2021-06-29,0.0126,25620816381
8,Capital International Investors,92898047,2021-06-29,0.0124,25166080932
9,Northern Trust Corporation,88583941,2021-06-29,0.0118,23997389616

In [13]:
msft.balance_sheet

,2021-06-30,2020-06-30,2019-06-30,2018-06-30
Intangible Assets,7.800000e+09,7.038000e+09,7.750000e+09,8.053000e+09
Total Liab,1.917910e+11,1.830070e+11,1.842260e+11,1.761300e+11
Total Stockholder Equity,1.419880e+11,1.183040e+11,1.023300e+11,8.271800e+10
Other Current Liab,5.261200e+10,4.600100e+10,4.586000e+10,3.819500e+10
Total Assets,3.337790e+11,3.013110e+11,2.865560e+11,2.588480e+11
Common Stock,8.311100e+10,8.055200e+10,7.852000e+10,7.122300e+10
Other Current Assets,1.347100e+10,1.151700e+10,1.013300e+10,6.855000e+09
Retained Earnings,5.705500e+10,3.456600e+10,2.415000e+10,1.368200e+10
Other Liab,3.168100e+10,3.449200e+10,3.569900e+10,3.570700e+10
Good Will,4.971100e+10,4.335100e+10,4.202600e+10,3.568300e+10
Treasury Stock,1.822000e+09,3.186000e+09,-3.400000e+08,-2.187000e+09
Other Assets,1.507500e+10,1.313800e+10,1.472300e+10,7.442000e+09
Cash,1.422400e+10,1.357600e+10,1.135600e+10,1.194600e+10
Total Current Liabilities,8.865700e+10,7.231000e+10,6.942000e+10,5.848800e+10
Deferred Long Term Asset Charges,7.181000e+09,6.405000e+09,7.536000e+09,1.369000e+09
Short Long Term Debt,8.072000e+09,3.749000e+09,5.516000e+09,3.998000e+09
Other Stockholder Equity,1.822000e+09,3.186000e+09,-3.400000e+08,-2.187000e+09
Property Plant Equipment,7.080300e+10,5.290400e+10,4.385600e+10,3.614600e+10
Total Current Assets,1.844060e+11,1.819150e+11,1.755520e+11,1.696620e+11
Long Term Investments,5.984000e+09,2.965000e+09,2.649000e+09,1.862000e+09
Net Tangible Assets,8.447700e+10,6.791500e+10,5.255400e+10,3.898200e+10
Short Term Investments,1.160320e+11,1.229160e+11,1.224760e+11,1.217180e+11
Net Receivables,3.804300e+10,3.201100e+10,2.952400e+10,2.648100e+10
Long Term Debt,5.007400e+10,5.957800e+10,6.666200e+10,7.224200e+10
Inventory,2.636000e+09,1.895000e+09,2.063000e+09,2.662000e+09
Accounts Payable,1.516300e+10,1.253000e+10,9.382000e+09,8.617000e+09

In [14]:
msft.quarterly_balance_sheet

,2021-06-30,2021-03-31,2020-12-31,2020-09-30
Intangible Assets,7.800000e+09,8.127000e+09,6.555000e+09,6.923000e+09
Total Liab,1.917910e+11,1.743740e+11,1.739010e+11,1.776090e+11
Total Stockholder Equity,1.419880e+11,1.345050e+11,1.302360e+11,1.233920e+11
Other Current Liab,5.261200e+10,4.006900e+10,3.992600e+10,4.299600e+10
Total Assets,3.337790e+11,3.088790e+11,3.041370e+11,3.010010e+11
Common Stock,8.311100e+10,8.230800e+10,8.189600e+10,8.108900e+10
Other Current Assets,1.347100e+10,1.203400e+10,1.274800e+10,1.357200e+10
Retained Earnings,5.705500e+10,5.073500e+10,4.497300e+10,3.919300e+10
Other Liab,3.168100e+10,3.160100e+10,3.158500e+10,3.317400e+10
Good Will,4.971100e+10,4.969800e+10,4.421900e+10,4.389000e+10
Treasury Stock,1.822000e+09,1.462000e+09,3.367000e+09,3.110000e+09
Other Assets,1.507500e+10,1.442700e+10,1.356100e+10,1.303400e+10
Cash,1.422400e+10,1.370200e+10,1.443200e+10,1.720500e+10
Total Current Liabilities,8.865700e+10,7.219300e+10,6.748600e+10,7.005600e+10
Deferred Long Term Asset Charges,7.181000e+09,NaN,NaN,NaN
Short Long Term Debt,8.072000e+09,8.051000e+09,5.387000e+09,6.497000e+09
Other Stockholder Equity,1.822000e+09,1.462000e+09,3.367000e+09,3.110000e+09
Property Plant Equipment,7.080300e+10,6.561800e+10,6.203500e+10,5.697400e+10
Total Current Assets,1.844060e+11,1.656140e+11,1.739730e+11,1.770770e+11
Long Term Investments,5.984000e+09,5.395000e+09,3.794000e+09,3.103000e+09
Net Tangible Assets,8.447700e+10,7.668000e+10,7.946200e+10,7.257900e+10
Short Term Investments,1.160320e+11,1.113110e+11,1.175570e+11,1.207440e+11
Net Receivables,3.804300e+10,2.632200e+10,2.731200e+10,2.285100e+10
Long Term Debt,5.007400e+10,5.000700e+10,5.513600e+10,5.705500e+10
Inventory,2.636000e+09,2.245000e+09,1.924000e+09,2.705000e+09
Accounts Payable,1.516300e+10,1.341200e+10,1.277000e+10,1.250900e+10

In [15]:
msft.cashflow

,2021-06-30,2020-06-30,2019-06-30,2018-06-30
Investments,2.876000e+09,6.980000e+09,5.400000e+08,6.557000e+09
Change To Liabilities,7.431000e+09,5.230000e+09,4.694000e+09,7.070000e+09
Total Cashflows From Investing Activities,-2.757700e+10,-1.222300e+10,-1.577300e+10,-6.061000e+09
Net Borrowings,-3.750000e+09,-5.518000e+09,-4.000000e+09,-1.020100e+10
Total Cash From Financing Activities,-4.848600e+10,-4.603100e+10,-3.688700e+10,-3.359000e+10
Change To Operating Activities,1.160000e+09,-6.730000e+08,-1.542000e+09,-4.590000e+08
Issuance Of Stock,1.693000e+09,1.343000e+09,1.142000e+09,1.002000e+09
Net Income,6.127100e+10,4.428100e+10,3.924000e+10,1.657100e+10
Change In Cash,6.480000e+08,2.220000e+09,-5.900000e+08,4.283000e+09
Repurchase Of Stock,-2.738500e+10,-2.296800e+10,-1.954300e+10,-1.072100e+10
Effect Of Exchange Rate,-2.900000e+07,-2.010000e+08,-1.150000e+08,5.000000e+07
Total Cash From Operating Activities,7.674000e+10,6.067500e+10,5.218500e+10,4.388400e+10
Depreciation,1.090000e+10,1.230000e+10,1.160000e+10,9.900000e+09
Other Cashflows From Investing Activities,-9.220000e+08,-1.241000e+09,-1.241000e+09,-9.800000e+07
Dividends Paid,-1.652100e+10,-1.513700e+10,-1.381100e+10,-1.269900e+10
Change To Inventory,-7.370000e+08,1.680000e+08,5.970000e+08,-4.650000e+08
Change To Account Receivables,-6.481000e+09,-2.577000e+09,-2.812000e+09,-3.862000e+09
Other Cashflows From Financing Activities,-2.523000e+09,-3.751000e+09,-6.750000e+08,-9.710000e+08
Change To Netincome,5.505000e+09,5.577000e+09,-2.521000e+09,-3.054000e+09
Capital Expenditures,-2.062200e+10,-1.544100e+10,-1.392500e+10,-1.163200e+10

In [16]:
msft.quarterly_cashflow

,2021-06-30,2021-03-31,2020-12-31,2020-09-30
Investments,-4.334000e+09,2.517000e+09,2.593000e+09,2.100000e+09
Change To Liabilities,1.301400e+10,3.600000e+08,-3.194000e+09,-2.749000e+09
Total Cashflows From Investing Activities,-1.085300e+10,-9.684000e+09,-1.669000e+09,-5.371000e+09
Total Cash From Financing Activities,-1.137100e+10,-1.319200e+10,-1.363400e+10,-1.028900e+10
Change To Operating Activities,7.990000e+08,1.305000e+09,1.879000e+09,-2.823000e+09
Issuance Of Stock,4.500000e+08,3.960000e+08,3.020000e+08,5.450000e+08
Net Income,1.645800e+10,1.545700e+10,1.546300e+10,1.389300e+10
Change In Cash,5.220000e+08,-7.300000e+08,-2.773000e+09,3.629000e+09
Repurchase Of Stock,-7.177000e+09,-6.930000e+09,-6.535000e+09,-6.743000e+09
Effect Of Exchange Rate,3.600000e+07,-3.300000e+07,1.400000e+07,-4.600000e+07
Total Cash From Operating Activities,2.271000e+10,2.217900e+10,1.251600e+10,1.933500e+10
Depreciation,2.558000e+09,2.936000e+09,2.761000e+09,2.645000e+09
Other Cashflows From Investing Activities,4.340000e+08,4.000000e+08,3.270000e+08,-2.083000e+09
Dividends Paid,-4.214000e+09,-4.221000e+09,-4.230000e+09,-3.856000e+09
Change To Inventory,-3.880000e+08,-3.290000e+08,7.880000e+08,-8.080000e+08
Change To Account Receivables,-1.160600e+10,2.900000e+08,-4.008000e+09,8.843000e+09
Other Cashflows From Financing Activities,-4.300000e+08,-1.937000e+09,7.900000e+07,-2.350000e+08
Change To Netincome,1.907000e+09,1.086000e+09,1.195000e+09,1.317000e+09
Capital Expenditures,-6.452000e+09,-5.089000e+09,-4.174000e+09,-4.907000e+09
Net Borrowings,NaN,-5.000000e+08,-3.250000e+09,-3.250000e+09

In [17]:
msft.earnings

           Revenue     Earnings
Year
2018  110360000000  16571000000
2019  125843000000  39240000000
2020  143015000000  44281000000
2021  168088000000  61271000000

In [18]:
msft.quarterly_earnings

             Revenue     Earnings
Quarter
3Q2020   37154000000  13893000000
4Q2020   43076000000  15463000000
1Q2021   41706000000  15457000000
2Q2021   46152000000  16458000000

In [19]:
msft.sustainability

                                     Value
2021-9
palmOil                              False
controversialWeapons                 False
gambling                             False
socialScore                           8.06
nuclear                              False
furLeather                           False
alcoholic                            False
gmo                                  False
catholic                             False
socialPercentile                      None
peerCount                               99
governanceScore                       4.73
environmentPercentile                 None
animalTesting                        False
tobacco                              False
totalEsg                             13.26
highestControversy                       3
esgPerformance                  UNDER_PERF
coal                                 False
pesticides                           False
adult                                False
percentile                            5.64
peerGroup              Software & Services
smallArms                            False
environmentScore                      0.46
governancePercentile                  None
militaryContract                     False

In [20]:
msft.recommendations

                               Firm       To Grade From Grade Action
Date
2012-03-16 08:19:00  Argus Research            Buy                up
2012-03-19 14:00:00  Hilliard Lyons  Long-Term Buy              main
2012-03-22 07:03:00  Morgan Stanley     Overweight              main
2012-04-03 11:53:00             UBS            Buy              main
2012-04-20 06:18:00   Deutsche Bank            Buy              main
...                             ...            ...        ...    ...
2021-07-28 14:54:54   Credit Suisse     Outperform              main
2021-07-29 10:53:54       JP Morgan     Overweight              main
2021-08-20 18:26:16         Wedbush     Outperform              main
2021-09-14 12:12:00  Morgan Stanley     Overweight              main
2021-09-17 13:09:25        Barclays     Overweight              main

[347 rows x 4 columns]

In [21]:
msft.calendar

                                    0                    1
Earnings Date     2021-10-25 10:59:00  2021-10-29 12:00:00
Earnings Average                 2.07                 2.07
Earnings Low                     2.03                 2.03
Earnings High                    2.17                 2.17
Revenue Average           43981200000          43981200000
Revenue Low               43658900000          43658900000
Revenue High              44767000000          44767000000

In [22]:
# ISIN = International Securities Identification Number
# ISIN
msft.isin

'US5949181045'

In [29]:
msft.options

('2021-06-18',
 '2021-07-16',
 '2021-09-17',
 '2022-01-21',
 '2022-03-18',
 '2022-06-17',
 '2022-09-16',
 '2023-01-20')

In [6]:
opt = msft.option_chain('2021-06-18')
type(opt)

yfinance.ticker.Options

In [15]:
opt.calls

,contractSymbol,lastTradeDate,strike,lastPrice,bid,ask,change,percentChange,volume,openInterest,impliedVolatility,inTheMoney,contractSize,currency
0,MSFT210618C00065000,2020-11-09 14:45:17,65.0,160.70,0.0,0.00,0.0,0.0,1,0,0.000010,True,REGULAR,USD
1,MSFT210618C00070000,2020-11-09 14:45:17,70.0,155.70,0.0,0.00,0.0,0.0,1,0,0.000010,True,REGULAR,USD
2,MSFT210618C00075000,2020-11-09 14:45:17,75.0,150.70,0.0,0.00,0.0,0.0,1,0,0.000010,True,REGULAR,USD
3,MSFT210618C00080000,2020-11-09 14:45:17,80.0,144.95,0.0,0.00,0.0,0.0,2,0,0.000010,True,REGULAR,USD
4,MSFT210618C00085000,2020-11-09 14:45:17,85.0,140.70,0.0,0.00,0.0,0.0,1,0,0.000010,True,REGULAR,USD
5,MSFT210618C00090000,2020-11-09 14:45:17,90.0,135.70,0.0,0.00,0.0,0.0,2,0,0.000010,True,REGULAR,USD
6,MSFT210618C00095000,2020-09-21 14:40:46,95.0,102.00,120.3,120.85,0.0,0.0,2,121,0.000010,True,REGULAR,USD
7,MSFT210618C00100000,2020-11-10 19:27:04,100.0,110.69,0.0,0.00,0.0,0.0,5,0,0.000010,True,REGULAR,USD
8,MSFT210618C00105000,2020-11-10 17:13:02,105.0,108.00,0.0,0.00,0.0,0.0,1,0,0.000010,True,REGULAR,USD
9,MSFT210618C00110000,2020-11-06 18:45:09,110.0,114.46,0.0,0.00,0.0,0.0,4,0,0.000010,True,REGULAR,USD
10,MSFT210618C00115000,2020-11-05 20:01:57,115.0,109.00,0.0,0.00,0.0,0.0,5,0,0.000010,True,REGULAR,USD
11,MSFT210618C00120000,2020-11-09 18:47:18,120.0,102.85,0.0,0.00,0.0,0.0,6,0,0.000010,True,REGULAR,USD
12,MSFT210618C00125000,2020-11-09 15:07:30,125.0,101.15,0.0,0.00,0.0,0.0,4,0,0.000010,True,REGULAR,USD
13,MSFT210618C00130000,2020-11-06 16:14:12,130.0,92.33,0.0,0.00,0.0,0.0,1,0,0.000010,True,REGULAR,USD
14,MSFT210618C00135000,2020-11-09 20:50:38,135.0,76.40,0.0,0.00,0.0,0.0,3,0,0.000010,True,REGULAR,USD
15,MSFT210618C00140000,2020-11-09 14:46:49,140.0,86.72,0.0,0.00,0.0,0.0,1,0,0.000010,True,REGULAR,USD
16,MSFT210618C00145000,2020-11-05 16:20:49,145.0,78.94,0.0,0.00,0.0,0.0,5,0,0.000010,True,REGULAR,USD
17,MSFT210618C00150000,2020-11-10 20:11:28,150.0,62.61,0.0,0.00,0.0,0.0,12,0,0.000010,True,REGULAR,USD
18,MSFT210618C00155000,2020-11-10 20:33:41,155.0,58.60,0.0,0.00,0.0,0.0,18,0,0.000010,True,REGULAR,USD
19,MSFT210618C00160000,2020-11-10 20:08:45,160.0,54.30,0.0,0.00,0.0,0.0,5,0,0.000010,True,REGULAR,USD
20,MSFT210618C00165000,2020-11-10 20:45:46,165.0,50.35,0.0,0.00,0.0,0.0,2,0,0.000010,True,REGULAR,USD
21,MSFT210618C00170000,2020-11-10 19:17:22,170.0,45.70,0.0,0.00,0.0,0.0,22,0,0.000010,True,REGULAR,USD
22,MSFT210618C00175000,2020-11-09 14:39:13,175.0,43.10,0.0,0.00,0.0,0.0,9,0,0.000010,True,REGULAR,USD
23,MSFT210618C00180000,2020-11-10 20:02:43,180.0,38.00,0.0,0.00,0.0,0.0,69,0,0.000010,True,REGULAR,USD
24,MSFT210618C00185000,2020-11-10 19:12:35,185.0,34.70,0.0,0.00,0.0,0.0,34,0,0.000010,True,REGULAR,USD
25,MSFT210618C00190000,2020-11-10 20:33:21,190.0,31.58,0.0,0.00,0.0,0.0,4519,0,0.000010,True,REGULAR,USD
26,MSFT210618C00195000,2020-11-10 20:38:34,195.0,28.60,0.0,0.00,0.0,0.0,18,0,0.000010,True,REGULAR,USD
27,MSFT210618C00200000,2020-11-10 20:52:36,200.0,25.10,0.0,0.00,0.0,0.0,96,0,0.000010,True,REGULAR,USD
28,MSFT210618C00205000,2020-11-10 20:00:29,205.0,22.43,0.0,0.00,0.0,0.0,163,0,0.000010,True,REGULAR,USD
29,MSFT210618C00210000,2020-11-10 20:47:30,210.0,20.15,0.0,0.00,0.0,0.0,347,0,0.000010,True,REGULAR,USD
30,MSFT210618C00215000,2020-11-10 20:42:42,215.0,17.85,0.0,0.00,0.0,0.0,155,0,0.000010,True,REGULAR,USD
31,MSFT210618C00220000,2020-11-10 20:59:37,220.0,15.69,0.0,0.00,0.0,0.0,340,0,0.000010,True,REGULAR,USD
32,MSFT210618C00225000,2020-11-10 20:14:08,225.0,13.50,0.0,0.00,0.0,0.0,144,0,0.000010,True,REGULAR,USD
33,MSFT210618C00230000,2020-11-10 20:40:25,230.0,11.90,0.0,0.00,0.0,0.0,2273,0,0.000010,True,REGULAR,USD
34,MSFT210618C00235000,2020-11-10 20:44:12,235.0,10.55,0.0,0.00,0.0,0.0,344,0,0.000010,True,REGULAR,USD
35,MSFT210618C00240000,2020-11-10 20:52:29,240.0,9.15,0.0,0.00,0.0,0.0,160,0,0.000010,True,REGULAR,USD
36,MSFT210618C00245000,2020-11-10 20:55:13,245.0,7.80,0.0,0.00,0.0,0.0,16,0,0.000010,True,REGULAR,USD
37,MSFT210618C00250000,2020-11-10 20:54:22,250.0,6.79,0.0,0.00,0.0,0.0,563,0,0.000010,True,REGULAR,USD
38,MSFT210618C00255000,2020-11-10 19:57:36,255.0,5.75,0.0,0.00,0.0,0.0,17,0,0.031260,False,REGULAR,USD
39,MSFT210618C00260000,2020-11-10 20:37:49,260.0,4.90,0.0,0.00,0.0,0.0,66,0,0.062509,False,REGULAR,USD
40,MSFT210618C00265000,2020-11-10 17:53:11,265.0,4.55,0.0,0.00,0.0,0.0,21,0,0.062509,False,REGULAR,USD
41,MSFT210618C00270000,2020-11-10 19:17:08,270.0,3.63,0.0,0.00,0.0,0.0,31,0,0.125009,False,REGULAR,USD
42,MSFT210618C00275000,2020-11-10 17:06:46,275.0,3.20,0.0,0.00,0.0,0.0,9,0,0.125009,False,REGULAR,USD
43,MSFT210618C00280000,2020-11-10 19:23:41,280.0,2.65,0.0,0.00,0.0,0.0,71,0,0.125009,False,REGULAR,USD
44,MSFT210618C00285000,2020-11-06 15:13:54,285.0,3.92,0.0,0.00,0.0,0.0,13,0,0.125009,False,REGULAR,USD
45,MSFT210618C00290000,2020-11-06 20:06:55,290.0,3.29,0.0,0.00,0.0,0.0,2,0,0.125009,False,REGULAR,USD
46,MSFT210618C00295000,2020-11-06 15:10:33,295.0,2.43,0.0,0.00,0.0,0.0,3,0,0.250007,False,REGULAR,USD
47,MSFT210618C00300000,2020-11-10 20:46:37,300.0,1.60,0.0,0.00,0.0,0.0,12,0,0.250007,False,REGULAR,USD
48,MSFT210618C00310000,2020-11-10 18:15:18,310.0,1.29,0.0,0.00,0.0,0.0,10,0,0.250007,False,REGULAR,USD
49,MSFT210618C00320000,2020-11-10 18:03:48,320.0,1.10,0.0,0.00,0.0,0.0,81,0,0.250007,False,REGULAR,USD

In [16]:
opt.calls.to_csv('AAPL_options.csv')